### ISSUE TITLE
Are initial_max_stream_id_bidi/uni examples correct?

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#1000]
"This value MUST be a valid bidirectional stream ID for a peer-initiated stream (that is, the two least significant bits are set to 0 by a server and to 1 by a client)."
Should this be other way around? the two least significant bits of initial_max_stream_id_bidi should be set to 1 by a server, because that is a valid stream ID for its peer, i.e. a client?

There is a similar issue for initial_max_stream_id_uni.

**Comment by ddragana** [comment]
Sorry, I accidentally looked at a older version of draft.

**Comment by martinthomson** [comment]
And thus does issue #1000 pass.  Ignominiously.  How apt.

**Comment by janaiyengar** [comment]
Various dictionaries define "igominous" as shameful or disgraceful, which is a bit harsh :-) Nevertheless, indifference to the passage of this benchmark is welcome.
