### ISSUE TITLE
Appendix on GQUIC transition

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#1006]
We're pretty close to settling on a wire image, I think. It would be useful for the transport draft (and eventually the RFC) to have an appendix covering issues with simultaneous support of GQUIC versions and QUIC v1.

I believe all the entities actually trying to support GQUIC are heavily involved in the working group. However, I imagine there are quite a lot of middleboxes out there doing some basic ID/classification (if not more) on GQUIC today, and will need some guide on how to simultaneously handle two packet header formats, etc.

If people are opposed to an appendix, I suppose a short-lived internet draft would also get the job done. In any case, I'd like to see a placeholder sooner rather than later.

**Comment by ianswett** [comment]
I suspect this would be valuable.  I tend to think it'd be better as a separate doc, since it hopefully will have little relevance by the time QUIC v2 comes around, but it could also just be removed in the v2 transport doc.

**Comment by mnot** [comment]
There's the operability document...

**Comment by ianswett** [comment]
Good point, I'm happy with that.

**Comment by martinthomson** [comment]
Moving over there: quicwg/ops-drafts#25
