### ISSUE TITLE
Parsing Ack Delay without ack_delay_exponent

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#1007]
>Once the TLS handshake is complete, this is indicated to QUIC along with any final handshake octets that TLS needs to send. TLS also provides QUIC with the transport parameters that the peer advertised during the handshake.

Unfortunately Handshake (and Retry) packets can contain ACK frames and be delivered before the transport parameters are provided to QUIC. The ack delay field of the ACK frame cannot be interpreted without the ack_delay_exponent from the transport parameters. This brings back memories of flow control and stream 0.

There are several ways to resolve this, but I'll suggest that non protected packets that contain ACK frames are always encoded with the default ack_delay_exponent.

**Comment by ianswett** [comment]
Agreed, and I might expand that to include 0RTT packets.

**Comment by martinthomson** [comment]
Cleartext, yes, defaults.

The problem with 0-RTT is that it uses transport parameters from the ticket or previous session.  We might want to consistently apply transport parameters, rather than mix and match.
