### ISSUE TITLE
Requirement of PMTU > 1280

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#1014]
The draft currently requires that QUIC require a network path supporting a MTU of at least 1280 octets. Specifically, "An endpoint MUST NOT reduce its MTU below this number, even if it receives signals that indicate a smaller limit might exist."

This text needs justification or needs to be removed. (I can't recall why this was added in.)

**Comment by mikkelfj** [comment]
Some may read the text as if packets can never be smaller than 1280, which is not the case.

**Comment by martinduke** [comment]
@McManus may have covered this in (3), but it really limits you can do with spurious ICMP messages (cache poisoning, etc)

**Comment by janaiyengar** [comment]
This is fixed.
