### ISSUE TITLE
stream frame bits in wrong order

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#1021]
the len bit is 0x2 and the offset bit is 0x4 (and they are described in that order)

but their corresponding data fields appear in the frame as offset then length.. and the fields are described in that order.

we should swap the values of the len and offset bits to make things consistent

**Comment by martinthomson** [comment]
I think that the error here is that we describe the bits starting at 0x01 and moving up to 0x80.  The order we have consistently used elsewhere is 0x80 down to 0x01.  If you reorder the descriptions of the bits, then you don't have to change the wire format.  (Besides, high bits come first, right?)

**Comment by mcmanus** [comment]
Wfm

On Dec 16, 2017 4:42 PM, "Martin Thomson" <notifications@github.com> wrote:

I think that the error here is that we describe the bits starting at 0x01
and moving up to 0x80. The order we have consistently used elsewhere is
0x80 down to 0x01. If you reorder the descriptions of the bits, then you
don't have to change the wire format. (Besides, high bits come first,
right?)

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/quicwg/base-drafts/issues/1021#issuecomment-352213809>,
or mute the thread

**Comment by huitema** [comment]
What Martin says. Most RFC use 0x80 down to 0x01.

**Comment by martinthomson** [comment]
Closed.  Thanks Patrick.
