### ISSUE TITLE
Is zero a valid stream-ID in Transport Parameters?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1023]
We found this issue in interop testing. One implementation would send transport parameters with max bidir ID and max unidir ID set to zero. The other implementation applied strictly was is in the spec, and rejected the connection. The spec says:

_initial_max_stream_id_bidi (0x0002):
    The initial maximum stream ID parameter contains the initial maximum stream number the peer may initiate for bidirectional streams, encoded as an unsigned 32-bit integer. This value MUST be a valid bidirectional stream ID for a peer-initiated stream (that is, the two least significant bits are set to 0 by a server and to 1 by a client). If an invalid value is provided, the recipient MUST generate a connection error of type TRANSPORT_PARAMETER_ERROR. Setting this parameter is equivalent to sending a MAX_STREAM_ID (Section 8.8) immediately after completing the handshake. The maximum bidirectional stream ID is set to 0 if this parameter is absent, preventing the creation of new bidirectional streams until a MAX_STREAM_ID frame is sent. Note that a default value of 0 does not prevent the cryptographic handshake stream (that is, stream 0) from being used._

If we interpret this strictly, 0 is illegal -- the way to encode 0 is simply to not provide the parameter. Should 0 actually be accepted?

**Comment by nibanks** [comment]
I'd make the argument that if we support implicitly setting a value of 0, why wouldn't we support explicitly setting it?

**Comment by huitema** [comment]
@nibanks The counter argument is that it makes every decoder a bit more complex, while the implementations that want to send the value zero can just as well omit the parameter. So basically, who pays the cost?

The other issue is "bit rot". The "liberal in what you accept" argument is nice, but it leads to maintaining warts all over the code to accommodate this or that "almost standard" implementation.

**Comment by martinduke** [comment]
It seems harder to check the stream_id is not zero than just write the value in regardless.

**Comment by huitema** [comment]
@martinduke with the current spec, we are supposed to check that the stream ID corresponds to a legitimate value for that class of stream, e.g. "unidir server initiated". If you do the check without also testing for 0, then a value 0 fails for anything but "bidir client initiated". And per spec, this is supposed to trigger a connection close.

**Comment by martinthomson** [comment]
Let's say that I have a limit of 3 unidirectional streams as a (these are type: 2).  If I wanted to express that, I might write this code:

```c
add_parameter(parameters, max_unidirectional, limit * 4 - 2 + is_server);
```
You will note that a limit of 0 goes negative here and so you need special logic anyway, so that might as well be something like:
```c
if (limit)
  add_parameter(parameters, max_unidirectional, limit * 4 - 2 + is_server);
```
The drawback is that you can no longer just construct the transport parameters using a fixed-size template where you just fill in certain gaps.

The problem with encoding a 0 is as Christian describes, you need to create a check that exempts a zero from being marked as invalid.

I could remove the zero if that confuses people and say instead that omitting the transport parameter means that no streams of that type are permitted until a MAX_STREAM_ID frame is sent.  In other words, not indicate a specific value for the default and let people deal with that as they choose.

**Comment by huitema** [comment]
Or, we could say that the transport parameter encodes the "limit" in @martinthomson 's formula. That would probably be the cleanest solution, because that way no value could be wrong.

**Comment by martinduke** [comment]
OK, I see now that this is a wash. I would have to check for zero in either case, either to reject it (if the spec disallows it) or let it through.

Stepping back, it seems nonsensical that our default value is an invalid one. So either we should make it a limit with no invalid values, or change the defaults.

**Comment by janaiyengar** [comment]
I'm fine with any resolution -- I think this is a minor issue, but it should be resolved. I like @huitema's proposal of encoding the actual max number of streams.

**Comment by martinduke** [comment]
@janaiyengar actually I'd prefer we stick with a max ID. Otherwise both ends have to agree on how many streams are open, which is another thing to screw up.

**Comment by MikeBishop** [comment]
@martinduke, I don't think the suggestion was that we go back to a maximum number of open streams at a time.  Rather, the idea is that you can both get a smaller encoding and make invalid values impossible by encoding the max stream ID as an initial stream count.

That is, if a client sends `initial_max_streams_bidi=0x20`, the server would expand that as `0x20 << 2 + 0x00` and always produce a valid stream value.

**Comment by MikeBishop** [comment]
In fact, we could bifurcate MAX_STREAM_ID in the same way; this would save a byte off each MAX_STREAM_ID frame for Stream IDs which currently use only the low two bits of the most significant byte.  (64-255, 16K-64K, etc.)    It would also similarly make it impossible to send MAX_STREAM_ID with an invalid Stream ID (i.e. one that you're supposed to be initiating).

That's somewhat appealing.  Frame types are cheap; the inability to send something invalid is valuable.

**Comment by mikkelfj** [comment]
Aren't we half there where it makes sense to not encode the stream id in lower bits, and make a specific frame type instead?

**Comment by janaiyengar** [comment]
<img src="https://rawgit.com/tabatkins/bikeshed/master/docs/icon.svg" width=100 height=100 align=left>

I'm happy with #1065, modulo nits. We should close this.
