### ISSUE TITLE
Handling of Frames Inappropriate for Unidirectional Streams

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#1047]
Something I can't seem to find in the transport doc: if I have a unidirectional stream, various frame types don't make any sense.

Send-only streams shouldn't see STREAM, STREAM_BLOCKED, or RST_STREAM frames.
Receive-only streams shouldn't see MAX_STREAM_DATA, STOP_SENDING

There are several courses of action here:
- blow up the connection with error code XXXX
- blow up the stream with error code XXXX
- drop the whole containing packet as somehow compromised, and continue
- ignore the frame and continue.

If we blow it up,  I think there's a decent case for STREAM_DIRECTION_ERROR or something similar.

Early responders on the mailing list thought it should be a fatal connection error. I don't have a strong opinion but we should document the correct behavior.

**Comment by ianswett** [comment]
I'm happy with blowing up.  I slightly prefer blowing up the whole connection.

Dropping is dangerous and creates more complexity than is warranted.  Ignoring the frame is really bad, because it violates the rule that if a packet is acknowledged, all frames were processed.

**Comment by mikkelfj** [comment]
Yes, close the connection. Anything that is an entirely avoidable protocol error should be fatal.

**Comment by mikkelfj** [comment]
Anything during handshake is not entirely avoidable because an attacker may inject packets, and here dropping is better, but this is not the case here, in general.

However, it rasises the question: what should be done with stream violations during handshake? I presume there is already some text about this somewhere, otherwise this should be considered a separate case.

**Comment by martinthomson** [comment]
There used to be a statement to the effect that unless explicitly permitted, frames were not allowed.  RFC 7540 had that, and we copied it into the drafts, but I think that it got lost.  We should put it back.

**Comment by janaiyengar** [comment]
+1 to closing the connection with PROTOCOL_VIOLATION. I prefer text that explicitly disallows frames on particular stream types, since I would find it convenient to have a list when implementing this return on error.

**Comment by martinthomson** [comment]
Maybe we should just tabulate frames against states.

**Comment by martinduke** [comment]
The editorial issue is that we added unidirectional streams, and there should be some text here talking about errors related to unidirectional streams. Right now, debugging in prep for the interop is my priority, but I'll generate a PR in a week or so if no one else wants to do it.

**Comment by janaiyengar** [comment]
@martinduke : PRs are always welcome :-)
