### ISSUE TITLE
PING/PONG ambiguity

### ISSUE THREAD

**Issue by boisjacques** [quicwg/base-drafts#1051]
The definition of PING and PONG frames are ambiguous.   

Section 8.9 states:
> If the Data field is not empty, the recipient of this frame MUST generate a 
> PONG frame (Section 8.15) containing the same Data. 

Section 8.15 states:
> If the content of a PONG frame does not match the content of a PING frame
> previously sent by the endpoint, the endpoint MAY generate a connection error of type
> UNSOLICITED_PONG.

The way I see it either the `MAY` in Section 8.15 has to be a `MUST` to solve this ambiguity or the part in Section 8.9 has to be changed into something less strict. 
This would be my preferred option since it gives the PING/PONG frames a little bit more semantic leeway.

**Comment by mikkelfj** [comment]
Even if the PONG'er behaves correctly, arbitrary network delays and packet duplication may cause PONG packets to arrive after they are no longer remembered by the PING'er. Requiring a MUST makes correct evalutation much harder, either by storing PING frames indefinitely or by using some hashing to confirm the validity of the PONG frame.

**Comment by martinthomson** [comment]
@mikkelfj's answer here is the reason that this isn't a MUST. @boisjacques, do you think that there needs to be some better explanation of this?

**Comment by boisjacques** [comment]
Thank you for the clarification, for me it's clear now. However it might help to make the implicit explanation more explicit.

**Comment by ianswett** [comment]
PING and PONG have been replaced by PING, PATH_CHALLENGE, and PATH_RESPONSE, so hopefully that closes this issue?

**Comment by MikeBishop** [comment]
The text is still there, but I agree with @mikkelfj and @martinthomson that the text is correct.  The sender MUST do the right thing, but the receiver isn't required to track sufficient information to detect it 100% of the time.
