### ISSUE TITLE
Exclusion from congestion control for ACK

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1055]
There is no evidence in the current draft of the exemption that ACK-only packets get to ignore the limit set by `congestion_window`.

**Comment by ronieven** [comment]
Implied in  4.7.2 "Packets only containing ACK frames do not
      count towards byte_in_flight to ensure congestion control does not
      impede congestion feedback."

**Comment by ianswett** [comment]
Thanks Roni, exactly.

Did you have a suggestion for somewhere else it should be mentioned?

**Comment by martinthomson** [comment]
I think that providing an explicit can-send description would help (as I request with #1056).  And the computation of bytes_in_flight in Section 4.7.4 doesn't include this tweak.
