### ISSUE TITLE
Definition of Recovery End

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#1059]
According to the spec, recovery starts with detection of a lost packet and ends with the acknowledgement of a single, newly sent packet. Why isn’t recovery ending only after all the information in the frames that were lost prior to the recovery period have been acknowledged?

For instance, if 4 packets worth of STREAM frames and a MAX_DATA frame were lost, why shouldn’t recovery last until all that data had been resent and acknowledged?

**Comment by martinthomson** [comment]
This is probably a question better taken to the list.

**Comment by janaiyengar** [comment]
Traditionally, "recovery period" is used for isolating loss epochs, for congestion control purposes. This definition is meant for that purpose. (Agreed with Martin, please take further discussion to the list.)
