### ISSUE TITLE
Retry packet and PADDING

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#1067]
-08 in Section 5.4.2. says:

>   The payload of the Retry packet contains a single STREAM frame on
>   stream 0 with offset 0 containing the server's cryptographic
>   stateless retry material.  It MUST NOT contain any other frames.  The
>   next STREAM frame sent by the server will also start at stream offset
>   0.

Any reason why PADDING is not allowed? (Insert usual stuff about zero-copy and fixed offsets.)

**Comment by marten-seemann** [comment]
There’s a related PR for this: https://github.com/quicwg/base-drafts/pull/882

**Comment by larseggert** [comment]
#882 says "It SHOULD also contain an ACK frame" and removes the limit on any other frames. That looks a bit too broad? 

Why not say "MAY contain PADDING (and ACK?) and MUST NOT..."

**Comment by MikeBishop** [comment]
#882 doesn't say anything about PADDING, and should perhaps also pad to the minimum handshake packet size (so it fails quickly if the network won't work).  We should get this as part of updating it to cover #627.
