### ISSUE TITLE
Why is packet_number an argument for OnPacketSent?

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#107]
In draft-quic-ietf-recovery, packet_number is listed as a parameter. But it is not used in the pseudocode, is not sent on to SetLossDetectionAlarm(), and there is no obvious place that SetLossDetectionAlarm() would use it.

**Comment by Aron-Schats** [comment]
I wonder whether the loss detection and recovery mechanisms can be explained without the use of the pseudo-code, which seems like a cop-out.  The pseudo-code does not match what occurs in proto-quic code.  (This is probably OK, as the draft may be describing a future version of QUIC.)

In addition, alarm mode is mentioned, but the different modes are not listed.
