### ISSUE TITLE
Stream 0 exemption from flow control

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1074]
@mikkelfj [asks](https://github.com/quicwg/base-drafts/commit/b52b40bb8ced2bbeda2e4f5d8ab00a2d21a3cc19#r27095625) whether the exemption of stream 0 also means that data counts towards MAX_DATA limits.

In other words, choose between:

* data sent on stream 0 counts as data sent, but it is permitted to exceed flow control limits
* data sent on stream 0 does not count as data sent for the purposes of flow control

**Comment by marten-seemann** [comment]
Option 1 doesn't work if you have reordering.
Example: The connection flow control credit is *x*. The sender sends *x* bytes on stream 1, and then exceeds the flow control limit to send *y* bytes on stream 0. If packets are reordered, such that data for stream 0 arrives before all data for stream 1 was received, to the receiver it will look like the sender violated its credit by sending too much data on stream 1.

**Comment by MikeBishop** [comment]
I'm inclined toward "not."  We've already discussed reasons why it can't be bound by connection flow control, and partial exemptions don't work.  The partial exemption from stream flow control works because you have fixed ordering on the stream.
