### ISSUE TITLE
Maximum stream number

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#108]
QUIC currently permits up to 32 bits of stream number.  This could be increased to 64.

**Comment by janaiyengar** [comment]
+1. Stream ID length is currently represented by 2 bits that encode 8, 16, 24, or 32. We could make this 8, 16, 32, 64.

**Comment by ianswett** [comment]
Agreed, we've already come up with a use case for 64 bits of stream ID.

**Comment by MikeBishop** [comment]
HTTP frames will need to update accordingly.

**Comment by ghedo** [comment]
@ianswett 

> we've already come up with a use case for 64 bits of stream ID

I think I missed out on something, so could you describe the use case in here (or direct me to where this is described)?

**Comment by ianswett** [comment]
The first use case I've discussed(not sure on what list) was WebRTC, where a proposed mapping is to use a stream per audio or video frame.  At that rate, we calculated we'd run out of stream ids after about a day.  Admittedly, we could also just reconnect at that point, so it's not a high priority use case.

**Comment by pthatcherg** [comment]
Some more explanation from the WebRTC perspective:

With both audio and video at high frame/sample rates and simulcast (multiple resolutions), and then add some high frequency data channel messages, you can easily be in the "500hz" combined territory, which if you're conservative and assume 1B stream IDs available, you end up with:

1B / (500 * 60 * 60 * 24) = 23 days

Which doesn't sound too bad, until you want some realtime data streaming for more than 23 days.

I admit it is an edge case.  Most uses of WebRTC will not be using so many streams, and even if they  did, we could do things like use a new connection ID or re-use stream IDs.  But if it's easy enough to add a few more optional bits of stream IDs, then we can avoid this possibility altogether and leave the flexibility open.  If it's difficult to add those optional bits, then perhaps it's not worth the tradeoff.

**Comment by krasic** [comment]
Would it be crazy to just use [HPACK's integer representation](https://tools.ietf.org/html/rfc7541#section-5.1)?

**Comment by ianswett** [comment]
@krasic That's a possible option, but we still need to decide if the max stream number is 32 or 64 bits.

**Comment by tatsuhiro-t** [comment]
SPDY and HTTP/2 use 31 bit stream ID space, and it can be expressed in 32 bit signed integer.
Some languages don't have unsigned types (e.g., Java), so if fully 32 bit space is used, they are forced to use larger data type (e.g., 8 bytes long).
Also there is concern in API compatibility.  I'd like to use the same higher level interface with HTTP/2 and HTTP/QUIC.  Some existing implementations use 32 bit signed int for stream ID (e.g., nghttp2, and netty, possibly more?).  If we go for larger ID space, we need to define different high level APIs for QUIC.
QUIC's 0 RTT connection really makes connection establishment penalty less effective.  Why we need larger ID space?

**Comment by ianswett** [comment]
I don't think this issue has much effect on QUIC's HTTP mapping.  It's relatively easy to layer a smaller stream ID space(ie: 31 bits) onto a larger one(ie: 64 bits), and it seems likely the HTTP mapping for QUIC will consume 2 QUIC streams per HTTP stream, so even 32 bits is only 31 for HTTP.

One thought(not sure if it's a good one yet): Allow 64 bit stream ids and use 8, 16, 32, 64 bits in the framing, but negotiate the max stream ID for a given connection in the handshake.  For over 99.9% of connections, more than 32 bits is overkill, but there may be use cases it's really helpful.

**Comment by martinthomson** [comment]
Note that at 64-bits, we now have more streams available for use than we have packet numbers.

**Comment by ianswett** [comment]
Packet numbers are 64 bits, there's just a bizarre quirk that we can't currently encode the full packet number's 64 bits, only 48 bits of it.

**Comment by martinthomson** [comment]
My point was that some packet numbers can be lost, whereas we require that all stream numbers be used.

**Comment by vasilvv** [comment]
I will note that you can easily have more streams than packets -- consider a situation where you send relatively short (100-200 bytes) messages in individual streams.

**Comment by mnot** [comment]
As discussed in Tokyo, we need to make sure that the design of QUIC can support many streams of small objects, but increasing the number needs a more concrete motivation

**Comment by martinthomson** [comment]
Just to add to this so I don't forget.  Stream numbers could become part of the state commitment that an endpoint makes.  If we increase the space, we also need to account for that in other places.  I'm thinking about nascent QPACK work here, which might need to save stream numbers.  There might be other places where we store stream numbers in addition to the obvious changes to the wire format in mappings.
