### ISSUE TITLE
Document Limit on Peers MTU

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#1080]
The current transport draft only discusses minimum MTU. However, a large MTU drains resources on the receiving end and could lead DoS attacks on validation of invalid very large packets. IPv6 has a limit of 64K, but apparently there can also be gigabyte sized jumbograms. Futher, this adds an implicit dependency on IPv6 that might be overlooked when adapting QUIC to other transports.

A receiver can always drop large data grams and thus force a MTU limit, but perhaps some text is needed to make this explicit?

**Comment by marten-seemann** [comment]
We already have the `max_packet_size` parameter in the transport parameters.

**Comment by mikkelfj** [comment]
Of course I overlooked `max_packet_size` in transport parameters.

But I still think some mention is needed in section 9.2 https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.9.2

**Comment by mikkelfj** [comment]
> We already have the max_packet_size parameter in the transport parameters.
yes I just realized

**Comment by martinthomson** [comment]
PR welcome.

**Comment by martinthomson** [comment]
After looking at this, this is fine.
