### ISSUE TITLE
Handshake failure with Retry and multiple Initial packets

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1085]
Initial 1 is sent twice.  The server generates a Retry for the first, then a Handshake for the second (after forgetting the first).  The client processes the Retry, then gets really confused about the Handshake packet and dumps the connection.

What, if anything, do we want to do about that?

This assumes that the connection ID the server uses is the same for both, but all that takes is the server echoing the connection ID chosen by the client.

**Comment by MikeBishop** [comment]
Inclined to do nothing -- if the server decided the Initial wasn't acceptable, it should remain unacceptable.  The server changing its mind doesn't seem like a common enough or valid enough case to require much protocol effort.

**Comment by martinthomson** [comment]
It's definitely valid.  Though doing nothing might be OK.

**Comment by MikeBishop** [comment]
What's the case for it being valid?  Given that the two ClientHellos can't be different, I would expect the reason for wanting to Retry would be that the address validation token is stale/doesn't match your address, which is something that cannot improve with time.

**Comment by martinthomson** [comment]
A server might have a budget for accepting unvalidated ClientHellos.  As long as it doesn't send a massive ServerHello flight, it can do that and avoid the round trip.  But you want to limit the number of those that you accept for load reasons or for denial of service reasons.

**Comment by marten-seemann** [comment]
I'd like to point out that this won't be an uncommon case. If clients start with a low initial RTT estimate, the retransmission of the Initial packet will happen quickly.

We could solve this by requiring the server to pick a new connection ID on the Retry packet. The client would latch onto the connection ID of the first packet it receives (this works in either case, Retry or Handshake packet), and ignore the packet that arrives second.

**Comment by martinthomson** [comment]
This was addressed by #1151.
