### ISSUE TITLE
Recommend simulating migration after quiescence

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1087]
A connection that is unused for a while might trigger NAT rebinding when the NAT times out.  We can recommend that a client use the next available connection ID at that point.  Nothing much is lost by doing so, and it increases the use of NEW_CONNECTION_ID.

**Comment by janaiyengar** [comment]
Seems reasonable, and I like the common-casing of NEW_CONNECTION_ID.

**Comment by huitema** [comment]
OK. Now define "a while". How long is that? Obviously less than the idle timeout. Then what? The 2 minutes specified in RFC 4787? The 30 seconds often adopted as a conservative NAT refresh rate?

**Comment by janaiyengar** [comment]
We'll have to define "unused" too. The send time of any packet, or just those that are acked?

**Comment by martinthomson** [comment]
Those don't really need definition here.  If you think that a new connection ID is worth using, then switch over to a new one.

Unlike the idle timeout, this has the advantage of being discretionary.
