### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#109]
I note that the IEEE754 reference doesn't help.

**Comment by janaiyengar** [comment]
The time representation is "inspired by" IEEE754, so it's likely that the reference doesn't help by itself :-)

**Comment by ianswett** [comment]
I propose we switch to scaled integers with a scale factor that is supplied by both peers at the beginning of the connection.  If no scale factor is supplied, default to microseconds.  This allows 65ms of time, which is plenty for most cases.

MAX_UINT_16 indicates the value was too large to be specified.

**Comment by marten-seemann** [comment]
I just ran some tests with a quic-go server, and some normal browsing activity using Chrome (all on localhost), and recorded the delay times of incoming ACKs. I'm seeing a few ones that have delay times on the order of 65 ms.
ACKs with a delay of MAX_UINT_16 would probably need to be excluded from contributing to the RTT calculations, right?

What's the reason to change the format at all? Other than that it's a little bit of bit shifting that needs to be implemented (which could be made a lot easier by providing some examples).

**Comment by larseggert** [comment]
The reason is that it's not fully specified. We either need to say it's IEEE754 and cite it, or we need to include a spec for what we actually are using.

**Comment by ianswett** [comment]
One reason for changing it is that it may be very difficult to get a Linux kernel implementation if we require support for any sort of floating point format, but maybe it could be read and immediately converted to an int.  Similarly, hardware support may be much more challenging.  And though it's sort of neat, I'm not sure it's buying us a lot over a scaled int.

I agree that sometimes the delay times are over 65ms, but I'd expect it's typically either in a connection close frame(where it's not important at all) or when there's reordering and an RTT sample has already been taken for the current largest observed.

**Comment by martinthomson** [comment]
Can't implementations also avoid providing timing for packets that have large processing delays?  If that means that there are no processing delays reported, that's probably OK too.  Though RTT measurements will then be 65ms+ out of whack, it might be better than sending a useless value.

**Comment by larseggert** [comment]
I think 65ms is at least an order of magnitude too short. We don't know where people will want to use QUIC in the future.

**Comment by ianswett** [comment]
Agreed Lars, that's why we'd have the ability to scale the value.

**Comment by larseggert** [comment]
Sorry I was unclear: We should use a scaling default that results in a sensible range.

**Comment by ianswett** [comment]
I'd propose we require a scale factor as part of the handshake, so we ensure this is well exercised, then we don't need to worry too much about whether we've chosen a good default.

For the current use of the custom 2 byte timestamp, 65ms is enough to handle all the cases when a time value is actually useful.  Obviously this would change if we used this time format in different use cases.

**Comment by mnot** [comment]
Comment from @larseggert in #159:

> There already is a "DISCUSS_AND_REPLACE: Perhaps make this format simpler" note in the spec about the homegrown floating point format used for ACK timestamps. I just wanted to open a corresponding issue.
>
> It would be really good if an encoding could be used that was either trivial to implement from scratch, or a standard for which code is readily available.
>
> As for the latter, the text in the spec sounds like what is desired is something like the "binary16" format in IEEE 754-2008. I'd be great if this could be used. Compiler support seems spotty/sketchy, e.g., gcc says this:
>
> The __fp16 type may only be used as an argument to intrinsics defined in <arm_fp16.h>, or as a storage format. For purposes of arithmetic and other operations, __fp16 values in C or C++ expressions are automatically promoted to float.
And it's only supported on ARM, apparently.

**Comment by mikkelfj** [comment]
I worked through the details before being pointed to this issue.

I have attached a reference implemention that only lacks MSVC optimization. Mind you, it is very recent and has not been reviewed.

While at first I found the format (I call uf16) to be quite daunting, overengineerd, an unclear, I now believe it is actually very well suited for the problem, and it is quite simple and fast to use if the the `uf16_encode` and `uf16_decode` functions are provided as an appendix.

quoting parts of the attached uf16.h file and embedded comments below:

```
The IETF QUIC transport draft Nov. 2016 draft appears to provide an
incorrect example of a delta encoded timestamp in the ACK Frame section.
It is also not clear if the spec is otherwise the same as the Chromium
implemention. The following definition attempts to make this more clear
and follows the logic that Chromium implements as of Jan 2017.


    QUIC uses a custom floating point format uf16 to represent a
    non-negative time delta in microseconds.

    The uf16 format encodes an unsigned 16-bit floating point value with
    non-negative exponent and no special values(*). It can always be
    expanded into a 64-bit signed or unsigned integer. The format is a
    16-bit encoded value v = e(5)f(11) or, when e < 2 a plain unsigned
    12-bit integer v = 0(4)m(12). When v < 2^12 (and therefore e < 2), the
    resulting integer value becomes k = v with no interpretation. When e >=
    2, the effective exponent becomes p = e - 1 and the mantissa, or
    effective fraction, becomes m = f + 2^11 which adds an implicit most
    significant fraction bit. Thus the resulting integer value becomes k = m
     * 2^p, p >= 1 or k = (f + 2^11) * 2^(e - 1), e >= 2.

    (*) The decoded value can comfortably be represented in a 64-bit signed
    or unsigned integer. When encoding an unsigned 64-bit value, any value
    that would overflow the 16-bit encoded representation is clamped to v =
    UF16_MAX = 2^16 - 1 = 0xFFFF, or k = UF16_UINT64_MAX = (2^12 - 1) * 2^30
    =  0x3FFC0000000.

    On common unsigned twos complement 64-bit hardware decoding from uf16
    can be computed as `if v < (1 << 12) then return v; else p = (v >> 11) -
    1; m = (v - p) << 11; k = m << p; return k; endif`. Note that v - p
    exposes the implicit fraction bit while removing the explicit exponent.
    Likewise encoding to uf16 can be computed as `if k < (1 << 12) return k;
    else if k >= UF16_INT64_MAX then return UF16_MAX; else p = 64 - 12 -
    leading_zero_count_uint64(k); v = (p << 11) + (k >> p); return v;
    endif`. Note that adding (p << 11) intentionally overflows the implicit
    fraction bit and increments p by one.

```

quoting the actual encode without support for leading zero count included:

```
/* `__uf16_leading_zero_count_uint64` may be implemented with __builtin_clzll when available. */

#define UF16_MAX UINT16_C(0xFFFF)
#define UF16_UINT64_MAX UINT64_C(0x3FFC0000000)

static inline uint64_t uf16_decode(uint16_t v)
{
    uint16_t p;
    uint64_t m;

    if (v < (1 << 12)) {
        return v;
    }
    p = (v >> 11) - 1;
    m = v - (p << 11);
    return m << p;
}

static uint16_t uf16_encode(uint64_t k)
{
    uint16_t p, f;

    if (k < (1 << 12)) {
        return (uint16_t)k;
    }
    if (k >= UF16_UINT64_MAX) {
        return UF16_MAX;
    }
    p = (uint16_t)(64 - 12 - __uf16_leading_zero_count_uint64(k));
    f = (uint16_t)(k >> p);
    return (p << 11) + f;
}

```
[uf16.h.zip](https://github.com/quicwg/base-drafts/files/720596/uf16.h.zip)

**Comment by mikkelfj** [comment]
`static uint16_t uf16_encode(uint64_t k)` =>
`static inline uint16_t uf16_encode(uint64_t k)`

Here is an updated wording:

```
The IETF QUIC transport draft Nov. 2016 draft appears to provide an
incorrect example of a delta encoded timestamp in the ACK Frame section.
It is also not clear if the spec is otherwise the same as the Chromium
implemention. The following definition attempts to make this more clear
and follows the logic that Chromium implements as of Jan 2017.


    QUIC uses a custom floating point format uf16 to represent a
    non-negative time delta in microseconds.

    The uf16 format encodes an unsigned 64-bit integer value k as an
    unsigned 16-bit floating point value v with non-negative exponent
    and no special values (*). The encoded format is either v =
    e(5)f(11), e >= 2, or a plain unsigned 12-bit integer v = 0(4)m(12),
    e <= 1. When v < 2^12 (and therefore e < 2), the resulting integer
    value becomes k = v with no interpretation. When e >= 2, the
    effective exponent becomes p = e - 1 and the mantissa, or effective
    fraction, becomes m = f + 2^11 which adds an implicit most
    significant fraction bit. Thus the resulting integer value becomes k
    = m * 2^p, p >= 1 or, equivalently, k = (f + 2^11) * 2^(e - 1), e >=
    2, and k = v, e < 2.

    (*) The decoded value can comfortably be represented in a 64-bit
    signed or unsigned integer. When encoding an unsigned 64-bit value,
    any value that would overflow the 16-bit encoded representation is
    clamped to v = UF16_MAX = 2^16 - 1 = 0xFFFF or, correspondingly, k =
    UF16_UINT64_MAX = (2^12 - 1) * 2^30 = 0x3FFC0000000.

    On common hardware supporting unsigned 64-bit two's complement
    arithmetic, decoding from uf16 can be computed as `if v < (1 << 12)
    then return v; else p = (v >> 11) - 1; m = (v - p) << 11; k = m <<
    p; return k; endif`. Note that v - p exposes the implicit fraction
    bit while removing the explicit exponent. Likewise, encoding to uf16
    can be computed as `if k < (1 << 12) return k; else if k >=
    UF16_INT64_MAX then return UF16_MAX; else p = 64 - 12 -
    leading_zero_count_uint64(k); v = (p << 11) + (k >> p); return v;
    endif`. Note that adding (p << 11) intentionally overflows and hides
    the implicit fraction bit and increments the explicit exponent by
    one. `leading_zero_count_uint64(k)` implements `64 - log2_floor(k)`
    and is often a single machine instruction, sometimes provided as
    `__builtin_clzll` in C.

```

**Comment by mikkelfj** [comment]
Updated uf16.h with new wording, and MSVC support, attached.

[uf16.h.zip](https://github.com/quicwg/base-drafts/files/721213/uf16.h.zip)

**Comment by mikkelfj** [comment]
Edited the above text, added MSVC support stolen from llvm headers, moved from leading_zero_count to using logbase2 in algorithm, and cleaned up reference implementation so it is self-contained. Reference pasted below and optimized version with test attached.

```
#include <stdint.h>

#define UF16_MAX UINT16_C(0xFFFF)
#define UF16_UINT64_MAX UINT64_C(0x3FFC0000000)

/*
 * Preferable provide builtin version when avaible.
 * Only needs to be implemented for [2^12 .. UF16_UINT64_MAx]
 */
#ifndef uf16_logbase2_floor

/* Returns 0 when `k == 0`. */
static inline int __uf16_logbase2_floor_reference(uint64_t k)
{
    k |= (k >> 1);
    k |= (k >> 2);
    k |= (k >> 4);
    k |= (k >> 8);
    k |= (k >> 16);
    k |= (k >> 32);
    k -= (k >> 1) & UINT64_C(0x5555555555555555);
    k = (k & UINT64_C(0x3333333333333333)) + 
        ((k >> 2) & UINT64_C(0x3333333333333333));
    k = (k + (k >> 4)) & UINT64_C(0x0f0f0f0f0f0f0f0f);
    k = (k * UINT64_C(0x0101010101010101)) >> 56;
    return k;
}

#define uf16_logbase2_floor(k) __uf16_logbase2_floor_reference(k)

#endif /* uf16_logbase2_floor */

static inline uint64_t uf16_decode(uint16_t v)
{
    uint16_t p;
    uint64_t m;

    if (v < (1 << 12)) {
        return v;
    }
    p = (v >> 11) - 1;
    m = v - (p << 11);
    return m << p;
}

static inline uint16_t uf16_encode(uint64_t k)
{
    uint16_t p, f;

    if (k < (1 << 12)) {
        return (uint16_t)k;
    }
    if (k >= UF16_UINT64_MAX) {
        return UF16_MAX;
    }
    p = (uint16_t)(uf16_logbase2_floor(k) - 12);
    f = (uint16_t)(k >> p);
    return (p << 11) + f;
}
```
[uf16.h.zip](https://github.com/quicwg/base-drafts/files/721330/uf16.h.zip)

**Comment by mikkelfj** [comment]
Discovered that logbase2 can work in 32-bits and debruijn is then very fast.
I have edited the above code snippet reference text to match content of attached file.

I did some benchmarks. Each encode/decode operation consumes less than 5ns with the reference deBruijn logbase2 implementation, and about 3.5ns with clang __builtin_clz. Using the k>>12 trick before logbase2 really added performance. On unoptimized builds the encode/decode operation is about 30ns default, and 20ns builtin.

Considering the heaviest operation is a 32-bit multiplication, or alternatively, a 32-bit leading zero bit count instruction, I'd say its fast enough for most use cases.

[uf16.h.zip](https://github.com/quicwg/base-drafts/files/721429/uf16.h.zip)

**Comment by mikkelfj** [comment]
In addition, I can now say exactly what is wrong in the spec - the first section is correction:

>  The time format used in the ACK frame above is a 16-bit unsigned
>    float with 11 explicit bits of mantissa and 5 bits of explicit
>    exponent, specifying time in microseconds.  The bit format is loosely
>    modeled after IEEE 754.  For example, 1 microsecond is represented as
>    0x1, which has an exponent of zero, presented in the 5 high order
>    bits, and mantissa of 1, presented in the 11 low order bits.

First observe that the explicit, or encoded exponent e in my description only apply when e >= 2, but it is valid include e >= 1 because the computation in either branch results in the same value, it is just more efficient to branch at e >= 2, and this is also what Chromium implements.

>   When  the explicit exponent is greater than zero, an implicit high-order
>    12th bit of 1 is assumed in the mantissa.  

This is only half-true. In fact the effective exponent is always one less than the explicit exponent, so we have effective exponents that are 0 and -1 as well, but it is much more efficient to implement the case e >= 2 separately and documenting the format otherwise is not really helpful to implementers.

The next section is wrong:
> For example, a floating
>    value of 0x800 has an explicit exponent of 1, as well as an explicit
>    mantissa of 0, but then has an effective mantissa of 4096 (12th bit
>    is assumed to be 1).

The explicit exponent is 1, and the implicit 12'th fraction bit has the value 2^11 = 2048.
The effective exponents is one less, so it is 0. Hence the resulting value is 2048 which is also a test case in my attached utf16.h file.

> Additionally, the actual exponent is one-less
>    than the explicit exponent,

This is correct. It is always one less. 

> and the value represents 4096  microseconds.

Incorrect. It represents 2048 microseconds.

>   Any values larger than the representable range are
>    clamped to 0xFFFF.

Correct.

**Comment by mikkelfj** [comment]
Added uf16.h as gist. Includes proposed text for uf16 format spec in comment.

https://gist.github.com/mikkelfj/64deb01b86d68f3d7aacff4b113c22d8

**Comment by mikkelfj** [comment]
One a related note. The first timestamp in the ACK frame is a 32-bit value stated to be relative to the connection start, measured in microseconds. This only allows for 71 minutes of connection time after which it must roll over somehow. If the same field was stored in 2 bytes in uf16 global there is more than enough range and the gradual precision loss relative to the starting time doesn't really matter. It also saves two bytes and avoids two different encodings for the same value type.

**Comment by mnot** [comment]
As discussed in Tokyo, updated drafts by using the floating point details in this thread

**Comment by mikkelfj** [comment]
Note that I just corrected an incorrect description of the encoding algorithm: v - p should have been v - (p << 1). The reference implementation is correct. Edited in the above. You can also see the text in the gist with revision history. I try to keep this up to date if I find anything wrong or inaccurate.

**Comment by marten-seemann** [comment]
Just for reference, this is how we implemented it in quic-go: https://github.com/lucas-clemente/quic-go/blob/master/utils/float16.go

**Comment by mikkelfj** [comment]
I copied some test cases from that implementation.

**Comment by mikkelfj** [comment]
I renamed the uf16.h implementation to ufloat16.h for consistency with Go and Chromium implementations.

Regarding my earlier comment on 32-bit overflow in first timestamp, I can see that Chromium maps overflow to closest previously or next epoch, which is probably a good way to handle this without loosing precision.

Off topic, but some other vague formulation in current ACK frame spec I noticed:

Ordering of ack blocks is unclear because blocks can't grow beyond latest observed, and descending blocks are only mentioned in source comments:
https://chromium.googlesource.com/chromium/src/net/+/master/quic/core/quic_framer.cc#1967

With descending blocks, it is also not clear how STOP_WAITING can make the receiver stop waiting if there are pending gaps below latested_acked. Intuitively STOP_WAITING seems to be a lower bound beyond which neither acks nor ack gaps are transmitted, but that can't be

**Comment by huitema** [comment]
Here are the test vectors that I use in my implementation:
~~~
struct _float16test_st {
    uint64_t n64;
    uint16_t f16;
    uint64_t n64_decoded;
};

static struct _float16test_st float16_test_case[] = {
    { 0, 0, 0},
    { 1, 1, 1},
    { 0x7FF, 0x7FF, 0x7FF},
    { 0x800, 0x800, 0x800},
    { 0x801, 0x801, 0x801 },
    { 0xFFF, 0xFFF, 0xFFF },
    { 0x1000, 0x1000, 0x1000 },
    { 0x1001, 0x1000, 0x1000 },
    { 0x1002, 0x1001, 0x1002 },
    { 0x2004, 0x1801, 0x2004 },
    { 0x10000000, 0x9000, 0x10000000 },
    { 0x10080000, 0x9004, 0x10080000 },
    { 0x3FFC0000000, 0xFFFF, 0x3FFC0000000 },
    { 0x40000000000, 0xFFFF, 0x3FFC0000000 },
    { 0x7F00000000000, 0xFFFF, 0x3FFC0000000 }
};

static size_t nb_float16_test_case = sizeof(float16_test_case) / sizeof(struct _float16test_st);
~~~
Hope it helps...

**Comment by mikkelfj** [comment]
BTW: I suggest avoiding the name float16 or f16 - there are numerous 16bit floating formats around for computer graphics, and this format is different, and decidedly unsigned. GQUIC and GOQUIC uses the term ufloat16.

**Comment by mikkelfj** [comment]
I have changed to text description and implementation very slightly: The test vector would originally have encoded `{k', v, k}` but I now use `{n, v, k}` for input, encoded and decoded value respectively. I also moved the old test code to a seperate file in the gist - the names are currently not consistent there.
