### ISSUE TITLE
hq Alt-Svc quic parameter and structured headers

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#1093]
I think the current syntax of the "quic" parameter for hq Alt-Svc is, after recent changes, incompatible with structured headers. For reference, https://github.com/httpwg/http-extensions/issues/281 provides history of the issue. This ticket highlights that HTTP/QUIC is now incompatible. 

Please close this out if a non-issue.

**Comment by MikeBishop** [comment]
Technically, it's a non-issue, since Alt-Svc isn't defined to be a structured header.  However, the goal is to track that draft as closely as reasonable, since it also represents a best practice.  I'll take a look and see if there's a simple change that would bring us closer, but I also don't want change for change's sake.

**Comment by MikeBishop** [comment]
Seems like the simplest choice would be a comma-delimited quoted string, i.e.

```
quic = DQUOTE version-number [ "," version-number ] * DQUOTE
version-number = 1*8HEXDIG; hex-encoded QUIC version
```

That certainly makes it shorter and matches the guidance, at the price of updating everyone's parser again.  What do folks think?

**Comment by LPardue** [comment]
I have no strong stake.

Good point about structured header / best common practice.

**Comment by ianswett** [comment]
So, oddly enough GQUIC has already started supporting the newly proposed IETF Alt-Svc, but if we're going to change it, sooner would be better.  And if you change it again after this time, we'll probably start getting grumpy :)

But shorter and following best practices seems like general goodness.

**Comment by siyengar** [comment]
+1 on sooner the better.

**Comment by janaiyengar** [comment]
+1 -- Let's do this, and ASAP.
