### ISSUE TITLE
Should path migration mimic an initial connection?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1096]
During the discussion of packet number encryption (PR #1079) many participants pointed out that migration does not look like a new connection. In a new connection, the first packet from the client is a "client initial" containing a clear text TLS "client hello", and the first packet from the server is a "handshake" containing a clear text TLS "server hello". In a migration, according to PR #1012, the first packet in either direction on the new path is an encrypted 1RTT packet, with a short header.

Does this really matter? 

If it does, the plausible solution is to treat the connection migration as a form of session resume. The resume ticket would need to encode that this really is a continuation of the existing QUIC session, but that seems reasonably OK to engineer. These would have to be passed to the client somehow, maybe as "MIGRATION RESUME TOKEN" frames, replacing the "NEW CONNECTION ID" mechanism. The connection setup would provide an implicit path validation, removing the need for the PATH CHALLENGE and RESPONSE frames. Not sure whether the result would be more or less complex than the present mechanism, probably similar in complexity.

**Comment by ianswett** [comment]
This has been raised in Issue #203, so I'd prefer to keep the conversation there.
