### ISSUE TITLE
Stream error handling is ambiguously specified

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1098]
In section 12.2. Stream Errors the spec says:

   _If the error affects a single stream, but otherwise leaves the connection in a recoverable state, the endpoint can send a RST_STREAM frame (Section 8.3) with an appropriate error code._

And a few lines later, it says:

   _RST_STREAM MUST be instigated by the application and MUST carry an application error code._ 

This is mildly ambiguous. What about stream errors like Stream State Error, Final Offset Error, or the Protocol Violation that occurs if a peer tries to close Stream 0? These are defined as Transport Error Codes, and thus can only be sent in a Connection Close message. Are they covered by the general "recoverable state" qualifier?

**Comment by martinthomson** [comment]
Yes, the simple fix here is to observe that all transport errors are connection errors (in 12.2).

**Comment by MikeBishop** [comment]
Fixed by #1204.
