### ISSUE TITLE
Push Stream Header duplication

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#1099]
I've been reading HTTP/QUIC section 3.4 on Server Push again. 

>    Each Push ID MUST only be used once in a push stream header.  If a
>    push stream header includes a Push ID that was used in another push
>    stream header, the client MUST treat this as a connection error of
>    type HTTP_DUPLICATE_PUSH.  The same Push ID can be used in multiple
>    PUSH_PROMISE frames (see Section 4.2.6).

I'd like to clarify if "another push stream header" means:

1) A STREAM frame received on a different stream ID to the original stream ID.
2) A duplicate STREAM frame received on the same original stream ID.

I think it's option 1. If its option 2 then I can see issues with receiving duplicate STREAM frames

**Comment by MikeBishop** [comment]
(1), but I would hesitate to use that language.  The HTTP layer has no visibility into QUIC STREAM frames -- it just sees an ordered bytestream of data.  The push header is the first bytes read off of each unidirectional stream, so for a Push ID to be in two push stream headers, it would have to be on two different streams.

**Comment by LPardue** [comment]
Ahh ok so where I'm confusing myself is around that abstraction/API.

Duplication of STREAM frames would be resolved by the QUIC transport, all the HTTP layer would see is the singular occurrence of the stream header as part of the byte stream. 

Is that right?

**Comment by MikeBishop** [comment]
Yep.  Do you think that needs text, or is this just personal clarification?

**Comment by LPardue** [comment]
Definitely no text in the push section. I think section 3 does well at
capturing the bytestream description. It doesn't mentioned STREAM frame
duplication but meh.

Perhaps where it says "exposing the data contained within as a reliable
byte stream to the application" could be tightened to say this application
mapping for HTTP/QUIC unframing. Or something to that effect.

On 6 Feb 2018 18:12, "Mike Bishop" <notifications@github.com> wrote:

Yep. Do you think that needs text, or is this just personal clarification?

**Comment by LPardue** [comment]
Lets close this because I don't think there is any real issue.
