### ISSUE TITLE
text on retry and connection id

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#1118]
5.4.2 retry

> The server includes a connection ID of its choice in the connection   ID field.  The client MUST use this connection ID for any subsequent   packets that it sends.

I don't think "any subsequent packets" is right.. this applies to subsequent initials, not forever and forever right? (the server, being stateless on the retry, might choose a new cid again in the HANDSHAKE reply)

**Comment by martinthomson** [comment]
I think that is fine.  That the server might later provide a different connection ID and that clients can use that is OK.

Is the imprecision here made worse by the choice of 2119 "MUST"?

**Comment by mcmanus** [comment]
I read "MUST - any subsequent" as "MUST all subsequent" which would rule
out the server later providing a different connection ID (which we both
agree we want to allow)

can't we just say "for subsequent INITIAL packets it sends" ?

**Comment by martinthomson** [comment]
Would dropping the "any" help.  I just don't want to avoid the over-rotation that specifically identifying Initial here would have: "so just the Initial, but not Handshake or packets with short headers..."

**Comment by martinthomson** [comment]
Closed with #1151.
