### ISSUE TITLE
The 32 octet overhead

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1127]
The draft currently notes that the 32 octet per-record overhead that HPACK uses for accounting might need re-evaluation.

Having implemented QCRAM, per-record overheads didn't change for a decoder, so I would say that the 32 octet value is fine.  If this is OK, we should still track the fact that the issue was raised and discussed.  If not, this is a great place to air concerns.  For instance, maybe the HPACK overhead was wrong in some critical way, but I've not heard anyone suggest that.

**Comment by afrind** [comment]
The encoder needs to track more things than it did before for the same size decoder table.  Of course, that's entirely the encoder's problem, and the encoder can choose to use fewer table entries to compensate.

**Comment by martinthomson** [comment]
Yes, the encoder can track significantly more than a 32 octet overhead, but, as you say, that's entirely at their discretion, so I think that's fine.

**Comment by MikeBishop** [comment]
Encoder can track as much or as little as it wants.  IIRC, the idea was that you need a pointer and length each for name and value.  An eight-octet length for an HPACK entry seems a little extreme, but platform-standard types....

**Comment by MikeBishop** [comment]
Re-opening as editorial -- if we've decided that 32 is fine, we need to remove the text from the draft that says it's not.
