### ISSUE TITLE
Referencing strategy

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1129]
(This is a little more nebulous than my other issues, but I think that there are concrete things that can be written down that will improve things.)

Referencing entries near the end of the table in a new header block is hazardous. If you just compress as you do in HPACK, you can end up pinning entries in the header table, making it impossible to add new entries. Thus, you have to stop referencing entries as they get nearer to the table capacity limit.

The draft isn't particularly good about explaining this exposure or outlining strategies that might be used to manage this (or the impact it might have on the selection of header table size, for example).

One framework for thinking about this is probably:

An encoder attempts new header fields to the header table at a certain rate.  Under ideal conditions, the insertion of header fields is never blocked by outstanding references to entries that might be evicted as a result of the insertion.  Under these ideal conditions, header fields enter the table at some rate, H.  Note that a new connection might see a higher rate of insertions, but the expectation is that the empty table will be able to absorb those insertions.  That is, H averages out in the long term to |H|.

New removals from the table are possible after one round trip if the header field is not referenced in that round trip.  Thus, an encoder preserves its ability to insert at a rate of |H| if it refrains from using the last |H|\*RTT of the table.  To allow for both delays in delivering acknowledgments and variance in RTT and H, an encoder might choose to use a higher value that takes variance into consideration.  In extremis: (Mh\*|H| + Nh\*Hvar)\*(Mr\*RTT + Nr\*RTTvar) where Mx > 1 and Nx > 0.  An encoder could measure these values and adapt the amount of buffer it reserves, or choose typical values.

A decoder should allow for this safety margin and - assuming no other constraints on space - set a table size that is this amount larger than is ideal for compression.  A decoder has to choose values based on typical (or some percentile, e.g., 90th) values, because it can't resize the table for each connection.

**Comment by dtikhonov** [comment]
What is *rate*? In particular, what is the denominator?

Does there exist an effective referencing strategy without making the encoder learn more about the outside world -- RTT, what time it is?

**Comment by MikeBishop** [comment]
And (mostly as a note for whichever of us writes this PR), note that there's no pinning problem with a duplicate instruction referencing entries in this range, so the encoder algorithm should still look for matches, then encode as a duplicate, then a reference to the new entry.

**Comment by dtikhonov** [comment]
> the encoder algorithm should still look for matches, then encode as a duplicate, then a reference to the new entry.

The encoder does not have to encode an entry as a duplicate each time it uses it, does it?

**Comment by afrind** [comment]
Duplication is never required.  It's just an optimization to keep important headers in the table when they are near the end.

**Comment by MikeBishop** [comment]
The proposed algorithm is that the encoder should segment off the last part of the table as "risky to use."  In this proposed algorithm, entries in that region shouldn't be used, but a good alternative is to duplicate them and then use the newly-added non-risky entry.  (Although a reference to it has the potential to block.)

Obviously, this is just a sample algorithm, and implementations can choose different approaches, either more aggressive about duplicating or less.

**Comment by martinthomson** [comment]
That is the algorithm that my implementation follows.  I always choose to risk blocking.  You only get blocking if the frames are separated in transit, and proximal writes increases the chances of landing in the same packet.

**Comment by krasic** [comment]
Complementary to preventing blocked evictions, another tactic might be to duplicate whenever a reference is generated for an index that requires or is close to the point that requires more than one byte to represent.     e.g. if indicies < 128 require one byte, and all others require tow or more.   Then whenever a reference to entry >= (128 - epsilon), duplicate.     This could save quite a few bytes if there would otherwise be a time window when an entry that requires more than one byte is popular.

**Comment by afrind** [comment]
I'm not sure there's any design work that needs to come of this issue, but editorial work in a section describing different possible approaches to reference strategy.

I think it makes sense to describe the 'draining index' algorithm, and also Buck's proposed optimization.  I'm somewhat skeptical many implementations are going to go to the length Martin described in choosing how much free space to keep in the table.
