### ISSUE TITLE
Base and the Static Table

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1130]
It is not explained at all that the base is applied to the dynamic table only.

That is, index 1 is a straight index into the static table and that index 62 will use the current number of inserts and the base to determine the actual index into the dynamic table (this is the first table entry only when the number of table inserts and base are the same, if the base is smaller, then it will be further along the table).

To be clear, my logic for finding entries is (absent some other bounds-checking, that real code cannot safely omit):

```python
    if i <= 0: error
    if i <= len(staticTable): return staticTable[i-1]
    delta = tableBase - base
    if delta < 0: error
    return dynamicTable[i - len(staticTable) - 1 + delta]
```

It is probably equally valid to assume that the indices for the static table also increment with each iteration of base, but that leads to approximately the same code anyway.

**Comment by afrind** [comment]
Perhaps another argument for using separate namespaces for static and dynamic indexes?

**Comment by martinthomson** [comment]
Possibly, though I'm not convinced that the separation would be worthwhile.  Especially if we can reclaim more bits for references by making the instruction opcodes shorter.

**Comment by MikeBishop** [comment]
In your proposed shorter instructions, we could just use the next bit to differentiate static/dynamic.  If we increase the size of the static table, they're equivalent (~128 entries); with the current size, the current arrangement is slightly more compact (albeit less clear to interpret).
