### ISSUE TITLE
qcram document title should include the term "QCRAM"

### ISSUE THREAD

**Issue by reschke** [quicwg/base-drafts#1133]

**Comment by afrind** [comment]
It may be too late to ask this question, but I thought I heard someone say we should have reserved the name 'QPACK' for our final design choice.  Have we burned that bridge, and if not, should we  rename QCRAM to QPACK, especially given how similar QCRAM is to HPACK?

**Comment by ianswett** [comment]
I was thinking the same thing last night in regards to renaming QCRAM to QPACK.  I think it may reduce the confusion about what QCRAM is.

**Comment by MikeBishop** [comment]
HAHAHAhahahHAHahaha.......  🤣🤣🤣

**Comment by MikeBishop** [comment]
More seriously, I have no objections.  The name is irrelevant to the technical merits, and if it improves the understanding of folks who weren't part of the design team, call it whatever you want.

**Comment by krasic** [comment]
+1

**Comment by afrind** [comment]
If no one objects, I'll make the change from QCRAM to QPACK at the end of the week.

**Comment by MikeBishop** [comment]
Worth changing the doc name as well, even though it means another -00?

**Comment by janaiyengar** [comment]
+1 -- QPACK SGTM

**Comment by afrind** [comment]
Renamed to QPACK and included in the title
