### ISSUE TITLE
Non-blocking decoder

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1140]
The QCRAM draft currently enables an encoder to operate in blocking or non-blocking mode, because the encoder always knows which header blocks have been processed by the decoder.  However, there's currently no mechanism for a decoder to require an encoder to operate in non-blocking mode.  During design team discussions, this seemed to be a desirable property -- do we want to add a setting to support this?

There was also some discussion that a decoder which permitted blocking might still want to constrain how many blocked decoder instances it had, and therefore put a bound on the number of blocking QCRAM frames which should be permitted.

**Comment by afrind** [comment]
If we made this a SETTING, is that too late, considering 0RTT?  Would a client be able to use a previous setting value, and what happens if the client then ends up violating a server's new maximum blocking frames?

**Comment by dtikhonov** [comment]
The client does not have to reference vulnerable entries until the second flight (assuming a single first request) and once the server response, its position regarding blocking avoidance becomes clear.

**Comment by MikeBishop** [comment]
Or we say that, like max table size, this is one of the settings the client must remember with the 0-RTT ticket, and the server can't accept 0-RTT if it wants to be stricter than it was.

**Comment by dtikhonov** [comment]
> Or we say that, like max table size, this is one of the settings the client must remember with the 0-RTT ticket, and the server can't accept 0-RTT if it wants to be stricter than it was.

This will punish servers that decide to remove a potential source of latency by introducing latency at the start.

**Comment by MikeBishop** [comment]
But only for the first connection after a change, just like any other setting where the client has to remember the value.  It's not like we're saying they're forever barred from using 0-RTT.

**Comment by dtikhonov** [comment]
Depending on the usage pattern, that penalty may be incurred by most connections.

On the other hand, if the client begins in avoidance mode, it incurs no penalty unless it packages more than one requests in the first flight.  Also, the requests in the second flight have no vulnerable entries.

**Comment by martinthomson** [comment]
Anything we do for 0-RTT should be consistent with QUIC itself.  That is, if the server can't honour the limits it knows to apply to 0-RTT, then it has to reject 0-RTT.  And the corollary: if the server wants to decrease limits, it has to reject 0-RTT.

**Comment by martinthomson** [comment]
I'm a little conflicted about this proposal.  It seems like it might be valuable, but then I have a serious aversion to options.  The added uncertainty about the value prior to receiving SETTINGS isn't a concern though: you can't use the table at all if you don't have settings.

**Comment by MikeBishop** [comment]
I'm not sure that's true, or at least not stated.  In HTTP/2, the client has to act without seeing the server's settings.  In HTTP/QUIC, the client will probably either have 0-RTT memory or the SETTINGS frame in 0.5 RTT, but we don't currently have a prohibition on the client sending requests without seeing the SETTINGS frame.

**Comment by martinthomson** [comment]
If we set the header table size to 0, the point remains: you can't use the table until you get SETTINGS.

(BTW, the current text on settings is poorly aligned with QUIC transport parameters, which should be fixed.)

**Comment by afrind** [comment]
I think the decoder needs to be able to declare some maximum value for the number of blocking references it will queue, rather than a boolean on/off.  Unbounded queues are bad.  True having Depends up front allows the decoder to leave the bulk of the compressed block in the transport, but the doing so could end up consuming a large amount of flow control space and memory in that case -- it should still have a limit.

The spec should also recommend that an implementation set a maximum amount of time it will queue before closing the connection.
