### ISSUE TITLE
Header table size change

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1142]
QCRAM doesn't afford the encoder the ability to specify the table size it is using, which is a takeback from HPACK.  In QCRAM, the encoder is using the maximum table size permitted by the decoder regardless.  Are we okay with that?

HPACK broke the "maximum you can use" and "size I am using" pieces apart because, although the encoder can choose to mostly-forget entries that are above the size it uses, the decoder is left tracking useless items.  (Also, it allows the encoder to play tricks like setting the table size to zero and then returning it to the previous size to flush the table on an idle connection.)

**Comment by martinthomson** [comment]
There is no reason why an encoder can't use the table resize instruction in the current design.  Or, maybe a prune instruction that causes old entries past the cutoff to be flushed.  Either is easy to add or implement.

It messes with your nice proposal for 4 instructions, but other than that, it could easily work.  We could put an octet on the start of table update if you wanted to preserve the clean instruction separation.

**Comment by afrind** [comment]
The encoder needs to be able to have its own limit, since a malicious client can try to tell a server that it wants a really big table for decoding, which can lead to memory DoS.
