### ISSUE TITLE
Version Negotiation Routing Problem

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#1146]
The invariants draft mentions the version negotiation packet.

If QUIC moves to asymmetric connection ID's it may become a problem because the connection ID may be used to route through middleware at both endpoints.

It is also not clear that the version negotation packet is indeed a version negotiation packet is a version negotiation packet because the only reliable information is that it is a long header format. Therefore it is hard for middleware to make exceptions for that packet, assuming it could then route the packet correctly, which is not a given.

Of course there are also details about the length of the connection ID, which have not been settled, but I trust that will be updated once decided.

**Comment by mikkelfj** [comment]
https://github.com/quicwg/base-drafts/pull/1151 will resolve this issue.

**Comment by martinthomson** [comment]
I don't see how #1151 fails to fix this.  The client puts its preferred value in the packet it sends and the server has to use that value.  These values are available to all middleboxes on the path.  No exception is needed for Version Negotiation.

**Comment by mikkelfj** [comment]
@martinthomson I really like the changes in #1151 and it does solve most concerns. You argue my remaining issue is a matter of expections and that it is not specific to vneg:

The concern is that the server and the TLS handshake places some restrictions on the initial client source CID because it is required to be random. If the client exists in a complex p2p server network it might want detailed control of routing bits in CID. A middelbox could do NAT style routing setup and remember the CID for reverse routing, but that is an assumption on infrastructure. In particular the reverse route might take an entirely different path so NAT won't work at all. Encrypting the CID is an option even if less than 16 bytes, but not all infrastructure might want to do that.

At the same time there are (or ought to be) requirements on CIDs to be unique per tuple and for linkability concerns etc. so there is a broader discussion on what a CID must fulfill. Since a CID is allowed to be zero length, it cannot be very hard requirements in general.

So, removing randomness restrictions on CIDs and in place provide recommendations or requirements for specific usecases (linkability) would remove the concerns I still have.

Note that randomness is less important now that the server can always choose it's own CID.

**Comment by martinthomson** [comment]
Only the destination connection ID needs to be random in that proposal.  The client sets the source connection ID in the Initial packet to whatever it likes.  The idea there being that the server will use this value in its destination connection ID on the return path.

**Comment by mikkelfj** [comment]
Oh, maybe I'm not thinking clearly here. In vneg dest is random, fine. On normal handshake destination is replaced by servers chosen source. And then both CID's are free. Yes.

**Comment by martinthomson** [comment]
Close this then?

**Comment by mikkelfj** [comment]
I'd say its pending on the PR, but close it if you like.
