### ISSUE TITLE
Connection migration

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#115]
There are a bunch of things that need to be addressed here.  What is likely to happen is that this issue will turn into many smaller issues and this will eventually get closed as those become better understood.

1. Reasons migration might be needed (mobility, NAT rebinding, routing changes, etc...)
2. Routing considerations when migration occurs
3. Privacy implications of linkability across migrations
4. Verifying consent to send on a new path
5. Establishing any desired middlebox state along the path

**Comment by martinthomson** [comment]
One more to add: congestion state reset for the new path.

**Comment by mnot** [comment]
Discussed in Tokyo. Need to discuss in a wider forum; target for Chicago.
