### ISSUE TITLE
hq: Can we have payload diagrams for all frames?

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#1158]
Hi,

I've been caught out again by HTTP/QUIC doc's "inconsistent" approach to diagramming the payload of frames. Specifically the `GOAWAY` frame in this case but it affects other frames too.

I appreciate a diagram for a single field is a bit of overkill, however I think it is of value and I would be happy to prepare a PR to do so. Comparing HTTP to Transport, there are diagrams for MAX_STREAM_ID, BLOCKED, PATH_CHALLENGE etc

**Comment by MikeBishop** [comment]
I thought @martinthomson had filed an issue requesting this as well, but I don't see it.  By popular demand, I'm willing to add them, but would gladly accept a PR.

**Comment by LPardue** [comment]
Ok let me see what I can come up with...
