### ISSUE TITLE
Each COPT might be better as empty transport parameters

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#116]
COPT is apparently repeated, once for each option.  

One thing that TLS implementations do is validate that there is only one instance of each extension.  This isn't possible for transport parameters if we require that COPT be used for a list of options.

Also, we can reduce the number of extension points in the protocol, we shouldn't pack a list of options into COPT when we have transport parameters for that.

**Comment by martinthomson** [comment]
Note: If there are values for connection options that should be included in the base specification, each need to be raised separately.

**Comment by MikeBishop** [comment]
Per discussion with Jana, this isn't what it looks like.  It's basically a tunnel for the client to relay opaque data from Chrome experiment configurations to the server, so the server can behave appropriate to the experiment on the given connection.

I'm not sure opaque data relay is needed in the RFC in the first place.

**Comment by martinthomson** [comment]
OK, that is actually entirely appropriate, in a way.  Of course, we would ask that Chrome/Google use an option number from the space reserved for experiments, but they can do what they please in that space.  That said, we don't need to register the number for them.

**Comment by martinthomson** [comment]
Discussed with @janaiyengar, these are OK to remove (Google can use proprietary codepoints).  Will be addressed by #122 (once I clean it up).

**Comment by martinthomson** [comment]
Closed with #122.
