### ISSUE TITLE
Moving version before connection ID in the long header

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#1166]
As I mentioned on PR #1151, if we change to asymmetric connection IDs with variable length, it would be ideal to have the version come before the connection IDs in the long header, because then it would be at a fixed offset and the destination connection ID would also still be at a fixed(but 4 byte later) offset.

Due to the importance of Connection ID, there is no intent to remove Connection ID from the invariants, though this change may enable some extra flexibility far down the road.

**Comment by helpingothers4u** [comment]
I cannot remember my password and I am on my phone now that is my kindel
I'm trying get on in

Angela Risner
