### ISSUE TITLE
Is 0RTT allowed after HRR?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#1168]
When a client attempts a 0RTT handshake and gets a Retry from the server, can that client retry with another 0RTT handshake attempt, or does it need to fall back to 1RTT?

(Hit this issue during interop. My client sends an initial CI+0RTT packet pair, receives a retry, and then resends a new CI+0RTT packet pair. Is this permitted?)

**Comment by ad-l** [comment]
Note that the TLS 1.3 spec forbids the client to send the `early_data` extension after a `HelloRetryRequest`
https://tools.ietf.org/html/draft-ietf-tls-tls13-24#section-4.1.2

**Comment by larseggert** [comment]
@ekr said on slack:

> 0-RTT after retry is forbidden in TLS 1.3
> It's not like it somehow couldn't be made to work, we just concluded it was too confusing

and later

> TLS 1.3 *does* allow you to do a HRR with no other requested changes. We put that in so it would work with DTLS 1.3.

**Comment by larseggert** [comment]
I think that means that 0RTT after retry is *not* allowed

**Comment by MikeBishop** [comment]
Given that we're trying not to modify TLS rules when running in QUIC, I'd agree.  Do you think we need text reminding implementers of this?

**Comment by larseggert** [comment]
I think that would be helpful. I will add that when I did the 0RTT stuff in quant, and Jörg did it for pandora, we both found that part of the spec to be pretty underspecified. Pretty much the only thing that explains the details is Figure 3 in -tls.
