### ISSUE TITLE
SCUP

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#117]
What is SCUP and do we need it?

**Comment by martinthomson** [comment]
Proposal: remove it.  This is currently Google proprietary.

**Comment by ianswett** [comment]
We should remove it. 

We already have a way to send new resumption info via the crypto layer, so I think that completely replaces the SCUP functionality.

**Comment by vasilvv** [comment]
I suggest that we remove SCUP and put any functionality it had into the NST messages (or any other post-handshake TLS messages we'd need to define).

**Comment by mnot** [comment]
Discussed in Tokyo; kill it.
