### ISSUE TITLE
Ban trial decryption in TLS stream after rejected early data?

### ISSUE THREAD

**Issue by knekritz** [quicwg/base-drafts#1172]
TLS 1.3 early data requires trial decryption after rejecting early data to skip over the records encrypted with 0-RTT keys that cannot be decrypted before you get to the client finished. In QUIC there will be no app data 0-RTT records, and the EndOfEarlyData is required by TLS to only be sent if early data is accepted, so there will be no records to skip but a TLS implementation will still likely set its record layer to skip TLS records that fail decryption.

**Comment by martinthomson** [comment]
Seems reasonable to allow the stack to disable trial decryption.  I wouldn't require this though, because that might be more intrusive than stacks might like (for instance, I doubt that we would provide a knob for this in NSS).
