### ISSUE TITLE
Closing or draining state after idle timeout?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#1178]
Section 7.9.1 says:
> An endpoint enters a **closing period** after initiating an immediate close (Section 7.9.3) and optionally after an idle timeout (Section 7.9.2). 

But Section 7.9.2 says:
> A connection enters the **draining state** when the idle timeout expires.

Which is it?

**Comment by martinthomson** [comment]
Hmm, I think that it has to be draining.  Without a CONNECTION_CLOSE to signal an end, both endpoints could enter closing and that would be bad.

**Comment by larseggert** [comment]
Shouldn't a *_CLOSE frame be sent prior to that? Otherwise the other side needs to wait for an idle timeout, too.

**Comment by martinthomson** [comment]
Yes, but the expectation is that both peers hit this at about the same time.

**Comment by larseggert** [comment]
Why would that be? Both can use different idle timeouts.

**Comment by martinthomson** [comment]
The minimum of the two applies.

**Comment by marten-seemann** [comment]
Why would that be? A server might want choose a much shorter idle timeout than a client.

**Comment by larseggert** [comment]
The minimum applies? Where does it say that?

**Comment by janaiyengar** [comment]
A server might choose a smaller value, but both sides should close when the earliest end times out.  The draft doesn't say anything about this, which is an oversight. I'll fix it.
