### ISSUE TITLE
Source Address Token encoding

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#118]
-transport currently has a TODO regarding the encoding of a source address token.

I would contend that we don't need to fix this.  This is a protocol from the server to the server.

**Comment by janaiyengar** [comment]
I agree. We could suggest what might go into one, but it's out of scope.

**Comment by martinthomson** [comment]
How about we keep this open for the moment.  If only to track the need to provide some suggestions.  Time, IP, and port seem fairly obvious, but we might some nicer framing.

**Comment by mnot** [comment]
Included in resolution to #52 and related
