### ISSUE TITLE
Add unknown packet version handling to invariants

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#1197]
#827 mentions that packets of unknown versions must be dropped.
But it is hard to make a version related requirement for a specific QUIC version, when clients can implement multiple versions.

**Comment by martinthomson** [comment]
The type of a packet is not an invariant, so what do you imagine we might do to distinguish "unknown" here?

**Comment by mikkelfj** [comment]
Sorry for being unclear - I meant to express the same as #827 does and the commit that resolves it:

"If a client receives a packet that has an unsupported version, it MUST discard that packet."

I'd say this ought to be an invariant because otherwise versions could disgree on this.

**Comment by mikkelfj** [comment]
I'm not sure this really needs to be addressed the invariants already says:

"A QUIC endpoint that receives a packet with a long header and a version it either does not understand or does not support sends a Version Negotiation packet in response. Packets with a short header do not trigger version negotiation and are always associated with an existing connection."

It just doesn't say what to do after a connection is established, but that might be splitting hairs, so closing.

**Comment by martinthomson** [comment]
I see.  Yes, we have that text (though it suggests that a client sends VN, which is probably wrong).  I'll fix that.
