### ISSUE TITLE
Decouple QUIC version and ALPN

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#12]
As per discussion at the meeting.  This will allow QUIC to evolve ahead of any updates to its higher layers.

**Comment by MikeBishop** [comment]
This is decoupled per the changes in #122 (which are mired in a separate discussion).  Whether #122 gets merged before -01 snaps or not, let's confirm that this issue is resolved acceptably at the interim.

In -00, the text was this:

> The ALPN identifier for the protocol MUST be specific to the QUIC version that it operates over.

The text in #122 currently says:

> The application-layer protocol MAY restrict the QUIC versions that it can operate over.  Servers MUST select an application protocol compatible with the QUIC version that the client has selected.

**Comment by mnot** [comment]
Discussed in Tokyo; same as #97, now a dup.
