### ISSUE TITLE
Use Conservative Initial Packet Size

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#1209]
The transport draft text on PMTU (8.4. Path Maximum Transmission Unit) says

... limit of 1280 followed by:
" Some QUIC implementations MAY wish to be more conservative in computing allowed QUIC packet size given unknown tunneling overheads or IP header options."

But the handshake requires banging against this limit, so it is not practical to reduce the limit in anticipation of tunnelling overhead.

There are two reasons for having the handshake at 1280: 1) to guarantee that 1280 really is available and force infrastructure to respect this, and 2) to discourage amplification attacks.

Perhaps it is better to set the handshake minimum to 1000 octets and encourage the use of 1280 for an initial PMTU unless additional tunneling concerns needs to be addressed. Alternatively edit the discussion on PMTU because it is not practical to reduce the size with the current handshake.

As discussed on list, it is often the case that ether frames have 1500+ octets, but when tunnels get layered, this might not be enough.

**Comment by martinthomson** [comment]
The path needs to support v6, and this suggests that the path might not support v6.
