### ISSUE TITLE
Version downgrade vulnerability

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#121]
If we do this badly, there might be two versions of QUIC for which the transport parameters are confusable in a way that confounds the validation of version negotiation because the transport parameters are interpreted differently for different QUIC versions.

We need to write that into the security considerations.  We might recommend preserving the initial part of the transport parameters extension, or - better yet - using a new extension codepoint when the format needs to change.

**Comment by martinthomson** [comment]
Marking as design to improve visibility.

**Comment by hardie** [comment]
So, just to be sure I understand this:  Client engages in version negotiation and claims to be version N.  The validation step would be an effort to confirm that transport parameters conform to N.  You're concerned that version N+1's use of that set of parameters would retain the same form but have a different meaning; in that case, validation by syntax doesn't work.  

If that's right, I agree that having design/security considerations highlighting the issue is reasonable and recommending that when the semantics of a syntactical element need to change a new codepoint should get assigned.

**Comment by martinthomson** [comment]
@hardie, yes you got it.

**Comment by MikeBishop** [comment]
I'm not certain I did, though.

If the server declines to speak N, it won't look at the handshake, and therefore won't ever attempt to interpret the transport parameters.  If they do a negotiation round-trip and wind up on N+1, the client would send fresh parameters in format N+1.

Are we guarding against a client bug where they accidentally reuse their original transport parameters in the new version, or where semantics "leak" between versions in a client that supports several?

**Comment by martinthomson** [comment]
The attack here is that you have a change in the *structure* of the transport parameters such that a client might construct transport parameters from version N, but due to the version negotiation being attacked have them interpreted as being version M.  That could be in a way that ensures that the server thinks the client is OK according to the server's version M interpretation; at the same time the client could see the server's version M parameters as valid according to a version N interpretation.

If you don't think that sounds likely, imagine moving the version fields in #122 to a parameter and follow the logic through.  It is plausible, if unlikely, that the two variations could be interpreted as being correct when evaluated under a different schema.

**Comment by martinthomson** [comment]
I think that this just needs some text as Ted observes.

**Comment by janaiyengar** [comment]
What in the transport params is used to validate a version negotiation? At the moment, we use only the packet number in the VN packet to verify that the packet was sent by the server.

**Comment by ekr** [comment]
The check is in the completed handshake. See:
https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.7.3.4
