### ISSUE TITLE
confusing Fast Retransmit modes

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#1212]
The loss recovery spec describes two different (and mutually exclusive) Fast Retransmit modes: one detects reordering in packet number space, the other one in time space.

The Fast Retransmit section is not clear about the fact that implementations have to choose one or the other mode, and just mentions time reordering at the very end.

Furthermore, I find the pseudo code for `DetectLostPackets` pretty hard to read, since depending on the mode, different variables are set to infinite and then used in comparisons. It would probably be easier to provide two different definitions of this functions depending on the mode.

I'd be happy to write up a PR, if people agree that the current text needs improvement in that direction.

**Comment by ianswett** [comment]
Agreed, though technically both of these could run at once, I think it's best to describe them as two mutually exclusive modes.

A PR to improve the text and pseudocode would be appreciated, thanks.

**Comment by siyengar** [comment]
ya there's some places which use the delayUntilLost for for time space for the early retransmit threshold. It might be nice to separate those two out to show that early retransmit is always active.

**Comment by pravb** [comment]
I don't think these are mutually exclusive modes. With TCP today we do both, if the SACK information suggests lost packets or RACK kicks in and marks packets lost. Time based detection cannot work for low latency connections due to lack of fine grained timers so you always need to augment with packet based detection. IMO an implementation should do both.

**Comment by martinthomson** [comment]
@ianswett, you seem to think that this is editorial, but it is still labeled design.  It's clearly a hot issue.  Do you have a plan to fix it?

**Comment by janaiyengar** [comment]
Closed by #1974
