### ISSUE TITLE
inconsistent definition of the TLP duration

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#1220]
The text says

> The alarm duration, or Probe Timeout (PTO), is set based on the following conditions:
> * PTO SHOULD be scheduled for max(1.5*SRTT+MaxAckDelay, 10ms)
> * If RTO (Section 3.3.2) is earlier, schedule a TLP alarm in its place. That is, PTO SHOULD be scheduled for min(RTO, PTO).

The second point is missing in the pseudo code:
```
else if (tlp_count < kMaxTLPs):
      // Tail Loss Probe
      alarm_duration = max(1.5 * smoothed_rtt + max_ack_delay, kMinTLPTimeout)
```

**Comment by pravb** [comment]
Yes this is needed otherwise the alarm duration could be too conservative in some cases.

**Comment by ianswett** [comment]
Agreed, the psuedocode should be updated to include this.
