### ISSUE TITLE
ACK frame timestamp format

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#123]
It may be possible to simplify the ACK frame, in particular, the timestamp section. We could conceivably make the "Time from Largest Acked" 16 bits, and simply have N-Timestamp-blocks, including this one. I think this is plausible.

**Comment by martinthomson** [comment]
It could be even simpler if you had a time since the last timestamp.  Start with the timestamp of the largest acked, then each entry is the delta to the last.  That gives you greater resolution overall.

**Comment by martinthomson** [comment]
@janaiyengar, Is this a duplicate of #109?

**Comment by janaiyengar** [comment]
Closing, since dup of #109
