### ISSUE TITLE
Do we still need Retry packets?

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#1233]
After the recent header changes, there's no need for a Retry packet type any more. The server could send its HRR in a normal Handshake packet.

**Comment by siyengar** [comment]
ya i agree with this. The TLS stack on the client already knows whether it is a stateful or a stateless retry, and can act accordingly. Serializing the information the client already knows into a frame type is redundant and error prone.

cc @mcmanus

**Comment by mikkelfj** [comment]
It depends - the frame type may help to decide between different CID's which helps lookup and reduce conflicts - but I'm not sure it is an issue in this direction.

**Comment by ianswett** [comment]
I can't come up with a clear reason for them.  The crypto handshake is going to have to indicate that the reset is stateful or stateless, and the transport is going to have to respond accordingly, so I haven't been able to determine what value the extra packet type provides.

**Comment by ekr** [comment]
@siyengar: How does the client know whether it's a stateful or stateless retry? They look the same in TLS. It's just an HRR. It's only the server that knows

**Comment by ekr** [comment]
Oh, I see you're going to claim it has a cookie or it doesn't. But that's not actually the same thing, because you might be using the cookie just to require a proof of reachability as an anti-crypto DoS mitigation

**Comment by siyengar** [comment]
@ekr I think the client shouldn't know what the difference is between those two cases and should react the same way. For the clients it's a stateless reset either way.  My thought here is that the TLS layer provides an API to say whether or not the message that was received was a stateless reset.

Generally I'm leaning towards the principle that if an endpoint can know about something via an API, we shouldn't need to signal that in a framing layer.
