### ISSUE TITLE
Allow repeat ACK's

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#1234]
It is an unfortunate that requirement that "SHOULD NOT be ack'ed again":

You want to ack packets again because you collapse gaps into larger blocks. Only the oldest ACK'ed block should not be acked again. It also leads to unnecessary bookkeeping.

**Comment by marten-seemann** [comment]
At the point where you received an ACK for an ACK, 1 RTT has passed, and there's no need to include any packet lower than the largest acked in new ACK frames, even if you received a heavily reordered packet. By that time, this packet will have been retransmitted anyway.

**Comment by martinthomson** [comment]
The text uses a SHOULD, which is entirely appropriate here.  If you have an idea of how to codify more concrete advice, we would be interested in receiving a PR.
