### ISSUE TITLE
PING guidance

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#1240]
It is unclear how fast an endpoint should respond to PING so some clarification would be useful.

It could be no later than when the delayed ACK timer expires because this is the latest an ACK can be deferred. But it could also be expected to be ASAP and used for timing data, or it could be application dependent.

There is also a potential for abuse - as others have pointed out recently, just adding PING to ACK frames can force the hand of the peer. But, if PING is responded to particularly fast, this could be worse than with normal delayed ACKs.

**Comment by martinthomson** [comment]
With PATH_CHALLENGE, the current text is fine.  PING is acknowledged, as normal.
