### ISSUE TITLE
UDP-like, not exclusively UDP

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1250]
@enygren suggests:

Would it make sense to say that "endpoints exchange QUIC packets via a datagram protocol such as UDP"?  While we are currently only defining on UDP, there is nothing in invariants that would force this perpetually.

**Comment by larseggert** [comment]
Let's get an IP protocol number :-)

**Comment by ianswett** [comment]
From the first sentence of the charter: "The QUIC working group will provide a standards-track specification for a UDP-based, stream-multiplexing..."

So I'm biased towards saying this is QUICv2.

**Comment by martinthomson** [comment]
I think that it is reasonable to say that we are developing invariants that are based on UDP.  In doing so we make no claims about the use of QUIC over other substrates (such as IP directly).  That seems perfectly OK.

This is invariants, so it can't be v2.

**Comment by ianswett** [comment]
The invariants don't say anything about non-UDP substrates, as you note, so I think it can be v2, because non-UDP substrates are out of scope.

**Comment by huitema** [comment]
V2, please!

**Comment by pravb** [comment]
agreed, v2 or later.

**Comment by MikeBishop** [comment]
I think the/another problem with this is that, unlike TCP, QUIC doesn't have port numbers -- it leaves that concern to UDP.  If we want to work atop something other than UDP, then we need to replace that multi-recipient functionality (or build atop something with equivalent recipient-demuxing capability).

Or say that QUIC is a per-device service in a non-UDP environment and use connection IDs to demux.  ;-)

Regardless, this is outside our charter as noted on the list.  We're explicitly chartered to define QUIC over UDP.  I'm inclined to close this with no action on that basis.

**Comment by mikkelfj** [comment]
Charter or not, it would be considerate to at least contemplate non-UDP designs, especially if this can be done with minimal impact. With dual connection ID's I don't see a strong need for port numbers - there might be some corner cases in handshake, and there might be some text that isn't sufficiently clear in this regard, but fundamentally this ought to be workable.

For example sensor networks using a minimal size connection ID dropping all data at IP/DUP layer and leaving any external routing to a gateway that  understands 8-bit CID's through an out of band configuration.

**Comment by martinthomson** [comment]
Based on the feedback thus far and [Section 3](https://quicwg.github.io/base-drafts/draft-ietf-quic-invariants.html#an-extremely-abstract-description-of-quic), I'm going to close with no action.  That doesn't mean that we're not going to ignore other substrates, only that our invariants are UDP-specific.

For all those who said v2: ![](http://3.bp.blogspot.com/-yiLSMXBJbVo/UrT9aN9hwRI/AAAAAAAAHJk/U_KfssGpG6U/s1600/picard-facepalm.jpg)
