### ISSUE TITLE
How to recover from loss of 3 Handshake packets without receiving PATH_RESPONSE

### ISSUE THREAD

**Issue by tatsuhiro-t** [quicwg/base-drafts#1257]
Draft 10 introduces PATH_CHALLENGE and PATH_RESPONSE, and it imposes a restriction on server that it cannot send more than 3 Handshake packets without receiving a packet from a verified source address.  The guidance is include PATH_CHALLENGE in each packets and wait for PATH_RESPONSE from client.
What if all 3 Handshake packets are lost?  ACK is also lost, client just keeps re-sending its Initial packet (note that Initial packet cannot include PATH_RESPONSE).  Server has sent 3 Handshake packets, so it cannot send any more packets.

**Comment by martinthomson** [comment]
The intent, as I understand it, was 3 packets out for every 1 in.  Is that the understanding?

**Comment by ianswett** [comment]
Martin's correct, that was the intent.

**Comment by tatsuhiro-t** [comment]
I think it would be nice to clarify this by explicitly saying that it is per received packet.

**Comment by martinduke** [comment]
Please do so, and make it clear that it's a *decryptable* packet with a unique packet number (assuming that's correct)

**Comment by martinthomson** [comment]
This was addressed in the stream0 design team changes.  Don't send more than 3 datagrams without receiving acknowledgments, and any acknowledgment is enough to provide address validation, after which any number is OK (short of limits on congestion control, etc...).  Reopen if you think we need more words.

**Comment by MikeBishop** [comment]
Any *acknowledgement*?  That seems odd, given how easy it would be to forge an acknowledgement of Initial packets with easily-guessed sequence numbers.  Clearly receiving anything under Handshake keys verifies actual receipt, though.

**Comment by martinthomson** [comment]
Imprecision in my comment only.  The text in the draft is clearer.  It says any acknowledgment with Handshake keys.
