### ISSUE TITLE
Separate transport parameters for 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#126]
TLS provides an extension that limits the amount of data that can be sent during 0-RTT.  This is an explicit configuration item, even though TCP flow control would naturally limit the amount of data a client can send to a server with 0-RTT.  The reason for this is that servers might have to hold some or all of the 0-RTT data.  That buffering might be part of replay mitigation, for example.  A server that supports 0-RTT can use that limit to ensure that it doesn't have to buffer more than it is willing to buffer.

In #122, I have chosen to carry over the values for initial flow control window and concurrent stream limit.  We might want to provide separate transport parameters for 0-RTT so that servers can apply lower limits.

**Comment by janaiyengar** [comment]
We could provide default minimums that are used by clients that have no server values yet.

**Comment by mnot** [comment]
Discussed in Tokyo; agreement in the room that parameters define defaults, and clients SHOULD cache parameters and MUST use default values if the client doesn't cache. The server always has the ability to kick unruly clients.

**Comment by martinthomson** [comment]
Not sure why this was reopened.  It is [fixed](https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#zerortt-parameters).
