### ISSUE TITLE
Invariants extensbility

### ISSUE THREAD

**Issue by pravb** [quicwg/base-drafts#1260]
If future versions of QUIC require us to add more fields to the invariants, how would we go about it? Would we add the fields after the PN or before it? We lack a field that specifies the offset to encrypted payload start and there will be no more reserved bits left if the spin bit experiment is successful.

**Comment by ianswett** [comment]
In the long header, it would need to come after the connection IDs.
In the short header, it could go anywhere after the first byte, since there are no constraints in the current invariants draft.

Can you clarify the issue?  Is this an editorial request for clarity on how future versions of the invariants might change from the current one, or something else?

**Comment by MikeBishop** [comment]
It seems a contradiction in terms to says that we would add something in a future version of the invariants.  These are supposed to be things which are true of *all* QUIC versions, and something we add in the future would, by definition, not be true of QUIC versions which precede it.  That makes it difficult for version-agnostic network components to observe it.

I think the first line of defense is to simply define them as version-specific, with the intention of including them in all future QUIC versions.  This does require version awareness on the part of the observer.  A more extended version might be a new document defining additional invariants which are true for all versions conforming to a particular version pattern (first byte of 0x01, for example).  This requires some version-awareness, but wouldn't require the observer to understand *particular* versions.

But most fundamentally is the answer I suggested and no one argued with during the call for adoption:  If the invariants differ, you're defining a new protocol which is not QUIC.  Describe *that* protocol's invariants (and hopefully how to demux it with QUIC) in a new RFC.

**Comment by pravb** [comment]
Both my education and a editorial request. I think it is important to state how extensibility will work in future. I think it is also important that we mark the invariant portions of the header some way in the transport draft diagrams of the headers, as otherwise a casual reader may assume other fields as invariant.

>>In the short header, it could go anywhere after the first byte, since there are no constraints in the current invariants draft.
The load balancers will need to know the location of the destination connection ID field for routing? Or are we expecting that the load balancers will need to become stateful and do version specific processing per connection?

**Comment by pravb** [comment]
Thanks Mike, it would be good to state this position in the draft. 

I suspect that we will see hardware terminating QUIC at some point (not that we have any plans around this). And at that point I see deployment issues if adding a few bits to cleartext requires defining a new protocol but this is speculation so I don't have any opposition to the approach.

**Comment by pravb** [comment]
Ian please confirm that location of connection ID in short header is invariant as stated by the draft and that any changes to headers in future will be after this field.

**Comment by martinthomson** [comment]
Based on the discussion here, I'm not seeing a concrete problem.

If there are some editorial changes that would improve clarity, we would consider editorial pull requests that did that.  If @MikeBishop would like to distill his comment about any future invariants wouldn't really be invariant, then that would be appreciated.

**Comment by pravb** [comment]
Agree with closing. Same request to @MikeBishop as @martinthomson.
