### ISSUE TITLE
error handling for path_response

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#1265]
>   If the content of a PATH_RESPONSE frame does not match the content of
>   a PATH_CHALLENGE frame previously sent by the endpoint, the endpoint
  > MAY generate a connection error of type UNSOLICITED_PATH_RESPONSE.

I think this is a footgun - we should just say MUST ignore.

PATH_RESPONSE is not sent reliably but PATH_CHALLENGES are regenerated as needed. So you've got a non-deterministic system because you have to timeout things.

If we want to keep the error then I think these frames ought to be considered reliable so a deterministic call can be made.

But I think the better route is to just ignore a RESPONSE you're not going to do anything with.

**Comment by mcmanus** [comment]
I know it says MAY - I just think this is mostly an opportunity for a broken implementation with very little upside... so bad design.

**Comment by martinthomson** [comment]
If you are certain that you never sent the challenge (say that you include a MAC), then why not permit the error?

**Comment by mcmanus** [comment]
I think I stand by 'footgun' - its not impossible to do but the value is small and the opportunity for screw up is disproportionate.

Its just based on experience of reading the provision in the text and starting off to build a system to enforce it (because I too enjoy strong protocol hygiene) .. and after getting down the road aways realizing that a full definition of this was madness.

Do we have a general provision regarding MAY PROTOCOL_VIOLATION as a reaction to a MUST (NOT) violation? That might be the right level of emphasis rather than a specific error code.

**Comment by martinthomson** [comment]
I'd be OK with removing the error code.  This isn't separately actionable, so PROTOCOL_VIOLATION is entirely appropriate.

**Comment by janaiyengar** [comment]
This seems fine. I don't think the error gives us much anyways.
