### ISSUE TITLE
Frame header reserved bits

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#127]
HTTP/2 compatibility at the framing level is a bit of an unrealistic goal.  Maybe we could just avoid allocating those bits first.

**Comment by MikeBishop** [comment]
This plays into #81.  There were certain vocal proponents of re-using their HTTP/2 parsing code as far as possible.  If/when we conclude that it's really silly, I'm more than happy to rip those out.  ;-)

**Comment by MikeBishop** [comment]
Note that without reserving HTTP/2 bits, no header type defines more than one flag bit.  I think the acrobatics required to save that extra byte might be more than it's worth, but the option exists.
