### ISSUE TITLE
[Congestion control] How to decrease the congestion window

### ISSUE THREAD

**Issue by scw00** [quicwg/base-drafts#1272]
We may lost a lot of packet for one Network fluctuation and server may response for the  received packets(after the lost packets) with several ack frames .  Every packet will trigger client to decrease the congestion window .

I'm not sure how to send ack frame correctly , or did I miss something ?

**Comment by martinthomson** [comment]
Questions like this should be asked on the [mailing list](mailto:quic@ietf.org).
