### ISSUE TITLE
Better define reaction to various connection migration failures

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1277]
In @ekr's review of the connection migration draft, he noted that "failure" is rather imprecise.  Does receipt of a PATH_RESPONSE from the wrong address mean that the path is considered invalid, or do you treat that just like loss and keep sending PATH_CHALLENGE?  This could be better defined.

**Comment by dtikhonov** [comment]
This issue seems stale.  Is it still relevant?

**Comment by MikeBishop** [comment]
I think https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-failed-path-validation answers this.  Let's close.
