### ISSUE TITLE
Order of Coalesced Packets

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#1287]
I am implementing the QUIC compound packets and I am coming across some implementation pain points related to the order of processing the packets in the UDP payload.

Generally, I have a model of "current buffer pointer" and "bytes left" and this continues though the UDP payload, processing QUIC packets until it runs out of space, encounters an invalid packet header that prevents any further processing, or it encounters a packet that requires a particular key to decrypt, that we don't have yet.

1. This model doesn't work if the client Initial packet isn't the first packet in UDP payload, because I use "bytes left" to do the packet length comparison, not UDP payload length. Obviously this could be fixed just by passing "total payload length" around, but that does make the implementation a bit messier.

2. I currently support deferring packets (up to a limit) that I don't have the keys for yet, so that I can process them when/if I do get the key. As you can see from my description of my processing logic above, if I get to a QUIC packet that I don't have the key for, I stop (for the time being) processing the rest of the packet, mark the packet to keep my place, and defer it for later. This would cause problems if a peer packaged up 0-RTT packets before Handshake.

The simple way to fix all these is just to require than Handshake packets be before 0-RTT packets. 1-RTT packets (short headers) are already last because they consume the rest of the UDP payload. Would it be acceptable to make "Handshake before 0-RTT" a MUST?

**Comment by dtikhonov** [comment]
I agree that the compound packets are pain, programming-wise.  Now one has to have "real packets" versus "QUIC packets" or do something else equally odd.

I'd go as far as to say that there can be at most one long-header packet in a compound packet.  (Is there a use case for having more than one?)

**Comment by kazuho** [comment]
@nibanks I can understand that the need for passing "total payload length" can be a bit of annoyance.

OTOH, I am not sure why the support for deferring the packets need to be complicated. Can't you buffer the 0-RTT packet found in a compound packet the same way as you handle a UDP datagram that only contains one 0-RTT packet?

My point is that even if we do not mandate handshake packets to be sent before 0-RTT packets most implementations will do so, and that you do not need to optimize (by avoiding a copy) for the case where a client sends a compound UDP datagram that contains a 0-RTT packet followed by a handshake packet.

**Comment by kazuho** [comment]
@dtikhonov 
> I'd go as far as to say that there can be at most one long-header packet in a compound packet. (Is there a use case for having more than one?)

Handshake packets and 0-RTT packets are both long header packets, so we cannot say that.

Regarding adding restrictions on how packets can be combined, my weak preference goes to having no restriction, since it would allow us to process bundling after our QUIC implementation emits a packet.

Consider the case where we have a packet in the send queue (due to pacing) and then the client decides to send another packet. Wouldn't it be great if we could simply append the new packet to the packet already stored in the queue?

**Comment by nibanks** [comment]
@kazuho I agree that's an interesting idea to be able to append a new packet to an already queued up one, but practically I don't know how often it would occur. How often will this new packet end up being a handshake one? I'd expect nearly never. Handshakes would likely be the first ones that needed to be sent out in the first place. If the current queued packet is 1-RTT you can't add to it. And if the currently queued is handshake, then you can already queue to it.

The problem with my deferred packet processing is that I don't want to allocate additional state to keep track of which packets in the UDP payload have already been processed and which haven't. I just want to keep track of the "next" one to process.

**Comment by nibanks** [comment]
In addition, if you do happen to have a 0-RTT packet in the queue and you have a handshake packet to send, you would prepend it to the queued packet.

**Comment by martinthomson** [comment]
@nibanks the second problem might be addressed by providing a pseudo-packet that uses the underlying UDP datagram as its source?  I think that for the first, it's tough, but the right check here is on the size of the UDP datagram and not the QUIC packet.

**Comment by nibanks** [comment]
I agree that I can come up with a solution to all the problems without changing the spec. I'm just saying I believe it is simpler to implement if we make the simple restriction of Handshake packets before 0-RTT packets.

**Comment by MikeBishop** [comment]
Discussed in Kista:  Sender SHOULD coalesce in order of encryption level, but receiver MUST NOT stop processing packets in a datagram if it encounters one it cannot currently process.  An implementation could either skip (and drop) the unreadable portion, or could buffer it for when the keys are available, just as if the packets were received out-of-order.

**Comment by mikkelfj** [comment]
What if the length if the bad portion cannot be derived (other than byte for byte trial decryption of next embedded packet)? Or what if the unencerypted header section makes no sense?

**Comment by nibanks** [comment]
If something is wrong with a first (only?) packet header, then you can't even know there is another coalesced packet after it. You can only just throw it all away.

**Comment by mikkelfj** [comment]
Exactly, so you cannot adhere to the MUST. The same applies if something is wrong in the second packet.

**Comment by nibanks** [comment]
I think it's a bit of a semantic issue at this point. In my mind, as the receiver of the packet, if something is wrong with the header, I can only assume there were no more packets and I am therefore not violating the MUST by throwing it away. Either way, the MUST is not enforceable as far as I can tell.

**Comment by MikeBishop** [comment]
It's enforceable insofar as, if you violate it, a peer that persistently violates the SHOULD NOT will never interop with you.  It is required for compatibility that one side or the other comply with these recommendations; which one is a SHOULD and which a MUST is strictly a tiebreak.

**Comment by MikeBishop** [comment]
@mikkelfj, this isn't targeted at a corrupted packet, but a well-formed one where you can tell from the headers that you don't yet have the keys.  For example, a coalesced packet containing (0-RTT | Initial) -- the server won't be able to read the 0-RTT portion.  It MUST skip to the second packet and process the Initial, though it is free to discard or return to the 0-RTT packet once that's done.

**Comment by martinthomson** [comment]
A packet can always be decoded as though it were valid.

A short header will either be too short or it will be sent to the AEAD to fail decryption.

Long headers are a little trickier, but not overly so.  If it is too short, it is discarded.  The difference is that it has an explicit length.  If the length is too short or too long, it is discarded.  Then you pass to the AEAD to fail decryption.  Only in that case do you need to worry about what comes after.

My question is: if the connection ID doesn't match, can the recipient discard the entire datagram?  We require that the connection IDs are consistent across the entire datagram.  I think that it would be reasonable to discard in that case.
