### ISSUE TITLE
Packet number transform should be negotiated

### ISSUE THREAD

**Issue by pravb** [quicwg/base-drafts#1296]
Packet number encryption has been proposed as a method to prevent ossification as well as improve privacy of connection migration. However there is a performance cost of doing the transform. There are deployments where ossification is not a concern (intra-DC, private network) and there are connections which are single path where privacy is not a concern, only ossification is. 

Hence packet number transform needs to be a negotiation with the caveat that the negotiated transform must meet the requirements for the deployment scenario otherwise the connection should be failed.
 
Packet number transform can be negotiated using transport parameters. Following PN transforms should be supported:

1. Packet number encryption (PNE)
Connections expecting to use multiple paths due to gratuitous/voluntary migration MUST negotiate and use PNE transform. See issue 1271 where options are being discussed on how migration could be negotiated. If a client or server fails to negotiate PNE and negotiates connection migration, fail the connection.
2. Low CPU cost ossification prevention transform (like shuffle)
For connections on the Internet on single path require them to negotiate this transform. If client or server fails to negotiate this transform on the Internet, fail the connection. 
3. No-op (current draft) 
For intra-datacenter or single domain private network scenarios allow usage of the no-op transform. This is for constrained deployments so clients should not negotiate this transform by default.

Servers are free to negotiate PNE all the time. This allows server deployments which have no performance concerns to always use PNE.

**Comment by pravb** [comment]
It needs to be determined what is set as the client initial (CI) packet number, since that is sent before any negotiation. The solution is the same as what we do for client connection ID, pick a random packet number and only apply the transform to subsequent packets per negotiation. There is also some discussion that the PN space for negotiation should be different (in context of the stream 0 improvements) so this may fit in more neatly in future.

**Comment by janaiyengar** [comment]
It occurs to me that you can always encrypt PN on long headers, and negotiate the transform for short headers. This ensures that a transform is negotiated for the performance-driving case, at the same time avoiding ossification issues for early packets. But yes, there might be a new PN space for the handhshake, which will make this easier to handle.

**Comment by mikkelfj** [comment]
I'm a bit worried that this negotiation could lead to more overhead than finding one good solution, but it depends on whether a good solution is indeed found.

For example: assuming PN space per path handles privacy without encryption leaving only the issues:
1) ossification
2) early packet reject on assumed invalid PN

A cheap seeded multiplication can handle these issues if offline attack and privacy are not a concern. Some other cheap solution could probably also be found, but there is hardly any reason to negotiate then - except if clear text PN is a specific objective.

**Comment by martinthomson** [comment]
Just to try to close on this, the transformation is negotiated, along with the version number.  That's the ultimate solution here.

But that's not the ask here, from what I can tell.  This appears to be asking whether the feature could be made optional, and at the discretion of the server.

@pravb, if you think that we need to resolve this issue, I'd suggest that you ask for some time on the agenda in Kista.

**Comment by bobdug** [comment]
With the rapid increase in Ethernet and bus speeds, the need for hardware offload has become critical in encryption applications.  Besides the reasons stated by @pravb, from this hardware vendor’s point of view, requiring packet number encryption makes the QUIC protocol less friendly to offload.  It requires an added pass through the hardware crypto engine and depending on the hardware implementation, this can result in a loss of performance or additional complexity.  It would hence be ideal to make this feature optional.  That would have the added benefit of allowing the hardware ecosystem time to mature to support this feature, especially at higher speeds.

**Comment by pravb** [comment]
@martinthomson I see that the issue is on the agenda to be discussed. PNE aims to solve two problems - ossification and unlinkability for voluntary migration. The primary motivation for making it optional is that there are deployments where one or both of these problems do not exist. Using versions does not help if the version number is not standardized and it also effectively halves the version space. I would prefer that we use a transport parameter for this. Always encrypting PNE for long headers is not a concern since the TLS handshake is already many orders of magnitude costlier. The primary concern around PNE is performance and hardware offloads, so making it optional for short headers solves this issue and can be negotiated in transport parameters.

**Comment by borisPis** [comment]
From another hardware vendor's perspective. It is not only additional complexity or performance loss. QUIC will be the only protocol to require a second pass over encrypted data. It means that this hardware circuitry must be implemented exclusively for QUIC, and it is unlikely to be reused.

IPsec has plaintext sequence numbers, and IPsec crypto offload in the data path increases performance by about 5x. Is there any indication of IPsec sequence numbers being ossified? I would assume that QUIC sequence numbers wouldn't be any different.

**Comment by pravb** [comment]
Connection migration cannot be incrementally deployed without changing load balancers and not all QUIC connections need migration support. So one could limit PNE to connections needing gratuitous migration by adding negotiation. Ossification is a concern and I would prefer lower cost alternatives compared to encryption if possible. That said, my main interest in adding the transport parameter is for backend connections and connections within DC with neither of these two problems exist.

**Comment by MikeBishop** [comment]
[Discussed in Kista](https://github.com/quicwg/wg-materials/blob/master/interim-18-06/minutes.md#1296-negotiating-packet-number-protection-slide-12).

The working group did not want to add such an option to the core specification.  However, if Microsoft or other interested parties want to propose such an extension (either transport parameter or different version number), the working group would at a minimum review and give feedback.  No decision was made about whether we would adopt such a draft or instead commend it to be AD-sponsored / independent submission / third-party-maintained.
