### ISSUE TITLE
Meaning of "application-owned streams" is unclear

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#1297]
This wording -- "application-owned stream" -- is only used to describe the QUIC transport parameters.  I tracked down the introduction of this concept to f6157a0b51f14ee1583df3cc7408d8ae86174180.

Based on the diff, I gather that this simply means "not the crypto stream," at least at the time of this writing. Nevertheless, I think that the concept of an application-owned stream should be defined before it is used.

**Comment by LPardue** [comment]
Now you've highlighted it, the phrasing with that term seems clunky. If anything you'd want to say application-layer-mapping-owned. Instead how about this...

Stream 0 is already identified as a special case so why not just talk about "streams"and put a reminder (which is already there fwiw) that stream 0 is not included.

Or so we really anticipate that the transport will "gobble up" more streams such that this term is usable for application layer mapping design?
