### ISSUE TITLE
Need to prevent amplification attack for any case where the server's response is big

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#1309]
S 4.4.3 says

```
If the server expects to generate more than three Handshake packets in response to an Initial packet, it SHOULD include a PATH_CHALLENGE frame in each Handshake packet that it sends. After receiving at least one valid PATH_RESPONSE frame, the server can send its remaining Handshake packets. Servers can instead perform address validation using a Retry packet; this requires less state on the server, but could involve additional computational effort depending on implementation choices.
```

However, there are two other cases where the server might generate >3 packets outside of the handshake:

* The application data protocol is a server speaks first protocol and it has a large banner it wants to send in 0.5 RTT
* The client is doing 0-RTT

There are ways to fix this, but it's not clear to me that the protocol actually documents them.

**Comment by mcmanus** [comment]
> 6.6.2.  Address Validation on Session Resumption

relevant?

**Comment by martinthomson** [comment]
@mcmanus, yes.  @ekr, does that work for you?  Do we need to put a pointer in?

**Comment by janaiyengar** [comment]
I wonder if this text should be stronger, given that we rely on servers doing the right thing to avoid amplification attacks. This is an issue IMO with TFO deployments, and I worry that if we don't specify something here we may end up with careless implementations.

We can have recommendations around the expiration time, and around what information should be included and verified. I don't want to bikeshed on these values, but having something here is better than nothing I think.

**Comment by martinthomson** [comment]
Yeah, we should be clearer about this, and more general.  PR wanted.

**Comment by martinthomson** [comment]
Fixed.  https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#packet-handshake

**Comment by martinthomson** [comment]
Oops, I should read more.  PR inbound.

**Comment by martinthomson** [comment]
OK, as discussed on #1616:

If there is no valid token we already have text that says that you can't send more than 3 datagrams.  That covers 0-RTT as well has the handshake.  If there is a valid token, limiting the amount of data sent to a valid peer is a job for a congestion controller.  In this case, the initial congestion window is sufficient (or, as ekr put it: YOLO).

With recommended settings, that moves from 3 packets to 10, which isn't a big enough increase to be problematic, especially considering the amount of processing involved in accepting and responding to 0-RTT.  Servers won't want to do that without a reasonable assurance that the data is wanted, so the amplification attack surface is reduced.
