### ISSUE TITLE
What to do when part of a coalesced packet is invalid?

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#1319]
The draft says

> Every QUIC packet that is coalesced into a single UDP datagram is separate and complete.

and later

> The receiver of coalesced QUIC packets MUST individually process each QUIC packet and separately acknowledge them, as if they were received as the payload of different UDP datagrams.

What is a receiver supposed to do, if it for example receives a 0-RTT with a payload length of 500 bytes, and then some garbage added to the packet.
The second sentence implies to treat these as two separate packets: 1. a 0-RTT packet (which would be processed) and 2. garbage (which would be dropped). However, this seems to contradict the first sentence.

**Comment by dtikhonov** [comment]
I don't see a contradiction: the first sentence says that multiple packets in a UDP datagram are separate as well.

**Comment by marten-seemann** [comment]
So would it be valid to not add PADDING frames in the Initial packet, but just to append arbitrary bytes after the Initial, such that the UDP packet has the minimum required size?

**Comment by dtikhonov** [comment]
That's an interesting question!  The text does seem to allow it.

**Comment by mikkelfj** [comment]
For communications with high failure rates it would make sense to treat packets entirely separately in the same UDP datagram so an error does not propagate to all packets.

**Comment by kazuho** [comment]
In addition to what @mikkelfj says, the reason I prefer not having rules regulating how QUIC packets can be coalesced is that having such rules might make the protocol more fragile to attacks.

From #1262:
> the rationale behind is to not give an on-path attacker the chance of terminating the handshake simply by appending several bytes to the packet (currently, we require an on-path attacker to do AES based on the handshake protection key)

**Comment by martinthomson** [comment]
I believe that the current text is clear on this point:

> Every QUIC packet that is coalesced into a single UDP datagram is separate and
 complete.  [...] If one or more
 packets in a datagram cannot be processed yet (because the keys are not yet
 available) or processing fails (decryption failure, unknown type, etc.), the
 receiver MUST still attempt to process the remaining packets.

Yes, this leads to the possibility of padding with junk.  The only restriction on that is to match the connection ID.

**Comment by MikeBishop** [comment]
(To be fair, that text was added after this issue was filed, and that PR probably should have closed this issue.)
