### ISSUE TITLE
Connection ID in version negotiation

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#133]
When I wrote the section on what can change in different versions, I originally just left an unlabelled slot for the connection ID.  But @marten-seemann observed that the server is required to echo the connection ID in a version negotiation packet.

I don't think that we need the server to echo the connection ID in this case.  That would allow us to restore the 8 octets to a version-specific field.

**Comment by marten-seemann** [comment]
This issue will be solved when we make the changes discussed in #119, since the client won't even pick a connection ID for the first packet.

**Comment by MikeBishop** [comment]
#361 purports to address this; please re-open or file a new issue if that's incorrect.
