### ISSUE TITLE
draft-ietf-quic-spin-exp-00 refers to draft-ietf-quic-transport-12

### ISSUE THREAD

**Issue by reschke** [quicwg/base-drafts#1330]
...which does not exist.

Maybe a problem with the overall tooling/submission process?

**Comment by martinthomson** [comment]
A consequence of a failure in the automated submission process which caused Brian to fall back to manual submission (and all that assumes that all drafts are concurrently submitted, perhaps incorrectly).

**Comment by martinthomson** [comment]
Related: @britram, did you push the draft-ietf-quic-spin-exp-00 tag?  I fetched tags but it's not there.

**Comment by britram** [comment]
I pushed it three times, thought I'd deleted it twice. Apparently I deleted it three times; should I pop back into history and push again (non-annotated, so as not to kick off a submission process that will fail?)

**Comment by martinthomson** [comment]
You can push again.  CI will just fail :)

**Comment by martinthomson** [comment]
We'll keep an eye on this, but closing for now.
