### ISSUE TITLE
plaintext in quic transmission

### ISSUE THREAD

**Issue by huowa222** [quicwg/base-drafts#1340]
quic by default only support ciphertext transmission, in some cases, for example when we're handling multi media that is not data-safe required, plaintext transmission works more efficiently. I have modified the quic source code in TLS negotiation for server to accept plaintext transmission and it work through. So i think plaintext transmission should be presented in new drafts.

**Comment by mikkelfj** [comment]
This is a reasonable use case, but I do not think you will get much traction on this proposal:

The main driver for encryption is that it becomes impossible to create new future protocol versions if data is not encrypted and encryption is considered to be fast.

A single core can encrypt 1GB/s with common hardware accelleration. (Some high end micro controllser have AES accelleration but still lack the CLMUL instruction needed for fast GCM tags, but that will likely change). This covers 10gbps bandwidth with a single core, and it is not uncommon to have multiple cores.

Privacy also has the additional problem that if you can opt out, you can be forced to either opt out or be flagged as suspect. Therefore optional encryption is not good for privacy.

**Comment by larseggert** [comment]
Keep in mind that our WG charter explicitly tasked us with producing an **encrypted** protocol, not a sometimes-encrypted protocol. Even if the WG came to consensus on this addition, it woudl certainly require a recharter.

**Comment by LPardue** [comment]
The IETF version of QUIC is a transport protocol, independent of the application mapping. 

A secure transport provides potential benefit over TCP and UDP for many application protocols. Without encryption, QUIC just might not be so useful in comparison to these.

I'd suggest that where a strong case for plaintext HTTP exists, then HTTP over TCP is a suitable option. That's a clear client opt-out possible today.

**Comment by martinthomson** [comment]
Closed as [out of scope](https://github.com/quicwg/base-drafts/issues/1340#issuecomment-387037282).
