### ISSUE TITLE
Implicit stream open

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1342]
We've had this on and off, but it doesn't seem like we've ever concluded.

Arguments for both sides claim simplicity.  It all depends on perspective apparently.

The material difference is that an implicitly opened stream can be used to send.  e.g., if a server receives a STREAM frame for stream 8, then it can now send on stream 4.

**Comment by dtikhonov** [comment]
Background: [original email](https://www.ietf.org/mail-archive/web/quic/current/msg01679.html), issue #634, issue #896, pr #1193.

**Comment by martinthomson** [comment]
We discussed this in Kista and on balance implicit open was preferred.
