### ISSUE TITLE
Reorder HTTP frame fields to put Type first

### ISSUE THREAD

**Issue by djc** [quicwg/base-drafts#1351]
This would make parsing easier to deal with. I don't think there are adverse effects?

I'm proposing standardizing this:

```
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    Type (8)   |   Flags (8)   |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |       Length (i)                        ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |       Frame Payload (*)     ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

instead of this:

```
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                           Length (i)                        ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    Type (8)   |   Flags (8)   |       Frame Payload (*)     ...
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by dtikhonov** [comment]
Why is one easier than the other?

**Comment by djc** [comment]
With type first, you can directly dispatch to a type-specific parser. Additionally, it would be more similar to how QUIC packets work (header type in the first bit) and how QUIC frames work (type in the first byte).

**Comment by dtikhonov** [comment]
Yes, but you still need to parse the length -- to skip unknown frames.  Even with a dispatch table, it is better to parse the length in one place rather than in each type-specific function.

**Comment by djc** [comment]
Why is that better? I don't think I necessarily agree. Having to pass the length to the type-specific parser makes the interface different from the one in other places, as explained, and more tightly bound.

Additionally, I prefer having variable-sized fields after types of statically known size.

**Comment by dtikhonov** [comment]
> Why is that better?

Less code duplication.

I prefer fixed-width fields first, too.  This preference, however, is not a valid _technical_ argument (the "making parsing easier to deal with" part in you original post).  If we want to argue for this change on the merits of its prettiness, we should frame (ha! get it?) the argument accordingly.

**Comment by LPardue** [comment]
The frame layout is close to HTTP/2. However it IS already different
because it strips the Stream ID.

There is unlikely to be much reuse between h2 parsers and hq frame parsers.

**Comment by martinthomson** [comment]
Having implemented this, I read the header in a single go.  So order makes no difference (at least to me).  That suggests that there is no value in reordering, other than the aesthetic ones, on which we might reasonably disgree.  That suggests no change to me as well.

**Comment by djc** [comment]
What about the consistency (with packet header types and frame types)?

**Comment by MikeBishop** [comment]
Not seeing a driving technical reason to make a change.  Closing for now; if there is a strong reason to flip, feel free to present it.
