### ISSUE TITLE
Largest Reference too big

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1404]
Clearly, a decoder is expected to fail decoding if Largest Reference is too small.  Chances are it will be referencing values that aren't in the table already.

But if the value is too big, should we let that pass, require a failure, or just permit a failure?  Policing this is a little annoying because you have to track the actual largest reference as you decode, so I'd be mildly against requiring failure, but don't care otherwise.

**Comment by afrind** [comment]
I don't think we should require the decoder to fail the stream if it doesn't actually make a reference as large as Largest Reference.  Making it larger than needed will only delay decoding (possibly indefinitely).  I think it can only happen because there's a bug in the encoder or the encoder is attacking the decoder.  

It's seems odd to say the decoder MAY fail the stream/connection when this happens.  I feel like we should say it's an error or it's not.

**Comment by MikeBishop** [comment]
It *is* an error, but it's not required for compatibility that a decoder actually validate that it was correct.  Validating your peer isn't buggy and tempting deadlocks seems like a good way to improve the ecosystem, so I also think it should be permitted behavior.  Thus, I tend toward MAY.

**Comment by martinthomson** [comment]
As do I.  Especially in light of discussions I've had recently.  Tolerance of errors like this is a downward spiral.

**Comment by afrind** [comment]
If tolerance of errors like this is a downward spiral, I guess I don't understand MAY instead of MUST.  Then there will be some implementations that don't treat it as an error (perhaps many, because tracking this is annoying), and the buggy encoder can just say "well it works with so-and-so".

**Comment by martinthomson** [comment]
You only need a few to police these things: https://medium.com/incerto/the-most-intolerant-wins-the-dictatorship-of-the-small-minority-3f1f83ce4e15

In some cases (this might be that case), the mere possibility of enforcement can suffice.

**Comment by afrind** [comment]
I can't imagine a scenario where a non-buggy, non-malicious encoder would do this on purpose and needs only the threat of an error to prevent it.  But I don't want to prevent a server from calling it an error either.  If everyone likes MAY I can live with it.

Related question: If a decoder is required to treat something as an error and it doesn't, does the encoder treat the decoder's permissiveness as an error?  No encoder would ever check that, so it's really just about declaring your implementation conforms to the specification?  Or guidance so you don't accidentally get yourself into trouble?

**Comment by MikeBishop** [comment]
No *production* encoder would ever check that, but there are test suites that intentionally violate certain prohibitions to confirm that the tested peer does, in fact, kill the session.  But ultimately, it's about declaring conformance.  At Microsoft, there was a procedural step where we had to disclose and document any deviations from the protocol, and complying with MUSTs is part of that.
