### ISSUE TITLE
Speed handshake recovery when only undecryptable packets arrive

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#1414]
There are a few cases in the handshake where the decryptable packets may be lost, but undecryptable packets may arrive.

Examples include the client Initial followed by 0RTT packets and the server's Handshake packets followed by 1(/2)RTT packets.

In those cases, no packets can be acknowledged because packets must be decrypted and processed before being acknowledged, but it is possible to indicate to the peer that something has arrived.

DTLS uses an empty ack frame to instigate a faster than standard retransmission of handshake data.  QUIC could adopt a similar mechanism or come up with something slightly different, depending upon how much feedback it wants to provide.  One question is whether the encrypted packet number of the undecryptable packet should be provided in a feedback frame.

**Comment by martinthomson** [comment]
Discussed in Kista and the consensus of the room was to punt this to v2.

**Comment by marten-seemann** [comment]
There's another case where this is occurs.
Consider a server that has a really big cert. It first sends its Server Hello (which is lost), and then begins sending the certificate in Handshake packets (until it is blocked by the 3x limit). The client can't decrypt the Handshake packets, so at some point it will retransmit the Client Hello.
When receiving the second Client Hello, the server has no way to distinguish between the case described above (1.) , and the case where the RTT is so long that the client retransmits the Client Hello before any of the server's packets arrive (2.).

For 1., the server would want to retransmit the ServerHello. For 2. the server could use the additional bytes received to increase the 3x limit and continue sending the certificate.
