### ISSUE TITLE
HTTP/QUIC: Enhance guidance of using "hq"

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#1415]
Section 2 deals with HTTP/QUIC connection establishment and touches on the "hq" Alt-Svc APLN value. However, it's not until section 2.2.1 is it made clear that "hq" should only be used for the *final* RFC version.

Do you think it would help to add a short forward reference to 2.2.1, to help mitigate wasted cycles caused by the wrong ALPN getting used when broader interop happens?

**Comment by MikeBishop** [comment]
Perhaps, but it's easier to ask the RFC Editor to drop an entire section than to delete a forward reference to the section, and I'm worried we'd end up with an erratum from a hanging reference.  Let me see if I can move 2.2.1 earlier in the section instead.

**Comment by LPardue** [comment]
Yeah I'm sympathetic with making the RFC editor life easier (and mitigating future problems).
