### ISSUE TITLE
HTTP/QUIC: "Streams SHOULD be used sequentially, with no gaps." ambiguity.

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#1417]
With a pedant hat on.

Section 3 discusses stream mapping and usage. The following sentence stands alone, but follows discussion on stream identifier usage.

> Streams SHOULD be used sequentially, with no gaps.

I presume this means that stream identifiers should be used sequentially, rather than lower-lever STREAM offset gaps?

**Comment by MikeBishop** [comment]
Saying that Stream IDs should be used sequentially feels a little odd, since the application doesn't actually have control on the Stream IDs themselves.  I'm having trouble coming up with a better wording; perhaps when I'm back on my own time zone.  ;-)

Suggestions welcome.

**Comment by LPardue** [comment]
One idea (discussed in-person) is to simply remove the offending statement. However, that seems to lose some of context. 

Perhaps we could join this sentance with earlier paragraph 

> When HTTP headers and data are sent over QUIC, the QUIC layer handles most of the stream management.

and some fluffier text might help?

**Comment by MikeBishop** [comment]
Given that QUIC will be swinging back to implicit-open streams, this requirement at the application layer seems unnecessary.
