### ISSUE TITLE
get_delay() undefined in loss detection pseudocode

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#142]
In draft-ietf-quic-recovery.md

`      if (rto_count = 0):
        alarm_duration = max(200ms, smoothed_rtt + 4 x rttvar);
      else:
        alarm_duration = loss_detection_alarm.get_delay() << 1;
      rto_count++;

The return value of get_delay() is not defined anywhere in the document.

**Comment by martinthomson** [comment]
@ianswett, correct this if it isn't purely editorial.

**Comment by ianswett** [comment]
It's editorial, as well as not defined.  I'll fix it.
