### ISSUE TITLE
encoder stream can deadlock

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1420]
If the encoder sends a large block that is bigger than the flow control limit AND the decoder doesn't read the block until all the data is present, THEN the decoder never releases flow control credit for the block, but the encoder can't complete sending of the block.  Deadlock.  Advise caution.

**Comment by krasic** [comment]
A decoder shouldn't do that.   The same kind of deadlock would be possible for any app protocol that precedes app level messages with a length where the message length is allowed to be larger than flow control window.     

[Blocked decoding](https://quicwg.org/base-drafts/draft-ietf-quic-qpack.html#rfc.section.6.3.2) is only for dependencies .

**Comment by afrind** [comment]
Right, if the decoder only wants to process the block in its entirety, it needs to buffer this data in application space and release the flow control.

**Comment by MikeBishop** [comment]
It's also worth noting that we really have two situations here:

On the encoder stream, nothing says the encoder has to send all updates in a single block.  It can query for available flow control, write that much, and wait for more credit.  The only time it deadlocks with this approach is when a single header is bigger than the flow control credit being issued, in which case don't put those huge Kerberos tickets in your dynamic table, for the love of God.

On the request stream, you do have to send the whole header set all at once, which is harder.  However, you're also bounding the size of headers you'll accept on any given stream; we can recommend that the flow control window be large enough to transfer the expected header set or that you be willing to buffer as needed.

**Comment by afrind** [comment]
@martinthomson - can you suggest what kind of text you think might help remedy the situation?  My read is that we're not going to make protocol changes to address this, but instead "advise caution" as you say.

**Comment by kazuho** [comment]
@afrind 
> If an encoder runs out of stream flow control on the encoder stream, it may erroneously send requests (and fill the connection flow control) that depend on bytes that haven't been transmitted. Some text advising caution in this scenario may be warranted.

+1.

Re the issue that @martinthomson initially raised, I think that we should state that:
* a non-streaming decoder should cap the maximum size of an instruction that it processes to avoid memory exhaustion attacks
* a non-streaming decoder that keeps partial instructions in the receive buffer should set the size of the receive buffer equal to or greater than the maximum permitted size of the instruction
