### ISSUE TITLE
QPACK: Huffman string compression

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#1435]
Does QPACK use the same Huffman coding table that is defined in HTTP/2 (https://tools.ietf.org/html/rfc7541#appendix-B)?

If so, there is no reference to it.

**Comment by MikeBishop** [comment]
Technically, it says that it uses the string literal format from HPACK, and mentions that that format includes a bit to indicate Huffman or not.  Would it suffice to expand that reference to explicitly call out that the format includes Huffman encoding?
