### ISSUE TITLE
What happens with lost packets that are detected when an Ack arrives

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#144]
In the loss recovery draft, `OnPacketAcked` is called for every packet that is acked by an incoming Ack frame.
This function calls `DetectLostPackets`, which returns a list of packets that are considered lost. However, this return value is never used in `OnPacketAcked`.

Furthermore, looking at `DetectLostPackets` in detail, it seems to me that it would be sufficient to call that function once (with the largest observed packet as function parameter) when receiving an Ack.

**Comment by marten-seemann** [comment]
It seems like my last point has already been resolved by the recent changes to the draft (`DetectLostPackets` is now called with `ack.largest_acked_packet`).

So this just leaves my original question what happens with the return values of `DetectLostPackets` when called from `OnAckReceived`.

**Comment by ianswett** [comment]
Yes, what to do with lost packets is missing. 

Two main things I plan to add:
1) Decide whether to retransmit any frames in the packets.
2) Notify the congestion control interface and pass any lost packets to that.  

I hadn't decided if I was going to use a list of frames to be retransmitted for (1), or keep two numbers, one for the earliest lost packet that hasn't been retransmitted and one for the largest lost packet.  I think the latter is closer to how I'd recommend people implement it and I think may be easier to describe.  Thoughts?

Tell me if I'm missing anything.

**Comment by ianswett** [comment]
I have decided to not go into what to retransmit, but I think the DetectLostPackets method(https://github.com/quicwg/base-drafts/blob/master/draft-ietf-quic-recovery.md#on-packets-lost) is fairly complete now.
