### ISSUE TITLE
Current Code for Recovery period misscounts

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#1440]
Recovery draft:

   InRecovery(packet_number):
     return packet_number <= end_of_recovery

end_of_recovery = largest_sent_packet

To my understanding the end of recovery will be when one ACKs the packet that is one larger than the largest sent when the congestion event happens. Thus, the InRecovery function should use only < as long as end_of_recovery is not assigned to largest_sent_packet+1 (assuming all PNs are used).

**Comment by ianswett** [comment]
So end_of_recovery is assigned to the largest sent when recovery starts, as you said.

Say the largest sent when recovery starts is 10.  So when 11 is acked, we are no longer in recovery.

InRecovery(10) returns true, and InRecovery(11) returns false, so I believe it's correct?

**Comment by gloinul** [comment]
Yes, you are correct. Closing.
