### ISSUE TITLE
Clearer pseudocode/TLS syntax specification

### ISSUE THREAD

**Issue by rmarx** [quicwg/base-drafts#1449]
I am quite new to the whole RFC stuff, so I am sorry for using hopelessly wrong names for things. 

I had some trouble today understanding some of the pseudocode in the transport draft, more specifically at https://tools.ietf.org/html/draft-ietf-quic-transport-12#section-6.4 :

```
struct {
 TransportParameterId parameter;
 opaque value<0..2^16-1>;
} TransportParameter;

struct {
 select (Handshake.msg_type) {
	case client_hello:
	   QuicVersion initial_version;

	case encrypted_extensions:
	   QuicVersion negotiated_version;
	   QuicVersion supported_versions<4..2^8-4>;
 };
 TransportParameter parameters<22..2^16-1>;
} TransportParameters;
```

For example the 'supported_versions' field: is that supposed to be an array prefixed with a length? Current implementations seem to think so. The 'value' field above is a single value prefixed with a length. But then the 'parameters' field below is very similar in syntax, but is not prefixed by length in the implementations (or I'm reading some things wrong, always possible).

I asked @larseggert about this, and he secretly admitted "Nobody but ekr understands the TLS syntax. It’s a huge pain.". Even if I'm misinterpreting some things, an alternative syntax or at least a clear explanation would be welcome (if that is already in there somewhere, possibly link it in https://tools.ietf.org/html/draft-ietf-quic-transport-12#section-2.1?)

**Comment by ekr** [comment]
It comes as a surprise to me that @larseggert  thinks that nobody but me understands the syntax, given that we have a pile of independent interoperable TLS 1.3 stacks.

Regardless, this is the appropriate syntax because these are PDUs that go into the TLS stack, which already uses that syntax. We don't need to explicitly state the size of the parameters because the protocol definition language tells youl

**Comment by martinthomson** [comment]
What @ekr said.  Also, this is the most complicated part of the protocol grammar and using pictures and words would be much more verbose and likely less precise.

**Comment by MikeBishop** [comment]
QuicVersion is explicitly defined as a uint32, so references to that type are already a known size. The other things with explicit sizes given are arrays (albeit sometimes arrays of bytes that represent a single value), and arrays are length-prefixed.
