### ISSUE TITLE
QPACK could use some examples

### ISSUE THREAD

**Issue by afrind** [quicwg/base-drafts#1454]
From an external researcher hoping to build an implementation: 

"The HPACK RFC authors made a wise choice to include several carefully crafted examples. I managed to create a HPACK implementation and to verify it using those examples. A similar list of examples could be considered for QPACK to make it easy to verify QPACK implementations. However, QPACK has some extra signaling, meaning constructing the examples list may not be as easy as it is for HPACK."

**Comment by LPardue** [comment]
That is good feedback. Examples are non-normative, so one angle is to provide test vectors (outside of documentation) that helps implementers

**Comment by afrind** [comment]
See also: https://github.com/quicwg/base-drafts/wiki/QPACK-Offline-Interop

I'm planning to put up some sample HAR files and their QPACK encodings under various params and assumptions.

**Comment by afrind** [comment]
For reference, there is now this repo: https://github.com/qpackers/qifs, which contains example encodings.  We could brush this up and have some semi-canonical encodings there.  That said, I kind of liked having a few concrete examples in the HPACK specification that you can refer back to.

Just reviewing HPACK's examples, it has:

3 Integer encoding examples
An example encoding of each instruction
A sequence of three requests and one with three responses, each encoded both with and without Huffman 

For each of the request/response examples it has a block that shows the decoding process - which octets produce which decoder actions (insert, evict, emit, etc). 

I'm not sure how much of this ground we need to retread in QPACK.  Since we use the same integer and Huffman encoding, we could probably skip those.  

So maybe we should have

1. One String literal example
2. One Example of each instruction (4 encoder, 3 decoder, 5 request)
3. An encoding that does not use the dynamic table/control stream at all
4. An encoding that uses the control stream
5. An encoding that uses the control stream and post-base instructions
6. An encoding that makes a duplicate on the control stream and references it

I think 1 and 2 are more to be consistent with what HPACK did and shouldn't really be required.  Even so, this might be a long section.

I'd like to avoid anything that involves decoder->encoder feedback since it can get hairy pretty quickly.  I'm less inclined to include the decoding process diagrams since decoding is pretty simple - it only emits.

**Comment by MikeBishop** [comment]
Perhaps the real decoder examples that are useful would be to show the state of the dynamic table before and after the control stream instructions?  I agree that we probably don't want examples that show an encoder responding to feedback, but it might be worth noting in the examples when the decoder sends it.

**Comment by larseggert** [comment]
This has been sitting around for almost two years. *If* we think that adding examples is a good idea, can we make this happen now? Or can we close with no action?

**Comment by LPardue** [comment]
As a recent implementer, I found the offline QPACK tests very useful. 

I don't know if textual examples are a good idea. There's a challenge to make them clear, concise and complete. But if you're going to add some, then perhaps also think about including one with "out of order delivery" where HEADERS arrive before their required inserts.
