### ISSUE TITLE
Coalesced packets and handshake packet limiting

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1458]
Both current and DT output text restricts the server from sending more than three "packets" to the client until address validation has occurred.  However, in the presence of coalesced packets, three packets could be contained in a single UDP datagram:  Initial, Handshake, 1-RTT with response to the client's 0-RTT requests.

Is this text actually intending to limit the transmission to three *datagrams*?

**Comment by nibanks** [comment]
I've always assumed it meant three UDP datagrams, and not QUIC packets. I think that makes the most sense.

**Comment by MikeBishop** [comment]
I think when we wrote that, we didn't have coalesced packets, so they were equivalent statements.

**Comment by janaiyengar** [comment]
Nice catch. Yes, we definitely meant that for 3 datagrams, and we did not have coalesced packets back then.  I suspect 3 datagrams is simpler than 3 * num_bytes_received, so I'm in favor of 3 datagrams.

**Comment by ekr** [comment]
+1 for 3 datagrams

**Comment by martinthomson** [comment]
Fixed in 3aea50db51a14f2b42ed8aea7dbeeea72c6321b4
