### ISSUE TITLE
Duplicate STREAM/CRYPTO_HS in the same packet

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#1463]
We should make it clear that implementations must handle overlapping data in all cases:

1) Duplicate STREAM/CRYPTO_HS in two different packets
2) Duplicate STREAM/CRYPTO_HS in the same packet
3) Duplicate STREAM/CRYPTO_HS in two packets but inside one UDP datagram

The receiver should discard overlapping data and not close the connection.

**Comment by mikkelfj** [comment]
The order in which the receiver apply ranges and discards overlap is arbitrary and does not necessarily happen on any one frame boundary.

The sender SHOULD send the same content when introducing overlap (but can't always when relaying on external data sources).

The receiver MUST provide consistent view of data. Once a range is visible to the application it will not change.

**Comment by ekr** [comment]
> The sender SHOULD send the same content when introducing overlap (but can't always when relaying on external data sources).

This is not correct: https://tools.ietf.org/html/draft-ietf-quic-transport-12#section-9.5 says:

>  An endpoint could receive the same octets multiple times; octets that
   have already been received can be discarded.  The value for a given
   octet MUST NOT change if it is sent multiple times; an endpoint MAY
   treat receipt of a changed octet as a connection error of type
   PROTOCOL_VIOLATION.

**Comment by mikkelfj** [comment]
Yes, sorry, I am aware that this is the case now. I propose to change it because it is impossible to conform to when using memory mapped files as a source on Linux.

**Comment by ekr** [comment]
Ah. I would oppose that change.

**Comment by martinthomson** [comment]
We discussed that specific possibility (that bytes can change after invoking sendfile() or equivalent), but I don't think that there was much appetite for allowing that.  See #1353.  If anyone disagrees with this, they are welcome to take that to the mailing list (or the chairs).

**Comment by martinthomson** [comment]
@rpaulo, looking at [Section 9.5](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.9.5) and this issue, I'm not sure what more we could add.  Is there something else we should be saying?

**Comment by rpaulo** [comment]
I had thought we could add a sentence about the different cases that data can be duplicated by an implementation but I think we can close.
