### ISSUE TITLE
Reflection Attack Resistance

### ISSUE THREAD

**Issue by britram** [quicwg/base-drafts#147]
The design of the QUIC packet header should consider the ease of creating an apparently-valid first packet via reflection against existing, widely deployed UDP protocols (DNS and NTP being the top two here). All easily reflectable packets off these services should be trivially droppable by a QUIC server. Otherwise, there exist a variety of possible DDoS attacks (of which #135 is one case).

For 1-RTT first packets, the probablity of creating a valid ClientHello would seem to be negligible, though there might be some value in reducing the processing necessary to recognize and reject reflected garbage, or to allow it to be rejected before delivery to the server process.

For 0-RTT first packets, the header layout should be defined such that a version number (or other magic pattern, though the version number space is sparse enough that it can do double duty as a magic pattern) has an offset and bit pattern that does not occur in traffic that can be generated via reflection off common UDP services.

**Comment by ianswett** [comment]
This seems like a good item to think about.  I believe the 12 byte auth hash on 0RTT packets mitigates this in practice, but maybe there's a reason it's insufficient?

**Comment by ianswett** [comment]
Apologies, the auth hash only helps the handshake packets, not 0RTT requests.

0RTT packets are typically sent with the version set, which would make fast identification of junk slightly easier, as you mention.

**Comment by martinthomson** [comment]
What auth hash?

**Comment by ianswett** [comment]
All the unencrypted packets all have a 12 byte hash to ensure they haven't been inadvertently modified in flight or they're random internet junk.  It also means all the encryptors have the same 12 byte overhead, which is nice.

I'm guessing from your comment this never got migrated from the QUIC crypto doc into the transport or tls docs?

**Comment by martinthomson** [comment]
Yes, this didn't get migrated.  It was intentional.  Given that no one noticed, I have to wonder whether it was needed.  Open an issue if you care.

**Comment by MikeBishop** [comment]
#361 purports to address this; please re-open or file a new issue if that's incorrect.

**Comment by martinthomson** [comment]
I suspect that #361 does not in fact address this.  What will address this, if anything, is the addition of an integrity check, see #167.

**Comment by britram** [comment]
agreed, #361 doesn't help much here but #167 would fix in a way with which qQUIC gives us implementation experience, so happy to leave this one closed.
