### ISSUE TITLE
Retry Token Makeup

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#1474]
This issue is related to the new Stream 0 dt PR (#1450).

Is a client allowed to change its connection ID in response to a Retry packet from a server?

The reason I ask is that it is possible to conceive of a server generating a token for a stateless Retry that encodes the client's original CID (among other things) in it for validation purposes. If the client is allowed to change its CID, then that obviously would break. So I feel we should have text either explicitly saying the client may (which I don't see how we could prevent) change its CID, and that a server shouldn't try to use the CID for stateless Retry validation or that a client must not change its CID so the server can use it for validation in stateless Retry.

**Comment by martinthomson** [comment]
My thought would be a token that is carried in a Retry would be bound strongly to the connection ID.  It's very different to NEW_TOKEN in that way.

**Comment by nibanks** [comment]
Should we add text to say that the client SHOULD NOT change their source CID in response to a Retry packet? If so, I can send a PR to that effect.
