### ISSUE TITLE
Guidance for flow control and ACK of extension frames

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#1487]
Given the past history, it is easy to overlook the complixity of ACK and flow control when adding new frames, so some guidance could be useful.

One option could be to define a few classes of behavior such as now flow no ACK, etc. and use an existing frame such as PING, PAD, etc. as example.

**Comment by martinthomson** [comment]
Good idea.  We should document what an extension needs to consider in defining a new frame type.
