### ISSUE TITLE
Packet Number Must Be Decrypted to Read Initial Token Field

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#1492]
Because the Initial packet's token is after the rest of the long header, the packet number must be decrypted first to determine the starting offset of the Token Length field and then the Token field. This adds a requirement for DDoS Mitigation Devices, that would simple read the token field to validate address ownership before passing the packet along or sending a Retry packet of its own, to have crypto support. If the packet number followed the token, this would no longer be a requirement on the hardware.

**Comment by ianswett** [comment]
Does the Token need a packet number?  It already echos the DCID.

**Comment by martinthomson** [comment]
It seems like @ianswett has the answer.  It means that Retry will be specified like Version Negotiation, which is clumsy, but it's probably better that way.

I have to ask, were people assuming that Retry used packet protection?  I had not expected it to be, but I look and it seems like it does.

**Comment by kazuho** [comment]
@ianswett @martinthomson Isn't the issue about the format of the *Initial* packet, not about *Retry*?

I agree with @nibanks that the current format of the Initial packet that places token after packet number is incorrect, for two reasons:
* token is not a good source of randomness for PNE
* token should be accessible by middleboxes that do not want to deal with PNE

**Comment by kazuho** [comment]
@martinthomson 
> I have to ask, were people assuming that Retry used packet protection? I had not expected it to be, but I look and it seems like it does.

My understanding is that the outcome of stream 0 DT was to have it _outside_ of packet protection.

**Comment by nibanks** [comment]
Yes, the issue here is the client **Initial** packet and we did agree to keep it **outside** of packet protection to reduce the complexity for DDoS mitigation.

**Comment by martinthomson** [comment]
Then let's put it before the Length field, outside encryption.

**Comment by ianswett** [comment]
Yes, the intent was for Retry not to use packet protection and to put the token outside of packet protection.

Given all the open issues with Retry, should we declare it out of scope for the Montreal interop?
