### ISSUE TITLE
Stateless Reset from clients, bis

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#1505]
In #466, we left it as the client cannot use Stateless Reset, until the server starts to use to a CID provided by the client's NEW_CONNECTION_ID.  (Something that is actually not stated explicitly in the draft.)

This is certainly not great, hence this issue.

To fix this, I can think of a few alternatives:
1. A new frame that provides the initial Stateless Reset Token from the client. It only applies to the initial CID (important to note, since you do not want it to override the token from a subsequent NEW_CONNECTION_ID in case of reordering).
2. If NEW_CONNECTION_ID frame is received from the client with Seq=0 and Length=0, it provides the initial Stateless Reset Token (and is considered to be Seq=-1, so the next NEW_CONNECTION_ID would actually be Seq=0).  I do not love this and would prefer just a new frame.

**Comment by hardie** [comment]
Hi Igor,

I think I'm a little confused.  Some questions in-line.


On Fri, Jun 29, 2018 at 3:12 PM, Igor Lubashev <notifications@github.com>
wrote:

> In #466 <https://github.com/quicwg/base-drafts/issues/466>, we left it as
> the client cannot use Stateless Reset, until the server starts to use to a
> CID provided by the client's NEW_CONNECTION_ID. (Something that is actually
> not stated explicitly in the draft.)
>
> This is certainly not great, hence this issue.
>
> To fix this, I can think of a few alternatives:
>
>    1. A new frame that provides the initial Stateless Reset Token from
>    the client. It only applies to the initial CID (important to note, since
>    you do not want it to override the token from a subsequent
>    NEW_CONNECTION_ID in case of reordering).
>
> If the purpose of Stateless Reset is to abruptly tear down a connection,
I'm not sure what the re-ordering issue is.  Sending a Stateless Reset and
then sending more traffic on that connection seems odd.  Similarly, if the
client needs to know whether data already sent has been received, it seems
like it either has to wait until that data is acknowledged and/or use a
graceful shutdown.  I don't seen how a reset matches this--what am I
missing?


>
>    1. If NEW_CONNECTION_ID frame is received from the client with Seq=0
>    and Length=0, it provides the initial Stateless Reset Token (and is
>    considered to be Seq=-1, so the next NEW_CONNECTION_ID would actually be
>    Seq=0). I do not love this and would prefer just a new frame.
>
> —
>
I agree that this is not very lovable.

Ted

**Comment by igorlord** [comment]
Ted, take a look at #466 (closer to the end of the thread).

The problem we have right now is that client cannot supply a stateless reset token during handshake, because client's part of the handshake (unlike the server's) is not protected.  So the situation we have right now is that clients _cannot_ send a Stateless Reset any time later, until the server has switched to using a new CID from the client, provided by the client in NEW_CONNECTION_ID.  (And switching CIDs may never happen.)

So the "idea" I am proposing is very simple -- since the client cannot not send its stateless reset token associated with its CID during handshake, let it send that token later (as soon as it starts to send protected packets).

**Comment by MikeBishop** [comment]
The reordering isn’t with the Stateless Reset itself.  The server doesn’t know, during the handshake, what SRT goes with the client’s chosen CID.  Igor is looking for a way the server could acquire this information, so that a Stateless Reset subsequently sent by the client can be recognized.

The first option is a separate frame type that supplies the SRT for a CID that the server already has.  But due to reordering, that might no longer be the CID in use when the server receives it, so the server needs to be careful not to overwrite the SRT it already possesses for the new CID.  Frankly, this just seems like a bug on the server implementer’s part, albeit one it might be worth cautioning them against.

The second becomes more palatable if the outcome of #1484 is that you can express the sequence number of the initial handshake CID in a NEW_CONNECTION_ID frame; the client could simply re-send that CID as if it were new, but including the SRT this time.

**Comment by igorlord** [comment]
Yes, if #1484 assigns number 0 to the client's initial CID, then the simplest way to implement this is to just repeat CID 0 in NEW_CONNECTION_ID frame.  Some care would be needed to decide whether CID 0 in NEW_CONNECTION_ID can be different from the client's initial CID, or that's an error.  (Len=0 there could be an optimization or be considered an unnecessary complication).

**Comment by martinthomson** [comment]
Isn't it easier to switch to a new connection ID?

**Comment by igorlord** [comment]
The client can only switch to a new connection id, if it was given one by the server. A server that does not want clients to stay connected after a network reconnection event will likely not supply additional connection ids.

**Comment by martinthomson** [comment]
We had that discussion when talking about migration.  I think that there is still value in having some new connection IDs available.  If a server doesn't want to support connection migration, there's a transport parameter for that now.

**Comment by igorlord** [comment]
Are you suggesting that a server that would like to learn a Stateless Reset Token (STR) needs to wait for a CONNECTION_ID frame with a new CID from the client and then start using that new CID?

Since servers would always prefer to know a SRT, and clients would know that and oblige by generating a new CONNECTION_ID frame.  The servers would also need to generate an extra CONNECTION_ID, since once the server switches to a new CID, the client will likely switch as well.

All this is basically creating a lot of extra messaging, logic, and busy work for the common case QUIC connection.  It seems easier for the client to send just one message supply a SRT for the current CID and be done with it.

**Comment by martinthomson** [comment]
I don't expect that a client sending a stateless reset will be common at all.

**Comment by igorlord** [comment]
@martinthomson This is very true!

I was thinking to TCP world, where clients sent RST all the time (when they crash or otherwise).  However, if a QUIC client crashes, it will very likely send ICMP Unreachable.

Your statement seems so true that I actually start to wonder if clients even need to send SRT with CONNECTION_ID...

**Comment by mikkelfj** [comment]
Clientside stateless resets apply in P2P where the client is more like a server - especially when it is random which endpoint becomes a client. I’m not generally a fan of resets though.

**Comment by igorlord** [comment]
Even in P2P, would not you have the client pick an ephemeral port as a source port? If so, once the client restarts, there is nothing listening on that ephemeral port.

**Comment by mikkelfj** [comment]
@igorlord : in P2P you could argue that ephemeral ports are not so easily exchausted when the client has long living connections to peers, as opposed to short lived loadbalancer forwards.

But in a mesh network it is much more convenient to just stick to a single port and avoid all problems with ports differing, especially when use interfaces like netmap where you have to manage to ephemeral port. It is vastly simpler to just reuse fixed port, also client side.

**Comment by mikkelfj** [comment]
Essentially you avoid the problem of calling "connect" to the OS all the time and handling its lifetime.

**Comment by igorlord** [comment]
@mikkelfj , got it.  So SRT may indeed be useful for clients in such applications.

**Comment by martinthomson** [comment]
Have we reached a resolution here?

**Comment by MikeBishop** [comment]
I don't think a clear one, no.  It's in my CID deck for next week; I'm inclined to just leave it until then.

**Comment by MikeBishop** [comment]
We ran short on time, so while I mentioned the issue, the discussion didn't focus on it.

**Comment by martinthomson** [comment]
The conclusion I've reached is that the server can start using a different connection ID if it cares about stateless reset.  If others disagree, please take it to the list.
