### ISSUE TITLE
Frame type field in APPLICATION_CLOSE

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#1508]
I would like to see some guidance on how to set Frame Type in APPLICATION_CLOSE. If this field should always be set to "unknown", it probably should not exist in APPLICATION_CLOSE.

**Comment by ianswett** [comment]
My intuition is this doesn't belong in APPLICATION_CLOSE, only CONNECTION_CLOSE.

**Comment by MikeBishop** [comment]
This is probably accidental -- the field was added to CONNECTION_CLOSE without consideration that APPLICATION_CLOSE is defined to have an identical payload.  Either the payloads have now diverged, or the APPLICATION_CLOSE section should recommend a value.  (Probably STREAM or unknown, given that the error is being provoked at the application layer.)

**Comment by igorlord** [comment]
If there is always one value (STREAM or Unknown), this provides no information. (And STREAM could be misleading -- it could be due to RST_STREAM or nothing to do with any stream at all.)

**Comment by martinthomson** [comment]
Yes, mea culpa.  I never intended APPLICATION_CLOSE to gain the new field.  I'll fix that.

**Comment by igorlord** [comment]
Thanks, @martinthomson .

While on the subject of the Frame Type field, the draft leaves its format ambiguous.  It is marked (i), which usually suggests a variable-length encoding, but all other fields that use variable-length encoding spell this out.

**Comment by martinthomson** [comment]
@igorlord, Section 5 says:

> The Frame Type field uses a variable length integer encoding (see Section 7.1) [...]

Is that enough?

**Comment by igorlord** [comment]
@martinthomson, yes, that section as well as Section 2.1. Notational Conventions point to the same thing.

Nevertheless, in all places but two variance-length encoded integers are explicitly stated to be such in frame descriptions.  A very rare departure from this convention would cause an unnecessary confusion that the departure was purposeful.

I'd just add the appropriate language to those places...  See PR #1534.
