### ISSUE TITLE
Justify various constants used in recovery draft

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#151]
Mostly references to drafts/rfcs/papers, but complete justifications are needed for this draft to be standalone.

**Comment by martinthomson** [comment]
@janaiyengar, are we done with this yet?  Or maybe to put it differently: can we close this and open more specific issues for different values?

**Comment by ianswett** [comment]
I'm closing this, because there's already an issue for the 100ms default RTT and otherwise I'm happy with what we have in "Discussion".
