### ISSUE TITLE
Short header: reserved bits

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#1511]
The test says:

> Reserved: The sixth, seventh, and eighth bits (0x7) of octet 0 are reserved for experimentation.

But there's no guidance on what they should be set to, so I think it should be:

> Reserved: The sixth, seventh, and eighth bits (0x7) of octet 0 are reserved for experimentation and MUST be set to zero.

**Comment by martinthomson** [comment]
Sure.  You have to say what to do with the values if you get them.  That is, you can't have recipients discard the packet if the value happens to be 1, because that might prevent the bits from being used.

**Comment by larseggert** [comment]
MUST grease?
