### ISSUE TITLE
Update references to new HTTP RFCs

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1523]
Some references in HTTP/QUIC would benefit from invoking the HTTPter drafts instead, if they finish before we do.  For example, the text is #1516 is unnecessarily awkward because it references concepts from RFC 7230 while disclaiming the wire format.  The equivalent text in [Semantics](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#message.abstraction) is far more appropriate.

**Comment by royfielding** [comment]
I think this should be unparked before last call.

**Comment by MikeBishop** [comment]
The intent was to make the cut-over if the dependency would not delay QUIC.  It seems like they're progressing quickly enough that we could probably do that.
