### ISSUE TITLE
Long header + token and PNE

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1535]
Draft-13 says:
```
The Initial packet has two additional header fields that follow the
normal Long Header.
```
But of course, this means that the variable length token length follows the variable length PN, which is encrypted. I guess the editors wanted to make the header parsing code more interesting. It certainly will not help load balancers, firewalls, etc., which may want to parse the tokens during DDOS defense.

**Comment by huitema** [comment]
Here is what I understand so far:

• Initial packet starts with long header, included encrypted PNE;

• Continues with varint length + retry token;

• Then encrypted payload.

The encryption is done before PNE, as usual.

The "nonce" used for PNE starts at (index of PNE)+4. This may well fall inside the retry token. Do we even care?

The "authenticated" data for AEAD covers the long header and the retry token. Or is it just the long header?

**Comment by kazuho** [comment]
My interpretation of -3 will be that token_len and token are placed _after_ the payload, because payload is defined as the last element of the long header. But that means that -13 is impossible to implement, because the length of the payload can’t be determined without parsing the token_len field that follows the payload.

Anyways my understanding is that the correct definition is to place token and token_len right before the encrypted pn field.

**Comment by huitema** [comment]
> On Jul 14, 2018, at 2:06 PM, Kazuho Oku <notifications@github.com> wrote:
> 
> My interpretation of -3 will be that token_len and token are placed after the payload, because payload is defined as the last element of the long header. But that means that -13 is impossible to implement, because the length of the payload can’t be determined without parsing the token_len field that follows the payload.
> 

Impossible is a big word. I did actually implement it. But it is ugly and unnecessarily complicated.

**Comment by kazuho** [comment]
@huitema To clarify, my interpretation of -13 (explained above) is different from your interpretation that is described as "this means that the variable length token length follows the variable length PN". #1567 to avoid that confusion.
