### ISSUE TITLE
HTTP Stream ID Size

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#154]
QUIC uses a 32-bit (soon to be 64-bit) stream space.  However, we know that HTTP sessions typically don't use nearly the 31 bits of stream space we have in HTTP/2.  As QUIC continues to expand the number of streams it supports, HTTP/QUIC ends up spending more bits on stream ID overhead (PRIORITY, PUSH_PROMISE, etc.).

Should we consider having variable-length stream ID fields in these frames?  Or is the complexity reduction worth stating the full stream ID, especially since we no longer have an HTTP-level stream ID on every frame?

**Comment by MikeBishop** [comment]
Related to #148, which is trying to take QUIC the other direction.  Is one right, or should we meet in the middle?

**Comment by mirjak** [comment]
Is stream ID space really an issue? Given it's so cheap to open new connections, you could probably seamlessly open a new quic connection...?

**Comment by MikeBishop** [comment]
That’s a good question for #108; this issue is over whether HTTP needs to spend all the bits to represent the full QUIC stream ID, no matter how large that is.

Sent from my Windows 10 phone

**Comment by martinthomson** [comment]
Since we decided not to increase the stream number space, is this still an issue?

**Comment by MikeBishop** [comment]
Nope.
