### ISSUE TITLE
Coalescing Packet including Initial Packet would be over the MTU

### ISSUE THREAD

**Issue by ami-GS** [quicwg/base-drafts#1546]
UDP datagram would be over the MTU(1252 bytes for IPv4) when coalescing packet with Initial Packet and some other packets during Handshake, because Initial Packet have to have at least 1200 bytes.

When to coalesce packets with Initial packet, should we consider the 1200 bytes limitation as whole coalescing packet UDP datagram?
Or should we send Initial Packet as it is?

**Comment by martinthomson** [comment]
We agreed that this would be datagram, but the fix was implemented inconsistently.

**Comment by huitema** [comment]
It is way simpler to send the client initial as is, and the 0-RTT data in a follow-up packet. If the implementation can predict that a 0-RTT will follow, it can refrain from padding the Initial packet, and make sure that the coalesced 0-RTT packet extends to the specified limit. Doable, even if not entirely natural.

**Comment by kazuho** [comment]
> It is way simpler to send the client initial as is, and the 0-RTT data in a follow-up packet. If the implementation can predict that a 0-RTT will follow, it can refrain from padding the Initial packet, and make sure that the coalesced 0-RTT packet extends to the specified limit. Doable, even if not entirely natural.

FWIW, you have the freedom to pad the 0-RTT packet of a coalesced datagram instead. IMO that is the natural way to combine Initial and 0-RTT into a single datagram.

What picotls does when both 0-RTT key is available is:
* construct Initial packet without padding
* construct 0-RTT packet coalesced to the Initial
* pad the 0-RTT packet if the datagram is going to be to small

**Comment by huitema** [comment]
Yes, the issue is that it not just the 0-RTT key -- it also depends on having 0-RTT data available. But I guess that if there are no 0-RTT data available, on can just send a 0-RTT packet full of pads...
