### ISSUE TITLE
Retry in response to 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1547]
It's entirely possible that a box that might be inclined to send a Retry packet could receive 0-RTT packets before an Initial packet.  Right now, that box has to drop the 0-RTT, it is prohibited from sending a Retry.

There doesn't seem to be a strong reason to prohibit sending Retry here.  Nor is there any strong reason to disallow it.  

In favour of the existing text are some weak arguments:
* Allowing Retry here means that the number of Retry packets in flight might exceed the number of Initial packets.  But we already have text about ignoring old and redundant Retry packets.
* A server that is sending Retry does so primarily to avoid taking on extra work and dropping the 0-RTT and waiting for an Initial is the easiest thing to do.

In favour of the change are equally weak arguments:
* This would allow Retry to be faster in cases where an Initial is reordered or dropped.
* A Retry sent in response to 0-RTT is indistinguishable from one sent in response to Initial packets.

Did I miss anything?

**Comment by MikeBishop** [comment]
I remain in favor of changing this to "MAY wait for Initial"; servers shouldn't be required to do anything here, but there's no reason to prohibit it and it improves performance in some not-unreasonable cases.

**Comment by ianswett** [comment]
MAY or SHOULD are both fine with me.  However, if we say MAY, are we obliged to recommend some reasonable rate-limiting strategy to avoid sending a RETRY for every single incoming packet?

**Comment by martinthomson** [comment]
1:1 shouldn't cause any problems, even if Retry is larger than the 0-RTT packets (which it shouldn't be).  With the changes in #1498, the client can easily identify and filter out extra Retry packets.

**Comment by huitema** [comment]
The obvious point against "must not" is that it is not enforceable. Suppose that a box sometimes sends retry after receiving a 0-RTT packet. The receiver does not know whether this was sent in response to Initial, or whether Initial was lost and this was sent in response to 0-RTT.
