### ISSUE TITLE
Be more explicit about key derivation

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1568]
The text on key derivation is extremely thin and this is causing some people trouble.  We should expand this and be more explicit.

**Comment by kazuho** [comment]
IIRC some of us slightly leaned to using "tls13 " as the prefix for traffic secrets, so that we could use a session ticket obtained using TLS 1.3 over TCP in QUIC.

It would give us 1-RTT reduction when switching from H2 to HQ using alt-svc.

**Comment by martinthomson** [comment]
I don't see how resumption from h2 to hq is relevant.

Traffic secrets are generated by TLS, using "tls13 ", the only one that we have to worry about is the initial secrets, which QUIC derives.

**Comment by ianswett** [comment]
@kazuho for more discussion of resumption from TLS over TCP, see Issue #941 which is v2.

**Comment by kazuho** [comment]
> Traffic secrets are generated by TLS, using "tls13 ", the only one that we have to worry about is the initial secrets, which QUIC derives.

My understanding is that (at least for the interop) we have agreed to use "quic " for traffic secrets as well.

**Comment by kazuho** [comment]
@ianswett Thanks for the pointer. I left my comment there.
