### ISSUE TITLE
Updated information in retransmitted frames

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#157]
WINDOW_UPDATE is cumulative.  Requiring retransmission of the exact value that was sent in the past doesn't make sense if a more recent value is available.  Rather than loss triggering a retransmission of the frame that was lost, loss should trigger the creation of a NEW frame with updated details.

In [this comment](https://github.com/quicwg/base-drafts/pull/150#discussion_r96152215) @janaiyengar observes that probably all of the control-like frames could be treated specially if they need to be retransmitted.  Changing the "retransmission" rule for control (i.e., non-STREAM) frames to allow for updated information to be included might not benefit many of the other frame types, though it might make sense to make the rule general to allow for some flexibility

See also #146 where there is discussion about verbatim retransmission of STREAM frames.

**Comment by mirjak** [comment]
In this case I simply wouldn't call it a retransmission but sending of a new frame should be triggered if loss was detected.

**Comment by martinthomson** [comment]
I think that we're good with this.
