### ISSUE TITLE
Consider encrypting the long header payload length as part of packet number encryption

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#1576]
Encrypting the long header payload length would make all non-invariant bytes of QUICv1 encrypted (apart from the first byte). It wouldn't give us a significant privacy win because the length can be computed from the UDP length and/or searching for cleartext version numbers further in the payload - but obfuscating this could help reduce yet another possibility for ossification.

If we decide to move forward with #1575, then PNE for long header would just encrypt 8 bytes starting from the start of the payload length.

Apologies if this has been discussed before, I wasn't able to find it.

**Comment by rpaulo** [comment]
This would break coalesced packets (multiple QUIC packets in one UDP frame).

**Comment by DavidSchinazi** [comment]
How so? You decrypt one length/packet number at a time. Or am I missing something?

**Comment by DavidSchinazi** [comment]
@mikkelfj good point. This would break that scenario, thanks for bringing it up. Closing this issue.
