### ISSUE TITLE
qpack: control stream is not defined

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#1583]
"_The_ control stream" (with the definite article) is mentioned several times in the draft, but is never defined.

The control stream must be the Encoder Stream.  Should we `s/control stream/Encoder Stream/g`?

**Comment by afrind** [comment]
Yes, let's replace references to control stream with the encoder or decoder stream as appropriate.

**Comment by afrind** [comment]
Fixed by #1588
