### ISSUE TITLE
Use of "supports ECN" is confusing

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#1587]
The texts should not talk about supporting ECN because all QUIC endpoints support it. An endpoint that decides to not send ECT marked packets (for what every reason) still needs to send feedback. Even if the receiver cannot access the IP codepoint it will never see one and never send an ECN-ACK frame (but still supoort it).

**Comment by martinthomson** [comment]
Instances of that text that exist should only exist with respect to support on the path.  If you could point out specific instances, then we could fix this more easily.

**Comment by mirjak** [comment]
see PR #1631

**Comment by janaiyengar** [comment]
I don't think this distinction is useful, and I don't understand it. An endpoint can choose to not support ECN, for whatever reason, one of them being that the ECN codepoints are not accessible. If it helps to clarify this, I'm happy to write something that clarifies what "endpoint support of ECN" means... I don't think we need more than a sentence to clarify this.

**Comment by mirjak** [comment]
There are two parts of "support": one is using it on the forward path and the other one is to provide feedback to the other end that decided to use ECN on its forward path. These are two independent decision and that's why "supports ECN" is confusing. It could be "use ECN" and "supoort ECN feedback" but I would rather recommend to just be clear and try to avoid any confusion at all. 

Another point is that in TCP no ECN support can also mean that ECN is not implemented because it's an extension that was added later (and therefore you need to negotiate it in the handshake). This should not be the case for quic and we should not give the impression that the providing feedback is an optional feature for implementation. 

Also I think, If the other end wants to use ECN on its forward pass and you are able to access the IP ECN bits, you respect the design of the other end and send feedback. I guess we could make a stronger point about this...

**Comment by martinthomson** [comment]
Closed by #1631.
