### ISSUE TITLE
Single Stream of Bytes for CRYPTO Frames

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#1592]
Currently, the spec states:

> There is a separate flow of cryptographic handshake data in each encryption level, each of which starts at an offset of 0. This implies that each encryption level is treated as a separate CRYPTO stream of data.

This means you must track set of bytes in each encryption level (Initial, 0-RTT, Handshake and 1-RTT) as a separate stream and manage them accordingly; separate outstanding sent byte ranges, recovery ranges, acked ranges.

Additionally, it makes it a little unclear where one 'stream' stops and another 'starts'. For instance, in the 0-RTT case, the client (is supposed to) sends EOED with 0-RTT key, immediately followed by (ideally in the same UDP datagram, but not required) FIN with the Handshake key. If the 0-RTT EOED is lost, but the FIN isn't it could look like the client just skipped EOED. Instead, if they were all in the same stream, with FIN's offset starting where EOED left off, it would be easier to track this.

For these reasons, I propose each CRYPTO stream in each encryption level's offset starts where the previous level stopped.

**Comment by marten-seemann** [comment]
Wouldn’t that be equivalent to going back to a single CRYPTO stream, which changes encryption levels at various offsets?
If I remember correctly, this was one of the main pain points with the old design, so I’d be unhappy to revert this change.

**Comment by nibanks** [comment]
I wouldn't say we had exactly that, as now we are much more explicit with encryption level (as there are 4 different ones). Why do you say that was a pain point? I feel that is a much cleaner and explicit design to implement.

**Comment by ianswett** [comment]
I have the single stream approach implemented today, and it's ugly on the send side, because I need a very weird datastructure to determine what was sent at what encryption level and make sure there's no cross-encryption level bundling/etc.

With a stream per level, it's much clearer what's going on, and I can re-use most of the standard stream code.  I need to actually implement this, so maybe there are some issues I'm not anticipating, but I know the single stream approach is ugly.

**Comment by nibanks** [comment]
Using a standard stream for this will bring in 4 times the overhead. What is your FC limit for each stream? What tracking variables do you store for each? Having one stream with 4 offsets (Initial is implicitly offset 0) is a much more efficient design, IMO. I also have the single stream approach implemented (because that's what I thought  we were supposed to do, before I reread the spec) and I have a much simpler implementation that using 4 different streams.

**Comment by dtikhonov** [comment]
What is the attack, though?  Resource exhaustion?  So a handshake uses four (by the way -- why four? I thought there were three encryption levels) streams.  Once handshake is complete, the client can open a hundred streams with a single packet!

**Comment by nibanks** [comment]
Yes, the attack in this case would be resource exhaustion. There are 3 packet number spaces, but 4 encryption levels (Initial, 0-RTT, Handshake, 1-RTT). Each encryption level can be used to send CRYPTO frames (EOED uses 0-RTT). As for the number of streams a client can open, that is controllable by the server. It can choose to give less while under attack. Additionally, completing the handshake to get those extra streams requires additional resources on the attacker side, which might make the attack less attractive.

**Comment by dtikhonov** [comment]
Perhaps the recommendation, then, is not to allocate a lot of resources until the handshake is completed?  There are ways to minimize memory usage.  The server has other state in addition to the stream state, so the memory increase is not fourfold.

**Comment by nibanks** [comment]
I agree this isn't the only memory being allocated, but it is one that is directly controllable/influenced by the attacker. If they attack your flow control for each 'stream' they can attempt to maximize your memory usage and then move on to a new connection to do the same.

With a single stream (and associated FC window/buffer) it seems a lot easier to manage this attack. It is still doable with 4 streams, but requires some cross stream logic, which I doubt anyone already has.

**Comment by dtikhonov** [comment]
@nibanks, you've mentioned your own implementation twice, but one implementation's preference is a dubious argument for a specification change.

I don't claim to understand all intricacies of the CRYPTO frame design (we haven't gotten around to implementing draft-13).  Nevertheless, the current designed has been "Design Teamed" and hummed upon.

**Comment by nibanks** [comment]
I know the design team suggested the CRYPTO frame design. I was part of the design team. At the time, in the theoretical sense it all made sense. After implementing it, I have seen some issues. Also, I agree one implementation experience isn't enough to change things outright, but it's enough to open an issue and have the discussion.

I'm not arguing to undo everything. I am just trying to consolidate things I see as bloated and overly complex. I very much like the design of multiple encryption levels. All I am arguing for is a change in how each starts its offset.

If folks still generally believe the current way we have offsets is better, then so be it. That is not my experience, so that's why I opened the issue.

**Comment by ekr** [comment]
I prefer the "starts at zero" structure. I found it much easier to just
have separate flows and then not have to worry about data coming on one
encryption level that had offsets appropriate to another encryption level.

**Comment by nibanks** [comment]
Well, it seems like everyone else likes the current design, so I will leave it be.

FYI, I still plan to implement it as a single stream with offsets, but I will just add/subtract offsets when I receive/send the CRYPTO frames. That way I don't need to duplicate all the send tracking state, reassembly buffers/flow control. It's not as clean, but still gets me to the memory usage I wanted.
