### ISSUE TITLE
draft-ietf-quic-recovery: kMarkReductionFactor is not defined

### ISSUE THREAD

**Issue by aep** [quicwg/base-drafts#1594]
https://github.com/quicwg/base-drafts/blob/master/draft-ietf-quic-recovery.md#on-new-congestion-event

this is the first and only mention of kMarkReductionFactor

**Comment by ianswett** [comment]
Thanks.  I'm not sure how that was misspelled in that way, but it's now kLossReductionFactor, as it should have been.
