### ISSUE TITLE
Indicate support for PRIORITY

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1600]
Suggestion received in side conversation:  Enable the HTTP community to experiment with priority schemes and/or save bytes by defining settings indicating what priority schemes are supported.  Doc defines "none" and "this one", future extensions can define new ones.

This may or may not be necessary.  Any extension that defines a new priority scheme would presumably already define a setting to declare that it's supported, and the client will pick the one it likes best of what the server indicates support for.  Dealing with a client who combines frames from multiple priority schemes isn't something we need to define for HTTP/QUIC.  We could conceivably define a list format of priority scheme types, get a registry, etc. but that seems overkill when the SETTINGS space is large and the set of priority schemes likely to see much deployment is so small.

So this really boils down to a hint which permits a server to say "I don't support priority, so don't bother" or indicate that it really does support the current scheme.

**Comment by ianswett** [comment]
Thanks for filing this Mike.  I think it'd be useful for clients or servers that don't support the existing H2 style priorities to indicate that.

The anecdotal info I've heard indicates efforts to translate the h2 priority scheme into other schemes commonly performs poorly.

**Comment by rmarx** [comment]
Some more anecdotal evidence on difficulties mapping browser priorities/heuristics to H2 in a recent Twitter discussion: https://twitter.com/slightlylate/status/1027800719561125888?s=09

I am very in favor of allowing alternative priority schemes.

**Comment by mnot** [comment]
Discussed in NYC; agreement to close with no action.
