### ISSUE TITLE
Discuss HTTP/2 more in the introduction

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1601]
Per side-conversation feedback.  Maybe new text, maybe move some from HTTP/2 transition section.

**Comment by mikkelfj** [comment]
I think it is fair to give a gentle introduction to HTTP/2 literates, but on the other hand having to digest both HQ and HTTP/2 concepts is an additional burden if you come with no HTTP/2 background.

**Comment by malchata** [comment]
I can see both sides of this, but I personally feel it would be worth doing, as long as such an introduction was kept brief and highlights how QUIC addresses the shortcomings of H2.

**Comment by MikeBishop** [comment]
More generally, I'm using this as a placeholder to do a pass over RFC7540 and identify whether its requirements and concepts are:
- inapplicable
- restated
- referenced

If we aren't going to require people to page in H2 before trying to work on H3, everything needs to be one of those things.
