### ISSUE TITLE
qpack: acking headers that do not reference the dynamic table is wasteful

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#1603]
There is no need to acknowledge header blocks that do not reference the dynamic table.  These acknowledgements do not contain any information useful to the encoder.  I propose that the draft be modified to state that

```
    A header is acknowledged only when the Largest Reference in
    its Header Data Prefix is not zero.
```

This change
1. saves bytes -- improving compression and potentially avoiding extra unneeded _STREAM_ frames and packets; and
1. allows the encoder to drop state for such header blocks as soon as they are encoded.

**Comment by afrind** [comment]
Fixed by #1605
