### ISSUE TITLE
Wonky definition of kInitialWindow

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1615]
[This](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#constants-of-interest-1) renders poorly, as the lead-in is too long.  Consider a different approach to defining recommended values.

**Comment by ianswett** [comment]
I'm not sure how to fix this.  Suggestions?

**Comment by nibanks** [comment]
Maybe just moving all the recommendations last, and to use actual English to describe them, instead of functions? That might look better.

**Comment by martinthomson** [comment]
I was thinking exactly what Nick suggested.
