### ISSUE TITLE
Dead path timeout

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#1638]
#1614 makes idle timeout more precise, but still leaves open the question of when a path is considered dead.  We still need a path timeout to close paths over which an endpoint cannot reach a peer.

My suggestion here is to have N RTOs be a value that's used for detecting a dead path, for some reasonable value of N (5? 7?). An endpoint can close the connection when a path is considered dead or can wait for a new path to become available (this is extremely useful when migrating from wifi to cell).

**Comment by ianswett** [comment]
Related to this, is #1049 closed?

**Comment by mirjak** [comment]
Is it the transport that should automatically try to reconnect or the application? In the later case it's just the question about when should the transport give up and tell the application and probably to we want to fail the transport fast than TCP usually does?

**Comment by mirjak** [comment]
Are we talking about multipath or re-connection (where you start with a new handshake)? I guess it the latter.

However also for multipath it's a tricky question and while mptcp was charter to provide a solution that can work without app layer changes it turns out that you usually need high layer input (because a full mesh between all available IP address is usually not what you want ;-) ).

**Comment by janaiyengar** [comment]
FWIW, SCTP had clear rules about path and connection timeouts, and it used two different numRTOs for them. I think the draft should talk about when to abandon a path and when to abandon a connection, but not recommend what should be done in terms of retrying new connections.

**Comment by martinthomson** [comment]
Tokyo conclusion: this is not a normative requirement.  A little bit of text about the need to declare paths and not connections dead in response to connectivity issues might be added to transport.  Marking editorial.
