### ISSUE TITLE
The server shouldn't use a token for much

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1647]
The token that a server provides in Retry or NEW_TOKEN isn't authenticated.  It can be used multiple times and it isn't folded into the handshake.  This is an explicit limitation of the design.  Neither client nor server can therefore rely on its contents for much.  A server can ensure that the token is self-authenticating (by including a MAC or self encrypting it with an AEAD, for instance), but it shouldn't really use the information beyond its immediate purpose: address validation.

**Comment by mikkelfj** [comment]
If adding such advice, please be specific about encryption is not authentication. Although QUIC implementers would or should now, it could easily be missed by infrastructure operators. Merely stating AEAD or MAC can easily be misread as golang.encrypt(x) should be fine.
