### ISSUE TITLE
ACKs imply stream state transitions

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1667]
We have text from a long-ago issue that says:

> A packet MUST NOT be acknowledged until packet protection has been successfully removed and all frames contained in the packet have been processed.  **Any stream state transitions triggered by the frame MUST have occurred.**

Since the move to MAX_STREAM_ID and the updated stream state machine, implementations no longer need to track the stream state transitions on the peer, only locally.  Do we still need this requirement?

**Comment by ianswett** [comment]
I don't think so?

**Comment by martinthomson** [comment]
I don't think that there are any state transitions that would be illegal that would result from this.  The "all frames have been processed clause" covers this anyway.  Let me double-check the state machines, but I think that this is OK.
