### ISSUE TITLE
TLS dependencies and packet number encryption

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#1669]
Given that PN encryption is not TLS specific and could/should be performed the same way even if a different crypto handshake protocol is used, I wonder if that part should rather go in the tranport draft. Not that the tls draft is actually named "Using Transport Layer Security (TLS) to Secure QUIC".

**Comment by mikkelfj** [comment]
The same argument could be made about transport parameters.

**Comment by MikeBishop** [comment]
@mikkelfj, transport parameters *are* in the transport doc.  The TLS doc simply defines a TLS extension capable of transporting the blob QUIC hands it.  That bit is TLS-specific.

I tend to think that all of packet protection belongs in the transport document, not the TLS document. TLS produces keys; QUIC consumes keys from its crypto handshake (which in this version is TLS).

**Comment by martinthomson** [comment]
One of the pieces of restructuring we have considered is moving the packet protection completely across.  That's tracked by #411. We'll address that there.
