### ISSUE TITLE
Recommendation for rate limits

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#1673]
There are to recommended/required rate limits in the transport draft:

"an endpoint MAY
   limit the rate at which it sends PATH_RESPONSE frames"

and

"Until a peer's address is deemed valid, an endpoint MUST
   limit the rate at which it sends data to this address."

Can we maybe provide more guidance what those rate limits should be or at least an upper bound because otherwise using normative language doesn't help much...?

**Comment by mirjak** [comment]
Same is true for re-tries:

"An endpoint SHOULD abandon path validation after sending some number
   of PATH_CHALLENGE frames or after some time has passed."

"A receiver MAY send
   MAX_STREAM_DATA frames in multiple packets..."

**Comment by martinthomson** [comment]
> an endpoint MAY limit the rate at which it sends PATH_RESPONSE frames

This needs no recommendation in my view.  This only allows for PATH_CHALLENGE to be dropped by a recipient, like the network might do.

> Until a peer's address is deemed valid, an endpoint MUST limit the rate at which it sends data to this address.

This needs to use the IW rules.

> An endpoint SHOULD abandon path validation after sending some number of PATH_CHALLENGE frames or after some time has passed

No recommendation needed here.

> A receiver MAY send MAX_STREAM_DATA frames in multiple packets

Or here.

**Comment by martinthomson** [comment]
The only item here that needs text includes that text already:

> endpoint MUST limit the rate at which it sends data to this address. The endpoint MUST NOT send more than a minimum congestion window’s worth of data per estimated round-trip time
