### ISSUE TITLE
PN of CLOSE

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#1674]
The spec provides an exeption for packet with closing frames to be re-send with the same PN (and then all state could be removed and only the packet must be stored). However, the packet could be store and before send out again the PN could be increased by one. Yes this requires to re-do PNE but that only needs very limited addtional state. Is that really necessary?

**Comment by mikkelfj** [comment]
If you close when you run out of packet numbers.

**Comment by ianswett** [comment]
Changing the PN requires re-encrypting the entire packet, which requires enough state to do that, which is likely larger than storing the payload of a connection close packet.

**Comment by MikeBishop** [comment]
Yep.  If the packet number weren't the IV to the payload encryption, you could keep the encrypted payload and just PNE a new packet number.  However, because of how that's connected, changing the packet number requires you to start over from the plaintext of the payload.

**Comment by martinthomson** [comment]
The allowance [here](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#immediate-close) isn't harmful.  And we don't say that endpoints can't regenerate the closing packet with new packet numbers.

So what is the exact problem here?

**Comment by mirjak** [comment]
I thought it's just not necessary but didn't realize that you have to re-encode the payload as well. So that's fine.
