### ISSUE TITLE
"Payload" vs. "content"

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1676]
@mirjak points out that payload and content are both used to refer to the body of QUIC packets.  Worth doing a pass to ensure that these are used consistently.  My first pass at definitions:

- "Payload" is the collection of frames in the encrypted body of the packet.
- "Content" is the conceptual set of information conveyed by those frames, but probably not something we reference very often in the spec.

**Comment by mirjak** [comment]
Yes, I agree with this definition there might actually only a few cases where its not correct but further I think it would be important to actually define this somewhere explicitly.

Or to say your definition in other words
Payload is the thing in a PACKET that follows the header.
Content is any information or data carried in a FRAME.
