### ISSUE TITLE
Does the first byte of stateless reset include random bits?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1678]
Section 6.13.4 of draft-transport-14 defines the first byte of the stateless reset packet as:
```
   +-+-+-+-+-+-+-+-+
   |0|K|1|1|0|0|0|0|
   +-+-+-+-+-+-+-+-+
```
I notice that the first byte is slightly different from the specification of the short header in section 4.2:
```
   +-+-+-+-+-+-+-+-+
   |0|K|1|1|0|R R R|
   +-+-+-+-+-+-+-+-+
```
Is that deliberate, or just an oversight?

**Comment by martinthomson** [comment]
It was deliberate, but only as a simplification.  Once we know what those R values are, we can fix this too.

**Comment by martinthomson** [comment]
This has been addressed.  The text now shows:

```
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|0|1|               Unpredictable Bits (182..)                ...
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
