### ISSUE TITLE
Ordering of ACK Frame fields

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#168]
Computing the length of an ACK frame is unnecessarily complicated because there are a series of length fields the implementation has to check. These fields are themselves of variable length from the start of the frame because they are placed after ACK frame content. This amounts to a lot of traversing of memory just to just to figure out how much memory to pull to process the ACK.

A simple solution would be to move NumBlocks and NumTS to immediate after the ACK frame flags. This would have no impact on the protocol except to ease implementation.

**Comment by ianswett** [comment]
Sounds good to me.

**Comment by ianswett** [comment]
@marten-seemann and @janaiyengar Any reasons why this wouldn't be a good change?

**Comment by marten-seemann** [comment]
lgtm

**Comment by mnot** [comment]
Subset of #62
