### ISSUE TITLE
QPACK does not specify how to handle invalid input on control streams

### ISSUE THREAD

**Issue by afrind** [quicwg/base-drafts#1683]
From Bence via the mailing list:

It is possible for a peer to receive invalid data on the encoder or decoder stream.  For example, on the encoder stream, a Duplicate instruction might address an already evicted entry.  Or on the decoder stream, a Table State Synchronize might contain an Insert Count exceeding the total number of applicable inserts and duplications, or the Header Acknowledgement might contain a Stream ID for which there are no unacknowledged header blocks.  As far as I can tell, the spec currently gives no direction on what should happen in such cases.

I propose that these should be treated as connection errors.

HTTP_QPACK_DECOMPRESSION_FAILED seems like a relevant error code, but it does not really match any of these cases (strictly speaking, these errors do not happen during decompression), especially incorrect data on the decoder stream (because it is the encoder, not the decoder,
that detects the error).  Should there be one error code covering all these cases, something like HTTP_QPACK_ERROR?  Or should there be multiple, like HTTP_QPACK_DECOMPRESSION_FAILED for errors on HEADERS and PUSH_PROMISE frames, and self-explanatory HTTP_QPACK_ENCODER_STREAM_ERROR and HTTP_QPACK_DECODER_STREAM_ERROR?

**Comment by bencebeky** [comment]
Drafted a pull request to move the discussion forward.  The phrasing might be a little clumsy at places, but it should be good enough to spark a conversation.

**Comment by kazuho** [comment]
My preference goes to having one error code, optionally with the ability to associate the stream ID that caused the error. Please refer to 
https://github.com/quicwg/base-drafts/pull/1726#issuecomment-419612428 for the rationale.
