### ISSUE TITLE
QPACK should explicitly state ordering requirements for headers within a block

### ISSUE THREAD

**Issue by afrind** [quicwg/base-drafts#1684]
From Bence via the mailing list:

HPACK Section 1.3 defines a "Header List" as "an ordered collection of header fields...".  QPACK uses the term "Header Set" instead and does not require it to be ordered.  HPACK has a whole section, 2.1, on ordering, whereas QPACK does not spell out this guarantee.  However, since frames on a given stream are guaranteed to be ordered by the underlying transport, my impression is that QPACK as specified already guarantees to preserve order of header fields within a header list. (Also in my experience things can break in colorful ways if you start reordering headers in your application.)

I propose to add language on the requirement to preserve order, and to use the expression "header list" instead of "header set" throughout. The clause "header list ... can contain duplicate header fields" should probably also be included.

**Comment by bencebeky** [comment]
Created #1725.  Also, I should have titled this issue "...ordering requirements for header fields within a header list".
