### ISSUE TITLE
Error for not receiving SETTINGS frame as the first frame on a control stream

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#1697]
The paragraph says the a SETTING frame must be the first frame on a control stream but it does not specifies which error should be sent if that is not the case.

>  A SETTINGS frame MUST be sent as the first frame of either control stream (see {{stream-mapping}}) by each peer, and MUST NOT be sent subsequently or on any other stream. If an endpoint receives an SETTINGS frame on a different stream, the endpoint MUST respond with a connection error of type HTTP_WRONG_STREAM. If an endpoint receives a second SETTINGS frame, the endpoint MUST respond with a connection error of type HTTP_MALFORMED_FRAME.

**Comment by MikeBishop** [comment]
Also, the control streams are now not so prominent in the referenced section.  I'm thinking a more generally clean-up is warranted, and perhaps even separating control vs. request/response streams.
