### ISSUE TITLE
Connection ID collisions

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#170]
There's currently no behavior defined for the case of a connection ID collision.
The probability for a collision of two 64 bit numbers is *really small*, if connections IDs are chosen randomly. For example, for a server handling 100,000 concurrent connections, the collision probability is about 3*10^-10.
It might therefore be justified to completely neglect this issue.

According to the current draft, if a client initiates a handshake and chooses an existing connection ID, the server would just silently discard those packets, because it already switched to an encrypted connection and will regard them as undecryptable.

**Comment by ianswett** [comment]
Yes, the packets would be discarded and the connection would fail.  I think that's a good response, given how infrequently it's expected to happen.

**Comment by martinthomson** [comment]
I agree with @ianswett here.  Given that the same client won't generate a colliding packet number (or it shouldn't), the server could recognize this by observing a change in the remote IP and port.  It could therefore handle the new connection (and propose a new connection ID) if it really wanted to.  But I wouldn't expect them to, it's just so damned unlikely.

The real question here is: do we need to write anything down about this?

**Comment by martinduke** [comment]
I've edited #169 to consider this possibility as well.

**Comment by janaiyengar** [comment]
Given that we're heading towards server-generated connection IDs, I suggest we close this issue.

**Comment by martinthomson** [comment]
I think that we still need to consider this.  The odds are going to be extremely low, because it's only really relevant during version negotiation of the two colliding identifiers.  But we should probably at least acknowledge the problem even if we don't plan to do anything about it.

**Comment by ianswett** [comment]
We could assume both connection ID and IP/port are all unchanging during the handshake, which would allow the collision to be resolved when the server picks a new connection id.  I believe this solves the collision problem in every case I can imagine.

Yeah for server chosen connection ids!

**Comment by martinthomson** [comment]
@ianswett, your point being that if you have a collision on connection ID + source IP + source port then you have won the lottery and you might as well give up (chances are that this is a badly busted client).  Otherwise, the server can pick a new connection ID during the handshake and avoid collisions.  That WFM.

**Comment by martinthomson** [comment]
@ianswett, your point being that if you have a collision on connection ID + source IP + source port then you have won the lottery and you might as well give up (chances are that this is a badly busted client).  Otherwise, the server can pick a new connection ID during the handshake and avoid collisions.  That WFM.

**Comment by martinthomson** [comment]
I think that this was mostly addressed with #361.  @marten-seemann reopen this if you think that we need to include specific text dealing with collisions.
