### ISSUE TITLE
GOAWAY with StreamID == 0

### ISSUE THREAD

**Issue by lnicco** [quicwg/base-drafts#1717]
The current text says about the StreamID in the GOAWAY frame definition:

> This identifier ... MAY be zero if no requests were processed.

With the latest transport changes, stream 0 is now a valid bidirectional stream, so GOAWAY(0) actually means that stream 0 is accepted/could be opened.
This opens up a case where an endpoint cannot know for sure whether the remote endpoint has accepted stream 0 or not.

If you agree this is an issue, I see two options to fix this: 
one is to add a flag to the GOAWAY frame that identify this particular case; 
another one is to sacrifice one stream and slightly change the GOAWAY semantics to say that StreamID is the id of the last client-initiated stream plus one, i.e. the endpoint agree that any stream with ID >= StreamID was not accepted.

**Comment by martinthomson** [comment]
Good catch.   I prefer the "this stream and all higher ones were not processed, guaranteed" interpretation.  Flags are awful.
