### ISSUE TITLE
recovery: clarification on TLP when sender is outpacing the timer

### ISSUE THREAD

**Issue by aep** [quicwg/base-drafts#1718]
The TLP is reset on every sent packet.
What's happen in my implementation is that the TLP never fires if the sender just keeps sending. If an Ack never arrives, this means disconnect is never detected until the window is full.

I'm not sure what i missed in the spec that is supposed to prevent that.

**Comment by mikkelfj** [comment]
As I understand it, the TLP is there to ensure the receiver sees something that it can ACK, in case a packet is lost. If you keep sending ACK'able content that problem never occurs, and it is fair that the timer is not triggered.

TLP is not meant to detect that the peer closed the connection but rather that the sender stopped sending (hence tail loss probe), possibly close to connection close, but not necessarily.

If you keep missing ACK's another trigger sets in: you loss rate gets too high and you close the connection. There is ongoing discussions about negoatiating how an ACK can be delayed.

https://github.com/quicwg/base-drafts/pull/1715#pullrequestreview-151076864

dead path dection:
https://github.com/quicwg/base-drafts/issues/1638

**Comment by aep** [comment]
thanks, i didn't these issues are related because they talk about what happens after RTO fires, which never happens in this case.

I also could not find the spec for which loss rate is considered dead. Is this something that is simply not specified or am i blind?

**Comment by mikkelfj** [comment]
Mmm - why doesn't RTO fire? If you do not get a timely ACK, you should retransmit? TLP just helps make that happen faster near the end. Retransmit can happen based on gaps in ACK or timeout, or both (from memory, spec keep changing). If you only rely on gap in ACK, then yes, it would not trigger, so that is a bad strategy to use exclusively unless you use an aggressive connection timeout.

I'm not sure the critical loss rate is documented explicitly - but perhaps a section is needed to discuss this further?  In any case, the loss rate is highly application specific because you might operate infiniband where minimal delays a considered critical and any loss unlikely, or you might be on domestic congested wifi with high loss rates, or on a satellite link with large RTT and possible large loss bursts. Loss can also happen from DoS attacks or on path attacks and may have to adjust to circumstances.

If both peers cooperate, a connection close should happen. If not, a timeout happens eventually, and and a stateless reset may happen much earlier when supported and when the path is still viable but the endpoint is not.

**Comment by mikkelfj** [comment]
I just skimmed over the recover / loss spec - it seems that RTO is only triggered after TLP fires. In that case you are right. I agree that this seems wrong and not what I would have expected, but I have not read the loss doc very carefully recently.

**Comment by mikkelfj** [comment]
I think we need to wait for @ianswett to comment on this.

**Comment by mikkelfj** [comment]
Maybe the problem is that RTO depends on TLP. TLP reset makes sense isolated but not when impacts triggering RTO. This could be a side-effect of trying to have only one timer active at time.

**Comment by siyengar** [comment]
You will have to stop sending at some point because you will hit cwnd limited or flow control limit

**Comment by mikkelfj** [comment]
@aep already mentioned the window the original post, but that can take along time if you just send small status messages just below TLP timeout.

**Comment by siyengar** [comment]
Why are you not getting acks? The peer will use a delayed ack timer which will be practicallly << tlp timer. If the peer is not acting at all then the peer is not going to get optimal perf either

**Comment by aep** [comment]
@siyengar the problem discussed is dead peer detection. its not sending acks because its dead.

**Comment by huitema** [comment]
@aep what @mikkelfj said. TLP should not be resetting the RTO timer. That is, even if you want to manage just one timer, you should have a check that if TLP would expire after the nominal RTO, then use RTO instead.

**Comment by siyengar** [comment]
Dead peers are detected by an idle timeout which can happen before the window is full. The idle timeout definition recently changed, if you were using the previous one then it’s possible that the implementation is setting the timer on every send. However idle timeout will now only be reset on the first send

**Comment by ianswett** [comment]
To address your first question, PR #1652 adds some more clarity to transport on the idle timeout and makes it clear that if you're sending into a void without receiving any ACKs, you should not keep extending your idle timeout.  The recovery doc doesn't describe anything relating to the idle timer, FWIW.

The intent is for the RTO timer to only go off after TLP.  There is text about setting the TLP to the min(TLP timeout, RTO timeout) in 4.3.2(https://tools.ietf.org/html/draft-ietf-quic-recovery-14#section-4.3.2).  If you want to discuss whether that should be what this document tries to specify, please open a separate issue about whether RTO should ever fire before any TLPs are sent?

Dead peer detection(#1638) is an entirely different problem, and there's no effort to describe that in the recovery draft at the moment.  It would be nice to talk about that somewhere, but I'm not sure it's known what best practices are?

**Comment by aep** [comment]
thanks for clarification.  I'm using a separate timer on idle now that only extends on incomming ack.

It would really help to describe best practices here a little further. But i'm unsure if its needed for other implementors who just follow quic-transport after implementing recovery.

**Comment by ianswett** [comment]
Q: Best practices for idle timeouts, dead path timeouts, or something else?

**Comment by aep** [comment]
all of it ;)  
Currently i'm just counting seconds since the last received ack, but that doesnt detect paths that are alive but unusable because of high packet loss for example. There's probably alot more details in this that i simply don't know about.  Should duplicated packets be filtered before the count? What about keepalive packets? Who sends them, when? etc

**Comment by ianswett** [comment]
I don't think we'll provide any guidelines on how high is too high for packet loss, because I'm doubtful we could write good general purpose guidance.

I don't have any clear advice on the rest of the questions except what's already in the transport and http docs.

**Comment by aep** [comment]
fair enough. thanks for your input :)
