### ISSUE TITLE
initial_max_stream_data_bidi_remote is a very capable foot gun

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1720]
Draft 14 splits the definition of "initial_max_stream_data" into two parameters, "initial_max_stream_data_bidi_local(0)" and "initial_max_stream_data_bidi_remote(10)". In early interop tests, we observed an interesting failure to communicate between the picoquic client and the winquic server because of that. Winquic server did not provide a value for the initial_max_stream_data_bidi_remote parameter, which meant that for client initiated streams like stream 0 the initial value of was 0. As a result, picoquic did not send any data on stream zero, the stream zero was not open, winquic did not send back any update for the stream 0 MAX_STREAM_DATA value, the server did not receive any request from the client, and after a suitable period of silence the connection was closed.

I would suggest two fixes:

1) Explain that servers that expect to receive messages such as HTTP requests from clients SHOULD send the "initial_max_stream_data_bidi_remote(10)" parameter and set it to a reasonable value.

2) Explain that if a client wants to open a stream but initial_max_stream_data_bidi_remote value is 0, it SHOULD send an empty STREAM frame to open the stream -- and give the server a chance to send back MAX_STREAM_DATA update for that stream.

**Comment by martinthomson** [comment]
Not sure if this belongs in http or transport.

**Comment by ianswett** [comment]
I'd say the first suggestion should become a MUST in the http draft.  Not advertising a reasonable value for initial_max_stream_data_bidi_remote should not be allowed, though I realize there's a wide range of what 'reasonable' is.  Possibly 1024 bytes is a bare minimum?

**Comment by martinthomson** [comment]
Any of these settings could be 0 if the intent is to update immediately after connection or stream establishment.  Values might be updated based on SETTINGS, for instance.  But 0 is rarely the right choice if that type of stream is intended to be used.

**Comment by MikeBishop** [comment]
The HTTP layer on the client is presumably offering bytes to the transport, so the transport should handle this like normal, no?  If it has bytes it can't send, it sends STREAM_BLOCKED to signal that state.  So I'd be inclined to recommend that rather than the empty STREAM frame, though I think the state machine effect is the same either way.

**Comment by huitema** [comment]
Sending the STREAM_BLOCKED frame facilitates diagnostic, but it does not solve the issue. Stream blocked frames are informational, and many implementations just ignore them.

**Comment by kazuho** [comment]
I do not have a strong opinion on the issue, but let me note that the same issue exists with max_stream_id_*.
