### ISSUE TITLE
When to send Stateless Reset

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#1728]
Section 6.2.2. Server Packet Handling, says, at the end:

> Servers MUST drop incoming packets under all other circumstances. They SHOULD send a Stateless Reset (Section 6.13.4) if they are able.

The last sentence is a bit dangerous.  A stateless reset should NOT be sent when the endpoint has access to the connection state and can't decrypt a packet.  Otherwise any random packet would kill a connection.  Saying "if they are able" might be interpreted incorrectly.  Can we just change it to "They SHOULD send a Stateless Reset (Section 6.13.4) when they no longer have access to the complete connection state."?

The way I understand it, a stateless reset token would be something that the endpoint saves in non-volatile memory which can be used to reset connections after a crash/reboot.

**Comment by martinthomson** [comment]
This also doesn't reflect the symmetric nature of stateless reset.  I will adjust.
