### ISSUE TITLE
Size of HTTP Headers Sequence Numbers

### ISSUE THREAD

**Issue by krasic** [quicwg/base-drafts#173]
Re: 5.2.2. HEADERS

Defines the sequence number as 16 bits.  

Under the HTTP mapping, with stream ids being 32 bit, and 2 streams per request, the limit would be ~ 2^30 requests per connection.   The 16 bit HEADERs sequence number will run out much sooner.

Unless the assumption is that these HEADERs sequence numbers can wrap around, and the active range constrained, ala TCP sequence numbers.

Or a third alternative might be to go with compressed, ala issue #154.

Maybe sequence numbers could adopt the integer encoding scheme of HPACK?

**Comment by MikeBishop** [comment]
I'm hoping that the sequence number is just vestigial, but you're correct.  I'll add text that allows them to wrap.  If you have 2^16 outstanding HEADERS frames in a given direction, you're likely doing something wrong.
