### ISSUE TITLE
Is zero a valid argument for the Table State Synchronize instruction?

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#1736]
The QPACK draft is unclear about if insert count of zero should be considered a valid argument of the Table State Synchronize instruction.

I think we should better clarify that to avoid interoperability issues (my fear is that if some minor portion of QUIC stacks consider insert_count of zero to be invalid, some QUIC stacks might get shipped without noticing the existence of such stacks. Then, we would see interoperability issues in the wild).

FWIW, my weak preference goes to prohibiting use of zero as the argument. One way of achieving that would be to change the argument of the insruction to _number_of_inserts - 1_.

**Comment by dtikhonov** [comment]
We can make zero invalid and keep the zero byte as a potential extension mechanism.

**Comment by MikeBishop** [comment]
If it's valid, the literal interpretation of it would be no-op.  I would be opposed to allowing an instruction that would move the value backwards, but having no effect seems relatively unobjectionable.

**Comment by afrind** [comment]
There's never a reason to send TSS/0, unless your implementation is buggy or lazy about calculating when to send it.  I'm not sure I see it as an extension point, but making zero invalid seems reasonable to me.  I prefer that to sending inserts - 1, which seems like another opportunity for off-by-one errors.
