### ISSUE TITLE
QPACK has no Security Considerations

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1737]
The full text of that section is "TBD."

**Comment by afrind** [comment]
HPACK covers the following topics:

Probing Dynamic Table State
Static Huffman Encoding
Memory Consumption/DoS
Implementation Limits

To what degree to we need to retread this vs referring to 7541?

There are some new areas to cover related to DoS, like recommending implementation timeouts for blocking requests.  Soliciting any other topics, and possibly a passionate security-minded volunteer to draft a PR.
