### ISSUE TITLE
Receiving same New Connection ID twice

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1738]
All frames are idempotent. I read that to mean that if the same New Connection ID frame is received twice, the second transmission should be a no-op. I assume that "same frame" here means the same connection ID, the same reset secret, and the same sequence if we still care about sequences. That much is fine. But what if the two frames are almost the same, say with the same connection ID and a different reset secret? Should the node update the previously received secret, or should it signal a protocol violation?

A variation of that happens if the node sends a "New Connection ID" frame, and the connection ID is the same as the source ID used by that node. I assume it is a protocol violation. Or is it just a nice way for clients to tell servers about their reset secret?

(I realize that there may be work in progress in some secret PR -- but then, please submit it to the main repo.)

**Comment by erickinnear** [comment]
@huitema I'm not aware of any secret PR. 
What I think you're referring to is the output from the Connection ID design team, which will be submitted as a PR to the main repo after all members of that DT have had a chance to review the latest proposal (hopefully tonight). It seems reasonable to make sure that everyone on the DT is happy with its output before submitting it to the main repo and representing it as such. 

Regardless, I don't believe that any of that work currently has impact on this issue, which is both a very good point and something that should probably be clarified.

**Comment by huitema** [comment]
OK, will submit a separate PR then.

**Comment by huitema** [comment]
@erickinnear The parenthesis was because after I flagged a similar issue (#1729), @martinthomson asked me to "Please see erickinnear#4 - that address this problem (and some others)." I read that, wanted to comment, and could not because of some access control. And I wasn't even aware that the CNXID design team was still working on something, since in theory draft 13 was incorporating the team's design.

**Comment by huitema** [comment]
Entered PR #1739

**Comment by martinthomson** [comment]
Closed by #1739.
