### ISSUE TITLE
Clarify whether QUIC packets with no payload are acceptable

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#1745]
QUIC changed to allow empty STREAM frames.

Are QUIC packets with no payload also acceptable?  They're pointless, but also presumably harmless?  Either way, it's worth being specific about this.

**Comment by nibanks** [comment]
I agree they are harmless and I would prefer not to need to add extra logic to my implementation to check for empty packets. My vote is to allow them.

**Comment by marten-seemann** [comment]
The reason we allowed empty STREAM frames was because they serve a purpose (they cause a change in the stream state machine). Before this change, you'd have to send a MAX_STREAM_DATA frame with the current offset, which was not a nice solution.

I'd prefer to keep disallowing empty packets, unless someone can come up with any use case for that.

**Comment by ianswett** [comment]
Marten, you said "keep disallowing empty packets", but I couldn't find any text in the IETF drafts that forbids them.  Possibly I missed it and then I'm happy to close this issue, since at least it's clear.

**Comment by RyanAtGoogle** [comment]
I agree with @marten-seemann. If there's no reason for empty packets to exist, I'd prefer we forbid them.

**Comment by marten-seemann** [comment]
@ianswett: I didn’t look it up in the draft, but that’s what gQUIC is doing, that’s why I said we should keep doing it.

**Comment by mikkelfj** [comment]
If you forbid empty, you must also consider padding only. And then you must consider if keep alive only happens with ping, which is extra load on the connection. What can go wrong with empty? Bandwidth abuse? That can happen by other means.

**Comment by ianswett** [comment]
Thanks for clarifying Marten, that is what gQUIC does today.

Empty packets definitely should not elicit an ACK, since they're tiny and there's nothing to declare lost/retransmit/etc.

**Comment by mikkelfj** [comment]
No, that is the point / PING has more overhead. You might not care for ping every keep alive packet. Not a big deal, just saying.

**Comment by martinthomson** [comment]
Section 5:

> QUIC payloads MUST contain at least one frame, and MAY contain multiple frames and multiple frame types.

**Comment by igorlord** [comment]
An empty long-header packet would be a natural choice for coalescing with a non-empty short-header packet.  Would we want to therefore call it a valid packet?  Or still call it invalid and let the language of "4.9. Coalescing Packets" take care of this case:

> If one or more packets in
>    a datagram cannot be processed yet [..] or processing fails (decryption failure, unknown type,
>    etc.), the receiver MUST still attempt to process the remaining
>    packets.  The skipped packets MAY either be discarded or buffered for
>    later processing [..].
