### ISSUE TITLE
QPACK: stream cancellation only required when max dynamic table size > 0

### ISSUE THREAD

**Issue by afrind** [quicwg/base-drafts#1747]
The stream cancellation instruction serves to help the encoder cleanup state related to the dynamic table, but a decoder that sets the maximum dynamic table size to 0 does not need to send them.  Now that we omit header acknowledgement for blocks with no dynamic table references, this is the only use of the QPACK control streams for an implementation not using the dynamic table.

This is not to be confused with the encoder's current table size, which can be temporarily zero but raised later to the decoder's maximum.

**Comment by martinthomson** [comment]
If you think of this as an optimization for the case where there is no dynamic table AND you are cancelling streams (i.e., an exceptional condition on an exceptional condition), this really gets exciting (not).  Let them send cancellations.

**Comment by dtikhonov** [comment]
Why send cancellations that serve no purpose?  My vote is for a consistent spec.

**Comment by kazuho** [comment]
I do not have a strong opinion on this, but I do think the proposal can be considered as a simplification.

The proposal allows endpoints that set maximum dynamic table size to zero to not even open a decoder stream. Maybe we could go one step further and forbid the creation of encoder stream if the maximum dynamic table size advertised by peer is zero.

Then, we can have simple HQ stacks that do not handle QPACK streams at all.

**Comment by dtikhonov** [comment]
Amen.

**Comment by mikkelfj** [comment]
That would be useful for constrained devices.

**Comment by afrind** [comment]
@bencebeky : in HQ you can only send SETTINGS at the beginning of the connection, for all the reasons you describe.

@kazuho : my reasoning here was exactly to allow for simpler implementations that do not implement a dynamic table.  I hadn't thought about not opening the streams, but I'm not sure it really matters - nothing will ever be sent on them so you can effectively ignore them.

**Comment by bencebeky** [comment]
Sorry, I wasn't aware of this amazing restriction in HQ.  Makes sense.

**Comment by martinthomson** [comment]
So the biggest problem here is for a generic implementation of the encoder where it now needs to handle the expectation of stream cancellation acknowledgment specially.  When I send a header block, I track the need for acknowledgment.  Creating the tracking in a way that is robust against that is tricky.

**Comment by kazuho** [comment]
@afrind 
> my reasoning here was exactly to allow for simpler implementations that do not implement a dynamic table.

:+1:

> I hadn't thought about not opening the streams, but I'm not sure it really matters - nothing will ever be sent on them so you can effectively ignore them.

The issue is the additional state. You need to accept the creation of the decoder stream and you cannot reset it. For memory constrained devices, we could have QUIC stacks that support only a small number of currently operating streams. Spending one stream for transmitting nothing would be an overhead.

**Comment by MikeBishop** [comment]
@martinthomson, I'm not sure that you do.  If the decoder's maximum size is zero, you can never insert to the dynamic table, and therefore can never emit a header block that references it.  That means you'll never have sent a header block that expects an acknowledgement, since we already agreed not to ack static-only blocks.

**Comment by martinthomson** [comment]
Right, that was the conclusion of the discussion in NYC.
