### ISSUE TITLE
TLP is getting triggered too early

### ISSUE THREAD

**Issue by DenisLug** [quicwg/base-drafts#1748]
When the function `SetLossDetectionTimer()` has been implemented like shown [in the draft](https://tools.ietf.org/html/draft-ietf-quic-recovery-14#section-4.5.7.4) I get the problem that the `tlp_timeout` gets the default value of 10ms when sending the first paket, because the `UpdateRTT()` has not been invoked yet. This leads into sending of probe shortly after sending the first packet.

Does anyone has experienced the same behaviour? Would a non-zero initial value for the srtt be a solution for this?

**Comment by siyengar** [comment]
If update rtt hasn’t been invoked yet it seems like you would still have handshake packets outstanding right? Could you elaborate on the situation that triggers this behavior

**Comment by DenisLug** [comment]
Thank you for your responses. In fact we had not considered the handshake packets before. Now the TLP is working without any problems.
