### ISSUE TITLE
Does DCID change after HelloRetryRequest?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1757]
When the client needs to send a subsequent Initial packet in response to the server's Initial packet (after HRR, containing ACKs, etc.), does it continue to use the same DCID as the first Initial packet, or does it update the DCID to the SCID from the server's Initial packet?

If the DCID changes, then load balancers cannot reliably identify which packets contain server-selected CIDs.  If the DCID does *not* change, then the Initial packet cannot be coalesced with Handshake packets due to the requirement that all packets in a datagram contain the same DCID.

**Comment by huitema** [comment]
There is no such thing as a HelloRetryRequest in Quic. There are just some bits produced by the TLS component, telling QUIC to please send this over Initial or Handshakes packet. So the answer to the question is very simple: NO, the CID should not change.

**Comment by martinthomson** [comment]
Fixed in #1788.
