### ISSUE TITLE
CONNECTION_CLOSE reliability

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#177]
>  If the total number of packets transmitted in this connection reaches 2^64 - 1, the sender MUST close the connection by sending a CONNECTION_CLOSE frame with the error code QUIC_SEQUENCE_NUMBER_LIMIT_REACHED

If this packet is lost there is not packet number available for its retransmission. CONNECTION_CLOSE should be reliably transmitted.

**Comment by marten-seemann** [comment]
Related: #192

**Comment by martinthomson** [comment]
Closed by #724.

**Comment by martinthomson** [comment]
I think that I meant #721.

**Comment by martinthomson** [comment]
Fixed in #721.
