### ISSUE TITLE
Build a version negotiation mechanism that mostly doesn't add round trips

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#1773]
In QUIC, version upgrade doesn't work w/o aditional RTs.

Consider the case where the client and server start out supporting version N. Then the client starts supporting N+1. If it offers N+1, then it's going to basically take an extra RT with every server, so it has to offer N, but then when the server upgrades to N+1, you have to take a RT to get to N+1. See #1755 for one such design

**Comment by martinthomson** [comment]
We discussed this in NYC and agreed as a WG that this is good in principle, but the PR needed a little more work.

**Comment by martinthomson** [comment]
This now has a new proposal in #2133.

**Comment by martinthomson** [comment]
Tokyo proposal: take version downgrade protections out of the draft, make a new draft with an extension that provides that.  This would entail merging a fixed-up version of #2313 into the docs.  Disabling downgrade protection would fix #1810.

If that extension makes traction before we complete v1, then we can merge it back in.

**Comment by martinthomson** [comment]
Resolution included in #2313.  We'll take this on in a new version (or extension).
