### ISSUE TITLE
OnRetransmissionTimeoutVerified issue

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#1774]
Issue for what I described to @ianswett at dinner yesterday.

When `OnRetransmissionTimeoutVerified` is called from `OnPacketAcked` for the highest ACK in a block, all earlier packets are marked as lost, even if they are contained in that same block. That seems suboptimal.

**Comment by ianswett** [comment]
Yeah, this is not intended behavior, so I'll clarify that both the text and pseudocode.
