### ISSUE TITLE
Editorial issue with STOP_WAITING

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#178]
In Section 7.3 (STOP_WAITING Frame), Least Unacked Delta is calculated using the packet ID of the packet carrying the STOP_WAITING frame. This is reasonable. 

In the ACK Frame section:

> An endpoint SHOULD use the "Largest Acked" packet number it received to calculate the "Least Unacked Delta" value in any STOP_WAITING frame it might send.

Maybe I understood it wrong but it suggest to calculate Least Unacked Delta using "Largest Acked".
This should be written in a different way if it meant that the information from an ack (not only "Largest Acked" but also unacked gaps ) is used to decide to send a STOP_WAITING frame.

**Comment by ianswett** [comment]
The intent is to cause the least unacked in the stop waiting to be raised to the most recently received largest acked.

Would it be clearer if the sentence was "The endpoint SHOULD raise the Least Unacked communicated via future STOP_WAITING frames to the most recently received Largest Acked"?

**Comment by ddragana** [comment]
Yes, that is clearer. Thanks.

**Comment by mcmanus** [comment]
can this be closed because of #66

**Comment by ianswett** [comment]
Closed with 358
