### ISSUE TITLE
Handshake failure after Retry

### ISSUE THREAD

**Issue by tatsuhiro-t** [quicwg/base-drafts#1784]
I found that there is a corner case that handshake fails after Retry.
The current specification allows server not to change its SCID in Retry packet.  In other words, server is allowed to set client chosen CID in SCID field of Retry packet.
The spec also allows client to create fresh TLS context each time it receives Retry packet.
If they are used, there is a case that handshake fails after Retry packet.
Here is the possible scenario.

1. client sends Initial to server with TLS context T0: Initial SCID=A DCID=B
2. client resends Initial to server with TLS context T0: Initial SCID=A DCID=B
3. client receives Retry from server: Retry SCID=B DCID=A ODCID=B
4. in response to Retry(3), client sends Initial to server with TLS context T1: Initial SCID=A DCID=B
5. client receives Retry from server (in response to client Initial(2)): Retry SCID=B DCID=A ODCID=B ODCID=B
6. in response to Retry(5), client sends Initial to server with TLS context T2: Initial SCID=A DCID=B
7. client receives Initial from server (in response to client Initial(4), thus using TLS context T1): Initial SCID=C DCID=A
8. client receives Handshake from server (which uses TLS context T1): Handshake SCID=C DCID=A

client cannot decrypt Handshake packet from server because client uses TLS context T2 meanwhile server uses TLS context T1.

**Comment by nibanks** [comment]
I guess the solution is to either:

a) Require Retry to change the CID.
b) Restrict the client from starting a new TLS context in response to Retry.
c) Have some other way for the client to differentiate between Retries, other than CID.

a) sounds like the simplest option to me.,

**Comment by ianswett** [comment]
My previous assumption was that if the client the connection ID the same,
it was the same connection, and therefore the TLS context should be kept
the same.

a) is likely ok, but I believe the variant of b) above fits better with the
design we have I believe?

**Comment by martinthomson** [comment]
Good catch.  This is effectively the same as the case where we required connection ID to change for the client's benefit, except in reverse.  I have a PR in chain that includes the discussed changes to Retry that I can roll this into.
