### ISSUE TITLE
Text for "half-closed (remote)"

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#179]
> A stream that is "half-closed (remote)" is no longer being used by
>    the peer to send any data.  In this state, a sender is no longer
>    obligated to maintain a receiver stream-level flow-control window.
> 
>    If an endpoint receives any STREAM frames for a stream that is in
>    this state, it MUST close the connection with a
>    QUIC_STREAM_DATA_AFTER_TERMINATION error (Section 11).

If a packet sent before the packet with FIN bit set gets lost and is retransmitted is going to cause close of the connection.
The text needs to change to say if a frame with offset  larger than the offset + size of the frame with FIN bit set is received. (or a better wording)

(An editorial remark: In the "Lifecycle of a stream" diagram going from "half-closed(remote)" to "closed" should be cause by "send FIN" not "recv FIN" and from "half-closed(local)" to "closed" should be cause by "recv FIN")

**Comment by martinthomson** [comment]
Yes, the correct formulation here is: if a STREAM frame *containing octets that are greater in offset than the last octet in a closed stream*, then the receiver MUST terminate ...  A receiver SHOULD retain a last octet value for closed streams for a short period of time after they close.  This value is the largest received octet offset if the stream is terminated by a STREAM frame containing a FIN bit; a peer will include this value in a RST_STREAM frame.

**Comment by martinthomson** [comment]
I think that we can keep this editorial.

**Comment by martinthomson** [comment]
We've a lot of [new text](https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#final-offset) here.  If there are any remaining errors, please open a new issue.
