### ISSUE TITLE
Avoid renewing retired connection IDs

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#1799]
to avoid a receiver accepting a retransmitted NEW_CONNECTION_ID, after the same connection ID has been retired. This can happen if a receiver receives, uses, and quickly retires a connection ID, but the sender is still retransmitting because it hasn't yet received an acknowledgment for the NEW_CONNECTION_ID frame.

A simple proposal (I believe due to @marten-seemann) is to add a sequence number to NEW_CONNECTION_ID, which is used in RETIRE_CONNECTION_ID. Then a receiver can easily discard old connection IDs.

**Comment by MikeBishop** [comment]
This is basically un-removing #1465.

**Comment by janaiyengar** [comment]
@igorlord : yes, that would be up to the receiver
