### ISSUE TITLE
Server's SETTINGS can be omitted in 0-RTT

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#1809]
#1808 adds a requirement to error out if the first frame on the control stream is not SETTINGS.  There's an existing error for duplicate control streams.  But what if the control stream never opens at all?

The current state of SETTINGS is that:
- In 1-RTT: Clients MUST wait until they see the server's SETTINGS frame before sending requests; the server MUST see the client's SETTINGS before sending any responses.  If either side fails to open the control stream and send SETTINGS, the connection stalls.
- In 0-RTT:  Servers MUST wait until they see the client's SETTINGS frame before sending responses; this is no different.  Clients, however, assume previous settings and update them *when* the server's SETTINGS frame is eventually seen.

It is a violation for the server to send responses without having sent the SETTINGS frame.  However, there is no requirement that clients validate this behavior because of reordering.  This means that a spec-conformant client would interop just fine with a server that never sends SETTINGS on 0-RTT connections.

Should we introduce a wait-for-SETTINGS requirement later in the connection (for example, before sending new requests in 1-RTT), or just hope that it's easier for servers to do the same compliant thing for both 0-RTT and 1-RTT connections?

**Comment by kazuho** [comment]
This is an interesting issue!

I might argue for banning the server from sending SETTINGS when 0-RTT is used. The client will assume that the SETTINGS obtained in the previous connection to be valid for during 0-RTT _and 1-RTT_.

**Comment by martinthomson** [comment]
I would prefer to have the SETTINGS frame always present.

**Comment by martinthomson** [comment]
That's an implementation choice.  I think that #1808 covers things well enough.  I don't see any reason to - for example - force the client to wait on SETTINGS before writing requests in 1-RTT, for example.

**Comment by kazuho** [comment]
My understanding is that the approach @martinthomson suggests is what we do in H2, and I think that's workable.

**Comment by MikeBishop** [comment]
Closing with no action.
