### ISSUE TITLE
Timing issues in version downgrade attack prevention

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#1810]
Current design requires the contents of the Version Negotiation packet and that of the `supported_versions` field of the Transport Parameters to be identical.

In practice, this is a requirement hard if not impossible to always meet.

Consider the case of upgrading the server from a version that supports v1 only to a version that supports v1 and v2.

If a client accesses the server running the old version using a v2 Initial, it would receive a Version Negotiation packet and retry with a v1 Initial. If the server was upgraded before the resent Initial is received, then the server will include both v1 and v2 in the Transport Parameters, and the client will terminate the handshake considering that a version downgrade attack has been mounted.

Same issue arises when you have a server cluster. The first Initial (that is responded by a Version Negotiation packet) and the second Initial might be delivered to a different node of a server cluster supporting different set of QUIC versions (note: it is rare to upgrade all the nodes behind a server cluster atomically).

IMO, we should either drop version downgrade attack prevention as a whole (as have been proposed in #1755), or move the detection logic to the server-side (e.g., by requiring the client to include in TP all the versions that it preferred to use rather than the version found in the packet header) so that the server could ignore the timing issues during an upgrade.

**Comment by martinthomson** [comment]
This should be addressed by the proposal on the table for #1773.

**Comment by martinthomson** [comment]
Removing downgrade protection (#1773) will fix this, and the responsibility for fixing this will fall on the extension draft.

**Comment by martinduke** [comment]
Given #2001, I'm not convinced this is a problem. Post-VN, we'll have the same CID and it's routed to the same server. Server upgrade between two INITIAL packets on the same CID is an exceedingly small corner case.

**Comment by kazuho** [comment]
@martinduke I'm not sure if I agree.

Firstly, the server might get upgraded after sending VN but before it receives the resent Initial. So there's a timing issue. Secondly, future version of QUIC might have different definition of CID than what we have in v1. In such case, CID will change when the client downgrades to v1 (in response to VN).

**Comment by martinduke** [comment]
Isn't the CID invariant?

**Comment by martinduke** [comment]
Isn't the CID invariant?

**Comment by kazuho** [comment]
Length of CID is. How to use the CID field is not.

**Comment by mnot** [comment]
From Tokyo: overcome by events.
