### ISSUE TITLE
MAX_DATA doesn't comply with MAX_STREAM_DATA

### ISSUE THREAD

**Issue by goelvidhi** [quicwg/base-drafts#1812]
Based on the draft, a receiver can compute MAX_DATA as below:

"A receiver might use a sum of bytes consumed on all contributing streams to determine the maximum data limit to be advertised."

But if the receiver misbehaves and advertises MAX_DATA (for example, 2MB) that doesn't comply with MAX_STREAM_DATA (for example, 3MB), does that mean that the sender is blocked if it has already sent up to 2MB?

**Comment by marten-seemann** [comment]
Yes, that's exactly the point of connection-level flow control.

**Comment by MikeBishop** [comment]
That's not misbehavior, it's reflecting the fact that stream- and connection-level flow control may have different constraints.
