### ISSUE TITLE
QUIC_FLOW_CONTROL_RECEIVED_TOO_MUCH_DATA isn't defined anywhere

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#1813]
We probably just want to use FLOW_CONTROL_ERROR and let the implementations specify a better reason if they want to.

**Comment by ajmacedonia** [comment]
QUIC_FLOW_CONTROL_RECEIVED_TOO_MUCH_DATA was removed in transport-draft-05, however Section 8.4. MAX_DATA Frame of the transport draft still references this error.
