### ISSUE TITLE
handshake timer spec is inconsistent

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#1816]
Section 4.3.1 of quic-recovery says:

The initial handshake timeout SHOULD be set to twice the initial RTT.

but the pseudocode says:

timeout = max(timeout + max_ack_delay, kMinTLPTimeout)

Do we include max_ack_delay or not?

**Comment by ianswett** [comment]
My intent was to not include max_ack_delay in the handshake timeout, because "4.4.1.  Crypto Handshake Data" advises using a very short or no ACK delay for handshake packets.
