### ISSUE TITLE
Use a "stream" for transmitting CIDs

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#1826]
Transmission of new and retired CIDs is something that do not need low latency, but it seems like it is going to have lot of code specific to the purpose.

Looking at #1799, I am starting to wonder if we could use a "stream" to carry the new and retiring CIDs (sorry for suggesting to change the approach at a late moment).

**Proposed Design**

Like the CRYPTO frame that carries the TLS messages, We will have a CID frame that carries the CID messages. This is essentially a "CID stream" much like the "CRYPTO stream."

The format of a CID frame will be equivalent to the CRYPTO frame.

A CID message has the following structure. Type is either NEW_CID (0) or RETIRE_CID (1).

```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|    Type (8)   |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                          Length (i)                         ...
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                       CONNECTION ID (*)                     ...
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

If necessary, we could flow-control the CIDs, by instead of flow-control based on octets, the number of CIDs given to the peer by the NEW_CID messages will be governed by a MAX_NEW_CID frame that is equivalent to the MAX_STREAM_ID frame, except for the fact that it carries the number of CIDs.

**Upsides**

Code reuse _and_ design reuse.

We can reuse a lot of code. Basically, we only need glue code and codec for the CID messages. All the code that relates to retransmission and back-pressure can be reused. We are also reusing a design that we are familiar with.

These aspects lead to less issues.

**Downsides**

Head-of-line blocking in the delivery of CIDs. But as I stated, I do not think that would be an issue in practice.

EDIT. clarify that flow control is optional (Oct 2 2115Z).

**Comment by nibanks** [comment]
You assume code reuse, but that is not necessarily the case. I'd prefer not to add this much overhead just for CIDs. Especially this late in the process.

**Comment by dtikhonov** [comment]
I proposed something very similar (use a special stream) at the very first CID DT meeting a couple of months ago.  Everyone else was against this.

**Comment by kazuho** [comment]
@nibanks My argument would be that because we are this late in the process, it is good to reuse an existing design rather than trying to fix issues with a special-purpose mechanism that none of us have implemented.

@dtikhonov Yeah I am sorry for that. Later changes (i.e. sending "retire" as an explicit signal and the reintroduction of sequence numbers to NEW_CID) made me inclined to the design.

**Comment by dtikhonov** [comment]
> My argument would be that because we are this late in the process, it is preferable to reuse an existing mechanism rather than trying to fix issues with a special-purpose mechanism that none of us have implemented.

+1

> Later changes (i.e. sending "retire" as an explicit signal and the reintroduction of sequence numbers to NEW_CID) made me inclined to the design.

OK.  I support this proposal, which makes two of us, @kazuho.

**Comment by kazuho** [comment]
> I'm wondering if we really need two different framing layers here (one for the CID frame and one for the CID message). Could we just introduce a sequence number for NEW_CID (which would be limited by MAX_NEW_CID), and keep RETIRE_CID as separate frame?

IMO, the costs with that approach are:
* Without using a "stream", you'd need to do book-keeping of each CID being received by the NEW_CID frame, because the frames can arrive out-of-order. "Stream" guarantees in-order-delivery and therefore you only need to maintain a counter.
* Not carrying NEW_CID and RETIRE_CID as a "message" on top of "streams" also means that you would have a retransmission logic specific to those frames.

**Comment by kazuho** [comment]
@marten-seemann @mikkelfj The proposed encoding of "CID stream" is exactly the same as that of the "CRYPTO stream". Why cannot you reuse that the same way you would reuse an actual QUIC stream?

>> Not carrying NEW_CID and RETIRE_CID as a "message" on top of "streams" also means that you would have a retransmission logic specific to those frames.
> 
> Why is that? They'd just be normal retransmittable frames, wouldn't they?

IIUC, there are two ways to send states. One is to retransmit frames. The other is to transmit the current state when necessary. For stacks that implement the latter approach, NEW_CID and RETIRE_CID will be a special-purpose logic. I am not saying that it is hard. But "retransmission of frames" is not all the stacks have as a concept.

**Comment by mikkelfj** [comment]
Yes, that also worries me a bit. But CRYPTO has a limited lifespan and can be done in a hacked custom implementation without interfering with a highly tuned stream implementation. you could also hack the CID stream, but that is then another and longer living hack.

**Comment by mikkelfj** [comment]
If stream frames need to be ordered, I think tagging a serial on them as proposed in the above is simpler. Then you have no FIN bit or RST whatever to consider. Nor can you write across packet boundaries. Etc. I think your stream proposal already does most of that, so it is actually far from a stream abstraction.

**Comment by kazuho** [comment]
> But CRYPTO has a limited lifespan and can be done in a hacked custom implementation without interfering with a highly tuned stream implementation. you could also hack the CID stream, but that is then another and longer living hack.

I am not sure if that is true, considering the fact that CRYPTO stream for 1-RTT packets lives forever.

> If stream frames need to be ordered, I think tagging a serial on them as proposed in the above is simpler. Then you have no FIN bit or RST whatever to consider.

CRYPTO stream that "CID stream" reuses does not have FIN or RST.

**Comment by nibanks** [comment]
I still feel that making them a stream is more overhead than necessary. For instance, if you sent three new CIDs to the peer and the first is lost, if you have a stream design, the second two stay around longer than necessary on the sender side.

Overall, I'm still not sure of the problem that currently exists that this is the solution to. What doesn't work with the current model that would require this design to fix? I feel like we're at a phase where we should start taking changes required to fix a particular problem, not changes that (some believe) make for a cleaner design.

**Comment by mikkelfj** [comment]
> I am not sure if that is true, considering the fact that CRYPTO stream for 1-RTT packets lives forever.

I was afraid you'd say that (I haven't reached the HS part in detail).

>CRYPTO stream that "CID stream" reuses does not have FIN or RST.

Which just proves my point, that it is a special case with special handling. I actually think it may be fine to do special handling for stream frames as well, as long as we don't call it streams and instead optimize it for what it is rather than a leaking abstraction.

**Comment by kazuho** [comment]
@nibanks 
> I still feel that making them a stream is more overhead than necessary. For instance, if you sent three new CIDs to the peer and the first is lost, if you have a stream design, the second two stay around longer than necessary on the sender side.

It is true that head-of-line blocking exists. But IMO it is not an issue latency-wise (because there is no need to race for 1-RTT for delivering / retiring CIDs) nor memory-wise (because CIDs are so small compared to stream buffers and because there would only be few CIDs inflight.

> Overall, I'm still not sure of the problem that currently exists that this is the solution to. What doesn't work with the current model that would require this design to fix? I feel like we're at a phase where we should start taking changes required to fix a particular problem, not changes that (some believe) make for a cleaner design.

FWIW, my view is that the proposal retains the new model (i.e. retirement of CIDs always transmitted as an explicit signal), at the same time changing the transmission framework of the CIDs to a mechanism that have proven record (rather than introducing a framework specific to the purpose).

As I have stated earlier, it is beneficial to use a proven method because we are at a later moment like this, instead of trying to fix all the design issues of a framework specific to transmitting CIDs that we haven't seen any interop.

**Comment by dtikhonov** [comment]
> the proposal retains the new model (i.e. retirement of CIDs always transmitted as an explicit signal), at the same time changing the transmission framework of the CIDs to a *mechanism that have proven record (rather than introducing a framework specific to the purpose)*.

[Emphasis added.]

Agree 100%.

**Comment by marten-seemann** [comment]
> As I have stated earlier, it is beneficial to use a proven method because we are at a later moment like this, instead of trying to fix all the design issues of a framework specific to transmitting CIDs that we haven't seen any interop.

The proven method here is the use of the MAX_NEW_CID frame (because we have that kind of frame for flow control and stream IDs). I'm not sure if putting things on a "stream" will actually simplify implementations.

Maybe we can combine your proposal of the MAX_NEW_CID with my proposal of adding a sequence number?

**Comment by dtikhonov** [comment]
> I proposed something very similar (use a special stream)...

To elaborate on my thinking about this.

In my mind, using an actual stream (with STREAM and MAX_STREAM_DATA frames) eliminates the need for new frame types.  Imagine a special flow-controlled CID stream.  For simplicity, assume CIDs are 8 bytes long.  If the flow control window is 64 bytes, writing 32 bytes to the stream (4 CIDs) will trigger a MAX_STREAM_DATA from the peer.  This is the signal to write more CIDs to the stream.  If the peer is not consuming the CIDs, MAX_STREAM_DATA is not sent and no CIDs are emitted.

The original objections to this was that the transport layer does not *own* the streams.  I don't know how to respond to this.  It seems that adding new frame types and protocol-like specifications around them for every new thing that we think to add to QUIC is not the most pragmatic thing to do.  Take the CRYPTO frames, for example: chances are, they are just wrappers on the stream mechanism anyway.

Perhaps a stream-based CID mechanism could be made into an extension which would use a new type of unidirectional stream for this purpose.

On the other hand, it seems we're going around in circles -- redesigning the design of the Design Team...

**Comment by marten-seemann** [comment]
> In my mind, using an actual stream (with STREAM and MAX_STREAM_DATA frames) eliminates the need for new frame types. Imagine a special flow-controlled CID stream. For simplicity, assume CIDs are 8 bytes long. If the flow control window is 64 bytes, writing 32 bytes to the stream (4 CIDs) will trigger a MAX_STREAM_DATA from the peer. This is the signal to write more CIDs to the stream. If the peer is not consuming the CIDs, MAX_STREAM_DATA is not sent and no CIDs are emitted.

That seems like a misuse of streams to me. You could end up with CID frames split up in the middle. I'm not saying that this wouldn't work, it just doesn't seem like a nice way to engineer a solution to me.

> The original objections to this was that the transport layer does not own the streams. I don't know how to respond to this. It seems that adding new frame types and protocol-like specifications around them for every new thing that we think to add to QUIC is not the most pragmatic thing to do. Take the CRYPTO frames, for example: chances are, they are just wrappers on the stream mechanism anyway.

They're not, in my implementation.
To me, using frames and protocol-like specification for new protocol features seems like exactly the way things should be.

**Comment by MikeBishop** [comment]
I'm dubious about the stream approach.  You could model it like flow control, but unlike flow control, there's also the retire issue -- stream data is never really "retired."  Also, while there are reasons we want all sequence numbers to be generated in order, there's no reason you need to block using CID 7 because you haven't seen CID 6.

**Comment by kazuho** [comment]
@MikeBishop FWIW, I do not think that flow control of CIDs is essential, even though I included that in this proposal. CRYPTO streams do not have flow control, and "CID frames" would work fine without flow control too (assuming that we continue allowing the receiver to "forget" CIDs).

> there's also the retire issue -- stream data is never really "retired." 

Would you mind elaborating on this? For the CID, the proposal has a RETIRE message. But I assume you are referring to something else.

> Also, while there are reasons we want all sequence numbers to be generated in order, there's no reason you need to block using CID 7 because you haven't seen CID 6.

That's correct. But it is still a requirement for book keeping. My point is that it would be worthwhile to consider reusing the "streams" approach, if we are to require book keeping using sequence numbers in a situation where HoLB is not a concern.

**Comment by MikeBishop** [comment]
You're still building the new/retire machinery inside this proposal, because it's needed and existing streams don't have that concept.  So you have those messages *inside* a stream-like structure.  I'm having trouble seeing what this actually makes simpler; I think having frames that affect state is a more natural fit to how QUIC works.

**Comment by janaiyengar** [comment]
Discussed, this might be overkill. Closing.
