### ISSUE TITLE
PLPMTUD section claims that PADDING frames generate ACKs

### ISSUE THREAD

**Issue by ajmacedonia** [quicwg/base-drafts#1827]
Section 8.4.2. of the transport draft (Special Considerations for Packetization Layer PMTU Discovery) says:
"The PADDING frame provides a useful option for PMTU probe packets. PADDING frames generate acknowledgements, but they need not be delivered reliably."

Meanwhile Section 8.1. of the transport draft (Packet Processing and Acknowledgment) contains language suggesting that PADDING frames do not generate acknowledgements. Also I believe this was the conclusion reached in older issues about PADDING frames generating ACKs so Section 8.4.2 is in error.

It may also be helpful, in Section 8.4.2, to state that PING+PADDING is useful for PMTU probe packets, as that will generate an ACK while allowing the packet to be inflated to whatever size necessary.

**Comment by mikkelfj** [comment]
I think the 8.1 section is reasonably clear

> To avoid creating an indefinite feedback loop, an endpoint MUST NOT send an ACK frame in response to a packet containing only ACK or PADDING frames, even if there are packet gaps which precede the received packet. The endpoint MUST acknowledge packets containing only ACK or PADDING frames in the next ACK frame that it sends.

but the next paragraph could be misread even if it is correct:

> While PADDING frames do not elicit an ACK frame from a receiver,

indeed it does not elicit ACK's, meaning that receiving PADDING does not trigger the peers urge to ACK incoming packets. Only when non-ACK, non-PADDING packets are received, will an ACK be transmitted (and possible during tail loss probe - not sure about that)
