### ISSUE TITLE
Abstraction of TLS

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#183]
The question is whether we maintain TLS as some abstract concept or not.

We could talk about "the cryptographic handshake" and features that it provides in the abstract when referring to them in the transport document.  Or we could just describe how this protocol works in concrete terms.

Proponents of the first seem to think that would make replacing TLS easier.  Others disagree.  Others think that replacing TLS would be a bad idea.  Others think that replacing TLS is the only rational choice.  Some people think that people who hold opposing opinions are completely nuts.

**Comment by britram** [comment]
Yay, another vi versus emacs.

I'd submit that completely separate from how the protocol is normatively defined in quic-transport, the exercise of talking about the cryptographic handshake in the abstract (as well as the properties of the interface between QUIC and ~TLS~ ~the cryptographic protocol~ TLS for stream/frame data) is useful its own right, in part to determine how in/dependent the transport/crypto interface is on peculiarities of TLS.

**Comment by martinthomson** [comment]
I'm going to close this on the basis that a) it's a dumpster fire of a discussion, and b) we have something of a plan that isn't improved by having the issue open to track it.
