### ISSUE TITLE
Contradicting statement about when CID can be changed during the handshake

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#1830]
#1794 introduced the following sentence in section 4.4:
> All subsequent Initial packets from the client MUST use the connection ID and token values from the Retry packet. 

I wonder if it contradicts with the following statement in section 4.10:
> During the handshake, a client can receive both a Retry and an Initial packet, and thus be given two opportunities to update the Destination Connection ID it sends. A client MUST only change the value it sends in the Destination Connection ID in response to the first packet of each type it receives from the server (Retry or Initial); a server MUST set its value based on the Initial packet. Any additional changes are not permitted; if subsequent packets of those types include a different Source Connection ID, they MUST be discarded.

My read is that section 4.10 allows CID of Initial packet to be changed twice at maximum, in case when the client first receives a Retry and then an Initial packet. However, section 4.4 does not allow the latter to happen.

To me it seems like an editorial issue introduced in #1794, and IMO it might make sense to drop the description in section 4.4 by instead referring to the provision in 4.10.

**Comment by MikeBishop** [comment]
I think the intent here is clear, but you're correct that we should clean up the text.
