### ISSUE TITLE
Optional packet length field in the short header?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#1831]
I'm wondering if it would be useful to optionally allow SH packets to carry a packet length field, as LH packets do. This would allow SH packets to be coalesced behind SH packets, which might be useful?

We could burn a flag bit to indicate the presence of said packet length field, but before doing a more detailed design I'd like to understand if coalescing of SH packets behind SH packets is something that anyone cares about?

**Comment by mikkelfj** [comment]
If you do that, you should also consider it in the context of transports other than UDP. I.e. ensure that the context ID (there, I said it, it is not a connection ID) is sufficient over header less transports such as a RS232 bus.

As to coalescing just for the sake of coalescing, I think it will just complicate things. As soon as you have short headers, you can do all sorts of optimizations with packet delivery and processing, but if you must also deal with coalescing at this level, it complicates things, so there need to be a good reason for that.

I'm not sure why coalescing would be useful for its own sake, over a UDP transport.

**Comment by nibanks** [comment]
At least with my implementation, I don't see a need to coalesce SH packets. I fill each SH packet to the max of the UDP payload size and then move to the next packet.

**Comment by britram** [comment]
I also don't see the point here; LH* SH? seems to be sufficient given the semantics of the two header types.

**Comment by mikkelfj** [comment]
I do think it might be a good idea to reserve the bit for use cases such as non-UDP transport, but that is not to say that has to happen in V1, or ever over UDP.

**Comment by larseggert** [comment]
Thanks for the feedback
