### ISSUE TITLE
HTTP: State that an empty SETTINGS frame is legal

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#1832]
[draft-ietf-quic-http-15](https://tools.ietf.org/html/draft-ietf-quic-http-15#section-4.2.6) states:

```
   A SETTINGS frame MUST be sent as the first frame of either control
   stream (see Section 3) by each peer [...]
```

Because both HTTP settings have default values, one should be able to send an empty _SETTINGS_ frame to indicate that the defaults are used.  Nevertheless, this is not specified in the draft.  I think it should be.

**Comment by MikeBishop** [comment]
A reasonable clarification.  I don't think anything currently *prohibits* a SETTINGS frame from being empty, but we should explicitly state that it contains zero or more values.

**Comment by dtikhonov** [comment]
Upon closer reading, I discovered this:

```
   The payload of a SETTINGS frame consists of zero or more parameters,
```

Closing the issue: invalid.
