### ISSUE TITLE
Forbid TLS-level KeyUpdate in draft-ietf-quic-tls

### ISSUE THREAD

**Issue by davidben** [quicwg/base-drafts#1833]
Since QUIC uses its own mechanism, the spec should say the TLS-level KeyUpdate MUST NOT be sent and MUST be treated as a fatal error on receive.

Otherwise an implementation may forget about this and, when TLS sees a KeyUpdate, call some callback in some weird unexpected way and confuse things.

**Comment by mikkelfj** [comment]
There must be some form of key update otherwise GCM is not safe on long running connections.

**Comment by MikeBishop** [comment]
There is.  TLS, section 6.
