### ISSUE TITLE
Error code constraints

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#184]
QUIC-TRANSPORT defines the syntax of QUIC error codes and defines some values for the QUIC transport. The section says:

> This section lists the defined QUIC transport error codes that may be used in a CONNECTION_CLOSE or RST_STREAM frame. Error codes share a common code space. Some error codes apply only to either streams or the entire connection and have no defined semantics in the other context.

Since the error space is shared, it is not clear what error codes are appropriate to use with which frame types. There is the possibility for endpoints to send a semantically incorrect error code in a frame. How should a receiver handle such an occurrence?

This possibility exists only for the Application-specific, QUIC transport or Cryptographic error codes. Host-local error codes must not be sent.  

As an example, a client sends a `RST_STREAM` frame with the error code `QUIC_TOO_MANY_SESSIONS_ON_SERVER`.  Is this actually allowed and what should the server do (close the connection, igore it, ...)?

**Comment by MikeBishop** [comment]
A convention we used in HTTP/2 with some success is that an endpoint MAY always treat a stream error as connection-fatal if the implementation so chooses.  So any error code is acceptable in a CONNECTION_CLOSE.  I'd advocate for that, at least.

And why isn't GOAWAY mentioned?

**Comment by MikeBishop** [comment]
Overtaken by events.  RST_STREAM no longer contains transport-level error codes (other than STOPPING), and application versus transport _CLOSE frames are separate.
