### ISSUE TITLE
When to ignore coalesced packets and when to terminate the connection

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#1840]
[QUIC Transport "Coalescing Packets" section](https://tools.ietf.org/html/draft-ietf-quic-transport-15#section-4.9) states:

> If one or more packets in a datagram cannot be processed yet (because the keys are not yet
> available) or processing fails (decryption failure, unknown type, etc.), the receiver MUST still
> attempt to process the remaining packets.

The "etc" needs to be clarified.

There are many conditions under which the receiver MUST (or SHOULD or MAY) terminate the connection.  It is not clear when the requirement to terminate the connection trumps the requirement to attempt to process remaining packets and when it does not.

**Comment by MikeBishop** [comment]
My interpretation would be that fatal errors can only occur *while processing* a packet, which is to say that protection has been successfully removed and you're consuming frames out of the payload.  Errors that prevent you from doing any processing in the first place, however, should cause you to keep going to other packets.

In other words, for most purposes, handle the packets independently -- if they were in separate datagrams and one was garbage, you'd move to the next-received datagram.

**Comment by martinthomson** [comment]
Closed as part of the reorg.
