### ISSUE TITLE
Should the key update expansion use "quic " or "tls13 "?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#1845]
I am looking at the details of the key update mechanism. The TLS draft says that "_A receiving endpoint detects an update when the KEY_PHASE bit doesn’t match what it is expecting. It creates a new secret (see Section 7.2 of [TLS13]) and the corresponding read key and IV._" That means using HKDF-Expand-Label.

I assume that we are going to use the prefix “quic “ rather than “tls13 “, since that's what we do at all the other places that use HKDF-Expand-Label. But the spec is silent. Maybe it should have a mention about the prefix for the label expansion?

**Comment by martinthomson** [comment]
I think that folks in slack settled on "quic ".  We need to write that down though.
