### ISSUE TITLE
STREAM_ID_BLOCKED frame can't encode being blocked on stream 0

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#1850]
The STREAM_ID_BLOCKED frame has the Stream ID field which is

> A variable-length integer indicating the highest stream ID that the sender was permitted to open.

This encoding doesn't allow to convey that the peer (in this case, this is always the client) would like to open stream 0, but the server didn't allow any bidirectional stream in the transport parameters (i.e. sent a 0 for `initial_max_stream_data_bidi_remote`).

The easy fix for this is to send the stream ID of the stream that the peer was **not** permitted to open due to missing stream flow control credit.

This would also have the nice property to make this frame more symmetric with the BLOCKED and STREAM_BLOCKED frames. For example, for STREAM_BLOCKED an offset of 0 means that the peer was **not** allowed to send byte 0 on that stream.

**Comment by janaiyengar** [comment]
Good catch. Your proposal seems reasonable to me.

**Comment by dtikhonov** [comment]
> Or we could finally decide that 0 is not a stream. 0 was invented for a reason.

Uh-oh -- not this can of worms again! :smile:

**Comment by ianswett** [comment]
+1 to 0 not being a stream from my perspective.

That being said, my understanding was that the question of 0 being a valid stream id(or 0 being a valid packet number) had clear lack of consensus, with about half the group wanting 0 to be valid and the other wanting to start at 1.

**Comment by marten-seemann** [comment]
I agree that 0 should not be a stream, and that 0 should not be a packet number. It's really useful to have a sentinel value.
Making 0 a valid stream created a bunch of overhead in my code - nothing complicated, just a bunch of bools of stream 0 was already created or not.

**Comment by dtikhonov** [comment]
I am with you about 0 being an invalid number for stream and packet numbers, @ianswett and @marten-seemann, and I also stated this on the mailing list. The (unofficial?) consensus seems to be 0, however. Should we be re-arguing the same issues over and over again?

**Comment by ianswett** [comment]
Anything worth arguing once is worth arguing at least twice based on past experience in this WG.

**Comment by mikkelfj** [comment]
The complication is that streams are module 4, so if 0 is invalid, so should stream 1, 2, and 3.

**Comment by marten-seemann** [comment]
> I am with you about 0 being an invalid number for stream and packet numbers, @ianswett and @marten-seemann, and I also stated this on the mailing list. The (unofficial?) consensus seems to be 0, however. Should we be re-arguing the same issues over and over again?

I don't think we ever even came close to establishing consensus on this issue, we just had some discussions during a coffee break at one of the interims.

> The complication is that streams are module 4, so if 0 is invalid, so should stream 1, 2, and 3.

The stream directionality is defined mod 4. Starting at 1 is equally arbitrary as starting at 0.

**Comment by kazuho** [comment]
I disagree to making 0 "special", because I care about having consistency in design. I do not care what is "natural."

Packet numbers, Stream IDs, stream offsets, MAX_DATA offset, all those things currently start from zero. Why do we need to start some of them from one? Doing so would be an unnecessary complexity.

As @marten-seemann points out, the issue here is MAX_STREAM_ID frame not following the design pattern we use for transmitting blocked state that we have for offsets. The fix should be to follow the pattern.

> I agree that 0 should not be a stream, and that 0 should not be a packet number. It's really useful to have a sentinel value.

I understand that sentinel is useful. But it does not need to be zero. Because the "integers" we use in QUIC is uint62_t, you can use `int64_t` to represent the value internally, with -1 being the sentinel below and 2<sup>62</sup> being the one above.

**Comment by nibanks** [comment]
I also disagree that 0 should be special. I feel like we've definitely had this discussion more than twice...

**Comment by janaiyengar** [comment]
I suggest that we stick with @marten-seemann's original proposal for now, since it's a simple consistency fix. It also has the very useful property of not opening a can of worms.

**Comment by martinthomson** [comment]
It's just not possible to leave you folks alone for any time, is it?  I agree with @janaiyengar.
