### ISSUE TITLE
No SHOULD for stateless reset

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1858]
Currently:

> Endpoints SHOULD send a Stateless Reset ({{stateless-reset}}) for any packets
that cannot be attributed to an existing connection.

I think that we instead want to say:

> Endpoints can send a Stateless Reset ({{stateless-reset}}) for any packets that cannot be attributed to an existing connection.  A stateless reset allows a peer to more quickly identify when a connection becomes unusable.

I don't think that there is any interoperability gain from recommending stateless reset.  On the other hand, it has enough sharp edges to cut badly.

**Comment by ianswett** [comment]
SGTM.

**Comment by janaiyengar** [comment]
+1.
