### ISSUE TITLE
Minimum concurrent stream value

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#186]
The specification allows endpoints to specify the maximum number of concurrent streams (MSPC), but should not the spec provide for the minimum value of MSPC that all endpoints must support?  If the minimum is 1 (excluding "service" streams), it would be good for the spec to state so explicitly.

**Comment by martinthomson** [comment]
Hmm, 1 is a valid value.  The only value that doesn't make sense is 0.  HTTP/2 permitted a value of 0, temporarily, but we don't have any way to change settings yet (see #50).

**Comment by igorlord** [comment]
What you say: "1", do you include STREAM 1?  If so, what does it say about clients not able to start data streams?  It is useful?

If 1 does not include STREAM 1, does it mean we cannot be HTTP anymore?  (Needs a minimum of 3 streams, plus STREAM 1).

**Comment by martinthomson** [comment]
#421 killed this dead.  Mostly.  #456 would remove the only remaining wart, but that's not necessary.
