### ISSUE TITLE
Reason Phrases

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#187]
The inclusion of "Reason Phrase" is CONNECTION_CLOSE and GOAWAY frames seems unnecessary and its normative usage uncertain. There is already an error code field (and a robust discussion in #19 and #184 about its values).

"Reason Phrase" seems like optional textual debug information (in what language?). This is actually another case for a generalized DEBUG frame (see #65).

**Comment by martinthomson** [comment]
Not sure what your intent is with this issue.  HTTP/2 had an "extra stuff" field in GOAWAY, but not RST_STREAM.

I don't think that this suggests a new frame type; providing the information in-context is more likely to ensure that it is actionable.

**Comment by igorlord** [comment]
I am not hot on this issue and can live with it. HTTP/2 has "extra stuff". TCP does not.  QUIC straddles multiple layers, so from the transport perspective, this "extra stuff" is extra (and streams are now a transport feature). From HTTP perspective it can be justified.

**Comment by MikeBishop** [comment]
The spec describes this as "human-readable," so whatever the implementation wants to use for display.  Given than @igorlord has said he doesn't feel strongly about this, closing for now.  We can revisit in v2 if needed.
