### ISSUE TITLE
Multihoming support

### ISSUE THREAD

**Issue by DemiMarie** [quicwg/base-drafts#1871]
It would be very nice if QUIC supported multihoming.  That is one of SCTP’s biggest advantages.

**Comment by mikkelfj** [comment]
A lot of the infrastructure is in place but the feature it is out of scope for v1. It will likely be addressed in a follow up version.

**Comment by DemiMarie** [comment]
Makes sense.  Ideally DTLS would already have multihoming support, but you are correct that multihoming is not needed for a MVP.

**Comment by MikeBishop** [comment]
Multipath has been marked as a feature for a future version.
