### ISSUE TITLE
FTP integration

### ISSUE THREAD

**Issue by DemiMarie** [quicwg/base-drafts#1873]
FTP is normally used over TCP in a rather awkward manner that can cause problems in the presense of firewalls.  Running FTP over QUIC obviates that problem.

**Comment by MikeBishop** [comment]
Our charter says that we will define the HTTP mapping.  Another working group could define an FTP/QUIC mapping, or we could if there were sufficient WG interest following a recharter.  For now, closing as out-of-scope.
