### ISSUE TITLE
Formal analysis of the protocol

### ISSUE THREAD

**Issue by DemiMarie** [quicwg/base-drafts#1874]
It would be nice to have a formal proof that QUIC meets its security goals, and is free from deadlocks, denial of service vulnerabilities, and other bad behavior.

**Comment by MikeBishop** [comment]
It would be.  TLS has had such formal proofs, but there are potentially parts of the QUIC protocol that could be modeled as well.

That said, there are known deadlock situations, so I suspect such a proof would not be possible.  I'll leave to others to suggest where/whether such verification might be useful.

**Comment by ianswett** [comment]
My understanding is that we have text that prevents all known deadlocks.  Are there deadlocks you're aware of that are not preventable, particularly at the transport layer?  At the application layer, certainly one can create an application that causes a deadlock.

**Comment by martinthomson** [comment]
Tokyo conclusion: this is clearly desirable, and there is some interest from some people in doing the work.  People are generally supportive of the work and will happily contribute.  However, the working group won't spend additional time on this and won't let it block publication.
