### ISSUE TITLE
Heartbeats

### ISSUE THREAD

**Issue by DemiMarie** [quicwg/base-drafts#1876]
QUIC should periodically send packets through the channel, even if no data is being transferred.  This ensures that NATs keep the channel open, and allows dead peers to be recognized.

**Comment by MikeBishop** [comment]
PING packets exist to provide this functionality, though when/whether to use them is implementation-dependent, with guidance from the application layer.  The HTTP mapping [already recommends when to do this](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#idle-connections).
