### ISSUE TITLE
Smart quotes in static table

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1879]
Yep, a toolchain problem.  We probably need to work out how to quote the single-quotes here.  Hopefully \ is enough.

**Comment by dtikhonov** [comment]
Which entries are you looking at?

**Comment by martinthomson** [comment]
CSP: is `script-src ‘none’; object-src ‘none’; base-uri ‘none’` in the HTML

**Comment by dtikhonov** [comment]
Ooh, you're looking at the editor's copy!
