### ISSUE TITLE
Receiving WINDOW_UPDATE before the first STREAM frame should not reset connections

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#188]
> **9.1.1. idle**
All streams start in the “idle” state.
...
Receiving any frame other than STREAM or RST_STREAM on a stream in this state MUST be treated as a connection error (Section 11) of type YYYY.

Receiving a WINDOW_UPDATE frame (or probably any other frame) for a stream before the first STREAM frame for that stream due to packet reordering/loss should not be treated as a connection error (causing a connection reset).

**Comment by martinthomson** [comment]
I think that this is just a bug, do you agree @janaiyengar?
