### ISSUE TITLE
Permitted frame types

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#1880]
In section 9.2.3:

>The sender of a stream sends just three frame types that affect the state of a stream at either sender or receiver: STREAM (Section 7.20), STREAM_BLOCKED (Section 7.11), and RST_STREAM (Section 7.3).

However, MAX_STREAM_DATA can also affect the state of the stream.

**Comment by kazuho** [comment]
I think the text is correct because the subject here is "the sender of a stream."

MAX_STREAM_DATA is sent by "the receiver of a stream," which is discussed later in the section.

**Comment by MikeBishop** [comment]
Yep.

> The receiver of a stream sends MAX_STREAM_DATA (Section 7.7) and STOP_SENDING frames (Section 7.14).
