### ISSUE TITLE
Should we collapse APPLICATION_CLOSE and CONNECTION_CLOSE

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1881]
With a flag in the type byte, just like we did for ACK?

**Comment by ianswett** [comment]
Oh, yes please.  That would make the text much easier to read.

**Comment by MikeBishop** [comment]
Also known as #978....

**Comment by ianswett** [comment]
I think it's a bit different, but it is similar.

**Comment by LPardue** [comment]
Maybe we should hold this as *THE* killer feature for QUICv2.
