### ISSUE TITLE
X (*) does not actually indicate that x is variable length

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#191]
For instance, in S 5.1

Flags (8) 

And yet flags is mandatory. Are there any variable length fields that aren't of the 8/16/.. variety?

**Comment by martinthomson** [comment]
The '*' is a literal '*'.  See the diagram in Section 7.1.

**Comment by ekr** [comment]
Hmm.. Then the text is confusing. See PR# https://github.com/quicwg/base-drafts/pull/212
