### ISSUE TITLE
Section 4.2.17 references HTTP_UNEXPECTED_GOAWAY which doesn't exist

### ISSUE THREAD

**Issue by macoxms** [quicwg/base-drafts#1918]
HTTP_UNEXPECTED_GOAWAY is referenced in section 4.2.17 as the connection error to generate when getting an unexpected goaway, but this is not defined in section 8.

**Comment by mikkelfj** [comment]
otherwise it wouldn't be unexpected

**Comment by martinthomson** [comment]
Fixed in #1910.

**Comment by lnicco** [comment]
@martinthomson, was it really fixed ? 
can't find anything related to GOAWAY in #1910 commits

and the draft editor's copy still has the undefined reference

**Comment by martinthomson** [comment]
My bad, I assumed it was a bad section reference.
