### ISSUE TITLE
Stop pretending we are going to get to a 64-bit packet number

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#192]
S 5.2.1 contains a bunch of instructions for how to deal with packet number 2^64 but (for instance) the connection flow control window is 64-bits in absolute values, so given that we're mostly sending data, it seems improbable you will get to 2^64 packets.

**Comment by martinthomson** [comment]
Should we increase the length of the flow control limits to allow for >2^64 then?

**Comment by ekr** [comment]
That would also be fine.

**Comment by martinthomson** [comment]
#378 would bring this limit back into play.

**Comment by martinthomson** [comment]
Closes with #378.
