### ISSUE TITLE
Limiting the number of active connection ids

### ISSUE THREAD

**Issue by plakhera** [quicwg/base-drafts#1924]
It looks like the spec should provide some more guidelines around connection ID management by endpoints.

In summary, an endpoint should have mechanism in place to avoid allocating excessive resources if the  remote endpoint ends up sending too many NEW_CONNECTION_ID frames without necessarily retiring the old ones.

Essentially the question would be how to communicate these limits and what should be the behavior while enforcing these limits.

Communicating limits
##################
The transport parameter max_active_cid could be used to communicate and limit the other endpoint from generating too many NEW_CONNECTION_ID frames.
The draft could also define a default QUIC_DEFAULT_MAX_ACTIVE_CID maximum (32), which should be the hard limit only to be over-ridden by the presence of  max_active_cid in the transport parameter advertised by the peer.

Enforcement
##################
On the receipt of NEW_CONNECTION_ID, the endpoint should check if the number of active CIDs maintained by it for the remote has exceeded the limit or not.
If the frame makes it go over the limit, it MUST send back a CONNECTION_CLOSE frame with error code PROTOCOL_VIOLATION.

**Comment by martinthomson** [comment]
This was discussed at some length by the working group and we decided not to add any mechanisms to limit the number of connection IDs.

The protection mechanisms we rely on are that a recipient isn't obligated to remember *or retire* connection IDs if it doesn't intend to use them.  That limits the costs of too many connection IDs to the bandwidth cost (which can be wasted in many other ways anyway).

Note that you seem to have misunderstood the function of RETIRE_CONNECTION_ID.
