### ISSUE TITLE
Version negotiation potential amplification issue

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#195]
If a client sends a packet with an unknown version and a forged source address, it can use it to mount a reflection DoS onto some victim machine. This is only really useful if:

(a) the server has a big version list (so the packet is big)
(b) the server doesn't require the client to pad out to ~1MTU.

Is (b) documented somewhere? The spec suggests that I can send a short packet with a bogus version and the server MUST respond

**Comment by britram** [comment]
On (b) see also #136

**Comment by martinthomson** [comment]
Given the requirement for padding the client's packet, let's leave this to #136.
