### ISSUE TITLE
Sequence Number between CID length and CID is weird

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#1952]
Layout of the NEW_CONNECTION_ID frame is defined as below, placing Sequence Number between Length field (that designates the length of the Connection ID field) and the Connection ID field.

This is wired. We should move Sequence Number to front so that Length and Connection ID become adjacent fields.

```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|   Length (8)  |            Sequence Number (i)              ...
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                    Connection ID (32..144)                  ...
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
+                                                               +
|                                                               |
+                   Stateless Reset Token (128)                 +
|                                                               |
+                                                               +
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by martinthomson** [comment]
FWIW, it is weird.  I think that we can fix this, but it will be disruptive.  Do we want to use a varint length at the same time?  Or is that just more weird?

**Comment by ianswett** [comment]
Yes, we should move the length next to the CID, but I don't think there's any reason to move to a varint here.

**Comment by kazuho** [comment]
> Do we want to use a varint length at the same time? Or is that just more weird?

Considering the fact that CID length is expressed using a fixed number of bits in the long header, I think it would be more consistence to continue using a fixed-length encoding here.

**Comment by martinthomson** [comment]
Sold.
