### ISSUE TITLE
what is the default dependent stream of pushed streams

### ISSUE THREAD

**Issue by siyengar** [quicwg/base-drafts#1959]
in http/2 the default dependency of the pushed stream was it's associated stream. However in h3 we now have push ids and not associated streams. Should we have a default priority here?

**Comment by martinthomson** [comment]
Yes, PUSH_PROMISE can be used, but which PUSH_PROMISE?

The pushed response is what would be prioritized, and multiple requests can point at the same pushed response.

**Comment by LPardue** [comment]
So I always look at Priortisation from the server's perspective - if it wants to push a thing, how should it assign resources to that in keeping with how the client already expressed it's priority preferences.

So in other words, what I said is then: the pushed pseudo-request assumes it's parent request's priority by default. A client could then repriortise that particular pseudo-request by using the PRIORITY frame with the Push ID.

Logically, the reprioritisation would point the dependency at some other request (Stream ID), a different Push promise ID (reprioritising to self means what??), or some placeholder ID.

Now, here's where I get told all my assumption have been wrong :)

**Comment by martinthomson** [comment]
I can put the same PUSH_PROMISE (promising the same push) on two request streams.  Which of those does the pushed stream depend on?

**Comment by LPardue** [comment]
Good point. The last one?

What about assuming no default priority as a solution.
