### ISSUE TITLE
Don't resend *all* packets in version negotiation

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#196]
"
   When the client receives a Version Negotiation packet from the
   server, it should select an acceptable protocol version.  If the
   server lists an acceptable version, the client selects that version
   and resends all packets using that version.  The resent packets MUST
   use new packet numbers.  These packets MUST continue to have the
   VERSION flag set and MUST include the new negotiated protocol
   version."

There might be some packets which should not be re-sent if, for instance, they are not relevant for this version of QUIC

**Comment by ianswett** [comment]
Also, given they have new packet numbers and the framing of a version may change, we should talk about retransmitting frames, not packets in this section.

**Comment by martinthomson** [comment]
I think that this instead needs to say something more generic: start over.  Marking this as editorial (let me know if you disagree).

**Comment by ianswett** [comment]
Agreed, start over is the correct answer.

**Comment by martinthomson** [comment]
The new text is better:

> If the server lists an acceptable version, the client selects that version and reattempts to create a connection using that version.
