### ISSUE TITLE
Spurious RTO detection

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#1966]
The spurious RTO detection calls an RTO spurious if any unacked packets sent prior to the RTO are acked after the RTO. The implication here is that _any_ packet that was received but not acked can cause the RTO to be labeled spurious, even if there were more packets that were in fact lost.

This is not always right.  Consider the following example:
- Packets 5, 6, 7 are sent
- Packet 5 is received, but 6 and 7 are dropped
- Ack of 5 is dropped
- TLPs (packets 8 and 9) are sent and dropped
- RTO (packet 10) is sent and received
- ACK acks 10 and 5
- Since 5 was sent prior to RTO, RTO is marked spurious.

A crisp definition of spurious RTO may be useful to continue. Here's what I think is sensible: A spurious RTO is an unnecessary RTO. If the RTO timer had not gone off, things would have been fine.

Based on this definition, clearly the RTO was necessary in the example, and therefore not spurious.

We need to change the mechanism for detecting spurious RTOs, and I'll propose the following. An RTO is spurious if an ack is received after the RTO fires that acks only packets sent prior to the RTO. In other words, RTO is spurious if ack is received after the RTO, and `largest_newly_acked <= largest_sent_before_rto` (instead of `smallest_newly_acked > largest_sent_before_rto`, as the draft currently states).

**Comment by janaiyengar** [comment]
@ianswett : #1774 does not change the semantics substantively of what was in the draft. The intent was always to declare spurious RTO if (packet prior to RTO was newly acked). I'm proposing that we change that to (no packet sent after RTO was newly acked).

**Comment by ianswett** [comment]
In light of #2293, I think this is OBE?

**Comment by janaiyengar** [comment]
Yes, this is OBE. Closing.
