### ISSUE TITLE
Remove kUsingTimeLossDetection from Recovery draft

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#1969]
@pravb Indicated declaring a packet lost if the reordering threshold(ie: 3) OR the time threshold has been reached, then a packet is declared lost.

I'd like to remove early retransmit entirely, because it's a bit complex and having QUIC operating in two alternate modes, but indicating both can be enabled at once in the text is very confusing.

**Comment by ianswett** [comment]
Thanks Matt, is there evidence the current RACK algorithm is a good approach for mixing packet and time reordering thresholds dynamically?

I believe there were few experiments that showed starting with time-only caused regressions on flows with little to no reordering, particularly in low RTT environments where the alarm granularity is comparable to the RTT.

If we think there's enough evidence the current RACK algorithm is close to optimal, I'm happy to put that in, but given RACK is not yet an RFC, I was under the impression it was still evolving?

**Comment by ianswett** [comment]
Based on my understanding of modern networking, I'd expect fraction of packets reordered to increase over time, even if the distance in time is quite small(ie: ~1ms).

And that narrative would argue a default reordering threshold of 1 dupack, which TCP has never recommended to my knowledge.

Good point that this seems like a larger question for both RACK and QUIC.

**Comment by maolson-msft** [comment]
Opened issue:
#1986

**Comment by janaiyengar** [comment]
@ianswett : I'd argue against removing ER, though I'm in favor of removing time-based-loss-detection since that's basically a separable boolean in the code that can be added once someone has more experience with it. ER requires at least one ack and uses a timer, and FR uses packet thresholds.

**Comment by ianswett** [comment]
I don't think removing time threshold loss detection is the right direction, both based on personal experience and on talking with Praveen and Yuchung about RACK.  Removing ER seems like a better long term direction.  Time threshold loss detection still requires a larger packet to be declared acknowledged to declare a smaller one lost.
