### ISSUE TITLE
Where does the "quic " HKDF label apply?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1971]
It turns out that this isn't very clear.  Implementations and drafts don't match.

We might like to reconsider the use of a new prefix here.

**Comment by mikkelfj** [comment]
Could we also get rid of the space in the label or replace it with a hyphen or something? Spaces might get lost or becomes tabs etc.

**Comment by marten-seemann** [comment]
I disagree that there's a problem with the space. As far as I'm aware of, it never created a problem during interop.

**Comment by kazuho** [comment]
@martinthomson Oh. Are you suggesting that the prefix used by the TLS key schedule needs to remain as "tls13 "?

To me, it seems that we discussed the issue at https://github.com/quicwg/base-drafts/pull/1377#pullrequestreview-124279091 but did not come to a clear conclusion.

**Comment by martinthomson** [comment]
Yes, I know that we discussed this.  However, the conclusion was not clear, and the resulting confusion needs to be addressed somehow.  I'm suggesting that this re-labeling isn't really needed, and has caused harm.

**Comment by martinthomson** [comment]
Oh, and the space thing is a done deal sadly.  We can't un-ship TLS 1.3.  We can only really control what QUIC does.

**Comment by mikkelfj** [comment]
Well, I think better safe than sorry. Using a dedicated QUIC label will close any "don't do that" attack vectors.

**Comment by martinthomson** [comment]
My point here is that it won't because it can't.

**Comment by kazuho** [comment]
@martinthomson Clarification question: are you suggesting to drop *all* use of the "quic " prefix (to revert to "tls13 "), including key-schedule, traffic key derivation, key update, ...

**Comment by martinthomson** [comment]
Yes, that's the implication.
