### ISSUE TITLE
Define server behavior for initial packets with < 8 byte DCID

### ISSUE THREAD

**Issue by gjnance** [quicwg/base-drafts#1981]
The spec states that initial packets sent by clients which have not previously received a Retry packet must populate the Destination Connection ID field with an unpredictable value, and that the value MUST be at least 8 bytes in length.

However, the spec doesn’t say what a server receiving a packet from a client which violates this condition should do. There are already discrepancies in various implementations that a change to the spec could help to remedy.

**Comment by marten-seemann** [comment]
Isn't this covered by 5.2.2?

> If the packet is an Initial packet fully conforming with the specification, the server proceeds with the handshake (Section 7). This commits the server to the version that the client selected.
> [...]
> Servers MUST drop incoming packets under all other circumstances.

**Comment by martinthomson** [comment]
Thanks for finding that one @marten-seemann .

**Comment by gjnance** [comment]
Thanks, Mart[ie]n[!duke]
