### ISSUE TITLE
Loss recovery draft section 4.3.1.1 clarification

### ISSUE THREAD

**Issue by nekiz** [quicwg/base-drafts#1983]
Section 4.3.1.1 of draft 16 says:
A Retry or Version Negotiation packet causes a client to send another
   Initial packet, effectively restarting the connection process.

Either packet indicates that the Initial was received but not
   processed.  Neither packet can be treated as an acknowledgment for
   the Initial, but they MAY be used to improve the RTT estimate.

Should we clear handshake_count when an Retry or Version Negotiation packet is received after Initial is sent (maybe multiple times)? Otherwise, the new Initial could be delayed extra if Initial is lost and needs retransmission.

**Comment by ianswett** [comment]
My mental model is that Retry or VN basically restart the connection, so I think it makes sense to set handshake_count back to 0.
