### ISSUE TITLE
Why are reason phrases potentially 65k long?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#199]
There is a two byte length field. Surely a 256-byte reason phrase is long enough.

Also, are these in ASCII? UTF-8?

**Comment by igorlord** [comment]
There is a related issue #187.

**Comment by martinthomson** [comment]
256 octets probably won't carry a stack trace :)

This is entirely proprietary, but we could recommend that text (if it is text) be UTF-8.

**Comment by marten-seemann** [comment]
Since frames cannot be split (except for STREAM frames), there's no way to send more than around 1340 bytes of reason phrase anyway in the general case (IPv6 doesn't support packet fragmentation).
