### ISSUE TITLE
HTTP2 connection preface clarification

### ISSUE THREAD

**Issue by abraud** [quicwg/base-drafts#1995]
Greetings,

RFC7540 Section 3.5 states that a client is to send a preface prior sending its SETTINGS frames.

QUIC HTTP draft states : "After the QUIC connection is
   established, a SETTINGS frame (Section 4.2.5) MUST be sent by each
   endpoint as the initial frame of their respective HTTP control stream
   (see Section 3.2.1)."

So should a preface be sent when doing HTTP2 over QUIC.

**Comment by martinthomson** [comment]
The preface is unnecessary.  HTTP/QUIC != HTTP/2.
