### ISSUE TITLE
bytes_in_flight update issue

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#2009]
I think the following issue exists in the pseudo code:

For a new ACK block, `OnAckReceived()` first calls `OnPacketAcked()`, where `OnPacketAckedCC()` reduces `bytes_in_flight` by the sizes of whichever packets were ACKed.

Then,`OnAckReceived()` calls `DetectLostPackets()`,  which reduces `bytes_in_flight` for every packet that it determines to be lost. That can cause `bytes_in_flight` to become zero.

Next, `SetLossDetectionTimer()` is called. The first thing that does is to cancel the `loss_detection_timer` when `bytes_in_flight` is zero.

So when and how are the packets that were declared lost retransmitted?

**Comment by janaiyengar** [comment]
@larseggert : That is correct behavior because even though packets have been deemed lost, nothing has been resent yet. bytes_in_flight == 0 means that there's nothing to start a timer for. When the lost data is retransmitted in new packets, OnPacketSent gets called, which sets the timer.
