### ISSUE TITLE
HTTP: Why are we defining CONNECT?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#202]
The primary use case for conventional CONNECT proxies is firewall traversal. Is there a big use case for QUIC proxies which we then need to traverse?

**Comment by martinthomson** [comment]
Is this a suggestion that we don't provide CONNECT?  We had a big discussion about this in HTTP/2 that had all the same basic constraints.  We decided to define it then.

**Comment by ekr** [comment]
Yes, it's a suggestion to that effect. I wasn't in the H2 discussion, but I guess I would say that perhaps we now have experience with defining CONNECT for h2. Has that worked out well? Does anyone do CONNECT/h2?

**Comment by martinthomson** [comment]
CONNECT/h2 is implemented, but I don't know about usage rates.

**Comment by mcmanus** [comment]
people definitely do CONNECT over h2.. sometimes yielding h2 in h2.

**Comment by MikeBishop** [comment]
My question was actually the opposite -- CONNECT gives you a TCP connection through the proxy.  In a hypothetical speaking-QUIC-to-proxy world, would we want an alternative method that let you get a UDP/QUIC connection through the proxy?

**Comment by tatsuhiro-t** [comment]
The use case of CONNECT method in h2 is HTTP/2 proxy. Tunneling request (stream?) to the upstream server.  h2 proxy is supported by Chroimium and Firefox.  We have some users doing this.

**Comment by mnot** [comment]
Dup of #95
