### ISSUE TITLE
Congestion window on new path

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2035]
PR #2023 covers reducing or pacing after an idle period to limit bursts. But path migration could also flood a new connection path even if there is no idle period, and this is not covered by any text that I am aware of.

**Comment by janaiyengar** [comment]
This is covered in [Section 9.4 of the transport draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.9.4).

**Comment by mikkelfj** [comment]
yes, I missed that, sorry.
