### ISSUE TITLE
Rename QPACK to HPACK3?

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#2041]
Since we renamed HTTP/QUIC to HTTP/3, perhaps we should rename QPACK to avoid its linkage with QUIC. :smiling_imp: 

Edit: the skip in version number is intentional

**Comment by mikkelfj** [comment]
Wouldn't HPACK/3, as opposed to HPACK3, be the more correct term?

**Comment by kazuho** [comment]
I am not sure if H of HPACK stands for HTTP. I had always assumed that it is the first letter of “header.” It is also my understanding that QPACK tries not to be HTTP-specific.

Assuming that they are correct, I think keeping the name QPACK might be better, reflecting the fact that it is a compression algorithm designed for QUIC.

Just my two cents.

**Comment by bagder** [comment]
I agree with @kazuho here. It isn't really a version three of HPACK so I think implying that in name would be unfortunate.

**Comment by dtikhonov** [comment]
I prefer to keep the QPACK name.

If we were to rename it, HPACK 2, not 3, is more appropriate (and forget the slash).

**Comment by kazuho** [comment]
My view is that it’s only the static table that’s HTTP-specific.

And we do not need a TP for having different static tables for each protocol; the use of protocol is negotiated by using ALPN, and static table selection can naturally depend on that.
