### ISSUE TITLE
Expand on "in-flight"

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2047]
@janaiyengar says "It might be worth articulating this point about the congestion controller in the recovery draft. We might want to have a discussion about inflight bytes there and about when to consider something in flight and when to remove something from inflight."

I've proposed some text in #2045 related to this that probably needs to be merged into this.

**Comment by ianswett** [comment]
@martinthomson and I believe this is now fixed with #2045 and various follow-ups.
