### ISSUE TITLE
Mismatch between version negotiation in TLS layer and in QUIC layer

### ISSUE THREAD

**Issue by vasilvv** [quicwg/base-drafts#206]
My current understanding of the documents is that on the QUIC layer, the client picks the version and the server offers a list of versions it support.  On the TLS layer ALPN handshake, client advertises its versions and server picks one.  This is not guaranteed to produce the same version in absence of MITMs, since client and server might have different version preferences.

I suggest that we change the TLS layer negotiation into "QUIC client says its version, and server says its supported versions", similar to #97 .  That way, we effectively repeat the version negotiation information used on transport layer in the handshake, allowing the peers to compare the authenticated information from the handshake with the one they used in transport, and tear down the connection in case those do not match.

**Comment by martinthomson** [comment]
This is already what we're proposing to do in #122 (which builds on #99).  We don't have any disagreement about this aspect of the pull request, though other aspects remain contentious, which have kept it from being merged.
