### ISSUE TITLE
Explain or reference key acronyms in recovery (RTT, RTO, SRTT, ...)

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2079]
In the recovery draft, RTT is briefly spelled out in section 5 but is used in several earlier sections. SRTT  and PTO are not explained at all, it seems. TLP is spelled out. RTO has a section of its own but it referenced before that.

The recovery doc cannot be a tutorial on transmission theory, but it would be helpful to list the key acronyms and possibly reference an RFC with more details. There are already sections summarising key variables in pseudocode. There are references at the end, but the reader would have to go through them all.

**Comment by janaiyengar** [comment]
Yes, thanks for the note. I'm planning to do a cleanup of that doc soon.

**Comment by ianswett** [comment]
I fixed defined RTT earlier in #2362.
