### ISSUE TITLE
Why ignore MAX_STREAM_DATA or MAX_DATA that don't increase the flow control limits

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2082]
S 4.1. says:

```
A receiver can advertise a larger offset by sending MAX_STREAM_DATA or MAX_DATA
frames at any time during the connection.  A receiver cannot renege on an
advertisement however.  That is, once a receiver advertises an offset,
advertising a smaller offset has no effect.  A sender MUST therefore ignore any
MAX_STREAM_DATA or MAX_DATA frames that do not increase flow control limits.
```

It seems like it would be more helpful if implementations were to remember the PN of the last advertisement and generate an error in this case. I get that this would be more work, but why is this prohibited?

**Comment by marten-seemann** [comment]
We discussed this in #1612 and decided to not prohibit this.

**Comment by mikkelfj** [comment]
It would be wasteful to track all that state for very little benefit. Reordering us likely, invalid max sequencing less so. For future multipath it would get complicated.

A peer could also schedule packets out of order due to concurrent pipelines, so checking PN could be damaging.

**Comment by MikeBishop** [comment]
Also because a naive implementation that just blindly retransmitted frames from lost packets would then be invalid, rather than simply unoptimized.  While that behavior isn't something we want to encourage, it's not clear that we want to outlaw it, either.

**Comment by ekr** [comment]
I don't find this persuasive, but as I said, I recognize I'm in the rough. Regardless, if that's the behavior we want, the text needs some rework

**Comment by kazuho** [comment]
> It's consistent with our decision elsewhere that frames which are valid when sent remain valid for the duration of the connection no matter how delayed (though they might get ignored as irrelevant).

FWIW, I am not sure if all the frames have such property; retransmitting an ACK frame is not a good idea because you would have an incorrect value in the ack delay field...

However I do agree that retransmission of MAX_* frames should be allowed. Or put it another way, I do not think that the endpoints should be mandated to detect rollback of max values in the succeeding frames and call that an error. It's something not easy to implement when reordering is involved.

**Comment by janaiyengar** [comment]
@ekr: Is the text you've proposed above your suggested rewording? That's not enough, because it doesn't capture what the sender needs to do when it receives a frame out of order. I'm happy to put together a PR but I'm not sure what you are after.

**Comment by MikeBishop** [comment]
I think the requirement on the sender is still correct.  Regardless of where it occurs (packet scheduling, retransmission, or wire), this is fundamentally a statement about reordering tolerance on the recipient of MAX(_STREAM)?_DATA, which is the sender of data.

**Comment by ekr** [comment]
@janaiyengar that was intended as an addition, I agree you still need to say ignore.
