### ISSUE TITLE
Discuss requirement that connection IDs not be correlatable

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2084]
S 5.1. says

```
Connection IDs MUST NOT contain any information that can be used by to correlate
them with other connection IDs for the same connection.  As a trivial example,
this means the same connection ID MUST NOT be issued more than once on the same
connection.
```

At minimum this needs to be restricted to endpoints and other elements associated with them (like load balancers) because they need to be able to correlate connection IDs. But this is also a very strong condition, and in some cases will basically mandate encryption.

**Comment by mikkelfj** [comment]
It should contain "by an external observer". I believe there is other text mentioning coordination with load balancers when constructing CID's. It is a strong condition - without it all other work on preventing linkage is more or less useless.

**Comment by DavidSchinazi** [comment]
It feels strange to me that this is an RFC8174 MUST NOT, as it's unclear how to enforce it. That said, I agree that this text should be constrained to external observers - and clearly define who that is.

**Comment by kazuho** [comment]
Maybe change to “Connection IDs MUST NOT _expose_”?

**Comment by martinthomson** [comment]
Tokyo conclusion: describe what the attack is and explain that anti-correlation text exists as an answer to this.

**Comment by larseggert** [comment]
Discussed in London, @ekr to resume work

**Comment by mnot** [comment]
@ekr how is this progressing?

**Comment by martinduke** [comment]
I believe this is an editorial issue, not design. We all know what we mean: it can encode information by use for itself and trusted intermediaries, but definitely is not correlatable. I agree that MUST is a little tricky unless we are mandating either true encryption or true randomness, which is a discussion I was hoping to defer until QUIC-LB is adopted.
