### ISSUE TITLE
Require peers to replace retired connection IDs

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2085]
```An endpoint maintains a set of connection IDs received from its peer, any of
which it can use when sending packets.  When the endpoint wishes to remove a
connection ID from use, it sends a RETIRE_CONNECTION_ID frame to its peer,
indicating that the peer might bring a new connection ID into circulation using
the NEW_CONNECTION_ID frame.
```

This text is very weak. Don't we expect peers to bring new connection IDs into circulation when they receive RETIRE_CID? Shouldn't we say so.

**Comment by erickinnear** [comment]
Yeah, I thought at one point that it was a SHOULD?

**Comment by ianswett** [comment]
SHOULD seems reasonable, with the usual caveats that there may be limits on how many CIDs a peer can generate.

**Comment by MikeBishop** [comment]
In general, while a peer might not give you as many as you want (#1998), they SHOULD be able to replace as many as they've given you.  And if they don't and you run out of CIDs, close the connection.

**Comment by MikeBishop** [comment]
Sorry -- didn't mean to close, just comment.
