### ISSUE TITLE
"MUST drop zero-length CIDs which match multiple connections" should never happen

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2086]
```
If the Destination Connection ID is zero length and the packet matches the
address/port tuple of a connection where the host did not require connection
IDs, QUIC processes the packet as part of that connection. Endpoints MUST drop
packets with zero-length Destination Connection ID fields if they do not
correspond to a single connection.
```

How could this happen? The recipient knows if a given tuple is unique, so it shouldn't issue zero-length DCIDs for that tuple.

**Comment by mikkelfj** [comment]
Yeah, it is more like recipients MUST not issue 0-length CID's in that case. And MUST drop non-issued CID's.

**Comment by martinthomson** [comment]
I remember why was added.  If you had one connection on those addresses, time passes and a NAT rebinding moves another connection to that same path, then you get problems.  That a nonsensical situation and better addressed as suggested.
