### ISSUE TITLE
Fix stream identifier size

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#209]
The doc defines stream identifiers as "variable-length".  But are they really?

**Comment by martinthomson** [comment]
To be clear, it might be encoded using a variable-length encoding, but the actual value is fixed size.  This refers to the following text in the description of the STREAM frame: "Stream ID: A variable-sized unsigned ID unique to this stream, whose size is determined by the `SS` bits in the type byte."

**Comment by MikeBishop** [comment]
I think this is long-since fixed. 

> Streams are identified by an unsigned 62-bit integer, referred to as the Stream
ID.

Everywhere else, it talks about a variable-length encoding of the Stream ID.
