### ISSUE TITLE
High BDP and adapted congestion control

### ISSUE THREAD

**Issue by NicoKos** [quicwg/base-drafts#2091]
In the context of high BDP networks, inadequate congestion control and its initial parameterization can result in very low QoE. 
As shown at IETF103, the web page download time can double with Google-QUIC as opposed to using tuned TCP proxy. 
We should let the QUIC server know that we are on a high BDP network. 
One solution would be to set the IW to a higher value (along with pacing) but other adaptations could be relevant. 
This issue could be relevant to other networks (data-centers, DOCSIS).

**Comment by ianswett** [comment]
I agree this is a problem, but I'm very unsure what the WG can do about it.  Can you provide some specific suggestions?

**Comment by NicoKos** [comment]
I wonder whether we should ask for specific parameter (such as the IW value - and above a certain threshold pacing msut be considered) or a more generic parameter saying 'you are on a high BDP network'. 
Those could be transport parameters, such as discussed in https://tools.ietf.org/html/draft-ietf-quic-transport-16#section-22.1

**Comment by janaiyengar** [comment]
At the moment, endpoints are free to choose an alternate congestion controller. Let's open this issue again when there is a specific controller with a specific transport parameter that is needed for it.
