### ISSUE TITLE
More generic keep-alive text

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2092]
In #2068, the direction of the discussion is that PING frames are an application-layer concept that won't necessarily be directly under the application-layer's control.  The HTTP draft currently says:
> HTTP clients are expected to use QUIC PING frames to keep connections open while there are responses outstanding for requests or server pushes. If the client is not expecting a response from the server, allowing an idle connection to time out is preferred over expending effort maintaining a connection that might not be needed. A gateway MAY use PING to maintain connections in anticipation of need rather than incur the latency cost of connection establishment to servers. Servers SHOULD NOT use PING frames to keep a connection open.

This should be reworded in terms of requesting the transport stack to keep the connection from idling out, rather than directly discussing PING frames.

**Comment by janaiyengar** [comment]
Gah! Not more types of PING please!

**Comment by LPardue** [comment]
KEEPTHECARRUNNING frame (ID=0xAF)
