### ISSUE TITLE
QUIC extensibility

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#210]
General strategy for QUIC extensibility, including:

- Version negotiation 
- Options negotiation

The document needs to define a general strategy for this. I see there are other related issues, but none that quite covers the general issue.

**Comment by martinthomson** [comment]
#122 gets started on this, most of that.  We don't have a lot of supporting text though.

**Comment by martinthomson** [comment]
This might also cover #58.

**Comment by MikeBishop** [comment]
Version negotiation is sufficiently covered by the existing draft.  Parameter extensibility is not currently needed; per scoping discussion, I think we can move this to v2.

**Comment by MikeBishop** [comment]
Closed by #1473, no?
