### ISSUE TITLE
Avoid creating QPACK codec streams when unnecessary

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2100]
Now that #2038 is being merged, we have the possibility to avoid creating unnecessary encoder / decoder streams.

Avoiding creation is beneficial for memory-constrained devices, because they can configure the QUIC transport stack to handle at most one unidirectional stream (in each direction) to support HTTP/3 _if_ the QPACK state forbids 1) peer's creation of the encoder stream when endpoint's `SETTINGS_HEADER_TABLE_SIZE:` is zero, and 2) peer's creation of decoder stream is delayed until the endpoint's creation of the encoder stream.

With the proposed changes, a memory constrained HTTP/3 stack that sends`SETTINGS_HEADER_TABLE_SIZE` of zero and never opens an encoder stream can be certain that the peer never opens an encoder stream or a decoder stream.

Note that it has minimal impact to existing implementations; regarding creation of the encoder stream, #2038 states that the stream cannot be used until SETTINGS is being received. It is a clarification (or a requirement) that "use" includes the creation of the stream. The situation is the same for the decoder stream.

Pull request filed as #2090.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; do not require creating the streams, but creating them is not forbidden even if the setting prevents their use.

**Comment by mikkelfj** [comment]
And make sure that constrained devices can trivially detect and reset non-forbidden forbidden streams instead of assigning state.

**Comment by ghedo** [comment]
I made #2529 to try and put into writing what was discussed in Tokyo since there hasn't been any actiity in a while. Incidentally we run into the problem of allowing endpoints to create all QPACK control streams while interop'ing between quant and quiche HTTP/3.

**Comment by afrind** [comment]
Discussed and clarified in London.

1. HTTP MUST set initial_max_uni_streams to at least 3
2. HTTP does not have to keep granting more credit if the peer burns the stream credits on grease/push/extensions.
3. Peers SHOULD create control, qpack encoder and decoder as their first 3 streams if they plan to use them, since there's no guarantee of ever getting more credit.

**Comment by ghedo** [comment]
Created #2762 in addition to the existing PR #2529 to also update the -http requirements as per the discussion in London.
