### ISSUE TITLE
Guidelines for Retransmitting Lost Data

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2103]
The recovery draft is oddly silent on when to send data that has actually been marked as lost. I'm not sure if this is constructive ambiguity or just an oversight.

Consider the following case with 1 stream, which is an entirely typical burst error scenario.
1. Segments A through J are sent in packets 1-10. There is no other data.
2. TLP timeout, send A in pkt 11.
3. TLP timeout, send pkt 12. **Do I send segment A or B** -- A is inflight twice so B is more likely to be new to the receiver, though if A is truly lost we won't make progress.
4. RTO timeout, send pkts 13 and 14. Similar to (3), **do we send C & D, or A & B**?
5. Receive ack of 14. Packets 1-12 are declared lost. Whatever was in pkt 13 is therefore the only outstanding data, and only the contents of pkt 14 are deleted from the queue. **Should I include the payload of pkt 13 in the outgoing queue,** or wait for pkt 13 to be declared lost?

Put another way, in the recovery draft we often prioritize segments that have no copies in-flight. Does that extend to prioritizing segments that are in-flight once over those that are out there twice? Does declaring a packet lost mean we should simply retx its segments if unacked, or do we consider that there are still outstanding copies?

**Comment by janaiyengar** [comment]
Said differently, the draft says _when_ a sender can send, but not _what_.

There are rules of thumb we used to have, but I would argue now that this doesn't require strong recommendations besides that the sender decide based on local priorities. That said, I think it'd be good to have a paragraph that discusses this point more explicitly and the tradeoffs, so I'll leave this issue open.  It is not an oversight that we don't say _what_ should be transmitted, but there should be text clarifying it.

**Comment by ianswett** [comment]
In the "Loss Detection" section, we reference the transport draft:

"If a packet is lost, the QUIC transport needs to recover from that loss, such as by retransmitting the data, sending an updated frame, or abandoning the frame. For more information, see Section 13.2 of {{QUIC-TRANSPORT}}."

We could certainly add some non-normative text about the considerations, particularly in regards to things like TLP, where sending the same payload in two consecutive TLPs seems a bit unwise, unless that's all that's outstanding.

**Comment by ianswett** [comment]
The current text, which was written after this issue was filed is:
"Probe packets sent on a PTO MUST be ack-eliciting. A probe packet SHOULD carry new data when possible. A probe packet MAY carry retransmitted unacknowledged data when new data is unavailable, when flow control does not permit new data to be sent, or to opportunistically reduce loss recovery delay. Implementations MAY use alternate strategies for determining the content of probe packets, including sending new or retransmitted data based on the application's priorities."

**Comment by ianswett** [comment]
Sure, let's discuss in person.
