### ISSUE TITLE
Largest Reference isn't the right concept

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2110]
Counting by reference implies something about the indexing system that is unnecessary.

For instance, with one entry in the table that is used, the current system insists on us signaling a Largest Reference of 1.  But most people would treat that entry as being at an index of 0.

The thing that we're sending is the number of inserts.  Describing the field in those terms clarifies things considerably.

**Comment by afrind** [comment]
Some of the mismatch here may come from QPACK inheriting its roots from HPACK via QCRAM.  HPACK indexes from 1, and so did QPACK for a while.  But when we changed QPACK to index from 0 then Largest Reference became an off-by-one misnomer.

**Comment by bencebeky** [comment]
QPACK is currently inconsistent in that static table indexing is explicitly defined to be zero-based, while dynamic table absolute indexing is explicitly one-based, see
https://quicwg.org/base-drafts/draft-ietf-quic-qpack.html#table-static
https://quicwg.org/base-drafts/draft-ietf-quic-qpack.html#indexing

I enthusiastically support PR #2111 and also changing absolute indexing to zero-based.

**Comment by dtikhonov** [comment]
@bencebeky writes:
> I enthusiastically support [...] changing absolute indexing to zero-based.

This had been discussed before.  The consensus was to leave it one-based.

**Comment by csillagasz** [comment]
> @bencebeky writes:
> 
> > I enthusiastically support [...] changing absolute indexing to zero-based.
> 
> This had been discussed before. The consensus was to leave it one-based.

My impression is that this consensus was driven by the artifical constraint of Largest Reference having to be able to match the absolute index while also having a dedicated value (of zero) for no dynamic reference.  Martin's proposed change from Largest Reference to Required Insert Count removes this rather contrived constraint and allows the more natural indexing scheme of zero based indexing that matches static table indexing, the majority of developers' mental model, and the majority of implementations' innards.

**Comment by bencebeky** [comment]
> @bencebeky writes:
> 
> > I enthusiastically support [...] changing absolute indexing to zero-based.
> 
> This had been discussed before. The consensus was to leave it one-based.

My impression is that this consensus was driven by the artifical constraint of Largest Reference having to be able to match the absolute index while also having a dedicated value (of zero) for no dynamic reference. Martin's proposed change from Largest Reference to Required Insert Count removes this rather contrived constraint and allows the more natural indexing scheme of zero based indexing that matches static table indexing, the majority of developers' mental model, and the majority of implementations' innards.

**Comment by dtikhonov** [comment]
I think the decision to keep dynamic index starting at 1 is because the static table also started at 1 when the initial proposal was made in August of 2018.

**Comment by martinthomson** [comment]
Whatever the reason (I forget why that was, but it was probably due to some special-casing of 0), that was a long time ago.

**Comment by MikeBishop** [comment]
I eliminated most one-based indexing in the giant PR that rewrote the instruction space; Absolute Indices remained 1-based because we needed the sentinel value of 0 in Largest Reference to signal no references.  In that PR, it was noted that the static table instruction indexed from zero, but the static table at the time had no entry in the zeroth position.

I'm content with #2111 as fixing that gap and enabling it to become consistent.
