### ISSUE TITLE
Limits on PATH_CHALLENGE/RESPONSE rate

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2129]
```On receiving a PATH_CHALLENGE frame, an endpoint MUST respond immediately by
echoing the data contained in the PATH_CHALLENGE frame in a PATH_RESPONSE frame.
However, because a PATH_CHALLENGE might be sent from a spoofed address, an
endpoint MUST limit the rate at which it sends PATH_RESPONSE frames and MAY
silently discard PATH_CHALLENGE frames that would cause it to respond at a
higher rate.
```

It's pretty hard to understand what the normative force of this is, given that it doesn't explain what the limit is. I think there's actually a simple rule we should propose, which is one PATH_CHALLENGE frame per packet (with others to be ignored). Given that we require duplicate suppression at the packet level, that will have an amplification factor of 1:1, which you can get by a variety of other mechanisms.

**Comment by martinthomson** [comment]
The relevant existing guideline is the 3x limit we have on handshake amplification.  Given that CHALLENGE/RESPONSE doesn't inherently include any amplification other than what might result from different connection ID lengths on packets, I don't think that we need to do much special.  That is, the text in 9.3.1 is fine, even if the limits are different.

>  Until a peer’s address is deemed valid, an endpoint MUST limit the rate at which it sends data to this address. The endpoint MUST NOT send more than a minimum congestion window’s worth of data per estimated round-trip time (kMinimumWindow, as defined in [QUIC-RECOVERY]).

I'm OK with striking everything from "However" onward here.
