### ISSUE TITLE
Guidance on path retransmission timer

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2130]
```
Endpoints SHOULD abandon path validation based on a timer. When setting this
timer, implementations are cautioned that the new path could have a longer
round-trip time than the original.  A value of three times the current
Retransmittion Timeout (RTO) as defined in {{QUIC-RECOVERY}} is RECOMMENDED.
```

We should probably give some guidance about the size of this timer, maybe matching whatever guidance we give for Initial retransmit

**Comment by martinthomson** [comment]
@janaiyengar, the RTO was chosen carefully - as long as it has a minimum it is still probably the right answer.  If we assume that the RTT on the old path is approximately correct, and that the minimum RTO will prevent the worst problems resulting from migration to a longer path, I think that this is OK.

**Comment by ekr** [comment]
@janaiyengar I dont't necessarily have problem with 3RTO here, but I don't see it in the doc. Can you point me to where it is?

With that said, it seems like the timeout for path validation actually ought to be quite aggressive because given the current migration design, it's actually a sensitive security parameter. Consider the case where you have an on-path attacker and A and B are quiescent. A sends B a packet containing data that doesn't need a reply (e.g., part of an HTTP request). At this point, the on-path attacker takes B's ACK and then forwards it to A with a different source address. From this point forward, A is sending to the wrong place for the duration of this timer. That's a pretty serious attack.

**Comment by martinthomson** [comment]
@ekr
> I dont't necessarily have problem with 3RTO here, but I don't see it in the doc. Can you point me to where it is?

You quoted the text that says 3RTO.

Please take a look at https://github.com/quicwg/base-drafts/pull/2238/files#diff-db016291106766877c4921a79f8596e0 which amends this value.  I think that closes this issue, but I'd like to confirm that.

**Comment by janaiyengar** [comment]
This guidance is in the document now: https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-8.6
