### ISSUE TITLE
Handling failed migration

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2131]
S 9.3. says:

```
After changing the address to which it sends non-probing packets, an endpoint
could abandon any path validation for other addresses.
```

And 9.3.2. says:
```
Note that receipt of packets with higher packet numbers from the legitimate peer
address will trigger another connection migration.  This will cause the
validation of the address of the spurious migration to be abandoned.
```

Which one of these is right?

**Comment by MikeBishop** [comment]
I'm not seeing the conflict -- they seem to work in concern.  Can you explain the failure mode in more detail?  In what circumstance do these instruct the server to do contradictory things?

**Comment by ekr** [comment]
The first paragraph says that you *could* abandon validation and the other says that you *will* abandon it. If you *could* abandon it, then you also are allowed no to,

**Comment by martinthomson** [comment]
Yeah, this is a problem.  I think that the latter needs to change.  We want to allow paths to be validated at any time for any reason.

The consequence is that a spurious migration might continue being validated, but as long as it isn't actively *used*, we have a defense.  There might need to be some tweaking of the surrounding text.

**Comment by janaiyengar** [comment]
This is OBE.
