### ISSUE TITLE
How many datagrams can a client send prior to validating the path?

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2135]
To avoid it being used as a DDoS attack vector, we forbid the server from sending more than three datagrams before the path is validated during the handshake.

Do we need similar safeguard for the number of datagrams that a client may emit before it sees a packet from the server? IMO, it might be worth considering, due to the following reasons:

* The attack vector exists. For example, an attacker can inject a DNS response for a huge website to a DNS server. Then, clients would start sending 0-RTT packets to the victim.
* The number of packets that the client can send prior to path being validated was one for TCP. The QUIC transport draft is silent about the limit (though INITCWND would practically become in play here).

**Comment by mikkelfj** [comment]
We limit amount of bytes now, not number of packets, no?

If we limit the client, it would need to be a rate limit, otherwise it would never be able to connect again later when network conditions improve.

I'm not sure it makes sense to have a MUST limit on client, as there can be many deployments types with different attack vectors. DNS might not be in the equation. However, obviously a client should not saturate a link on connection retries.

**Comment by kazuho** [comment]
> We limit amount of bytes now, not number of packets, no?

That's a good point. This is not a reflection attack (unlike the server's packets) and therefore it makes more sense to define a limit using number of bytes.

> If we limit the client, it would need to be a rate limit, otherwise it would never be able to connect again later when network conditions improve.

IMO it can be a fixed number of bytes that can be transmitted in one RTO. For example, "a client SHOULD NOT send more than 3 * MTU bytes per every retransmission timeout, until it receives a packet from a server."

**Comment by ianswett** [comment]
My thinking was that the initial CWND was a sufficient limit.

**Comment by kazuho** [comment]
@ianswett If that's the consensus, I am happy to accept it (I do not have a strong opinion here).

**Comment by ianswett** [comment]
That's what I remember us arriving at before.  But I'm happy to have it explicitly stated if it's not.

**Comment by ianswett** [comment]
@mikkelfj Malicious clients can always send an unlimited number of packets anywhere.  QUIC doesn't change that.

**Comment by mikkelfj** [comment]
@ianswett I mean that the client causes the peer to respond to a fake migration attempt and coerces the peer into sending packets elsewhere. I'm not sure if that can amplify, e.g. via PMTU probe.

**Comment by mikkelfj** [comment]
I think we had a similar discussion twice, getting some text, and later removed. But I don't recall anymore.

**Comment by ianswett** [comment]
There's a section on address validation which should prevent reflection attacks: https://tools.ietf.org/html/draft-ietf-quic-transport-17#section-8

This issue is about what the client can send.

**Comment by mikkelfj** [comment]
@ianswett thanks, that covers it.

**Comment by kazuho** [comment]
@ianswett 
> I don't see anyone objecting to that approach, is there some text you'd like added to one of the drafts?

Filed #2341. I do not have a strong opinion on whether this needs to be clarified, therefore I would not oppose if the PR gets refused.

**Comment by ianswett** [comment]
Thanks for the PR.  I'm not against clarification, I'm just not sure what to write and I'd like to close this before Tokyo if we can.  Taking a look at the PR now.
