### ISSUE TITLE
Preferred address text is confusing

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2146]
The following text is kind of hard to track:

```A server might receive a packet addressed to its preferred IP address at any
time after it accepts a connection.  If this packet contains a PATH_CHALLENGE
frame, the server sends a PATH_RESPONSE frame as per {{migrate-validate}}.  The
server MAY send other non-probing frames from its preferred address, but MUST
continue sending all probing packets from its original IP address.

The server SHOULD also initiate path validation of the client using its
preferred address and the address from which it received the client probe.  This
helps to guard against spurious migration initiated by an attacker.
```

I'm not really following what's going on here. The server knows that it has two addresses and it wants to use its preferred address. Why does it have to probe from its preferred address. Also, I don't understand how these two paragraphs work together. The first one says you have to send probing packets from your original address but the second paragraph tells you to probe from the preferrd address.

**Comment by MikeBishop** [comment]
You're right, that last restriction in the first paragraph looks backwards.  IIRC, it's supposed to be a reiteration of the fact that the client decides when to actually cut over, so the server shouldn't be sending non-probing packets from the preferred address until the client starts sending them there.

This is section 9.6.2 of Transport.

**Comment by martinthomson** [comment]
I think that the first paragraph is just missing "... until it receives a non-probing packet from the client at its preferred address."  Then maybe a simple: "The server MUST probe on the path toward its preferred address before sending non-probing packets."
