### ISSUE TITLE
Why would late-arriving packets create state?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2148]
```
Disposing of connection state prior to the end of the closing or draining period
could cause delayed or reordered packets to be handled poorly.  Endpoints that
have some alternative means to ensure that late-arriving packets on the
connection do not create QUIC state, such as those that are able to close the
UDP socket, MAY use an abbreviated draining period which can allow for faster
resource recovery.  Servers that retain an open socket for accepting new
connections SHOULD NOT exit the closing or draining period early.
```

I'm not following why in general this *would* create state. If the
handshake has occurred > MSL ago, and you just refuse to create state
on short packets with unknown CIDs s, why isn't that enough?

**Comment by martinthomson** [comment]
This was written when there was some uncertainty about what packets might look like.  I think that we can truncate this sentence.  Basically, you can drop state earlier, but it will mean that you won't be able to attribute any laggardly packets properly.
