### ISSUE TITLE
Increase the odds of a stateless reset?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2153]
```
An endpoint can increase the odds that a packet will trigger a Stateless Reset
if it cannot be processed by padding it to at least 38 bytes.
```

Why does this increase the odds? It seems like the test here is deterministic.

**Comment by MikeBishop** [comment]
The previous paragraphs allow the receiver to ignore the MUST-be-smaller if it can use state to avoid looping.  Even if the packet is large enough, the receiver is also allowed to rate-limit the SRs.  It's never guaranteed that you'll trigger one.  It might actually be deterministic on the receiver side, but that isn't knowable by the sender.

However, sending a packet that's bigger than 38 bytes eliminates one big reason the receiver might ignore without generating a SR, so you improve your odds by doing that.

**Comment by MikeBishop** [comment]
Does this require text?  The explanation of how it might not be deterministic (from the client's perspective) is already present in the preceding sections.

**Comment by martinthomson** [comment]
I'm going to punt this back to a potential design issue, requiring of a consensus call.  Why?  Because I think that the right answer is to explicitly permit endpoints to discard packets that are too small.

I'm recommending removal of the deterministic text in the process, for the reasons implicit in Mike's comments.  The rest should sort itself.

**Comment by mikkelfj** [comment]
>  Because I think that the right answer is to explicitly permit endpoints to discard packets that are too small.

Yes, but I still suggest it can respond on some safe random fraction of these.

**Comment by martinthomson** [comment]
Randomness was explicitly ruled out in discussions about a year ago.  People felt uncomfortable with non-deterministic behaviour.  (FWIW, I was OK with non-determinism on the basis that individual cases of determinism devolve to hollistic non-determinism, but that wasn't a winning argument at the time.)

**Comment by mikkelfj** [comment]
It still doesn't change the physics of it all though, but I take that is what you mean by "holistic non-determinism". Now you just have random peers making arbitrary choices instead, some of which could be fatal, others inefficient.

**Comment by martinthomson** [comment]
#2869 decided this issue for us.  But we should confirm with the working group.
