### ISSUE TITLE
Idempotent frames?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2154]
```
All QUIC frames are idempotent.  That is, a valid frame does not cause
undesirable side effects or errors when received more than once.
```

Is this just a statement about this spec or a normative requirement
on future specs?

**Comment by mikkelfj** [comment]
It is not an invariant.

**Comment by ekr** [comment]
There's more to requirements on future specs than invariants.

**Comment by mnot** [comment]
Perhaps it'd be better to use `QUICv1` to avoid confusion like this.
