### ISSUE TITLE
Retry is not a long header

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2157]
```
A Retry packet uses a long packet header with a type value of 0x3. It carries
an address validation token created by the server. It is used by a server that
wishes to perform a stateless retry (see {{validate-handshake}}).
```

This is not correct b/c the long header has length and PN.

**Comment by MikeBishop** [comment]
Retry uses a long header as defined in Invariants, but doesn't include the extra fields defined for the long header in v1.  Perhaps we need a different name for the two long-header references, or perhaps the length/PN should be defined as part of the body of each packet type.
