### ISSUE TITLE
Optimistic ACKs and PFS in security considerations

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2160]

**Comment by ekr** [comment]
```
The second mitigation is that the server can require that acknowledgments for
sent packets match the encryption level of the sent packet.  This mitigation is
useful if the connection has an ephemeral forward-secure key that is generated
and used for every new connection.  If a packet sent is protected with a
forward-secure key, then any acknowledgments that are received for them MUST
also be forward-secure protected.  Since the attacker will not have the
forward-secure key, the attacker will not be able to generate forward-secure
protected packets with ACK frames.
```

I don't understand what this means. Forward-security doesn't matter
here because you always get fresh keys for each connection and if you
don't see SH, you can't send packets.

**Comment by mikkelfj** [comment]
This might be a leftover from before the change towards multiple packet number spaces. An attempt to ensure ACK's use the proper "channel".

**Comment by martinthomson** [comment]
Definitely @janaiyengar's text.  "Forward-secure" is a turn of phrase gQUIC uses.

**Comment by janaiyengar** [comment]
Wow, this text is weird. I don't remember writing this, but then I don't remember half the things I do. I'll send a PR.
