### ISSUE TITLE
Limit sending while in RTO

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2162]
A sender might have unused cwnd left when it enters the RTO phase of recovery. The spec currently does not prohibit sending under these conditions. In other words, a sender that is RTOing might suddenly send a cwnd's worth of data. We may want to disallow this.

**Comment by janaiyengar** [comment]
This issue was noted by @pravb a while ago. I'm not convinced that this issue needs addressing, but I wanted to document it.

**Comment by ianswett** [comment]
Given the new text doesn't have a concept of RTO and focuses on an extended period of persistent congestion, I'm closing this issue.
