### ISSUE TITLE
ECN attacks

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2163]
S 21.7 

```
An on-the-side attacker can duplicate and send packets with modified ECN
codepoints to affect the sender's rate.  If duplicate packets are discarded by a
receiver, an off-path attacker will need to race the duplicate packet against
the original to be successful in this attack.  Therefore, QUIC receivers ignore
ECN codepoints set in duplicate packets (see {{ecn}}).
```

This could use more elaboration. As written, it seems like if you win the race (which you might like half the time) then you will succeed in the attack. Is that true?

**Comment by martinthomson** [comment]
Yes, the winner of a race can reduce the congestion window or maybe prevent it from being reduced.

**Comment by gorryfair** [comment]
As I see this: QUIC receivers ignore the ECN codepoint field received in IP packets that carry duplicate QUIC packets (see {{ecn}}).

**Comment by gloinul** [comment]
So @ekr is this resolved or do you expect more than what Martin wrote?

**Comment by martinthomson** [comment]
I think that I can make that call now.  If there is a problem, we can open an issue.
