### ISSUE TITLE
References in Section 12 are awkward

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2165]
> Packets that carry the long header are Initial Section 17.5, Retry Section 17.7, Handshake Section 17.6, and 0-RTT Protected packets Section 12.1.

These references should be delimited with parentheses, as is done in the other paragraphs:

> QUIC endpoints communicate by exchanging packets. Packets are carried in UDP datagrams (see Section 12.2) and have confidentiality and integrity protection (see Section 12.1).
>
> This version of QUIC uses the long packet header (see Section 17.2) during connection establishment and the short header (see Section 17.3) once 1-RTT keys have been established.

It also seems odd that our references are to subsections (5, 7, 6) rather than matching the order of the actual sections, and that three of the references are to 17.x while one is to 12.1.  Can we make these a little more symmetric?

**Comment by martinthomson** [comment]
PRs welcome.
