### ISSUE TITLE
Embed QUIC version in expansion

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2170]
This may duplicate a previous issue, but there has been a lot of aggressive closing. Instead of using "quic hp", etc. we should use a label that reflects the QUIC version. Assuming I am counting correctly, we can do:

"qxxxxxxxx hp" where xx is the version in hex.

This would match TLS practice.

**Comment by ekr** [comment]
I don't strongly object, but it seems like if we know this is v1, we might want to indicate that, but ultimately I agree it's a matter of taste

**Comment by martinthomson** [comment]
Tokyo conclusion: @martinthomson and @ekr will sort this out.

**Comment by larseggert** [comment]
London discussion: @ekr and @martinthomson to resume work

**Comment by mikkelfj** [comment]
If the expansions are revised, could we get rid of spaces then?

**Comment by ekr** [comment]
I don't think that would be advisable. We should keep this as close to TLS practice as possible.

**Comment by larseggert** [comment]
Discussed in Montreal, close with no action
