### ISSUE TITLE
What's a short period?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2172]
```
An endpoint SHOULD retain old keys for a short period to allow it to decrypt
packets with smaller packet numbers than the packet that triggered the key
update.  This allows an endpoint to consume packets that are reordered around
the transition between keys.  Packets with higher packet numbers always use the
updated keys and MUST NOT be decrypted with old keys.
```

If you are going to have a 2119 SHOULD here, I think you need to explain what a short period is

**Comment by hardie** [comment]
On Thu, Dec 13, 2018 at 4:18 PM ekr <notifications@github.com> wrote:

> An endpoint SHOULD retain old keys for a short period to allow it to decrypt
> packets with smaller packet numbers than the packet that triggered the key
> update.  This allows an endpoint to consume packets that are reordered around
> the transition between keys.  Packets with higher packet numbers always use the
> updated keys and MUST NOT be decrypted with old keys.
>
> If you are going to have a 2119 SHOULD here, I think you need to explain
> what a short period is
>
> 2 RTT?  Just throwing out a theory, but it seems like packets that aren't
decryptable after that would have the data re-transmitted anyway.

**Comment by martinthomson** [comment]
Packets are declared lost after RTT*9/8 or thereabouts, so that would be fine.  I was more generous in my proposal; going with the same timer we use for other key discards (3RTO).  That is far more than necessary, but there's no real cost in holding old keys over that sort of period.
