### ISSUE TITLE
Using caution

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2173]
```
duplicate.  Implementations SHOULD use caution in relying on any data which is
contained in Initial packets that is not otherwise authenticated.
```

This is pretty hard to make sense of. Am I relying on the data as a server when I take the DH key and work with it? That's not authenticated. If you're going to use 2119 language, then it has to be clear what conformance means.

**Comment by mikkelfj** [comment]
I think this might originate from early times where all sorts of frames could exist in early transmission.

The text now says

> The payload of an Initial packet includes a CRYPTO frame (or frames) containing a cryptographic handshake message, ACK frames, or both. PADDING and CONNECTION_CLOSE frames are also permitted. An endpoint that receives an Initial packet containing other frames can either discard the packet as spurious or treat it as a connection error.

However, the connection error part might be inviting injection attacks?

**Comment by martinthomson** [comment]
We already decided that CONNECTION_CLOSE in Initial was acceptable on the basis that more complicated attacks (flip a bit in the TLS random, for instance) are more effective at denial of service.
