### ISSUE TITLE
Don't levy requirements on non-QUIC TLS endpoints

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2174]
Section 8.2 says:

```
Endpoints MUST NOT send this extension in a TLS connection that does not use
QUIC (such as the use of TLS with TCP defined in {{!TLS13}}).  A fatal
unsupported_extension alert MUST be sent if this extension is received when the
transport is not QUIC.
```

However, this directly contradicts TLS 1.3 https://tools.ietf.org/rfcmarkup?doc=8446#section-4.1.2, which says:

```
Servers MUST ignore unrecognized extensions.
```

In order to say this, this document would need to Update 8446, and even then it doesn't make sense because the presumptive point of this rule is to detect attempts to negotiate QUIC with non-QUIC TLS endpoints, which don't need to conform to this RFC (and may predate it).

**Comment by mikkelfj** [comment]
I don't think QUIC can tell anyone what do with regard to any protocol that is not QUIC. And since QUIC v1 carries its own TLS record wrapping it makes even less sense.

**Comment by kazuho** [comment]
I agree with the problem statement, however I wonder if this opens a session ticket obtained using TLS13-over-TCP to be used in QUIC. Is that what we want?

**Comment by ekr** [comment]
@kazuho: why would this text have an impact on that? Couldn't I negotiate TLS 1.3 over TCP  w/o extension and then send the resume over QUIC w/ extension?

**Comment by martinthomson** [comment]
The point here is to insist on the alert if the extension is understood.  This wasn't intended to supersede 8446.

**Comment by kazuho** [comment]
@ekr My bad. I was confused with the earlier versions of the QUIC-TLS draft that had the transport_parameters extension in the session tickets.

**Comment by ekr** [comment]
@martinthomson I think you could phrase that, but is it useful, given that we can't rely on it?

**Comment by martinthomson** [comment]
Probably not.  I'm OK with culling the text.
