### ISSUE TITLE
Rename ACK block something else?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2178]
An ACK frame currently consists of:

- A header
- An ACK block count (N)
- A field called ACK blocks which consists of
   - A single field called "First ack block" (if N > 0)
   - N-1 repeats of a pair of fields called respectively "gap" and "Additional ACK block"

(Please correct me if I have misread this).

It's a bit weird to call these fields "blocks" because really they are the length of something, rather than a block. Perhaps "ACK Range"?

**Comment by janaiyengar** [comment]
How about "ack range" and "missing range"?

I like the idea of moving the "First ack block" out of the "ack block"
section and into the fixed section. Ack Block Count refers to the number of
Gaps+AckBlocks anyways, so that would work out fine, I think.

**Comment by martinthomson** [comment]
#2197 resolved this one.
