### ISSUE TITLE
If you don't reset DCID you will repeat keys.

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2179]
```
Note that if you don't reset DCID, you repeat keys


A client sets the Destination Connection ID field of this Initial packet to the
value from the Source Connection ID in the Retry packet. Changing Destination
Connection ID also results in a change to the keys used to protect the Initial
packet. It also sets the Token field to the token provided in the Retry. The
client MUST NOT change the Source Connection ID because the server could include
the connection ID as part of its token validation logic (see
{{validate-future}}).
```

Correct me if I'm wrong, but if the server chooses a DCID that is the same as the client's DCID (which, I believe it can do), then you would get the same keys. Arguably, this doesn't matter b/c any attacker who is on-path can derive the keys anyway, but...

**Comment by martinthomson** [comment]
I thought that we had a requirement to keep increasing the nonce.

(You say that this isn't a problem, and I agree that it isn't given the ease with which keys are obtained.  But there are tweaks to the protocol being contemplated that might trip over this.)

**Comment by martinthomson** [comment]
I agree.  That's a mistake.  PR inbound.

**Comment by martinthomson** [comment]
Too many open discussions, I missed this:

> The server includes a connection ID of its choice in the Source Connection ID field. This value MUST not be equal to the Destination Connection ID field of the packet sent by the client.
