### ISSUE TITLE
Should number of Tail Loss Probes be 1 or 2?

### ISSUE THREAD

**Issue by pravb** [quicwg/base-drafts#2185]
Latest RACK draft suggests just one TLP (likely reflecting Linux TCP) and Windows TCP also does just one TLP.

**Comment by ianswett** [comment]
After discussion in Prague, we agreed we're happy with the number of packets sent upon PTO.  This issue originally referenced whether QUIC should suggest 1 TLP or 2 TLPs in a row before RTO.  Now that QUIC uses PTO with exponential backoff, that's largely solved, but there is still a detail issue of whether the current multiplier of PTO should be 3 or 2.  2 is the value that would have naturally resulted if we previously recommended 1 TLP previously.

@pravb Indicated he'd open a new issue for this 2 vs 3 question, and we should close this issue.
