### ISSUE TITLE
Discuss considerations for max_ack_delay

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2186]
Conversations with implementers suggests that it might be useful to clearly discuss considerations for how a receiver might choose max_ack_delay. Specifically, the receiver should  communicate worst case delay, since communicating something smaller can result in spurious retransmissions. Some guidance should be added.

**Comment by pravb** [comment]
A receiver SHOULD add a perturbation on top of the actual max ack delay. This value should be the OS timer granularity (typically 15.6 msec) or at least 2 msec when platform supports fine grained timers. This implies that a receiver which has turned off ACK delays, still needs to advertise a non-0 value in the transport parameter. 


Should a sender add the perturbation itself when it sees the value 0 or absence of the transport parameter?

**Comment by janaiyengar** [comment]
@pravb: I think this is good. I think SHOULD is the right level here -- there might be conditions where a receiver knows its delay bounds well enough.

As you noted in #2114, this is a departure from how we've traditionally thought about responsibilities, since in TCP this is entirely sender-side.  This is probably important to emphasize, as a rationale for why we're doing this differently in QUIC.

**Comment by janaiyengar** [comment]
@pravb: 15.6 ms is an oddly specific timer granularity ;-)

**Comment by ianswett** [comment]
There is text that you should include any timer delays in the max ack delay when we define the transport param in the transport doc, but not elsewhere:
"This value SHOULD include the receiver's expected delays in alarms firing. For example, if a receiver sets a timer for 5ms and alarms commonly fire up to 1ms late, then it should send a max_ack_delay of 6ms. If this value is absent, a default of 25 milliseconds is assumed."

Ideally I'd like to ensure specifying a max ack delay of 0 degrades to suboptimal, but reasonable behavior.  That's one of the reasons we limited the adjustment of RTT by max_ack_delay.

**Comment by ianswett** [comment]
Somewhat related, editorially.  Jana was going to move the ack sending text from recovery into transport, because now it's split between two spots and there's already at least one inconsistency.

The text about max_ack_delay is currently in 3 spots from what I can tell, so maybe it'd be nice to unify that as well?

**Comment by ianswett** [comment]
@janaiyengar, Is this closed the host delay section of #2568 ?

**Comment by pravb** [comment]
What about scheuler delays? I've been thinking about max_ack_delay and I think we need more than just one timer tick here since its supposed to be the worst case. If we get this wrong then we will have lot of unnecessary firing of the TLP timer when only the tail packet is due.

**Comment by janaiyengar** [comment]
@pravb: I've proposed separating platform delays from stack-controllable delays in #2596. My thinking has moved since this issue was first filed, and I now think that max-ack-delay should only include stack-controllable delays. Any additional delays will go into the smoothed_rtt anyways, so any timers should account for those delays via the increase in the smoothed_rtt. At any rate, I propose that we move discussion of that specific question to #2596.

I'm closing this issue, let's open new issues for any other more specific concerns.
