### ISSUE TITLE
persistent congestion can never happen

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2208]
The collapse of the congestion window (which used to happen after an RTO was verified) happens in `CongestionEvent`, if `pto_count > kPersistentCongestionThreshold`.
`CongestionEvent` is called from `OnPacketsLost`, which is called from `DetectLostPackets`, which in the case of a tail is only called when a new ACK is received from `OnAckReceived`. However, `OnAckReceived` resets the `pto_count` to 0 *before* calling `DetectLostPackets`, so the condition that leads to the collapse of the congestion window can never occur.

**Comment by martinthomson** [comment]
Marking as design, because it will affect interop if this is implemented as documented.

**Comment by marten-seemann** [comment]
Why is this design? The intention of the pseudo code was clearly that the congestion window is collapsed, and the text states this as well.

**Comment by martinthomson** [comment]
It's bug that probably needs to go into change logs, that's all.  (We really need a 'bug' label for this sort of thing.)
