### ISSUE TITLE
0RTT ACKs

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#221]
The quic-tls draft says:

```
  What about 0-RTT data?  Should we allow acknowledgment of 0-RTT with
  unprotected frames?  If we don't, then 0-RTT data will be unacknowledged until
  the handshake completes.  This isn't a problem if the handshake completes
  without loss, but it could mean that 0-RTT stalls when a handshake packet
  disappears for any reason.
```

I assume what you're talking about here is the case where the server's first flight of packets are lost, because the server can only find itself in one of two positions because the CH must fit in a single packet.

- It has no ClientHello, in which case it must buffer any packets
- It has a ClientHello, in which case it can can complete the handshake by sending its first flight.

My sense is that having stalling of 0-RTT in the case where parts of the server's first flight are lost is not that big a deal. If you really don't want stalling, you should retransmit faster :)

**Comment by martinthomson** [comment]
Yes, this is a pretty simple bug to fix.
