### ISSUE TITLE
Packet Number encoding in draft-17

### ISSUE THREAD

**Issue by yangchi** [quicwg/base-drafts#2217]
In Section 12.3, the transport specs says: 

> Where present, packet numbers are encoded as a variable-length integer (see Section 16). 

But in both 17.2 (Long Header) and 17.3 (Short Header), Packet Number field in the packet is noted as the following format:
> Packet Number (8/16/24/32)

which suggest it isn't variable-length integers.

Can we get some clarification regarding this? Thank you!

**Comment by janaiyengar** [comment]
Section 17.2/17.3 is correct -- PNs are _not_ encoded using the varint form in Sec 16.
