### ISSUE TITLE
Move HTTP Section 5 before Section 4

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2220]
It would be a lot easier to read the spec if the lifecycle (which provides an overview of operation implicitly) came before the packet formats. Happy to provide a PR, but no point if the editors don't want it.

**Comment by MikeBishop** [comment]
Thanks for the suggestion.  I can see this either way.  The ordering was intended to follow the HTTP/2 pattern of "framing layer, putting HTTP on the framing layer."  The QUIC spec's new layout of successive layers of detail (concepts, then specific mechanisms, then wire format) would suggest putting frame specifics last.

PR not necessary -- it's a straightforward change if we decide to reorder this way.

**Comment by ianswett** [comment]
I just suggested this change the other day, because I had the same issue.  In particular, talking about the multiple push frames before introducing what push is is very awkward.
