### ISSUE TITLE
Other ways to discover QUIC besides Alt-Svc

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2221]
S 2.2 says.

```
On receipt of an Alt-Svc record indicating HTTP/3 support, a client MAY attempt
to establish a QUIC connection to the indicated host and port and, if
successful, send HTTP requests using the mapping described in this document.
```

1. This implies that the only way in which a client might discover that
the server did HTTP/3 was alt-svc, but there might be other mechanisms.
One example would be to simply try to connect to UDP/443 on a given site.
Also, this implies that that information isn't sticky, whereas I'm assuming
we want it to be.

```
Connectivity problems (e.g. firewall blocking UDP) can result in QUIC connection
establishment failure, in which case the client SHOULD continue using the
existing connection or try another alternative endpoint offered by the origin.
```

This seems like it doesn't match up with a happy eyeballs kind of approach
because I might have neither an existing connection nor an alternative
provided by the server. Rather, I'm provided with the URL and then I
try to connect to both, but if QUIC fails fast, then I might still be
waiting, in which case neither of these cases applies.

**Comment by LPardue** [comment]
Seems related to https://github.com/quicwg/base-drafts/issues/253. Our third oldest ticket that was opened in Jan 2017 and deferred by @martinthomson in March 2018.

**Comment by martinthomson** [comment]
Let's shift the discussion over there.  I'm not sure that this is really the same thing, but it seems like it would be best to have the discussion in the one place.
