### ISSUE TITLE
Confusing text around push streams

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2225]
S 3.2.2.

```
A push stream is indicated by a stream type of `0x50` (ASCII 'P'), followed by
the Push ID of the promise that it fulfills, encoded as a variable-length
integer. The remaining data on this stream consists of HTTP/3 frames, as defined
in {{frames}}, and fulfills a promised server push.  Server push and Push IDs
are described in {{server-push}}.
```

This isn't understandable without knowing what push is or what a PUSH
promise is. Am I supposed to get that from 7540? In either case, you
should clearly state that a push stream can only be used for a single
push promise (this is implied by the formatting). Happy to supply a PR if
we can agree on what's wanted?

**Comment by martinthomson** [comment]
Yes, as currently written, a push stream corresponds 1:1 with a PUSH_PROMISE.  Which is consistent again with 7540 (we had a period where it was not).

**Comment by LPardue** [comment]
Well. A push stream corresponds one-to-one with a push ID. You can duplicate promises using the DUPLICATE_PUSH frame.

I think this is what was attempted to be described by the term "promised server push" as abstract from the frames that might get sent. If the language needs to improve to make this clearer then lets do it.

**Comment by MikeBishop** [comment]
Does #2701 address this sufficiently, now that the description of push precedes this section?  There's already a back-reference at the end of the paragraph if someone needs more details.

**Comment by MikeBishop** [comment]
Closing; please reopen if you feel that #2701 does not sufficiently address this.
