### ISSUE TITLE
It's annoying that one can't send push in 0.5RTT

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2227]
S 5.4.

```
Server push is only enabled on a connection when a client sends a MAX_PUSH_ID
frame (see {{frame-max-push-id}}). A server cannot use server push until it
receives a MAX_PUSH_ID frame. A client sends additional MAX_PUSH_ID frames to
control the number of pushes that a server can promise. A server SHOULD use Push
IDs sequentially, starting at 0. A client MUST treat receipt of a push stream
with a Push ID that is greater than the maximum Push ID as a connection error of
type HTTP_PUSH_LIMIT_EXCEEDED.
```

This seems not ideal. Could we put a default in transport parameters
or the like.

**Comment by afrind** [comment]
As push is currently designed, a server can't push until it receives a request.  The MAX_PUSH_ID frame can arrive in the same flight as the request.

**Comment by afrind** [comment]
@ekr I'm not sure what you are asking be removed.  Are you suggesting the server should be able to send a push without a request, or something else?

**Comment by ekr** [comment]
On Thu, Dec 20, 2018 at 4:43 PM afrind <notifications@github.com> wrote:

> @ekr <https://github.com/ekr> I'm not sure what you are asking be
> removed. Are you suggesting the server should be able to send a push
> without a request,
>

Yes


or something else?

**Comment by afrind** [comment]
That's not part of the HTTP/2 push design.  I agree that it would be a nice feature, but perhaps it's out of charter/scope for v1?

**Comment by kazuho** [comment]
While I understand the concern, I would prefer to not change the semantics of push at this point (especially considering the fact that the design comes from H2).

@ekr 
> Could we put a default in transport parameters or the like.

Looking at #436, it seems like we concluded to not? I remember myself arguing for exchanging HTTP-level settings using Transport Parameters, but people preferred the other way.

**Comment by martinthomson** [comment]
We discussed pushes without a request as context in h2, and concluded that they were very difficult.  Using the request as context is what made it possible to support push at all in cases where there are multiple users of the same connection (a common occurrence).

I can see how using 0.5 RTT for pushing some content is appealing, such as origin policy, favicons, or other such common resources.  However, I see that as an entirely new feature.

**Comment by mikkelfj** [comment]
Doesn't push risk pushing a lot of data that is already client cached?

**Comment by martinthomson** [comment]
Yeah, settings doesn't cut it here.  You need a new version.

**Comment by ianswett** [comment]
One question on: "Using the request as context is what made it possible to support push at all in cases where there are multiple users of the same connection (a common occurrence)."
I thought browsers don't pool connections from different users?  That seems sensible from a user-expectation and privacy perspective.

Proxies may, but they should really be providing some other user-isolation besides a push ID to ensure the response doesn't get pushed back to the wrong user.  Or they should only use push from the server to end user, which I suspect is actually what happens.

I'm not arguing for replacing the current push design with unbound push, but we should be willing to make changes to push in cases the original assumptions didn't turn out to be true.

**Comment by martinthomson** [comment]
The original requirement was, I think, from HTTP.SYS, so @MikeBishop might be able to provide more insight there.  There, you can have different applications sharing the same connection, I recall.  Whether that is advisable, I haven't thought through fully.  I think that gateways/reverse proxies were a case for this more than (forward) proxies.

Even within a browser, requests from the same origin can share connections (though not always).  Even there, you might want to know whether the push was attributed to a page load in one context vs. another.

**Comment by afrind** [comment]
Maybe I'm not understanding @ianswett's comment, but our reverse proxy is capable of proxying HTTP/2 pushes (by virtue of the fact that they are bound to a request).  That said, given that push is an optimization anyways, a reverse proxy could always drop or cancel an unbound push if it couldn't figure out which client(s) to send it to.

**Comment by MikeBishop** [comment]
I believe we are now closing v2 issues for sanitation reasons, and revisiting them post-recharter.
