### ISSUE TITLE
How do I generate an RST?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2228]
S 5.2.

```
A TCP connection error is signaled with QUIC RESET_STREAM frame. A proxy treats
any error in the TCP connection, which includes receiving a TCP segment with the
RST bit set, as a stream error of type HTTP_CONNECT_ERROR
({{http-error-codes}}).  Correspondingly, a proxy MUST send a TCP segment with
the RST bit set if it detects an error with the stream or the QUIC connection.
```

I don't believe this is possible on UNIX. What system call do I use to
generate RST? Neither close() nor shutdown() does it.

**Comment by afrind** [comment]
You set SO_LINGER to {1, 0}, then close.

**Comment by janaiyengar** [comment]
I don't think there's a question here about the -http draft, is there?

**Comment by ekr** [comment]
The question is if it's possible on standard OSes. Sounds like it is on Unix. How about Windows? @nibanks

**Comment by LPardue** [comment]
This is the same requirement as in HTTP/2. A "MUST (but we know you probably won't)" ?

**Comment by ekr** [comment]
Well, that was a joke in 6919, so probably we shouldn't do that.

**Comment by ekr** [comment]
Note that this particular issue is not about half-closed. In half-closed,
you generate a FIN and then keep receiving data. This is about sending an
RST.

**Comment by janaiyengar** [comment]
Perhaps the text should be "SHOULD", and if the platform doesn't allow it, to "close the connection".

**Comment by MikeBishop** [comment]
There's risk with that too, though.  We encountered issues where the TCP connection was closed cleanly instead of aborted, and the client interpreted a truncated response as the (cacheable) response.  It gets ugly.

If you can't force a RST on the other side, you perhaps shouldn't be implementing CONNECT.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; MUST close the connection, SHOULD close with a RST.
