### ISSUE TITLE
When can PUSH_PROMISE frames be sent?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2230]
S 5.

> When a stream is closed, this indicates the end of an HTTP message. Because some
messages are large or unbounded, endpoints SHOULD begin processing partial HTTP
messages once enough of the message has been received to make progress.  If a
client stream terminates without enough of the HTTP message to provide a
complete response, the server SHOULD abort its response with the error code
HTTP_INCOMPLETE_REQUEST.

This creates two ways to say the end of the HTTP messages:

- Send the HEADERs frame (at which point you have to close,
  but you know its done)
- Don't send the HEADERs frame and close the stream

That seems a bit unfortunate. Would it make more sense to require the final HEADERS frame, even if it were empty?

Also, can the server send PUSH_PROMISE after the second HEADERS. I think no, but...

**Comment by martinthomson** [comment]
This is low on the list of ways in which HTTP is not great.  I'm not inclined to change it.

There is no prohibition on PUSH_PROMISE, just a recommendation against it.  That is, promises SHOULD precede any mention of the promised resource.  It's very likely that a promise after trailers is not useful, but there is no explicit prohibition.

**Comment by kazuho** [comment]
+1 to what @martinthomson says.

I also agree that this is not great, but this is based on the design of HTTP/2. I do not think there is a reason strong enough to adopt a different approach.

**Comment by huitema** [comment]
This HTTP novice was also perplexed by the relation between "content length" header and length of data frames. This might be unrelated...

**Comment by MikeBishop** [comment]
Discussed in Tokyo; will not change the components of messages, but will add editorial clarification about where PUSH_PROMISE can be sent.

**Comment by MikeBishop** [comment]
Since the guidance about where PUSH_PROMISE should be sent falls in the broader category of "info from 7540 that needs to be restated / referenced in H3," I plan to fix this as part of that change.
