### ISSUE TITLE
HTTP Errors aren't consistent

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2231]
Clients don't send GOAWAY and when a client sends one, the server treats
it as HTTP_UNEXPECTED_FRAME. By contrast, servers don't send MAX_PUSH_ID
but the client treats receiving one as HTTP_MALFORMED_FRAME.

By contrast, if GOAWAY is sent on !control it's HTTP_UNEXPECTED_FRAME,
but if MAX_PUSH_ID is sent on !control, it's HTTP_WRONG_STREAM.

I think the answers here are HTTP_UNEXPECTED_FRAME and HTTP_WRONG_STREAM
respectively, but we should be consistent.

**Comment by MikeBishop** [comment]
I think you're correct.  There are some situations where newer errors would be more appropriate.
