### ISSUE TITLE
description of persistent congestion threshold is wrong

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2243]
The text says
> If a threshold number of consecutive PTOs have occurred (pto_count is more than kPersistentCongestionThreshold, see Section 7.9.1), the network is considered to be experiencing persistent congestion, and the sender’s congestion window MUST be reduced to the minimum congestion window.

Similar text exists for the description of kPersistentCongestionThreshold.

We actually only collapse the congestion window when receiving an ACK for a probe packet, and only if this ACK leads us to declare any packet(s) lost.
Specifically, this means that pto_count may grow larger than kPersistentCongestionThreshold, if no acknowledgements are received.

**Comment by janaiyengar** [comment]
Good point. Sent #2244.
