### ISSUE TITLE
AES-Based Header Protection still mentions "counter input"

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#2246]
In 5.4.3. AES-Based Header Protection

> This algorithm samples 16 bytes from the packet ciphertext. This value is used as the counter input to AES-ECB.

ECB has no counter, so "counter input" doesn't make sense to me.

**Comment by martinthomson** [comment]
Thanks.  No PR for such a simple change.

**Comment by rpaulo** [comment]
Noted...
