### ISSUE TITLE
Authenticating public parts of the packet header

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#226]
QUIC AEAD usage in quic-tls draft currently says "associated data, A,  for the AEAD is an empty sequence." The current rationale is that the public header fields do not need to be authenticated since the connection ID, flags, packet number, and version number are all effectively covered by  encryption/decryption. 

We have at least 1 public flags field that is as yet unused. Since we do not know its use yet, we may want to authenticate the header to future-proof.

**Comment by martinduke** [comment]
I can think of mildly problematic middlebox behavior that QUIC could block by authenticating the public header. For instance, a middlebox could inspect a CHLO and then rewrite the connection ID to aid in classification and traffic shaping.

This may or may not be acceptable, but then if there is a path change or multipath that bypasses the middlebox, the connection will break.

**Comment by martinthomson** [comment]
We didn't write this down, but it was discussed at the Tokyo interim.  I can take this one on.
