### ISSUE TITLE
RESET_STREAM.final_offset is ambiguous

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2262]
Current definition of "Final Offset" is: _a variable-length integer indicating the absolute byte offset of the end of data written on this stream by the RESET_STREAM sender._

This is not crisp-clear; it's ambiguous if it means the maximum offset among the bytes that have been sent, or number of bytes that has been sent excluding overlaps (due to retransmissions). Of course, we want to specify the latter; otherwise, you cannot send RESET_STREAM before sending a single byte of data.

Maybe it's worth considering using the term "Maximum Stream Data" instead, that we now use for MAX_STREAM_DATA.

**Comment by martinthomson** [comment]
Happy to look at a PR.  Though "Max[imum] Stream Data" is a limit, so it might be confusing if it were also used to refer to the used amount as well.

**Comment by kazuho** [comment]
> Though "Max[imum] Stream Data" is a limit, so it might be confusing if it were also used to refer to the used amount as well.

Agreed. Maybe something like "Committed Bytes"?

**Comment by mikkelfj** [comment]
Technically QUIC must be able to deliver stream data in-order, but implementations can deliver data out of order, and a sender can data at high offsets way earlier than low offsets (at the risk of being rejected on too many gaps connection error or so).

So, committed bytes or data sent without duplicates does not cover the concept. It is the EndOffset which is of interest.

**Comment by kazuho** [comment]
What @martinthomson says.

Anyways, I've went with "Final Size", because I did not see any reason to change the word "final." I think that just changing "offset" to "size" fixes the issue.

**Comment by marten-seemann** [comment]
> This is not crisp-clear; it's ambiguous if it means the maximum offset among the bytes that have been sent, or number of bytes that has been sent excluding overlaps (due to retransmissions).

I don’t see a difference here. The offset doesn’t change when you retransmit data.

**Comment by kazuho** [comment]
@marten-seemann I am not saying that it changes when you retransmit.

What I am calling confusing is that "final offset" sounds like a term referring to the offset of the last octet within a stream. For a stream of 1 byte long, "final offset" could either mean 0 or 1.

**Comment by marten-seemann** [comment]
Looks like this has nothing to do with retransmissions at all, but just with the definition of "offset". I still like it better than "size" though, because one could reasonably expect the size to change when data is retransmitted, or when sending data with gaps.
Maybe we can define the stream offset as the offset of the next byte that would be sent on the stream would have.

**Comment by kazuho** [comment]
> Looks like this has nothing to do with retransmissions at all, but just with the definition of "offset".

Correct. That's why I stated "excluding overlaps (due to retransmissions)"; maybe that was confusing though.

> Maybe we can define the stream offset as the offset of the next byte that would be sent on the stream would have.

We can do that. However the downside would be that the difference from the terms we define MAX_DATA and MAX_STREAM_DATA becomes bigger. While MAX_STREAM_DATA can be adjusted that way, I am not sure if we can have a similar definition for MAX_DATA. It should also be noted that MAX_STREAMS uses "stream count"; using "byte count" in the definition of flow control credit is in align of that better than using "offset".

**Comment by janaiyengar** [comment]
@kazuho: Ignore my question on the PR, I understand your ambiguity now. I like "offset" better than "size", but unfortunately, the term does not match the definition. Changing the offset to mean the next byte is viable, but it still isn't intuitive. I think size might be the best we've got.

**Comment by mikkelfj** [comment]
Regarding size vs offset, consider the hypothetical stream construct where you send every second 256 byte block. If you don't get a STOP_SENDING you continue with the gaps in order after sending the first 128 blocks. This is interleaved image transmission. Now, is the size the number of blocks sendt sent so far, or the end offset.

As @kazuho says, MAX_STREAM_DATA could be adapted either way, while MAX_DATA is more tricky.

But size is not unambiguous either unless you define it cover all unsent gaps as well.

As for interleaving, a better approach is to sent all even lines first, without gaps, then all uneven lines, which avoids the problem.

**Comment by martinthomson** [comment]
I'm not entirely satisfied with the outcome here.  Is this the MAX_STREAM_DATA text that is problematic?

> The MAX_STREAM_DATA frame (type=0x11) is used in flow control to inform a peer of the maximum amount of data that can be sent on a stream.

Because I don't see a problem there.  As a maximum, it naturally doesn't need to concern itself with gaps.  You just can't send the maximum if you leave gaps.

**Comment by mikkelfj** [comment]
I'd prefer the term `end-offset` because that cannot point to the last byte and it does not say anything about effective payload size, and it works the same for offsets in sparse files.
