### ISSUE TITLE
Make ALPN mandatory in QUIC-via-TLS

### ISSUE THREAD

**Issue by vasilvv** [quicwg/base-drafts#2263]
TCP-based protocols have historically had a lot of issues with protocol confusion, where one protocol could be interpreted as another and that lead to security issues; that lead to various ways of working that issue around, sometimes quite ugly (e.g. WebSockets).

The root issue in TCP or regular UDP is that the application protocol is multiplexed by the port, but the port is never a certain indicator of the protocol.  ALPN, on other hand, is exactly that.  Since there are no b/c concerns in our case, can we make ALPN mandatory in QUIC?  This could save us a lot of security issues down the road.

**Comment by LPardue** [comment]
Is this not already the case? In transport section 7 is says:

> QUIC provides reliable, ordered delivery of the cryptographic handshake data. QUIC packet protection is used to encrypt as much of the handshake protocol as possible. The cryptographic handshake MUST provide the following properties:
> <snip>
> * authenticated negotiation of an application protocol (TLS uses ALPN [RFC7301] for this purpose)

**Comment by marten-seemann** [comment]
This doesn't require the endpoints to actually use the ALPN, does it?

**Comment by LPardue** [comment]
@kazuho I don't see read any optionality, so perhaps this is the ambiguity in the spec. (FWIW optionality of client authentication is explicitly highlighted in that section).

I also share your concerns about mandating ALPN. There still seem to be a few open questions about de-multiplexing different UDP-based protocols when a server listens on the same port - how does ALPN for QUIC mitigate that?

We also have WIP like DATAGRAM frame that are proposing use of TP for enabling the transport-layer feature that could be used by an application to talk arbitrary protocols. 

It seems like ALPN is too rigid a model to support multiple application layers within a single QUIC connection.

**Comment by martinthomson** [comment]
I'm OK with the proposed requirement.  Using ALPN protects you from others.  Not using ALPN might make you ulnerable to weird cross-protocol attacks.

However, I take @kazuho's and @LPardue's points collectively as "if ALPN2 is better, mandating ALPN *specifically* might be bad".  I'm OK with loosening the straps on registrations a little (maybe just for <N character names) there if that's the only real concern.

Would people be OK with "explicit protocol negotiation, such as ALPN"?  Like @kazuho, I don't believe that the text explicitly mandates that the protocol negotiation facility be *used*, so I'd like to add that.

**Comment by LPardue** [comment]
Sgtm

**Comment by mikkelfj** [comment]
I don't know enough about ALPN, but if QUIC doesn't handle inhouse protocols well without bureaucracy, ALPN will get abused. What about future? decentralised approaches e.g. via DNS records?

**Comment by erickinnear** [comment]
I think requiring some form of explicit protocol negotiation would be good. The TLS draft could potentially be a bit more specific about what that looks like, too, but I agree that we don't want to be too restrictive here. 

In other words, what @martinthomson said above sounds good to me.

**Comment by kazuho** [comment]
@martinthomson 
> Would people be OK with "explicit protocol negotiation, such as ALPN"?

SGTM.

@mikkelfj 
> I don't know enough about ALPN, but if QUIC doesn't handle inhouse protocols well without bureaucracy, ALPN will get abused. What about future? decentralised approaches e.g. via DNS records?

I think that the concern will be resolved if we adopt @martinthomson's proposal. You would not be required to send ALPN for example when name resolution with combined protocol negotiation is being used.

**Comment by martinthomson** [comment]
The transport doc currently says:

> The cryptographic handshake MUST provide the following properties:
>
> * authenticated negotiation of an application protocol (TLS uses ALPN {{?RFC7301}} for this purpose)

So I think that is fine.  I've opened #2284 to make the ALPN requirement clearer.

As @kazuho says, if you have other means of agreeing on protocol, then you can avoid ALPN.  For instance, a QUIC version that could only be used with one application protocol would be one way.  In the end, you have to be sure that both client and server agree on what protocol they are talking.  I can see how binding to name resolution would work; though I can also see how it might not work (multiple subjectAltNames, failing to communicate SNI properly, coalescing, etc...).
