### ISSUE TITLE
Encrypt the initial cleartext packets with a deterministic key

### ISSUE THREAD

**Issue by lucas-clemente** [quicwg/base-drafts#227]
This is an alternative to #167: We could just encrypt the cleartext data in the initial handshake packets with a deterministic key (e.g. a mixture of a version-dependent key and the initial packet number). The AEAD used there would have to be fixed in the spec.

The goal would be to make it harder for middleboxes to ossify on stuff in the client hello, e.g. SNI, and to detect initial packets (#203). On the other hand, there's additional computational cost for decrypting packets server-side.

**Comment by ianswett** [comment]
It's worth noting the AEAD would have to be fixed per QUIC version, but not fixed for all time.

**Comment by martinthomson** [comment]
@ianswett, that's only true if we decide to "protect" the version negotiation packet.  Otherwise, it could be version-specific.

**Comment by ianswett** [comment]
Yes, I meant that it should be version-specific, but I said that in a potentially confusing way.

We keep coming back to the theme that the version negotiation packet can't be protected in any way, because we don't want to be stuck with the same protection for all time.

**Comment by martinthomson** [comment]
We decided not to do this (and chose to use FNV-1a) in Chicago.
