### ISSUE TITLE
Varint h3 unidirectional stream types

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2275]
Continuing on from #2253, I realized that the spontaneous push example might be something better supported by a unidirectional stream.  And here, the same arguments about uncoordinated, spontaneous use apply.

**Comment by LPardue** [comment]
That's how my h3 extension worked, reserving 0xTBD.

This would have the effect of changing the current stream type greasing

**Comment by dtikhonov** [comment]
I'll support this if the current stream types in HTTP/3 and QPACK get values of 63 or smaller, making the encodable in a single byte.

**Comment by martinthomson** [comment]
Yes, that would be the only sensible plan, as it was with QUIC frame types.  These are important enough to spec at the beginning, so we take prime positions.  I would also recommend the same registration rules: to 0x3f = Standards Action or IESG Review, to 0x3fff = Specification Required, all other values = Private Use.

**Comment by DavidSchinazi** [comment]
I also support this (with changing existing stream types to be <= 63). I'd also make it a MUST encode as smallest possible encoding.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; despite some unhappiness, we will do this.

**Comment by LPardue** [comment]
One idea for testing is to use a set of grease streams. On connection open the opposite endpoint sends partial varints at various encoding lengths (e.g. write one byte, delay, write another byte, etc). the receiving endpoint should either wait for a complete varint and then proceed (i.e. a resilient endpoint), or it will explode in varint parse failure (a fragile one).

**Comment by martinthomson** [comment]
I plan to send unidirectional stream types in non-minimal varint encodings.  Vive la liberté.

**Comment by LPardue** [comment]
Great opportunity for network-oriented fuzzer

**Comment by martinthomson** [comment]
Fuzzer?  I'm talking a live stack.

**Comment by LPardue** [comment]
Me too. To elaborate my thoughts, some of the test methods presented at EPIQ, like quic tracker, can easily write bytes-on-wire tests that exercise such handling and edge cases
