### ISSUE TITLE
Disallow changes of table size after 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2276]
We currently allow an increased to the dynamic table after 0-RTT.  This is safe, but it complicates things.  @kazuho suggests that we don't allow this.  On balance, I also think we need to simplify and this is a great way to do that.

**Comment by MikeBishop** [comment]
I don't feel strongly about the feature itself, but this would make QPACK differ from the "increase is permitted" pattern we've created.

Assuming that SETTINGS arrives before any acknowledgements do and given that you can't evict unacknowledged entries from the dynamic table anyway, there's no way you could be wrapping under the old value of MaxEntries; increasing the max table size upon receipt of SETTINGS won't change the interpretation of anything you've sent.

The problem scenario seems to be a SETTINGS frame that's delayed past some acknowledgements on the decoder stream -- a bar on evicting anything until SETTINGS is received seems like the simplest fix.

**Comment by martinthomson** [comment]
If we allow 0 to become >0, that isn't fundamentally that different to allowing increases. If you chose 0, then 0-RTT probably isn't that effective either. I am inclined to leave no change as the only option if we go this way.

The alternative is to prohibit wrapping until SETTINGS is received, which I agree is manageable, but a little clumsy. For me, this comes down to whether we think that changing max capacity will be that common. It might be easier to say that changes (increases really) can't be made until you get a full handshake.

We see only slightly more than 1% of our TLS 1.3 connections accepting 0-RTT - or even attempting it. It is early days for 0-RTT, but that suggests that there will be plenty of opportunities - even for a server that prefers 0-RTT - to bump the capacity limit.

**Comment by bencebeky** [comment]
> If we allow 0 to become >0, that isn't fundamentally that different to allowing increases. If you chose 0, then 0-RTT probably isn't that effective either. I am inclined to leave no change as the only option if we go this way.
> 

I would argue that allowing 0 to become >0 is different from allowing increases in a subtle but important way: while the SETTING value is 0, wrapping is automatically disabled.  Therefore I do not see any complexity change from banning all changes to allowing 0 to be increased.  Whether there is any benefit to this in practice is a different, and quite valid, question.

In the end I do not feel strongly about allowing 0 to be increased either way, as long as non-zero values are not allowed to be changed.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; okay with allowing changes only from zero to non-zero, and not increases between two non-zero issues.
