### ISSUE TITLE
HPACK relies on in-order delivery

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#228]
QUIC doesn't make order guarantees between streams.  The options on the table currently are:

- Current (-01) draft puts a sequence number in the frames; HPACK data MUST be handled in order, and will HOL-block.  HPACK is exactly the same as HTTP/2.
- Buck's proposal (draft forthcoming) puts two sequence numbers in the frames and modifies the HPACK encoder to prevent blocking references.  Partially-received HPACK frames must block until fully received.  The new encoder could also be used in HTTP/2, but would require changes to existing code.
- [QPACK](https://tools.ietf.org/html/draft-bishop-quic-http-and-qpack) modifies HPACK to be order-resilient and permit partial frames to be processed, but breaks from the HPACK encoding enough that you'd have at least some separate code paths.

Also agreed to put a "hard-hat warning" in this section of the HTTP draft, to warn readers this is still work-in-progress.

**Comment by MikeBishop** [comment]
There appears to be a hard-hat warning already present.

Per discussion during the lunch break yesterday, Buck and I concluded that all schemes on the table achieve consistency if we can guarantee the following things (I'm not certain we can):

- The HTTP layer will never RST a message control stream
- The QUIC layer will never RST a message control stream with any error code other than REFUSED (i.e. guarantee that no frame was delivered to HTTP)
- The HTTP layer will *always* replay *the same HPACK frame* on a different stream if a REFUSED is encountered **or** the HTTP layer can roll back all effects of the frame when a REFUSED stream is encountered.

Note that the last is very different than the semantics of REFUSED in HTTP/2, where the request MAY be retried, but the same original headers will be recompressed with the state of the table at the time of the retry.

**Comment by martinthomson** [comment]
That last requirement is horrific.  It essentially means that you can't commit any change to the header table without the ability to roll it back.  Maybe we can take a good hard look at stream refusal and whether that could be moved to the HTTP layer somehow.

**Comment by MikeBishop** [comment]
I agree that requirement is horrific.  #274 updates the draft to say you kill the connection if you get painted into this corner.  QPACK has also been updated to remove this requirement.

**Comment by Aron-Schats** [comment]
The introduction to RFC 7541 states that using DEFLATE to compress header fields proved "very effective."  The problem with that approach was that it made the protocol vulnerable to [CRIME](https://en.wikipedia.org/w/index.php?title=CRIME) attack.  I wonder whether QUIC would also be vulnerable to CRIME were it to use DEFLATE instead of HPACK.

The advantages of not having to come up with a specialized compression mechanism are many.  The one closest to my heart is that it would not have to be implemented.

**Comment by martinthomson** [comment]
I also note that control streams are implicitly reset by GOAWAY (CONNECTION_CLOSE too, but that's probably not going to cause any problems).  I conclude that there is a hazard inherent in committing any state to any streams that aren't created immediately after connection establishment.

@Aron-Schats, yes, QUIC would be vulnerable to those sorts of attack if it used DEFLATE.  FWIW, HPACK is also vulnerable to attack, but the researchers who studied it found it was much, much harder to extract any signal from than DEFLATE/GZIP/friends.

**Comment by krasic** [comment]
Was discussing REFUSED here.   Just to throw out an idea that came up which I don't remember seeing elsewhere yet.

What if the last requirement were changed to the following:

* The HTTP layer will *always* replay the *same* HPACK *frame* on a *stream 3* if a REFUSED is encountered.   

Sending again surely isn't optimal, but I think it would be quite simple to implement.
