### ISSUE TITLE
What the maximum of TransportParameters.max_ack_delay?

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2282]
Previously, the maximum was 255 milliseconds, because it was a 8-bit value. But now that the type is varint, the value can express up to 2<sup>62</sup> - 1 milliseconds.

Should we define a reasonable maximum for the value, like what we have for ack_delay_exponent? Capping it so somewhere well below 32-bit range makes sense to me.

I ask this in fear that QUIC stacks might ship with code that fails to handle unreasonably large values.

**Comment by ianswett** [comment]
Capping it to max signed int SGTM.

**Comment by martinthomson** [comment]
How big?  2^16-1, 2^32-1, 2^64-1, 2^30-1?  I'd have said that 2^14-1 would be more than enough here.  16 seconds is a long time to hold an ACK.

**Comment by mikkelfj** [comment]
Is there an attack here? Otherwise why bother - its just one more complexity.

**Comment by kazuho** [comment]
> How big? 2^16-1, 2^32-1, 2^64-1, 2^30-1? I'd have said that 2^14-1 would be more than enough here. 16 seconds is a long time to hold an ACK.

2<sup>32</sup>-1 would be a bit too big for 32-bit timers. OTOH I do not think anybody will be using a 16-bit millisecond-precision timer and therefore 2<sup>14</sup>-1 or  2<sup>16</sup>-1 sounds fine.

**Comment by janaiyengar** [comment]
2^14-1 is good.

Interplanetary QUIC can be pushed to v2.

**Comment by mikkelfj** [comment]
> Interplanetary QUIC can be pushed to v2.

Thanks for making my point.

How about low power devices that are prone to falling asleep?

**Comment by janaiyengar** [comment]
Do they take > 16 seconds to wake up?

**Comment by ianswett** [comment]
Equally importantly, would they ever want to indicate a 16 second ack delay, given the latency implications in the current recovery algorithms?

**Comment by mikkelfj** [comment]
Actually NarrowBand-IoT is just about to be deployed on the danish mobil net, and from what I understand sensor latency is between 1-10s, but I don't know how that translates into network packet processing.

https://en.wikipedia.org/wiki/Narrowband_IoT
