### ISSUE TITLE
Use a quic= parameter for Alt-Svc rather than collide with existing use of v=

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#229]
As discussed at the Tokyo interim, we might choose to use a less generic name for this and to avoid colliding with an existing but incompatible usage.

**Comment by MikeBishop** [comment]
I believe this was agreed to in the interim; @mnot, can I merge the PR and close?

**Comment by mnot** [comment]
Missed the notification, sorry. Sure, go ahead :)
