### ISSUE TITLE
Connection migration attacks may have other side effects

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#2311]
I think the sections that describe connection migration attacks should mention that, when the endpoint detects a spurious migration, it should revert back to using the same CC state and ECN state as before.  Otherwise, an attacker could degrade the performance of a connection.

**Comment by rpaulo** [comment]
Perhaps the tag should be recovery, not transports.

**Comment by ianswett** [comment]
I can see it going either way.  @janaiyengar what do you think?

**Comment by janaiyengar** [comment]
I think the text is going to be in transport, so that's probably the right tag
