### ISSUE TITLE
"PRIORITY frame expresses priority of a stream"

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#2321]
Draft 17 says

> The PRIORITY (type=0x02) frame specifies the client-advised priority of a stream.

If I understand H3 Placeholders correctly, the PRIORITY frame would be used to set their priority too. Perhaps we can say:

`The PRIORITY (type=0x02) frame specifies the client-advised priority of a stream or placeholder`.

**Comment by kazuho** [comment]
To me it seems that the current text is more accurate.

While a PRIORITY frame might use a placeholder to designate the target, what is actually prioritized is the stream that carries the response. The transmission of the placeholder itself is never prioritized.

**Comment by LPardue** [comment]
But the PRIORITY frame contains the Prioritized Element ID field, that allows us to set the priority of Placeholder type.

**Comment by kazuho** [comment]
Yeah, my view is that it is an act of prioritizing a stream by specifying a placeholder ID that maps to the stream. Section 5.3 talks about prioritizing "streams".

**Comment by LPardue** [comment]
That's a good observation, so I'd go further say that IMO the textual description of H3 prioritisation is not completely aligned the protocol mechanisms. Cue @MikeBishop to tell me I am completely off the mark :)

**Comment by LPardue** [comment]
Also, the table of prioritized element types in [section 4.2.3](https://tools.ietf.org/html/draft-ietf-quic-http-17#section-4.2.3) seems to be duplicated

**Comment by dtikhonov** [comment]
The two tables in section 4.2.3 are slightly different.

**Comment by LPardue** [comment]
Correct, I just independently spotted that. Its logical but a bit annoying

**Comment by LPardue** [comment]
#2322 makes some basic edits to section 4.2.3, adding Table captions and linking to them from the paragraph above.

It reworks 5.3 slightly to reframe the language toward describing a tree of abstract elements but still provides concrete examples of request prioritisation.

**Comment by MikeBishop** [comment]
Yeah, there was originally one table and I had to split it to accommodate the current design.  If anyone sees an elegant way to recombine them, I'm fully supportive.

**Comment by LPardue** [comment]
I thought perhaps make the labels multi line and then combine the last two
columns of the second table onto the first. So there would be two colums
containing two sub columns each, plus the left most bits column. I don't
know the Markdown foo to make that happen though.

**Comment by kazuho** [comment]
@LPardue My bad. I was confused. I now understand the issue and think that the PR will provide us the necessary fixes.

**Comment by martinthomson** [comment]
A comment on this text: we should be prioritizing *requests* and maybe *pushes*, not streams.

**Comment by LPardue** [comment]
That's a fair point I'll see if I can incorporate that into the PR
