### ISSUE TITLE
Frame type extensibility

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#233]
The draft currently says:

> Frames of unknown types are ignored.

Which is basically impossible. The only option an endpoint has when it encounters an unknown frame type is to throw out the entire frame or terminate the connection.  We should pick the latter.

**Comment by ianswett** [comment]
You're correct.  That should be removed.

**Comment by martinthomson** [comment]
Note that we also have #194 and #62 that might be resolved in one fell swoop.

**Comment by martinthomson** [comment]
Duplicate of #58.  Well, not that the offending text no longer appears anyway.
