### ISSUE TITLE
Packet number space not explained in handshake text

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2334]
Sect. 7 in transport refers to packer number spaces without any reference to what that might mean. These are only introduced later in sect. 12.3.

Also the text talks about crypto sequence numbers and the text is not very clear about these being different from packet numbers if you haven't been through TLS text.

**Comment by dtikhonov** [comment]
This is still an issue.

I think adding references to [Section 12.3](https://tools.ietf.org/html/draft-ietf-quic-transport-25#section-12.3) where packet number spaces are mentioned (List of Common Terms and Section 7) would be sufficient.

**Comment by ianswett** [comment]
Sounds great, would you be willing to write a PR @dtikhonov

**Comment by MikeBishop** [comment]
Fixed in #3401.
