### ISSUE TITLE
Invariants: Unclarity in short headers

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#2335]
Section 4.2 of the Invariant Short header are not explicit that the Destionation CID follows the first byte: 

"A QUIC packet with a short header includes a Destination Connection ID. The short header does not include the Connection ID Lengths, Source Connection ID, or Version fields."

As see it just says that the destination CID is part of the short header, not where to find it.

**Comment by gloinul** [comment]
Also the length of the DCID in the short header is unclear. With the long header's restriction on both source and destination CID I don't think the CID is of arbitrary length as stated in Section 4.3. I think it is 0 to 18 bytes long as set agreed by the connection.

**Comment by martinthomson** [comment]
Yes, DCID follows the first octet, and we should say that.

As for the length, 0/4-18 is a restriction that we agreed applies only to long headers.  You can - if the QUIC version allows it - negotiate other lengths for connection IDs using other methods.

**Comment by gloinul** [comment]
Ok, the spec is in some sense clear that this can be of arbitary length. However, that this is not required to be consistent with the long header is far from obvious and probably should be explicitly remarked. 

An realization I didn't have before over this design is that a given destination IP address and UDP port that deals with multiple QUIC connections will be foreced to use one commond DCID length across all QUIC connections using that port, otherwise it will have to use prefixes for DCIDs to be able to determine how long the actual DCID field are to enable decoding the header protection. It might have been a misstake to not include an DCID length field.

**Comment by mikkelfj** [comment]
The endpoint can decide on its own DCID length encoding, so that is fine.
