### ISSUE TITLE
HTTP/3: Push stream description diagram is ambiguous

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#2338]
Push streams are special, compared to other unidirectional streams, because they requires some some additional preface (Push ID) before allowing frames.

Reading through section 3.2 again. It seems like a reader could be mislead by the combination of figure 1 and 2.

The usual convention across QUIC and HTTP/3 specs is to define a frame header, then later section define the frame body. The Push stream shown in figure 2 duplicates the stream header field, and I think it could be misread as saying there are two stream headers.

Do others think this is a problem? We could fix the diagram or remove it completely. Or something else entirely.

**Comment by MikeBishop** [comment]
Closing, since no one else has weighed in.
