### ISSUE TITLE
STOP_SENDING on implicitly opened streams is error-prone

### ISSUE THREAD

**Issue by Ralith** [quicwg/base-drafts#2345]
> A stream ID that is used out of order results in all streams of that type with lower-numbered stream IDs also being opened.

> Receiving a STOP_SENDING frame for a locally-initiated stream that is “Ready” or not yet created MUST be treated as a connection error of type STREAM_STATE_ERROR

Streams can easily become open while still in the `Ready` state on the sender if the sender does not necessarily transmit data on streams in exactly the order in which they are allocated. If the receiving application decides to abandon such a stream and sends STOP_SENDING, a connection error results.

If STOP_SENDING is additionally permitted for streams in the `Ready` state which have been implicitly opened by some higher-numbered stream of the same type entering any other state, then implicitly-opened streams can be safely discarded without waiting for a STREAM or RESET_STREAM frame which the application is no longer interested in.

**Comment by marten-seemann** [comment]
I think the text should be
> Receiving a STOP_SENDING frame for a locally-initiated stream that is not yet created MUST be treated as a connection error of type STREAM_STATE_ERROR.

There's value in an endpoint being able to communicate that data from a stream won't be read, even if no data was ever sent on that stream before.

**Comment by MikeBishop** [comment]
Works for me.

**Comment by mikkelfj** [comment]
Please review past discussions on this

#1050
#1797

**Comment by Ralith** [comment]
I did review #1050 before opening this issue:
> Yes, we should prohibit the frame for streams that are not yet created.

It seems to me that the intention here was not to exclude implicitly opened streams, since by most reasonable interpretations they have indeed been created. Perhaps it was overlooked in the removal/restoration churn of implicit opening?

Is there something specific in the #1797 discussion that affects this? Nothing jumps out at me, though the overall thrust of weakening the STOP_SENDING restrictions is certainly related.

**Comment by mikkelfj** [comment]
Please see my response here: https://github.com/quicwg/base-drafts/pull/2352#issuecomment-455762660

I don't object to the intention, I fact I seem to recall finding the original text overlooking this. But we just need to be careful here.

**Comment by mikkelfj** [comment]
The old and new text is based on the senders local created state.
But the peer cannot know the senders local state.

https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#fig-stream-send-states

The fact that a sender created a stream does not mean that the peer has the information yet. It cannot have that information before the highest numbered stream is beyond the READY state.

A peer could legally send STOP_SENDING if it has a out of band information about the senders state even if it is not permitted to send anything else.

The text should instead forbid a peer from sending STOP_SENDING on any stream that is not yet created at its end, meaning it has seen data from the same stream or a higher stream of same kind.

Also the sender should not accept STOP_SENDING unless the local stream state is beyond Ready, or a higher numbered stream of same kind is beyond Ready.

**Comment by mikkelfj** [comment]
What makes this difficult is the remote initiated uni-streams do not have a created state in the same way a bidi-stream has. STOP_SENDING should behave the as if the stream was a bidi stream only be allowed send STOP_SENDING when it can send data on the reverse channel. But it doesn't make sense to say that for uni streams. This leads to assumptions on state at the wrong end of the connection.
