### ISSUE TITLE
Indicate which frames go on which stream types

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2351]
While each frame's description indicates the stream type(s) on which it is allowed, there isn't one unified place to indicate which frames are expected on which streams.  QPACK subdivides the instruction space per stream, which has the nice property that you _can't_ put something on the wrong stream.  While that's overkill for H3 (too dramatic a departure from H2, multiple IANA registries, etc.), having a table to indicate which frames are permitted on which streams would be helpful.

**Comment by LPardue** [comment]
I like the table idea for both. Want a PR?

**Comment by MikeBishop** [comment]
Text always welcome.  🙂
