### ISSUE TITLE
MAX_STREAM_DATA risk unbounded state

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2353]
MAX_STREAM_DATA should not be able to be transmitted on uni-directional until frames have been received on the same or a higher numbered stream of same type. Or until the stream is created for bidi streams.

If this is not the case, a peer can force the initiator to track unbounded state and frames or risk frames being received when an endpoint is not ready to handle them.

See discussion here

https://github.com/quicwg/base-drafts/pull/2352#issuecomment-455767160

**Comment by marten-seemann** [comment]
As I said in that discussion, I don't think there's an unresolved issue here. [We already have text about that](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#frame-max-stream-data):

> An endpoint that receives a MAX_STREAM_DATA frame for a send-only stream it has not opened MUST terminate the connection with error STREAM_STATE_ERROR.

**Comment by mikkelfj** [comment]
Sorry if that is the case. My impression was that you used it as an example to where we did not have such protection, and didn't care. I'll leave it open for now since the term "has not opened" is also a bit vague. Exactly what state must the sender be in for this to count?

**Comment by martinthomson** [comment]
This is a non-issue, with the clarifications in the PRs incoming.  That is, you can only receive MAX_STREAM_DATA for a stream that you have decided to open.  At that point you have decided to track considerably more state than a flow control limit.  We can leave this until #2354 or similar lands.

**Comment by mikkelfj** [comment]
Thanks
