### ISSUE TITLE
Stream Send State Machine is Confusing

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2357]
The send state machine diagram says that if the "Peer Creates Bidirectional Stream" it should transition to READY and then to SEND. The text says ""a bidrectional stream initiated by a peer... enters the 'Ready' state then immediately transitions to the 'Send' state if the receiving part enters the 'Recv' state."

This seems unnecessarily indirect and opaque. I suggest that instead we say that if a host receives STREAM, STREAM_DATA_BLOCKED, RESET_STREAM, MAX_STREAM_DATA, or STOP_SENDING on an unopened, peer-initiated bidirectional stream, it transitions directly to the "Send" state.

If people agree, I'll file a PR.

**Comment by martinduke** [comment]
"or the peer creates a higher-numbered stream"

**Comment by martinthomson** [comment]
The current structure is deliberate (operating from memory here, there are too many PRs to search through), because it captures all the events through the one entry-point.  Don't feel constrained to follow the state machine in your implementation.

**Comment by martinduke** [comment]
Last call for like-minded folks. I'll close this if no one else thinks it is badly presented.

**Comment by martinduke** [comment]
Closing due to lack of interest
