### ISSUE TITLE
0-RTT flow control limits can't be increased

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2360]
In #2344, we discuss what can be sent in 0-RTT.  We realized that while in theory the client should not be accepting 1-RTT packets from the server and then sending 0-RTT, there is nothing to prevent that.

The proposed defense is to prohibit the client from using increased limits (on flow control or streams) that it might have learned from 1-RTT packets.  This ensures that 0-RTT - the parts of the connection that might be replayed - are strictly limited to the initial limits.  Like many other things, we would require the client not to exceed this limits and merely allow the server to enforce that, in case the server was not inclined to do so.

**Comment by martinthomson** [comment]
Tokyo conclusion: we will prohibit the client from sending more than the remembered flow control limits (nothing from the new transport parameters or 1-RTT packets can be used to increase the window).  Some debate about requiring servers to enforce this requirement, decided not to require the generation of a connection error.

**Comment by mnot** [comment]
Discussed in Prague; believe it's a dup of #2458.

**Comment by mnot** [comment]
@martinthomson is the "proposal" here that it's a dup?

**Comment by MikeBishop** [comment]
#2461 closes this issue.
