### ISSUE TITLE
The initial table capacity is zero

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2363]
Which means that encoders have to send a table capacity change instruction as the first instruction they send on the table update stream.  This is never stated clearly in the draft.

It might be possible to assume - incorrectly - that the table capacity is initially set to the maximum value.  We even contemplated this possibility until the complexities of 0-RTT and stream concurrency squashed those dreams.

**Comment by hardie** [comment]
Where do you believe the clarification should occur?  3.2.1?

**Comment by afrind** [comment]
CC: @ekr  who also asked why it's not just set to the maximum, and wants to remove this requirement I think?

**Comment by afrind** [comment]
I added text specifying this to #2330

**Comment by afrind** [comment]
Fixed by #2330
