### ISSUE TITLE
Text banning post-handshake client auth is unclear

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#2367]
draft-tls section 4.4 (Peer Authentication) states:
> A server MUST NOT use post-handshake client authentication (see Section 4.6.2 of [TLS13]).

This sounds like there are security implications, but what they are is unclear. As a reader of the document, this makes me doubt my understanding of the protocol.

If we don't have a good justification for banning this, we shouldn't be banning it.

(This is me reopening #2294 since that was closed for being a question.)

**Comment by martinthomson** [comment]
Is the text unclear, or are you asking to re-enable post-handshake authentication?

**Comment by mikkelfj** [comment]
At least I am curious about the reasoning behind this, not that I am against it.

**Comment by martinthomson** [comment]
@mikkelfj, The best way to understand the rationale is to try to work through how a particular protocol might use this feature.  Read [HTTP/2 secondary certificate authentication](https://httpwg.org/http-extensions/draft-ietf-httpbis-http2-secondary-certs.html), look at the design and discussion and see the sorts of problems it tries to address.  In that case, some of the problems are with server-authentication, which you can safely ignore, but the general class of problems related to concurrency and how that relates to the status of authentication produce a fairly complex design.

Now I might concede that it is possible to build a protocol that uses this TLS feature well, but I would still hold that [exported authenticators](https://tlswg.github.io/tls-exported-authenticator/draft-ietf-tls-exported-authenticator.html) are a far superior design.

**Comment by mikkelfj** [comment]
@martinthomson Thanks for the explantion and pointers. On exported authenticators I guess there is some overlap with OAuth2, Fido, and temporary web service tokens once you get past the handshake.

**Comment by DavidSchinazi** [comment]
@martinthomson if we have a good reason (which it sounds like we do), then this issue tracks adding that reason to the draft.

**Comment by DavidSchinazi** [comment]
Now that @davidben has clearly written this up, perhaps we can resolve this issue by adding a reference to https://tools.ietf.org/html/draft-ietf-httpbis-http2-tls13 in draft-ietf-quic-tls. If that sounds good to the editors I can write a PR.

**Comment by mikkelfj** [comment]
I'd prefer more direct text. You get references to HTTP/2 doc and that in turn references TLS 1.2 with compression rules etc. that needs to be filtered out.

**Comment by janaiyengar** [comment]
@DavidSchinazi : that sounds like a good way forward.
