### ISSUE TITLE
PTO and key update packets

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#2375]
Spec says:

> When crypto packets are in flight, the probe timer (Section 6.2.2) is not active.

Does this mean that during a key update we also disable PTO?  What's the reason for doing so?

**Comment by marten-seemann** [comment]
Crypto packets are [defined as](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#conventions-and-definitions):

> Crypto Packets:
Packets containing CRYPTO data sent in Initial or Handshake packets.

**Comment by rpaulo** [comment]
Okay, that makes more sense.
