### ISSUE TITLE
Crypto Frames/Packets Aren't Blocked by CC

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#2377]
Initial/Handshake packets with CRYPTO frames should not be prevented from being sent my cwnd. I thought we had text to this effect already, but I couldn't find it.

**Comment by siyengar** [comment]
Original transmissions are still blocked by cwnd atm, retransmissions are not blocked on cwnd. Previously this would be done by considering all handshake packets as lost, now in draft 18, you would just retransmit all unacked handshake packets

**Comment by nibanks** [comment]
Why should original transmissions be blocked? On the server side, you have the 3x amplification logic, but I view that as separate from CC. Once the client's IP has been validated, then you have no restrictions. On the client, I don't see any reason to restrict it at all.

**Comment by ianswett** [comment]
In most cases, even with 0-RTT responses, you'd send the crypto data before 1-RTT data, so the crypto data wouldn't be blocked by congestion control.

I think the interesting case is what if the crypto data is large(ie: >IW10)?  It seems like congestion control should probably apply there?

gQUIC did ensure crypto packets were never blocked by congestion control, so I suspect this was in the docs early on, but has subsequently removed.  I suspect it was rarely if ever a practical issue in our implementation, but it is a bit easier to reason about if CRYPTO frames are always sent immediately.

**Comment by ianswett** [comment]
To clarify, there are no exceptions for TLS data in TCP, correct?  If so, I'd suggest we not make exceptions for CRYPTO frames in QUIC unless we have evidence this is an issue.

**Comment by pravb** [comment]
Yes let's not exempt any data from CC, that's just dangerous on painfully slow links that are congested like 2G etc. CRYPTO frames should be counted in CC.

**Comment by nibanks** [comment]
All the arguments sounds reasonable to me. I'm fine with closing the issue.

**Comment by ianswett** [comment]
Before I permanently close this, I want to ask if the existing text needs clarification?
