### ISSUE TITLE
What if a client sends a NEW TOKEN frame?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#2382]
Should the server just ignore it, or is is a protocol violation?

**Comment by ianswett** [comment]
I vote for protocol violation.

**Comment by huitema** [comment]
The spec says nothing...

**Comment by martinthomson** [comment]
Yeah, there's no need to vote, this is just an omission.  A protocol violation (or similar) is what we should mandate.

**Comment by huitema** [comment]
Playing devils' advocate: what about p2p apps? The token says, you can call me back from that address, I will accept it. The client is not saying anything untrue.

**Comment by martinthomson** [comment]
I'll bite.  Yes, a P2P app that used mutual authentication in a way that would allow a former server to associate a token with an attempt to connect to a peer that was previously a client, might be able to use NEW_TOKEN.

That's a little outside our remit.  I'm going to take this as an editorial change on the understanding that a design issue could be opened to allow the asymmetry.

Anyone who is serious about that should also consider the fact that NewSessionTicket in TLS is potentially symmetrical by the same logic.  Which suggests that 0-RTT isn't out of the question either.

**Comment by mikkelfj** [comment]
On p2p there is the potential problem of relating a token to previously stored settings and observables from a previous session. This isn't well defined if the client specifies a new token. So perhaps it is better for each peer to "waste" a single 1-RTT connection the first time in a given direction.
