### ISSUE TITLE
What scheme should be used for HTTP/3?

### ISSUE THREAD

**Issue by masaori335** [quicwg/base-drafts#2384]
During interop session in Tokyo, @dtikhonov pointed out that current HTTP draft (-17) does not say anything about what `:scheme` should be used.

**Comment by MikeBishop** [comment]
This is another variant of #253, actually.  In the current draft, H3 can *only* be used as the target from an Alt-Svc entry.  So the scheme is the scheme of whatever the origin is which gave you an H3 alternate.  That's probably https://, but it could also be http:// (see RFC 8164).
