### ISSUE TITLE
Write up our security target against on-path attack

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2387]

**Comment by mnot** [comment]
@ekr do you have a PR in progress?

**Comment by larseggert** [comment]
Discussed in Montreal, will be a add-on to #2143

**Comment by janaiyengar** [comment]
@mnot @larseggert @LPardue: Editors believe that #2925, which has been merged, addresses this issue. Can we close this issue alongwith #2143 ?

**Comment by martinthomson** [comment]
The proposal here is to do no more than we have already done in #2925.
