### ISSUE TITLE
Articulate principles for definition of error codes

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2388]
We don't really have any real principles that we agree on for deciding what error codes we are describing.

Proposal:

1. if the error carries distinct semantics (like stream rejection in HTTP), then it gets a new error code

2. if the error is frequent or particularly significant, then it gets a new error code

3. otherwise, target a more generic error code that identifies the broad area of the protocol

4. finally, if there is no more specific applicable error code, use PROTOCOL_VIOLATION

**Comment by ianswett** [comment]
#1989 is example of an issue discussed where it would have been useful to have principles.
