### ISSUE TITLE
Be clearer about the purpose of disable_migration

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2389]
The mechanism for disabling migration might be clear, but it isn't clear what problems it addresses.  Some more clarity on that would be useful.

What I understand this to be intended for is server deployments that can't guarantee that packets from a new source address will be routed to the same server instance.

**Comment by janaiyengar** [comment]
Having re-read the minutes from Tokyo, I would re-articulate the problem statement a bit. As you said, disable_migration is an indication from a server that the serving infrastructure cannot handle client address changes. I don't think there's any confusion on this purpose. The pending question IMO is what a server should do if it disables migration and then receives packets on the connection from a different address.

@martinthomson : Do you agree?

**Comment by martinthomson** [comment]
That sounds about right, but I draw two conclusions:

There are some editorial improvements we might consider in light of this analysis.

The pending question about what to do in those scenarios is complex, but the conclusion might just be a better explanation of the sorts of trade-offs that servers work on.  As you imply, that might be editorial as well, but I suspect that we'll uncover ways in which conflicting interpretations of working group participants come to light.

**Comment by janaiyengar** [comment]
Yes, that is what I had in mind as well. We may want to add some text around what a client might expect when it continues sending packets after switching networks to a server that has disable_migration set.

**Comment by igorlord** [comment]
> what a client might expect when it continues sending packets after switching networks to a server that has disable_migration set.

It is my understanding that "disable_migration set" means that packets sourced from a different IP or port are likely to be blackholed.  Hence, the client SHOULD reconnect instead of attempting a connection migration.

As for the servers that specified "disable_migration", they are free to blockhole packets for migrating connections or to honor connection migration (after an ordinary path validation).

**Comment by janaiyengar** [comment]
@igorlord, yes that sounds about right, but we probably want to specify that a server that cannot validate a new source MUST blackhole packets from that source.

**Comment by igorlord** [comment]
Sure, though this is already what falls out from the text. There is already explicit text that source address validation is a MUST.

**Comment by mikkelfj** [comment]
It may also be due to implementations not implementing path migration logic or maintain the necessary state, or servers that wish to use 0-length CIDs.

**Comment by larseggert** [comment]
Discussed in London: to be resolved together with #2342

**Comment by mnot** [comment]
@erickinnear are you working on a PR here?

**Comment by igorlord** [comment]
@erickinnear I am happy to give it a read, if you have a PR ready.  Or I could propose my own if that would not duplicate your work. Let me know.
