### ISSUE TITLE
HTTP/3 uses LTV unlike TLS or QUIC transport

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#2395]
TLS uses TLV and QUIC use TV.  HTTP/2 uses LTV, but HTTP/3 frames are so different from HTTP/2's frames that there's no code reuse benefit of LTV, so making HTTP/3 similar to those two seems like a better choice in my opinion.

Benefits originally cited:
 You can switch on the frame type before you even read a variable-length value
 You can have special-case (negotiated) frame types with no lengths

As discussed in #2235

**Comment by MikeBishop** [comment]
Discussed in Tokyo; no opposition to this change and some support.

**Comment by MikeBishop** [comment]
Fixed by #2235.
