### ISSUE TITLE
"Invariant check" for any inbound LH packet

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#2397]
Consensus on Slack seems to be that a server should set the version field of a Retry packet to v1 (i.e., echo the version from the client Initial ), and that a client should verify that a received Retry packet echoes the version it sent.

However, I cannot find corresponding text in the documents.

**Comment by MikeBishop** [comment]
Well, Retry is a packet type defined in version 1.  If you receive a v2 packet and you don't speak v2, you have no idea what that packet means, even if it superficially *looks* like a Retry packet.

**Comment by MikeBishop** [comment]
Also, from 5.2.1:
> If a client receives a packet that has an unsupported version, it MUST discard that packet.

**Comment by martinthomson** [comment]
Tokyo conclusion: editorial.  You discard packets from versions other than the negotiated version.

**Comment by mikkelfj** [comment]
> So the answer by current spec might be different for a v1+2-capable client which sent a v1 Initial versus a v1-only client.

That's interesting. Probably not the intention, but it would allow a v2 SuperRetry packet to be retrofitted into an otherwise v1 connection.
