### ISSUE TITLE
Sending FINs on empty streams

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#240]
There might be a way in which both sides of a connection could agree (by convention, protocol, or explicit signaling) that a particular stream is closed WITHOUT sending a FIN and spending the extra octets.  This could be used by HTTP to avoid the FIN that a client currently has to send when receiving a server push.

**Comment by martinthomson** [comment]
In #263 it was observed that this is a potentially useful property, allowing an endpoint to limit the number of pushes that it might receive.

**Comment by mikkelfj** [comment]
I have hinted at this elsewhere, but it is perhaps relevant to summarize in the this topic:

This can be handled by stating that a stream is initiated by one end-point and accepted by the other end point. A stream can be initiated as read-only or read/write, and a stream can be accepted as write-only or read/write. In read/write mode both directions must be FIN or RST_STREAM terminated. QUIC can then tear down a connection early and fail if assumptions are broken by when receiving data where none are expected. The application level protocol defines when a stream is initiated and accepted in either mode.

However, it would be simpler with uni-directional streams.

**Comment by MikeBishop** [comment]
I think this is sufficiently addressed by the bidirectional / unidirectional proposals.
