### ISSUE TITLE
loss recovery description mixes variables depending on the packet number space and packet numbers independent of it

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2405]
[Section 6.5.2](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#rfc.section.6.5.2) lists the variables used by the loss recovery algorithm. 
Some of these variables are independent of the packet number space, e.g. `crypto_count`, `*rtt*.`
Other variables apply per packet number space, and we say so explicitly, e.g. `largest_acked_packet`.
Then there are a lot of variables that should be applied per packet number space, but we never say so explicitly, e.g. `sent_packets`, `loss_time`, etc.

The same applies to the pseudo code itself, for example `DetectLostPackets` uses both variables that only apply to one packet number space as well as variables that apply independent of the packet number space.

One way to resolve this would be to index the variables by their respective packet number space.

**Comment by ianswett** [comment]
I'm labeling this editorial, since the pseudocode isn't intended to be normative, but it's also a bit of work to fix, unfortunately.

**Comment by marten-seemann** [comment]
I mostly agree, although there might be some non-editorial parts to it.
For example, if `loss_time` is applied per packet number space, we need to define which one to use in `SetLossDetctionTimer()`. I don't see that we do that anywhere (and we don't describe it in the text either).

**Comment by ianswett** [comment]
Good point.  I'll make this design then.  We can also split this issue in two, but I think it makes sense to try to write a PR and see if there any other changes necessary in the text.
