### ISSUE TITLE
What do we do if special packets are lost

### ISSUE THREAD

**Issue by siyengar** [quicwg/base-drafts#241]
For example if the version negotiation packet is lost, there's no ACK frame for the receiver to signal anything to the sender, we should specify what the loss recovery behavior for version negotiation and other special packets is.

**Comment by MikeBishop** [comment]
I think this is already dealt with -- the server responds with a Version Negotiation packet to *every* packet from the client.  If any packet and its response make it through, the client will know what to do.  If no packet pair makes it through the whole round trip and the client gets no response, the client will assume that its packet was lost and retransmit it.

**Comment by martinthomson** [comment]
There are three cases of interest here: the initial handshake packet from a client (if lost retry on a timer), the version negotiation packet (send in response to every packet that arrives with the wrong version number ...maybe limiting it to those that are plausibly an initial handshake packet), and a public reset (I don't know what the rule might be here, but I suspect there is a timer involved as well).

**Comment by ianswett** [comment]
Agreed on the first two.

Public reset currently is, and I believe should continue to be, like the version negotiation packet.  Send (at most) one per packet received.  Public resets need to be stateless, and timers add state.

**Comment by martinthomson** [comment]
Closing after #474.  I will open an issue regarding the generation of public reset in response to short form headers and other packets that are clearly not starting a handshake.  Those packets that shouldn't arrive should be ignored.
