### ISSUE TITLE
Mandate using a new connection ID on migration

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2413]
In fixing #2145, I discovered that we don't actually mandate this.  It's a privacy requirement that I thought we had previously agreed to, but it appears as though we missed capturing it properly.

**Comment by igorlord** [comment]
I do not think it is wise to prohibit connection migration, when there are no available connection IDs.  This is something that the client is fully capable of deciding for itself -- to migrate using an old connection ID or to reconnect instead.  I would go with MUST use, if there is one available.  Otherwise, privacy-conscious clients SHOULD reconnect.

**Comment by erickinnear** [comment]
It looks like it’s been moved around a lot, but 5.1.2 says

> As discussed in Section 9.5, each connection ID MUST be used on packets sent from only one local address. An endpoint that migrates away from a local address SHOULD retire all connection IDs used on that address once it no longer plans to use that address.

Historically, that’s been under the CID sections, not the migration sections, which made it kind of hard for me to dig up. 

Re the proposed diff: 
>An endpoint that exhausts available connection IDs can only
migrate if the peer chooses to use receive packets with zero-length connection
IDs.

Does that conflict at all with the below text in 5.1?

> An endpoint whose peer has selected a zero-length connection ID MUST continue to use a zero-length connection ID for the lifetime of the connection and MUST NOT send packets from any other local address.

**Comment by martinthomson** [comment]
Thanks for finding that @erickinnear.  That supports the change being editorial-only.

As for the perceived conflict, yeah, the text is not ideal.  I'll find some way to reword it.  Perhaps by observing that you can never run out of zero-length connection IDs.

@igorlord, allowing a peer to exhaust connection IDs to maintain linkability across migrations is an attack that I'd rather we not have.

**Comment by igorlord** [comment]
> allowing a peer to exhaust connection IDs to maintain linkability across migrations is an attack that I'd rather we not have.

I'd not worry about the peer. But I would, indeed, worry about a man-on-a-side exhausting your reserve of connection IDs by pretending to initiate peer migration events.  So this is a valid concern.

Of course, a violation of this MUST is indistinguishable from NAT rebinding/tethering migration and thus is not detectable by the peer.  So this MUST is really just a recommendation.  It is a fine recommendation.

**Comment by DavidSchinazi** [comment]
I agree with @igorlord here. In Tokyo we decided we want to avoid MUSTs that can't be enforced, and in this case it's reasonable for some clients to value migration over non-linkability when they run out of CIDs.

**Comment by mikkelfj** [comment]
> As for the perceived conflict, yeah, the text is not ideal. I'll find some way to reword it. Perhaps by observing that you can never run out of zero-length connection IDs.

The intent is clearly to disallow avoidable migration on empty CIDs. Not running out would suggest keep using it, which is wrong.

Otoh: if it is not required to use a new CID, it makes no sense to forbid empty CID, on migration.

**Comment by MikeBishop** [comment]
The problem with migrating with an empty CID is that the recipient can't identify which connection it should be considered for.  It's going to have to do trial decryption with the keys for all current 0LCID connections on that destination port if it wants to permit that.  (In fact, I'm fairly sure we previously had text that said if you couldn't match a packet to exactly one connection upon receipt, you had to drop it; that seems to have been removed.)  On a NAT rebinding, a server could say that if the IP matches and only the port has changed, it might still match a singular existing connection.

That's only safe if the server is using a unique port for each connection, which seems unlikely.

**Comment by mikkelfj** [comment]
@MikeBishop Good point.

**Comment by martinthomson** [comment]
Yes, I think that this was a mistake on my part.  Clearly, if there is no connection ID on outward-bound packets, migration is generally inadvisable.  I'll update the PR.

**Comment by martinthomson** [comment]
Superseded by #2414, which does more, but does it better.

**Comment by janaiyengar** [comment]
We ought to leave this issue open, and let it be closed by PR #2414.
