### ISSUE TITLE
Error code for indicating that a HTTP response is aborted

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2416]
When a reverse proxy forwards a HTTP response to the client, sometimes it sees the upstream server terminate the response early. For example, a HTTP/1.1 connection being closed prior to transmitting number of bytes specified by the `content-length` field. Or a chunked response being closed abruptly.

The only way of delegating such a condition to the client in HTTP/2 was to send a RST_STREAM frame with `PROTOCOL_ERROR`. However, use of the error code is awkward in this case, considering the fact that the error did not happen within the communication between the endpoints using the particular HTTP/2 connection.

I think it makes sense to have an error code that better designates the case.

One way to address the issue in H3 would be to change `HTTP_REQUEST_CANCELLED` to `HTTP_MESSAGE_CANCELLED`, and let the server use the error code (as an argument of the RESET_STREAM frame) to indicate that the response has been "cancelled".

Originally proposed in 
https://github.com/quicwg/base-drafts/issues/2410#issuecomment-460330192.

**Comment by mikkelfj** [comment]
What if you do not want to admit to being a proxy? (who does?)

**Comment by kazuho** [comment]
HTTP_MESSAGE_CANCELLED would simply mean that the transfer of the response is cancelled, regardless of the server being an origin or a reverse proxy.

**Comment by martinthomson** [comment]
I can get behind this.  As long as we're not looking for a byte-by-byte reproduction of the bytes the intermediary received (as was once requested and rejected, I think at the Seattle interim), then it makes sense to signal that the message was killed.

**Comment by MikeBishop** [comment]
This is basically an expansion of the CANCELLED/REJECTED codes to allow a server to do either.  WFM.

**Comment by kazuho** [comment]
@MikeBishop Yes. And thank you for the PR.
