### ISSUE TITLE
HTTP/3 TLV length description is no longer precise

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2429]
Now that length is no longer first, I think the length description should be updated to clarify what it includes: it says it does not include the type, but the type precedes it. Does it include the length itself? Many designs mix do this, and some designs have both styles in the same message.

**Comment by MikeBishop** [comment]
This may be OBE.  Looking at the current version, it says:

```
A frame includes the following fields:

  Type:
  : A variable-length integer that identifies the frame type.

  Length:
  : A variable-length integer that describes the length of the Frame Payload.

  Frame Payload:
  : A payload, the semantics of which are determined by the Type field.
```

This appears to be fairly precise -- the Length field describes the length of the Frame Payload, which is a specified region of the frame.  I'm not inclined to add further disclaimers around what "length" means unless others feel it's unclear.
