### ISSUE TITLE
Reserved versions will "probably" never represent a real protocol?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2430]
This seems unnecessarily wishy-washy.  Either they're reserved by definition, and therefore **will never** represent a real protocol, or they're available for use.

We should remove the "probably" unless there's a good reason to keep it that I'm missing.

**Comment by martinthomson** [comment]
Use of that word was entirely intentional.  If there is certainty about this status, then it creates a temptation to apply certain optimizations that could be disruptive.  What if middleboxes cached Version Negotiation packets from servers and helpfully provided responses to greased connection attempts?

**Comment by MikeBishop** [comment]
We fear that someone might ossify if they discover that these are *definitely* not real protocol versions.  On the other hand, the thing that breaks is use of these as real protocol versions, which I don't believe we're trying to achieve.  If the middlebox is generating *accurate* VN packets, that seems entirely reasonable (and indistinguishable from actual VN packets).  If they're generating inaccurate VN packets, then our anti-downgrade protections that we've decided to implement RSN will break.

On the other hand, if these ever are real protocol versions, then a junk grease packet using the reserved version will fail to parse as a valid Initial and will just fail rather than eliciting a VN response.

This seems like an impossible battle to win, and a lot of subtlety to expect of middlebox vendors.  Write what we mean and move on.
