### ISSUE TITLE
Change Idle Timeout Units of Milliseconds

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#2453]
Currently, the t[ransport parameter for specifying Idle Timeout](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.18.1) is in units of seconds. This seems to be too restrictive and not very future proof. Additionally, from an API perspective, most other timers are settable on the millisecond scale, so it creates a kind of ugly discrepancy between all the different timers settable by the app if just one of them has units of seconds.

I propose we change the units from seconds to milliseconds. The change both for implementations and spec should be minimal, and it makes things (timers) a little more consistent.

**Comment by ianswett** [comment]
This seems sensible to me both for consistency and I can imagine cases when one would want to specify a fraction(ie: 1/2 of a second).

**Comment by pravb** [comment]
Agreed. A second is an eternity for a intra-datacenter connection for example. For future proofing all time units should be at least msec IMO.

**Comment by rpaulo** [comment]
Don't we want to specify a minimum value now?

**Comment by nibanks** [comment]
No, I don't think so. Even before, if you had a greater than 1 sec RTT (somehow...) if you set an idle timeout of 1 second it would cause you problems. I think bottom line you be smart about your idle timeout values. If you set too small a value you can unnecessarily kill your own connection.

**Comment by kazuho** [comment]
As @nibanks says, actual idle timeout depends on RTT, and that’s what we have adopted in #2404.

**Comment by janaiyengar** [comment]
This SGTM.

**Comment by DavidSchinazi** [comment]
I support this

**Comment by larseggert** [comment]
I think this has rough consensus. Tagging as such and reassigning.
