### ISSUE TITLE
Client MUST use 1-RTT packets if it reads 1-RTT packets

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2458]
I am not sure if this is accurate.

IIUC their is nothing that mandates the client to switch to using 1-RTT when it receives ServerFinished. In fact, on a lossy network, a client would benefit from using 0-RTT packets until it receives an ACK for ClientFinished. In such case, it would be natural to observe these frames in a 0-RTT packet.

I think we should either forbid them or clarify that there are allowed, instead of suggesting (IMO incorrectly) that it’s impossible.

_Originally posted by @kazuho in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MjQ2MTcyNjUx/pull_requests/unread_timeline_

**Comment by martinthomson** [comment]
To be clear, this was in reference to text that mentioned that certain frames couldn't be sent in 0-RTT.  That would only be true if we made this a requirement.

**Comment by MikeBishop** [comment]
This actually is already addressed in the TLS draft, as @martinthomson pointed out in another thread:  [TLS 4.9](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#rfc.section.4.9), "Though an endpoint might retain older keys, new data MUST be sent at the highest
  currently-available encryption level."

If you have 1-RTT keys, you MUST use them.  There's currently no server verification that you do so, however.

**Comment by ianswett** [comment]
I think this should be stated in transport as well as TLS, along with a statement that a server MAY/SHOULD/MUST ignore 0RTT packets that have higher packet numbers than the first received 1RTT packet.  The first is editorial I believe, the latter is borderline design.

If we decided it was valid to close the connection if a 0RTT packet was received with a higher packet number than 1RTT, then that's definitely not editorial, but I think it may be a good way to enforce proper behavior.

**Comment by kazuho** [comment]
@ianswett 
> I think this should be stated in transport as well as TLS

Agreed.

> along with a statement that a server MAY/SHOULD/MUST ignore 0RTT packets that have higher packet numbers than the first received 1RTT packet.

I think that this should be a MAY/SHOULD close the connection with PROTOCOL_VIOLATION rather than "ignore", because that aligns the handling with how we agreed to handle other misuse of 0-RTT packets (see 
https://github.com/quicwg/base-drafts/issues/2360#issuecomment-459171200).

**Comment by huitema** [comment]
@martinthomson said it right at the mike: this is a key update scenario, from 0-RTT to 1-RTT key. Treat it the same way as peer continuing using old key after key update.

**Comment by huitema** [comment]
I think the only verifiable requirement is "must not ack 1RTT packet in 0RTT packet". The server can definitely detect that, and send a connection close with reason PROTOCOL VIOLATION when it happens. This would effectively force the client to switch to 1RTT soon.

**Comment by MikeBishop** [comment]
@huitema, exceeding the initial flow control / max streams from the remembered TP's is also detectable.

**Comment by huitema** [comment]
@MikeBishop detection with flow control would require special case code in stream processing, as in "check against the current window but if 0-RTT check against the initial window". Could be done, but that would be another wart. Also, in many cases the 0-RTT data sent is well below the initial flow control window, so it will not be a very efficient test.

**Comment by kazuho** [comment]
@huitema 
> detection with flow control would require special case code in stream processing, as in "check against the current window but if 0-RTT check against the initial window". Could be done, but that would be another wart.

It's actually something that can be implemented in a clear and concise way. The only thing you need to have are objects representing limits for each type of packets. When processing 0-RTT packets, the logic would refer to the limits declared by TP of the previous connection. When processing 1-RTT packets, the logic would refer to the limits declared by current TP and the max frames.
