### ISSUE TITLE
SPA ad Infinitum

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2462]
As far as I can tell, there is currently no protection against infinite loops in Server Preferred Address redirection.

In comparison, Retry only permits one hop.

A server should of course not send its own address, but it might not aways know it.
It is also possible for two servers to prefer each other.
A client should not keep shopping for a better connection endlessly.

**Comment by ianswett** [comment]
Server's preferred address does not cause a new handshake.  It merely changes the server IP the client is communicating with for the existing handshake.

**Comment by mikkelfj** [comment]
Uhh, so I am mixing up Retry with SPA.

**Comment by marten-seemann** [comment]
How can there be a loop? SPA is only used to tell the client to migrate, not to initiate a new connection.
