### ISSUE TITLE
Suggestion that Retry might not change CID

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2465]
In 17.2.3, the transport draft says:

> Receiving a Retry packet, especially a Retry that changes the connection ID used for subsequent packets, indicates a strong possibility that 0-RTT packets could be lost.

However, in 17.2.5:

> The server includes a connection ID of its choice in the Source Connection ID field. This value MUST not be equal to the Destination Connection ID field of the packet sent by the client.

The subordinate clause in the first is unnecessary, as that statement is true of all Retry packets.  In the second, should that be "MUST NOT" rather than "MUST not"?

**Comment by martinthomson** [comment]
OBE
