### ISSUE TITLE
PTO calculation

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#2472]
Should the following line be rto calculation from RFC 6298?

`PTO = max(smoothed_rtt + 4*rttvar + max_ack_delay, kGranularity)`

in that case it should be:

`PTO = smoothed_rtt + max(4*rttvar, kGranularity) + max_ack_delay`

do I miss something?

**Comment by ianswett** [comment]
I think this was a small error in the PR that moved from TLP + RTO -> PTO, but @janaiyengar may have had a reason to make this change I'm not aware of.

If not, I'd suggest we change the draft to align with RFC 6298.

**Comment by janaiyengar** [comment]
Thanks for catching this @ddragana -- yes, this was unintentional. I've sent #2480.
