### ISSUE TITLE
Specify what occurs when the maximum Stream Id exceeds 2^62 - 1 in MAX_STREAMS

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#2487]
Currently, stream IDs are as high as 2^62-1.  The MAX_STREAMS frame specifies a limit as a varint that has a max value of 2^62-1 that translates to a Stream ID of 4 * max_streams + initial_stream_id_for_type.  This is larger than the max expressible stream ID, so we should specify what happens in this case.

I'm suggesting that we allow all streams to be opened and MUST NOT close the connection in PR #2486

**Comment by mikkelfj** [comment]
Good idea.

**Comment by janaiyengar** [comment]
I don't have a strong opinion, but this seems like a bug at the peer. I would be inclined to specify that an endpoint MUST NOT advertise max streams that are too large, and close the connection (with PROTOCOL_VIOLATION) if a value is received that is too large.

**Comment by marten-seemann** [comment]
I'd also lean towards closing the connection (probably with a TRANSPORT_PARAMETER_ERROR, not a PROTOCOL_VIOLATION though).

Interestingly, we have the following definition for packet numbers
> Packet numbers are integers in the range 0 to 2^62-1

but no such thing for stream IDs, although this is implied by the way we encode them.

**Comment by ianswett** [comment]
I'm happy to close the connection as well, as long as the behavior is well-defined.

**Comment by ianswett** [comment]
On PR #2499, @marten-seemann noted that this logic should apply to the equivalent transport param as well.
