### ISSUE TITLE
Provide address validation token in Alt-Svc

### ISSUE THREAD

**Issue by ghedo** [quicwg/base-drafts#2488]
Similarly to how the server can provide tokens for future connections with the `NEW_TOKEN` frame, it could be useful to be able to do the same with Alt-Svc. This way the server can decide to be more aggressive about requiring a token for new connections while avoiding the additional round-trip caused by `Retry` when a client has never connected over QUIC before.

**Comment by LPardue** [comment]
One might choose to do this with a new Alt-Svc parameter. Theres some interesting interrelation with the ma and persist parameters that might happen. 

If I understand correctly, a server would need to generate a unique token per client. Presently, as far as I've observed, Alt-Svc is used a bit more as a blanket hint. I don't think there is anything preventing it from being more targeted but there are challenges.

**Comment by MikeBishop** [comment]
`persist=false` seems to cover it quite nicely; of course, to get the "right" behavior, you'd have to include two entries -- one non-persistent and with a token, the other persistent.  It would be simpler to define that, even on a persistent entry, the token can only be used on the same network where it was issued.

I'm not convinced this needs to be in the core spec, though the VN hint technically doesn't need to be either.

**Comment by LPardue** [comment]
When you say VN, do you mean the Alt-Svc version hint in the HTTP/3 document? (Just for clarification purposes)

**Comment by MikeBishop** [comment]
Yes -- the hint as to which QUIC versions the server intends to support.

**Comment by martinthomson** [comment]
Discussed in London; tentative conclusion was to close with no change (i.e., quicv2).

**Comment by MikeBishop** [comment]
HTTP isn't under new process yet, which means we can just close without a consensus call.

**Comment by MikeBishop** [comment]
Also, note that consensus in London was that @lnicco can write an Alt-Svc extension for this if he'd like to experiment.

**Comment by LPardue** [comment]
I think you mean @ghedo
