### ISSUE TITLE
Why InitialWindow = 14600?

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2491]
In the Recovery Draft pseudocode section:

> kInitialWindow: : Default limit on the initial amount of data in flight, in bytes. Taken from {{?RFC6928}}. The RECOMMENDED value is the minimum of 10 * kMaxDatagramSize and max(2* kMaxDatagramSize, 14600)).

Why 14600? This looks like 10 * MSS, but for UDP this should be 14720. It would lead to neat MSS multiples were that code ever executed.

**Comment by ianswett** [comment]
This was taken from RFC6928: https://tools.ietf.org/html/rfc6928

**Comment by martinduke** [comment]
Well, yes, but that is for TCP and I'm arguing that 14720 makes a lot more sense for QUIC.

**Comment by ianswett** [comment]
That seems reasonable, I was only trying to add an explanation of how we ended up with 14600.

**Comment by ghedo** [comment]
@martinduke Did you mean 14520? 1472 as MSS seems too big if you assume MTU of 1500.

**Comment by martinduke** [comment]
@ghedo I was thinking IPv4. Perhaps we should make the value dependent on the IP version.

**Comment by ianswett** [comment]
I believe the goal is no more than 10 1500 byte packets, so it could be IP version dependent.

But TCP doesn't bother making it IP version dependent, so I'm leaning towards specifying 14720 with the rationale that TCP has 20 bytes of overhead vs UDP's 8 bytes.

**Comment by ianswett** [comment]
PR #2494 sent.
