### ISSUE TITLE
Error Code when SETTINGS exceeds maximum

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2498]
The HTTP draft doesn't have any SETTINGS parameters with a maximum value, but QPACK does.  I don't see any text in hpack sec. 4.2.5.1 or qpack sec 5 that explains what to do if we receive a parameter that exceeds the maximum parameter.

**Comment by LPardue** [comment]
Good observation. This is another case where MALFORMED_FRAME is not appropriate. 

I might reset the peer-initiated stream with HTTP_LIMIT_EXCEEDED, which would prompt the other end to close the connection HTTP_CLOSED_CRITICAL_STREAM.

An alternative is just CONNECTION_CLOSE with HTTP_GENERAL_PROTOCOL_ERROR. 

... or We could invoke the YAEC label :)

Whatever we decide, I think it needs documenting.

**Comment by MikeBishop** [comment]
Technically, you can't reset a peer-initiated stream, just STOP_SENDING.

**Comment by LPardue** [comment]
That's an astute observation and something I've missed. Perhaps I'm missing it but the spec doesn't say how to handle a STOP_SENDING received on a control stream. Should this peer issue a RESET_STREAM in response (causing the other peer to blow up) or should it just close the connection itself?

**Comment by kazuho** [comment]
My understanding is that STOP_SENDING is an act of closing a stream rather than an advisory signal.
Based on that, I'd argue that receipt of STOP_SENDING on a critical stream should trigger a HTTP_CLOSED_CRITICAL_STREAM connection-level error.

**Comment by mikkelfj** [comment]
I don’t think that STOP_SENDING terminates a stream per se, but an application can choose to interpret it as such, so HTTP/3 can make that call.

**Comment by kazuho** [comment]
To be precise, STOP_SENDING "_typically indicates that the receiving application is no longer reading data it receives from the stream_, but it is not a guarantee that incoming data will be ignored" ([transport daft section 3.5](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.3.5)).

Because there is a chance of it indicating that the peer is no longer reading, STOP_SENDING received on a critical stream ought to trigger a HTTP_CLOSED_CRITICAL_STREAM error.

**Comment by LPardue** [comment]
I'd be happy with MUST close connection in response

**Comment by MikeBishop** [comment]
Discussed in London; generalize to a "SETTINGS error" which covers multiple ways you can screw up the SETTINGS frame.  This is one of them.

**Comment by MikeBishop** [comment]
Resolved by #2766 and #2814.
