### ISSUE TITLE
STOP_SENDING on Critical Stream

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2509]
> Perhaps I'm missing it but the spec doesn't say how to handle a STOP_SENDING received on a control stream. Should this peer issue a RESET_STREAM in response (causing the other peer to blow up) or should it just close the connection itself?

_Originally posted by @LPardue in https://github.com/quicwg/base-drafts/issues/2498#issuecomment-470316968_

There are three reasonable places to blow up:
- When you decide to stop reading a critical stream (i.e. when STOP_SENDING is sent)
- When you discover the peer has stopped reading a critical stream (i.e. when STOP_SENDING is received)
- When you discover the peer has closed a critical stream (when RESET_STREAM or FIN is received)

My inclination would be to advise against FIN/S_S/R_S on a critical stream and mandate connection termination on receipt of any of them.

**Comment by RyanAtGoogle** [comment]
On Fri, Mar 8, 2019 at 4:43 PM Mike Bishop <notifications@github.com> wrote:

> Perhaps I'm missing it but the spec doesn't say how to handle a
> STOP_SENDING received on a control stream. Should this peer issue a
> RESET_STREAM in response (causing the other peer to blow up) or should it
> just close the connection itself?
>
> *Originally posted by @LPardue <https://github.com/LPardue> in #2498
> (comment)
> <https://github.com/quicwg/base-drafts/issues/2498#issuecomment-470316968>*
>
> There are three reasonable places to blow up:
>
>    - When you decide to stop reading a critical stream (i.e. when
>    STOP_SENDING is sent)
>    - When you discover the peer has stopped reading a critical stream
>    (i.e. when STOP_SENDING is received)
>    - When you discover the peer has closed a critical stream (when
>    RESET_STREAM or FIN is received)
>
> My inclination would be to advise against FIN/S_S/R_S on a critical stream
> and mandate connection termination on receipt of any of them.
>
Completely agree. This seems like the simplest and most obvious solution.

**Comment by LPardue** [comment]
SGTM mike

**Comment by martinduke** [comment]
Note that this PR does NOT address #2498, just a comment that came up there.

**Comment by MikeBishop** [comment]
Re-reading this, I think the existing text is pretty good; it just needs a little reframing.  The existing requirement is to error out "If the control stream is closed at any point," without reference to whether it was closed because the peer send a FIN/RESET on their control stream or you obeyed a STOP_SENDING on yours.

I think I'll add an existing requirement not to request closure of a control stream; do you think we need more elucidation here?
