### ISSUE TITLE
Remove size optimization for Initial packets

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2522]
Initial packets need to be in 1200 byte datagrams for DoS amplification reasons. We have an exception for the case where an ACK for a Handshake packet has been received from the peer.  In that case, we remove the requirement to pad.

That condition is extraordinarily obscure, especially if we are suggesting that endpoints not send any more Initial packets once they have Handshake keys.  Removing this text is the right answer.

**Comment by janaiyengar** [comment]
+1 to the proposed resolution.
