### ISSUE TITLE
Are transport parameters mandatory?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2528]
All of them have defaults.

**Comment by janaiyengar** [comment]
If you mean "Is sending TP mandatory", I don't think so. An endpoint that doesn't receive a TP assumes the default value. An endpoint that uses a default value does not need to advertise it.

**Comment by martinthomson** [comment]
The issue could have been more precisely worded.  The question was about the entire QUIC transport parameters extension.  Individual parameters are still clearly optional.

We should be very crisp about that.  Up until -18, this was mandatory, but we don't need the version parameters any more.

**Comment by DavidSchinazi** [comment]
One nice property of making the TLS transport parameters extensions mandatory is that it helps mitigate cross-protocol attacks: QUIC servers can abort the connection if it's missing and TLS over TCP servers can abort if the extension is present.

**Comment by kazuho** [comment]
I think we can call the entire extension as an option.

As to @DavidSchinazi's point, I'm not sure if it helps in practice. TLS 1.3 stacks that run on top of TCP does not have (and it's doubtful if all of them would have) the capability to detect and raise an error when it sees the QUIC TP extension.

**Comment by martinthomson** [comment]
Our defense for cross-protocol attacks is ALPN.  Then key separation, and probably other things.  While layers of defense is generally a good idea, that isn't a necessary layer.

**Comment by DavidSchinazi** [comment]
I agree with @kazuho's and @martinthomson's points. This was more of a belt-and-suspenders approach. That said, I still think every single deployment will actually send transport parameters, therefore requiring the extension to be present sounds simpler to implement. But I don't feel too strongly about this.

**Comment by martinthomson** [comment]
The question arose when we realized that you can have a perfectly functional stack with the defaults. And it was non- trivial sending any. 

However, if the client doesn't send any, it prevents the server from sending any. That seems bad.

**Comment by DavidSchinazi** [comment]
> However, if the client doesn't send any, it prevents the server from sending any. That seems bad.

That argument is more compelling than mine.

**Comment by mnot** [comment]
Discussed in Prague; no pushback against making them mandatory.

**Comment by mnot** [comment]
@ekr can you make that into a PR?

**Comment by ianswett** [comment]
There already is a PR, it just wasn't tagged properly as closing this issue.
