### ISSUE TITLE
spin bit intro: information can't be used "for" techniques

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#2531]
The [spin bit draft](https://tools.ietf.org/html/draft-ietf-quic-spin-exp-01) states:

> QUIC's wire image [...] does not expose any information that can be used for passive latency measurement techniques that rely on this information

The wording "information that can be used for [...] measurement techniques" can stand improvement.  The information is either

1. used *for* measurement; or
1. used *by* techniques.

**Comment by britram** [comment]
thanks; let's make this change in #2364 (paging @ihlar)

**Comment by ihlar** [comment]
> thanks; let's make this change in #2364 (paging @ihlar)
Agree, will make the change.

**Comment by mnot** [comment]
Is this still an issue in `transport`? #2364 is very messy...

**Comment by martinthomson** [comment]
Yep.  OBE.
