### ISSUE TITLE
Handling of PRIORITY Frame Empty bits

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2533]
PR #2501 kicked up a bit more controversy than expected, so I'm opening an issue. Currently he Empty bits it the PRIORITY frame MUST be zero and MUST be ignored by the receiver.

In most other areas, we're killing connections for this kind of violation. Then again, HTTP/3 is a different protocol from QUIC.

What do people think?

**Comment by ianswett** [comment]
Closing the connection SGTM.

**Comment by LPardue** [comment]
I can live with must be zero and connection error if not.

**Comment by LPardue** [comment]
Which means drop requirement to ignore them.

**Comment by dtikhonov** [comment]
I'd keep the requirement to ignore them on receipt -- why require more unnecessary checking?

**Comment by LPardue** [comment]
That works, but then state that their value is completely meaningless and should not be interpreted as anything

**Comment by dtikhonov** [comment]
@LPardue, you want to add verbiage in addition to this?

```

**Comment by LPardue** [comment]
Looking back to HTTP/2, it had this to say about in-frame PADDING in DATA frames.

> Padding octets that contain no application semantic value.
      Padding octets MUST be set to zero when sending.  A receiver is
      not obligated to verify padding but MAY treat non-zero padding as
      a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

https://tools.ietf.org/html/rfc7540#section-6.1

**Comment by martinthomson** [comment]
That is probably OK here as well.  Though the need is less acute for a 4 bit field.  Padding in DATA can be arbitrarily large.

Either way, the hope would be that at least a few implementations check and enforce.

**Comment by MikeBishop** [comment]
Closed by #2501.
