### ISSUE TITLE
ECN text disables ECN too aggressively

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2534]
Section 13.3.2 "ECN Verification"

> If an endpoint sets ECT codepoints on outgoing IP packets and encounters a retransmission timeout due to the absence of acknowledgments from the peer (see {{QUIC-RECOVERY}}), or if an endpoint has reason to believe that an element on the network path might be corrupting ECN codepoints, the endpoint MAY cease setting ECT codepoints...

Although I understand the intent here, retransmission timeouts, as a term, don't exist anymore in QUIC except during handshakes.

Disabling ECN after any PTO firing seems a bit extreme, so I'd like to see a better recommendation here, which covers both handshakes and short headers.

**Comment by ianswett** [comment]
Fixing the naming(retransmission timeout to probe timeout) is trivial, but I'm not sure what to recommend here for when to disable ECN.  Also, probe timeouts don't occur until the handshake is complete, is that a problem?

One idea that's somewhat in keeping with RFC3168 would be to disable ECN on crypto handshake timeouts and probe timeouts, and if the un-marked packets get through and the marked do not, disable ECN.  But even that is subject to random loss and I believe is likely to spuriously trigger.  We could disable ECN temporarily on only the second timeout, to reduce the chance of spurious disabling?

RFC8311(https://tools.ietf.org/html/rfc8311#section-4.3) says we can do something different from 3168 if we document it, but doesn't specify what.

Is there some useful RFC I can cite that I haven't found, or are we on our own in designing a mechanism here?

**Comment by ianswett** [comment]
@larseggert I reclassified this as design, because it's not just the name update.  If we decide to just fix the name, then we can change it back.  Correct me if I'm wrong.

**Comment by mikkelfj** [comment]
How about probing ECN on even packet numbers for the first N packets before making a decision, where N is tunable.

**Comment by mirjak** [comment]
I believe what the text was actually meant to say was that if you set the ECT code point and you loose ALL packet which the code point set, you MAY disable it.

**Comment by janaiyengar** [comment]
What @mirjak says makes sense. We don't need to document a full algorithm here, but the proposed text works for me.

**Comment by gloinul** [comment]
So the intention here is that if you hit an ECN blackhole that you disable ECT marking the sent packet in a timely fashion to minimize the impact on connection establishment. And I don't think a single sender behavior is necessary.

**Comment by martinthomson** [comment]
@janaiyengar mentioned that this should be triggered on persistent congestion.

**Comment by larseggert** [comment]
Agreed in London for @janaiyengar to write a PR.

**Comment by gorryfair** [comment]
Just to clarify: RFC8311 permits other uses that are specified by an RFC: i.e., currently this is RFC8511, and the expected RFC to be published by the L4S work items in TSVWG (expecting to be Lc'ed later in 2019).

**Comment by gorryfair** [comment]
There seems two things:

• What to do during handshake (maybe is described in transport)

• Disabling after handshake which I think is in the loss/recovery draft, rather than transport? - I thought I heard Jana argue that this reaction depends on the loss/marking observations on the path - which I would agree with.

**Comment by mnot** [comment]
@janaiyengar is that ready for a consensus call?

**Comment by ianswett** [comment]
There are a lot of open comments on the PR, so I think not yet?

**Comment by janaiyengar** [comment]
@mnot: Not yet, the PR needs some work.
