### ISSUE TITLE
What happens if STREAM offset exceeds 2^62 -1

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2538]
Sec 19.8 says:
The first byte in the stream has an offset of 0.  The largest offset
   delivered on a stream - the sum of the offset and data length - MUST
   be less than 2^62.

It certainly possible to express a STREAM frame that violates this rule. What action should we take?

**Comment by martinthomson** [comment]
I don't know if we ever wrote this down, but I think that we might say if you catch a peer violating the spec, then you can send an error of any type you like.  But for this case, PROTOCOL_VIOLATION is entirely appropriate (as with many others of this sort).

**Comment by mikkelfj** [comment]
Not just offset, but offset + content size of stream frame, otherwise there is no fixed limit on stream sizes, which is unfortunate.
