### ISSUE TITLE
NEW_TOKEN token and encryption

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2543]
My understanding is that tokens provided by NEW_TOKEN frames should not leak information that allows observers correlate the newly established connection with the previous connection. Such information include the time when the token was issued, RTT, server name (when SNI is not used or Encrypted SNI is used), or even the size of the token.

However, the draft seems to be vague about the requirement. I think it might be worth clarifying the principle in the draft.

"a token SHOULD include an expiration time" (section 8.1.2) - I think we should change this to "a token SHOULD be associated an expiration time", considering the fact that we are talking about "stateful" design (stateless design is mentioned briefly in one of the following paragraphs). In a stateful design, an opaque identifier is the only thing that a server should be allowed to send.

"In a stateless design, a server can use encrypted and authenticated tokens to pass information to clients" - I think we might prefer using "SHOULD" rather than "can".

**Comment by dtikhonov** [comment]
I think the current text is fine:

```
   Unlike the token that is created for a Retry packet, there might be
   some time between when the token is created and when the token is
   subsequently used.  Thus, a token SHOULD include an expiration time.
   The server MAY include either an explicit expiration time or an
   issued timestamp and dynamically calculate the expiration time.  It
   is also unlikely that the client port number is the same on two
   different connections; validating the port is therefore unlikely to
   be successful.
```

"include" translates to "put into the token and encrypt" in my mind.  Reading that a token is "associated" with an expiration time would give me pause.

**Comment by kazuho** [comment]
> "include" translates to "put into the token and encrypt"

Would you mind clarifying where the "and encrypt" comes from? My point is that that is the way it should be, however the text does not seem to clarify that.

**Comment by dtikhonov** [comment]
I don't recall how I arrived at it -- perhaps some common sense. 😄  Now that I have implemented it, it seems only natural.

Perhaps we should simply add "and encrypt" to the text instead of changing to "associated with," which is less clear?

**Comment by kazuho** [comment]
I'm happy to know that we share the common sense :+1:

As stated in the opening comment, my "editorial" preference goes to stating the principle that any information in an NEW_TOKEN token (other than the opaque lookup key used in a stateful design) SHOULD be encrypted. If that is to be met, I think keeping "and encrypt" would be fine.

**Comment by janaiyengar** [comment]
I agree with @kazuho -- I think stating this explicitly as a SHOULD is sensible.

**Comment by martinthomson** [comment]
(For the chairs, and triage purposes).

This suggests a normative requirement that I don't think that we need, or that is already implied by existing text.  There would be new normative text.  I believe that is still editorial on the basis that the requirement is already implied, but will defer to your judgment.

**Comment by kazuho** [comment]
FWIW, what I am shooting for is a change like https://github.com/kazuho/base-drafts/commit/9017aaeb7924124ee93175283cb6c97ad11edf2c.

**Comment by larseggert** [comment]
@martinthomson and others, is  kazuho@9017aae kind of the editorial change you were envisioning?

**Comment by kirsey** [comment]
I was asked to move #2587 here. I miss the point, that the server SHOULD NOT construct the same token multiple times because this leads to additional scenarios where tracking by a network observer becomes feasible. The referenced PR does not fix this problem.

**Comment by kazuho** [comment]
@kirsey 
>  I miss the point, that the server SHOULD NOT construct the same token multiple times because this leads to additional scenarios where tracking by a network observer becomes feasible. The referenced PR does not fix this problem.

I think we are in agreement that unlinkability between tokens are required. IMO the phrase "SHOULD NOT expose linkability" in the proposed text captures the concept, though I might agree that "i.e., ..." needs improvement.

**Comment by janaiyengar** [comment]
@larseggert: @kazuho's change would be adequate, and I agree with @martinthomson that this is effectively editorial.  Do the chairs want to mark this issue as `editorial`?

**Comment by kirsey** [comment]
@kazuho Yes, I agree with you on the phrase "Should NOT expose likability".
To address my concern, I suggest to include "This includes that the server constructs each time a different token when issuing tokens to clients from the same source address." after line 1560 of  #kazuho/base-drafts@9017aae.

**Comment by larseggert** [comment]
Marking this as editorial
