### ISSUE TITLE
MAX_PACKET_SIZE frame

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#2545]
This is likely a v2 feature, as we discussed on the list.

This is a proposal for a new MAX_PACKET_SIZE frame that updates the “max_packet_size” received in transport parameters.

There are several ongoing efforts in IETF to have network deliver PMTU information to the intended destination, in addition to sending the traditional ICMP PTB message to the sender from an on-path device.

The efforts include [draft-hinden-6man-mtu-option](https://tools.ietf.org/html/draft-hinden-6man-mtu-option), [draft-leddy-6man-truncate attempts](https://tools.ietf.org/html/draft-leddy-6man-truncate), [draft-ioametal-ippm-6man-ioam-ipv6-options](https://tools.ietf.org/html/draft-ioametal-ippm-6man-ioam-ipv6-options), [draft-ietf-ippm-ioam-data](https://tools.ietf.org/html/draft-ietf-ippm-ioam-data).

In all cases, if an endpoint learns the PMTU from the sender to itself, there is still a problem of passing that information back to the sender.  We know that ICMP PTB has only limited chances of getting back to the sender, even if sent directly by the receiver.  However, a QUIC packet with MAX_PACKET_SIZE frame solves the problem.

Another use for the MAX_PACKET_SIZE frame is support for connection migration.  For an anycast server deployment, a path change may cause the new path to reach a different anycast node.  That would require tunneling the packets from the new anycast node to the original anycast node.  I would expect that significantly fewer than 1% of connections will migrate to another anycast node during their lifetime.  The server deployment would either pre-emptively set pack_packet_size transport parameter low enough to accommodate the possible tunneling overhead (something that would needlessly reduce the efficiency of >99% of connections) or send MAX_PACKET_SIZE frame after the migration only to those connections that need it.

**Comment by ianswett** [comment]
As I've suggested for other similar situations, an UPDATE_TRANSPORT_PARAMS frame seems potentially very useful for this and other params(ie: max_ack_delay).

However, I'll admit it's less useful in a multipath scenario where two paths are likely to have different MTUs.

**Comment by martinthomson** [comment]
Done is a feature.  This should be v2.

**Comment by mnot** [comment]
Are we happy to just call this v2 then?

**Comment by ianswett** [comment]
Yes, v2 (I realize my previous comment was unclear on this)
