### ISSUE TITLE
Clarify that stateless_reset_token is not mandatory

### ISSUE THREAD

**Issue by ghedo** [quicwg/base-drafts#2547]
The language could be clearer, and there was some confusion today during the hackathon.

/cc @marten-seemann

**Comment by martinduke** [comment]
This would also address #2471, I believe, so please consider closing this if it covers all the issues. I'll look at the PR in a few days.

**Comment by martinthomson** [comment]
I suggest that this is a duplicate of #2471, that we discussed in Prague today.

**Comment by ghedo** [comment]
Yeah, I agree. This only covers a subset of #2471, so closing in favour of that.
