### ISSUE TITLE
Line to long warnings in -recovery

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#255]
> WARNING: artwork line too long: '      alarm_duration = max(1.5 * smoothed_rtt, kMinTLPTimeout) << handshake_count;' (82 characters) (at line 261)
WARNING: artwork line too long: '        alarm_duration = max(kMinRTOTimeout, smoothed_rtt + 4 x rttvar);' (72 characters) (at line 261)
WARNING: artwork line too long: '     # TODO: Don't remove packets immediately, since they can be used for' (73 characters) (at line 364)
WARNING: artwork line too long: '           acked_packet.time_sent - kTimeReorderThreshold * smoothed_rtt):' (74 characters) (at line 404)

Build with `USE_XSLT=true` set to see these.

**Comment by ianswett** [comment]
Is there a way to see this in the github editor?  Because otherwise it'll probably keep happening.

**Comment by martinthomson** [comment]
Not that I'm aware of.  If you use the online equivalent of notepad.exe, I'm not sure that there is much we can offer in terms of assistance.

**Comment by martinthomson** [comment]
These are fixed and should no longer continue to pop up.
