### ISSUE TITLE
Apply GREASE to transport parameters

### ISSUE THREAD

**Issue by mjoras** [quicwg/base-drafts#2550]
We have space for private transport parameters and a process for assigning new standard transport parameters. However, since we do not apply GREASE to transport parameters, we leave ourselves open to that flexibility ossifying.

I'm happy to produce a PR to address this in the spec.

**Comment by DavidSchinazi** [comment]
During interop in London we found an implementation that failed the handshake upon seeing an unknown transport parameter. I think applying GREASE to transport parameters is a great idea.

**Comment by larseggert** [comment]
Discussed in London, @mjoras to prepare a PR

**Comment by mnot** [comment]
@mjoras any progress here?

**Comment by loganaden** [comment]
I have prepared something. I can open a pr

**Comment by mjoras** [comment]
@mnot sorry I totally dropped the ball here! I had text ages ago and was circling back today finally.  Thanks @marten-seemann for seeing to it.
