### ISSUE TITLE
Clarify text in transport section 3.2 about RESET_STREAM while in DataRecvd

### ISSUE THREAD

**Issue by agrover** [quicwg/base-drafts#2558]
> Alternatively, the RESET_STREAM signal might be suppressed or withheld if stream data is completely received and is buffered to be read by the application. In the latter case, the receiving part of the stream transitions from “Reset Recvd” to “Data Recvd”.

This is talking about the case of being in "Data Recvd" and therefore ignoring RESET_STREAM. Should the last sentence instead read: "In the latter case, the receiving part of the stream remains in "Data Recvd" ?

**Comment by martinthomson** [comment]
That sounds right.
