### ISSUE TITLE
Crypto retx timeout should have higher priority than time based loss detection

### ISSUE THREAD

**Issue by yangchi** [quicwg/base-drafts#2565]
In both SetLossDetectionTimer() and OnLossDetectionTimeout(), the loss_time based timer setup and loss detection happens before the crypto loss recovery logics. That seems at the cross road with the idea that crypto packets having higher priority in loss recovery. In fact in OnLossDetectionTimerou(), if loss_time is present and we go into DetectLostPackets(), then we will only decect loss of one packet number space between Initial and Handshake. Plus the loss_time used to set the timer is the earliest among all possible values, which means even if only one of Initial and Handshake space has inflight packets, we may still not retransmit all the inflight packets when this timer fires. So this current code really doesn't follow the idea that when crypto is inflight and loss timer fires, all inflight crypto needs to be retransmitted.

If we change the code so that crypto is handled first, we can also reduce the states need to be maintained and simplify some of the functions. In current draft there are 3 loss_times, one per packet number space. By always handling crypto first, we will need such loss_time for AppData space only, and no need to have the helper function to GetEarliestLossTime().

(I'm more than happy to cook up a PR if people think this makes sense.)

**Comment by yangchi** [comment]
It's been a few days. I sent PR #2619.

**Comment by marten-seemann** [comment]
This was introduced as a fix to https://github.com/quicwg/base-drafts/issues/2435, and fixed in https://github.com/quicwg/base-drafts/pull/2451. I don't think that reverting that fix is a good idea.

**Comment by ianswett** [comment]
+1 to @marten-seemann's comment.  Timers are necessary when you have no information about what might be lost, but if you do have information, there's no reason not to use that instead.

**Comment by ianswett** [comment]
I sent out an editorial PR to clarify why time based loss detection has higher priority.
