### ISSUE TITLE
Usage of "epoch" term in recovery draft (example code in appendixes)

### ISSUE THREAD

**Issue by agrover** [quicwg/base-drafts#2566]
In watching the [streams of the IETF QUIC sessions](https://www.youtube.com/watch?v=9xDS27UBi4U) there's a lot of discussion around "epoch", but this term is not defined in any of the quic draft documents, and is only mentioned (as "recovery epoch" and "congestion epoch") in the sample code in the -recovery appendices.

It is defined and discussed in the [DTLS RFC](https://tools.ietf.org/html/rfc4347), however.

I'm not sure if mention of "epoch" should be purged or expanded, but it struck me as unclear currently.

**Comment by martinthomson** [comment]
Hopefully there is no mention of epoch in TLS or transport. Though we use the concept in discussion as a shorthand and to help reason through the complicated key update cases we were discussing, taking the meaning from DTLS, QUIC currently doesn't have that concept. And it probably won't have to grow that concept either. 

Should this issue be used to track the lack of definition of those terms in the recovery draft?

**Comment by agrover** [comment]
Sounds good to me.

**Comment by kazuho** [comment]
> is only mentioned (as "recovery epoch" and "congestion epoch") in the sample code in the -recovery appendices.
> 
> It is defined and discussed in the DTLS RFC, however.

Doesn't "epoch" used in the sample code in -recovery have different meaning than that used in DTLS? IIUC, the recovery draft is talking about the distinction of each loss event by using the term.

**Comment by DavidSchinazi** [comment]
If the "epoch" in question here is the one in my slides on discarding old 1-RTT keys after a key update, then I indeed meant it in the DTLS sense, and I apologize for the confusion. The TLS 1.3 spec refers to this concept as a "generation", so perhaps I should have used that instead here. But I agree with Martin that this concept might not necessarily need to be named in the spec if we can clarify the key update edge cases without it.

If the "epoch" in question is the one in recovery, then this is specific to recovery concepts that do not involve (D)TLS.

**Comment by janaiyengar** [comment]
Yeah, it's confusing, but it's unfortunate terminology used in both loss recovery and in DTLS. It's best to use congestion event, as @ianswett is doing in #2585.
