### ISSUE TITLE
RTT sample should be taken only once for each largest_acked

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2569]
The pseudo code in [Section A.6](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#on-ack-received) ends up taking an RTT sample on every ack, which can result in multiple RTT samples per largest_acked. The code should check to see if the largest_acked is newly acked.

The text does say that an RTT sample MUST NOT be taken on a packet that is not newly_acked, but pseudo code needs to match.

**Comment by nibanks** [comment]
To be fair, the comment in the pseudo code does say only to update the rtt if it's newly acked:
```
  // If the largest acknowledged is newly acked and
  // ack-eliciting, update the RTT.
  if (sent_packets[pn_space][ack.largest_acked] &&
      sent_packets[pn_space][ack.largest_acked].ack_eliciting):
```
Personally, I'd solve this by always setting `sent_packets[pn_space][#] = null` once it has been acknowledged. Then the pseudo code above would be correct.

**Comment by ianswett** [comment]
@nibanks That's what remove() is supposed to do, which is called when a packet is acked or lost.

As with #2571, this may be a matter of more clearly defining what remove() does.

**Comment by ianswett** [comment]
Jana and I talked about this, and I think Nick's suggestion is a good one.  We'll stop calling remove() and start setting the value to null.
