### ISSUE TITLE
bytes_in_flight might be reduced twice for lost packets

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2571]
The pseudo-code reduces bytes_in_flight on loss and on acked, but a packet might be acked after marked as lost (it might still be in the sent_map). Pseudo code fix needed.

Thanks, @kazuho, for this catch.

**Comment by ianswett** [comment]
We call remove() when a packet is acked or lost.  We can be more specific about what remove() does, but my intent was that removed the packet from the sent_packets data structure, so it could only be acked or lost, not both.

Admittedly, this does not allow detection of spurious losses, but I thought we decided that was out of scope for the pseudocode?

**Comment by janaiyengar** [comment]
I think the resolution to #2569 should resolve this as well.
