### ISSUE TITLE
Construction of address validation token

### ISSUE THREAD

**Issue by kirsey** [quicwg/base-drafts#2587]
The draft describes that a client SHOULD NOT reuse a token in different connections (https://tools.ietf.org/html/draft-ietf-quic-transport-19#section-8.1.2). However, I miss the argument that the server SHOULD NOT construct the same token multiple times.
This argument addresses the risks of client tracking via tokens if a deterministic approach is used to construct them.

**Comment by kazuho** [comment]
Maybe #2543?

**Comment by larseggert** [comment]
@kazuho do you mean @2543 already covers this?

**Comment by larseggert** [comment]
@kirsey do you agree that this is (mostly) covered by #2543? If yes, can we close this issue and resolve it as part of #2453?

**Comment by kirsey** [comment]
No, #2543 does not cover this particular point. #2543 makes the point that a network observer should not be able to derive information such as a timestamp from observed tokens.

However, this issue says that the construction of the token should not be deterministic. To illustrate this problem, assume that the token is more or less the hash of the client's source address. Thus, the client receives upon repeat connections the each time the same token, if its source address is identical. As a result, even if the client uses each token only a single time the corresponding connections established with these tokens can be correlated to each other by a network observer.

**Comment by larseggert** [comment]
@kirsey could #2543 be modified to cover your issue? could you comment there?

**Comment by kirsey** [comment]
@larseggert Ok, I will make proposals within #2543 to cover this issue.

**Comment by larseggert** [comment]
@mnot the automation failed here - this should not be moved to "Text Incorporated", it should just be closed
