### ISSUE TITLE
Should platform delays be included in ack-delay?

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2596]
Spawned from #2592.

@martinthomson typed: "Probably not for this change, but do we really want to encourage people to be estimating delays in the kernel? Because it seems like the point of some of the other changes is to include that sort of delay in the RTT estimate. What matters here is end-to-end delays - the time between when the packet was consumed and when the packet containing the ACK was sent out. Yes, it's true that you get a bigger RTT estimate if you don't correct for delays in the kernel or NIC, but those are just another piece of the plumbing now. If we fail to cover things like scheduling delays in the RTT estimate, we're just deluding ourselves about where the delays are."

@janaiyengar typed: "Yeah, I was thinking about this too, but it's text that we already had. FWIW, I think it's useful to separate out these delays, not because they shouldn't get used for PTO estimates, but because knowing component delays might be helpful. That said, I don't have a good use case for these component delays yet. OTOH, I've started that separation between stack-controlled delays and other delays in the text, it might be worth using that distinction here, and arguing that these delays ought to be part of the path RTT since they're not controlled delays."

**Comment by kazuho** [comment]
> I've started that separation between stack-controlled delays and other delays in the text, it might be worth using that distinction here, and arguing that these delays ought to be part of the path RTT since they're not controlled delays.

:+1: I share the view with @martinthomson and @janaiyengar that ack-delay should represent only the delay introduced intentionally by the QUIC stack. "stack-controlled delay" sounds like a good way of explaining them.

**Comment by ianswett** [comment]
+1 to the idea that ack-delay should be intentionally introduced delay, since almost anything on path(including the local host NIC/OS/Firmware) can delay things without the receiver's control.

**Comment by ianswett** [comment]
From London: Platform delays SHOULD be included in RTT, but ack_delay should only include intentionally introduced delays, not platform delays.
