### ISSUE TITLE
Explain extraordinary conditions that lead to sending a Handshake packet

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2598]
We don't provide examples of the weird cases where you need to send Handshake packets to prevent amplification deadlock.  The strangest one is where the client has all Initial data (and therefore has Handshake keys), but never receives a Handshake packet from the server.  In this case, the client needs to send a Handshake packet that won't contain ACK or CRYPTO frames.  We should explain this in a note.

See #2597.

**Comment by Ralith** [comment]
I think the logic in the recovery draft misses some of these cases entirely. The rule in draft 23 is:
>  the client MUST set the probe timer if the client has not received an acknowledgement for one of its Handshake or 1-RTT packets.

but in your example case there is not necessarily any unacknowledged data to transmit in a probe, and a `PING` is forbidden at Handshake level, leaving no reasonable options to compose an ACK-eliciting packet.
