### ISSUE TITLE
Pseudocode fix: Data should be sent on loss-threshold timer

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2604]
(@larseggert : Thanks for catching this)

Currently, in OnLossDetectionTimeout(), we detect losses but do not sent anything on time threshold loss detection.  This means that SetLossDetectionTimer() that is called later in the function does not set a timer because inflight can be 0 (if all inflight is marked lost).

This is an oversight, since clearly we send rtxs when we mark packets as lost, and in the case of threshold detection, we send as much as the cwnd allows.

My proposal is to add the last two lines below
if (loss_time != 0):
    // Time threshold loss Detection
    DetectLostPackets(pn_space)
    SendOnePacketWithRetransmittedData()
    SendDataAsCwndAllows()

**Comment by ianswett** [comment]
I don't think you need to indicate what should be sent, so I'd recommend: "SendPacketsAsCongestionControllerAllows()" since it may be pacing or CWND limited.

**Comment by janaiyengar** [comment]
Yeah I thought about this... your point is taken in the PTO case, but there is a difference between the PTO case and this case. What you suggest is exactly what quicly implements right now. Without PRR however, the sender waits for half an RTT until it is able to send out the retransmission, since it waits until inflight < cwnd before sending anything.

I'm suggesting (and this is what TCP does) that we allow _one_ packet of rtx to go through before applying the cwnd clamp. Maybe this pseduocode isn't the best, but it's what I could come up with to capture that intent.

**Comment by ianswett** [comment]
Ah, that makes sense, thanks for clarifying.

My first suggestion is "SendOneOrMorePacketsAsCongestionControlAllows()" which is insanely verbose.  An alternative is to say:

// Time threshold loss Detection
if (DetectLostPackets(pn_space)):
  // PRR allows immediately sending a packet
  SendOnePacket()
SendDataAsCwndAllows()

We don't reference PRR anywhere I can find in the existing recovery text.  Should we?

**Comment by janaiyengar** [comment]
Yeah, I realized that we don't really talk about PRR. If we want to bring the entire mechanism here, that might be a bit of work. How about we do as you propose above (without PRR in the comment), add some text about how a sender can implement PRR if they want a smoother way out of recovery with a reference to the PRR draft?

Separately, is it worth filing an issue to do PRR for QUIC? Since we don't assume pacing here, it might actually be useful. It will be some work to do it though. WDYT?

**Comment by ianswett** [comment]
Given where congestion control and pacing are going, I'd be inclined to not mention PRR, but if we want to mention it as another informational reference, particularly when senders aren't pacing, that SGTM.

**Comment by ianswett** [comment]
I've thought about this more, and I really don't want to get into PRR, so I went with a simple fix to this issue which reflects what I believe code should do.

**Comment by janaiyengar** [comment]
Thinking about this some more and discussing this with @ianswett, I'm closing this issue in favor of the better scoped #3335.
