### ISSUE TITLE
HTTP/3 reserved value range

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#2606]
The definition of reserved ranges (AKA GREASE values) seems a bit off, e.g. section 10.3 in draft 19:

```
   Additionally, each code of the format "0x1f * N + 0x21" for integer
   values of N (that is, "0x21", "0x40", ..., through
   "0x3FFFFFFFFFFFFFFE") MUST NOT be assigned by IANA.
```

The frame type is sent on the wire using a varint, which is limited to a value of 2^62 -1. Should we only reserve frame types that can be sent on the wire?

This applies also to settings parameters and unidirectional stream types.

**Comment by martinthomson** [comment]
Are you suggesting that there is a world in which a frame type outside of the range that can be expressed in the protocol can be reserved?  That would seem to be a little academic.  

There was a discussion of defining frame types to be integers in the 0..2^62-1 range, but I don't know if we ever got to writing that down.  If we do anything, that would be what I would do.

**Comment by LPardue** [comment]
On Thu, 11 Apr 2019, 02:23 Martin Thomson, <notifications@github.com> wrote:

> Are you suggesting that there is a world in which a frame type outside of
> the range that can be expressed in the protocol can be reserved? That would
> seem to be a little academic.
>

I think we agree this situation is odd.

> There was a discussion of defining frame types to be integers in the
> 0..2^62-1 range, but I don't know if we ever got to writing that down. If
> we do anything, that would be what I would do.
>
As a start, I'll make a PR to fix up all reserved ranges to fall into
sensible limits.

**Comment by LPardue** [comment]
While looking again at this I think the reserved values fall in valid limits, it is just unclear. I'm now confused by the text that explains that certain ranges are restricted to being allocated to IESG or for private use. 

So I'll attempt an editorial PR that tries to  clarify things.

**Comment by LPardue** [comment]
On reflection, I think the HTTP document does enough to describe everything - I have no positive editorial changes to make at this time. Closing this issue.
