### ISSUE TITLE
HTTP/2 to HTTP/3 mapping section of http/3 is stale

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#2627]
I'm not sure exactly what needs to be updated, but it's fairly clear this section is out of date.

Example: "Below is a listing of how each HTTP/2 frame type is mapped:" and below.
ie: "As described above, the PRIORITY region of HEADERS is not supported. ..."

**Comment by LPardue** [comment]
I'm not sure I 100% agree

> Example: "Below is a listing of how each HTTP/2 frame type is mapped:" and below.
ie: "As described above, the PRIORITY region of HEADERS is not supported. ..."

This statement is still correct, although perhaps it is more accurate to say something like:

```
HEADERS (0x1):
: The PRIORITY region of HEADERS is not defined in HTTP/3 frames. A separate PRIORITY frame is used in all cases. Padding is not defined in HTTP/3 frames.
```

Likewise, the statement below that appears earlier in the section isn't wrong but doesn't describe that PRIORITY frame can appear as the first frame on a request stream

> To achieve in-order delivery of priority changes in HTTP/3,
PRIORITY frames are sent on the control stream and exclusive prioritization
has been removed.

**Comment by ianswett** [comment]
Thanks Lucas, your text makes it clear what was intended.

**Comment by MikeBishop** [comment]
Are there additional changes here, or does #2633 address it?

**Comment by ianswett** [comment]
I'm happy with the text in #2633
