### ISSUE TITLE
Clarify send state behavior for peer-created bidi stream

### ISSUE THREAD

**Issue by agrover** [quicwg/base-drafts#2636]
From -transport section 3.1:

> The sending part of a bidirectional stream initiated by a peer (type 0 for a server, type 1 for a client) enters the “Ready” state then immediately transitions to the “Send” state if the receiving part enters the “Recv” state (Section 3.2).

The event causing transition Ready->Send is the host initially having data to send on the stream, which is not the case when the receiving part has just been created in its initial Recv state. I think the send stream should stay in Ready until it has data. This also aligns better with similar text in 3.2.

I suggest:

> The sending part of a bidirectional stream initiated by a peer (type 0 for a server, type 1 for a client) starts in the “Ready” state.

p.s. see also #2357, but which is more about being explicit about frames that cause stream creation... rather than this issue, which is about the state the new sending part starts in.

**Comment by dtikhonov** [comment]
This issue can be closed -- see @martinthomson's commit above.

**Comment by MikeBishop** [comment]
That commit hasn't been merged, and is sitting in a branch that doesn't appear to have an associated PR.

**Comment by dtikhonov** [comment]
Oh -- sorry about that.  I should have checked.

**Comment by martinthomson** [comment]
Wow, that sat there for ages.  I made a PR.
