### ISSUE TITLE
client should send PING in Initial or Handshake, but PINGs are forbidden in these packets

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2640]
The [text about the crypto timer](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#crypto-retransmission-timeout) says:
> If the crypto retransmission timer expires before the client has 1-RTT keys, it is possible that the client may not have any crypto data to retransmit. However, the client MUST send a new packet, containing only PING or PADDDING frames if necessary, to allow the server to continue sending data. If Handshake keys are available to the client, it MUST send a Handshake packet, and otherwise it MUST send an Initial packet in a UDP datagram of at least 1200 bytes.

PING frames are forbidden in both Initial and Handshake packets.

**Comment by ianswett** [comment]
The smallest change is to only send PADDING without a PING, since the purpose here is to allow the server to send, not for the client to receive an ACK.  The PING doesn't really add any value.

**Comment by ianswett** [comment]
Sorry for the churn.  I sent out the smallest fix possible.  We can also change the transport doc to allow PING in Initial and Handshake.  Functionally, I don't think it matters for recovery, but both are reasonable options in my opinion.
