### ISSUE TITLE
RTT measurement using PATH_* frames

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#2644]
Should the recovery draft explain how to gather RTT samples during connection migration using PATH_CHALLENGE and PATH_RESPONSE?

This is explained in:
- https://tools.ietf.org/html/draft-paulo-quic-migration-00#section-3.3

**Comment by martinthomson** [comment]
Is there any expectation that the response is sent immediately?

**Comment by rpaulo** [comment]
Section 8.4:

> On receiving a PATH_CHALLENGE frame, an endpoint MUST respond immediately by echoing the data contained in the PATH_CHALLENGE frame in a PATH_RESPONSE frame.

**Comment by ianswett** [comment]
If PR#2637 lands, we'd need to restrict this to cases when the PATH_RESPONSE arrived on the same path the PATH_CHALLENGE was sent on.

**Comment by rpaulo** [comment]
@ianswett don't we already have text about that?

> To ensure that packets can be both sent to and received from the peer, the PATH_RESPONSE MUST be sent on the same path as the triggering PATH_CHALLENGE. That is, from the same local address on which the PATH_CHALLENGE was received, to the same remote address from which the PATH_CHALLENGE was received.

**Comment by janaiyengar** [comment]
@rpaulo, #2637 removes that text. @ianswett is right, we'll need to caveat this at a minimum. I think it gets a bit tricky to use the PATH_CHALLENGE/RESPONSE for RTT if the RESPONSE can arrive on any path. The endpoint does not know what path will be used for data/acks, and it would have to assume that the path for CHALLENGE/RESPONSE will be the one used for data/acks, if it is to set its RTT estimate.

Perhaps we could say that an endpoint can use the CHALLENGE/RESPONSE RTT as a hint.

This will need some more thought.

**Comment by ianswett** [comment]
How about "MAY use the delay between sending a PATH_CHALLENGE and receiving a PATH_RESPONSE to seed initial_rtt for a new path, but MUST not be considered an RTT sample."?

**Comment by rpaulo** [comment]
Discussed with Ian in London: I'm okay with just using the PATH_CHALLENGE/PATH_RESPONSE RTT as the initial RTT.

**Comment by ianswett** [comment]
Thanks @rpaulo can you review the outstanding PR?
