### ISSUE TITLE
is persistent congestion per pn_space?

### ISSUE THREAD

**Issue by yangchi** [quicwg/base-drafts#2649]
The wording around persistent congestion sounds across pn_spaces:

> When an ACK frame is received that establishes loss of all in-flight packets sent over a long enough period of time, the network is considered to be experiencing persistent congestion.

But DetectLostPackets function is per pn_space and persistent congestion checking is invoked from there. So if DetectLostPackets find all packets of one pn_space within a persistent congestion window are lost but packets from other pn_space within this time window are not lost, is this persistent congestion?

**Comment by ianswett** [comment]
I think it should only be for ApplicationData, and say that we expect the handshake timeout to be smaller than the persistent congestion threshold, so it does not need to apply to Initial or Handshake spaces.

Prior to the persistent congestion concept, RTOs(and then consecutive PTOs) were used as a signal of persistent congestion, and the RTO and PTO alarm are only active when the crypto handshake alarm is not, so I think saying it's ApplicationData only is keeping with the original design.

**Comment by yangchi** [comment]
Oh i see your point. Basically crypto timer would have been fired earlier than persistent congestion. So this is for AppData only and will apply to AppData only anyway, then I shouldn't have to worry about packets from more than on pn_space are in the persistent congestion window.
