### ISSUE TITLE
STREAM_LIMIT_ERROR vs MAX_STREAMS

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2661]
The MAX_STREAMS frame as named as it is, but causes a STREAM_LIMIT_ERROR if violated.
It is already confusing that these are accumulative counters (with the largest allowed value being 2^60) so I suggest renaming MAX_STREAMS to STREAM_LIMITS. Alternative rename the error to MAX_STREAM_ERROR, but that would be inconsistent with STREAM_STATE_ERROR.

Note that I'm all for the counter design, just the naming is a bit confusing.

**Comment by LPardue** [comment]
To push back, the transport document has a lot of text that describes or uses the term "stream limit". Therefore IMO an error related to these requirements is logically a STREAM_LIMIT_ERROR.

**Comment by mikkelfj** [comment]
No argument there, my preferred change is to rename MAX_STREAMS to STREAM_LIMITS and leave the errors alone.

**Comment by marten-seemann** [comment]
I don't think we should rename the MAX_STREAMS frame. It's a form of flow control, and we use MAX_DATA and MAX_STREAM_DATA for data limits.
If you were suggesting to rename those to DATA_LIMIT and STREAM_DATA_LIMIT, your renaming would at least be consistent. I'd push back against that as well though.

**Comment by martinthomson** [comment]
Anyone who cares about this is free to open a PR.  However, the chairs have given editors some leeway when it comes to naming, and this doesn't seem to be particularly important, so we might close this issue without action.  I'll give people a chance to suggest alternatives though.

**Comment by mikkelfj** [comment]
I don't have a strong opinion, although I do find it mildly confusing. So if consensus ranges from meh to moderate push back I'd be inclined to close this - but as Martin says, let's give people a chance.
