### ISSUE TITLE
Only received Stateless reset token should be checked

### ISSUE THREAD

**Issue by tatsuhiro-t** [quicwg/base-drafts#2669]
The current text does not explicitly say that endpoint has to check the stateless reset token received in NEW_CONNECTION_ID (and server's TP if endpoint is a client).

> The endpoint MUST
   then compare the last 16 bytes of the packet with all Stateless Reset
   Tokens that are associated with connection IDs that are currently in
   use.  This includes Stateless Reset Tokens from NEW_CONNECTION_ID
   frames and the server's transport parameters.

With this wording, I was under the impression that server can use stateless reset token in its own TP, but it seems not.

I think it would be nice to state that only received stateless reset tokens are checked.

**Comment by tatsuhiro-t** [comment]
>  The token is
   carried in the NEW_CONNECTION_ID frame sent by either peer, and
   servers can specify the stateless_reset_token transport parameter
   during the handshake (clients cannot because their transport
   parameters don't have confidentiality protection).

This text is also problematic because it suggests that endpoint can specify token sent by either peer.

**Comment by martinthomson** [comment]
The first of these is already addressed in the draft, though it could be improved.
