### ISSUE TITLE
DUPLICATE_PUSH push ID validation

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#2681]
Two questions: 
1. Should DUPLICATE_PUSH respect max push ID limit?
  PUSH_PROMISE says the following:

 > A server MUST NOT use a Push ID that is larger than the client has
   provided in a MAX_PUSH_ID frame (Section 4.2.8) and MUST NOT use the
   same Push ID in multiple PUSH_PROMISE frames

2. What should a client do if it sees a DUPLICATE_PUSH for an ID of a PUSH_PROMISE that it never received?

This could be caused by a race condition, so it seems sensible to allow this to clients to support this without error. We should probably document that like we did for other racy things. E.g.

> If the client receives a CANCEL_PUSH frame, that frame might identify
   a Push ID that has not yet been mentioned by a PUSH_PROMISE frame.

**Comment by MikeBishop** [comment]
(2) is covered in [Section 5.4](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#server-push):
> Due to reordering, DUPLICATE_PUSH frames or push stream data can arrive before the corresponding PUSH_PROMISE frame. When a client receives a DUPLICATE_PUSH frame for an as-yet-unknown Push ID, the request headers of the push are not immediately available. The client can either delay generating new requests for content referenced following the DUPLICATE_PUSH frame until the request headers become available, or can initiate requests for discovered resources and cancel the requests if the requested resource is already being pushed.

For (1), yes it should -- the DUPLICATE might show up first, but the implication is that the ID has already been used in a PUSH_PROMISE frame.  If that would be invalid, we should be explicit that the DUPLICATE_PUSH is also invalid.

**Comment by LPardue** [comment]
SGTM
