### ISSUE TITLE
Mixture of transport and congestion control functions

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#2684]
Section 9.4 contains a mixture of transport (handling migration, setup, etc) and congestion control functions (choice of path parameters - RTO, window, etc). 

The abstract suggests that these are a part of QUIC Recovery ID, which seems correct to me. So, I would like to discuss if these are intentionally a part of the transport spec, rather than the Loss Detection & Congestion Control Spec.? 

Specifically, para 1,2 : "... SHOULD NOT contribute to congestion control or RTT estimation for the new path." and "...  SHOULD immediately reset ...."  - Where the ID could note whatever transport implementors need to be aware of, but point normatively to the QUIC Recovery ID for RFC2119 language.

Para 3: "An endpoint MUST NOT return to the send rate..." seems a reasonable thing to note, but also, I think, should point to QUIC Recovery ID.

**Comment by larseggert** [comment]
Discussed in London: @gorryfair to work with @janaiyengar to propose an editorial PR

**Comment by ianswett** [comment]
The target is to fix this issue with the same PR as #2909

**Comment by martinthomson** [comment]
Discussed today with editors and we believe that these issues have been rectified in the numerous edits that section has received since this issue was opened.
