### ISSUE TITLE
CC state after a change of path?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#2685]
I think a normal transport assumption is that a change of path implies a (potential) loss of congestion state, and that the endpoint should reset the path CC parameters. 

Transport-ID: “On confirming a peer's ownership of its new address, an endpoint
SHOULD immediately reset the congestion controller and round-trip
time estimator for the new path.”

• Does the "reset" require setting the CC to the initial window value for a connection? I think so.
• Why not MUST? 

Transport-ID:  “An endpoint MUST NOT return to the send rate used for the previous
path unless it is reasonably sure that the previous send rate is
valid for the new path. “

This could therefore be seen as a “significant” departure from conventional approaches considered safe - and extends this to “reasonably sure”. 
• Is there a rationale for extending this to “reasonably sure”, because this seems bolder than permitted for a new TCP connection. How do people quantify reasonably sure, and why not just in this case grow from the Initial window?

**Comment by janaiyengar** [comment]
> • Does the "reset" require setting the CC to the initial window value for a connection? I think so.
Yes. We should articulate this better though.

> • Why not MUST?
To allow for pre-existing knowledge, such as stored values. I think this can be changed to say "unless an endpoint has other knowledge, it MUST reset" (or some such).

> This could therefore be seen as a “significant” departure from conventional approaches considered safe
Fair point. The intent here again was to allow pre-existing knowledge to be used, but I think the wording can be changed to reflect that more explicitly.

**Comment by larseggert** [comment]
Discussed in London: @janaiyengar to provide a PR

**Comment by janaiyengar** [comment]
Re-opening issue. This needs a bit more work.
