### ISSUE TITLE
Checking duplicate TPs is onerous

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#2689]
Unlike HTTP/3 settings, receipt of [duplicated transport parameters must be treated as an error](https://tools.ietf.org/html/draft-ietf-quic-transport-20#section-7.3):

```
                                                    An endpoint MUST
   treat receipt of duplicate transport parameters as a connection error
   of type TRANSPORT_PARAMETER_ERROR.
```

Why the inconsistency?

The checks for duplicated transport (or settings) parameters are expensive, because one has to maintain an arbitrarily-sized set of possibly large numbers.

I propose we switch the duplicate transport parameters enforcement to "MAY treat as error."

**Comment by ianswett** [comment]
I'm fine with MUST not send duplicates, MAY treat receipt as an error.

**Comment by MikeBishop** [comment]
Fine by me.

**Comment by janaiyengar** [comment]
Yup, seems sensible to me.
