### ISSUE TITLE
Public Packet Number Echo

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#269]
In Mirja's Management draft:
[https://tools.ietf.org/html/draft-kuehlewind-quic-appman-00#section-3](url)

> [EDITOR'S NOTE: the addition of a simple packet number echo would
   allow passive RTT measurement and partial passive downstream loss/
   reordering measurement.  Packet number echo can be sampled at the
   echo-side (i.e. one-in-N packets or 1/p packets can carry an echo)
   for efficiency tradeoff, if necessary.]

I endorse this idea. Service providers are very interesting in measuring their users' quality of experience and this is one key thing we can expose to enable that. On the face of it, it seems that the privacy hit is marginal.

**Comment by britram** [comment]
Adding packet-number echo is, IMO, much easier with Jana's alternate header format proposal. This could be done with just two additional codepoints. Propose:

`35 and b5: 1-RTT packet (4-byte packet number + 4-byte packet echo)`

```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+
|      Type     |             
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                     Packet Number (4)                         |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                  Packet Number Echo (4)                       |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                            Payload                          ...
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

`3d and bd: 1-RTT packet with connection ID(4-byte packet number + 4-byte packet echo)`

```
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+
|      Type     |             
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
+                        Connection ID                          +
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                     Packet Number (4)                         |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                  Packet Number Echo (4)                       |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                            Payload                          ...
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by martinthomson** [comment]
@britram, Who would be able to decide to use this?  Does it require mutual agreement (to use or to disable)?  Or, could be unilateral?

**Comment by britram** [comment]
Right now, packet number echo is only intended for the use of devices on path, to support passive RTT/loss measurement -- QUIC uses ACK frames for the same. So the decision whether to echo packet numbers, and how often, is unilateral. 

Whether this would be an application-level or system-level configuration option is IMO implementation-specific.

**Comment by ianswett** [comment]
Technically, the choice of sending it would be unilateral.

But I think if we add this, we need SHOULD(s) on the appropriate times to include this(ie: in packets containing an ack frame).  And I believe we may want this to be a MUST do.  If we believe the path is relying upon them for network management or optimization, then I think a MUST makes sense.  If we don't think the path really needs it, we shouldn't add it.

**Comment by martinduke** [comment]
It ought to certainly be at least a SHOULD, and a MUST if no one comes up
with a situation where this might compromise privacy.

**Comment by britram** [comment]
Agreed that the goal should be MUST; my point on "unilateral" is that no negotiation is required.

Adding guidance on when/how often to echo (the sweet spot of the overhead/benefit curve) might be a little difficult to make universal, but is worth doing. It'll make a nice (if smallish) bikeshed.

**Comment by martinthomson** [comment]
This is a lot of bytes to spend and it looks like you want a lot of those bytes spent.  That makes me think that @janaiyengar's arguments about short packet numbers are going to have fun with this.

I agree that if you pick the design you propose, unilateral certainly makes the most sense.  This isn't an optional feature.

BTW, you can't really measure RTT with this given the time between receipt and ACK, but I guess that you can narrow in on a value close to RTT and maybe that's enough.  It's about as good as you get with TCP, as you point out.

**Comment by britram** [comment]
I'm not sure that 4 (for large-window flows) to 7 (for small-window flows) bytes per RTT in the MUST (see #351) counts as "a lot of bytes". Obviously echoing on every packet with an ACK frame uses more.

You can measure RTT components on each leg (observation point to endpoint A, observation point to endpoint B) and add them together; see e.g. http://queue.acm.org/detail.cfm?id=2539132 (which uses tsval/tsecr, but it doesn't really matter what you're echoing)

**Comment by acmacm** [comment]
I support packet number echo at the "MUST" level.  I can't easily correlate an ephemeral path performance indication with a privacy breach, but if someone else can connect the dots I'm willing to learn the linkage. 
In general, I support the Management draft because it has raised several issues I'm interested to follow and resolve during the remaining spec development.  (acmacm is Al Morton)

**Comment by ianswett** [comment]
@martinthomson My solution to the short packet number approach is to define a codepoints for 2 byte packet numbers and 2 byte echos.  This covers the vast majority of connections which have limit the max number of outstanding packets to less than 32,000.

**Comment by mirjak** [comment]
I might probably okay to always have a short (e.g. 2 byte) echo no matter how long the packet number is because RTT measuremnents are estimated only and you always have to account for potential measurement errors.

**Comment by britram** [comment]
@ianswett yep, have added a comment to this effect to #351.

**Comment by britram** [comment]
@mirjak I'm not sure that e.g. a 4-byte PN with a 2-byte echo makes sense: if you actually need four bytes of packet number on a high-delay link, guessing the wrong values for octets 2 and 3 might inject a lot of error. Need to think about this a bit more...

**Comment by britram** [comment]
Note that the required size of the packet number echo is related to the peer's in-flight window, not the echoer's in-flight window. When an endpoint sends a packet echo, it should send the echo using the same size as the packet number it's echoing. So, when deciding whether to use 1, 2, or 4-byte packet number/echo, it should use the maximum of the size of the value to echo and the packet number size its inflight window requires.

**Comment by ianswett** [comment]
You're correct Brian, and that's why I tend to think 1 byte packet number echos are a foot gun.

**Comment by acmacm** [comment]
Assuming that we are moving information from the encrypted side to the clear side and the recipient can use it either way, then this proposal doesn't expand the header overhead (but I may be overlooking a detail I haven't learned about yet, mea culpa if so).

**Comment by britram** [comment]
working on updating the PR right now: I think the correct thing to do here is to require that the packet number echo is of exactly the same size as the packet number field on the packet whose number is being echoed.

**Comment by ianswett** [comment]
Al, that's an idea I considered.  In that formulation, the largest acked would be expressed outside of the encryption layer and the rest of the ack would be encrypted.  This is a bit awkward from a parsing perspective, but it's worth considering.  For better or worse, it makes this truly required.

**Comment by britram** [comment]
...see #391 for discussion of possible approaches...

**Comment by mnot** [comment]
This seems like a proposal for #631 and/or #632, not an issue itself. Let's figure those out first.

**Comment by ianswett** [comment]
This is superseded by the reservation of bits for experimentation and future work is tracked in #631 and #632
