### ISSUE TITLE
Does InPersistentCongestion calculate a bogus value?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#2694]
```
InPersistentCongestion(largest_lost_packet):
        pto = smoothed_rtt + max(4 * rttvar, kGranularity) +
          max_ack_delay
```
`pto` is usually < 1 sec, right?
```
        congestion_period = pto * kPersistentCongestionThreshold
```
So because `kPersistentCongestionThreshold` is 3, multiplying by `pto` will result in 0 (cast to integer, since it's supposed to be a window width). Or what unit do you assume `pto` to be calculated in?

**Comment by mikkelfj** [comment]
I don't think you can assume integer math 1 second resolution here, if this is what you are suggesting.

Most would likely use floating point here, since that is simple and efficient. And for those who don't, computing in units of milliseconds or microseconds would make sense.

**Comment by ianswett** [comment]
Given max_ack_delay and other fields are in microseconds, I assumed all of this would be done in microseconds.

I can add that to the document if you can tell me where that should be stated.

**Comment by nibanks** [comment]
I also assumed microseconds.

**Comment by mikkelfj** [comment]
I don't think it makes sense to state any particular resolution here. It ought to be clear that if your resolution does not cover your value range, you loose precision. The value range depends on circumstances.

**Comment by larseggert** [comment]
Well, my timestamps are doubles in seconds.

**Comment by ianswett** [comment]
That should work as well.

**Comment by mikkelfj** [comment]
> Well, my timestamps are doubles in fractional seconds.

That shouldn't cause you problems then, unless you cast to integer naively.

**Comment by larseggert** [comment]
Well, the congestion_period is supposed to be in packets, so you have to scale it somehow, no?

**Comment by larseggert** [comment]
Or is it in time?

**Comment by mikkelfj** [comment]
I'd assume the congestion_period is time because a unitless factor is multiplied to pto which has a time unit.

**Comment by larseggert** [comment]
Ah. When I hear "window", I think "packets".

**Comment by mikkelfj** [comment]
But somehow you are right. You can view smoothed RTT as conversion unit for packets, roughly.

**Comment by ianswett** [comment]
Ah, now that I go back and read the pseudo-code, I understood the confusion.

Yes, IsWindowLost is a very confusing name, we should change it.

**Comment by ianswett** [comment]
I sent you a PR, @larseggert Feel free to suggest a different name if that doesn't work for you.

**Comment by janaiyengar** [comment]
@larseggert: The TCP is strong in you :-)
