### ISSUE TITLE
Truncated http stream error handling is aggressive

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#2718]
HTTP draft sect. 6.1

> These streams carry frames related to the request/response (see Section 4.1). When a stream terminates cleanly, if the last frame on the stream was truncated, this MUST be treated as a connection error (see HTTP_MALFORMED_FRAME in Section 8.1). 

I can see the point of always sending the header fields of a frame, but if a data frame is required to be sent in full or have the connection closed, it is hard for a server to stop a cancelled request without having the connection closed when it sends an entire file in a single data frame.

Maybe "terminates cleanly" covers this concern, but it would be good if someone can ensure this is the case.

Splitting up files into multiple frames ought to be done because the length is not known in advance, not to avoid connection close.

**Comment by martinthomson** [comment]
If you create a stream that is invalid, then it is perfectly reasonable to kill the connection.  If you make a bad prediction that results in having to abandon a stream, then RESET_STREAM is the tool you use.  You don't close the stream as though it was OK.

**Comment by LPardue** [comment]
Right. After thinking this over again, I think @mikkelfj's case falls into the bracket of request cancellation desribed in section 5.1.2 of draft 20.

Someone wants to abruptly finish the request or response, so it is not a clean termination.

**Comment by MikeBishop** [comment]
I actually encountered this bug in the past, where the server decided to truncate a response but didn't indicate that there was an abort.  Then the truncated response was cached and served to future clients.

If you're not going to finish the response, RESET the stream so everyone knows it.

**Comment by MikeBishop** [comment]
Discussed in London; no action here.  The spec is correct to say that stopping a stream mid-frame needs to be an abort, not a clean closure, so the intent is clear.
