### ISSUE TITLE
Clarify PATH_RESPONSE lack of retransmission in Path Validation

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#2724]
We have a must for PATH_CHALLENGE "The endpoint MUST use unpredictable data in every PATH_CHALLENGE frame so that it can associate the peer's response with the corresponding PATH_CHALLENGE."

"On receiving a PATH_CHALLENGE frame, an endpoint MUST respond immediately by echoing the data contained in the PATH_CHALLENGE frame in a PATH_RESPONSE frame."

This text should clarify that an endpoint MUST respond exactly once as well.  Saving PATH_RESPONSEs for later retransmission could be a memory attack.  If one wanted to be particularly careful you could also limit how many you buffer if you're congestion control limited.

https://tools.ietf.org/html/draft-ietf-quic-transport-20#section-8.2

**Comment by erickinnear** [comment]
Good call. Note that this is already indicated in [Section 13.2](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.13.2), way down at the bottom of the bulleted list, but I agree that we should have this be MUST NOT save for retransmission/MUST response exactly once.

**Comment by martinthomson** [comment]
This is technically design, but trivial.  Do you want to take this @erickinnear ?

**Comment by erickinnear** [comment]
Yup, I'll put up a PR for this
