### ISSUE TITLE
Recovery: exit initial slow start on RTT increase

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#2728]
The current recovery spec says *7.2. Slow Start*: 
_QUIC begins every connection in slow start and exits slow start upon loss or upon increase in the ECN-CE counter. QUIC re-enters slow start anytime the congestion window is less than ssthresh, which only occurs after persistent congestion is declared. While in slow start, QUIC increases the congestion window by the number of bytes acknowledged when each acknowledgment is processed._ 

That's fine, but it is often advisable to exit the initial slow start before observing the first loss. Very often, the default behavior results in widely overshooting the "fair" window, leading to not just one loss but rather a series of losses. For example, implementations could monitor the evolution of the RTT during initial slow start, and exit slow start as soon that the measured RTT exits RTTMin + some margin -- maybe the min 1/8th of RTT and 10 milliseconds, or 1ms 1/8th of RTTMin was too small.

**Comment by martinthomson** [comment]
This really seems to be stepping into the realm of designing a congestion control algorithm.

**Comment by larseggert** [comment]
What @martinthomson said. For example, it's unclear whether leaving slow-start due to an RTT spike doesn't lead to situations where you're then stuck in congestion avoidance for a looong time.

**Comment by mirjak** [comment]
I guess you don't want write in the spec that slow start couldn't be left earlier in order to allow experimentation. But I would say that is not the intention of the current text and it should be fine as is.

**Comment by ianswett** [comment]
The TCP Cubic RFC has a section on slow start that says you can do standard slowstart, limited slowstart, or hystart: https://tools.ietf.org/html/rfc8312#section-4.8

We could add more text along those lines, but I'm not sure it's necessary?  Also, hystart is not in any RFC, from what I can find.

**Comment by mnot** [comment]
Out of scope.
