### ISSUE TITLE
Re-visit initial keys discard

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2741]
This was prematurely closed and got kicked out of the design team.

Here's my proposal for how to handle this
I propose that we apply effectively the same algorithm as elsewhere: you discard initial keys when you get an ACK for a packet that was sent with the handshake key

On the server side, this will generally be at the same time, because the server will likely bundle Initial and Handshake packets, and therefore the clients' second flight will contain the ACK for the server's first handshake packet.

On the client side, it is 1-RTT later, but for the reasons I argued in the meeting, I don't think that this changes the situation: an attacker who occupies a position between the client and the server can forge a bogus partial first server flight to the client faster than the server responds. Then, as required by the current spec language, the client will discard the Initial key and be unable to receive anything from the true server, so there is already a DoS, which is not made significantly worse by the proposal above.

As Kazuho has pointed out you can do better than this by keeping multiple candidate server flights, but that's extratextual, and would be in violation of the language you quote above. I suppose if we wanted to do better, we could require:

1. The server to drop keys when it receives a handshake ACK.
2. The client to drop keys on handshake complete

But this seems more complicated.

**Comment by ianswett** [comment]
This was previously discussed in #1951

**Comment by kazuho** [comment]
The proposed change brings symmetry to how Initial keys are discarded.

FTR, during the interim some folks discussed that there's another asymmetry and that introducing symmetry there helps us resolve an open issue; at the moment only the server is allowed to replace the CID when responding to an Initial packet. We could allow clients to do that as well, and that would resolve #2645.

**Comment by MikeBishop** [comment]
That would address one of @nibanks's scenarios for which he needs #2645.  I don't believe it would entirely remove that requirement.  However, I don't believe that's the same as this issue; that might warrant a separate issue.

**Comment by DavidSchinazi** [comment]
@MikeBishop I think #2645 is fairly different from this issue, and I'm not sure I understand how they interact. Perhaps filing a separate issue is best?

**Comment by MikeBishop** [comment]
"That" was @kazuho's comment.  I'll let him take it to a separate issue if he wants to pursue that suggestion.

**Comment by kazuho** [comment]
Re #2645, it is my understanding is that @nibanks is pushing for #2769. I am fine with the WG adopting that PR, hence have no intent to pursue the approach described in https://github.com/quicwg/base-drafts/issues/2741#issuecomment-496745243 at this moment.

**Comment by DavidSchinazi** [comment]
Thanks for clarifying @MikeBishop and @kazuho. In that case, let's keep the CID discussion separate from this one.

**Comment by larseggert** [comment]
Discussed in Cupertino. Close with no action.

**Comment by DavidSchinazi** [comment]
Unassigning from myself - next action item is for chairs to close with no action.
