### ISSUE TITLE
Automatic applicability of new TLS cipher suites

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2742]
Suppose that we had a future TLS cipher suite such as AES_OCB_SHA256. Would that work with QUIC without a new QUIC draft? The AEAD part is already clearly defined and given that AES-OCB uses AES, the same HP mechanism as we currently use with GCM can be used here. 
From my perspective, the desirable property is that if we add new TLS cipher suites with analogous cipher cores (block cipher and/or nonce-based stream cipher) to the existing spec, then no new QUIC document should be required.

An alternative design would be to just require a "QUIC applicability" paragraph in new TLS cipher suites analogous to the DTLS-OK IANA flag.

(see also #2019).

**Comment by mikkelfj** [comment]
How about header protection which depends on being defined for the negotiated AEAD?

**Comment by ekr** [comment]
That's what paragraph 2 above is about.
