### ISSUE TITLE
Idle Timer Can Fire Even with Outstanding Data to Send

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#2744]
If a connection gets send blocked for long enough (i.e. the peer application isn't draining the data right now, and thus not giving more flow control credit) the idle timer will fire. This is because no data is being sent over the wire while the sender is blocked. To me, it seems that we shouldn't consider a connection as idle if the application is actively trying to send.

While in this blocked state, should the transport periodically send some ACK eliciting packet to keep the connection alive?

**Comment by mikkelfj** [comment]
It is not much different from being blocked because there is currently nothing to send. The timeout will clean up connections that do not make progress. If the application is happy with waiting a very long time to proceed, it could send pings, but it might as well want to call it a day. So I'm not sure the spec needs to say anything about that. We are talking about 10 minutes of no progress by default.

**Comment by martinthomson** [comment]
It seems reasonable to use a keep-alive.  If you have something you want to use the connection for and you aren't able to maintain activity on the connection, then either poke it or - more likely - give up.  I don't think that we need a design change for this, but if you want to write some text, I wouldn't be opposed to taking a look.

**Comment by nibanks** [comment]
Thinking about this, another solution would be to continue to send a *blocked frame, while in the blocked state. Even if the peer acknowledged the first blocked frame, if you're still blocked, you send it again. Personally, for my implementation, this would be the easiest thing to implement.

I don't think the spec should make any requirements in this area, but I do think it should call this problem out and possibly make a recommendation.

**Comment by ianswett** [comment]
Sending a BLOCKED frame repeatedly, maybe on exponential backoff, makes sense to me.  @nibanks any interest in writing a PR for this one?

**Comment by nibanks** [comment]
I could definitely write a PR. We implement exactly this. I would argue though that it's not exponential. It's immediate and will go forever. The app has data to send. The connection is not idle, and should never idle out in this scenario. It's the app's responsibility to time out, if their protocol dictates as such (which it might not, if they expect to be blocked while a long running operation is processed).

**Comment by janaiyengar** [comment]
This should be a design issue. The proposal to send multiple BLOCKED frames is a design change.
