### ISSUE TITLE
HTTP error codes use inconsistent language

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2765]
During the London interim, it was noted that error codes refer to things being "malformed," "bad," "invalid," and "unexpected."  Pick one and use it consistently, or establish precise definitions for each.  This applies to both the current document and #2662.

**Comment by dtikhonov** [comment]
The three words are not equivalent: while both "malformed" and "invalid" are "bad," "malformed" is not the same as "invalid."

**Comment by LPardue** [comment]
Minor correction here, "bad" is only used in #2662. The only instance of "bad" in current document is a substring of example "0x1abadaba"

**Comment by MikeBishop** [comment]
Resolved by #3090 and something prior to it.
