### ISSUE TITLE
Remove QPACK settings maxima as useless

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#2766]
Both [QPACK settings](https://tools.ietf.org/html/draft-ietf-quic-qpack-08#section-5) specify the maximum value the decoder supports.  The encoder is free to pick and use a smaller value.  There is no reason to add artificial limits to the way an decoder is implemented.

**Comment by MikeBishop** [comment]
This could be viewed as an alternative resolution to #2498.

**Comment by MikeBishop** [comment]
Also, historical note:  These have maxima because settings used to be length-prefixed blobs.  By defining them to be integers of a maximum size, the length could be constrained.  Now that we use varints, there is a maximum structural size already.
