### ISSUE TITLE
Error code to be sent when the size of request headers exceed server's limit

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2775]
At the moment, the HTTP spec says that "an HTTP/3 implementation MAY impose a limit on the maximum size of the header it will accept on an individual HTTP message; encountering a larger message header SHOULD be treated as a stream error of type `HTTP_EXCESSIVE_LOAD`."

Is this the intended behavior?

IIUC, HTTP_EXCESSIVE_LOAD indicates a temporary issue inside the server; a client is allowed to retransmit the request in the future hoping that it would succeed. In contrary to that, I view the size of the request exceeding the maximum imposed by the server to be a permanent error, and therefore that a different error code should be used. Or even better a HTTP status code, because what we want here is not a hop-by-hop signal; the other benefit of suggesting the use of a HTTP status code is that it removes the risk of the connection getting shut down (an action that affects other requests).

**Comment by mikkelfj** [comment]
Makes sense - it is probably one of the few places where you actually benefit from an error other than HTTP_GENERAL_PROTOCOL_ERROR because you a making a qualified guess when sending blind.

**Comment by ianswett** [comment]
I agree, HTTP_EXCESSIVE_LOAD seems like the wrong error code here.

HTTP_GENERAL_PROTOCOL_ERROR or HTTP_REQUEST_REJECTED would be better.

Did you have an HTTP status code in mind for this case?  I believe HTTP status codes should be consistent across HTTP versions, so If neither HTTP or HTTP/2 are sending back a status code for this case, an HTTP/3 error code seems more appropriate.

**Comment by kazuho** [comment]
@ianswett Glad you asked.

I went back to check RFC 7540 and now realize that the only suggested behavior is:
> A server that receives a larger header block than it is willing to handle can send an HTTP 431 (Request Header Fields Too Large) status code [RFC6585].
> https://httpwg.org/specs/rfc7540.html#rfc.section.10.5.1

I think we should provide the same guidance in HTTP/3.

**Comment by ianswett** [comment]
Thanks for checking.  SGTM

**Comment by MikeBishop** [comment]
I'm fine importing that guidance.

**Comment by kazuho** [comment]
@MikeBishop Changes to #2774 look good to me. Thank you! :+1:
