### ISSUE TITLE
HTTP/3 Cookie Crumbling

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#2777]
@bencebeky notes that:
> [RFC7540](https://httpwg.org/specs/rfc7540.html#CompressCookie) allows crumbling cookies for compression efficiency with HPACK.  However, neither quic-http nor quic-qpack drafts mention cookies or crumbling.  Is it considered safe for a QPACK implementation to crumble cookies before compression and concatenate them after decompression?  If so, should the draft include clarification on this?

We need to normatively reference 7540 for this capability.

**Comment by bencebeky** [comment]
See also discussion thread starting at https://mailarchive.ietf.org/arch/msg/quic/DgMheH6mnosTw3vHnJW0gYD8dk4.
