### ISSUE TITLE
HTTP/3 has less concurrency than HTTP/2

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#2787]
At the moment, we state that "It is RECOMMENDED that initial_max_bidi_streams be no smaller than 100, so as to not unnecessarily limit parallelism."

This means that there is a reduction in parallelism compared to HTTP/2 that allows 100 concurrent requests, due to the following reasons:
1. unlike HTTP/2, a QUIC server is likely to consider a stream to be existing until receiving an ACK for the stream-level FIN that it has sent
2. even after the stream state is discarded (when receiving an ACK for FIN), a server might not immediately send a MAX_STREAMS frame to indicate the client can open new streams

IIUC, one of the primary reasons we want parallelism is to fulfill the bandwidth of a high latency connection even when the size of the HTTP responses are small<sup>2</sup>.

The differences pointed out above means that in such a scenario (where the responses are small, e.g. 304), the concurrency could go down from 100 requests per RTT in HTTP/2 to 50 in HTTP/3, because the minimal latency of retiring a stream state changes from 1 RTT to 2 RTT (see point 1 above).

I think we should provide some better guidance, assuming that we consider "100" that we have in HTTP/2 as a good advice.

One way would be to change the recommended minimum of initial_max_bidi_streams to 200. The other way would be to recommend servers providing clients "window to issue 100 requests in parallel," without giving them concrete suggestion on how, because the way the QUIC servers retain stream-level states and how they send MAX_STREAMS can be different.

2: The other reason is to provide sufficient amount of window for prioritization.

**Comment by mikkelfj** [comment]
I can in fact see a use case with much more than 200 concurrent requests, but then you would know that you need it, and a ramp up time might not be a big deal so the initial value is of less importance.

**Comment by kazuho** [comment]
Admittedly, I did not argue how appropriate it is to use initial value as a way of describing the expected parallelism. If we are to address that too, the suggestion would be more like the latter (i.e. "provide clients window to issue 100 requests in parallel").

**Comment by MikeBishop** [comment]
I'm more inclined toward that as well.  I agree that the recommendation is to allow ~100 concurrent requests, and transport implementations could decide to consider it safe to re-issue the stream at different points in the request lifecycle.

**Comment by LPardue** [comment]
I think its important to keep this recommended level of effective parallelism - deployment with HTTP/2 (and DoH) has seen these recommendations easily hit.

**Comment by ianswett** [comment]
@kazuho if you'd like to see some new text, either editorial or a slightly different recommendation, can you write a PR?

**Comment by kazuho** [comment]
This issue has been addressed by #2857.

Now, the text says: "It is RECOMMENDED that at least 100 requests be permitted at a time, so as to not unnecessarily limit parallelism." ([section 6.1](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#rfc.section.6.1))

**Comment by MikeBishop** [comment]
I think there's probably still room for some text in the HTTP/2 differences noting that the accounting is different, but that's a purely editorial change.
