### ISSUE TITLE
Use a higher seed RTT for new paths

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2789]
@gorryfair mentions on list:

>>   A connection MAY use the delay between sending a PATH_CHALLENGE and 
receiving a PATH_RESPONSE to seed initial_rtt for a new path, but the delay 
SHOULD NOT be considered an RTT sample.
>
> .... Maybe I am wrong, but I interpret RFC6298 as saying the seed value 
should be 1.5 x larger than this RTT value?
>
> (To account for RTT variance.)

I don't quite get the same reading from 6258 (the 0.5 seems to come from setting RTTVAR on the first sample, but that isn't fed into SRTT anywhere...), but this seems like a good idea, if only out of caution.  The new path might be longer.  But it's hard to say by how much.  Some hedging seems wise.  

The first RTT measurement will erase this, so it will only govern behaviour on unresponsive paths.  So it's probably not critical.

**Comment by rpaulo** [comment]
I also don't see where RFC6298 specifies 1.5x.  Can you clarify @gorryfair?

**Comment by ianswett** [comment]
I reread 6298 and I also can't find the 1.5 text.  Can you point out which text you have in mind?

The goal is not to base the new path's congestion control properties on the previous path, but if there was a PATH_CHALLENGE/RESPONSE before migrating, then it's ok to use that to seed the initial_rtt.

**Comment by gorryfair** [comment]
I missed this, and the text isn’t correct, but my comment was over-simplified  - and I am on vacation for a week, really sorry. 

So will get back after the vacation.

Gorry

**Comment by gorryfair** [comment]
I get this text. The vacation helped me, but I still struggle to work out the full pathology.

So, can we move forward: What happens if that "unmeasured" timeout period expires,  is the timeout re-initialized to increase it to 3 seconds [RFC6298] [RFC8085]. I think this conservative increase is necessary to avoid congestion collapse when many flows retransmit across a shared bottleneck with restricted capacity.

**Comment by ianswett** [comment]
I believe the relevant text is(?):
" (5.7) If the timer expires awaiting the ACK of a SYN segment and the
         TCP implementation is using an RTO less than 3 seconds, the RTO
         MUST be re-initialized to 3 seconds when data transmission
         begins (i.e., after the three-way handshake completes)."

I believe that's saying the RTO should be set to 3 seconds if any syn timers expired?  Do implementations(ie: Linux, Windows, etc) do that?  If so, that means a single packet loss in the handshake causes the RTO to increase to 3 seconds, but a subsequent data packet loss would not have that effect?

@gorryfair  If you're in Montreal Saturday or Sunday at the Hackathon, maybe we can talk about this more and figure out what to do here?

**Comment by gorryfair** [comment]
Yes, let’s talk Montreal.

I think your comments hold true - and this is about backing off an initial exchange, not about data when there has already been a handshake. In a @normal@ case, you should not see this happen. Talk to you sat (or if not, on sun).

Gorry

**Comment by mnot** [comment]
Discussed in Montreal; editors to prepare a PR.

**Comment by ianswett** [comment]
Gorry and I discussed this in Singapore, and I believe this issue stemmed from some poor word choice, which I and Jana fixed in editorial PRs while we were there.

As such, I don't think a further design change is necessary here.
