### ISSUE TITLE
Switch to big endian

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#28]
We had consensus in Seoul (which we should reconfirm on the list) about switching from little endian to big endian. This should probably happen in concert with the version number scheme that @martinthomson and @janaiyengar are hashing out.

**Comment by larseggert** [comment]
I started an email thread to confirm the consensus. Deadline Jan 6, 2017.

**Comment by mnot** [comment]
@janaiyengar please don't close design issues, we need to complete the call for consensus.

**Comment by janaiyengar** [comment]
Ah, apologies. I thought we had already wrapped up the consensus call -- I merged the PR, which automagically closed the issue. I'm happy to revert the (now merged) PR if consensus changes.

**Comment by larseggert** [comment]
Yep, was on my to-do list. Will send email to the group now.
