### ISSUE TITLE
Promising more than the client concurrency limit

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#281]
In HTTP/2, streams states were modified at the point that a PUSH_PROMISE was sent, but actually using that stream could be deferred.  The "reserved" state didn't count toward concurrency limit, those streams would count only when packets were first sent.

If the client had a low concurrency limit, that could mean that use of promised streams had to be deferred until active streams could be closed.  QUIC maintains a similar model, but that model is incompatible with QUIC.  In HTTP/2, any promised streams can be opened without creating any ambiguity about the state of other reserved streams.  HTTP/2 also allowed endpoints to skip stream numbers.

In QUIC the lack of ordering between streams (a feature!) forces us to insist on having a strict monotonic sequence of stream numbers.  If a stream number appears to be skipped, that is only because a packet using it has not yet arrived.  This ensures much simpler accounting for streams and avoids adding latency to stream creation.

This creates a problem for promises.  Servers cannot use streams in any order, only those streams within the window of streams permitted by the client concurrency limit are free to be used.

For example, a client could have an MSPC of 2.  That allows just one server push at a time.  A server that wants to push two resources could advertise one push on streams 4+6 and the other on 8+10.  However, unlike in HTTP/2 the server cannot start the second push first.  Opening stream 8 would imply that streams 4 and 6 are also open, violating the concurrency limit.

It's not clear that this problem needs a solution, but it is a functional regression that we should at least consider and make a conscious decision to accept.

**Comment by krasic** [comment]
Apologies for chiming in late.  

But it appears that this issue is a result of "simplifying" the state diagram to its present form as of the -02 mapping.    The previous reserved remote state exactly allowed the number of promises to be larger than the concurrency limit.    There would of course be a separate limit on the number of outstanding PUSH_PROMISES, and a corresponding ENHANCE_YOUR_CALM error when exceeded.   

I would propose adding back the "reserved" state as in the -01 revision.

**Comment by martinthomson** [comment]
This has nothing to do with the removal of the reserved state, which had no material effect on the protocol.  As you say, there was no limit on reserved streams.  Though the state doesn't appear, the value is still unlimited.  The problem is that you can't *use* a reserved stream.

**Comment by krasic** [comment]
Ok, but the state diagram in the -02 mapping draft indicates that a stream can be opened if a higher stream id was received.   In effect, this means opening one stream can imply the opening of others.  This was not the case in the prior state diagram.   Also, the text of prior revisions may have not called it out, but having a limit associated with the number of reserved streams independent of the number of open streams is the natural way to allow promises beyond the concurrency limit, but within a (higher) bound.

**Comment by martinthomson** [comment]
The change to have a stream open when a higher-numbered stream is used is a bug fix that was made at the same time as removing reservation.  You have to account for streams that you haven't seen, but are open anyway otherwise you have uneven accounting for concurrent streams.

**Comment by martinthomson** [comment]
Closed by #701.
