### ISSUE TITLE
Guidance for propogation of errors between H2 and H3

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#2817]
An intermediary that converts between HTTP/2 and HTTP/3 is likely to end up needing to propagate errors between the protocols. We don't have much guidance for this.

Some points from the mailing list discussion on this:

* Suspect an intermediary that receives error codes from the upstream would convert many of these to 502 errors
* The REJECTED error code is a possible exception to the above behaviour
* It may be preferable to propagate "temporary" errors (REFUSED_STREAM) and CONNECT_ERROR (the use case related to websocket usage, although there is no formal HTTP/3 websockets yet).

**Comment by martinthomson** [comment]
So the editors discussed this and concluded that while this would be very nice to have, we need a PR in order to do anything.  Lucas, you seem to be the resident expert here, so I'm assigning this to you.

**Comment by LPardue** [comment]
Sure. Amusingly since I created this issue we decided to shift the error code space in H3 so that there is no implicit mapping. Therefore I'm inclined to start by addressing that simple point first and then more specific points captured in the issue (if they are still relevant after the shuffle). I'll start on a PR and will probably seek some input from @kazuho who seemed to have some opinion on this topic during past discussion and some experience in actually mapping H2 and H3.

**Comment by MikeBishop** [comment]
Discussed in Cupertino; we want this guidance, but non-normative.  @LPardue to author PR.

**Comment by LPardue** [comment]
I'll refresh my context based on recent updates and get started on a PR soon.

**Comment by MikeBishop** [comment]
If non-normative, then non-design.
