### ISSUE TITLE
CANCEL_PUSH edge cases

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#2819]
I think there are some edge cases with the CANCEL_PUSH frame that we don't explain: 

* reception of a CANCEL_PUSH frame with ID greater than the current push limit
* reception of CANCEL_PUSH with ID that has already been used

**Comment by martinduke** [comment]
I'd also add a CANCEL_PUSH from the client for a PUSH_ID that has not been promised.

**Comment by MikeBishop** [comment]
CANCEL_PUSH with a reused ID is probably indistinguishable from receiving one for a stream that's already open; you SHOULD reset the stream (which is a no-op if the stream is already full transferred).
