### ISSUE TITLE
Proposal for Handling Issues with NAT due to QUIC being a UDP protocol

### ISSUE THREAD

**Issue by john01dav** [quicwg/base-drafts#2824]
I recently read [Cloudflare's blog post on QUIC](https://blog.cloudflare.com/the-road-to-quic/), and one of the issues that they stated that QUIC needs to solve before becoming viable is the issue of NATs blocking UDP packets as the normal TCP connection based system won't work. As I read this, a possible solution jumped out at me: ipv6. With ipv6, there almost never NAT, so this issue is eliminated. If QUIC were to become an ipv6-only protocol, designed to be deployed along-side traditional HTTP for legacy clients, then it could encourage ipv6 deployment. There is precedent for something like this, where a new protocol is only available if some other improvements go with it. When HTTP/2.0 came out (and SPDY before it), most client implementations set it up to only work with TLS-enabled connections. In this way, any website that wants to take advantage of the performance benefits of HTTP/2.0 must also setup TLS, making the Internet a better place. ipv6 support will have to happen eventually, and right now it is mostly held back because many networks refuse to support it as there is little advantage (read: profit) to doing so right now. QUIC being an ipv6-only protocol would create an advantage to ipv6 deployment, especially for mobile websites as at least one major mobile network already supports ipv6 (T Mobile)¹. This would allow the world to move past ipv4 more quickly, by making ipv6 a more viable protocol by itself. 

1: This point is especially important because generally mobile devices have carrier-grade NAT, if any, thus making a mobile network's deployment of ipv6 particularly beneficial. Furthermore, the main areas where QUIC shines (packet loss and high latency) are particularly common on mobile networks compared to wifi or wired networks.

**Comment by RyanAtGoogle** [comment]
According to this post:

https://blog.apnic.net/2018/05/15/how-much-of-the-internet-is-using-quic/

QUIC accounts for up to 7.8% of the total traffic volume on the internet. I'd say it's already viable.

**Comment by mikkelfj** [comment]
In Athens those 7.8% would have to be consumed by nearly every IPV6 endpoint:
https://www.gr-ix.gr/ipv4-ipv6-ratio/

**Comment by mikkelfj** [comment]
https://www.google.com/intl/en/ipv6/statistics.html

**Comment by mikkelfj** [comment]
I find this proposal impractical. However, I could imagine a new QUIC version that would fully rely on IPv6 and perhaps simplify various other aspects. If such a version were to arrive soon, then indeed it might help push IPv6 as well as simplify the protocol.

**Comment by mikkelfj** [comment]
Fun fact: According to above link, Denmark has 3.31% IPv6 adoption, and Germany just a few degrees south, slightly south, has a whopping 42.16% adoption rate. I guess someone didn't distribute IP blocks according to population count?

**Comment by ianswett** [comment]
I'd like to accelerate IPv6 deployment and I can imagine a future version of QUIC being v6 only, but I can't think of any critical technical benefit to making QUIC v6-only, so this seems well out of scope for QUIC v1.

**Comment by mnot** [comment]
This isn't a spec change (QUIC is chartered to work on the existing Internet, including IPv4).
