### ISSUE TITLE
Consider adding flags transport parameter for extension, frame, or feature negotiation

### ISSUE THREAD

**Issue by chris-wood** [quicwg/base-drafts#2839]
`disable_migration`, for example, is a boolean parameter that conveys one bit of information with a zero length value. There are likely to be more parameters like this in the future. There's currently an I-D in TLS that describes an extension for these sorts of boolean flags [1]. Maybe it'd be useful to allocate space for a similar bitmap in QUIC's TPs, too?

[1] https://datatracker.ietf.org/doc/draft-nir-tls-tlsflags/

**Comment by mikkelfj** [comment]
In principle you could also negotiate feature masks that way. Client says, I have this mask, server says I have this mask. AND them together and see of the result makes sense.

**Comment by ianswett** [comment]
One could also imagine changing disable_migration from a bool to an enum, if we want to describe a wider variety of functionality?  I'm not sure if that's better or worse than a bitmap, but it's certainly more descriptive than a bool.

**Comment by DavidSchinazi** [comment]
This is interesting but it can also be implemented as an extension, so I'd personally recommend waiting until after QUICv1 ships to avoid delaying the core spec.

**Comment by martinthomson** [comment]
I think that David is right about this.  We have just one transport parameter that could use this right now, so anything we do is strictly worse.  Also, TLS haven't really settled any of the details of the flags proposal.  We can avoid doing the same work in parallel, so to avoid creating similar but confusing mechanisms, so we should.

My proposal: quicv2.

**Comment by chris-wood** [comment]
> My proposal: quicv2.

That works for me!
