### ISSUE TITLE
Does rejecting 0-RTT data prohibit ACKing 0-RTT data?

### ISSUE THREAD

**Issue by RyanAtGoogle** [quicwg/base-drafts#2840]
4.6 Of the TLS doc says:

   A server rejects 0-RTT by rejecting 0-RTT at the TLS layer.  This
   also prevents QUIC from sending 0-RTT data.

However, this doesn't explicitly say that it prevents QUIC from **receiving** 0-RTT data. I suspect this is implied, but it might be worth clarifying. 

I could imagine a server rejecting 0-RTT data, but attempting to ACK the client's 0-RTT packets in order to deliver a congestion signal to the client. I think this would be a rather terrible idea, so it would be nice to explicitly prohibit it.

**Comment by ianswett** [comment]
Throughout transport, there is the idea that you MUST not acknowledge packets you can't fully process, so this should be against the spec.  But it may be worth noting explicitly, probably in transport.

**Comment by RyanAtGoogle** [comment]
Doing it in transport would make sense. Or perhaps in TLS by noting that if 0-RTT is rejected, 0-RTT keys must not be generated.

**Comment by marten-seemann** [comment]
@RyanAtGoogle I just added text about that to my PR that's targeting #2829.

**Comment by ianswett** [comment]
SG @marten-seemann  If so, can you update the CL description to indicate what issues it closes?

**Comment by martinthomson** [comment]
I'm going so recommend that this be triaged as a design issue, even if it might seem trivial.  The prohibition in #2829 is the right response.
