### ISSUE TITLE
Policing packet number size

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#285]
From the document:

> DISCUSS: Should the receiver be required to enforce this rule that the sender MUST NOT exceed the inflight limit? Specifically, should the receiver drop packets that are received outside this window?

As a reminder, we require that the packet number size be determined based on the number of outstanding (undefined, but assumed to be packets that are sent but not yet acknowledged).

A requirement like this would be virtually impossible to enforce.  The receiver would have to know what of its acknowledgments had arrived at the sender in order to know what was outstanding when the sender generated the packet.  That's only possible in a narrow set of cases.

**Comment by ianswett** [comment]
I would lean towards not enforcing it.  And if one was going to enforce it, there should be a connection close error associated with it, because debugging silent failures would be virtually impossible.
