### ISSUE TITLE
Retransmission Instructions do not include NEW_TOKEN

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2871]
Sec 13.2 of QUIC Transport explains what to do for the loss of a packet for every stream type except NEW_TOKEN.

IMO it's nice but not critical to repair this loss, but I care less about how we resolve it than that we write it up.

**Comment by ianswett** [comment]
Somewhat related question: Does this section fit better in the recovery draft?

**Comment by martinthomson** [comment]
I don't think so.  This talks about the repair semantics of these frames, not the process of detecting loss.  Recovery doesn't care about the distinction between PING and STREAM when it comes to repair.
