### ISSUE TITLE
Appendix A of quic-tls is wrong

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2885]
The initial salt changed in draft-21, but there is no change to the example initial keys.

**Comment by martinthomson** [comment]
Yes, we also didn't update the examples to include the new invariants.  Oh well.  There's updated test vectors in #2887, but those are for -23.  If you want test vectors for -22, you can tweak the version and salt in the .js file in the repo and run that.  If that doesn't work, let me know and we can work out what is wrong.

For now, I just have to humbly apologize again for the mess that I made of all these drafts this time around.
