### ISSUE TITLE
Crypto Retransmission Timeout interacts poorly with Congestion Control

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#2886]
The crypto retransmission timeout works similar to the PTO timeout. On each timer expiration, you are supposed to send some data, and do an exponential backoff.
However, there's an important difference: PTO packets are not blocked by the congestion controller, whereas crypto retransmissions are. 

This can lead to a deadlock: Consider the case where the CFIN is lost, and the client sends all the available window of application data. When the crypto retransmission timer fires, the client would be supposed to retransmit the CFIN, but the congestion controller will not allow that. Furthermore, since the CFIN was lost, the server won't be able to read any of the 1-RTT packets, so cwnd will never be cleared.

**Comment by ianswett** [comment]
It was not intended for crypto timeout retransmissions to be blocked by the congestion controller.

Does PR# 2806 fix this by merging them?
