### ISSUE TITLE
HTTP/2 in Peer Denial of Service?

### ISSUE THREAD

**Issue by zz85** [quicwg/base-drafts#2890]
Under the section _Peer Denial of Service_ of TLS draft, a referenced was made to HTTP/2.

https://github.com/quicwg/base-drafts/blame/master/draft-ietf-quic-tls.md#L1393

I was wonder if this is in fact referring to HTTP/3 or HTTP/2. Also curious why the section is labelled `{#useless}`

**Comment by martinthomson** [comment]
That mention of h2 was a mistake.

I've made a few changes after reviewing this.

(The `{#useless}` thing is a joke.)
