### ISSUE TITLE
Advise bundling a PING or other small ACK eliciting frame with Initials

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#2895]
When there is nothing to send today, the text says you can send a PADDING only packet.

These packets will be removed from flight when Initial keys are dropped, but it may never be acknowledged, which loses some congestion control signal, including RTT measurements.

For PTO, we decided you always send a PING if PTO expires and there's nothing to send.  It seems like we should say the same for the handshake case now that it's part of PTO?

This came from Ryan's comment on #2806

**Comment by martinthomson** [comment]
Not sure that this helps all that much.  Even though you might be eliciting an acknowledgment, you will still lose the packet when you discard keys, which could still happen.  All you have done is increase the work that the recipient needs to perform.

**Comment by ianswett** [comment]
It doesn't help that much, but it's a lot more consistent with the rest of the PTO design, so I think it's preferable.

**Comment by martinthomson** [comment]
In discussing our PTO strategy yesterday I realized that you only send a packet if you have something ack- eliciting outstanding. Would you not want to send that again?

**Comment by ianswett** [comment]
Sometimes you can't send that again once the handshake is confirmed(there's an example in the text, but the easiest is something unreliable like DATAGRAM).

Prior to handshake confirmation, the client needs to drive the handshake to confirmation so it may have to send something, as your PR #2881 discusses

**Comment by martinthomson** [comment]
Makes sense to me.  I hadn't considered data that isn't retransmitted after loss, which is a little embarrassing.

**Comment by janaiyengar** [comment]
This seems reasonable. The RTT estimate could be quite wrong at this stage in the connection, so an ack-eliciting packet can be used to improve that as well.
