### ISSUE TITLE
DCID Len's description should be updated in draft-ietf-quic-transport-22

### ISSUE THREAD

**Issue by mengguer** [quicwg/base-drafts#2897]
the description of DCID Len in draft-ietf-quic-transport-22 not update from transport-21:
![image](https://user-images.githubusercontent.com/9623979/61195416-6cdd7b80-a6fa-11e9-9833-ece3fe82f7a3.png)

**Comment by martinthomson** [comment]
Fixed in editor's draft:
![image](https://user-images.githubusercontent.com/67641/61196361-79b99980-a711-11e9-9b1a-22a679c39a63.png)
