### ISSUE TITLE
Should server TP encryption be a requirement for the cryptographic handshake?

### ISSUE THREAD

**Issue by chris-wood** [quicwg/base-drafts#2920]
The TPs might carry a stateless reset token, which must be encrypted in transit. Section 7 in the transport document [1] lists some requirements for the handshake, including authentication of the TPs, yet does not include any mention of encrypting them from server to client. Should it? 

cc @DavidSchinazi @martinthomson 

[1] https://tools.ietf.org/html/draft-ietf-quic-transport-22#section-7

**Comment by DavidSchinazi** [comment]
This makes sense to me. The TLS document ensures that the server's transport parameters are encrypted so an editorial PR changing the transport doc to require that should be sufficient.

**Comment by martinthomson** [comment]
Good catch.  Marking as design so that we can consensus call this, but it's arguably editorial.
