### ISSUE TITLE
Does the connection id need to be in a consistent location?

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#293]
@martinthomson created a header proposal that provides a fixed 8 byte connection id in a fixed location.  

We need to decide if this is a requirement or a nice to have.

I haven't found any environments it needed to be in a fixed location for all packets, as long as it's easy to determine where it will be from the first byte of the packet.

**Comment by martinthomson** [comment]
I thought that it was nice to have, but not a deal-breaker.

**Comment by ianswett** [comment]
Agreed.

**Comment by MikeBishop** [comment]
#361 purports to address this; please re-open or file a new issue if that's incorrect.
