### ISSUE TITLE
Non-ACK-eliciting packets never need to be ACKed

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#2931]
By definition, non-ACK-eliciting packets never need to be ACKed.  Verbiage introduced in PR #2794 states:

> When only non-ACK-eliciting packets need to be acknowledged, ...

I am not sure what the intended meaning was.  Perhaps what was meant is "when only non-ACK-eliciting packets have not been acked,..."  We could try to find a more graceful way to phrase it.

**Comment by mikkelfj** [comment]
Non-ack-eliciting packets do need to be ack'ed, they just don't trigger the process.

**Comment by dtikhonov** [comment]
OK -- closing.
