### ISSUE TITLE
Omission of DCIL change in draft-ietf-quic-transport-22?

### ISSUE THREAD

**Issue by evagld** [quicwg/base-drafts#2932]
I'm currently working on an implementation of the protocol and have juste realized the changes in the last draft of RFC about the DCIL and SCIL. 
Reading the changes, I noticed that the DCID Len didn't change in the draft, opposed to the SCID Len, which doesn't seem rigth :
 "_DCID Len: The byte following the version contains the lengths of the two connection ID fields that follow it. These lengths are encoded as two 4-bit unsigned integers. The Destination
 Connection ID Length (DCIL) field occupies the 4 high bits of the byte and the Source Connection ID Length (SCIL) field occupies the 4 low bits of the byte. An encoded length of 0 indicates that the connection ID is also 0 bytes in length. Non-zero encoded lengths
 are increased by 3 to get the full length of the connection ID, producing a length between 4 and 18 bytes inclusive. For example,  a byte with the value 0x50 describes an 8-byte Destination
 Connection ID and a zero-length Source Connection ID_."
Is it an omission of change or have I missed something?

**Comment by martinthomson** [comment]
The [editor's drafts](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#long-header) contain the fix already.
