### ISSUE TITLE
Layout of PreferredAddress

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#2944]
The PreferredAddress structure has a variable length field right in the middle of it.  Since the CID is the only variable length field, we could make it slightly easier to implement by moving the CID to the end:

```
  struct {
     opaque ipv4Address[4];
     uint16 ipv4Port;
     opaque ipv6Address[16];
     uint16 ipv6Port;
     opaque statelessResetToken[16];
     opaque connectionId<0..18>;
   } PreferredAddress;
```

**Comment by DavidSchinazi** [comment]
Google's QUIC implementation uses a TLS encoding parser so changing the order of fields would not impact our implementation complexity. I'm inclined to push back against encoding changes at this point, but I don't feel incredibly strongly here.

**Comment by martinthomson** [comment]
We're similarly equipped and disinclined toward change.

**Comment by MikeBishop** [comment]
I agree that this would be an improvement, but I'm not sure the benefit is significant.

**Comment by mikkelfj** [comment]
Minor change but the annoyance will stay forever, so I think it is worth going for.

**Comment by huitema** [comment]
You gotta be kidding. No time for such changes now....

**Comment by larseggert** [comment]
Discussed in Cupertino. If we decide to do #3087 , we will do this as part of it, otherwise we won't.
