### ISSUE TITLE
What if server does not send HTTP_EARLY_RESPONSE but starts sending response

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#2963]
There is a text that say:

> A server can send a complete response prior to the client sending an
>    entire request if the response does not depend on any portion of the
>    request that has not been sent and received.  When this is true, a
>    server MAY request that the client abort transmission of a request
>    without error by triggering a QUIC STOP_SENDING frame with error code
>    HTTP_EARLY_RESPONSE, sending a complete response, and cleanly closing
>    its stream.  Clients MUST NOT discard complete responses as a result
>    of having their request terminated abruptly, though clients can
>    always discard responses at their discretion for other reasons.

A server MAY send STOP_SENDING. What should the client do if the server does not send it? Is the client allowed to close the send stream or should it continue until everything has been sent? In the second case the client may receive the complete response before the complete request has been sent. Is there a use case where a sever can send a response before receiving the complete request, but still cares about the request data?

**Comment by MikeBishop** [comment]
Good question.  From a purely transactional point of view, if no part of the response depends on the remainder of the request, the client might as well stop sending.  However, I can also imagine an API where the server wants to consume and store the remainder of what the client is sending even if the return value is determined already.

The most generic way to handle this is to say that the server can express that it doesn't need the remainder of the response, and if it doesn't do so, the client SHOULD finish sending it.

**Comment by MikeBishop** [comment]
Another potential case where the server would want to keep the client sending is where the server is performing some transformation (compress/decompress, transcode, en/decrypt, etc.) on the data sent by the client, and is doing the conversion in blocks as bytes are received rather than storing the full resource locally.

The same recommendation stands -- unless the server exercises the option to tell the client to stop, the usual rules apply that the client needs to fully send the request to get a full response.  Do we need text for this?  I'd think that's already the default position.

**Comment by martinthomson** [comment]
Maybe add that blurb.  I'd recommend marking this as editorial on that basis.

**Comment by ianswett** [comment]
The text is now:

> A server can send a complete response prior to the client sending an
   entire request if the response does not depend on any portion of the
   request that has not been sent and received.  When this is true, a
   server MAY abort reading the request stream with error code
   HTTP_EARLY_RESPONSE, send a complete response, and cleanly close the
   sending part of the stream.  Clients MUST NOT discard complete
   responses as a result of having their request terminated abruptly,
   though clients can always discard responses at their discretion for
   other reasons.

**Comment by MikeBishop** [comment]
Discussed in Cupertino; http-core will or should say that clients have to send the full request.  Point to core or clarify.

**Comment by MikeBishop** [comment]
http-core [says](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#header.expect):
> A server that responds with a final status code before reading the entire request payload body SHOULD indicate whether it intends to close the connection (see Section 9.7 of [Messaging]) or continue reading the payload body. 

I think the resolution here is to explicitly map STOP_SENDING(EARLY_RESPONSE) to the indication that it intends the stream to be fully closed after the response, and the absence of STOP_SENDING to the server's intent to continue reading the payload body.

**Comment by RyanAtGoogle** [comment]
Does it matter if the the STOP_SENDING error code is something other than EARLY RESPONSE?
