### ISSUE TITLE
Remove the quic parameter from Alt-Svc

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#297]
Ostensibly, the `quic` parameter is a performance optimization for Alt-Svc.  A client can learn what QUIC version is most likely to succeed and use that version.  That increases the chances that version negotiation succeeds and thereby reduces the chance that the QUIC connection setup costs an extra round trip.

However, alternative services is precisely the point where performance is not critical.  The client already has a perfectly functional HTTP/1.1 or HTTP/2 connection to the server.  This is a point where they could afford an additional round trip on connection setup.

@MikeBishop suggested that if we are serious about greasing version negotiation, perhaps we could remove the `quic` parameter from the Alt-Svc header field and force clients to always pick a greased version number for their initial packet.

Advantages: grease more often and version negotiation actually gets a real workout, disadvantages: an extra round trip every time you use Alt-Svc.

This came up in #278.

**Comment by martinthomson** [comment]
OK, duplicate of #296.

**Comment by MikeBishop** [comment]
Race!
