### ISSUE TITLE
What's the difference of closing and resetting a stream?

### ISSUE THREAD

**Issue by tandf** [quicwg/base-drafts#2971]
In draft-ietf-quic-http-22

> A sender can close or reset a unidirectional stream unless otherwise
   specified.  A receiver MUST tolerate unidirectional streams being
   closed or reset prior to the reception of the unidirectional stream
   header.

Is there a difference between closing a stream and resetting a stream?
According to my understanding, the only way here for the peer to end a stream is by sending a RESET_STREAM frame. Sure it can lalso end the stream by closing the connection, but obviously it's not what the text means.
Maybe the difference between these two terms needs to be clarified, if there is any.

**Comment by LPardue** [comment]
In this case, the peer could close the stream with a FIN.

**Comment by tandf** [comment]
Thank you for your reply. I forgot FIN. So the peer can send a QUIC STERAM frame, whose Stream Data field has a length of 0 to close the stream. Thanks again.
