### ISSUE TITLE
Empty NEW_TOKEN

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#2978]
It makes absolutely no sense to allow NEW_TOKEN to be empty, but we never really said that explicitly.  So let's do that.  @marten-seemann opened #2977 for that.

Unfortunately, this is technically a design change, and we are that point.  So let's do this by the book.

**Comment by mikkelfj** [comment]
Would a token of length 1 be any better? We already have that tokens must be unique and different from other token types.

**Comment by martinthomson** [comment]
Yes.  At least then we have a clear signal that a token was provided.  Now, it's probably still awful (though it might be stateful and so not *completely* awful), but absent some strong signal about how short things can be we're in much the same state we are with connection IDs.  We now allow those to be 1 byte long, with similar results.

**Comment by kazuho** [comment]
My weak preference is to not forbid 0-byte tokens, as it would be something that stacks would be forced to implement, just to pass the conformance tests.

It does not provide us any benefit (as @mikkelfj points out), while requiring stacks to have the check implemented.

**Comment by mikkelfj** [comment]
@martinthomson I see the point. There is already text in initial packets stating

"Token Length:
A variable-length integer specifying the length of the Token field, in bytes. This value is zero if no token is present. "

**Comment by marten-seemann** [comment]
Allowing 0-length token requires the receiver to filter them out before saving them to their token store (however that is implemented) for reuse in a connection in the future. If you don't do this, you might go and retrieve a token from the token store, use it on an Initial packet, just to end up in the situation that you're actually not using a token at all.

I disagree with @mikkelfj here. A stateful implementation could for example generate tokens by drawing random numbers between 0 and (a big value of) N. Occasionally, this will result in small token lengths, without compromising on the desired privacy properties.

**Comment by mikkelfj** [comment]
@marten-seemann there is nothing to disagree with, or thumbsdown - it was a question.

**Comment by marten-seemann** [comment]
Fair enough, that's a legitimate question, and I hope that I could provide a satisfying answer.
Removed my thumbsdown.

**Comment by kazuho** [comment]
@marten-seemann That's a good point. That makes sense - I can see the value of  using "0" as a signal to indicate the "absence" of the token throughout the specification, considering the fact that it is used that way at some parts of the spec.

**Comment by ianswett** [comment]
I'm not sure why you'd want to do this, but an empty NEW_TOKEN could be used to indicate the past tokens are no longer valid, but the peer isn't getting a new one(at least yet).  That is the practical implication of the way it's written today(later tokens are likely better than earlier, etc).

**Comment by martinthomson** [comment]
Yeah, that's just confusing.  The semantics of NEW_TOKEN don't imply invalidation.  We'd have to explicitly say that if NEW_TOKEN.size == 0, all previous tokens are invalid.  And then you have to also address the case of reordering and retransmissions of old NEW_TOKEN frames that arrive after the empty one.  Let's not go there.
