### ISSUE TITLE
Confused about Header Protection Application?

### ISSUE THREAD

**Issue by Ainiroad** [quicwg/base-drafts#2994]
In [tls draft](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#rfc.section.5.4.1)
Section 5.4.1 figure 4 shows a sample algorithm for applying header protection:
```
mask = header_protection(hp_key, sample)

pn_length = (packet[0] & 0x03) + 1
if (packet[0] & 0x80) == 0x80:
   # Long header: 4 bits masked
   packet[0] ^= mask[0] & 0x0f
else:
   # Short header: 5 bits masked
   packet[0] ^= mask[0] & 0x1f

# pn_offset is the start of the Packet Number field.
packet[pn_offset:pn_offset+pn_length] ^= mask[1:1+pn_length]
```
I think pn_length should be calculate after decode packet[0], like:
```
mask = header_protection(hp_key, sample)

if (packet[0] & 0x80) == 0x80:
   # Long header: 4 bits masked
   packet[0] ^= mask[0] & 0x0f
else:
   # Short header: 5 bits masked
   packet[0] ^= mask[0] & 0x1f

pn_length = (packet[0] & 0x03) + 1 // move here

# pn_offset is the start of the Packet Number field.
packet[pn_offset:pn_offset+pn_length] ^= mask[1:1+pn_length]
```

Do I have any misunderstanding? 
Thanks a lot!

**Comment by mikkelfj** [comment]
The algorithm is for applying header protection. The text just above says:

> Removing header protection only differs in the order in which the packet number length (pn_length) is determined.

**Comment by Ainiroad** [comment]
> The algorithm is for applying header protection. The text just above says:
> 
> > Removing header protection only differs in the order in which the packet number length (pn_length) is determined.

understood,  thanks!!!
