### ISSUE TITLE
QPACK decoder stream buffer grows without bounds

### ISSUE THREAD

**Issue by tatsuhiro-t** [quicwg/base-drafts#2999]
If I understand correctly, the decoder stream buffer which endpoint has to keep grows indefinitely if encoder-side app does not return back flow control credit.
The number of Header Acknowledgement instruction is bounded by the number of max blocked streams which decoder can specify.
On the other hand, the number of Stream Cancellation is not bounded.  So if encoder-side app keeps resetting stream without sending MAX_STREAM_DATA, decoder-side has to keep all closed stream in decoder stream.  I'm not sure this has been discussed already.

**Comment by MikeBishop** [comment]
The solution to this seems implementation-dependent, but implementations should place a bound on the amount of data waiting to be sent on the decoder stream.

**Comment by MikeBishop** [comment]
Hypothetically, this limit would create a way to force the peer to kill the connection by starving the decoder stream of flow control credit and then cancelling lots of streams.  However, the consumer of (and therefore the entity which could fail to read) the decoder stream is the encoder, and the encoder can trivially cause the connection to close by emitting an invalid instruction anyway.  That seems fine.

**Comment by dtikhonov** [comment]
@tatsuhiro-t writes:
> The number of Header Acknowledgement instruction is bounded by the number of max blocked streams which decoder can specify.

This is incorrect: an [acknowledgement is sent](https://tools.ietf.org/html/draft-ietf-quic-qpack-11#section-4.4.1) for each header that references the dynamic table.
