### ISSUE TITLE
Rename transport parameters

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#300]
The cryptic 4 lettter names for these are a relic of the encoding in Google QUIC.  We can afford to use words since we're identifying them with numbers (assuming #122 ever moves). For example,

* MSPC → maximum concurrent streams (or max_streams)
* CFCW → initial connection flow control offset (conn_fc_offset)
* SFCW → new stream flow control offset (str_fc_offset)
* etc...

**Comment by RyanAtGoogle** [comment]
Great idea. Using the full words sounds clearest to me.
