### ISSUE TITLE
There is no STOP_WATING frame in IETF quic

### ISSUE THREAD

**Issue by Ainiroad** [quicwg/base-drafts#3001]
In google quic, there is STOP_WAITING frame, and it was designed to be that:
> To limit the NACK ranges to the ones that haven't yet been
   communicated to the peer, the peer periodically sends STOP_WAITING
   frames that signal the receiver to stop waiting for packets below a
   specified squence number

But there are no STOP_WAITING frame in IETF quic, what's your consideration about that?
Thanks a lot!

**Comment by marten-seemann** [comment]
See #358.

**Comment by Ainiroad** [comment]
Thanks!
