### ISSUE TITLE
Some questions about Packet Number Encoding And Decoding

### ISSUE THREAD

**Issue by Ainiroad** [quicwg/base-drafts#3002]
Thank you guys a lot! I have some questions about Packet Number Encoding And Decoding

In transport draft Section `17.1. Packet Number Encoding and Decoding`
>For example, if an endpoint has received an acknowledgment for packet 0xabe8bc, sending a packet with a number of 0xac5c02 requires a packet number encoding with 16 bits or more; whereas the 24-bit packet number encoding is needed to send a packet with a number of 0xace8fe.

1. What's the purpose of Packet Number Encoding? to be safe or save some bits space or something else?

> A peer receiving the packet will then correctly decode the packet number, unless the packet is delayed in transit such that it arrives after many higher-numbered packets have been received. An endpoint SHOULD use a large enough packet number encoding to allow the packet number to be recovered even if the packet arrives after packets that are sent afterwards.

2. How can an endpoint know to use a large enough packet number encoding? For example, as example 1 said, an endpoint can send 16 bits to send a number of 0xac5c02 if peer has received an acknowledgment for packet 0xabe8bc, which means it will send 0x5c02. So in the early time when it want to send 0x5c02 exactly(not 0xac5c02), How should it encode packet number to avoid conflict with 0xac5c02 if the packet is delay so much.

3. If an endpoint is not encoded packet number well, the peer will recover it as a wrong packet number, what happens next?

**Comment by martinthomson** [comment]
@Ainiroad I'd like to request that you take these questions to our [mailing list](mailto:quic@ietf.org).  This issue list really isn't the best place for this sort of query.

**Comment by Ainiroad** [comment]
Sorry for that!
Thanks!

**Comment by martinthomson** [comment]
No worries.  As [our contributing doc](https://github.com/quicwg/base-drafts/blob/master/CONTRIBUTING.md) says, we use this to track issues, not as a general discussion forum.
