### ISSUE TITLE
Unclear how short header packets should be matched to connections

### ISSUE THREAD

**Issue by nanokatze** [quicwg/base-drafts#3006]
Section 5.2 of current draft (22) doesn't explain how one should match short headers to connections.  Does one first check if one has a connection associated with the address/port tuple and then use Connection ID?

**Comment by mikkelfj** [comment]
You cannot assume that the src port is always stable because of NAT rebinding. Perhaps not even the IP address. So you should look up the CID first. On the other hand, some CID's are zero length. In this case you can assume the address is stable, so you would use the tuple for connection lookup.

**Comment by martinthomson** [comment]
@mikkelfj has it about right, though I would point out two things: you choose how long the connection ID is based on your understanding of requirements.  Zero-length is basically only for when you have a unique address for the connection at your end.

The other is that this is not the best place to ask questions.  Try our [mailing list](mailto:quic@ietf.org).

**Comment by nanokatze** [comment]
Thanks for clarifying. Though I did not create the issue just as a plain question but rather to express that I believe the order of actions of matching a short header to connection isn't very clear as described in the current draft.

**Comment by martinthomson** [comment]
> Hosts try to associate a packet with an existing connection. If the packet has a Destination Connection ID corresponding to an existing connection, QUIC processes that packet accordingly.

I'll concede that this should probably say "processes that packet for the identified connection" or something along those lines, but I don't see how this is ambiguous otherwise.
