### ISSUE TITLE
The QUIC bit in stateless resets

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3008]
Do we need discussion on the fixed QUIC header bit in the triggering packet and outgoing reset packet?

_Originally posted by @mikkelfj in https://github.com/quicwg/base-drafts/pull/3007#issuecomment-528706518_

**Comment by marten-seemann** [comment]
Maybe I'm misunderstanding the question, but isn't the spec is completely clear on that? A stateless reset has the first bit unset and the second bit set.

**Comment by ianswett** [comment]
Agreed, I think this is already clear and I don't see any need to change it.

**Comment by martinthomson** [comment]
Thanks both.  I just wanted to check and didn't feel like I had the brain cells to answer that.  I don't like relying on the image only, but the text says "two fixed bits", and stateless reset - unlike Version Negotiation - is version-specific.  So I'm closing with no action.
