### ISSUE TITLE
Original/Initial Connection ID

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3011]
The connection ID that the client chooses for the Destination Connection ID hold special status.  It is used for source address validation for servers that send Retry or Version Negotiation, it determines the packet protection keys for Initial packets, and it is used to validate the Retry.

If we go with #2878 (which isn't yet decided, but seems plausible) then we have an opportunity to revisit this naming.  The name "original" was chosen to distinguish this connection ID from the one that was in other Initial packets, as the value wasn't the same for all Initial packets and the packet protection keys were also consistent.  Using "initial" might be feasible if the packet protection keys are all based on this one value.

**Comment by mikkelfj** [comment]
See also https://github.com/quicwg/base-drafts/issues/2926

**Comment by martinthomson** [comment]
Discussed in Cupertino and we'll close it.
