### ISSUE TITLE
Transport parameter registry is too constraining for innovation

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#3020]
As of [draft-22](https://tools.ietf.org/html/draft-ietf-quic-transport-22#section-22.1), transport parameter identifiers are 16bit integers, with a registry where
- `[0x0000 - 0xfeff]` uses the [RFC8128 Specification Required policy](https://tools.ietf.org/html/rfc8126#section-4.6)
- `[0xff00 - 0xffff]` is reserved for experimentation

While keeping Specification Required makes sense for a good chunk of the registry space, I think there will be many experiments that are conducted before a full specification is written (some already exist today and I expect there to be many many more once the protocol is standardized).

However, those experiments only have 256 values to play with, and that is bound to cause collisions and headaches down the road.

I think the simplest solution to this problem is to use variable length integers for transport parameter identifiers. The TLS presentation language doesn't support them but since we already use VLIs for the values of several transport parameters we're no longer bound by the TLS presentation language. I think there was also support for doing this when it was discussed on #1608, but that issue was closed when the *values* were changed to VLI with #1947, without changing the identifiers.

I'm happy to write the PR if this issue gathers support.

**Comment by martinthomson** [comment]
You aren't the first to suggest this one.  Let's make sure we at least discuss this directly.  We did discuss this in the context of the issues that you cite and decided not to, but that was never the central question.

From our perspective, this isn't a significant change to code.

**Comment by kazuho** [comment]
> From our perspective, this isn't a significant change to code.

The same for us, too.

Am I understanding correctly that the concern here is that extensions of TLS structures tend to use uint16_t as their type identifiers, and that the reusable parser might be constrained to that design pattern?

**Comment by martinthomson** [comment]
I thought that this might be the case originally, but it turns out that the blob for transport parameters is generated by QUIC code in mostly all of the cases I have seen.  If there is someone out there who is relying on passing a TLS stack a structured grammar and letting the TLS stack perform serialization, then we might want to just leave this alone.

**Comment by kazuho** [comment]
Thank you for the clarification.

We _do_ use the TLS stack to encode / decode the transport parameters, therefore we do want see the TLS grammar-based design being preserved. The reason we do not mind the extension type being a varint is because our codec is flexible enough to handle that.
https://github.com/h2o/quicly/blob/master/lib/quicly.c#L1353-L1437

**Comment by janaiyengar** [comment]
I agree with @ianswett, and I don't think we need to go varint here, that seems like a bit of an overkill. How about reserving 4096 codepoints for spec required, and leaving the rest (2^16 - 2^12 = 61440) for experimentation:
[0x0000 - 0x0fff] uses the RFC8128 Specification Required policy
[0x1000 - 0xffff] is reserved for experimentation

**Comment by DavidSchinazi** [comment]
Apart from the fact that we want to limit changes at this stage, are there arguments against going varint here? It feels pretty odd that many transport parameters are TLVs where T and L are 16bit and V is varint.

**Comment by janaiyengar** [comment]
I don't have much of an argument here besides the general principle that we shouldn't provide more flexibility than is necessary. I don't think it's odd that T is fixed-length while the V is varint, FWIW.

If no implementations are bothered by the change to varint, then it's a bit of a bikeshed. Let's see if other implementers are bothered.

**Comment by alagoutte** [comment]
> 
> 
> I agree with @ianswett, and I don't think we need to go varint here, that seems like a bit of an overkill. How about reserving 4096 codepoints for spec required, and leaving the rest (2^16 - 2^12 = 61440) for experimentation:
> [0x0000 - 0x0fff] uses the RFC8128 Specification Required policy
> [0x1000 - 0xffff] is reserved for experimentation

Split in two ? what the same size ?

Don't forget there is also GREASE TP now

**Comment by DavidSchinazi** [comment]
From looking at all the integer fields in QUICv1, it looks like at this point everything is a varint except the versions, packet numbers, connection ID lengths (which all have valid reasons for their lengths), and the transport parameter identifier and transport parameter lengths. Switching transport parameters to QUIC format (as opposed to TLS presentation language) feels fitting to me, saves bytes on the wire, and will facilitate innovation down the road.

**Comment by ianswett** [comment]
I'm happy to make transport parameter identifier a varint.

@DavidSchinazi Are you(implicitly) suggesting that transport parameter lengths should be varint as well?

**Comment by DavidSchinazi** [comment]
I think so, yes. If we're changing implementations might as well make both changes at once (assuming no one wants one of them to be varint but not the other).

**Comment by kazuho** [comment]
I'd be opposed to changing the transport parameter lengths to varints, as that means departure from the TLS notation that we use for defining TPs. It's very different from changing the IDs to varints, which is just changing the type of a particular variable.

IIRC, we discussed if we should switch to a different notation, and decided to go with the TLS-based design. At least I have built (or maintained) code based on that.

**Comment by ekr** [comment]
I agree with Kazuho here: splitting it in half would make plenty of room

**Comment by marten-seemann** [comment]
I'm in favor of the change that @DavidSchinazi is suggesting in #3087.
There's no reason for us to use TLS presentation language, if anything, it just makes the spec harder to read for people who are unfamiliar with the TLS presentation language (if I remember correctly, this came up multiple times on issues here and / or on Slack).

**Comment by huitema** [comment]
Remember the experience with the X-Options in SMTP or HTML? Do we really want to replicate that?

**Comment by larseggert** [comment]
Discussed in Cupertino. @DavidSchinazi to rework #3087 to only replace the TLS syntax with something easier to understand. This will be an Editorial change, reclassifying accordingly.

**Comment by DavidSchinazi** [comment]
As discussed in Cupertino, I have closed #3087 and replaced it with:
- editorial-only PR #3108 
- IANA policy PR #3109

**Comment by martinthomson** [comment]
I think that the RFC 6648 lessons need to be considered carefully here.  I think that it would be better to use a combination of random selection and provisional registration as a means of handling experiments.  Random selection means that we end up colliding with very low probability; provisional registration ensures that registrations are protected.  Making the private use space larger does neither.  I would prefer to instead remove the private use space completely.
