### ISSUE TITLE
Codes for frame encoding errors

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3027]
In the context of deciding what code to use for badly formatted frames:

> I'd use a FRAME_ENCODING_ERROR error here. However, for other invalid frame errors we use PROTOCOL_VIOLATION. Not sure if that's something we want to address at some point.

_Originally posted by @marten-seemann in https://github.com/quicwg/base-drafts/pull/2977_

I tend to agree with this.  Let's go through and try to apply some sort of consistency.  Maybe even try to be principled about it.

**Comment by ianswett** [comment]
I'd like to see a PR, but that seems like a good principle.

**Comment by marten-seemann** [comment]
@ianswett I prepared a PR, just waiting for #2977 to get merged to apply the principle there.

**Comment by mnot** [comment]
Can we call this editorial?

**Comment by martinthomson** [comment]
It changes functional requirements about what error codes to send, so not really.

**Comment by larseggert** [comment]
Discussed in Cupertino. Will be consensus-called.
