### ISSUE TITLE
Remove Requirement of an Acknowledgement per Round Trip

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#3030]
The spec gives no reason (that I can see) as to why an ACK frame must be sent at least once per round trip (assuming there are ack-eliciting packets to acknowledge), effectively overwriting the ACK delay logic when the RTT is very small. If the RTT is smaller than the platform's timer granularity, this isn't really even possible.

I propose to remove this requirement. If the WG instead feels that we should keep this requirement, then there should be a reasoning for it; and probably an update to the PTO calculation as well.

**Comment by ianswett** [comment]
As I commented on the PR that this came up in, given we have an explicit max_ack_delay that's now communicated, removing the 1 ACK per RTT requirement seems wide.

TCP has no such recommendation and I'm unaware of any indications or proposals that it should have such a property.

**Comment by janaiyengar** [comment]
@nibanks's point that the RTT can be smaller than the platform's granularity is a good one. I agree that this text ought to be removed.

**Comment by ianswett** [comment]
This is changing text in a SHOULD statement, so I believe it should be marked as design.
