### ISSUE TITLE
Detectable Stateless Resets

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#3032]
What are the implications of some stateless resets being detectable? The new language explicitly allows a situation where a host chooses not to pad out all its packets to include the length of its own connection ID. In this situation, a small packet could trigger a stateless reset from the peer that is too small to be anything other than a stateless reset.

I don't believe this will happen "all the time", as in general Server CIDL > Client CIDL and in general servers are the ones sending resets. Those are somewhat weak assumptions for reasons we can bracket for now, but I feel confident that the detectable reset will happen in the internet, at least occasionally. What is the threat model we feared when we put in the original rules to block reset detection, and do the concerns apply here?

**Comment by DavidSchinazi** [comment]
My understanding is that we want stateless resets to be hard to detect to avoid someone implementing a NAT that detects stateless resets and upon seeing them removes the NAT port mapping. As long as stateless resets are almost-always undetectable, we've removed the incentive for anyone to write that bad NAT code.

**Comment by janaiyengar** [comment]
What @DavidSchinazi said. The goal here was to avoid trivial signatures that get used by middleboxes so that connections are resilient to a third party that injects a StatelessReset-like packet.

**Comment by martinduke** [comment]
I guess the embedded assumption is that the following scenario does not become prevalent in the internet:
- Server infrastructures generally do not support migration, meaning a 4-tuple based architecture is satisfactory;
- As CIDs are irrelevant to switching, servers choose short CIDs, specifically to enable stateless reset; and
- Clients generally do not take care to pad their small packets

It's hard to predict the future, but if the internet evolves this way we'll have enabled some bad outcomes. I'm disinclined to change the spec at this time, but we should aware of the implications of this evolution if it occurs.

Unless I've gotten someone more concerned than I am, I believe it's OK to close this issue. I'll do so in a couple of days if no one pipes up.

**Comment by mikkelfj** [comment]
That is not a good assumption.

I have redundant servers that respawn should one go down either due to an error, or more likely, a software upgrade. While these are behind load balancers that hide their address, this is not always the case.

Therefore, server migration could be a very real thing. Now, it is not necessarily trivial to pass state to fail-over servers, but it does happen.

**Comment by martinduke** [comment]
I'm not talking about server migration, I"m talking about server support for client migration.

**Comment by DavidSchinazi** [comment]
@martinduke I think your nightmare scenario is very unlikely, as it requires the three bullets you mentioned, but also depends on the size of client connection IDs. I think we can assume that:

- most browsers will use zero-length client connection IDs
- most servers will use non-zero-length server connection IDs

At that point it's extremely unlikely that NAT/firewall manufacturers will build the "remove port mapping when you observe a 20-byte packet" feature for a minority of traffic, it's not like there's an overwhelming amount of innovation in this space...

**Comment by martinduke** [comment]
Why would a server use a connection ID if stuck with a 4-tuple based infrastructure? The only reason is to allow stateless resets, which only requires a byte.
