### ISSUE TITLE
Require peers to check if RETIRE_CONNECTION_ID sequence number is valid

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#3037]
An issue to match with PR #3036 

The text is:
"Receipt of a RETIRE_CONNECTION_ID frame containing a sequence number greater
than any previously sent to the peer MAY(->MUST) be treated as a connection error of
type PROTOCOL_VIOLATION."

**Comment by erickinnear** [comment]
Just pasting in the PR text:
> When it comes to error checks for protocol violations, our principle is that easy to implement error checks are REQUIRED. Only error checks that might require a lot of state to perform are optional.
>
>The check that the sequence number retired in a RETIRE_CONNECTION_ID frame is smaller than the highest issued connection ID is a single trivial uint64 comparison. Furthermore, every implementation needs to track the highest issued sequence number anyway, since connection IDs are issued in order.

**Comment by erickinnear** [comment]
I agree with the reasoning here and agree that it’s easy enough to check, but didn’t we consider this previously and decide against it for some reason (reordering or some other issue making this possible to have happen?)?

**Comment by martinthomson** [comment]
Reordering won't change what the maximum sequence number is.  That should be tracked.

**Comment by ianswett** [comment]
I agree with Martin(and Marten).  This is similar to the rule that a peer can't ACK a packet number you've never sent.

**Comment by janaiyengar** [comment]
@erickinnear : I have a vague recollection, but I think that might have been about tracking this at the receiver of NEW_CONNECTION_ID frames. This issue is about what the corresponding sender does when the receiver indicates a CID that the sender never sent.

**Comment by mikkelfj** [comment]
I think there might be issues with checking for _any_ invalid sequence number, but the maximum should be easy. But if that is the case, what is the point of specifically checking for max and not a host of other bad cases? Sanity check...

**Comment by kazuho** [comment]
I think the question is if we consider *processing* of NEW_CONNECTION_ID and RETIRE_CONNECTION_ID frames as a mandatory feature.

Migration is an optional feature of QUIC. For endpoints that do not migrate, there is no reason to update the Connection IDs (note that even though we recently introduced Retire Prior To field, we do not mandate endpoints to respect it - the keyword is "SHOULD"). If we consider that way, I think it is reasonable to never use a MUST for anything related to NEW_CONNECTION_ID or RETIRE_CONNECTION_ID frames.

**Comment by ianswett** [comment]
@kazuho I wouldn't encourage people to think of NEW_CONNECTION_ID and RETIRE_CONNECTION_ID as optional, but I agree that effectively they are in many cases.  However, if you sent NEW_CONNECTION_ID, I don't think it's optional to not correctly process RETIRE_CONNECTION_ID, and that's the question here(I copy-pasted the paragraph above).

If the peer never sends RETIRE_CONNECTION_ID because it doesn't fully implement connection ID functionality, then this is not a problem.

**Comment by nibanks** [comment]
I agree with Ian. Processing these frames, and acting accordingly is not optional. Even in the absence of migration RETIRE_CONNECTION_ID can be used to force a peer to start using new connection IDs. WinQuic will make use of this to dynamically balance load of connections across processors; independent of migration.

**Comment by kazuho** [comment]
@ianswett 
> However, if you sent NEW_CONNECTION_ID, I don't think it's optional to not correctly process RETIRE_CONNECTION_ID, and that's the question here(I copy-pasted the paragraph above).

Thank you for clarifying your position. I'd be perfectly fine if the intent of the proposed change is to  require validation _if the endpoint has sent a NEW_CONNECTION_ID frame_. My problem has been that I have been uncertain if the proposed change meant that; I'd be happy to proposed editorial tweaks to better clarify that.

@nibanks By saying "force a peer to start using new connection IDs", I think you are referring to the Retire Prior To field of the NEW_CONNECTION_ID frame. That's a SHOULD (as the text currently says), IIRC we have agreed on that.

**Comment by ianswett** [comment]
If you've never sent a NEW_CONNECTION_ID, how could receiving a RETIRE_CONNECTION_ID frame ever be valid?

**Comment by nibanks** [comment]
@kazuho sorry. You're right, I mean the NEW_CONNECTION_ID frame's Retire Prior To field. But I disagree on your interpretation of the `SHOULD`:
> Upon receipt, the peer SHOULD retire the corresponding connection IDs and send the corresponding RETIRE_CONNECTION_ID frames in a timely manner. Failing to do so can cause packets to be delayed, lost, or cause the original endpoint to send a stateless reset in response to a connection ID it can no longer route correctly.

The `SHOULD` is for `in a timely manner`. If you don't do it, the connection **will** eventually break, likely via a stateless reset.

**Comment by kazuho** [comment]
@ianswett The preferred_address TP. An endpoint is allowed, even though not required, to send a RETIRE_CONNECTION_ID frame to retire a CID used during handshake. Quoting from [section 19.16](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.19.16): _An endpoint sends a RETIRE_CONNECTION_ID frame (type=0x19) to indicate that it will no longer use a connection ID that was issued by its peer. This may include the connection ID provided during the handshake._

**Comment by kazuho** [comment]
@nibanks 
> The `SHOULD` is for `in a timely manner`. If you don't do it, the connection will eventually break, likely via a stateless reset.

The question is the intent of using "SHOULD in a timely manner" rather than "MUST in a timely manner". Yes, the connection would break, if the receiver does not migrate to a new connection ID. However, because we use a SHOULD, that is one of the expected outcomes when an endpoint sends a NEW_CONNECTION_ID frame carrying non-zero Retire Prior To field.

**Comment by nibanks** [comment]
@kazuho it sounds like you're arguing that it's an acceptable trade off for clients that don't want to implement support for the Retire Prior To field. I hope that isn't what you're saying. As it is, I'm thinking I'm going to have to add some greasing for this feature to WinQuic.

**Comment by kazuho** [comment]
@nibanks
> it sounds like you're arguing that it's an acceptable trade off for clients that don't want to implement support for the Retire Prior To field. I hope that isn't what you're saying.

I am saying that that is the natural way of reading the text. It seems to me that there is a disagreement on what the text implies, and I think it'd be more productive to try to polish up the intent of the text before resorting to encouraging particular behavior through greasing; hence #3046.

**Comment by erickinnear** [comment]
Thanks @janaiyengar, that sounds about right, this is the other direction, makes sense. 👍
