### ISSUE TITLE
kMaxDatagramSize should use the PMTU rather than be fixed

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#3041]
kMaxDatagramSize is currently set to the minimum packet size of 1200 bytes. It should be set instead to the max packet size used by the connection, which is discussed in Section 14.1 of the transport draft.

(Issue raised by Timo Völker on the mailing list.)

**Comment by ianswett** [comment]
My reading is that this value is the actual max packet size used in the connection, it's just not clear from the explanation.  kInitialWindow and kMinimumWindow are also per-connection fields defined directly below.

There is one potential detail, which is if the MTU increases after the handshake, do the min CWND and Reno behavior change accordingly?  I think it's simpler to reason about them not changing, but I can see both arguments and in the end I don't think it'll matter that much.

**Comment by nibanks** [comment]
WinQuic uses the currently calculated path MTU instead a constant kMaxDatagramSize.
