### ISSUE TITLE
Handling of Retire Prior To field

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3046]
At the moment, [section 5.1.2](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.5.1.2) states, quote: _Upon receipt, the peer SHOULD retire the corresponding connection IDs and send the corresponding RETIRE_CONNECTION_ID frames in a timely manner. Failing to do so can cause packets to be delayed, lost, or cause the original endpoint to send a stateless reset in response to a connection ID it can no longer route correctly._

As the text uses "SHOULD" rather than a "MUST", some view it as an optional requirement to switch to using a new connection ID in such a situation. Others think that it is a mandatory requirement for an endpoint to switch to a new connection ID.

If we are to consider the latter behavior to be the case, I think the text should better be changed to "**MUST** retire the corresponding connection IDs and send the corresponding RETIRE_CONNECTION_ID frames in a timely manner".

**Comment by kazuho** [comment]
My personal take is that it would be nice if the processing of NEW_CONNECTION_ID frame and RETIRE_CONNECTION_ID frame can be an optional feature. QUIC is already very complex, and it would be beneficial to have some features being optional, in sense that endpoints can simply discard certain frames when not implementing certain features.

IIUC, at the moment, these two frames are optional for an endpoint that do not support migration.

OTOH, from the robustness viewpoint of the protocol, it does make sense to change the text to MUST. We might have already crossed the river by introducing the Retire Prior To field.

The third option is to add a TP that indicates if an endpoint supports retirement of connection IDs...

**Comment by nibanks** [comment]
There was a lot of discussion when the Retire Prior To feature was added. At the time, I felt it pretty clear that it could not be optional from our server's perspective. I agree the sentence with the SHOULD, if read in isolation, could be interpreted as making the feature as optional. But the sentence immediately following it makes it pretty clear that it's not option.

> Failing to do so can cause packets to be delayed, lost, or cause the original endpoint to send a stateless reset in response to a connection ID it can no longer route correctly.

I understand the desire to make things optional for simplicity's sake, but a primary point of this feature, when it was added, was that is was required. Making it optional now would, IMO, defeat the purpose of the feature.

**Comment by ianswett** [comment]
My understanding is that this is optional in the sense GOAWAY is optional.  At some point, the connection is likely to terminate abruptly if you don't follow the request.

**Comment by nibanks** [comment]
That's one way to look at it. The difference here is that we're not trying to kill the connection with Retire Prior To.

**Comment by erickinnear** [comment]
There was definitely lots of discussion around the requirement level here when this was added (see #2645), @nibanks asked: 
> why couldn't we make it a "MUST immediately retire" instead of a SHOULD? What reasons would an endpoint have to ACK the packets but not retire the CIDs at the same time?

There was good discussion following that ([start here](https://github.com/quicwg/base-drafts/issues/2645#issuecomment-499180920) and scroll down). 

My understanding of [where we ended up](https://github.com/quicwg/base-drafts/issues/2645#issuecomment-501041204) was that the endpoint being asked to retire a CID really SHOULD retire it or else the peer may stop responding to that CID. 

After the endpoint requesting retirement gives up on a CID and forgets about it, packets will either arrive with that CID or they will not. It has two choices, it can choose to process them if they arrive with the wrong CID, or it can drop them. The enforcement mechanism here is to stop processing the "bad" CIDs, not close the connection, especially as you take into account potentially delayed-but-valid packets.

I think the current stance of "really SHOULD stop using such a CID, but the other endpoint needs to be careful about enforcing that" is the right one, if there's a wording update that would help with understanding there, then it would be great to update the wording as an editorial issue.

**Comment by martinthomson** [comment]
Whatever the answer here, the SHOULD was chosen because "timely manner" isn't defined in a testable fashion.  If someone wants to argue for MUST, then we need a firmer definition of the reaction.

**Comment by martinthomson** [comment]
And to agree with @erickinnear, the squishiness here only exists up until the point that this is "do this or else".  We should make it clearer that the cost of non-compliance is losing the connection.  Not always, but a endpoint is entitled to cut and run if their peer doesn't comply.

**Comment by kazuho** [comment]
@erickinnear Thank you for the explanation and the links. They help a lot in understanding how we ended up here.

> Whatever the answer here, the SHOULD was chosen because "timely manner" isn't defined in a testable fashion. If someone wants to argue for MUST, then we need a firmer definition of the reaction.

Yeah we already state that "_an endpoint MAY discard a connection ID for which retirement has been requested once an interval of no less than 3 PTO has elapsed since an acknowledgement is received for the NEW_CONNECTION_ID frame requesting that retirement._" So I think it's testable.

Considering that we have a MAY on the side that initiates the retirement, I think we can have a MUST on the receiver side (assuming that we want to).

**Comment by martinthomson** [comment]
That almost works, except that PTO isn't a shared variable.  It's subjective and so endpoints might disagree on where this line is.  At 3PTO, that's probably not a disagreement worth having, but you are effectively recommending instant compliance if you set the bar that low, as packet loss on any packet sent that attempts to comply might cause it to take up to 3PTO to get through.

**Comment by MikeBishop** [comment]
IIRC, the base of the SHOULD was that we didn't have a specific timeout anyone felt comfortable enforcing in the absence of shared timers between peers.  We've had a general principle that requirements you can't tell whether the peer violated are probably SHOULDs instead of MUSTs.  As Nick says, the SHOULD is intended to refer to doing so promptly, not to doing so at all.

**Comment by kazuho** [comment]
While I agree that we have tried to make MUST requirements testable, I am not certain if it is a goo idea to avoid use of MUST when a requirement cannot be tested (or if doing so is a good idea, per the definition of the keywords in RFC 2119).

At least for this particular case, isn't it a requirement for an endpoint to drop the old connection IDs?

Though I could well be wrong though in how the keywords are used in practice.

**Comment by nibanks** [comment]
I'm fine saying MUST drop in a timely manner, and being explicit about what we mean by timely manner (3 PTO from the peer's perspective). Obviously, from the peer's perspective, that is enforceable. Locally though, it's obviously not as clear cut.

**Comment by martinthomson** [comment]
We need a PR.  @kazuho, do you think that you can do this?  As discussed, should be that the receiving side will retire within one PTO.  The sending side can enforce at 3PTO, by dropping the connection.

**Comment by larseggert** [comment]
Discussed in Cupertino. @kazuho to quickly rev the PR to incorporate @martinthomson's suggestion.
