### ISSUE TITLE
Label for key updates

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3054]
We've been back and forth on this issue for a while now and I honestly don't know what the answer is.  #3050 picks a value that we haven't seen before, or we could - as I think some have assumed - use the TLS value of "traffic upd".

I think that because QUIC is managing this, it should be a quic-specific label.

See also #1845 and #1003.

**Comment by kazuho** [comment]
> I think that because QUIC is managing this, it should be a quic-specific label.

I would not strongly suggest this, but I wonder if it be possible to define the derivation function inside QUIC too. If the labels are going to be different, it would be helpful to the readers to have all the definition in one place.

**Comment by DavidSchinazi** [comment]
+1 to clarifying what the label is. I don't have a strong opinion on what the label should be as long as it's in the quic-tls draft.

**Comment by nibanks** [comment]
I also agree the label should be explicitly defined in the quic-tls spec. I do like Kazuho's suggestion as well, to completely define the derivation function. I don't care too much what the label is. We were using `traffic udp` (and interop'ing with it).

**Comment by martinthomson** [comment]
There's a difference between defining the function and providing a much clearer example of what the function is for TLS 1.3.  I've chosen the latter on the basis that the cryptographic handshake function provides us with a KDF and that we shouldn't be making our own if we can avoid it.  If TLS 1.4 wants to use a different KDF, then that will be used here instead.

**Comment by larseggert** [comment]
Discussed in Cupertino. #3050 has proposal.
