### ISSUE TITLE
Lost client Initial is never retransmitted

### ISSUE THREAD

**Issue by Ralith** [quicwg/base-drafts#3056]
As of https://github.com/quicwg/base-drafts/pull/2806, if the client's Initial is lost, there is no required behavior that leads to it being retransmitted. Because the client has received no ACKs, no `loss_time` is set, and no loss is detected, leading to the client only sending probe packets, which are not required to bear any particular data ("A probe packet **MAY** carry retransmitted unacknowledged data") so long as they are ACK-eliciting. The server, having no connection state, cannot do anything with these packets. 

Quinn probes are currently a single PING frame (plus padding, when appropriate) for simplicity, so implementing the new logic immediately broke our tests. If recovery logic now requires probe packets to bear specific data to function correctly in certain circumstances, this should be specified explicitly.

**Comment by tatsuhiro-t** [comment]
I also hit this issue too.  After several hours tries and error, I came to the conclusion that implementation should mark the in-flight Initial packet lost in this case, and resend it.  Draft-22 has explicit statement that implementation should not mark in-flight crypto packet lost, but draft-23 does not have it anymore.
BTW, draft-23 does not allow PING in Initial or Handshake packet.

**Comment by Ralith** [comment]
> implementation should mark the in-flight Initial packet lost

Why not retransmit the data without declaring the in-flight packet lost?

**Comment by tatsuhiro-t** [comment]
I think it is rather implementation detail to internally mark in-flight packet lost but keep it in order to catch late ACK.

**Comment by Ralith** [comment]
There's a related problem where if the server's first flight goes missing, the only response the new logic has is to send a probe at unspecified, i.e. highest known, encryption level. The server will generally have 1-RTT keys at this point, so it sends a 1-RTT probe, which the client, not having received anything prior, cannot decrypt and drops.

**Comment by ianswett** [comment]
The packets should not be marked as lost, but data needs to be retransmitted before sending a PING.

I sent out a PR #3057, feel free to make further suggestions there.

**Comment by ianswett** [comment]
I'm marking this design because it adds some normative language, though I'll note that it doesn't change what I originally intended the text to say.
