### ISSUE TITLE
Clearer description of detecting spurious retransmissions

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#3058]
There are multiple mentions of spurious retransmission in the recovery draft, but no text on what detecting this may require from an implementation.  Maybe there should be?

"Spuriously declaring packets as lost leads to unnecessary retransmissions and may result in degraded performance due to the actions of the congestion controller upon detecting loss. Implementations that detect spurious retransmissions and increase the reordering threshold in packets or time MAY choose to start with smaller initial reordering thresholds to minimize recovery latency."

From comments on #3057

**Comment by Ralith** [comment]
Some discussion of implementation strategies here would absolutely be helpful; it doesn't obviously fall out of Quinn's current architecture.

**Comment by ianswett** [comment]
@janaiyengar and @martinthomson indicated my effort at adding more text wasn't that useful, so I'm closing this.
