### ISSUE TITLE
Unclear what to do when QUIC Version Hints are missing

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#3061]
[draft-quic-http defines QUIC Version Hints](https://tools.ietf.org/html/draft-ietf-quic-http-23#section-3.2.1). This allows the server to indicate which versions of quic-transport it prefers. However, there is no guidance as to what to do in the absence of such hints.

If a client receives `Alt-Svc: h3=":443"` (without any hints), is it expected to start with QUIC version 1, or with the client's preferred QUIC version?

If a client receives `Alt-Svc: h3-23=":443"`, is it expected to start with `0xff000017` (draft-ietf-quic-transport-23)?

We may want to provide guidance in draft-quic-http to ensure everyone's on the same page.

**Comment by LPardue** [comment]
I happy to be proven wrong but it seems like noone uses this parameter and it raises all sorts of questions. I'm leaning towards killing it off.

**Comment by Lekensteyn** [comment]
The Version Hints presumably exist to avoid one roundtrip for the [Version Negotiation packet](https://tools.ietf.org/html/draft-ietf-quic-transport-23#section-17.2.1). Thus without hints, a client could probably decide to use any version it supports (1 or whatever latest version it desires to use).

FWIW Google uses alt-svc, but I do not remember seeing the version hint *parameters*. For example:
```
$ curl -sI https://google.com | grep alt-svc
alt-svc: quic=":443"; ma=2592000; v="46,43,39"
```

**Comment by LPardue** [comment]
in this case the "v" parameter is comparable to the "quic" parameter

**Comment by Lekensteyn** [comment]
Right, but that `v` is a parameter on its own whereas `quic` is a parameter value in the current -http draft.

Removing the `quic` parameter was previously suggested in #297, but that did not seem to proceed.

**Comment by RyanAtGoogle** [comment]
@LPardue I also lean towards killing it off. However, that would prevent us from doing something like:

h3=":443", quic="1,2"

At some future date when we have QUICv1 and QUICv2 and we want to support HTTP/3 over either of them. Does that seem problematic?

Of course, if the alpn continues to imply the transport version and HTTP+QUICv2 == HTTP/4 then we wouldn't ever need to advertise this.

**Comment by LPardue** [comment]
That's a compelling argument, I'm just concerned that we aren't seeing this used much today and so when the time comes that you'll need it, it won't work as we all hoped. Perhaps we could _defer_ the quic parameter until v2 - similar to other VN related issues.

**Comment by LPardue** [comment]
We also have a hard time testing this today - there is no standard legal valid combination of "h3-N" and quic versions that would allow a client to select one QUIC version over another. Perhaps this was a motivator for https://github.com/quicwg/base-drafts/issues/3062?

**Comment by MikeBishop** [comment]
It's fine to omit this parameter.  As @Lekensteyn notes, if the client supports multiple versions of QUIC, this helps avoid the need to do Version Negotiation.  However, it's only an optimization -- in the absence of this information, the client does any version of QUIC it believes to be compatible with the ALPN token(s) it is offering.  If the server needs to do VN, it will.  (Details TBD, unfortunately.)

Is this critical to HTTP/3?  No, and it could reasonably be extricated to a separate document until such time that there are multiple QUIC versions.  Most stacks currently support only one version at a time, so this doesn't serve much purpose.  If HTTP/3 doesn't require breaking changes to keep up with QUICvN, this probably serves a purpose on the day there are several.

Personal opinion:  If anyone thinks this is half-baked, let's set it aside until we need it, with the rest of VN.  If we're fairly confident this is what we want, however, it saves us the trouble of defining another separate RFC later.

**Comment by DavidSchinazi** [comment]
I'm worried that relying on clients to "do the right thing" might cause serious performance issues down the road. I'd prefer to either have explicit guidance, or remove this mechanism until we understand it better as @MikeBishop suggests.

**Comment by MikeBishop** [comment]
It was designed at a stage where QUIC had a fully-defined Version Negotiation mechanism.  The client could offer any version -- in fact, was *encouraged* to offer a grease version -- on the first flight, and would learn the server's list of versions in response.  But if you knew that list up front, either via Alt-Svc or because you've connected before, you could save a round-trip by selecting something that was on the list.  And if your information was wrong, or stale... oh well, you get a VN packet and learn the correct list.

Now, we don't have such a mechanism and receipt of a VN packet is fatal.  There are two ways to look at this:
- There is only one version, so we can define this mechanism once it can be paired with a version negotiation mechanism.
- Getting the server's version wrong is fatal, and therefore this mechanism is essential.
