### ISSUE TITLE
Disconnect version number from draft number

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#3062]
As the documents are becoming more mature, the amount of protocol-level changes is going down. Would it make sense to start disconnecting the protocol versions ([ALPN](https://tools.ietf.org/html/draft-ietf-quic-http-23#section-3.1) `h3-23`, [transport version](https://tools.ietf.org/html/draft-ietf-quic-transport-23#section-15) `0xff000017`) from the draft numbers (i.e. `draft-ietf-quic-http-23`, `draft-ietf-quic-transport-23`)?

This correlation caused a few headaches in the final stages of TLS 1.3 standardization, it would be nice not to repeat that here.

(This was discussed a while back, and is not my idea, but is now the right time?)

**Comment by LPardue** [comment]
I'm sympathetic to the point that is being made here but I don't know how solvable it is. 

HTTP/3 has been quite independent of QUIC version for a while, so its been funny watching if move in lock step with transport.

On the one hand, there are implications to changing the alt-svc identifier, which makes migration a little annoying. But on the other hand we just made a breaking changes between h3-22 and h3-23.

**Comment by DavidSchinazi** [comment]
The idea would be to update the protocol version in a new draft if any breaking change was made, but not when only editorial changes were made.

**Comment by LPardue** [comment]
That makes sense. For HTTP/3 we'd need to rephrase https://tools.ietf.org/html/draft-ietf-quic-http-23#section-3.1 slightly (but that is not a huge problem because the section will be deleted in the final version anyway). In the interest of sanity, I might suggest that the HTTP/3 identifier simply reflects the wireprotocol version, and is explicitly tied to it. For example, if we were to freeze on 0xff000017, then the ALPN becomes `h3-ff000017` (give or take some prettifying). This would sidestep the discussion takign place on #3061 but with the possible cost of duplication.

**Comment by kazuho** [comment]
@LPardue I'm not sure it sidesteps. Instead, I think it might turn out as a practical way of testing the "quic" attribute of Alt-Svc.

Wire versions of the transport and the application protocol would not change in the same versions. Consider the case where http-24 remains wire-compatible with -23 (hence ALPN=h3-23), while the transport-24 making breaking changes.

In such case, to avoid the use of VN, the server _is_ going to send `Alt-Svc: h3-23=":443"; quic="ff000018"`.

**Comment by LPardue** [comment]
My proposal was imperfect but I was attempting to avoid having to maintain some out of band matrix somewhere that lists what draft versions of H3 are compatible with what draft versions of QUIC, and also avoid gaps in the H3 apln identifier space.

**Comment by kazuho** [comment]
@LPardue Yeah I think I get that.

My point is that if we are say that the ALPN identifier changes only when the HTTP/3 draft makes a wire-incompatible change, a single HTTP/3 draft could match to multiple versions of QUIC transport drafts (that are incompatible with each other), and therefore that the "quic" parameter would be useful.

If we are going to update the ALPN identifier when either of the HTTP/3 draft or the transport draft changes, then there would be no benefit in sending the "quic" parameter.

**Comment by LPardue** [comment]
I have a concern about how the quic parameter would relate to Alt-Svc caching in practice, especially on a rolling upgrade.  But I'm not sure my concern is found or the proposal helps.

**Comment by huitema** [comment]
Booh!

**Comment by larseggert** [comment]
Discussed in Cupertino. Closed with no action!!!

**Comment by erickinnear** [comment]
(Specifically, closed with a commitment to being more clear about which draft numbers are intended for implementation. The idea being that editorial-only draft numbers won't be "implemented", avoiding the problem entirely.)
