### ISSUE TITLE
Help me fix this problem 

### ISSUE THREAD

**Issue by gitup10** [quicwg/base-drafts#3065]
Help please to fix
 sh: 1: cannot create /: Is a directory 
![Screenshot_20190924-211922_Termux](https://user-images.githubusercontent.com/55763670/65543410-66952800-df11-11e9-9a88-1b499efd54b6.jpg)

**Comment by gitup10** [comment]
Up

**Comment by MikeBishop** [comment]
No.

**Comment by gitup10** [comment]
No . ? Why

**Comment by MikeBishop** [comment]
From [CONTRIBUTING.md](https://github.com/quicwg/base-drafts/blob/master/CONTRIBUTING.md), emphasis added:
> Before filing a new issue, please consider a few things:
>
> - Issues should be just that; issues with our deliverables, not proposals, questions or support requests.
> - Please review the issues list to make sure that you aren't filing a duplicate.
> - If you're not sure how to phrase your issue, please ask on the mailing list.
>
> Issues can also be raised on the Working Group mailing list by clearly marking them as such (e.g., "New Issue" in the Subject: line).
>
> Be aware that issues might be rephrased, changed in scope, or combined with others, so that the group can focus its efforts. If you feel that such a change loses an important part of your original issue, please bring it up, either in comments or on the list.
>
> **Off-topic and duplicate issues will be closed without discussion.** Note that comments on individual commits will only be responded to with best effort, and may not be seen.

**Comment by mikkelfj** [comment]
I first thought this is spam, but whatever, since this thread won't die: the reason for the error is an extra space in the last line 

`> / sdcard/hola.apk` should probably be `>/sdcard/hola.apk`
