### ISSUE TITLE
0RTT or 0.5RTT data extends the PTO before handshake completion

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#3067]
In the recovery draft, when an ack-eliciting packet is sent in any packet number space, the PTO is extended.  

For example, if there is a long delay between a server sending Initial and Handshake, then that would delay retransmitting the Initial.

A larger problem may be the delay between Initial and 0.5RTT data on the server side or Initial and 0RTT data on the client side.

In both cases, prior to handshake completion, the application may write data at anytime, subject to congestion control limits and availability of ApplicationData keys.  In pathological cases(ie: an application sending tiny 'keep-alive' like pings) the Initial of the client or server may never be retransmitted until after the connection runs out of CWND, which is likely longer than the handshake timeout.

This problem was observed in gQUIC and we added an extra field to track the last sent packet containing crypto data and before the handshake was complete, armed the handshake timer from that.

The most straightforward fix to this I'm aware of is #3066, which makes PTO per PN space.

**Comment by huitema** [comment]
I did not realize that the PTO was not already expected to be per number space!

**Comment by larseggert** [comment]
Discussed in Cupertino. @ianswett to rework #3066.
