### ISSUE TITLE
Mysterious 1 vs 2 packet distinction in recovery pseudocode

### ISSUE THREAD

**Issue by Ralith** [quicwg/base-drafts#3070]
[The pseudocode](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#rfc.appendix.A.9) only potentially sends 2 packets if the endpoint is a server or if 1-RTT keys are had. It's unclear why this distinction is made, as opposed to sending "one or two" packets in every case. The text says:
>  Sending two packets on PTO expiration increases resilience to packet drops, thus reducing the probability of consecutive PTO events.

which seems to apply universally.

**Comment by martinthomson** [comment]
I think that we probably need to start saying "send a probe" rather than "send one or two packets".  And to define a probe as being one or two packets that can exceed the congestion limit.

**Comment by ianswett** [comment]
I updated the pseudocode in #3461 to always prefer the standard PTO response unless it's the client anti-deadlock case.  I believe this matches the text much better now.  It keeps the two cases when 1 packet is sent for anti-deadlock, but that matches the normative text.

**Comment by martinthomson** [comment]
That is a different solution to the one I imagined, but a better one.  You forgot some conditions in the pseudocode though.
