### ISSUE TITLE
Probe packet section needs to suggest a crypto context

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#3074]
Sec 5.3.1 of quic-recovery discusses how to send loss probes. Now that this can be done at any crypto level, there ought to be some suggestions (are any MUSTs needed?) on what crypto level to send probes at.

This is probably like the CONNECTION_CLOSE suggestion; if you have multiple levels, it may be good to coalesce some packets.

I'm working through the logic and may have some suggestions soon.

**Comment by ianswett** [comment]
There are some outstanding Issues relevant to this, including #3067 #3056 and #2604

**Comment by martinduke** [comment]
I agree, #3066 would obviate this issue.
