### ISSUE TITLE
SRTT vs. smoothed_rtt in quic-recovery

### ISSUE THREAD

**Issue by jrudolph** [quicwg/base-drafts#3076]
In section "Time Threshold", `SRTT` is used for the first time. I guess that would reference the same value before called `smoothed_rtt`? If that's the case they should be named the same. Further down in the same paragraph "smoothed SRTT" is used which is even more confusing. SRTT is used a few more times further down.

**Comment by mikkelfj** [comment]
There was a cleanup a while ago to ensure definitions such as SRTT happened before use, but that might have been lost in recovery to transport migration?
