### ISSUE TITLE
Stateless reset detection should be datagram-based

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3085]
This will make the process more robust, as the process of splitting a datagram into packets could cause the token to be split.  We recommend sending a packet (and one that can't be coalesced to boot).  This was always going to be a single packet datagram anyway, so this shouldn't affect implementations much.

**Comment by martinthomson** [comment]
Not sure if this is editorial or not. We already require *sending* to be a whole datagram: 

> A stateless reset uses an entire UDP datagram, [...]

So this could be seen to match things up.  But it could require code changes in implementations, so I'm leaning toward `design`.

**Comment by larseggert** [comment]
Discussed in Cupertino. #2993 to be merged following consensus call.
