### ISSUE TITLE
Backoff of CONNECTION_CLOSE needs to be a MUST

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3095]
At the moment, the backoff is merely a recommendation. Quoting from [section 10.3](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.10.3): _endpoints SHOULD limit the number of packets they generate containing a CONNECTION_CLOSE frame._

However, there is a DoS attack vector unless we make this a MUST, as an attacker can create bounce of packets carrying CONNECTION_CLOSE frames between two servers.

Consider the case where you have two servers (A, B) that use the original DCIDs supplied by the client as the server CIDs.

The attacker sends the following two Initial packets:
* srcaddr=A, destaddr=B, srcCID=X, destCID=Y
* srcaddr=B, destaddr=A, srcCID=Y, destCID=X

Both of the two packets would contain an invalid payload.

Then, both server A and server B would enter the CLOSING state sending CONNECTION_CLOSE frame to the peer. While in the CLOSING state, the specification allows endpoints to respond to packets from peer without decrypting them. Therefore, this creates a ping-pong.

To prevent this type of attack, I think we need to change "SHOULD limit" of the quoted text to "MUST limit". The alternative might be to forbid servers adopting the DCID given by the clients as their server CIDs.

**Comment by kazuho** [comment]
> Servers don't need to pad Initial packets and servers drop Initials less than 1200 bytes, so I believe the other 'Server' would drop the Initial CONNECTION_CLOSE and this would stop quickly.

Oh I missed that point. Thank you for pointing it out.

Though it is still possible to mount this attack by sending an invalid 0-RTT packet

Consider the case where an attacker obtains a session ticket from both servers beforehand, and sends datagrams to the servers, each consisting of Initial and 0-RTT packets (of which 0-RTT packet contains an invalid frame). Then, assuming that both servers accept 0-RTT, they would send to each other a series of Initial, Handshake, and 1-RTT packets, of which the 1-RTT packet would contain an CONNECTION_CLOSE frame.

So that would cause a ping-pong.

**Comment by kazuho** [comment]
PS. Though I now realize that the maximum about of bytes that each server would ping-pong is limited to 3x the size of the datagram that the attacker sends.

So it might be possible to call this a non-issue, though the number of UDP packets that the servers would send might be less concerning (it would be like 30 UDP packets, assuming that the packets containing CONNECTION_CLOSE would be around 100 bytes each).

**Comment by larseggert** [comment]
Discussed in Cupertino. @kazuho to write up a PR that replaces SHOULD by MUST in this case.

**Comment by martinthomson** [comment]
Note that this is only MUST in the case where the server drops state and uses a canned packet.

**Comment by janaiyengar** [comment]
I would suggest saying that impls MUST implement one of the two solutions: MUST NOT use the client's DCID as the SCID, or MUST do an exponential backoff if it does.

**Comment by janaiyengar** [comment]
An alternative would be to simply require backoff always. Whether or not a canned packet is used. Not backing off seems like a live wire, and it might be better to neutralize it in general.

**Comment by martinthomson** [comment]
I think that a "SHOULD" is enough generally; the problem only exists because you are blindly sending packets without understanding the packet that triggers them.

**Comment by kazuho** [comment]
In #3157, I've gone with
* SHOULD limit when you retain packet protection keys (as you can stop sending packets once you receive CONNECTION_CLOSE)
* MUST limit when you drop packet protection keys (as you do not know when to stop)

Re https://github.com/quicwg/base-drafts/issues/3095#issuecomment-542920940, while we can define a rule based on how endpoints use CIDs, I think I prefer having a rule based on how a stack is implemented (i.e. when you drop packet protection keys) rather than how a stack is configured (i.e. the way CIDs are used). IMO, the latter is harder to test and therefore fragile.
