### ISSUE TITLE
Is CONNECTION_CLOSE ACK-eliciting?

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3097]
At the moment, we state that _a QUIC packet that contains frames other than ACK and PADDING_ ([section 1.2](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.1.2)), but I wonder if that is true for CONNECTION_CLOSE frame.

A CONNECTION_CLOSE frame never elicits an acknowledgment. IIUC, it is not meant to be governed by the congestion controller.

Considering the aspects, I think we should add CONNECTION_CLOSE to the list of *non-*ACK-eliciting frames.

**Comment by ianswett** [comment]
That also ensures the congestion controller never inadvertently blocks sending a CONNECTION_CLOSE, which is consistent with the intent.

If we make this change, I believe APPLICATION_CLOSE needs to be on the list as well.

Now that we discuss ack-eliciting in transport, I think we'd need to change both transport and recovery and mark this design.

So I think this would be a slight improvement, but I an also imagine people claiming that CONNECITON_CLOSE is already special, so there's no need for a change.

**Comment by janaiyengar** [comment]
This seems sensible.

**Comment by larseggert** [comment]
Discussed in Cupertino. Obvious correction.
