### ISSUE TITLE
Use packets or packet numbers in algorithms/pseudocode

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#310]
The text for `DetectLostPackets` claims that `acked_packet` is a packet number, but the code shows it as having a `packet_number` field, as well as a `time_sent` field.  Maybe a TimeSent() lookup function would work, but at the level that this code operates, I think that it would be better to talk about packets in the abstract.  A real implementation might not carry around all the information a packet might accumulate, but that's for real implementations to worry about.

**Comment by martinthomson** [comment]
FWIW, I've fixed this in #304, but only for this specific function.  The same problem exists in other functions.

**Comment by ianswett** [comment]
Fixed by PR #394
