### ISSUE TITLE
ACK+PADDING in response to ACK should be illegal

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#3100]
quic-transport draft 13.2.1:

An endpoint MUST NOT send a packet containing
   only an ACK frame in response to a non-ACK-eliciting packet (one
   containing only ACK and/or PADDING frames),

@marten-seemann points out that this allows one to send an ACK+PADDING packet, which seems to violate the spirit of the rule. This loophole breaks #3093. I believe this may be Editorial if we all know what we meant.

**Comment by ianswett** [comment]
Yes, it was intended that ACK should not elicit an ACK+PADDING packet.

**Comment by marten-seemann** [comment]
I agree with this change, but I disagree that this is a satisfactory fix for #3093.

**Comment by marten-seemann** [comment]
This issue should have been closed by #3104.
