### ISSUE TITLE
Alt-Svc and extension equivalence across H2 and H3 

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#3101]
This is a spin off from a [thread I started on the HTTP WG mailing list](https://lists.w3.org/Archives/Public/ietf-http-wg/2019OctDec/0022.html).

To avoid duplication, the TL;DR is that there could be cases where a H2 connection that is using some type of extension advertises an H3 alternative that is incapable of supporting the connection (most likely due to a configuration mistake). The example I use is WebSockets, which is predicate on extending CONNECT, but it probably applies to all version-specific extensions.

I don't think there is a non-trivial way to prevent such cases. So I propose that we help the ecosystem spot such cases but introducing an error code (this is quite similar to the 421 status code defined in RFC 7838). This error code can be used when closing a stream or a connection - clients can factor this in to their Alt-Svc selection logic, while servers could analyse error codes to spot misconfigurations etc.

Since this problem is more-or-less introduced by HTTP/3, it feels right to define an error code in this document. A separate I-D can specify a similar code for HTTP/2.

**Comment by MikeBishop** [comment]
That's basically what HTTP_1_1_REQUIRED / HTTP_VERSION_FALLBACK were for.  We originally used HTTP status 505 with a header describing what versions could have handled the request.  However, during HTTP/2 development we concluded that a stream error was more appropriate than a status code, because you might discover the blocker during response generation.

**Comment by MikeBishop** [comment]
(See [draft-nottingham-http-over-version](https://tools.ietf.org/html/draft-nottingham-http-over-version-00) for the 505 extension that got abandoned in favor of the error code.)

**Comment by LPardue** [comment]
Discussed f2f at Cupertino interim. The feeling was that a new error code could be useful but that we don't need to define it in the HTTP/3 core doc. Since I was going to make a separate document for the HTTP/2 version of this code, I'll simply define the code there. Closing this issue.
