### ISSUE TITLE
Add provisional registration for all registries

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3102]
We have nice registration policies for everything, but that doesn't serve for experimentation very well, because those experiments can clobber each other.  See also RFC 6648.

The proposal here is to allow for permanent registrations (under the same rules we have now), but to allow FCFS provisional registrations so that we avoid collisions when people start experiments that could be widely deployed.

We should also encourage people to choose random values rather than sequential ones.

**Comment by MikeBishop** [comment]
Does #3170 resolve this?
