### ISSUE TITLE
Does a client need to remember SETTINGS it doesn't understand when doing 0-RTT resumption?

### ISSUE THREAD

**Issue by nharper** [quicwg/base-drafts#3110]
The HTTP draft currently specifies

>  If a server accepts 0-RTT, but then sends a SETTINGS frame which reduces a setting the client understands or omits a value that was previously specified to have a non-default value, this MUST be treated as a connection error of type HTTP_SETTINGS_ERROR.

Is it intentional that a client MUST remember SETTINGS values that it doesn't support (to check that the server didn't omit a setting)?

**Comment by RyanAtGoogle** [comment]
The comment about checking for omitted settings says ... "omits a value that was previously specified to have a non-default value". In order for a client to know what the default value is for that setting, surely the client must support that setting, right?

**Comment by nharper** [comment]
You're right that for the client to know whether or not it's the default value it needs to support the setting (or at least know about it).

Suppose the server sends SETTING BLORP (which the client knows nothing about) with value X in the original SETTINGS, but omits it on the 0-RTT resumed connection. As currently specified, if value X is not the default value, the client MUST close the connection, but if it is the default value, then that's fine. (Meaning the client needs to know all possible default values for all possible settings.)

I think this needs an editorial fix to apply something like "a setting the client understands" to the bit about omitting a value as well.

**Comment by RyanAtGoogle** [comment]
Oh, I see your reading now. Interesting! Good point about an editorial tweak.

**Comment by LPardue** [comment]
I think this could affect reserved settings (aka grease) too, just in a slightly different way. Some editorial tweak to address the problem would be good.
