### ISSUE TITLE
Consider HTTP_ prefix on h3 error codes

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3116]
Either s/HTTP_/H3_/g or s/HTTP_//g.  Because these aren't really HTTP errors, they are HTTP/3 errors.

**Comment by royfielding** [comment]
Er, reconsider the existing HTTP_ prefix on h3 error code names so that they are not confused with HTTP status codes.

**Comment by LPardue** [comment]
`s/HTTP_//g` will cause a name clash between for the Transport error code `NO_ERROR (0x0)` and the HTTP/3 error code `HTTP_NO_ERROR (0x100)`. The name clash is not a massive problem but I think it using a `H3` prefix is more preferable.
