### ISSUE TITLE
Recouple QUIC version and ALPN

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3117]
We've removed the text saying that application protocols can constrain which QUIC versions they can run over.  We need to discuss where the correlation between ALPN tokens and version numbers gets considered.  Some proposals discussed in Cupertino:

- **ALPN tokens imply one specific QUIC version.**  This leads to a possible error case, where an ALPN token is offered/accepted over another QUIC version.
- **Application protocols can restrict which QUIC versions they run over.**  This implies that the QUIC version being spoken must be considered when selecting an ALPN token.

**Comment by martinthomson** [comment]
Discussed with @MikeBishop, this is fine in the TLS draft, but the HTTP/3 draft needs to have a firmer opinion.  Right now it says "anything with TLS 1.3".

**Comment by martinthomson** [comment]
The discussion in Singapore seemed to end with the conclusion that HTTP/3 would be defined to refer to QUIC version 1 exclusively.  But we decided not to answer the broader question of what ALPN actually refers to.  That was considered too broad a topic for the QUIC WG to address without involving TLS, HTTP, and others.

**Comment by mirjak** [comment]
Probably it would be good to have a more general section on service discovery and point to the HTTP/3 doc as one example.
