### ISSUE TITLE
Recommend algorithm for packet scheduler, rather than implementation

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#3122]
The current text in recovery says:

> As an example of a well-known and publicly available implementation of a flow pacer, implementers are referred to the Fair Queue packet scheduler (fq qdisc) in Linux (3.11 onwards).

Could we change this recommendation to something like "a Fair Queue packet scheduler using an algorithm such as "Weighted Round Robin" or "Deficit Round Robin"? The specific Linux reference is not very helpful in online searches.

**Comment by ianswett** [comment]
The interesting part about the the Linux qdisc is its support for rate-based packet pacing, not it's fair queueing algorithm.  Would it help to make that more clear or provide a reference such as: http://man7.org/linux/man-pages/man8/tc-fq.8.html

**Comment by mikkelfj** [comment]
Not really, this is the first (and almost only) thing you find and it tells you very little about queueing algorithms.

**Comment by pravb** [comment]
I agree. I found this reference pretty odd and it could become dated in time. I don't think we need to refer implementers to any particular implementation.

**Comment by ianswett** [comment]
I think @martinthomson was going to write a more crisp definition of a pacer and remove this reference?

**Comment by martinthomson** [comment]
I was [advocating for a crisper definition](https://github.com/quicwg/base-drafts/issues/3094#issuecomment-574962313).

If the formula I described is acceptable, then I'm happy to contribute text, but I hadn't planned to.

**Comment by mikkelfj** [comment]
@martinthomson I think it is good to have a clear definition of what pacing means when QUIC has that as a requirement for one operational mode. I'm not sure it is really helpful by itself in guiding the user towards queueing disciplines such as deficit round robin. I'd prefer at least a mention of such an algorithm as one way to achieve the desired behaviour rather then referring to qdisc. Such a name can searched and Wikipedia will answer.

**Comment by goelvidhi** [comment]
We had tried to provide a clearer definition of pacing here:
https://github.com/quicwg/base-drafts/pull/3351

This includes specification for how long should an implementation wait between two consecutive bursts:
`To effectively avoid creating these large packet bursts, a sender SHOULD also
 enforce a minimum time between sending the above mentioned bursts. To
 achieve high throughput while at the same time minimizing the bursts it is
 considered safe to wait for (RTT * maximum_burst_size / (cwnd * 2)) seconds
 between each burst (multiplying the congestion window by two allows the
 the rate to increase during slow-start).`

If the text in #3351 looks close to what we want, I can recreate the PR and we can go from there.
