### ISSUE TITLE
NEW_TOKEN and Retry tokens must be distinguishable

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3127]
We currently say that these tokens SHOULD be distinguishable by a server on the basis that an error in a NEW_TOKEN token is recoverable, but an error in a Retry token is fatal.  I don't see why this can't be MUST.  If we make it "MUST", then we can rely on this property in the design.

**Comment by ianswett** [comment]
Agreed, that'd be a useful property to rely on.

**Comment by marten-seemann** [comment]
Does that property need to hold if there are bit flips in the token?
If you’re encrypting the token, this would be easy to ensure: put the distinguishing bit under crypto cover. If you’re using a map lookup, you’ll probably have to work a little bit harder.

**Comment by marten-seemann** [comment]
Please ignore my last post, I mixed up Retry packets and Initials. Tokens in the client’s Initial are part of the AAD, so we don’t have to worry about bit flips.
