### ISSUE TITLE
allow sending PADDING after receiving a non-ack-eliciting packet

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#3135]
#3104 changed the rules regarding what kind of packet an endpoint is allowed to send after receiving a non-ack-eliciting packet. The intention of that text used to be to prevent peers from getting stuck in an ACK-loop, but now the text says:

> An endpoint MUST NOT send a non-ack-eliciting packet in response to a non-ack-eliciting packet, even if there are packet gaps which precede the received packet.

Among others, this means that once an endpoint receives a non-ack-eliciting packet, it's not allowed to send a packet containing only PADDING. This would be valuable for defeating traffic analysis. While it would be possible to hack your way out of this by sending a PING + PADDING packet, I'm not sure if this was the intention of #3104.

**Comment by ianswett** [comment]
To me, the key phrase here is 'in response to'.  If you want to send PADDING for some other reason and the congestion controller allows it, then you can send it.

**Comment by mnot** [comment]
This feels editorial...

**Comment by martinthomson** [comment]
I don't intend to do anything about this one.  As Ian notes, you can use other reasons to justify sending of anything, just don't justify the sending on the basis of having received a non-ack-eliciting packet or you will get into the sort trouble that doesn't end.

**Comment by janaiyengar** [comment]
I think the text is clear that sending PADDING is allowed at any time. I'm closing this with no action.
