### ISSUE TITLE
Rephrase "under crypto cover"

### ISSUE THREAD

**Issue by seanturner** [quicwg/base-drafts#314]
For some of the non-security folks, I could see that the phase "under crypto cover" might not make sense (from s3.5:

    Some early handshake packets, such as the Version Negotiation packet, are not encrypted, but information sent in these unencrypted handshake packets is later verified under crypto cover.

Maybe:

  Some early handshake packets, such as the Version Negotiation packet, are not encrypted, but information sent in these unencrypted handshake packets are later verified as part of the cryptographic processing.

**Comment by martinthomson** [comment]
We lost the text somewhere in the process, which makes me happy because I can close an issue.
