### ISSUE TITLE
It is unspecified how a server sends Handshake packets during / after migration

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3142]
At the moment, each endpoint confirms the handshake by it's own.

That means that, a client might confirm the handshake and initiate a migration and that migration might complete while the server is transmitting Handshake packets, in case the 1-RTT acks sent by the client is repeatedly lost. This is a possibility, as we do not require 1-RTT acks to be bundled with packets carrying PATH_CHALLENGE or PATH_RESPONSE frames.

However, we do not specify if the path used for sending Handshake packets migrate or continue to use the old path. In case it is the former, we also need to specify how the server fills in the SCID field of the Handshake packets it sends.

Credit: @janaiyengar

**Comment by ianswett** [comment]
I think there is a key principle we've previously agreed upon.

The 5-tuple doesn't change during the handshake.  That means we should not send Handshake packets down the new path.

**Comment by kazuho** [comment]
@ianswett 
> The 5-tuple doesn't change during the handshake. That means we should not send Handshake packets down the new path.

I agree.

Assuming that is the case, we need to define a mechanism that allows the server to drop Handshake keys and the path before migration completes, or even better before the sends the first packet in response to a migration attempt. Otherwise, the server would be required to have a special-case for handle the original path.

Proposed solution is #3141.

**Comment by erickinnear** [comment]
I think this comes back to a lot of what @huitema was bringing up during the interim -- there are other things that rely on having a explicit signal for the handshake being entirely complete, and this is one of them. 

Having a well-defined moment where we're entirely done and can move on from Handshake packets would make this a lot nicer.

**Comment by martinthomson** [comment]
@kazuho, this appears to be addressed by #3145, like the others in this cluster.  Is that right?

**Comment by kazuho** [comment]
@martinthomson Yes. That's correct.
