### ISSUE TITLE
loss detection timer description could be simplified by definining a timer mode

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#3151]
In `SetLossDetectionTimer` we're setting the loss detection timer in order to:

- trigger an early retransmit (if we received gaps in the acknowledged packets) **or**
- trigger a PTO (if we only have a tail outstanding)

When the timer fires, in `OnLossDetectionTimeout`, we first need to figure out why we set the timer, and trigger an early retransmit or a PTO based on that.

I think the code would be easier if we save a "timer mode" `enum { EARLY_RETRANSMIT, PTO }` in `SetLossDetectionTimer`, and take action based on that mode in `OnLossDetectionTimeout`.

@ianswett, @janaiyengar What do you think?

**Comment by ianswett** [comment]
That could work, but I'd call it { LOSS_DETECTION, PTO }

Any interest in writing up a PR so we can see what the change you have in mind looks like?

**Comment by ianswett** [comment]
I wrote up #3182, but I don't think it's an improvement.  Maybe it wasn't what you had in mind, @marten-seemann ?

**Comment by marten-seemann** [comment]
@ianswett I have a half-baked PR on my disk, but I still need to figure out the details of how this interacts the amplification limit. It seems like on the client side, there's a third timer mode (send *anything* to unblock the server from the 3x limit).
I'll put some more work into my PR and post it by early next week.

**Comment by ianswett** [comment]
One other idea would be to add a second timer, so you'd have a loss_timer and pto_timer.  I was strongly against this when we had handshake retransmissions and TLP retransmissions and RTO retransmissions, but now that we're down to PTO, I like the idea better.  I think that might be simpler to understand than an enum, and you could split the pseudocode into two methods.

**Comment by janaiyengar** [comment]
If we are going to make a change, I would very much argue for using a
single timer. There's never a time when we might want both timers, which is
signaled clearly to implementers by using a single timer. We can refactor
the handling of timeouts though.

**Comment by ianswett** [comment]
@mnot All changes discussed are in the pseudocode, so I believe this will be editorial.

**Comment by larseggert** [comment]
Changed per discussion in ZRH

**Comment by ianswett** [comment]
I don't think we should do this anymore, and I have no intent to fix it.
