### ISSUE TITLE
ASCII reference in 6.2.1.1

### ISSUE THREAD

**Issue by seanturner** [quicwg/base-drafts#317]
We got two options for an ASCII reference:

1. RFC20
2. American National Standards Institute (formerly United States of America Standards Institute), "USA Code for Information Interchange", ANSI X3.4-1968, 1968.

When RFC5137 use the ANSI reference they also included the following note: ANSI X3.4-1968 has been replaced by newer versions with slight modifications, but the 1968 version remains definitive for the Internet.

I lean towards RFC20.

**Comment by janaiyengar** [comment]
What? No unicode parameters??
