### ISSUE TITLE
TLS MUST NOT deliver server 1RTT Rx keys until getting Finished

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#3173]
In #3159 it's becoming clear that some QUIC server implementations are using their 1RTT receive keys before getting CFIN, which is not supposed to happen.

IMO, there are going to be plenty of hacky QUIC implementations but only a handful of TLS implementations, especially TLS implementations that have the special APIs required for QUIC. This is the narrow waist where we should enforce good behavior.

Figure 5 of quic-tls shows that we shouldn't deliver the keys that early, but there's no normative language. I will file a PR shortly for quic-tls that imposes this requirement, so that QUIC implementations can't possibly mess this up.

**Comment by martinthomson** [comment]
I like that this class of problem is naturally assumed to require some sort of protocol change.  As I said on #3159, maybe those implementations can fix their bug.

#3174 is a pragmatic sort of fix that would make this an editorial issue.  I'd like that, but it sounds like there is a strong desire to go all nuclear on this.  We should discuss that, or its spectre will haunt us.

**Comment by kazuho** [comment]
I think it's worth noting this, though I tend to agree with @martinthomson that we cannot write this down using an normative language because that is a requirement of TLS.

That said, I actually wonder if we can have a section discussing Implementation Pitfalls. TLS 1.3 has an appendix dedicated to that (see [RFC 8446, Appendix C](https://tools.ietf.org/html/rfc8446#appendix-C])), and it has been extremely helpful to me. I think it would be nice to have something like that in the QUIC drafts.

**Comment by martinduke** [comment]
I'm not sure of the rules here, but this requirement is on the
QUIC-specific interfaces. People already have to modify TLS to comply with
quic-tls.

**Comment by kazuho** [comment]
> I'm not sure of the rules here, but this requirement is on the QUIC-specific interfaces.

IIUC, This requirement comes from the TLS handshake protocol defined in section 4 of RFC 8446 (specifically, [section 4.4.4](https://tools.ietf.org/html/rfc8446#section-4.4.4)). TLS 1.3, DTLS 1.3, and QUIC all share the same handshake protocol.

**Comment by ghedo** [comment]
Wouldn't this prevent the server from sending 0.5 RTT responses to 0-RTT?

**Comment by ghedo** [comment]
Or, well, sending 0.5 RTT at all, not just for 0-RTT.

**Comment by kazuho** [comment]
@ghedo Regardless of if we should use the normative language in QUIC-TLS, I think that RFC 8446, Section 4.4.4 clarifies what the requirements are, i.e.:
* do not use the 1-RTT keys until the Finished is received
* with the exception of 0-RTT
* and also with the exception of 0.5-RTT, while keeping in mind that the peer's identity or liveness has not been asserted.

**Comment by martinduke** [comment]
@ghedo No, just the receive keys.

**Comment by kazuho** [comment]
@martinduke As said, it is not only QUIC. DTLS 1.3 also uses the TLS 1.3 handshake protocol while having a different packetization layer ("records" in TLS term).

That said, I am fine with letting the editors of the QUIC-TLS draft decide.

**Comment by mnot** [comment]
Calling this editorial, since it looks like it can be addressed without adding requirements.

**Comment by martinthomson** [comment]
Closing now that we have merged #3224.
