### ISSUE TITLE
Maximum packet size should be per 4-tuple

### ISSUE THREAD

**Issue by hoang-tranviet** [quicwg/base-drafts#3176]
In Sec. 14.1, current transport draft said that:

> Each pair of local and remote addresses could have a different PMTU. QUIC implementations that implement any kind of PMTU discovery therefore SHOULD maintain a maximum packet size for each combination of local and remote IP addresses.

However, if only UDP port changes, ECMP could cause traffic to be routed through different physical paths, which potentially have different PMTUs. I wonder if Maximum packet size should be per 4-tuple instead.

**Comment by martinthomson** [comment]
The term "address" is used here to include UDP ports.  The definition is buried in 8.2 though: "where an address is the two-tuple of IP address and port."  I'll take this as a prompt to move this up.

**Comment by hoang-tranviet** [comment]
Thanks for clarification. 
This was confusing for me since it currently uses the specific term "IP addresses" instead of "addresses".

**Comment by martinthomson** [comment]
5653e332c7394814bedd12b84586da20f3a6c186 fixed this, but I missed the # in the comment, so this didn't get closed.
