### ISSUE TITLE
reordered NEW_CONNECTION_ID frames with retired sequence numbers shouldn't be used

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#3194]
Let's say an endpoint receives a NEW_CONNECTION_ID frame with Sequence Number: X, Retire Prior To: M. At a later moment, it receives a (reordered) NEW_CONNECTION_ID frame with Sequence Number: N (where N < M).

As the spec is currently written, it would be perfectly legal to use CID N at this moment. Obviously, this doesn't make sense, since the receiving peer is about to or has already stopped accepting packets with using CIDs < M. When receiving such a reordered NEW_CONNECTION_ID frame, the reasonable thing to do is to immediately send the corresponding RETIRE_CONNECTION_ID frame for N.

**Comment by erickinnear** [comment]
Agreed, I think that was the intent all along, we just missed the text. Thanks for the close read! 😄

**Comment by martinthomson** [comment]
Technically design, so we'll need a consensus call, but the PR is probably the best way to address this.
