### ISSUE TITLE
conflicting advice how to handle Retire Prior To

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#3195]
In the section talking about Connection IDs (section 5.1.2) it says:
> An endpoint can cause its peer to retire connection IDs by sending a NEW_CONNECTION_ID frame with an increased Retire Prior To field. Upon receipt, the peer MUST retire the corresponding connection IDs and send corresponding RETIRE_CONNECTION_ID frames.

In the description of the NEW_CONNECTION_ID frame (section 19.15) it says:
> The Retire Prior To field is a request for the peer to retire all connection IDs with a sequence number less than the specified value. [...] The peer SHOULD retire the corresponding connection IDs and send the corresponding RETIRE_CONNECTION_ID frames in a timely manner.

So it's not clear if you just SHOULD or if you MUST send the RETIRE_CONNECTION_ID frame.

As an editorial remark, I find the existing text a bit hard to understand, since it's spread over these two sections. Maybe it would be easier to keep the frame description relatively short, and move more of the logic into the section that describes how CIDs are used and retired.

**Comment by MikeBishop** [comment]
I think what we concluded in previous discussion was that you MUST retire them, and SHOULD do so in a timely manner.  The suggested reorganization isn't a bad suggestion either.

**Comment by martinthomson** [comment]
Based on this feedback, this can probably be handled as an editorial matter.  I would be happy to receive a PR that reconciled this with [the agreed conclusion](https://github.com/quicwg/base-drafts/issues/3195#issuecomment-550460829).

**Comment by erickinnear** [comment]
Definitely agree that this is editorial, we just missed this duplicate requirement in the original change. Removed that duplication and cleaned up the frame description a bit.
