### ISSUE TITLE
ChaCha20 header protection sample

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3199]
The sample taken for header protection is interpreted differently in DTLS 1.3.  QUIC uses `counter||nonce`, DTLS 1.3 uses `nonce||counter`.

That difference is likely to cause problems unless we erase it.  It's possible that the DTLS ordering is the right one here, but we should make a conscious decision.

See tlswg/dtls13-spec#109.

**Comment by kazuho** [comment]
I do not have a strong opinion here, though I might point out that [RFC 7539 section 2.3](https://tools.ietf.org/html/rfc7539#section-2.3) states:
```
   o  Word 12 is a block counter.  Since each block is 64-byte, a 32-bit
      word is enough for 256 gigabytes of data.

   o  Words 13-15 are a nonce, which should not be repeated for the same
      key.  The 13th word is the first 32 bits of the input nonce taken
      as a little-endian integer, while the 15th word is the last 32
      bits.
```

Retaining this order (i.e. `counter||nonce`) might be helpful to certain implementations.

**Comment by martinthomson** [comment]
This is what motivated the order that is in QUIC, yes.  But the construction of AES-GCM puts the counter second.  And here I thought that we were free of endianness issues.

**Comment by kazuho** [comment]
Though we do not use AES-GCM for header protection. That said, I can see your argument that we tend to favor having the nonce first.

So to me it seems the question is if we should have a generic design for using stream ciphers for header protection, or if we should let each stream cipher have its own.

**Comment by martinthomson** [comment]
Oh, I'm not arguing for the DTLS approach, only pointing out that it is rational when taken from a certain perspective.  I'd be happy if QUIC didn't need to change.  @davidben tends to favour the QUIC ordering also, FWIW.

**Comment by martinthomson** [comment]
OK, it looks like ekr moved DTLS to match.  Closing this with no action.

**Comment by mikkelfj** [comment]
How does that work? Is that a future version of DTLS?

**Comment by martinthomson** [comment]
@mikkelfj, this is [DTLS 1.3](https://github.com/tlswg/dtls13-spec).

**Comment by mikkelfj** [comment]
@martinthomson thanks
