### ISSUE TITLE
max_datagram_size being a variable means other constants become variables

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#3205]
Now that `max_datagram_size` is a variable, other constants that are defined in terms of it need to become variables (or probably function), too. This includes at least `kInitialWindow` and `kMinimumWindow`.

**Comment by ianswett** [comment]
Good point, thanks for filing this.

**Comment by gorryfair** [comment]
I have thoughts... I suggest the currently definition wrt max_datagram_size raises new safety issues. I am not sure a minimum of 10 * max_datagram_size, where max datagram, is say 9KB or 16KB, is actually something that is safe. From what I recall, the MSS term in IW for TCP related to sub 1500B MSS, and the need to constrain, not safe to expand. I suggest we define this in terms of the base size of 1280B. 

There is also an evil pathology in IPv4, where this can result in a router on path fragmenting larger packets to result in intense bursts of packets.

**Comment by gorryfair** [comment]
#3243 - is related.

**Comment by ianswett** [comment]
@gorryfair the current formula specifies a max of 14720 bytes, so increasing the MTU does not increase the IW beyond 14720.  This was based on the referenced RFC6928.

**Comment by gorryfair** [comment]
Bah - the "and" in the ID text confused me, this actually is Min(10 * max_datagram_size, max(2 * max_datagram_size, 14720)). So - I was wrong on my comment, sorry.
