### ISSUE TITLE
3.1.3 loss epoch

### ISSUE THREAD

**Issue by rpaulo** [quicwg/base-drafts#3210]
> QUIC ends a loss epoch when a packet sent after loss is declared is acknowledged. 

I believe there's an extra "is".

**Comment by ianswett** [comment]
Can you write a PR?  Removing either 'is' doesn't read well to me, but I suspect a sentence rewrite could be an improvement.

ie: "A loss epoch ends when a packet sent after loss is first declared is acknowledged."?

**Comment by rpaulo** [comment]
I agree a rewrite would be better.
