### ISSUE TITLE
Remove SHOULD for advice to pre-generate KeyUpdate

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3211]
> The process of creating new packet protection keys for receiving packets could
> reveal that a key update has occurred.  An endpoint MAY perform this process as
> part of packet processing, but this creates a timing signal that can be used by
> an attacker to learn when key updates happen and thus the value of the Key Phase
> bit in certain packets.  Endpoints SHOULD instead defer the creation of the next
> set of receive packet protection keys until some time after a key update
> completes, up to three times the PTO; see {{old-keys-recv}}.

I don't believe we had consensus on this -- and there was considerable debate in YUL. It just got pulled in as part of a big PR. 

This is a significantly more complicated mechanism than just generating as needed, and I haven't yet seen any real security analysis.

**Comment by martinthomson** [comment]
This text was specifically put in to address #2792.  That issue was extensively debated, but I agree that it was not concluded.

**Comment by mnot** [comment]
Reopening #2792. We need to be more careful about PRs that close multiple issues...
