### ISSUE TITLE
Terminology QUIC-Transport-24

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#3233]
- The word "host" is undefined. If it is equal to "endpoint", it should be replaced. Otherwise, "host" should" be defined in Sec 1.2.
- The word "address" sometime means "IP address" and "a pair of IP address and port" in other cases. Sec 1.2 should define "address" as "a pair of IP address and port". And "IP" should be added in front of "address" which means "IP address".

**Comment by martinthomson** [comment]
#3249 fixed this.

**Comment by kazu-yamamoto** [comment]
Thank you!
