### ISSUE TITLE
Add caution when using IW10 and fragmentation 

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#3243]
Gorry notes correctly that fragmentation can play poorly with using IW10. If a sender uses a large max_datagram_size, and if the network fragments, then IW10 can result in substantially larger amplification than 10x.

A simple fix here is to say that if the endpoint uses max_datagram_size larger than 1280 bytes (this is what the transport spec limits it to in the absence of DPLPMTUD), then the endpoint MUST set DF on outgoing packets.

This is a problem with RFC 6928 as well, but we should be clear about it for QUIC.

**Comment by pravb** [comment]
Shouldn't endpoint always set DF for all QUIC packets? TCP does so.

**Comment by ianswett** [comment]
I tend to agree with Praveen here.  I think this is something that's under-specified in transport?

I believe it should be in section 14: https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-14

**Comment by martinthomson** [comment]
Yeah, this is probably an issue in transport.  DF seems like the obvious answer.

**Comment by janaiyengar** [comment]
That was my first answer, but I thought that might be too intrusive. If we all agree that is a fine response, I'm happy with that. I can write up a PR.

**Comment by mikkelfj** [comment]
From memory, I think there was once a discussion on DF bit not being accessible in some language interfaces. As such, the formulation should perhaps be that the DF bit SHOULD be set whenever possible. Having a MUST whenever possible could be problematic because possible could involve a lot of complexity.

**Comment by martinthomson** [comment]
> UDP datagrams MUST NOT be fragmented at the IP layer. In IPv4 [IPv4], the DF bit MUST be set to prevent fragmentation on the path.

-- https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-14-4

**Comment by mikkelfj** [comment]
@martinthomson yes, that is exactly the text I am referring to. I'm questioning if that requirement is practically enforceable.
