### ISSUE TITLE
Can we make a normative ref to  RFC8085?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#3244]
I would like to suggest that RFC8085 is normative. 

This RFC was written as BCP for UDP usage, and QUIC implementations need to comply with that or describe the difference and reach consensus about why it differs.

**Comment by martinthomson** [comment]
I see RFC 8085 in the list of normative references already.  Was there something in particular that you think we should be explicitly depending on?

**Comment by martinthomson** [comment]
...Or, I realize now, does this comment apply to the recovery document?

**Comment by ianswett** [comment]
This was intended for the recovery doc.

**Comment by martinthomson** [comment]
Ahh, the comment still applies then.  What specific items in RFC 8085 would this need to depend on?  We don't just add normative dependencies without that.

**Comment by gorryfair** [comment]
Yes, this comment targets recovery. I think the editors can propose text referring to the draft - there is no intended change to the technical spec.

**Comment by martinthomson** [comment]
I'm sorry, I perhaps wasn't clear.  This is not stated as an issue.  "This document doesn't cite X" isn't an issue.  Is there something specific that is in RFC 8085 that is needed to address an issue?

**Comment by janaiyengar** [comment]
I suspect what I have in PR 3248 (
https://github.com/quicwg/base-drafts/pull/3248) ought to address this. I
think Gorry wanted to have normative reference for congestion control
conformance.

**Comment by gorryfair** [comment]
Yes, and WFM - see single comment on the PR.

**Comment by janaiyengar** [comment]
If this goes into late-stage, it should be design.
