### ISSUE TITLE
I am concerned the congestion control text is too permissive.

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#3247]
The docs call out that the design is based on (new)Reno. That is good and suitable for a PS. I have no problem here.

However, there are several places where the text is very permissive "MAY..." that suggests the PS can implement this or anything else. This combination seems awkward for a PS. I'd hoped that we could allow experimentation with new CC's but say SHOULD use an IETF-specified congestion control method, or something text close to that, and change the MAYs into something more helpful. I think this is an easy piece of text to get correct.

**Comment by gorryfair** [comment]
Please check appendices, e.g.

" Constants used in loss recovery are based on a combination of RFCs,
   papers, and common practice.  Some may need to be changed or
   negotiated in order to better suit a variety of environments."
- that final sentence needs thought.

**Comment by janaiyengar** [comment]
If this goes into late-stage, it should be design.
