### ISSUE TITLE
clarify when a client needs to include the version

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#325]
There's conflicting information in Section 6.1:

First it says

> If the packet contains a version that is acceptable to the server, the server proceeds with the handshake (Section 6.2). All subsequent packets sent by the server MUST have the VERSION flag unset.

Two paragraphs later it says

> The client MUST set the VERSION flag and include its selected version on all packets until it has 1-RTT keys and it has received a packet from the server that does not have the VERSION flag set.

This is conflicting, because the client may receive a packet from the server (which is not a Version Negotiation Packet, meaning that the server accepted the proposed version) before having the 1-RTT keys.

Furthermore, the last part of the last sentence makes little sense anyway. It's impossible for the client to have 1-RTT keys unless the server already accepted the version.

**Comment by martinthomson** [comment]
These are two separate requirements: the first describes when the server can use the VERSION flag, the second describes when the client can use the VERSION flag.

The latter sentence is the logical conjunction:

```
must_include_version_flag = has_1rtt_keys() && received_packet_without_version()
```

Can you propose a way to reword this that is less confusing to you?

**Comment by marten-seemann** [comment]
@martinthomson: Seems I didn't read carefully enough. There's no conflict in that paragraph. Sorry for that!

I'd still suggest to shorten the second sentence to 

> The client MUST set the VERSION flag and include its selected version on all packets until it has 1-RTT keys.

because there's no way a client can obtain a 1-RTT key from a version negotiation packet.

**Comment by martinthomson** [comment]
The extra condition is a concession to proprietary things that Google are doing.  If you can convince @janaiyengar, I'd be very happy to make that change.

**Comment by ianswett** [comment]
I think we want the ability to do out of band key negotiation, and not just for Google internal use cases, because I believe others will/do have similar use cases.

**Comment by marten-seemann** [comment]
That makes sense, I didn't consider that use case.
I guess nothing needs to be changed here then.
