### ISSUE TITLE
Contradictory language regarding multiplexing connections with zero-length IDs

### ISSUE THREAD

**Issue by Ralith** [quicwg/base-drafts#3254]
[§5.1](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#connection-id):

> A zero-length connection ID can be used when a connection ID is not needed to route to the correct endpoint. However, multiplexing connections on the same local IP address and port while using zero-length connection IDs will cause failures in the presence of peer connection migration, NAT rebinding, and client port reuse; and therefore MUST NOT be done unless an endpoint is certain that those protocol features are not in use.

[§5.2](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#packet-handling):

> If the Destination Connection ID is zero length and the packet matches the **local** address and port of a connection where the host used zero-length connection IDs, QUIC processes the packet as part of that connection.

> Packets with a supported version, or no version field, are matched to a connection using the connection ID or - for packets with zero-length connection IDs - the local address and port.

If only the local address is used, the described multiplexing is impossible. Multiplexing zero-length connection IDs is useful for reducing overhead when remote clients are known to not use the described features, so I think this language should be updated to refer to the 4-tuple rather than only the local connection.

**Comment by martinthomson** [comment]
I don't think that these are completely inconsistent, though there is an unstated section in those quotes from Section 5.2: that the implementation has followed the advice and provided a unique local address where it uses a zero-length connection ID.

This needs a little care, but we could just remove "local" and this would be OK, but it's probably best to be a little less crude.

**Comment by Ralith** [comment]
I think literally "the packet matches the address and port of a connection" would be much too vague, particularly due to the singular forms used.
