### ISSUE TITLE
Clarify padding of INITIAL packets

### ISSUE THREAD

**Issue by rmarx** [quicwg/base-drafts#3255]
Following a discussion on Slack (cc @jlaine, @nibanks, @rpaulo ), I feel a clarification might be needed on how/which INITIAL packets should be padded to 1200 bytes.

E.g.,  https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-8.1 states:

> Clients MUST ensure that UDP datagrams containing Initial packets
   have UDP payloads of at least 1200 bytes, adding padding to packets
   in the datagram as necessary.

Some people (cc @nibanks) interpret this to mean ALL packets containing initials should be padded (e.g., also an initial ACK from the client to the server) and not just the first initials with crypto data from the client. 

However, https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-14 somewhat contradicts/restates this:

> The payload of a UDP datagram carrying the first Initial packet MUST
   be expanded to at least 1200 bytes, by adding PADDING frames to the
   Initial packet and/or by coalescing the Initial packet (see
   Section 12.2).

@nibanks said he feels this should be removed/restated.

I personally don't know why ALL initials should be padded outside of the first flight... @nibanks mentioned the stateless LB use case, where they could drop all initials < 1200 bytes, though I'm not sure why a LB would do this... @rpaulo mentioned that padding the client's initial ACKs gives additional allowance towards the 3X amplification factor limit, but as those intitial ACKS will arrive with/close to the client's first handshake packet (which validates the path, IIUC, https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-8.1). 

Either way, I feel the text should be tightened to clarify the intended use.
Full disclosure: we're working on some dirty stuff that spoofs/abuses QUIC initials to carry in-band metadata, so we'd really not like intermediaries dropping < 1200 byte initials by default.

**Comment by RyanAtGoogle** [comment]
"Some people (cc @nibanks) interpret this to mean ALL packets containing initials should be padded"

This matches my interpretation and sounds simple and straightforward.

**Comment by kazuho** [comment]
Yes. We have the consensus to require *every* datagram containing an Initial packet to be padded. See #2522.

**Comment by ianswett** [comment]
To clarify, section 8.1 talks about client Initials.  @RyanAtGoogle at @kazuho are you saying all datagrams containing client Initial packets or all datagrams containing Initial packets?

I think there are some uses for non-padded server to client Initials, such as a CONNECTION_CLOSE.

**Comment by rmarx** [comment]
I also meant client-sent initials. Though, I assume for asymmetric PMTU reasons, the server's initials should also be 1200+ bytes?

IIUC correctly from the comments above: requiring client initial ACKs to also be 1200+ is mainly out of convenience/consistency (#2522)?  In that case, the text in section 14 should indeed be updated to make that more clear? I can submit a PR for that.

**Comment by kazuho** [comment]
@rmarx That is my understanding, and I think that a PR would be very welcome.

To clarify, the following statement in section 8.1 is correct as I understand: _Clients MUST ensure that UDP datagrams containing Initial packets have UDP payloads of at least 1200 bytes, adding padding to packets in the datagram as necessary._.

The text in section 14 seems to be incorrect (likely out-of-date).

**Comment by janaiyengar** [comment]
I'm pretty sure that the text in Section 14 is outdated, and should probably be removed, with a short reference to section 8.1.

**Comment by martinthomson** [comment]
That's right, that's just cruft.

**Comment by rmarx** [comment]
Thank you for the PR Martin. 

Just for my understanding: the requirement to pad client initials from the second flight onward (i.e., after receiving server packets, ACKing server initials) is purely for convenience. It is not necessary for PMTU or anti-amplification-allowance. As such, the limit should also not be enforced at intermediaries wholesale?

**Comment by martinthomson** [comment]
For the most part, yes, the second flight is generally sent with some evidence that the return address is live, however we can't guarantee that the second flight carries sufficient entropy.

For instance, HelloRetryRequest causes a second flight that still requires anti-amplification.

Initial packets with acknowledgments in the second flight might still require padding in the case that the client isn't able to send Handshake packets (which can happen when you have a partial server flight).

In the end, this is just simpler.  I would be sad if intermediaries were to "enforce" MUSTs from QUIC.

**Comment by RyanAtGoogle** [comment]
In thinking about this a bit more, I wonder if 8.1 says everything we want it to say:

_Clients MUST ensure that UDP datagrams containing Initial packets have UDP payloads of at least 1200 bytes, adding padding to packets in the datagram as necessary._

What about INITIAL packets which contain only a CONNECTION_CLOSE frame? Should those be padded? It doesn't seem terribly necessary to do this...

**Comment by ianswett** [comment]
For the client, I think requiring padding even a CONNECTION_CLOSE is the right thing to do, since it simplifies processing on the server side.  On the server, I definitely do not want to require padding Initials that only contain CONNECTION_CLOSE.

**Comment by janaiyengar** [comment]
Yeah, it should be super uncommon for a client to send a CONNECTION_CLOSE in Initial, and I don't think the cost of padding it is terribly high in that uncommon case. I think keeping it simple is probably best here.

**Comment by kazuho** [comment]
The far most likely case of a server receiving a CONNECTION_CLOSE is a middlebox trying to disrupt the handshake (i.e. RST injection). I do not think we should help them by relaxing the full-size padding requirement.
