### ISSUE TITLE
Disabling Spin bit for what percentage of connections?

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#3257]
The draft says:
> The random selection process SHOULD be designed such that on average the spin bit is disabled for at least one eighth of network paths.

Given that each endpoint needs to decide for itself whether it is enabling spin bit, it is not exactly clear whether each endpoint SHOULD disable spin bit on at least 1/8 (=12.5%) of connections, or it can assume that the other endpoint is also making a random decision to disable and disable only on 1-sqrt(7/8) (=6.5%) of connections.

**Comment by britram** [comment]
as the author of this passage, I intended the latter (assume the other side is disabling as well, so 1-sqrt(7/8)), but the "at least" is in there since just disabling 1/8 is probably what people will do, and the result (about 1/4) is "at least 1/8".

**Comment by igorlord** [comment]
@britram could you review #3270?
