### ISSUE TITLE
Allow CRYPTO_BUFFER_EXCEEEDED error when CRYPTO frame goes beyond 2^62 bytes

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3258]
When discussing #3027 at Cupertino, we agreed that either of the following two errors can be sent when the payload of the STREAM frame exceeds 2^62 bytes:
* FRAME_ENCODING_ERROR
* FLOW_CONTROL_ERROR

And we've merged PR #3042 that made that change, along with other changes. However, in that PR, we failed to apply the rule that we agreed for SRTEAM frame to CRYPTO frame.

Editors' draft now allows use of FRAME_ENCODING_ERROR for CRYPTO frames, but not CRYPTO_BUFFER_EXCEEDED.

As CRYPTO_BUFFER_EXCEEDED *is* the flow control error for CRYPTO streams, that should be permitted too.

To be fixed by PR #3186.

**Comment by martinthomson** [comment]
Thanks for doing all of this Kazuho.

**Comment by martinthomson** [comment]
#3186 fixed this one.
