### ISSUE TITLE
Reduce HTTP/3 editorial dependence on HTTP/2

### ISSUE THREAD

**Issue by royfielding** [quicwg/base-drafts#3264]
The HTTP/3 draft relies on the reader's familiarity with the HTTP/2 spec, bouncing between normative references to HTTP/2 and specification as a delta to some prior decision for HTTP/2. While that's understandable for initial development and for a section on gatewaying to h2, I don't think it is appropriate for a standards track document that will eventually (or at least likely) obsolete HTTP/2.

I don't expect readers (outside of the WG members) to have implemented h2, even if the design is based on h2. I would like all of the necessary concepts, aside from what can be normatively referenced via http-core, to be fully defined within this spec, even if that means copy and paste from h2.

(I would label this as editorial and -http)

**Comment by ianswett** [comment]
I agree that readers should not be required to read the HTTP/2 spec.  We've taken the same approach with recovery where the intent is to be self-contained, but add informative references to TCP RFCs.

**Comment by MikeBishop** [comment]
I agree with that principle, but I've been working on that for a while, but I think we're already mostly there.  There are normative references to specific sections of HTTP/2 where relevant; I've attempted not to have anything that assumes you already know HTTP/2 in general.  The informative comparisons to HTTP/2 have largely (if not entirely) been moved to an appendix.

If you have specific places where you think I haven't achieved that, please point them out.

**Comment by MikeBishop** [comment]
Rereading this, I see there's a distinction between your suggestion and my previous attempts to separate them -- you want to get rid of all normative references to RFC7540, duplicating text as necessary and leaving only informative references for further reading.

Let me take a look at this.  At first pass, many of the 7540 references could be informative, but some specific sections are referenced as a whole.  I tend to think that a reference to a specific section is sufficient, but if it's small enough to copy over, that might work too.

**Comment by MikeBishop** [comment]
QUIC is described in {{QUIC-TRANSPORT}}.  For a full description of HTTP/2, see
    {{!HTTP2=RFC7540}}.

Pretty clearly informative.

    Server push is an interaction mode introduced in HTTP/2 {{!HTTP2}} which permits
    a server to push a request-response exchange to a client in anticipation of the
    client making the indicated request.  This trades off network usage against a
    potential latency gain.  Several HTTP/3 frames are used to manage server push,
    such as PUSH_PROMISE, DUPLICATE_PUSH, MAX_PUSH_ID, and CANCEL_PUSH.

*Probably* informative.

    A server that does not wish clients to reuse connections for a particular origin
    can indicate that it is not authoritative for a request by sending a 421
    (Misdirected Request) status code in response to the request (see Section 9.1.2
    of {{!HTTP2}}).
    
    The considerations discussed in Section 9.1 of {{!HTTP2}} also apply to the
    management of HTTP/3 connections.

Just referencing the definition of the existing response code could go either way.  Might want to copy over the connection management advice.

    As in HTTP/2, HTTP/3 uses special pseudo-header fields beginning with the ':'
    character (ASCII 0x3a) to convey the target URI, the method of the request, and
    the status code for the response.  These pseudo-header fields are defined in
    Section 8.1.2.3 and 8.1.2.4 of {{!HTTP2}}. Pseudo-header fields are not HTTP
    header fields.  Endpoints MUST NOT generate pseudo-header fields other than
    those defined in {{!HTTP2}}.  The restrictions on the use of pseudo-header
    fields in Section 8.1.2 of {{!HTTP2}} also apply to HTTP/3.  Messages which
    are considered malformed under these restrictions are handled as described in
    {{malformed}}.

This definitely would require copying text; it's a purely normative reference to a specific section of RFC 7540.

    To allow for better compression efficiency, the cookie header field {{!RFC6265}}
    MAY be split into separate header fields, each with one or more cookie-pairs,
    before compression. If a decompressed header list contains multiple cookie
    header fields, these MUST be concatenated before being passed into a non-HTTP/2,
    non-HTTP/3 context, as described in {{!HTTP2}}, Section 8.1.2.5.

This might require some text copying, or might be informative -- I'd have to read the section in more detail.

    A CONNECT request in HTTP/3 functions in the same manner as in HTTP/2. The
    request MUST be formatted as described in {{!HTTP2}}, Section 8.3. A CONNECT
    request that does not conform to these restrictions is malformed (see
    {{malformed}}). The request stream MUST NOT be closed at the end of the request.

This would require text copying.

    Server push is an interaction mode introduced in HTTP/2 {{!HTTP2}} which permits
    a server to push a request-response exchange to a client in anticipation of the
    client making the indicated request.  This trades off network usage against a
    potential latency gain.  HTTP/3 server push is similar to what is described in
    HTTP/2 {{!HTTP2}}, but uses different mechanisms.

This is purely informative.

    The header of the request message is carried by a PUSH_PROMISE frame (see
    {{frame-push-promise}}) on the request stream which generated the push. This
    allows the server push to be associated with a client request.  Promised
    requests MUST conform to the requirements in Section 8.2 of {{!HTTP2}}.

Requires text copying.

    The security considerations of HTTP/3 should be comparable to those of HTTP/2
    with TLS; the considerations from Section 10 of {{!HTTP2}} apply in addition to
    those listed here.

Seems kind of borderline -- this isn't really normative text, but you really should read the security considerations.

All the references in IANA Considerations and H2 Considerations are explicitly informative, so the switch would be easy there.
