### ISSUE TITLE
Retry packet with zero-length token doesn't make sense

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#3271]
The Retry packet currently allows sending an empty token. The Retry token is defined as an opaque blob 
```
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                        Retry Token (*)                      ...
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
where `(*)` "indicates that x is variable-length", which also includes zero-length values.

On the wire, an Initial packet with a zero-length token is identical to an Initial without a token. However, there's a difference on the client side, since a client will perform at most a single Retry.

**Comment by martinthomson** [comment]
Tagging this editorial.  This was clearly intended to be considered non-zero length.
