### ISSUE TITLE
TIME_WAIT

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#328]
6.4 currently has
`TODO: Connections that are terminated are added to a TIME_WAIT list at the server, so as to absorb any straggler packets in the network. Discuss TIME_WAIT list.`

this is an open issue for the TODO.

Some initial thoughts: is it always the server that is in TIME_WAIT as opposed to the TCP active close behavior? (seems fine at first blush, but asking for a friend who is less sure :)).

what happens in the TIME_WAIT state.. retransmissions? What happens when you receive packets (ignored - trigger retrrans, RST?)

**Comment by RyanAtGoogle** [comment]
In the current Google QUIC implementation, for each connection in time
wait, the server saves the serialized "close" packet for that connection.
When new packets are received for that connection, the server retransmits
the close packet (subject to back-off). This is to handle the case where
the close packet is lost and so the client is unaware that the connection
has been closed. I can imagine that there might be better alternatives,
though.

**Comment by mcmanus** [comment]
on the list @janaiyengar notes

> On the point of what to do in TIME_WAIT, the server should hang on to some
> state. At the least, hanging on to the connection ID protects the server by
> preventing late packets from causing creation of new connection state, and
> the server can simply discard incoming packets for connection IDs in
> TIME_WAIT. (If a server wanted to hang on to more state, it could do so,
> allowing it to retransmit CONNECTION_CLOSE frames later, but as you note,
> this is more state and I wouldn't require it.)

```

**Comment by MikeBishop** [comment]
But why is that the server specifically?  It seems like either peer, having sent a CONNECTION_CLOSE and not received one, needs to be in this state.

**Comment by martinthomson** [comment]
I think that @MikeBishop is right.

Rather than just fixing this one small thing, I think that we need a more comprehensive rework of the shutdown logic.  @janaiyengar sent an email to the list outlining one extreme in the design space.  I want to write up a proposal that is close to that.  That will necessarily include a roughly 2xRTO TIME_WAIT2-like state on both peers.  Then we can discuss whether that sort of design is desirable.

**Comment by martinthomson** [comment]
Fixed by #721, I hope.
