### ISSUE TITLE
Define AreAllPacketsLost() function

### ISSUE THREAD

**Issue by ghedo** [quicwg/base-drafts#3288]
It's not very clear how the `AreAllPacketsLost()` function in the recovery draft should be implemnted, so having more guidance would be helpful.

**Comment by ianswett** [comment]
Also, I believe the example is incorrect, and should be (7 - 0) = 7.  3 is correct for the packet number, not for the time.

`If an ack-eliciting packet is sent at time = 0, the following
   scenario would illustrate persistent congestion:

                     +-----+------------------------+
                     | t=0 | Send Pkt #1 (App Data) |
                     +-----+------------------------+
                     | t=1 | Send Pkt #2 (PTO 1)    |
                     |     |                        |
                     | t=3 | Send Pkt #3 (PTO 2)    |
                     |     |                        |
                     | t=7 | Send Pkt #4 (PTO 3)    |
                     |     |                        |
                     | t=8 | Recv ACK of Pkt #4     |
                     +-----+------------------------+

   The first three packets are determined to be lost when the ACK of
   packet 4 is received at t=8.  The congestion period is calculated as
   the time between the oldest and newest lost packets: (3 - 0) = 3.
   The duration for persistent congestion is equal to: (1 *
   kPersistentCongestionThreshold) = 3. `

**Comment by ianswett** [comment]
Sorry, disregard my second comment, the example is correct.

**Comment by ghedo** [comment]
Made https://github.com/quicwg/base-drafts/pull/3290 to update the pseudo-code.

**Comment by kazu-yamamoto** [comment]
As suggested in https://github.com/quicwg/base-drafts/pull/3290#discussion_r355089680, what about the following?

```
congestion_period <= largest_lost_packet.time_sent - earliest_lost_packet.time_sent
```

We should check if `largest_lost_packet /= earliest_lost_packet` before that.

**Comment by kazu-yamamoto** [comment]
@ianswett @janaiyengar I would like to hear your opinions about the suggestion above.

**Comment by martinthomson** [comment]
@kazu-yamamoto, I think that you might want to look at #4010.  If you could review that, it might help.

**Comment by kazu-yamamoto** [comment]
@martinthomson Thanks. I will try to review it.

**Comment by LPardue** [comment]
All linked PRs seem to meet a tragic end. What needs to be done here?

**Comment by LPardue** [comment]
#4080 closed this but GitHub automation was too late. Manually closing.
