### ISSUE TITLE
Allow use of token after client address changes

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#3307]
[Section 8.1.3 of the transport draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-address-validation-for-futu) states:
```
A client MUST NOT reuse a token if it believes that its point of network attachment has changed
since the token was last used; that is, if there is a change in its local IP address or network
interface.
```

This is an unnecessary constraint and there’s value in not having it. A server can, for example, include multiple IP addresses for a client in a token, enabling client validation from multiple attachment points.

**Comment by kazuho** [comment]
Agreed.

Just to give one example, it'd make sense for a server to issue a NEW_TOKEN token containing two addresses, if the client is using one path to communicate while having another path being probed and validated.

Note also that it is difficult to implement the MUST NOT that exists now. Consider the case where a client receives a NEW_TOKEN frame during or after path migration. Is the client expected to bind the token to the old IP address? Or the new address? It is hard to tell the intention of the server.

**Comment by ianswett** [comment]
I agree this seems unnecessary, given tokens cannot be used multiple times.

The worst case scenario is including the token increases the number of Initial packets the client needs to send to two packets from one and the token turns out not to be useful for address validation.

**Comment by ianswett** [comment]
As is clear from the PR, this should be marked design.
