### ISSUE TITLE
Guidance wrt ACK frames that don't fit in a packet

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#3311]
The [ACK frame section](https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-19.3) of the Transport Draft should explain what to do when generated ACK is too large to fit in a packet:
1. Generate a shorter ACK frame (instead of aborting connection or erroring out).
2. To generate the shorter frame, don't include older (smaller) packet numbers.  (As opposed to not including newer packet numbers.)

**Comment by ianswett** [comment]
There is a good amount of existing text about what ranges to send, ie "ACK frames SHOULD always acknowledge the most recently received packets,"

I think this can be solved with some editorial additions to 13.2.2.
https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-13.2.2

**Comment by janaiyengar** [comment]
The text we already have in 13.2.4 has the right context:
```
  To limit receiver state or the size of ACK frames, a receiver MAY
   limit the number of ACK Ranges it sends.  A receiver can do this even
   without receiving acknowledgment of its ACK frames, with the
   knowledge this could cause the sender to unnecessarily retransmit
   some data.
```

**Comment by janaiyengar** [comment]
Ok, this became a bigger fix. See #3316 and #3315.
