### ISSUE TITLE
Fix language in recommendations for ack-range limits

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#3316]
In trying to do a simple fix for #3311, I found other irrelevant or poorly-written recommendations in how a receiver could limit ACK ranges it sends. This section needs to be rewritten.

Specifically, the sentence below is a poor recommendation and contradicts earlier recommendation on acking until the ACK frame is acknowledged.
```
   The receiver SHOULD
   exclude already acknowledged packets from future ACK frames whenever
   these packets would unnecessarily contribute to the ACK frame size.
```

The recommendation below is fine, but the rationale does not make sense:
```
   Standard QUIC algorithms ([QUIC-RECOVERY]) declare
   packets lost after sufficiently newer packets are acknowledged.
   Therefore, the receiver SHOULD repeatedly acknowledge newly received
   packets in preference to packets received in the past.
```

This should be a design change.

**Comment by ianswett** [comment]
I'm not in love with this (entire) section either, but I'd like to better understand this issue.

I agree that sentence is mis-written, though I think the intent was fine.

On the rationale, can you clarify why it does not make sense?
