### ISSUE TITLE
Grease HTTP/3 error codes

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3325]
The discussion on #3276 made us conclude that the reason for doing this is that we want to safeguard our ability to define new error codes.  Greasing might help with that.

**Comment by LPardue** [comment]
Since you'd probably want want the grease to not sacrifice connections it might make sense to couple grease error codes to H3 grease streams.

Also, what about greasing of transport-level error codes? Can't play the stream tricks there.

**Comment by MikeBishop** [comment]
Unknown error codes are supposed to be equivalent to H3_NO_ERROR.  Perhaps a recommendation (SHOULD) to substitute a grease code with non-zero probability when you would have sent NO_ERROR?  And MAY use them when terminating grease streams, sure.
