### ISSUE TITLE
Clarify what the "first Initial packet" is

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#3329]
Section 14 of the [Transport Draft](https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-14) states:

```
   The payload of a UDP datagram carrying the first Initial packet MUST
   be expanded to at least 1200 bytes, by adding PADDING frames to the
   Initial packet and/or by coalescing the Initial packet (see
   Section 12.2).
```

If the first Initial packet gets resent, the second incarnation of it is no longer the _first_ Initial packet.

Instead of specifying this packet as the "first Initial packet," we could state this as
- Initial packets carrying the first CRYPTO frame; or
- the first Initial packet received by the client.

**Comment by ianswett** [comment]
I believe the editor's copy fixes this(https://github.com/quicwg/base-drafts/blob/master/draft-ietf-quic-transport.md#packet-size-packet-size), but there are some other occurrences of "first Initial packet" which should be reviewed.

For example, I also noticed "A server sends its first Initial packet in response to a client Initial. A server may send multiple Initial packets." in https://github.com/quicwg/base-drafts/blob/master/draft-ietf-quic-transport.md#initial-packet-packet-initial

I think the second sentence is from when the client could only send one initial, so the two sentences should possibly be changed to: "A server sends its first flight of Initial packets in response to the client's Initial flight." or something of that sort?

**Comment by martinthomson** [comment]
Ian is right.  There are two things that hang off this (broken) concept of "first Initial":

1. the client-selected destination connection, which changes once the client has received an Initial packet from the server
2. the size constraints, which I think we have addressed

Let's make sure we get this right.
