### ISSUE TITLE
Immediate retransmission upon loss detection

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#3335]
TCP recommends that a sender retransmit a packet immediately upon detecting the first loss in a recovery window (see Section 3.2, second para, of RFC 5681; Section 5 of RFC 6675 seems to follow the same idea). QUIC should at least allow the same. Not doing this can delay loss recovery by 0.5 RTT, which is not great.

This replaces #2604; this is a more correct description of the problem, which is a design issue.

**Comment by larseggert** [comment]
Discussed in ZRH. Proposed resolution is to get a PR done.
