### ISSUE TITLE
Anti-amplification limits should count junk too

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3340]
>  In determining this limit, servers only count the size of successfully processed packets.

This is wrong.  If the server receives 0-RTT packets that it is discarding, it won't receive enough bytes to clear the 3x multiplier.  This needs to explicitly count all bytes received from the given address, even junk bytes.

I think that this is just editorial; this is just a mistake in transcription.  I'll defer to chairs.

**Comment by marten-seemann** [comment]
I'd like us to be a little bit more specific than "junk bytes". I can imagine that for many implementations, it would be hard to associate random junk sent from the same 4-tuple with the newly established connection, since implementations will track connections by their CID, not by 4-tuple.

If our intention is to include 0-RTT packets, it would be sufficient to count all datagrams that are received with the same QUIC DCID (no matter if they're actually processed or not).

**Comment by kazuho** [comment]
> If our intention is to include 0-RTT packets, it would be sufficient to count all datagrams that are received with the same QUIC DCID (no matter if they're actually processed or not).

I might actually prefer this definition (i.e. sum of QUIC packets sent on the correct path using correct CIDs, regardless of if they were processable), above a definition that states that the amplification limit is 3x the sum of the size of UDP datagrams that an endpoint has received on the correct path.

It is easier to implement (because all the logic can be implemented at the QUIC packet processing layer), and it has the nice side-effect of deterring padding outside QUIC packets (#3333).

**Comment by ianswett** [comment]
I have no objection to requiring both CID and path to match, though I'll note that if the server changes the CID in an Initial packet, but the client doesn't receive enough data to generate handshake keys, it'll need to match against both CIDs.

**Comment by ekr** [comment]
I actually don't think this is editorial. The CID match requirement is clearly technical and, as has been noted before, this would cause problems with Neqo's padding strategy.

**Comment by martinthomson** [comment]
This came up in the room as well.  The current proposal is:

If a packet is successfully processed, then the bytes of the datagram that it was contained in count toward the amplification limit.

There is some question about whether servers are permitted to include other datagrams that are sent on the same path.  This might be easier for some people to manage, but @marten-seemann is concerned that it could lead to inconsistencies and therefore bugs.  Personally, I find the idea that purely junk datagrams MAY be counted to be acceptable.

**Comment by ianswett** [comment]
To add normative language to Martin's statement, "If a packet is successfully processed, then the bytes of the datagram that it was contained in MUST count toward the amplification limit."

Additionally, I'd suggest if the long header matches, but it's not processable(ie: 0-RTT), then it SHOULD count and pure junk MAY count.  As such clients cannot rely on non processable packets to increase amplification limits.

**Comment by kazuho** [comment]
I share @ianswett's concern regarding 0-RTT packets.

At the moment, [section 8.1](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-8.1-4) states:
> In order to avoid this causing a handshake deadlock, clients SHOULD send a packet upon a probe timeout, as described in [QUIC-RECOVERY]. If the client has no data to retransmit and does not have Handshake keys, it SHOULD send an Initial packet in a UDP datagram of at least 1200 bytes.

As you can see, we do not require the probe to be an Initial packet. They could be purely 0-RTT packets. If we are to allow an endpoint calculate amplification factor at QUIC packet level, we need to change this provision.

And that change should require the client to send probes as Initial packets that are large enough. It cannot simply be a packet that contains only one byte PADDING (or PING).

To me, that seems a bit too complicated.

**Comment by ianswett** [comment]
All client Initial packets are in full-sized datagrams, based on my understanding, so a PING is fine in practice.

And the PTO is never armed for 0-RTT, so the probe packets would not be 0-RTT.  That being said, I'm a bit concerned those are SHOULDs and not MUSTs.

**Comment by kazuho** [comment]
@ianswett 
> And the PTO is never armed for 0-RTT, so the probe packets would not be 0-RTT. That being said, I'm a bit concerned those are SHOULDs and not MUSTs.

Yeah, I am concerned that it might be fragile to rely on the behavior of recovery. Moreover, if the client has large amount of data to send, it'd me natural for that client to continue sending datagrams, each of them consisting of a tiny Initial packet and a large 0-RTT packet.

**Comment by ianswett** [comment]
So the interesting case is when 0-RTT is accepted, but address validation is not?  And therefore, the server can process 0-RTT packets but cannot send much in response?

If so, I hadn't considered that, but I could document that case in recovery if it's helpful?

**Comment by mikkelfj** [comment]
If random packets from a given source is counted, I could imagine a spoofed source attack that piggy backs on valid connections to amp up its own traffic.

Initial packets can have zero length SCID, and ODCID with very little information, so linking to CIDs might not be much more effective.

**Comment by martinthomson** [comment]
With #3333 being recently resolved, what are we missing on this issue?  Is it just a duplicate?

**Comment by ianswett** [comment]
This feels like a duplicate to me.

**Comment by martinthomson** [comment]
As this is untriaged, I'm going to triage it as "invalid" and close it.  That isn't an indictment on any of the comments here (except perhaps mine, since I opened this), just a judgment on the necessity of doing anything.
