### ISSUE TITLE
max_ack_delay should be in us, not ms

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#3363]
The presentation on low latency TCP options presents a way to convey max ack delay of ms, us and ns.  I don't think we need to do ns(?) in QUIC, but it's clear datacenter use cases will want us, so I believe we should change from ms to us.
https://datatracker.ietf.org/meeting/99/materials/slides-99-tcpm-tcp-low-latency-option-00

ack_delay in the QUIC ACK frame is already in microseconds(admittedly scaled), so I think this is more consistent as well.

**Comment by martinthomson** [comment]
This is a big fat design issue that will have a serious impact on existing implementations.  It sounds perfectly reasonable, but we'll need to run the process.

**Comment by ianswett** [comment]
Yes, I agree it's a design issue.  

I confirmed with the TCP team at Google and they agreed microseconds was a better choice than millis.

I will say that we can punt this and make the extension Jana and I are working on specify it in us, but that seems a bit hacky to me given we haven't yet shipped QUIC v1.

**Comment by janaiyengar** [comment]
We did discuss this a while ago when we decided to use ms here, and we thought it was quite reasonable. (I cannot recall the arguments, I'll have to dig up the issue.) There's also a limit of 2^14 on this, which will have to change if you wanted to go down to microseconds.

Thinking about this, I agree with @martinthomson: I don't think we should be opening up a design issue for consistency if it doesn't solve any other issues.

(FWIW, @ianswett, let's work on getting the extension accepted first before making changes in core spec to accommodate it.)

**Comment by ianswett** [comment]
I did a quick search for microseconds and couldn't find anything about the tradeoff of ms vs us, but maybe you'll have better luck:
https://github.com/quicwg/base-drafts/issues?utf8=%E2%9C%93&q=is%3Aissue+microseconds

**Comment by larseggert** [comment]
I think the argument was that the number would be smaller = use less bits. (Not that I care much.)

**Comment by martinthomson** [comment]
Yeah, that was the idea, but on the presumption that values below 1ms wouldn't have a huge effect on performance.  But this is now part of the PTO calculation.

Right now, we could have had up to 63ms in one byte.  With the proposed change, you get 4 bytes if you want to signal 25ms.  But that is once per connection, and hardly the end of the world.  Reduce the value below 16ms to save two bytes.

It's a bit weird that it is possible to advertise a very small value without first measuring RTT to the peer, but I guess that this is what narrow deployment contexts are all about.  The question is to what extent we think that this becomes too specialized for general purpose use.  We are, after all, designing for the big "I" Internet and advertising max_ack_delay of 10us is hardly suited to trans-continental use.

An alternative would be to to define an extension with the smaller, more granular value.  That might say: if sRTT < X, then I will reduce max_ack_delay to Y.  Or variations on that theme.

**Comment by ianswett** [comment]
Thanks for the comments.  I think it makes sense to discuss this more once the extension draft @janaiyengar  and I wrote is published, since that allows updating max_ack_delay in us.  It's possible that's enough and then we should just close this issue and move on.

**Comment by mnot** [comment]
OK. Closing in triage, then.

**Comment by marten-seemann** [comment]
Should this be reopened now that everybody is rewriting their transport parameter code anyway (#3169)?

**Comment by ianswett** [comment]
I think the thought was that if you want microsecond resolution, the ack-frequency draft is what you should implement, since it can be sent after an RTT measurement of the path has been made.

But I'd be happy to discuss this tomorrow when we discuss ack-frequency.
