### ISSUE TITLE
Retry integrity protection should not add new requirements to TLS API

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3366]
Retry integrity protection (#3120) specifies the AES-GCM key and IV directly. While that works fine for people using TLS stacks that provide direct access to AES-GCM, it does not for people using TLS stacks that only provides access to TLS AEAD API. Previously, we have been consistent in using HKDF-Expand-Label in a specific way so that people could rely on the "TLS" stack generating AEAD contexts.

I think we can resolve the concern by simply changing the hard-coded AES-GCM key and IV we specify in the TLS draft to a set of values that can be derived by using the TLS AEAD API.

**Comment by martinthomson** [comment]
It would be easier for me to do as @kazuho suggested, but the overall effort is small.  I can live with either answer.  Note that the additional indirection can be hard-coded out if people find they want to prime their AES directly.  Of course, you don't need to run AES at all if you want to go that far.

**Comment by kazuho** [comment]
I agree that this is not a must, even though it's about helping some of the implementations.

I would highly appreciate it if you could merge the PR before -25 ships, as I think changing the default key before shipping the first draft that adopts the GCM-based Retry protection would have the least friction.

**Comment by janaiyengar** [comment]
This is useful, and we should merge this. I don't think this needs to be design.
