### ISSUE TITLE
Clarify CANCEL_PUSH server send conditions

### ISSUE THREAD

**Issue by BrianGithubber** [quicwg/base-drafts#3387]
The current draft (7.2.3) says:
A server SHOULD NOT send a CANCEL_PUSH when it has already created a corresponding push stream.

However, this is ambiguous.   In our implementation, at least, it is possible to create a push stream, but not have sent anything on that push stream yet.
If a failure happens while in this state, and we don’t send a CANCEL_PUSH per current draft, then the peer will never know that that push stream has failed.

A possible suggested edit could be:
A server SHOULD NOT send a CANCEL_PUSH after it has completed a send on the corresponding push stream of the pushId.

**Comment by LPardue** [comment]
In this state, the server could abruptly terminate the stream (I.E RESET_STREAM) with the error code H3_REQUEST_CANCELLED or H3_NO_ERROR

**Comment by martinthomson** [comment]
In some cases, creating a stream can result in a STREAM frame being sent.  It depends on the shape of the contract between the different components.  And it also might be difficult to determine whether anything has been sent.

I believe that the existing language is fine.

If you have created a stream object locally, and can be sure that the other side is unaware of this, and you have some means of taking it back or repurposing it, then it's fine to do that.  Note that this is only a "SHOULD" anyway.
