### ISSUE TITLE
recovery: initial reordering threshold

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#3389]
The doc says:
"Implementations that detect spurious retransmissions and increase the
   reordering threshold in packets or time MAY choose to start with
   smaller initial reordering thresholds to minimize recovery latency."

For the packet based threshold does that this say that a smaller initial value than 3 packets could be used? Is that really sensible?

And for a time based threshold I don't really understand what this means because the threshold is anyway calculated dynamically based on the RTT, so there is no real initial value. I guess there was a time when the threshold was a fixed value and this sentence is maybe a left-over?

**Comment by ianswett** [comment]
Given the current guidance to never use packet thresholds below 3, I think this text should be changed to be clear that you can start with a smaller fraction of RTT and it only applies to time threshold.

**Comment by ianswett** [comment]
I think the fix will be editorial, but once a PR is out we'll know for sure.

**Comment by mirjak** [comment]
If it's only about time-based threshold, any advise should be moved in the respective subsection. However, I would also be okay to just remove this sentence/paragraph...
