### ISSUE TITLE
Scale flow control offsets

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#340]
@ddragana observes that the 64-bit offset value in the WINDOW_UPDATE message is probably the first value that we will run out of (over packet numbers and stream numbers, which should last a bit longer in most cases).  We could avoid this by multiplying these values by a constant (she suggests 1024), which would reduce the granularity with which flow control credits could be granted, but increase the total lifetime of a long-lived connection.

So, trade-off time.  The scaling multiplier is now 1.  A larger value allows for longer-lived connections, a shorter value allows finer control over flow control.  I'd suggest that values in the order of 8 are probably easy to justify, can we go as high as 1024?

We could also choose a different value for the connection and stream flow control offsets on that basis that connections need more octets, whereas streams do not.

**Comment by ddragana** [comment]
stream flow control does not need scaling. It is absolute offset.

**Comment by martinthomson** [comment]
Well, both are absolute, but you are right, there isn't much value in increasing the amount of data available to individual streams.

**Comment by martinthomson** [comment]
Closed by #378.
