### ISSUE TITLE
No type for `active_connection_id_limit` transport parameter

### ISSUE THREAD

**Issue by hawkinsw** [quicwg/base-drafts#3405]
Unlike the other transport parameter definitions, there is no type specified for the `active_connection_id_limit` parameter. I will assume that the type is an integer (like the other numeric-like transport parameters) and submit a PR to adjust the wording so that it is in line with the other transport parameter descriptions, if that's ok?

Thanks for all the great work that you are all doing on getting QUIC specified!

**Comment by erickinnear** [comment]
Good catch! Looks like all the other values have a type either implicitly or explicitly stated. `active_connection_id_limit` is indeed intended to be an integer, a PR to that effect would be great.
