### ISSUE TITLE
active_connection_id_limit description is unclear about whose connection ID might be zero length

### ISSUE THREAD

**Issue by nharper** [quicwg/base-drafts#3427]
The current language defining the active_connection_id_limit transport parameter refers to "a zero-length connection ID is being used". It's unclear whether the zero-length CID is the CID of the sender of the TP or the receiver of the TP. Since this TP limits how many CIDs the peer can send, the references to using a zero-length CID only make sense if it's the peer using a zero-length CID, but it would be useful to clean up that language.

I've created PR #3426 to clarify this language, including that checking whether the peer is using a zero-length CID can only be done by the server.

**Comment by martinthomson** [comment]
Chairs, the fix here turned out to be more complex.  Let's get wider review for this.
