### ISSUE TITLE
A fixed transport parameter profile is legitimate

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3429]
In the description of active_connection_id_limit, we require that the server make the value of the transport parameter conditional on the choice of connection ID from the client.

In the past, we have had the principle that either endpoint not condition its choice of transport parameter values based on anything from its peer.  We should maintain this principle throughout.

This means changing the definition of active_connection_id_limit;  @larseggert had a sense that there was another.

**Comment by ekr** [comment]
I'd like to understand what your argument is here. Is it that you *must not* condition your response, or merely that it is not necessary to.

For instance, you suppose we have a set of extensions that exist and that those extensions need to be jointly agreed on whether they will be done. The client supports some set E_c and the set of extensions E_s. The client clearly sends E_c. Is your argument that the server must send E_s and not E_c \cap E_s and the client must compute the intersection? Or that it might send either?

**Comment by nharper** [comment]
My understanding of the argument is that we shouldn't force servers to condition their TPs based on the client's Initial packet (possibly including TPs). E.g. the server currently needs to condition its active_connection_id_limit TP based on whether the client's Initial had a zero-len SCID; PR #3426 relaxes that constraint.

Assuming we have some future sets of TPs for extensions (and these TPs are advertised values, not negotiated values) E_c on the client and E_s on the server: The server could always send E_s (so it doesn't have to condition its response), or the server could send E_c \cap E_s, and in either case the client will ignore values sent by the server not in E_c. For future extensions that have negotiated transport params, the server will have to condition those values based on what the client sent.

**Comment by martinthomson** [comment]
MAY send a fixed set (so MAY NOT condition the response I guess) or that it is not necessary to.

So managing intersection of incompatible extensions is one case where conditioning might seem to be necessary, but that can be resolved by establishing precedence for instance.

**Comment by nharper** [comment]
I looked through the existing transport parameters for what currently conflicts with a fixed profile of transport parameters. I've only found one (apart from the already discussed active_connection_id_limit): original_connection_id. This field is necessarily dependent on what the client sends. The only way to avoid this is to not send Retry packets so you don't need to send this TP. The rest of the transport parameters appear to be independent of what the peer sent.

**Comment by dtikhonov** [comment]
What about stateless_reset_token?  I doubt many servers would send a static value (or not send it at all).

**Comment by marten-seemann** [comment]
> In the past, we have had the principle that either endpoint not condition its choice of transport parameter values based on anything from its peer. We should maintain this principle throughout.

@martinthomson Where did we use this principle in the past? I can't remember that we said anything like that.
Since we're using transport parameters to negotiate extensions (and extensions might use the value of the TP to negotiate *something*), I don't think this is a viable principle to follow.

**Comment by kazuho** [comment]
@marten-seemann IIRC the most recent occasion that we discussed this principle is when we changed the name of `idle-timeout` to `max-idle-timeout`.

The reason we changed the name was specifically due to this principle. Each endpoint declares its maximum, instead of conditioning its value on the others. That's why it's now called max-idle-timeout, and why we require each endpoint to calculate the minimum of the two.

**Comment by ianswett** [comment]
My understanding is that the principle was you shouldn't be required to condition TPs based on data from the peer, not that one is precluded from doing so.

**Comment by martinthomson** [comment]
I guess that "fixed" is the wrong term.  More to the point that the transport parameters don't necessarily depend on what a peer does.  That accounts for the stateless reset case, because that only "depends" on local choices.

**Comment by larseggert** [comment]
I think we need to see more (supportive) discussion in order to justify taking this on.

**Comment by MikeBishop** [comment]
I don't know that there's much here to "take on" beyond clarifying what our design principles are, and maybe writing those down somewhere for designers of future transport parameters.  The principle here is that TPs are independent declarations by each side, not negotiations.

I've noticed as we get further and further into this process, we have a number of principles which haven't been written down which have guided our design -- and we keep revisiting them because only the resulting design is explicit.  I'm wondering if those principles belong... somewhere.  An appendix, a published draft, etc. even if not enshrined in an RFC.

**Comment by nharper** [comment]
I agree with Mike. I noticed we already state this design principle in section 7.3: "These declarations are made unilaterally by each endpoint."

Taking on/resolving this issue brings transport parameters back in line with the stated property of them being declarations, not negotiated. I think this is a worthwhile change.
