### ISSUE TITLE
It is unclear if some frames are forbidden in 0-RTT

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3430]
In TLS draft, we state that _all other frame types MUST only be sent in the 0-RTT and 1-RTT levels_, then state that it is impossible to send some of those frames in 0-RTT (HANDSHAKE_DONE, NEW_TOKEN, PATH_RESPONSE, RETIRE_CONNECTION_ID).

As it seems that we think use of these frames in 0-RTT to be forbidden, I think we should be clear about that.

**Comment by martinthomson** [comment]
See also #3435.

**Comment by ekr** [comment]
It seemed to me that the principle MT was espousing was that we don't forbid any frames in 0-RTT and just note in the draft the frames where some other rule made it impossible to send a conformant frame in 0-RTT.

**Comment by MikeBishop** [comment]
It's not forbidden, it's impossible -- or more precisely, it's a protocol violation to send them for other reasons.  HANDSHAKE_DONE and NEW_TOKEN frames are sent only by servers, and servers don't send 0-RTT.  A client sending them at any time is forbidden.

PATH_RESPONSE is sent only in response to a PATH_CHALLENGE; PATH_CHALLENGE can only be sent in 0-RTT or 1-RTT, and servers don't send 0-RTT.  Therefore, the client can't be responding to a PATH_CHALLENGE while it's still sending 0-RTT.

RETIRE_CONNECTION_ID can't retire the CID of its own packet.  Until the transport parameters have been parsed, the client only has one CID for the server, so it's illegal to retire it.  Once the transport parameters have been parsed, in the "simple" handshake flow, the client shouldn't be sending 0-RTT.  If the handshake requires an extra round-trip, is it possible to keep sending 0-RTT after having processed the Server Hello?

**Comment by ekr** [comment]
@MikeBishop yes, I think that is what I was saying.

**Comment by marten-seemann** [comment]
> It's not forbidden, it's impossible -- or more precisely, it's a protocol violation to send them for other reasons.

Does that mean I can't send a FRAME_PARSING error? That would complicate things quite a bit, since I'd have to build extra tracking logic e.g. for a HANDSHAKE_DONE that is not sent in 1-RTT.

**Comment by martinthomson** [comment]
Why bother?  The client can't send HANDSHAKE_DONE, so you only need to check the role of the endpoint when receiving it.

**Comment by MikeBishop** [comment]
I think you need both pieces of logic anyway.  If a peer sends HANDSHAKE_DONE in a Handshake frame, that's an error regardless of role.  You need to check the packet type on receipt.  If a client sends HANDSHAKE_DONE, that's an error regardless of packet type.  You need to check the peer's role on receipt.

The assertion here is that we don't need to expand the packet type check to overlap with the role check.  Then we get into discussion about which of multiple overlapping errors you should use.  We've done that already.

**Comment by kazuho** [comment]
FWIW, I think #3440 is the way to go.

Though to avoid confustion, I think it might be helpful to clarify what th "Packets" column means in [table 3](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#frame-types) of the transport draft.

At the moment, the column is being explained as _the types of packets that each frame type can appear in_ (https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-12.4-8), but we could specifically say that it reflects the rules defined in [section 4 of the TLS draft](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#section-4) plus prohibitions stated elsewhere.
