### ISSUE TITLE
Initial RTT for resumption (recovery draft)

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#3464]
The recovery draft says:
"Resumed connections over the same
   network SHOULD use the previous connection's final smoothed RTT value
   as the resumed connection's initial RTT."
I wonder if we should change this to a MAY, as there is also a temporal aspect. Or maybe we should say more about this?

Also note that draft-ietf-tcpm-2140bis is probably related.

**Comment by martinthomson** [comment]
I would agree with switching to MAY. Even mentioning this leads to some incentive to implement, so the effect on implementation is similar. But we really don't need to recommend something like this.
