### ISSUE TITLE
Text on migration in recovery draft seems outdated

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#3465]
Draft says:
"   Until the server has validated the client's address on the path, the
   amount of data it can send is limited to three times the amount of
   data received, as specified in Section 8.1 of [QUIC-TRANSPORT].  If
   no data can be sent, then the PTO alarm MUST NOT be armed until
   datagrams have been received from the client.

   Since the server could be blocked until more packets are received
   from the client, it is the client's responsibility to send packets to
   unblock the server until it is certain that the server has finished
   its address validation (see Section 8 of [QUIC-TRANSPORT]).  That is,
   the client MUST set the probe timer if the client has not received an
   acknowledgement for one of its Handshake or 1-RTT packets."

I guess most of this can just be removed and replaced with a pointer to section 9 of the transport draft?

**Comment by larseggert** [comment]
The text you quote is about path validation during connection establishment, not about path validation during connection migration. Not sure that pointing to Section 9 of -transport is appropriate?

**Comment by mirjak** [comment]
Ah, sorry was mapping this wrongly... I guess we could still remove some of the text and only point to 8.1. Anyway the text is correct/inline with the transport draft and I close the issue!
