### ISSUE TITLE
RTO in handshake in recovery draft

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#3467]
The draft says:
"To allow the client to
   improve its RTT estimate, the new packet that it sends MUST be ack-
   eliciting.  If Handshake keys are available to the client, it MUST
   send a Handshake packet, and otherwise it MUST send an Initial packet
   in a UDP datagram of at least 1200 bytes."
Is the second sentence actually needed (in this draft). What are the other options?

**Comment by mirjak** [comment]
I also just noticed that there is this sentence in the "sending probe packets" section:
"   Alternatively, instead of sending an ack-eliciting packet, the sender
   MAY mark any packets still in flight as lost."

and this sentence in the next "detection loss" section:
"   A PTO timer expiration event does not indicate packet loss and MUST
   NOT cause prior unacknowledged packets to be marked as lost."

So maybe that first sentence should have be removed as well? Not sure what is intended here...?

**Comment by ianswett** [comment]
We could drop "send an Initial packet in a UDP datagram of at least 1200 bytes." because all client Initial packets are padded to make it less duplicative with transport.  Besides that, I'm not aware of any other options.

**Comment by larseggert** [comment]
@mirjak this looks like it can be closed with no action?

**Comment by mirjak** [comment]
I think the use of normative language is somehow redundant. But that not really an issue. Closing...
