### ISSUE TITLE
Clarify meaning/definition of GOAWAY

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#347]
GOAWAY has a "Last Good Stream ID", which is "The last Stream ID which was accepted by the sender of the GOAWAY message. If no streams were replied to, this value must be set to 0."

The sender does not specify the last stream id it will use, which I think it should.

I also think the text in "6.6 Connection Termination" should specify that all streams <= the Last Good Stream ID will be completed(fin'd or reset), including delivering any outstanding data.

**Comment by MikeBishop** [comment]
This is probably a vestige from HTTP/2, where the last stream created by the server prior to sending a GOAWAY was deterministic.  You're right, this needs to be explicit in QUIC.

**Comment by martinthomson** [comment]
The proposal would be to identify the stream number in the both send AND receive directions.  Higher number streams are implicitly and pre-emptively reset.  Sounds easy enough to do.
