### ISSUE TITLE
Encrypting token in Retry packet

### ISSUE THREAD

**Issue by nqv** [quicwg/base-drafts#3477]
I have read through https://github.com/quicwg/base-drafts/pull/3120 and related issues (https://github.com/quicwg/base-drafts/issues/3274 https://github.com/quicwg/base-drafts/issues/3014)
and wonder if we can have it similar to Initial Packet encryption instead. I understand we already have consensus but wonder if we can make the protocol simpler.

In initial packet, the initial AEAD is calculated from Destination CID. So I propose we remove pseudo-packet concept and build AEAD from Original Destination CID to encrypt the retry token just like Initial packet encrypting its token, packet number and payload.

I see the benefits are:
- Consistent packet encryption mechanism, more code resuse (please)
- No additional buffer to build pseudo-packet
- Easier to have custom protocol (or next version) to use chosen AEAD, i.e. CHACHA20_POLY1305
- Can apply to other packets in future (e.g Version Negotiation)

**Comment by martinthomson** [comment]
This idea was discussed and dismissed.  The problem here is that the HKDF application required to get the keys is significantly more expensive than applying the AEAD.  The cost of producing a Retry was considered important enough not to take this cost.

The pseudo-packet is relatively inexpensive in practice.  Allocating an extra 21 bytes and pre-filling the connection ID in that space doesn't end up costing that much.

**Comment by nqv** [comment]
If HKDF-Expand-Label is expensive, can we use ODCID such as first 128 bit as the secret key and the remain as the nonce? Or can we generalize it and say SHA256 of user data (ODCID in this case) will be AEAD key and nonce?

WRT pseudo packet. I think on client side, I still need to allocate memory for a copy of received retry packet plus odcid to verify the integrity tag.

**Comment by martinthomson** [comment]
Those options were also suggested.  I think that the extra AES operation (or operations) was regarded as "too expensive".

If you pull incoming packets into a buffer starting at position 21, you can pre-fill the extra stuff.  It's not great, but it can work.

**Comment by ianswett** [comment]
This has been discussed at considerable length as @martinthomson nicely summarized, so I don't see a reason to change the previous consensus now.
