### ISSUE TITLE
Starting packet number

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#35]
We might be able to randomize the starting packet number and thereby avoid having it as a point of ossification.  It also increases the entropy for an off-path attacker who wishes to guess connection IDs because now they have to guess packet number as well.

**Comment by ianswett** [comment]
This is possible today, but it should be required or highly recommended.

**Comment by ianswett** [comment]
When fixing this, also fix the following inconsistency(noted by Mirja):
Section 4.2 (Regular Packets) page 10 says: "The first packet send by an endpoint MUST have a packet number of 1."
And section 7 (Packetization and Reliability) page 28 says: "That is, the first packet in both directions of the connection MUST have a packet number of 0."

**Comment by JimRoskind** [comment]
Reading the motivation (re: off-path guessing of connection ID), I'm hopeful that a client would use a good Random Number Generator (RNG) and not produce a "guessable" connection ID. The presumption of a "good RNG" is indeed central to having many clients connecting to a single server (without collision).  If one would posit a poor RNG... then in addition to collisio problems, I'd be wary that a RNG used to select a "unguessable" initial packet number would be problematic.  Bottom line: I don't grok the security based motivation.

The other motivation is to prevent "ossification."  Can someone provide a plausible motivation for a "need" to start at a different packet number, and avoid "ossification" in this context?  I would have expected that standardization in this area simplifies code, and would not be a long-term problem.

**Comment by mnot** [comment]
Discussed in Tokyo; agreement that it's a good idea. Randomise some number of the bottom bits.

**Comment by martinthomson** [comment]
Currently, we aren't sure how many bits are going to be in initial packets.  When @ekr produces a proposal for the packet headers, I think that this should include a fixed-size slot for the packet number.  That will make this easier to write up.

**Comment by martinthomson** [comment]
This was addressed in #283.
