### ISSUE TITLE
Formally verify the protocol

### ISSUE THREAD

**Issue by DemiMarie-parity** [quicwg/base-drafts#3507]
TLS1.3 was formally verified, and QUIC should be too.  This refers to the protocol itself, not implementations.

**Comment by larseggert** [comment]
Sure. But that verification was not done in the TLS WG, and similarly if this happens for QUIC, it won't be done by the QUIC WG.

**Comment by larseggert** [comment]
Also see https://eprint.iacr.org/2020/114.pdf
