### ISSUE TITLE
Does GOAWAY need an error code

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#352]
In writing up a change for GOAWAY, I realize that it doesn't need to signal the error condition that triggered it.  An endpoint that wants to kill a connection can use CONNECTION_CLOSE and the error code that carries.  The purpose of GOAWAY is to signal graceful shutdown and to mark multiple streams as being safe to retry.

If it doesn't need an error code, then the reason phrase can go away as well.

(This might depend on the outcome of discussions that suggest that CONNECTION_CLOSE could be replaced by Public Reset.  Or, it might influence the outcome of that discussion...)

**Comment by ianswett** [comment]
I favor removing error code and the reason phrase from GOAWAY, but adding a sender side stream ID as mentioned in #347 

Removing the reason phrase is in #187 as well.
