### ISSUE TITLE
Inconsistency between early timeout calculations

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3524]
For each connection, the loss detection timeout is defined as 2 * InitialRTT.

I wonder if this should be 3 * InitialRTT instead, because, once you have one RTT sample, PTO is calculated as 3 * InitialRTT.

I do not think we have a reason to believe that the variance of RTT (which applies as a multiplier here) increases when we obtain the first sample?

PS. The other benefit of making these two consistent is that we can get rid of `if (smoothed_rtt == 0)` in SetLossDetectionTimer. It would be possible to always rely on PTO calculation.

**Comment by ianswett** [comment]
I wasn't sure if this would be design or not, but now that the PR is complete, I believe it's editorial, as @kazuho PR changes the pseudocode, but proscribes exactly the same behavior as the existing text.

**Comment by kazuho** [comment]
To be precise, there is one thing that does change, and that is the initial timeout when a connection is resumed on the same path.

At the moment, the only variable we recommend to remember is SRTT, and when resuming a connection on the same path, use 2 * SRTT as the initial timeout.

The proposed change increases that to 3 * SRTT. I think this is better than status-quo, assuming that we agree that RTTVAR should be 2 * sample when there is only one known sample.

**Comment by ianswett** [comment]
Thanks for pointing that out, I noticed that the first time around and then forgot.  I'll let @larseggert make the call about whether he thinks this is design then.
