### ISSUE TITLE
Defense against version number corruption

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#3532]
The "packet corruption" test that @marten-seemann added to the interop-runner has surfaced an issue about version number corruption. Suppose that a long header packet is corrupted in transit, and that the corruption changes the value of the version number. Per spec, the server will respond with a version number negotiation packet. In the test, we observe that when clients receive such packets, they abandon the connection attempt.

Obviously, this is a rare event. We don't know how frequent packet corruption is today. The [1997 paper by Vern Paxson ](https://cseweb.ucsd.edu/classes/wi01/cse222/papers/paxson-e2e-packets-sigcomm97.pdf) measured "1 packet in 5000". In theory, only one in 2^16 of these corruptions would not be detected by the UDP checksum, leading to undetected corruption in 1 in 300 million packets.

That's a very small number, but I don't know whether the 1997 measurements are still valid. They could be higher. I also don't know whether the loss patterns would be detected by the UDP checksum, since some middleboxes appear to rewrite these checksums. Faced with exactly the same issue, we decided recently to add a checksum to the Retry packets.

Clients can protect against such corruptions by checking the incoming VN packets for sanity. If the server issues a VN in response to a corrupted packet, the list of supported versions will include the version proposed by the client. That should normally never happen. Ignoring such bogus VN does protect against most version number correction issues. Should we point that out in the spec?

**Comment by martinthomson** [comment]
We used to require that a client ignore Version Negotiation packets that include the version the client attempted.

@DavidSchinazi edited that out.  Maybe we should restore it.  That pushes the odds of failure to 1 in 90 quadrillion.  Would that help?

I want to say that this is a design issue.

**Comment by huitema** [comment]
The problem with the "one in 300 million" figure is that it relies on the UDP checksum. If you cannot trust the UDP checksum, the figure is "1 in 5000", which is more concerning. And there are scenarios in which uncontrolled middle-boxes do rewrite that checksum.

**Comment by ianswett** [comment]
I'd support restoring that check that @DavidSchinazi edited out.

Anecdotally, we've found packet corruption to be very rare and basically a non-issue.  Or maybe something in the network or the host is just dropping them, but we don't receive them in userspace.

**Comment by janaiyengar** [comment]
I'm fine with adding this check back in. It's not onerous to implementers. This is a design issue.

**Comment by huitema** [comment]
Now if we were really paranoid, we would consider the possibility that the VN packet itself is corrupted.

**Comment by martinthomson** [comment]
> [..] we would consider the possibility that the VN packet itself is corrupted.

I did.  If we don't trust the UDP checksum on either, the error rates are still pretty high, but either checksum bumps it up to 1.5 trillion and both is 90 quadrillion.

**Comment by janaiyengar** [comment]
I was thinking about that -- it doesn't need paranoia, it's just a question of how often -- and in this case the chances are vanishingly small.

**Comment by DavidSchinazi** [comment]
To clarify the `@DavidSchinazi edited that out` statement, that happened when we decided to move version negotiation to an extension. The [current text](https://tools.ietf.org/html/draft-ietf-quic-transport-27#section-6.2) states that `When a client receives a Version Negotiation packet, it MUST abandon the current connection attempt.` - I'd be supportive of adding a sentence such as `Clients MUST ignore received Version Negotiation packets that contain the version they attempted to use.`

**Comment by martinduke** [comment]
I support the change.

Does the general concern about security proofs that is driving us to authenticate the CIDs also apply to the version field?

**Comment by DavidSchinazi** [comment]
@martinduke The security concerns do apply to the version field, our current plan to address that is [draft-ietf-quic-version-negotiation](https://tools.ietf.org/html/draft-ietf-quic-version-negotiation).

**Comment by martinduke** [comment]
@DavidSchinazi Thanks, but is it sufficient for this to be an extension? What if the base spec isn't provably secure?

**Comment by DavidSchinazi** [comment]
@martinduke there's still time for us to make the use of that extension mandatory before we ship, but I'd suggest having that discussion on a separate issue.
