### ISSUE TITLE
Align the "Maximum Data" and "Data Limit" terms

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3579]
Orthogonal to this PR, but perhaps we should align the "Maximum Data" and "Data Limit" terms which reference the same limit in different frames?

_Originally posted by @MikeBishop in https://github.com/quicwg/base-drafts/diffs/3_

**Comment by ianswett** [comment]
SGTM.  Maximum Data(or Max Data) seems like the preferable option to me.

**Comment by marten-seemann** [comment]
@martinthomson The link to @MikeBishop's post seems to be broken.

**Comment by martinthomson** [comment]
Odd, that was automatically generated by GitHub.  That comment was on a review of #3573.
