### ISSUE TITLE
Semicolons on references in !-transport

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3592]
More of the same; see #3591.

**Comment by martinthomson** [comment]
This might even touch -transport as it turns out that Eric didn't catch 'em all.

**Comment by erickinnear** [comment]
😃 
I did a search through with a focus on `( see X`, but intentionally kept some of the other formulations mid-sentence, etc.
Also certainly may have missed a bunch! 
Github is lacking some emojis I need here... 🙃
