### ISSUE TITLE
No more private TPs since -26?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#3598]
transport-26 dropped this sentence, which was present up to -25:
>   Values with the first byte 0xff are reserved for Private Use [RFC8126].

Don't we have private TPs anymore? Or is this due to an editing bug?

**Comment by LPardue** [comment]
It was modified in the fix that addressed [TPs are too constraining for innovation](https://github.com/quicwg/base-drafts/issues/3020)

**Comment by MikeBishop** [comment]
> Provisional registration of codepoints are intended to allow for **private use and experimentation** with extensions to QUIC. Provisional registrations only require the inclusion of the codepoint value and contact information. However, provisional registrations could be reclaimed and reassigned for another purpose.

**Comment by larseggert** [comment]
Right, but how to grease? Don't want to provisionally register for that?

**Comment by MikeBishop** [comment]
Greasing is still defined as it was.

Section 18.1:
> Transport parameters with an identifier of the form 31 * N + 27 for integer values of N are reserved to exercise the requirement that unknown transport parameters be ignored. These transport parameters have no semantics, and may carry arbitrary values.

Section 22.2:
> Additionally, each value of the format 31 * N + 27 for integer values of N (that is, 27, 58, 89, ...) are reserved and MUST NOT be assigned by IANA.

**Comment by larseggert** [comment]
Oh, I *totally* missed that change!
