### ISSUE TITLE
Formatting of persistent congestion text

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3605]
![image](https://user-images.githubusercontent.com/67641/80560752-89e30100-8a25-11ea-961b-3c15dd31b884.png)

Should the list of assumed values be an inline figure, a list, or just text?

**Comment by ianswett** [comment]
This looks fine when I'm viewing the markdown, and it's using ~~~ like the pseduocode is, so I'd expect it to render like the pseudocode does.

**Comment by MikeBishop** [comment]
It does render that way in the HTML version, it appears, with both Firefox and Chromium:
![image](https://user-images.githubusercontent.com/4273797/82253603-4b9f7a00-991f-11ea-96b1-3e6b3f72536f.png)

@martinthomson, what URL are you looking at, and in which browser?

**Comment by LPardue** [comment]
Seems to work in the editor's txt - https://quicwg.org/base-drafts/draft-ietf-quic-recovery.txt

Draft 27 though seems to be broken in all forms for me (Firefox76, https://tools.ietf.org/html/draft-ietf-quic-recovery-27#section-6.7)

**Comment by martinthomson** [comment]
Oh, this is because I already fixed it.  As Lucas points out, it was a mess.
