### ISSUE TITLE
Backticks around parameter names

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3609]
We're somewhat inconsistent about whether transport parameters et al. get backticks or not across the documents.  For example,

>   the ACK Delay field is scaled by multiplying the encoded value by 2 to the
>  power of the value of the `ack_delay_exponent` transport parameter set by the
>  sender of the ACK frame; see {{transport-parameter-definitions}}.  Scaling in

> The Retire Prior To field counts connection IDs established during connection
> setup and the preferred_address transport parameter; see {{retiring-cids}}. The
> Retire Prior To field MUST be less than or equal to the Sequence Number field.

Same goes for error code names, frame types, etc.

**Comment by martinthomson** [comment]
I think that - at this point - the overwhelming majority of parameter names are not quoted in any way and do go in and fix all of them would be tiresome.  However, most are in snake_case, CamelCase, Title Case, or SHOUTING_CASE so they are almost always distinguishable.

I grepped through and we have 38 instances of backticks.  Most of these are in -http and -qpack.  Most of them are in the description of reserved codepoints.  I'm going to suggest we scrub the others out.
