### ISSUE TITLE
Review conditions for PTO arming around end of handshake

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#3613]
(deleted comment, because the initially mentioned problem was incorrect. the requirement to arm the PTO timer after the handshake finishes is in Section 5.2.2)

**Comment by martinduke** [comment]
I see now that Section 5.2.2 explicitly describes this, so there's no problem here, though I might complain a bit about handshake complete vs. handshake confirmed.

Sorry, feel free to close this issue if you don't think the confirmed thing is worth changing.

**Comment by martinduke** [comment]
I changed the title, since it's wrong.

There might be some useful editorial cleanup here, but the substantive change would be to reset PTO when the handshake is complete, rather than confirmed. The edge case is that the client lost its 0RTT flight and HANDSHAKE_DONE is held up by losses or something. The delay in sending the client's HTTP request could turn out to be quite long.

**Comment by martinduke** [comment]
There's some architectural inconsistency around the treatment of 1RTT PTOs at the end of the handshake.

On the one hand, we are not supposed to set the PTO timer for 1RTT before the handshake is **complete**. This is to prevent us from retransmitting stuff the peer may not be able to process.

On the other hand, we are supposed to arm the PTO timer when the handshake is **confirmed**. This is the point where we're guaranteed that the peer has receive keys.

So there is a weird gap between handshake complete and handshake confirmed where new 1RTT packets will arm the PTO, but outstanding 0RTT or 1RTT packets from before handshake complete will not have an active PTO timer.

This isn't the end of the world -- the connection will recover -- but it doesn't make any sense, and could result in either excessive PTO delays, or 1RTT probes that the peer can't decode.

**Comment by martinthomson** [comment]
@ianswett can we get a status update?

**Comment by ianswett** [comment]
The PTO is always armed when there are bytes in flight(except when the loss timer is armed), it's just a matter of what PN spaces it can be armed for at a given point in time.  Once the connection is handshake complete, it's immediately allowed to arm it for inflight 1-RTT ack-eliciting packets.

Re-reading the text, I couldn't find anything explicitly calling out that the alarm may need to be recomputed and reset in the handshake confirmed case, though it is stated for discarding keys.

As clarified in #3597 when the client is handshake complete but not confirmed, it is unsure whether the server has Handshake keys or ApplicationData keys, but it's very unlikely to have both.  As such, sending something ack-eliciting from both PN spaces is safest.
