### ISSUE TITLE
Error code for increasing stream_id in GOAWAY frames

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#3616]
The spec defines this as MUST NOT:

> An endpoint MAY send multiple GOAWAY frames indicating different identifiers, but MUST NOT increase the identifier value they send, since clients might already have retried unprocessed requests on another connection.

we should define an error code for this?
I do not see that it is define, maybe I missed it somewhere.

**Comment by martinthomson** [comment]
We can define our own internal error code for this and report that as a generic error.

**Comment by ddragana** [comment]
> We can define our own internal error code for this and report that as a generic error.

I am fine with that. Adding a description to the "Reason Phrase" in CONNECTION_CLOSE frame is enough.

**Comment by LPardue** [comment]
Seems like you have a solution that does not require any spec changes so I'm closing this. Reopen the ticket if my assessment is wrong.
