### ISSUE TITLE
Does a dynamic table entry insertion needs to be acknowledged for the enttry to become evictable?

### ISSUE THREAD

**Issue by ddragana** [quicwg/base-drafts#3624]
> Once the insertion of a
   dynamic table entry has been acknowledged and there are no
   outstanding unacknowledged references to the entry, the entry becomes
   evictable.

Does a entry really needs to acknowledged to become evictable? Inserts are happening on the same stream so it is not possible a entry is reference after being evicted.

**Comment by dtikhonov** [comment]
Yes, this is necessary.  This is done to prevent unlimited speculative insertions, otherwise wrapped [Required Insert Count](https://tools.ietf.org/html/draft-ietf-quic-qpack-14#section-4.5.1.1) does not work.  See proposal in issue #1644.

**Comment by ddragana** [comment]
thanks
