### ISSUE TITLE
What error kind is caused by multiple GOAWAYS that increase the limit

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#3631]
Draft 27 says:

```
   A server MAY send multiple GOAWAY frames indicating different stream IDs, but MUST NOT
   increase the value they send in the last Stream ID, since clients
   might already have retried unprocessed requests on another
   connection.
```

Maybe I'm missing it but I can't see where we say how the GoAway receiver handles an seeing the GoAway ID getting increased. 

We typically state what the receiver should do in such a case. For instance, with MAX_PUSH_ID we say " receipt of a MAX_PUSH_ID that contains a smaller value than previously received MUST be treated as a connection error of type H3_ID_ERROR.".

I suggest that we need text that states receiving a larger GOAWAY ID than previously received MUST be treated as a connection error of type H3_ID_ERROR.

N.B. since draft-27 we landed changes to make the GOAWAY symmetrical. I believe this issue is still applicable to the most recent editors draft

**Comment by ianswett** [comment]
H3_ID_ERROR SGTM
