### ISSUE TITLE
Minor editorical issue in QPACK draft

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#3633]
In Figure 1, the right hand means the future. But in Figure 2, 3 and 4, the right hand indicates the past. Is this intentional? If not, why don't we redraw Figure 1 or Figure 2/3/4 for consistency?

**Comment by afrind** [comment]
I think some of the diagrams (2-4) were imported from HPACK and modified, but figure 1 is original to QPACK.  I agree we should make it consistent.

**Comment by kazu-yamamoto** [comment]
@afrind Thank you!
