### ISSUE TITLE
Tell people which document to cite when citing QUIC

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#3687]
The chairs just had a question from someone who wanted to cite "QUIC" on what document they should be citing. We responded that they should cite -transport, since we see this as the central document.

Should we add brief notes to the documents saying "if you want to cite QUIC, cite -transport"?

**Comment by janaiyengar** [comment]
That seems reasonable, since we say in there that accompanying documents describe TLS and recovery. Where are you thinking of adding that note?

**Comment by larseggert** [comment]
As early as possible?

**Comment by MikeBishop** [comment]
If you want to cite QUIC version 1, transport.  If you want to cite QUIC all-up, invariants.

**Comment by martinthomson** [comment]
[This paragraph](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-1.1-4), or immediately after it, seems like as good a place as any.
