### ISSUE TITLE
Deduplication window suggested by RFC 4303 is insufficient

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3692]
[Section 12.3 of the transport draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-12.3-11) requires deduplication, delegating the details to RFC 4303. I am not sure if that is enough.

IIUC, the difference between RFC 4303 and QUIC is that in case of QUIC, packets are sent using multiple paths.

Consider the case of a client connected through Wi-fi, probing a 3G network. The latency of Wi-fi could be much shorter than that of 3G, and the bandwidth could be high. In such case, the requirement on the deduplication window becomes high: the window needs to cover packet numbers across multiple PTOs (where PTO is calculated from the RTT of the Wi-fi). A server can respond reliably to a path probing packet on the 3G network, only if the server's deduplication window is fairly larger than the *bandwidth of the Wi-fi* multiplied by *the latency of the 3G network*.

I do not think that this case is covered by RFC 4303.

IMO, we need to at least clarify this corner case exists, otherwise, we might end up seeing servers not responding to probes sent on cellular networks, and clients failing to migrate due to that failure.

**Comment by kazuho** [comment]
As a fix, I think we should remove reference to RFC 4303, and state that an endpoint SHOULD be capable of deduplicating packets that are received across more than half the largest RTT that the endpoint intends to support.

**Comment by martinthomson** [comment]
I agree that RFC 4303 is showing its age here.  32 packets is probably woefully inadequate here.  But there is an additional insight that is important: you need to drop all packets older than the oldest packet you are individually tracking or you are vulnerable to duplication attack.  It's a little awkward restating that.

It's not obvious that you need to allow for an increase of half of the difference between the current min_rtt and some maximum value either, so it is worth saying that.  Noting that the collective packet rate on all paths affects any limit is similarly non-intuitive.

The nice thing about this is that the most obvious packet-tracking structures (aside perhaps from those that are subject to DoS) are not susceptible to this problem.  For instance, many people are tracking ranges and limiting the total number of ranges.  If you do that, you only run into problems after the number of slow probes sent within one of these extra-long round trip times exceeds the number of ranges the receiver is tracking.  Most implementations are tracking more ranges than there are packets in an initial congestion window, so you won't get issues.

**Comment by kazuho** [comment]
> I agree that RFC 4303 is showing its age here. 32 packets is probably woefully inadequate here. But there is an additional insight that is important: you need to drop all packets older than the oldest packet you are individually tracking or you are vulnerable to duplication attack. It's a little awkward restating that.

Regarding the insight, I agree that we need to state that. We can site RFC 4303 as part of that attempt, even though we need to refrain from suggesting that the design document in RFC 4303 works for QUIC.

As you state, the practical advice we'd better provide is that an endpoint can retain ranges of packets. The number of ranges that an endpoint should retain is questionable, but hopefully, endpoints would make a sensible choice.
