### ISSUE TITLE
Integrate QUIC DPLPMTUD text

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3695]
It turns out that coordinating the publication of all the documents is a real challenge.  Right now, DPLPMTUD depends on QUIC, which is fine, but it turns out that this is a problem for other things that depend on DPLPMTUD who now transitively depend on QUIC.  QUIC could adopt the DPLPMTUD text that is specific to QUIC and loosen this dependency chain.

The text changes are relatively modest, see #3693.

While this could be editorial, I think that this will require a consensus call.  The nature of the changes is such that it should be treated as design.  Also, I think that there are substantive changes required.

**Comment by gloinul** [comment]
So from an AD perspective, draft-ietf-tsvwg-datagram-plpmtud is currently blocking another document (https://datatracker.ietf.org/doc/draft-ietf-intarea-frag-fragile/) from being published that has a missref on it. Except for this question of QUIC I am ready to approve draft-ietf-tsvwg-datagram-plpmtud. 

To me it is also clear that integration of DPLPMTUD done in the QUIC WG will result in less editorial clarity issues that potentially could make an future implementer uncertain. As can already been seen in the PR there a few question that potentially can improve the operation and not unnecessary restrict the operation of DPLPMTUD. 

From my perspective it looks like the core is a set of minor editorial issues to resolve that will make the DPLPMTUD be clearer and resolve the missref issue and function as well as keeping it in the TSVWG document would. If a little bit more effort is invested after the first step then there is potential for additional improvements.
