### ISSUE TITLE
use TRANSPORT_PARAMETER_ERROR when authenticating connection IDs

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#3703]
The guiding principle here (as we apply it for FRAME_ENCODING_ERRORs) is that if an error is detectable without accessing connection state, we use the more specific error. So for example, since `initial_source_connection_id` and `original_destination_connection_id` are required transport parameters, their absence should be responded to with a TRANSPORT_PARAMETER_ERROR. A similar argument applies to the absence of the `retry_source_connection_id` TP, although I can see how one might use PROTOCOL_VIOLATION here (note that this is still valid behavior with this PR, as every more specific error can be replaced with a PROTOCOL_VIOLATION, if an implementation wishes to do so).

**Comment by martinthomson** [comment]
Thanks.  I think that this is fine.  I will make a few editorial comments on the PR, but I think that the application of the agreed principles is correct.
