### ISSUE TITLE
ALTSVC Frame

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#371]
As @LPardue has pointed out in the thread for #242, the HTTP/QUIC spec claims to update the IANA registry for "existing" frames.  It really only updates the frames defined in RFC7540; the ALTSVC frame defined in RFC7838 isn't updated.

It would be a simple update, but the question is where it belongs.  Should we:

- Add text in this document to include that frame, because it is "existing"?
- Write a new (very short) document updating RFC7838 with HTTP/QUIC support, following the recommendations in #363?
- Kick it back to the httpbis working group to write exactly the same very short document?

Note that the latter two options probably differ by nothing but the filename of the I-D in question -- the same people will probably end up writing it.

**Comment by LPardue** [comment]
I think that option 3 (kickback to httpbis) sets a good precedent for future extensions that want to use HTTP/QUIC. This potentially makes it clearer that drafts in httpbis-land shouldn't expect a free ride from the QUIC WG.

**Comment by MikeBishop** [comment]
Potentially fixed by draft-bishop-httpbis-altsvc-quic.

**Comment by LPardue** [comment]
ALTSVC frame support came up in a recent conversation and it took me a bit of time to remember that this issue (and the @MikeBishop draft) existed. 

Would it make sense to adopt the document as part of the QUIC WG activity? Or perhaps incorporate the text into draft-ietf-quic-http.

I fear there may be some intellectual interop problems when talking about ALTSVC. For example with draft-ietf-quic-http we describe how ALTSVC can be used to discover HTTP/QUIC but only really for H2 connections prior to HTTP/QUIC, you can't use ALTSVC frames inside a HTTP/QUIC connection unless you're aware that the QUIC extension frame exists.

**Comment by MikeBishop** [comment]
I'm inclined to say this is still the job of httpbis.  However, I understand that one of our beloved chairs (@mnot) sees one of the httpbis chairs pretty frequently, and might be able to convince him to move this along if we need it.

**Comment by martinthomson** [comment]
Parking.  This is the responsibility of the HTTP WG, but we do want to make sure that it is handled soon after QUIC ships, if not at the same time.

**Comment by MikeBishop** [comment]
These drafts will be handed over to the HTTPbis for consideration; they own HTTP/3 maintenance and extensions.
