### ISSUE TITLE
HTTP: provide guidance on PING usage

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#3723]
The transport Draft states:

> An application protocol SHOULD provide guidance about the conditions under which generating a PING is recommended.

This guidance was added to the HTTP Draft in #744, but was subsequently removed.

**Comment by mirjak** [comment]
I guess that something to discuss in the applicability draft as well

**Comment by MikeBishop** [comment]
Looks like #2324 made this text more generic, leaving the specifics of how to keep a connection alive (e.g. with PING frames) to the transport implementation.  The text in question is now in Section 5.1:

> HTTP clients are expected to request that the transport keep connections open while there are responses outstanding for requests or server pushes, as described in Section 19.2 of [QUIC-TRANSPORT]. If the client is not expecting a response from the server, allowing an idle connection to time out is preferred over expending effort maintaining a connection that might not be needed. A gateway MAY maintain connections in anticipation of need rather than incur the latency cost of connection establishment to servers. Servers SHOULD NOT actively keep connections open.

It's possible the transport draft needs a similar generalization, to recommend implementations expose a way for the application layer to control whether an connection is idle.

**Comment by mirjak** [comment]
Actually there is a section on "Session resumption versus Keep-alive" in the applicability draft already. Do we need to say more? Is that needed in the transport draft as well?
