### ISSUE TITLE
Question on ECN validation

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#3733]
So, I am finally implementing this, and have questions. Section 13.4.2.2 says:
```
   *  For validation to succeed, the total increase in ECT(0), ECT(1),
      and CE counts MUST be no smaller than the total number of QUIC
      packets sent with an ECT codepoint that are newly acknowledged in
      this ACK frame.  This step detects any network remarking from
      ECT(0), ECT(1), or CE codepoints to Not-ECT.
```
What is meant by "total increase" here? I guess it is a delta, but against what? Against the values in the last received ACK frame? Against the "local reference counts" (which aren't really described well either, see below)? Or something else?

Also, I guess the "total increase" compared here is a **sum** of these individual deltas?

```
   *  Any increase in either ECT(0) or ECT(1) counts, plus any increase
      in the CE count, MUST be no smaller than the number of packets
      sent with the corresponding ECT codepoint that are newly
      acknowledged in this ACK frame.  This step detects any erroneous
      network remarking from ECT(0) to ECT(1) (or vice versa).
```
Again, "increase" relative to what?
```
   An endpoint could miss acknowledgements for a packet when ACK frames
   are lost.  It is therefore possible for the total increase in ECT(0),
   ECT(1), and CE counts to be greater than the number of packets
   acknowledged in an ACK frame.  When this happens, and if validation
   succeeds, the local reference counts MUST be increased to match the
   counts in the ACK frame.
```
Same question about "total increase". And what are the "local reference counts", and how are they maintained?

**Comment by mirjak** [comment]
You are supposed to keep three counters for the number of each ECT(0) and ECT(1) and CE mark reported so far on this connection (for this ack space). Increase means the difference of the count reported in the latest ACK compared to the current local counter value. Total increase is increase of ECT(0)+increase of ECT(1)+increase if CE compared to local current count of ECT(0)+ECT(1)+CE. Does that help?

**Comment by larseggert** [comment]
It does, thanks. it would probably be useful to introduce those local reference counts before the bullet list, describe how that are maintained, and then use them when describing how to validate.

**Comment by mirjak** [comment]
Yes. Will try to propose a PR. Thanks for implementing!

**Comment by larseggert** [comment]
Actually, this doesn't make sense to me:
> Total increase is increase of ECT(0)+increase of ECT(1)+increase if CE compared to local current count of ECT(0)+ECT(1)+CE. 
The increase is the value in the current ACK frame minus the current local reference value. A sum of those increases is always going to be less than the sum of the total reference values?

**Comment by mirjak** [comment]
Yes, sorry, in the text you don't compare the total increase to the local value of course. You compare the total increase to the number of packets  acknowledged in an ACK frame

**Comment by mirjak** [comment]
and then you also compare the increase of ECT(0)+increase in CE to number of packet send with ECT(0) from the newly acknowledge packets, and same for ETC(1). So you need to remember with packet was sent with which ECN codepoint if not all packets are send with the same codepoint.

**Comment by larseggert** [comment]
So let me tell you what my code is doing now to verify incoming ACK-ECNs, and then you tell me if this is correct:

I maintain ECN reference counter vectors (`ecn-ref`) per pn space. These hold the last counts received in an ACK-ECN from the peer.

I could new ACKs for ECN-marked packets that I send in a `new_ack`vector. (I only send ECN_ECT0 packets though, so this isn't really a vector, just a variable.)

When I receive a new ACK-ECN with ECN counts (`ecn_cnt`), I compute the `ecn_inc` vector as `ecn_ref - ecn_cnt`.

I then do the verification per Section 13.4.2.2:

* (First bullet in 13.4.2.2 is easy, omitted here)

* Second bullet in 13.4.2.2: `ecn_inc[ECN_ECT0] + ecn_inc[ECN_ECT1] + ecn_inc[ECN_CE] <  new_ack[ECN_ECT0]` => verification failed

* Third bullet in 13.4.2.2: `ecn_inc[ECN_ECT0] + ecn_cnt[ECN_CE] < new_ack[ECN_ECT0]` => verification failed. (Since I only send ECN_ECT0, I can omit looking at ECN_ACT1, I believe.)

**Comment by larseggert** [comment]
@mirjak ping?

**Comment by mirjak** [comment]
Sorry, long weekend in Germany. Yep this sounds right. If you only have ECT(0), you can simplify test 2 to just do what you do in 3 ('ecn_inc[ECN_ECT0] + ecn_cnt[ECN_CE] < new_ack[ECN_ECT0]') and for test 3 you just need to check if there are any ECT(1) marking at all and fail if you ever get feedback that ECT(1) was observed.

**Comment by martinthomson** [comment]
Maybe use <= rather than < though.

**Comment by larseggert** [comment]
@martinthomson I'm not sure that's correct?

**Comment by mirjak** [comment]
Oh yes, didn't see that. I also think it should be <= . @larseggert why do think it should be < ?

**Comment by larseggert** [comment]
Because if the number of marked packets in the ACK is == the number of marked packets I sent, that is not a verification failure? (Or am I misunderstanding something?)

**Comment by mirjak** [comment]
Right... I got confused that the condition is about moving into failure mode. 

So usually the numbers should always be exactly equal; only if some marked packets get not ack'ed at all the received count could be larger than the number of marked sent and ack'ed packet. I guess, if you know that this is not the case you could be even stricter.

Otherwise if there are no unack'ed packets and the received count would be larger, it would mean you have some remarking from Not-ECT to ECT or CE. That less a problem in terms of hiding congestion but might still indicate that something is wrong... however, given that you mark all packet in your implementation with ECT(0) that case should not happen.

**Comment by gloinul** [comment]
And as noted the primary failure mode where increase of reference counter can be larger than newely ACKed packets is lost ACKs. Section 13.4.1 is clear on that duplicate packets shall be surpressed prior to increasing the relevant ECN counter.
