### ISSUE TITLE
bundling and coalescing?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#3736]
What does “bundling” refer to? I think I might now understand coalescing, but I don’t understand if bundling is subtly different?

**Comment by MikeBishop** [comment]
Several instances I see in the draft refer to the situation where an endpoint is required to send a packet containing certain frames.  The endpoint might opportunistically add other frames, not mandated to be sent, as long as it's doing the work of generating and sending a packet anyway.  These opportunistically added frames are "bundled" with the mandatory frames.

More generally, the term refers to selecting a collection of frames waiting to be sent when generating an outgoing packet.

**Comment by MikeBishop** [comment]
(Versus coalescing, which is putting more than one packet in a single UDP datagram.)
