### ISSUE TITLE
Frame Types and Formats by transport requirements

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#3737]
In Section Frame Types and Formats, there is a very useful summary of frame types by packet type. As a person with a CC and transport protocol interest, it would be really nice to have had a summary table of key properties that included whether each frame type is ack-eliciting;  whether transmission is controlled by flow-control; and whether transmission is controlled by congestion-control. Is there any chance we can add an extra column say to this table?

**Comment by martinthomson** [comment]
The problem with the table is that it is already essentially the full width available to us.  That makes the addition of more information quite difficult.

The rules for most of these are simple enough that I'm not sure that the table is the best way to present it.  That is:

ack-eliciting: all except ACK, PADDING
congestion-controlled: all except ACK
flow controlled: only STREAM

**Comment by gorryfair** [comment]
I wouldn't want to mess-up the table format to include the info. However, it would be really nice to have the info in a compact way close to the table somehow so that readers quickly confirm this. Would a note below the table possibly work, saying just this?
