### ISSUE TITLE
max_udp_payload_size (0x03) needs a ref. to packet size section.

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#3738]
In max_udp_payload_size (0x03) the following text seems good: 
/This limit does act as an additional constraint on datagram size in the same way as the path MTU, but it is a property of the endpoint and not the path./
- could it refer to the appropriate section in the QUIC spec?
- In DPLPMTUD the same value is known as “MAX_PLPMTU”, Section 5.3.1 - in case you wish to cite that.

**Comment by martinthomson** [comment]
MAX_PLPMTU is *slightly* different as it refers to the IP layer, but you are right that it constrains the same underlying variable.

I'll add a cross-reference though.
