### ISSUE TITLE
Editorial work on pacing text

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#3748]
N was introduced in #3630 to describe how a sender might pace at a rate that allows it to send a congestion window's worth of data in a period that is shorter than an RTT. This PR clarifies text that goes into unnecessary detail, trying to describe assumptions (the network is spreading the packets out, for example, resulting in an ack clock).

**Comment by larseggert** [comment]
Can we make progress in this one?

**Comment by janaiyengar** [comment]
Yes, I'm waiting for the design issues to get done before moving on the remaining editorial ones.

**Comment by larseggert** [comment]
I think that has happened now :-)

**Comment by larseggert** [comment]
Nudge
