### ISSUE TITLE
[Editorial] Lots of forward references

### ISSUE THREAD

**Issue by wbl** [quicwg/base-drafts#3763]
When I was reading quic-transport I found it very difficult to deal with the forward references. Streams are presented before connections, the overall state machine isn't introduced up front, packets come long after frames, and both are long before the wire formats are described. It might worth revisiting the section ordering.

**Comment by ianswett** [comment]
At some point, transport was hugely restructured, and I believe many of those changes were good, but some didn't work out that well.

I find streams coming before connections particularly odd.

**Comment by MikeBishop** [comment]
The larger idea is "high-level concepts, then wire encoding" which I think makes sense.  It puts the things that someone needs for a conceptual understanding of the protocol in one place, and the things that someone needs to implement the protocol elsewhere.

Within the high-level concepts, I also find it strange that connections don't come before streams.  However, the "connections" group also includes things that really don't deserve pride-of-place as the first couple things to be discussed, either.

**Comment by martinthomson** [comment]
I think that the main concept you need is that QUIC has a connection that is shared state between two endpoints.  The later sections about connections go into more detail than you need to understand the stream sections.  But I note that we don't properly provide that basic knowledge in our introductory parts, which are quite lean.  Leanness is good, but we might have overdone it slightly in this regard.

**Comment by MikeBishop** [comment]
Having worked my way through the spec, my suggested resolution to this is that Section 5.3 needs to be earlier, perhaps *much* earlier.  At the least, it should open Section 5; some or all of it might belong in Section 1.
