### ISSUE TITLE
Clarify RESET_STREAM interaction with flow-control limits

### ISSUE THREAD

**Issue by jlaine** [quicwg/base-drafts#3782]
When a `RESET_STREAM` is received, it carries a `final size` field. The specs do not describe the behaviour if the final size exceeds per-stream or connection-wide flow-control limits: should a `FLOW_CONTROL_ERROR` be triggered or a `FINAL_SIZE_ERROR`?

My preference would be `FLOW_CONTROL_ERROR` as this means the peer has transmitted too much data (presumably lost in flight prior to the reset).

**Comment by martinthomson** [comment]
I think that the [current text](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-4.1-7) is clear enough:

> A receiver MUST close the connection with a FLOW_CONTROL_ERROR error (Section 11) if the sender violates the advertised connection or stream data limits.

**Comment by larseggert** [comment]
Resolution seems to be to close with no action - @jlaine ?

**Comment by larseggert** [comment]
No response from @jlaine in two weeks, am closing this on the assumption that the current text is clear enough. Please reopen if there is disagreement.
