### ISSUE TITLE
Clarify text on HTTP/1.1 and multiplexing

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#3790]
@reschke raised the point that the following text might be misleading, since HTTP/1.1 allows pipelining: "HTTP/1.1 [HTTP11] is a TCP mapping which uses whitespace-delimited text fields to convey HTTP messages. While these exchanges are human-readable, using whitespace for message formatting leads to parsing complexity and motivates tolerance of variant behavior. Because each connection can transfer only a single HTTP request or response at a time in each direction, multiple parallel TCP connections are often used, reducing the ability of the congestion controller to effectively manage traffic between endpoints."

@mnot suggested the following text instead: "Because of limitations in how HTTP exchanges are mapped onto TCP connections in HTTP/1.1, multiple parallel connections are often used..."

@royfielding suggested the following text instead: "Because HTTP/1.x does not include a multiplexing layer, multiple TCP connections are often used to service requests in parallel. However, that has a negative impact on congestion control and network efficiency, since TCP does not share congestion control across multiple connections."

**Comment by mnot** [comment]
Roy's works for me.
