### ISSUE TITLE
PATH_RESPONSE isn't path-tied

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3797]
In #2637, we removed the requirement that PATH_RESPONSE be sent/received on the same path that PATH_CHALLENGE was sent.  However, there is still text in the document that relies on this assumption.

- In 8.5, it explains that receipt of the PATH_RESPONSE on another interface doesn't cause validation to fail, because "It is possible that a valid PATH_RESPONSE might be received in the future."  But receipt of the PATH_RESPONSE, over any interface *is* valid, and causes the validation to *succeed*.
- In 9.2, it suggests using path validation to demonstrate return reachability, but since PATH_RESPONSE need not be sent on the same path, path validation doesn't demonstrate that.

**Comment by huitema** [comment]
Note that sending the response on the old path can lead to failures in "break before make" scenarios. Shall we mention that?
