### ISSUE TITLE
Draining after Idle Timeout?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3798]
10.2 says that after the idle timeout expires, "the connection is silently closed and its state is discarded."  However, 10.2.1 says that the peer "might enter its draining state."  Based on 10.2, I would not expect there to be a draining state; the connection is simply gone, and you would get a stateless reset.

Is the draining state used after the endpoints time out, or not?

**Comment by martinthomson** [comment]
I need to find the issue, but we explicitly decided to not drain after idle timeout.

**Comment by martinthomson** [comment]
#2347 resolved this.
