### ISSUE TITLE
Source for 15-30 second timeout on middleboxes?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3799]
10.2.2 says that "experience shows" you should send packets every 15-30 seconds, RFC4787 notwithstanding.  Ideally, we would have a source that we could reference for this "experience."

**Comment by larseggert** [comment]
Maybe see https://tools.ietf.org/html/bcp145#section-3.5

**Comment by martinthomson** [comment]
I'm going to say that while the 15s floor is a good requirement, I don't want to cite RFC 8085 for this gem, which I think is straight-up misinformation: "NATs require a state timeout of 2 minutes or longer [RFC4787]."  We do cite RFC 8085 elsewhere and that's fine, but the fact here is that the IETF has requested that NATs provide a state timeout of 2 minutes.  That does not mean that they do.

**Comment by janaiyengar** [comment]
I have seen anecdata as well that showing 30 seconds is an important threshold. I think the ref we now have is good.
