### ISSUE TITLE
Which packet number spaces can't be reset?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3801]
17.2.5.3 says that after receiving a Retry, clients MUST NOT reset the packet number for *any* packet number space, and references 17.2.3 for more info.  However, 17.2.3 only explains why this is the case for 0-RTT packets.  We should either narrow the prohibition or expand the explanation.

**Comment by kazuho** [comment]
Or maybe move the explanation that currently exists 17.2.3 to 17.2.5.3 and use it as an example (to avoid it being read as the only reason).

**Comment by larseggert** [comment]
@MikeBishop does @kazuho's editorial change address your issue?

**Comment by MikeBishop** [comment]
Yes, this is fine.
