### ISSUE TITLE
Frames vs. Frame

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3804]
In the Frame Types section (19.x), the types which span multiple IDs are identified as "STREAM Frames", "ACK Frames", and "CONNECTION_CLOSE Frames" while all other frame types are singular ("NEW_TOKEN Frame").  I initially thought it was just a typo, but it's consistently done for everything that has embedded flags.

Raising an editorial issue to double-check if we want to retain a convention that looks like an error on first glance.  If the editors say yes, feel free to close with no objection from me.

**Comment by martinthomson** [comment]
I made this change quite deliberately, but I'm happy to take input on why "Frame" is clearer.

**Comment by janaiyengar** [comment]
I suggest that we use the singular, since these sections are definitions of these frame types.

**Comment by MikeBishop** [comment]
Two reasons.  The first is simply consistency -- something technically correct that still looks like an error might not be worth defending.  The second is the question of whether there are in fact multiple types versus a single type with flags.

I can see the alternate view, that there are two different ACK frames and the section describes those two frame types.  The same is true for CONNECTION_CLOSE, where there are two types with different implications. Both of these *were* two distinct frame types in previous drafts.

For me, that view breaks down with STREAM, unless you want to say there are eight types of STREAM frame and the section describes all eight.  The section describes a single STREAM frame with flags embedded in the type byte.

**Comment by LPardue** [comment]
I've seen implementations handle it both ways: one struct with a type, and many structs.

My suggestion would be to define a `Frameset` term, then it is editorially pleasant to say something like 

``` 
   The MAX_STREAMS frameset (type=0x12 and 0x13) informs the peer of the
   cumulative number of streams of a given type it is permitted to open.
```

**Comment by martinthomson** [comment]
I'm ambivalent on "frame" vs. "frames" here, but I will oppose any attempt to add to the cognitive load on readers.  New terms are out for me.

**Comment by martinthomson** [comment]
How about we refer to frames collectively always instead and say "X frames are formatted as shown in {{x}}."

**Comment by MikeBishop** [comment]
Works for me.
