### ISSUE TITLE
Minor fixes for the recovery draft

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#3813]
- [x] In A.8 `#` should be `//`.
- [x] Both "in-flight" and "in flight" are used. It's better to uniform them to "in-flight". (rejected)
- [x] The same for "count toward" and "count towards". (rejected)
- [x] The packet field `ack_eliciting` is not referred. It should be removed.
- [x] The packet field `sent_bytes` is defined but the field name actually used is `size`. `.size` should be `.sent_bytes`.
- [x] In Sec 6.2.3 "For example, clients can coalesce an Initial packet containing PING and PADDING frames with a 0-RTT data packet and a server can coalesce an Initial packet containing a PING frame with one or more packets in its first flight".  Singular vs plural: client*s* and *a* server. "Clients" should be "a client".
- [ ] Should `max_datagram_size` be `max_udp_payload_size` for clarity?
- [ ] In A.6, I think that `OnDatagramReceived` should be `OnPacketReceived` since `OnPacketSent` is used in A.5.

**Comment by kazu-yamamoto** [comment]
- In A.7, `// DetectNewlyAckedPackets finds packets` should be `// DetectAndRemoveAckedPackets finds packets`. Or this comment is not necessary at all.

**Comment by kazu-yamamoto** [comment]
> - The packet field `ack_eliciting` is not referred. It should be removed.

Rather than removing it, I guess it's better to define `IncludesAckEliciting` explicitly and refer `.ack_eliciting` in it.

**Comment by kazu-yamamoto** [comment]
> - In A.7, `// DetectNewlyAckedPackets finds packets` should be `// DetectAndRemoveAckedPackets finds packets`. Or this comment is not necessary at all.

I cannot find the definition of `DetectAndRemoveAckedPackets`. (I was confused with `DetectAndRemoveLostPackets`.)

**Comment by kazu-yamamoto** [comment]
In B.5, `acked_packet` of `acked_packet.size` is used only here. It should probably be `packet.size`.

**Comment by kazu-yamamoto** [comment]
In A.7, `now -` should be `now() -`.

**Comment by kazu-yamamoto** [comment]
In A.7:

```
latest_rtt = now - sent_packets[pn_space][ack.largest_acked].time_sent
```

is also strange. `sent_packets[pn_space][ack.largest_acked]` is not available here since it was removed by `DetectAndRemoveAckedPackets`.

**Comment by kazu-yamamoto** [comment]
`kInitialRtt` is not used anywhere. Should `initial_rtt` in A.4 be `kInitialRtt`?

**Comment by kazu-yamamoto** [comment]
B.8: "Invoked from `DetectLostPackets` when packets are deemed lost."

But `OnPacketsLost` is called from `OnLossDetectionTimeout` and `DetectLostPackets` is not defined.

**Comment by kazu-yamamoto** [comment]
A.9: `bytes_in_flight`, which is defined in B, is used.

**Comment by kazu-yamamoto** [comment]
The `return` in `for` in `GetPtoTimeAndSpace` suggests me that the semantics of `return` in `for` returns a value form the function. In `OnPacketsAcked`, `return` is also used in `for`. But in this case, it seems to me that the semantics of this `return` goes to the next item.

**Comment by kazu-yamamoto** [comment]
In A, `for` is not followed by `(`. But on some places in B, `for` is followed by `(`.

**Comment by kazu-yamamoto** [comment]
@janaiyengar I would like to see fixed pseudo code so that I can put my implementation work forward.

**Comment by kazu-yamamoto** [comment]
I would like to know how to implement `AreAllPacketsLost` and `DetectLostPackets`.

**Comment by kazu-yamamoto** [comment]
> I would like to know how to implement `AreAllPacketsLost` and `DetectLostPackets`.

`DetectLostPackets` was fixed via 2961b77dc1742f337343134bf455405688eb47c3.

**Comment by kazu-yamamoto** [comment]
@ianswett Some inconsistencies would be added via #3540.

**Comment by kazu-yamamoto** [comment]
`max_ack_delay` is initialized to 0 but not updated anywhere.

**Comment by kazu-yamamoto** [comment]
> `max_ack_delay` is initialized to 0 but not updated anywhere.

- [ ] I would like to have a comment that `max_ack_delay` is set when TP is exchanged.

- [ ] `max_ack_delay` is used in three places in the pseudo code. `InPersistentCongestion` uses non-0 value for Initial and Handshake. Other two places looks good.

**Comment by larseggert** [comment]
Does anything remain to be done for this one?

**Comment by kazu-yamamoto** [comment]
Some but minor. Let's close this. I will open some issues when the current merge process is done.
