### ISSUE TITLE
Editorial Fixes for HTTP-QUIC

### ISSUE THREAD

**Issue by Jxck** [quicwg/base-drafts#3815]
> If a client stream terminates without enough of the HTTP message to provide a complete response, the server SHOULD abort its response with the error code H3_REQUEST_INCOMPLETE.

**client stream** should be clearly written as **client initiated stream**

> If the server sends a partial or complete response but does not **abort reading**, clients SHOULD continue sending the body of the request and close the stream normally.

the word which pair of **send response** is **receive request**, so its better to be **does not abort recieving request** here for clearify.

**Comment by MikeBishop** [comment]
First one is good. The second one is intended to align with Section 2.4 of the transport draft, where "abort reading" is a defined operation on a stream; maybe "does not abort reading the request"?

**Comment by Jxck** [comment]
@MikeBishop > "does not abort reading the request"
SGTM too
