### ISSUE TITLE
Confusing duplication in TLS Encryption Level Changes

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3816]
The first two sentences of QUIC-TLS, Section 4.1.4 clearly intend to say different things, but I can't figure out the distinction.  Is there a way we could reword them to make them clearer?

> As keys for new encryption levels become available, TLS provides QUIC with those
> keys.  Separately, as keys at a given encryption level become available to TLS,
> TLS indicates to QUIC that reading or writing keys at that encryption level are
> available.

**Comment by martinthomson** [comment]
I think that this is not separately at all.  Let's reduce that to a single statement.
