### ISSUE TITLE
Tickets/tokens MUST NOT carry application semantics, but carry settings

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3817]
There seems to be a conflict between this assertion in Section 9.2:

> TLS session tickets and address validation tokens are used to carry QUIC configuration information between connections.  These MUST NOT be used to carry application semantics.

...and the fact that 4.8 explicitly discusses how application protocols might need to have data embedded in the session ticket.  (Also, QUIC doesn't use TLS address validation tokens.)  I think this is actually trying to say that receipt of the session ticket MUST NOT cause side-effect beyond setting up the connection, but it's a broader prohibition than that.

**Comment by martinthomson** [comment]
I think that it says something else, namely that these are not intended to convey semantic information from client to server (or vice versa).  PR inbound.
