### ISSUE TITLE
Inconsistent recommended initial RTT values

### ISSUE THREAD

**Issue by Ralith** [quicwg/base-drafts#3822]
The recovery draft states both:

> [When no previous RTT is available, the initial RTT SHOULD be set to 333ms, resulting in a 1 second initial timeout, as recommended in [RFC6298].](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#section-6.2.2-1)

> [kInitialRtt: The RTT used before an RTT sample is taken. The value recommended in Section 6.2.2 is 500ms.](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#section-a.2-2.8)

I'm guessing the latter was missed in an edit?

**Comment by kazuho** [comment]
> I'm guessing the latter was missed in an edit?

+1. I think we missed to change the definition of kInitialRtt in #3525.

**Comment by kazu-yamamoto** [comment]
As I pointed out in #3813, the current pseudo code does not use `kInitialRtt`, which should be fixed.
