### ISSUE TITLE
Invariants definition of Unused in Version Negotiation packet

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#3827]
For -09 in WG LC.

Section 6 has a packet header structure with the field:

Unused (7)

All the other fields are either fixed value or kind of defined earlier. In fact I would argue they represent concepts that are defined in -transport. Thus a second part of this is if -transport needs to be normative reference for the concepts used in this document. 

But back to Unused: I think this field can take any value on transmission, and should be ignored on reception. Maybe this needs to be noted explicitly in Section 6.

**Comment by MikeBishop** [comment]
It's very deliberate that Invariants does not normatively depend on Transport.  Invariants needs to stand alone, as a description of what versionless QUIC means.  Arguably, Transport could normatively depend on Invariants, but it chooses instead to restate the things it depends on and make the reference informative.
