### ISSUE TITLE
Inconsistency regarding future protection of version negoitation

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#3828]
This is for -invariants-09:

Section 6 says:

   Version Negotiation packets do not use integrity or confidentiality
   protection.  A specific QUIC version might authenticate the packet as
   part of its connection establishment process.

Is the second not contradicting what is said in previous paragraph:

    A Version Negotiation packet contains no other fields.

So to my understanding the authentication that the paragraph above talks about needs to be done in another QUIC packet, it can't be done in a QUIC packet that is Version Negotiation. Can this be made more explicit or do I misunderstand and can you then clarify why this is not a contradiction?

**Comment by martinthomson** [comment]
I don't think so.  The sentence here:

>  A specific QUIC version might authenticate the packet as part of its connection establishment process.

Implies that the version fields might be authenticated.  Indeed, the document says that they MUST be authenticated (somehow).

It doesn't say how.  However, this

> A Version Negotiation packet contains no other fields.

... means that it can't use any fields that are included in a Version Negotiation packet to do that.

If you look at the current proposal for [QUIC version negotiation](https://github.com/quicwg/version-negotiation), that uses transport parameters.

**Comment by gloinul** [comment]
Ok, then I would request a very minor tweak in this sentence: 

 A specific QUIC version might authenticate the packet as
part of its connection establishment process.

So that it is explicit that is in another packet(s) than the Version negotiation packet. For example:

 A specific QUIC version might authenticate the version negotiation packet as
part of its connection establishment process outside of this packet.

**Comment by martinthomson** [comment]
I have made a slightly larger tweak.
