### ISSUE TITLE
Remove API requirement for resource allocation

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3838]
S 5.4 requires that the application be able to

  - control resource allocation of various types, including flow control and the
  number of permitted streams of each type;

This seems like a good idea, but it seems like one could have a reasonable QUIC stack that did not do this.

**Comment by martinthomson** [comment]
I would prefer to leave this.  Noting that the level of control is not specified.

This also suggests that the stack provide a keep-alive control, but there are likely cases (I'm thinking here of DNS over QUIC) where that is unlikely to be a useful feature.

The goal is to list things that the specification believes a generic stack will provide.  Maybe we could avoid the implication that such an implementation is incomplete by saying that specialized implementations might provide less than a complete API.

**Comment by larseggert** [comment]
@ekr willing to fight for this one?

**Comment by martinthomson** [comment]
After discussing with editors, we think that it would be better to remove the MUST in this section and say something like: "A general purpose QUIC implementation provides the following functions:" and add "A specialized implementation might provide a subset of these."

The same applies to the stream operations.

**Comment by LPardue** [comment]
I think that is a positive change. Borderline design by the sound of it. It would be good to see the PR once its available.
