### ISSUE TITLE
Require only support for PSK-(EC)DHE

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3839]
S 7. Claims

      * 1-RTT keys have forward secrecy

This is only true if you only resume with PSK-(EC)DHE, but I don't see a requirement for this. So we need to either require this or change the text.

**Comment by martinthomson** [comment]
This obsession with forward secrecy is a hang-up from Google QUIC.  I think that we should instead say that 1-RTT keys are derived from the completed cryptographic handshake instead.
