### ISSUE TITLE
Which DCID used to determine packet protection keys

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3840]
>  When an Initial packet is sent by a client that has not previously received an
  Initial or Retry packet from the server, the client populates the Destination
  Connection ID field with an unpredictable value.  This Destination Connection ID
  MUST be at least 8 bytes in length.  Until a packet is received from the server,
  the client MUST use the same Destination Connection ID value on all packets in
  this connection. This Destination Connection ID is used to determine packet
  protection keys for Initial packets.

I had understood that you changed keys for the later initial packets when DCID changed. No?

**Comment by marten-seemann** [comment]
> I had understood that you changed keys for the later initial packets when DCID changed. No?

That is correct. I guess the confusion comes from the "This" in the last sentence. We should make clear which CID it is referring to.

**Comment by MikeBishop** [comment]
Depends why it changed.  Retry starts a new connection attempt, with a new DCID, and new Initial keys.  But the Initial keys don't change when the server's Initial provides a new SCID.
