### ISSUE TITLE
Off-path and on-path (S 9.3.2)

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3841]
I find the text in 9.3.3 confusing, because it says:

  Unlike the attack described in {{on-path-spoofing}}, the attacker can ensure
  that the new path is successfully validated.

This is odd because on-path attackers are generally regarded as stronger than on-path attackers. Why can't an on-path attacker complete this attack.

**Comment by MikeBishop** [comment]
I think you're right that the text is confusing, if not quite incorrect.

An on-path attacker can rewrite a source address, causing an apparent migration, but can't cause path validation to succeed with that source address unless it is actually on-path from both endpoints to the spoofed addresses as well.  An off-path attacker which can race packets successfully can cause migration with successful path validation to a path which includes it, becoming a limited on-path attacker.

This also feels slightly duplicative of 21.12.3; it might be worth condensing some text between these sections.
