### ISSUE TITLE
Which idle timeout are we avoiding in 10.2.2

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3844]
> An endpoint might need to send ack-eliciting packets to avoid an idle timeout
if it is expecting response data, but does not have or is unable to send
application data.

However, you can't necessarily reset your own idle_timeout that way because it only is reset when you haven't already sent an ack-eliciting packet after the last received packet. If this is about resetting the peer, then maybe editorial. If it is about resetting yourself, then this may be design.

**Comment by martinthomson** [comment]
This is both idle timeouts.

The idea behind the rules regarding the local reset of the idle timer is that if you send an ack-eliciting packet, you will get an acknowledgment.  You are required to send probes until you do.  So you only reset the timeout on the first.
