### ISSUE TITLE
What does "MUST reduce" mean?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3845]
> An endpoint is allowed to drop the packet protection keys when entering the
closing period ({{draining}}) and send a packet containing a CONNECTION_CLOSE in
response to any UDP datagram that is received.  However, an endpoint without the
packet protection keys cannot identify and discard invalid packets.  To avoid
creating an unwitting amplification attack, such endpoints MUST reduce the
frequency with which it sends packets containing a CONNECTION_CLOSE frame.  To

This seems like a pretty vague requirement for a 2119 MUST. Like, I could only send it 9999/10000 packets and that would be compliant.

**Comment by martinthomson** [comment]
I think that it would be good to follow the 3x rule here also, but that's a non-editorial change.

**Comment by larseggert** [comment]
Do folks agree the PR resolves this?

**Comment by ianswett** [comment]
I think the PR resolves this and is a sensible choice.

**Comment by janaiyengar** [comment]
Yup, the PR resolves this.

**Comment by larseggert** [comment]
OK, labelling as such.
