### ISSUE TITLE
Integrity protection

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3849]
Should we perhaps not use integrity in S 12.1 when we are talking about null keys?

**Comment by martinthomson** [comment]
I don't follow.  Assuming that you are talking about [the same Section 12.1](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-protected-packets) then I don't see any reference to null keys.  Are you suggesting that we say something like:

>  Initial protection only exists to ensure that the sender of the packet is on the network path.  The integrity protection provided for Initial and Retry packets guards against accidental modification of packets that might not be caught by the UDP checksum.

**Comment by ekr** [comment]
What I'm saying is that we should probably reserve the word "integrity" for when there are strong keys.

**Comment by martinthomson** [comment]
Address in #3900.
