### ISSUE TITLE
Packet coalescing rules

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3850]
Here are three quasi-nits about S 12.2.

> Coalescing packets in order of increasing encryption levels (Initial, 0-RTT,
Handshake, 1-RTT; see Section 4.1.4 of {{QUIC-TLS}}) makes it more likely the
receiver will be able to process all the packets in a single pass. A packet
with a short header does not include a length, so it can only be the last
packet included in a UDP datagram. An endpoint SHOULD NOT coalesce multiple
packets at the same encryption level.

Is the implication here that you should instead pack all the frames into one packet?

> Receivers MAY route based on the information in the first packet contained in a
UDP datagram.  Senders MUST NOT coalesce QUIC packets for different connections
into a single UDP datagram.  Receivers SHOULD ignore any subsequent packets with
a different Destination Connection ID than the first packet in the datagram.

Is there a valid reason to have different SCIDs?

> Retry packets ({{packet-retry}}), Version Negotiation packets
({{packet-version}}), and packets with a short header ({{short-header}}) do not
contain a Length field and so cannot be followed by other packets in the same
UDP datagram.  Note also that there is no situation where a Retry or Version
Negotiation packet is coalesced with another packet.

Should this be a MUST NOT?

**Comment by martinthomson** [comment]
1. Yes.
2. See #3800.
3. I don't see why.  It's just a fact, not a conformance requirement.

**Comment by ekr** [comment]
For (1) I think it would be helpful to say that.
