### ISSUE TITLE
Frames of impermissible type

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3851]
> An endpoint MUST treat the receipt of a frame of unknown type as a connection
error of type FRAME_ENCODING_ERROR.

What about a frame of an impermissible type for this key space?

**Comment by martinthomson** [comment]
https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#section-4-5

**Comment by ekr** [comment]
This seems to only apply to 0-RTT, but there are lots of frames which may not appear in Initial
