### ISSUE TITLE
Are 13.2.3 and 13.2.4 normative or not?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#3852]
13.2.2. calls them "exemplary" but 13.2.4 has MUST in it.

**Comment by martinthomson** [comment]
For reference, this refers to [Section 13.2.3](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-managing-ack-ranges) and [Section 13.2.5](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-limiting-ack-ranges) in the editor's copy.

I'm in favour of striking the exemplary note and saying that while the recovery draft is advisory, this document depends on implementations following something like what is recommended.

**Comment by MikeBishop** [comment]
The specific MUSTs aren't really about the ACK algorithm per se, but about state endpoints will have to maintain for other reasons that are typically folded into your loss recovery code.

- If an implementation is unable to do duplicate detection for a packet number range, it MUST fail toward rejecting all packets, not toward accepting potential duplicates.
- An implementation must track the greatest packet number ever received, for use in recovering future packet numbers.

In fact, the first requirement is discussed in 12.3 and could probably be dropped here.  The second isn't actually called out (MUST) in 17.1, but could easily be moved there.

**Comment by ianswett** [comment]
I think I'm inclined towards reorganizing the text and putting all the 'exemplary' parts into one section(ie: "Limiting ACK Ranges") and moving the normative text either into "Managing ACK Ranges" or elsewhere in the draft.

**Comment by ianswett** [comment]
I thought I could clean this up fairly quickly, but I think a fair number of paragraphs need to move, including some of @MikeBishop suggestions.  I'm happy to try to improve this in a few days if no one else has beaten me to it.

**Comment by larseggert** [comment]
Anyone want to help @ianswett out and take this on?
