### ISSUE TITLE
incorrect error code used for invalid RETIRE_CONNECTION_ID frames

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#3860]
> The sequence number specified in a RETIRE_CONNECTION_ID frame MUST NOT refer to the Destination Connection ID field of the packet in which the frame is contained. The peer MAY treat this as a connection error of type FRAME_ENCODING_ERROR.

Our principle regarding error codes states that only those errors that are detectable without accessing connection state should result in a FRAME_ENCODING_ERROR. Since the RETIRE_CONNECTION_ID frame contains only the sequence number of the connection ID, but not the actual connection ID itself, this should be a different error.
Looking through the list of error codes, it seems like we don't have any more specific error code here, so this would be a PROTOCOL_VIOLATION.

**Comment by martinthomson** [comment]
Seems OK.

**Comment by LPardue** [comment]
As the proposed PR indicates, this would be a design change.

**Comment by ianswett** [comment]
Agreed, this seems OK.

**Comment by janaiyengar** [comment]
As I noted in the PR, I agree that PROTOCOL_VIOLATION seems like a more appropriate error. In addition to @marten-seemann's point, this is a semantic error, not one of encoding (which suggests syntactic).

**Comment by larseggert** [comment]
It seems we have a proposed resolution, marking as such.

**Comment by dtikhonov** [comment]
PR #3042 was less than a year ago, that's when this error code went from _PROTOCOL_VIOLATION_ to _FRAME_ENCODING_ERROR_
