### ISSUE TITLE
Allow for other inputs than packets

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3873]
The process for interacting with TLS does not acknowledge the possibility that progress in the handshake might depend on inputs other than CRYPTO frames.  In particular, endpoints might need to perform additional checking to decide that the TLS handshake is complete.  The most important example being the processing that occurs for certificate validation.  This is often an asynchronous process, with OCSP and other muck, so recognizing that explicitly in the draft is worthwhile.

This might help tease out one of the causes of the problem discussed in #3821, but it doesn't lead to a solution.

**Comment by ianswett** [comment]
Q: Does this indicate that the TLS changes involved in #3821 may be editorial?  I'd like to focus on the transport and recovery changes to deal with the issue, and it'd be nice if the tls changes were separate from my perspective.

**Comment by janaiyengar** [comment]
Why isn't #3874 adequate for this? Specifically, isn't it enough to change the stance from synchronous to asynchronous?

**Comment by martinthomson** [comment]
I would prefer to explain how certificate validation can take time and block availability of keys.

**Comment by larseggert** [comment]
Should this become proposal-ready?

**Comment by janaiyengar** [comment]
@larseggert : This is an editorial issue, so no.
