### ISSUE TITLE
Why no minimum Handshake packet size during anti-amplification?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3876]
Recovery, Section 6.2.2.1:

> Since the server could be blocked until more packets are received from the client, it is the client’s responsibility to send packets to unblock the server until it is certain that the server has finished its address validation (see Section 8 of [QUIC-TRANSPORT]). That is, the client MUST set the probe timer if the client has not received an acknowledgement for one of its Handshake or 1-RTT packets, and has not received a HANDSHAKE_DONE frame. If Handshake keys are available to the client, it MUST **send a Handshake packet**, and otherwise it MUST send an Initial packet in a UDP datagram of at least 1200 bytes.

As the sentence currently reads, the size requirement only applies if the client does not have handshake keys.  However, since the server's anti-amplification limit is in bytes, not packets, sending a small Handshake packet will not enable the server to make forward progress.

I would suggest the sentence be rearranged to require sending a packet in a 1200-byte datagram, and switch only the type of packed based on possession of handshake keys.  This might be the intent of the current text, in which case this issue is editorial.

**Comment by ekr** [comment]
Because receipt of a handshake packet proves reachability, the amplification limits no longer apply once it is received.

**Comment by MikeBishop** [comment]
Ah, right.  Forgive the silly question.  🙄

**Comment by ekr** [comment]
Heck, I keep having to work through the logic myself.
