### ISSUE TITLE
Timestamps in acknowledgment of PING?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#388]
Should we encourage implementations to include a timestamp for the specific packet that contains a PING when acknowledging it?

**Comment by ianswett** [comment]
PING frames are retransmittable, so the current text in 8.2 indicates one SHOULD include a timestamp.  This seems reasonable.  Is there a reason to do something else?

**Comment by martinthomson** [comment]
The text says: " A receiver SHOULD send a timestamp exactly once for each retransmittable packet recevied."  Which doesn't really directly identify PING.  (Also, typo, and packets arent' retransmittable.)

**Comment by ianswett** [comment]
Yes, it should be "for each received packet containing retransmittable frames."

It doesn't directly address PING, but a PING is retransmittable, so I don't think it needs to.
