### ISSUE TITLE
Packet protection or not?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3887]
In Transport, we say:

> Invalid packets without packet protection, such as Initial, Retry, or Version Negotiation, MAY be discarded.

However, in TLS we have a section named "Packet Protection" (Section 5) with subsections describing how to protect Initial (5.2) and Retry (5.8) packets which talk about Initial, at least, as using packet protection.  I think it would be clearer to describe the lack of security properties that this limited form of protection provides, rather than say they're not protected at all.

Alternatively, we could rework the language in TLS, but that feels like a bigger terminology change.

**Comment by martinthomson** [comment]
ekr suggested that we limit the use of "integrity protection" (and I presume "confidentiality protection") to those cases where the protection is real, and not based on fixed keys or trivially-acquired keys.  I think that might be the best answer here, even if that takes more effort to get right.

**Comment by janaiyengar** [comment]
@martinthomson : That sounds good like a good way forward.
