### ISSUE TITLE
MUST requirement on bursts smaller than IW is too restrictive

### ISSUE THREAD

**Issue by pravb** [quicwg/base-drafts#3892]
"Implementations MUST either use pacing or another method to limit such bursts to the initial congestion window; see Section 7.2."  

This precludes use of segmentation offload of sizes greater than IW. Hardware does not pace TSO for TCP or USO for UDP. In datacenters we routinely send bursts that are higher without causing loss. Both Linux and Windows TCP send bursts larger than IW (up to 64k) at higher bandwidths. Higher bursts are required for achieving high data rates. 

This text should be changed to a SHOULD.

**Comment by janaiyengar** [comment]
@pravb: DC requirements are likely to run into more than just this problem -- for instance, the initial window itself might be too small. Since the recovery document was really meant for Internet use, not for DC, I would suggest leaving out DC requirements. Perhaps there's a separate document in order for how to tune QUIC for DC.

**Comment by LPardue** [comment]
As an individual, I agree with Jana. We're not going to be able to ship a specification that is able to accommodate all of the spectrum of network characteristics. The documents should allow implementers to build a QUIC implementation that is safe to deploy on the Internet.

As someone less familiar with DCTCP and more general DC considerations, the nuance of making a MUST a SHOULD is likely to be lost on me. A document that takes a more broad look as QUIC in the DC would be super helpful.

**Comment by larseggert** [comment]
Also being discussed [on the mailing list](https://mailarchive.ietf.org/arch/msg/quic/DYjeywiWYuWPF3iTX9_T3R3sI-s)

**Comment by janaiyengar** [comment]
Based on the discussion on the mailing list, I'm proposing that we change the MUST to a SHOULD. See #3936.

**Comment by larseggert** [comment]
Do folks agree with this proposed resolution?

**Comment by ianswett** [comment]
@larseggert I think it's the right direction, but I'd like to do some more work on the PR.
