### ISSUE TITLE
Editorial Fixes for HTTP-QUIC

### ISSUE THREAD

**Issue by Jxck** [quicwg/base-drafts#3895]
## Request Cancellation and Rejection 

1. it better be clarify  Implementation means Client/Server or both.

> When the client aborts reading a response, it indicates that this response is no longer of interest. **Implementations** SHOULD cancel requests by abruptly terminating any directions of a stream that are still open.

2. there are some of similar terms

- reset
- cancel
- reject
- abort
- (abruptly) terminate

it seems better to make them more clarify what each of them describes and how they can be done.

**Comment by MikeBishop** [comment]
"Implementations," throughout the document, refers to both clients and servers.  Do you have a suggested place to clarify this?

- "reset" and "abrupt termination" are synonyms for the same operation in [Section 2.4 of QUIC-TRANSPORT](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-required-operations-on-stre)
- "cancel" and "reject" are separate actions an implementation can take, described in [Section 4.1.2](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-request-cancellation-and-re)

It looks like "abort" is used with relatively little context -- I'll try to clean that up a bit.  It's intended to refer to "abort reading," another operation in [Section 2.4 of QUIC-TRANSPORT](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-required-operations-on-stre).

**Comment by Jxck** [comment]
1. I thought this section says about client, but suddenly `Implementation` appears.

- **Clients** can cancel requests by ~
- When the **client** aborts reading a response ~
- **Implementations** SHOULD cancel requests by ~

 so I think this `implementation` is also a client (that says about cancel response). but you mean this says both client/server ? server can cancel request too ?


2.  SGTM >  I'll try to clean that up a bit

**Comment by MikeBishop** [comment]
Yes, servers can cancel a request; that is, indicate that for some reason they will not be processing it any further.  But perhaps it would be clearer to separately state that in a paragraph about server behavior.
