### ISSUE TITLE
When is the "current time"

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3908]
> A client could have received and acknowledged a Handshake packet, causing it to discard state for the Initial packet number space, but not sent any ack-eliciting Handshake packets. In this case, the PTO is set from the current time.

This paragraph does not really provide any context that would allow you to infer what the "current time" is.  Based on the pseudocode, this time is when SetLossDetectionTimer() is invoked, but that covers a range of cases:

* When a packet is received and the endpoint is at its anti-amplification limit
* When an in-flight packet is sent
* When an ACK is received
* When the loss detection timer pops
* When a packet number space is discarded

Of these, the "current time" clause only really applies to the last two, and the last one is the real baseline (because the other only matters if the first was set).  I think that this can be more precisely worded to say "In this case, the PTO is set from the time at which the Initial packet number space is discarded."  That's far more direct, but I would like others to check my work to ensure that it catches all the cases properly.

**Comment by ianswett** [comment]
Setting the time from when the Initial PN space is discarded is a good clarification, and conveniently it lines up with the pseudocode.  The pseudocode for OnPacketNumberSpaceDiscarded(pn_space) calls SetLossDetectionTimer().

**Comment by ianswett** [comment]
There are actually two cases now() is used, so we can't solely rely on handshake keys being discarded.

See #3959 for a larger change.
