### ISSUE TITLE
assertion in OnLossDetectionTimeout of recovery draft

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#3912]
The assertion in `OnLossDetectionTimeout` sometime fails in Haskell implementation which is translated from the pseudocode:

```
OnLossDetectionTimeout():
  ...
  if (earliest_loss_time != 0):
    ...
    return

  if (bytes_in_flight > 0):
    SendOneOrTwoAckElicitingPackets(pn_space)
  else:
    assert(endpoint is client without 1-RTT keys)
    // Client sends an anti-deadlock packet: Initial is padded
    // to earn more anti-amplification credit,
    // a Handshake packet proves address ownership.
    if (has Handshake keys):
      SendOneAckElicitingHandshakePacket()
    else:
      SendOneAckElicitingPaddedInitialPacket()
```

How does `bytes_in_flight > 0` guarantee "endpoint is client without 1-RTT keys"?

**Comment by ianswett** [comment]
The only time the PTO is armed when there are no bytes in flight is when it's a client and it's unsure if the peer has completed address validation, so I'll change the assert to that.  It's possible for the client to have 1-RTT keys prior to the server validating it's address, as your code demonstrates.

**Comment by janaiyengar** [comment]
@kazu-yamamoto : In addition to the PR, the point of the assert is not to suggest that it's always true when `(bytes_in_flight == 0)`. The assert confirms that if OnLossDetectionTimeout() is called with `bytes_in_flight == 0`, it's only when the server hasn't yet completed address validation.
