### ISSUE TITLE
Initial window bursts are too small

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#3918]
@pravb argues that limiting bursts to IW is too small a limit in his WGLC comments here: https://mailarchive.ietf.org/arch/msg/quic/_KeDg0RMQqP5epdYQdFb0M7MJ5s/

Section 7.9

"Implementations MUST either use pacing or another method to limit such bursts to the initial congestion window; see Section 7.2."

This seems to preclude use of segmentation offload of sizes greater than IW. In datacenters we routinely send bursts that are higher without causing loss. The MUST here seems unnecessary. It also conflicts with the RECOMMENDED in an earlier sentence.

Neal Cardwell's suggestion:
"Implementations MUST either use pacing or another method to limit such bursts.
  It is RECOMMENDED that traffic over the public Internet limit bursts to the initial
  congestion window; see Section 7.2."

**Comment by ianswett** [comment]
@pravb suggestion on the thread is to change the MUST to a SHOULD.

**Comment by ianswett** [comment]
There's also the classic "MUST unless" option.

**Comment by ianswett** [comment]
@LPardue I think this comment came in prior to WGLC ending, it just didn't get an issue because I'm so behind on email.

**Comment by janaiyengar** [comment]
Yeah, this was filed in WGLC.

**Comment by larseggert** [comment]
Is this not a duplicate of #3982?

**Comment by ianswett** [comment]
Yup, it's a duplicate of #3892 I missed that when filing this.
