### ISSUE TITLE
Recommended behavior for reserved streams

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3933]
In Section 6.2.3, we recommend the following about the reserved unidirectional stream types:
> When terminating abruptly, the error code H3_NO_ERROR or a reserved error code (Section 8.1) SHOULD be used.

However, this has a fatal flaw -- it recommends special handling for the grease types, which is *precisely* the behavior we're trying to disincent with grease.

Instead, I think we should move the recommendation to use reserved error codes to the guidance on what to do with unknown stream types, which is currently:
> Recipients of unknown stream types MAY abort reading of the stream with an error code of H3_STREAM_CREATION_ERROR, but MUST NOT consider such streams to be a connection error of any kind.

This has the same net effect on the grease streams.  The change in behavior is on actual unknown-but-real stream types, which will now get grease error codes in response.

**Comment by LPardue** [comment]
+1 lets do this (as an individual)

**Comment by MikeBishop** [comment]
Actually, scratch that -- it's a misreading.  This is a statement about how the *sender* of the stream should close them, not about behavior on receipt at all.  I'll take this as editorial to emphasize that this is purely about how to send them.
