### ISSUE TITLE
Starting persistent congestion on a ack-eliciting packet

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3941]
Persistent congestion has to start with an ack-eliciting packet.  The section on persistent congestion isn't very clear about this point.

This is because a non-ack-eliciting packet won't be followed up with any probes.  It is therefore possible to send one packet and then not send anything else for an extended period.  After this, the loss of just the next packet will cause persistent congestion.

Note that persistent congestion can be caused by the loss of just two packets after multiple PTOs have occurred, but the common case is that you have at least three packet, or four if you send two packets on PTO.

**Comment by marten-seemann** [comment]
> Note that persistent congestion can be caused by the loss of just two packets after multiple PTOs have occurred, but the common case is that you have at least three packet, or four if you send two packets on PTO.

Would it make sense to change the persistent congestion condition to require at least 3 packets to be lost, in addition to the time threshold that we already have?

**Comment by kazuho** [comment]
> Would it make sense to change the persistent congestion condition to require at least 3 packets to be lost, in addition to the time threshold that we already have?

FWIW we have had some discussion around this in #3875, and it seemed to be that there were preference to *not* do that.

**Comment by martinthomson** [comment]
I implemented this as requiring ack-eliciting on the basis that once you are two PTOs out, it's not that bad that you hit persistent congestion, but I wouldn't object to that.

**Comment by janaiyengar** [comment]
I can at least change this to ack-eliciting -- that's a simple editorial change. That was the intent anyway. If we want to change the way persistent congestion is established, that's a bigger issue, so let's separate that issue from this one.
