### ISSUE TITLE
Reno does not require window reduction on loss

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#3944]
As it stands, the recovery draft does not require the congestion window to be reduced on loss. The only part that talks about this is in Section 7.4, which says:
```
When a loss or ECN-CE marking is detected, NewReno halves the congestion window, sets the
slow start threshold to the new congestion window, and then enters the recovery period.
```
We need to require this reduction for the controller to be a NewReno controller.

**Comment by ianswett** [comment]
To clarify, this isn't a change in what we're describing, you just want to add normative language?
