### ISSUE TITLE
HTTP/2 Settings reservation isn't called out

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3954]
We explicitly discuss what the behavior should be for H2 frame types that don't have corresponding H3 frames.  The same sort of reservation with IANA is done with settings, but isn't explicitly stated in the definition of SETTINGS.

**Comment by MikeBishop** [comment]
Arguably editorial, since the text in the Appendix clearly implies this was already intended to be the case, but fixing entails new MUST and MAY statements.

**Comment by LPardue** [comment]
Lets run this as design for visibility.
