### ISSUE TITLE
Editorial fixes for quic-http

### ISSUE THREAD

**Issue by shqld** [quicwg/base-drafts#3960]
- Ambiguous description with `MAY` for user agents in [server-push](https://github.com/quicwg/base-drafts/blob/e0aa78966fc74475b6a5ef8d12d9472497cdfd2d/draft-ietf-quic-http.md#server-push):

It'd be better to remove or clarify rather than ambiguously allowing user agents with `MAY`.

> These associations do not affect the operation of the protocol, **but MAY be considered by user agents when deciding how to use pushed resources**

- A bit misleading expression with `MAY` in [connection-shutdown](https://github.com/quicwg/base-drafts/blob/e0aa78966fc74475b6a5ef8d12d9472497cdfd2d/draft-ietf-quic-http.md#connection-shutdown)

> Endpoints MUST NOT initiate new requests or promise new pushes on the connection after receipt of a GOAWAY frame from the peer. **Clients MAY establish a new connection to send additional requests**.

This sentence looks to readers like that clients MAY send same requests on another connection even when the server keeps canceling or something regardless of clients' requests. There should be additional sentences no matter if it's the expected behavior or not.

- Some phrases in [connection-shutdown](https://github.com/quicwg/base-drafts/blob/e0aa78966fc74475b6a5ef8d12d9472497cdfd2d/draft-ietf-quic-http.md#connection-shutdown) look verbose and confusing

> Upon receipt of a GOAWAY frame, if the client has already sent requests with a Stream ID greater than or equal to the identifier **received in a GOAWAY frame**

> If a server receives a GOAWAY frame after having promised pushes with a Push ID greater than or equal to the identifier **received in a GOAWAY frame**

- The link `section 4.1 of [QUIC-TRANSPORT]` in [quic-http-29#section-4.4](https://tools.ietf.org/html/draft-ietf-quic-http-29#section-4.4) is wrong:

[quic-http#section-4.1](https://tools.ietf.org/html/draft-ietf-quic-http#section-4.1) should be replaced with [quic-transport#section-4.1](https://tools.ietf.org/html/draft-ietf-quic-transport#section-4.1).

> The client can use stream flow control (see section 4.1 of {{QUIC-TRANSPORT}}) to limit the amount of data a server may commit to the pushed stream.

**Comment by MikeBishop** [comment]
These are separate issues, so let's look at them separately:


> * Ambiguous description with `MAY` for user agents in [server-push](https://github.com/quicwg/base-drafts/blob/e0aa78966fc74475b6a5ef8d12d9472497cdfd2d/draft-ietf-quic-http.md#server-push):
> 
> It'd be better to remove or clarify rather than ambiguously allowing user agents with `MAY`.
> 
> > These associations do not affect the operation of the protocol, **but MAY be considered by user agents when deciding how to use pushed resources**

This is deliberately vague, and the reason is explicitly stated.  They don't affect the operation of the protocol, but user agents are allowed to make use of the associations in implementation-specific ways.  This reflects HTTP/2, where some browsers use the association and some do not.

> * A bit misleading expression with `MAY` in [connection-shutdown](https://github.com/quicwg/base-drafts/blob/e0aa78966fc74475b6a5ef8d12d9472497cdfd2d/draft-ietf-quic-http.md#connection-shutdown)
> 
> > Endpoints MUST NOT initiate new requests or promise new pushes on the connection after receipt of a GOAWAY frame from the peer. **Clients MAY establish a new connection to send additional requests**.
> 
> This sentence looks to readers like that clients MAY send same requests on another connection even when the server keeps canceling or something regardless of clients' requests. There should be additional sentences no matter if it's the expected behavior or not.

Here again, I'm not seeing the problem.  The requests have been canceled -- effectively "unsent" on this connection.  If the client still needs to make those requests, they can't send them on this connection, but they MAY open a new connection.

> * Some phrases in [connection-shutdown](https://github.com/quicwg/base-drafts/blob/e0aa78966fc74475b6a5ef8d12d9472497cdfd2d/draft-ietf-quic-http.md#connection-shutdown) look verbose and confusing
> 
> > Upon receipt of a GOAWAY frame, if the client has already sent requests with a Stream ID greater than or equal to the identifier **received in a GOAWAY frame**
> 
> > If a server receives a GOAWAY frame after having promised pushes with a Push ID greater than or equal to the identifier **received in a GOAWAY frame**

"received in a" -> "contained in the" would help here, unless you had a suggestion for making it tighter.

The final issue is unrelated to these drafts, and is something the Tools server does.  If you see an incorrect reference in the text draft or Editor's Copy HTML, please do point them out.
