### ISSUE TITLE
pseudo code doesn't reflect the change introduced in #3911

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#3962]
The pseudo code says the following:
```
if (no in-flight packets):
    assert(!PeerCompletedAddressValidation())
    if (has handshake keys):
      return (now() + duration), Handshake
    else:
      return (now() + duration), Initial
```

With the change introduced in #3911, the spec says the following for the time from which the timer should be armed if there are no outstanding packets in the Handshake packet number space:
> the PTO timer is armed from the time that the Initial packet number space is discarded.

**Comment by ianswett** [comment]
This code is called from where Initial keys are discarded, so I believe it still matches the text, which only discusses the "(has handshake keys)" case.

**Comment by ianswett** [comment]
That being said, it feels odd we mention one case of using now() and not the other, so I updated PR #3959
