### ISSUE TITLE
infinite loop of OnLossDetectionTimeout

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#3967]
`OnLossDetectionTimeout` in the recovery draft always calls `SetLossDetectionTimer`, resulting in an infinite loop which continues even after the connection is closed. It would be nice if conditions such as `if (connection is open):` are added or comments are added.

**Comment by marten-seemann** [comment]
`SetLossDetectionTimer` cancels the timer when there are no ack-eliciting packets in flight, so I can't see how this would create an infinite loop. I'd prefer to not further complicate the pseudo-code here for this corner case.

**Comment by kazu-yamamoto** [comment]
@marten-seemann You are right. My interpretation and implementation was wrong. Thank you for pointing out.
