### ISSUE TITLE
Define slow start and congestion avoidance

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3982]
These are not very crisply defined currently.

The congestion controller starts in slow start.  Slow start is where the congestion window is less than the slow start threshold.  Congestion avoidance is where the congestion window is at least the slow start threshold.

**Comment by martinthomson** [comment]
BTW, do people prefer to think of this as a two-state system, or three states:
![image](https://user-images.githubusercontent.com/67641/90358813-71612a00-e09a-11ea-8a05-63dc5672170e.png)

**Comment by janaiyengar** [comment]
This would be excellent to add after we've merged the normatives in #3978.

**Comment by janaiyengar** [comment]
FWIW, I think now that this really is 3 states. Your FSM works for me.
