### ISSUE TITLE
Explain why we include max_ack_delay in some timers

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#3987]
@Ralith says in #3951:

> Some clarifying language expressing that the ack delay is included in path validation/closing/draining timers/etc only for simplicity would be nice. Given the large potential impact, the reader is otherwise left trying to guess why that's appropriate.

This is reasonable.  I don't know which document needs the text though.

**Comment by larseggert** [comment]
This looks like it should go into -recovert, since -transport mostly only refers to `max_ack_delay` as a TP, except in Section 13.2.1 ("sending-acknowledgements"), but that text is very general.

**Comment by janaiyengar** [comment]
I would suggest that this should go where a value of X PTOs is suggested for each specific timer.

**Comment by larseggert** [comment]
Relabeling, since #4071 ended up being against -transport and not -recovery.
