### ISSUE TITLE
Reserved frame types error

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#3991]
We currently say:
> Frame types that were used in HTTP/2 where there is no corresponding HTTP/3 frame have also been reserved (Section 11.2.1). These frame types MUST NOT be sent, and receipt MAY be treated as an error of type H3_FRAME_UNEXPECTED.

This text has two failings:

- It doesn't specify whether the error is a stream error or a connection error
- In #3955, it was argued that this violation is easily detected, and perhaps warrants a "MUST error" instead of a "MAY error"

**Comment by ianswett** [comment]
+1 to both changes from my perspective.

**Comment by LPardue** [comment]
This sounds like a design issue. Since this spins off from https://github.com/quicwg/base-drafts/issues/3954 and https://github.com/quicwg/base-drafts/issues/3955 I'm going to assume from past discussion that there is sufficient interest in discussing this.

**Comment by kazuho** [comment]
MUST respond with a connection error SGTM. Frames are hop-by-hop (compared to HTTP messages being end-to-end), therefore we can enforce this.

**Comment by MikeBishop** [comment]
Thanks, @kazuho.  This had shades of the tunneling discussion before, and I wasn't sure on which side of that fence you'd land.

**Comment by kazuho** [comment]
@MikeBishop Thank you for checking. As stated above, I think we can be strict regarding HTTP frames (especially the types), even though I tend to think that we need to be lax about HTTP messages (and how they are terminated).
