### ISSUE TITLE
Testing notifications to quic-issues@ietf.org

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4]
Sorry for the spam. We only seem to get issue notifications through intermittently.

**Comment by larseggert** [comment]
Matt says things are fixed; testing

**Comment by mattinfla** [comment]
Testing base drafts, sorry for the spam.

**Comment by quic-issues** [comment]
Seeing if a settings change makes GitHub not use BCC when it sends notifications. @mattinfla: check the logs, too, please?

**Comment by larseggert** [comment]
It seems as if this settings change has fixed notifications. Fingers crossed.
