### ISSUE TITLE
Doesn’t say the default is in-order delivery

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4017]
(Broken out of #3214.)

> However, implementations MAY choose to offer the ability to
> deliver data out of order to a receiving application.

This doesn’t say the default is in-order delivery, which I would have thought was the case. It also doesn’t say whether this is per-connection, or per-stream (I imagined the latter).

**Comment by MikeBishop** [comment]
The previous paragraph seems pretty clear about exactly those points.

> Endpoints MUST be able to deliver stream data to an application as an ordered byte-stream. Delivering an ordered byte-stream requires that an endpoint buffer any data that is received out of order, up to the advertised flow control limit.

I'm not seeing the issue here.

**Comment by janaiyengar** [comment]
There isn't a "default". The sentence up there was in fact added later to allow endpoints to deliver out of order. As @MikeBishop notes, the para before it says that in-order is necessary. We aren't requiring anything of the API, so a default delivery mode does not make sense.

**Comment by larseggert** [comment]
@gorryfair OK to close with no action?
