### ISSUE TITLE
ECN "not quite enough"

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4022]
(Broken out of #3214.)

>An endpoint can verify support for Explicit Congestion Notification
>   (ECN) in the first packets it sends, /
- Nearly - It can verify the endpoints support ECN and the current path could be used to transfer ECN-marked packets. That’s not quite enough to complete verification that the path and endpoints have full ECN support.

**Comment by martinthomson** [comment]
This is the level of support that we rely upon.  If the path does not provide ECN-CE marking, that's OK, because the congestion controller responds to loss just as well as marking.  If it doesn't have L4S support, that's not something we care about.

**Comment by larseggert** [comment]
@gorryfair?

**Comment by gorryfair** [comment]
No. I think this is not the same understanding of what it means to say "verify support for ECN". What I see as validation, is the act of setting a CE code point and seeing this echoed by the remote endpoint. To me this can be done at the sending endpoint and the resulting ECN feedback can safely ignored from a CC perspective when it refers to the packet was intentionally CE-marked.

(This does not confirm the devices on path observe or remark, simply that if a known CE-mark is inserted by the sender, this is in fact observed by the receiver and generates a response to the sender. I agree that knowledge whether the path updates ECT-marks is not a part of the spec.)

**Comment by larseggert** [comment]
So would a resolution be "An end point can verify support for ECN by observing whether the ACK frames acknowledging the first packets it sends carry ECN counters"?

**Comment by gorryfair** [comment]
Hmmmm, I recall that proposal .... That's a different approach to what I said, and doesn't check that CE is correctly interpreted, but I think there is only a slim chance that CE-only is not correctly reported (I guess a server could in principle cheat and refuse to report CE-marks - but I have no evidence to suggest we currently need this).

So ... I think my answer is "YES"! Can we explain this out a little, and state that QUIC does this. I'm assuming that this refers independently for each direction of transmission.

**Comment by larseggert** [comment]
If you'd like more text than what I proposed above, could you craft that text?

**Comment by gorryfair** [comment]
Bashed and I believe I'm fine with the current rev.

**Comment by larseggert** [comment]
I added the text above to #4016.
