### ISSUE TITLE
What if parameter definition requires that it is stored?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4024]
(Broken out of #3214.)

> An endpoint MUST ignore transport parameters that it does
>   not support./
- What happens if the parameter definition requires that it is stored? How would it know?

**Comment by MikeBishop** [comment]
From 7.4.1:
> A client need not store a transport parameter it cannot process.

If the client doesn't understand a TP, it doesn't store it and ignores it.

**Comment by ianswett** [comment]
I think this is close with no action, personally.

If it's ignored, then it cannot be stored.

**Comment by larseggert** [comment]
@gorryfair?

**Comment by gorryfair** [comment]
This was a question, close with no action is fine.
