### ISSUE TITLE
Suspect this needs to not delay?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4025]
(Broken out of #3214.)

> MUST respond
>   immediately by echoing the data/
- Of course it may not be able to immediately send anything:-) , but I suspect this needs to not delay?

**Comment by MikeBishop** [comment]
These frames aren't subject to flow control, so the only reason it would be unable to send something is congestion control.  The frame that it echos back needs to be enqueued for sending; if it takes some time to actually hit the network, that's fine.

**Comment by larseggert** [comment]
@gorryfair?

**Comment by gorryfair** [comment]
Seems resolved by the PR

**Comment by marten-seemann** [comment]
For the benefit of others reviewing this: This seems to refer to [8.4 Path Validation Responses](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-path-validation-responses).
