### ISSUE TITLE
New path may not have the same RTT

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4026]
(Broken out of #3214.)

> 9.2.  Initiating Connection Migration/
- I assert the new path may not have the same RTT, because the path could traverse a different set of network devices or be subject to different policies that influence forwarding behaviour. These are not currently listed here, but are the basis for some later text in 9.3.1. Can we mention here?

**Comment by MikeBishop** [comment]
Is the RTT not included in the reset of the congestion controller?

> When migrating, the new path might not support the endpoint's current sending rate. Therefore, the endpoint resets its congestion controller, as described in Section 9.4.

**Comment by ianswett** [comment]
Section 9.4 reads:

"The capacity available on the new path might not be the same as the
   old path.  Packets sent on the old path MUST NOT contribute to
   congestion control or RTT estimation for the new path."

**Comment by ianswett** [comment]
I sent a PR to add "and RTT estimate" to that sentence to make this completely clear.
