### ISSUE TITLE
This statement is dangerous

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4027]
(Broken out of #3214.)

This statement is dangerous:
>However, an implementor should
>   only deviate from these requirements after careful consideration of
>   the performance implications of doing so./
- Let me argue this statement needs to be replaced by:
- “The requirements described are baed on consideration of
   the performance implications and the on other flows that could share network capacity”.
- I strongly argue that implementors how do not implement a PS do not conform to that PS. That happens, but I don’t see the point in a spec saying if you don’t comply you’re still compliant.

**Comment by martinthomson** [comment]
Current text is:

> However, an implementation should only deviate from these requirements after careful consideration of the performance implications of a change, for connections made by the endpoint and for other users of the network.

Which was the result of this feedback.

**Comment by ianswett** [comment]
I'd suggest this is already fixed per @martinthomson comment

**Comment by larseggert** [comment]
@gorryfair?

**Comment by gorryfair** [comment]
Yes - this includes other uses of the network.
