### ISSUE TITLE
Allowing QUIC to suspend ECN usage

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4028]
(Broken out of #3214.)

In Section 13.4 
>An endpoint
>   validates the use of ECN on the path, both during connection
>   establishment and when migrating to a new path (Section 9)./
- I think the QUIC endpoint MAY also validate ECN is still support by the path during communication. This may be necessary when ECN is enabled, but a path change results in there no longer being support.
- I think this needs to also be permitted in Section  13.4.2, allowing QUIC to suspend ECN usage for a path or to an endpoint for which it currently has a connection.

**Comment by martinthomson** [comment]
I apologize, but I don't understand the "suspend" comment.

**Comment by larseggert** [comment]
@gorryfair?

**Comment by mirjak** [comment]
I think the point is if a path changes happens without the sender noticing and suddenly because of misconfiguration alll packets get CE marked you want to detect that and disable ECN. However, if that is something we want to recommend I think we further need to specify this. Another case that is easier to detect would be you only set ECT(0) packets but suddenly get feedback for ECT(1) marks. For that case to detect you basically would need to "run" the validation continuously.

**Comment by mirjak** [comment]
Having that said I'm not sure how likely this case is. I guess we could recommend to re-start validation if e.g. the RTT jumps suddenly as this might be an indication of path change. Again, not sure how likely this case is.

**Comment by larseggert** [comment]
Since we don't know how likely these ECN misconfigs are and what to do about them, maybe we remain silent on the issue?

**Comment by larseggert** [comment]
(I have yet to receive a single CE mark on *any* packet reaching my public server. I set it up so I get an email when that happens.)

**Comment by gorryfair** [comment]
My original point was not calling for a new "test" (I'm also unsure about adding extra tests for pathologies before we know they are needed), but simply a request that a "QUIC endpoint MAY/SHOULD validate ECN is still support by the path during communication"... and as mentioned, this can be simply realised by checking the ECN counters continue to reflect packets that are being sent.

**Comment by larseggert** [comment]
But that ongoing validation is already in the spec in https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-13.4.2.2, right?

**Comment by gorryfair** [comment]
Yes. I've reread that text and the current text is fine with me.
