### ISSUE TITLE
Does that include retransmissions? 

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4030]
(Broken out of #3214.)
>   Prior to validating the client address, servers MUST NOT send more
>   than three times as many bytes as the number of bytes they have
>   received./
- So, let me understand - does that include retransmissions? or is this constrain within the PTO or something?

**Comment by martinthomson** [comment]
Why would it not?  QUIC generally doesn't regard retransmissions as special in any way; calling that out here would be weird.

**Comment by ianswett** [comment]
Agreed, I'd suggest close with no action.

**Comment by larseggert** [comment]
@gorryfair?
