### ISSUE TITLE
Uncapped ACK Delay and RTT estimates

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4035]
When reported ACK Delay would cause the RTT sample to go below min_rtt, we ignore the ACK Delay.  In general, I think that this provides the right incentives to report delays accurately.  If the true minimum RTT is lower than the observed value, you add a few samples that are inflated by up to max_ack_delay.

However...during the handshake, where we don't have an effective cap on ACK Delay, so we effectively have unbound inflation.  And min_rtt is likely not well established.  Should we discard these samples instead?

**Comment by ianswett** [comment]
I think this is a potential issue, but I'd like to see this addressed in #3874 with some text to advise this is a potential issue that MAY be solved by ignoring RTT samples.

**Comment by martinthomson** [comment]
Happy to have this rolled into #3874 as long as we can do so expediently.  I don't want a design issue floating around after this next batch of consensus calls.  @janaiyengar do you think that something could be done?

**Comment by kazuho** [comment]
I tend to think that if we are going to have some advice, it would be something like "MAY ignore the first ACK sample for Handshake and ApplicationData packet number spaces." IIRC, @ianswett suggested something like that somewhere.

Though, if we are going to have something like that, I think we also need to state that using a bad RTT sample might still better than relying on initial RTT of 333ms.

**Comment by janaiyengar** [comment]
I've added some text in #3874 ([commit](952952a241916edbca9cd1a56cd633fc596c756d)) that should capture this point.

**Comment by ianswett** [comment]
Thanks @janaiyengar that new text works for me.
