### ISSUE TITLE
recovery pseudocode enters "recovery" after "slow start"

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#4045]
The spec says that "congestion avoidance" after "slow start". However, it seems to me that pseudocode enters "recovery" after "slow start".

When packets are lost, `OnCongestionEvent` is called:

```
OnCongestionEvent(sent_time):
  // Start a new congestion event if packet was sent after the
  // start of the previous congestion recovery period.
  if (!InCongestionRecovery(sent_time)):
    congestion_recovery_start_time = now()
    congestion_window *= kLossReductionFactor
    congestion_window = max(congestion_window, kMinimumWindow)
    ssthresh = congestion_window
    // A packet can be sent to speed up loss recovery.
    MaybeSendOnePacket()
```

This function sets `congestion_recovery_start_time` if the state is not "recovery", which means either "slow start" or "congestion avoidance". So, "recovery" starts after "slow start".

**Comment by janaiyengar** [comment]
@kazu-yamamoto : you are right; perhaps this could be made part of #3982?

**Comment by kazu-yamamoto** [comment]
@janaiyengar Better definition of each state is welcome. But I'm talking about the pseudocode. My implementation based on the pseudocode enters "recovery" after "slow start". That's why I noticed this issue. We should fix the pseudocode somehow. (To fix this bug, I introduced a variable to hold the state explicitly in Haskell quic.)

**Comment by martinthomson** [comment]
Entering recovery after slow start is correct.  The language in the draft was confusing.  Hopefully #4055 helps there.

**Comment by kazu-yamamoto** [comment]
> The language in the draft was confusing. 

Indeed...

**Comment by kazu-yamamoto** [comment]
After merging #4055, the pseudocode matches the language. Let's close this.

**Comment by martinthomson** [comment]
Let's leave this open until #4055 merges then.
