### ISSUE TITLE
Tokens are repeated in Initial packets

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4047]
This issue has a long and storied history.  We were originally of the view that only one packet needed to include a token (which you can see in the discussion of #1649).  However, the resolution of that issue in #1794 was very clear: every Initial packet needs to include a token.

That introduced a regression as it grouped the token with the connection ID, and we caught that in #1830.  However, the fix to that in #1929 reverted the token changes along with the connection ID changes.  Since then, this error has gone unnoticed.

Most people will have seen the stronger normative requirement [here](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-8.1.2-1):

> This token MUST be repeated by the client in all Initial packets it sends for that connection after it receives the Retry packet. 

To my knowledge, every implementation includes the token in every Initial packet, changing only when a Retry is received.  We should reconcile the text.

**Comment by marten-seemann** [comment]
> To my knowledge, every implementation includes the token in every Initial packet, changing only when a Retry is received. We should reconcile the text.

FWIW, that's what the interop runner tests for in the Retry test case.

**Comment by janaiyengar** [comment]
@marten-seemann : Yes, that's what sent us off on this chase :-)
