### ISSUE TITLE
When to reduce cwnd in recovery

### ISSUE THREAD

**Issue by mirjak** [quicwg/base-drafts#4050]
The recovery draft currently has the following text:

```
When slow start is exited, the congestion
window halves and the slow start threshold is set to the new congestion
window.
```

However, in https://tools.ietf.org/html/rfc5681#section-4.3 ssthresh is reduced upon entering recovery but cwnd is set to ssthresh when leaving recovery.

There is more discussion on this already in PR #3978 and PR #4005.

@ianswett proposed by email the following alternative wording:

```
MUST reduce the CWND to the ssthresh by the time recovery is exited and implementations MAY use a variety of mechanisms to reduce bytes in flight, including reducing it immediately, packet conservation, PRR(RFC6937) or decreasing the pacing rate.
```

@janaiyengar noted this text from RFC5861 which works as well:

```
   Second, until all lost segments in the window of data in question are
   repaired, the number of segments transmitted in each RTT MUST be no
   more than half the number of outstanding segments when the loss was
   detected.
```

**Comment by janaiyengar** [comment]
This discussion belongs in #3944, since #3978 hasn't been merged yet. Let's move this there.

**Comment by larseggert** [comment]
I'll close this one, since we have #3944
