### ISSUE TITLE
HTTP nitpick: checking for maximum Push ID

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#4052]
[Section 4.4 of the HTTP-29 I-D](https://tools.ietf.org/html/draft-ietf-quic-http-29#section-4.4) states:

```
   Server push is only enabled on a connection when a client sends a
   MAX_PUSH_ID frame; see Section 7.2.7.  A server cannot use server
   push until it receives a MAX_PUSH_ID frame.  A client sends
   additional MAX_PUSH_ID frames to control the number of pushes that a
   server can promise.  A server SHOULD use Push IDs sequentially,
   starting at 0.  A client MUST treat receipt of a push stream with a
   Push ID that is greater than the maximum Push ID as a connection
   error of type H3_ID_ERROR.
```

The case when the client has not sent a _MAX_PUSH_ID_ frame is not covered.  (In this case, the client should treat the receipt of any frame with a Push ID as an error.)

**Comment by LPardue** [comment]
There is some other text that kinda makes the error case:

```
  The maximum Push ID is unset when a connection is created, meaning
  that a server cannot push until it receives a MAX_PUSH_ID frame.
```

One interpretation is that since any value of ID is greater than `unset`, then the error condition holds. But I agree with Dmitri that we could probably make this clearer with some editorializing.

**Comment by dtikhonov** [comment]
> since any value of ID is greater than `unset`

That's a big stretch.  Does it hold in languages that have a `NaN`, such as JavaScript?  E.g., can one write `assert(0 > NaN);`?

**Comment by LPardue** [comment]
Since it starts as unset, and MAX_PUSH_ID can only increase the value then in this world, 0 must be greater than unset

**Comment by dtikhonov** [comment]
What is "unset?"  &lt;DmitriMode>If 0 is a valid value, then "unset" means `UINT64_MAX`, which is *not* smaller than 0.  That is, it is not true that `UINT64_MAX < 0`, which is what the text says.&lt;/DmitriMode>

**Comment by LPardue** [comment]
Sure, but then it makes it very hard to send a MAX_PUSH_ID that doesn't decrease the value. 

I think we agree that it would help the doc to fix your original nitpick.

**Comment by MikeBishop** [comment]
Unset is negative one?  The frame sets a `push_allowed` boolean?

I see a couple possible doc fixes.  The most minimal change is to simply state that it is also an error to receive anything that uses a Push ID if no MAX_PUSH_ID frame has been sent.  That's compatible and consistent with the intent of the current design.

Alternatively, we could define MAX_PUSH_ID to tell the recipient *how many* Push IDs they can use; 0 is the initial value, and sending 0 leaves push disabled.  That's consistent with QUIC's MAX_STREAMS et al. but would be a breaking change.

**Comment by dtikhonov** [comment]
I vote for the simplest approach:
> [...] state that it is also an error to receive anything that uses a Push ID if no MAX_PUSH_ID frame has been sent.

**Comment by LPardue** [comment]
+1 let's keep it simple

**Comment by martinthomson** [comment]
Editorial?

**Comment by dtikhonov** [comment]
Yes, this is an editorial issue.
