### ISSUE TITLE
Does HTTP spec mention all frames are flow controlled?

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4057]
In HTTP/2, only DATA frames are flow controlled. In HTTP/3, all frames are sent on STREAM frames, meaning that all frames are flow controlled. This is fine but it might bite people that make wrong assumptions, just like the differences in stream ordering would.

HTTP/3 appendix A provides Considerations for Transitioning from HTTP/2, and includes a section on Frame Types. So I expected to see some coverage about the flow control differences there but I did not.

I'm marking this as editorial because I don't want any change to HTTP/3. Just looking for some exposition.

**Comment by larseggert** [comment]
@LPardue it sounds like you know what text you would like to see. Maybe do a PR to help the editors out a bit? Since it's editorial, I see no COI.

**Comment by LPardue** [comment]
I'll prepare one soon.
