### ISSUE TITLE
Restructuring the QUIC packet header

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#406]
There are a large number of issues are around the packet header. The simplified/streamlined header proposed in PR 361 can address the following laundry list of issues:
#35: Starting packet number
#56: Extending flags
#119: Server-proposed connection ID
#133: Connection ID in version negotiation
#135: DoS using Version Negotiation Packets
#147: Reflection Attack Resistance
#185: Reliable identification of the initial packet for a connection
#193: Flags section is kind of confusing
#244: Need a NONCE in version negotiation packets
#293: Does the connection ID need to be in a consistent location
#295: Connection ID on a version negotiation packet
#148: QUIC packet header complexity
#170: Connection ID collisions

We may want to change the header further, but it would be good to have consensus on PR 361 as being a good way forward.

**Comment by martinduke** [comment]
I think this is a good step in the right direction.

@martinthomson Note that a lot of KEY_PHASE language in the TLS draft has to be revised.

**Comment by mnot** [comment]
Jana, all of those issues are either editorial or has-consensus. I don't think it's good to declare consensus on a specific PR, since that's effectively saying we have consensus on a set of bytes in the draft, rather than the ideas behind them.

**Comment by martinthomson** [comment]
Are we done with this issue yet?

**Comment by mnot** [comment]
Yes; marking as dup.
