### ISSUE TITLE
Generalizing QUIC to allow underlying tranports other than UDP

### ISSUE THREAD

**Issue by Ericson2314** [quicwg/base-drafts#4061]
In https://mailarchive.ietf.org/arch/msg/quic/fWbftfhTopjo6O2YjIZZwRQ92GM/ I questioned whether QUIC should be standardized requiring the underlying transport to be UDP.

The main thrust of my argument was that even assuming virtually QUIC usage in practice would be over IP, we might get a nicer RFC text by being somewhat open-ended and instead being forced to spell out the relevant properties of the underlying transport.

The response was mostly skeptical, but with just allowing that it might work out that I started an attempt in https://github.com/quicwg/base-drafts/pull/4043 

Since then, @MikeBishop brought up that other transports might actually be useful in practice, like:
 -  Message-based Websockets across an HTTP proxy
 -  Local datagram sockets for IPC

**Comment by janaiyengar** [comment]
Thank you for the intellectual exercise, @Ericson2314. Having seen the accompanying #4043, I'm convinced now that this is not a direction we should pursue, for at least two reasons:
- All implementers of QUIC today are doing this for UDP. Reading the text with the generalization makes it less concrete and, as @DavidSchinazi notes, less readable for the most common usage case that we are targeting with QUICv1.
- It is not clear to me what the driving use-case of such a generalization is, and therefore who benefits from this generalization.
- Without an implementation of it on a different underlying protocol, I'm wary that this would catch all the assumptions we've made.

When there is a need, it's easy enough to do a document that maps QUIC to a different underlying transport. Until then, this generalization seems unnecessary.

**Comment by Ericson2314** [comment]
I am a bit confused by the association with concreteness with legibility. To me, this sounds like saying "I prefer to read assembly than C because it's more concrete w.r.t. the machine code". A higher-level description to me better conveys concepts like purpose behind a mechnaism, which cannot in-general be recovered easily from the low-level description, and furthermore no low-level details are actually being removed (It's like C with an appending containing the disassembly, to continue my earlier analogy).

I do understand that a standard can be revised, and so only talking about UDP now doesn't prevent talking about other underlying transports later once they are tried out. But just that there is a risk of specifying the details of other transports without experience, there is the risk of ending up with a "non-portable" protocol that is much more tightly bound to UDP than intended. That can also be a difficult situation to recover from.

**Comment by DavidSchinazi** [comment]
Could you elaborate on how we might end tying QUIC too closely to UDP? I'm not sure I see how renaming things would help.

**Comment by martinthomson** [comment]
As @DavidSchinazi is likely one of the first people to want an abstraction, his opposition is worth paying attention to.

For me, this discussion highlights how abstractions aren't free.  They aren't free in terms of the time that I need to spend in order to review changes, then maintain them.  I appreciate that someone is willing to do the work to create the abstraction, but remember that you are asking editors to maintain that abstraction.  Other such "gifts" have turned out to be extremely expensive in the past as well.

People have talked about comprehension.  I think that the pull request demonstrates a small regression in comprehension.  That might be improved, but, to my previous point, that's not work that I was planning on doing.

Either way, I've taken a look at the work so far and the number of subtle errors makes me disinclined to accept the gift.

**Comment by janaiyengar** [comment]
> "there is the risk of ending up with a "non-portable" protocol that is much more tightly bound to UDP than intended."

QUIC was meant to run on UDP, and there was no intention to make this protocol portable in this working group. The first sentence of the [working group's charter](https://datatracker.ietf.org/wg/quic/about/) says: "The QUIC working group will provide standards-track specifications for a UDP-based, stream-multiplexing, encrypted transport protocol, based on pre-standardization implementation and deployment experience."

This suggests to me that building a portable version of QUIC is outside the scope of the working group.

**Comment by larseggert** [comment]
Thanks for the charter reminder, @janaiyengar. Given that, I am going to close this issue at this point, as we are certainly not going to be able to recharter before shipping v1.

**Comment by MikeBishop** [comment]
> One thing I noticed is that while most of QUIC is agnostic to the addressing format, the packet advertising the new address is rather not extensible, being isomorphic to `(Optional<(Ipv4, Port)>, Optional<(Ipv6, Port)>)` (in pseudo-Rust), rather than some sort tagged enum that would be more extensible.

That's a fair point; it's bound to the assumption of IP and some kind of port underlying it.  That said, it's also not core to the protocol -- an implementation that was addressed differently could simply define a parallel transport parameter that carries a different address type.  You're right that this might be made more generic by supplying a count-prefixed list of addresses, each of which contained an enum address type followed by a length-prefixed address blob; I don't think there's appetite for such generality when the alternative of a new TP type is cheap.

**Comment by Ericson2314** [comment]
I agree with all that. My example absolutely isn't a show-stopper, just the first example of the sort of thing that can crops up more easily with a UDP-specific text.
