### ISSUE TITLE
Move/duplicate no server migration text

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#4063]
9.6 says:

 >  Migrating a connection to a new server address mid-connection is left
   for future work.  If a client receives packets from a new server
   address not indicated by the preferred_address transport parameter,
   the client SHOULD discard these packets.

However, this is after several sections which describe how connection migration works generically from either side, including this text in 9.3.

>  Receiving a packet from a new peer address containing a non-probing
   frame indicates that the peer has migrated to that address.
   In response to such a packet, an endpoint MUST start sending
   subsequent packets to the new peer address and MUST initiate path
   validation (Section 8.2) to verify the peer's ownership of the
   unvalidated address.

Which is confusing and in fact arguably contradictory. I would propose that we add a sentence to the top of 9.3 that explains that while the text is generic, it actually only applies to servers.

**Comment by martinthomson** [comment]
Is this enough?

> This document limits migration of connections to new client addresses, except as described in Section 9.6. 

This appears in [the top of Section 9](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-9-6) (that's paragraph 6, not sub-section 6 in case you look at the URL).

**Comment by ekr** [comment]
It's not awesome because it basically contradicts the generic text in 9.3.
But maybe we're past the point of diminishing returns

**Comment by MikeBishop** [comment]
The intent was to keep the path validation mechanisms generic so that an extension could potentially introduce server migration later.  It's stated in 9.6 and the top of 9; before and after the generic part seems sufficient to me.  That said, I think the server migration extension would still require that the client be the one to actually make the change.  Only clients should ever spontaneously send from a new address.  (P2P scenarios notwithstanding....)

**Comment by larseggert** [comment]
@ekr do I read your last comment as you being OK with closing this with no action?

**Comment by ekr** [comment]
To be honest, I still think this could use some work, but I'm willing to let it drop.

**Comment by larseggert** [comment]
Thanks. Let's see if someone has energy/interest to do a PR during the next few days.
