### ISSUE TITLE
Can PATH_RESPONSE be sent on a different path than PATH_CHALLENGE?

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/base-drafts#4064]
Currently, [the Path Validation Responses subsection](https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-8.4) does not specify which path a PATH_RESPONSE needs to be sent over. That was somewhat surprising to me, as I had expected it to be scoped to the path that PATH_CHALLENGE was received on. If it isn't, could we add a sentence to the Path Validation Responses subsection to explicitly state that a PATH_RESPONSE is not scoped to a given path (and ideally explaining why it isn't)?

**Comment by martinthomson** [comment]
So I thought we were really crisp about this, but we were not.

PATH_RESPONSE does not need to follow the path on which PATH_CHALLENGE was received.  We're clear about this when it comes to preferred address handling, but there is some vestigial text that contradicts this.  That should be fixed.

**Comment by DavidSchinazi** [comment]
For the record, I personally believe that #4068 adequately resolves this issue while remaining purely editorial.

**Comment by martinthomson** [comment]
Thanks for being so prompt David.  I will leave this for a bit to allow others a chance to spot errors, but I plan to merge this before we publish -30 (real soon now, I hope).

**Comment by MikeBishop** [comment]
Yes, the requirement was removed but the inverse statement was never explicitly added.  #4068 corrects that.
