### ISSUE TITLE
Avoid generating overlapping CIDs?

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#4065]
This may be stupid and is definitely editorial, but should we provide advice for an endpoint to not do the following:

CID for connection 1: 0x34a3f036
CID for connection 2: 0x34a3f036a2
?

It would be crazy to do this intentionally, but if an endpoint randomly generates CIDs with differing lengths, it probably ought to catch the case, or otherwise implement trial decryption.

**Comment by larseggert** [comment]
I don't quite see the problem. In a long header, there is the CID length, so there is no confusion. In a short header, the implementation needs a way to derive the CID length implicitly, e.g., by only using one length or through some other means. That means an implementation can always distinguish the two? In other words, when it can't, it's buggy.

**Comment by martinthomson** [comment]
@martinduke's example is clearly ambiguous, but I don't think we need to document it.  It's pretty clear that connections wouldn't survive very long if this happened.

**Comment by martinduke** [comment]
It can survive if the endpoint uses trial decryption, but point taken that this isn't important to write down.
