### ISSUE TITLE
Add warning about request forgery and client-side migration

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#4086]
I find Martin's argument that QUIC servers are able to control their topology well enough to prevent request forgery attacks somewhat persuasive. However:

1. I think the document should be clearer that if you can't do this you can't deploy QUIC as a server.
2. We should add text indicating that a candidate extension to allow migration by the client would need to deal with this (likely by adding one of the countermeasures we decided not to ass). This is a very long specification and otherwise the institutional knowledge about this issue is likely to be lost.

**Comment by ekr** [comment]
If people agree, I can provide PRs for these.

**Comment by martinthomson** [comment]
These sound like good additions that I would welcome.  (I would write the PR, but I don't trust myself, I'd appreciate you providing text.)

**Comment by LPardue** [comment]
Sounds like a good path forward.

**Comment by MikeBishop** [comment]
> 2. We should add text indicating that a candidate extension to allow migration by the client would need to deal with this (likely by adding one of the countermeasures we decided not to ass). This is a very long specification and otherwise the institutional knowledge about this issue is likely to be lost.

Do you mean migration by the server?

**Comment by ekr** [comment]
I'm not clear on the grammar, but I mean "the server address changing"

**Comment by MikeBishop** [comment]
FWIW, when we've talked about a server migration extension before, it was usually in the form of a frame that mimics the preferred_address TP, prompting the client to probe the new address and actually make the change.  That approach seems like it limits the attacks to those already possible with SPA, though it broadens the window / number of attempts.

**Comment by larseggert** [comment]
Could people take a look at the PR? Would like to move this along.
