### ISSUE TITLE
Is SCID  omitted in Retry Pseudo-Packet since draft tls-29 ?

### ISSUE THREAD

**Issue by Lingtaonju** [quicwg/base-drafts#4094]
As stated in the title,  I wander  whether this is a typo or there is some reason to omit scid?

![image](https://user-images.githubusercontent.com/19946268/93039393-f16ab780-f679-11ea-93b9-844b8d3abbcd.png)

**Comment by martinthomson** [comment]
Thanks for catching this.  It's an omission.  We had a similar error in other drafts, that was fixed, but copy-paste makes errors live longer than you might like.
