### ISSUE TITLE
Should invalid TP result in FRAME_ENCODING_ERROR?

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#4099]
I noticed this in the Transport Draft (ID-30):

```
   If a max_streams transport parameter or MAX_STREAMS frame is received
   with a value greater than 2^60, this would allow a maximum stream ID
   that cannot be expressed as a variable-length integer; see
   Section 16.  If either is received, the connection MUST be closed
   immediately with a connection error of type FRAME_ENCODING_ERROR; see
   Section 10.2.
```

Is this intentional?  Should an invalid transport parameter result in a frame encoding error?

**Comment by ianswett** [comment]
I believe this aligns with our principles that a framing error which can be detected with no connection context is a FRAME_ENCODING_ERROR.

Is there another error you'd suggest?

**Comment by dtikhonov** [comment]
My concern is that transport parameter values have nothing to do with framing and using _FRAME_ENCODING_ERROR_ is therefore misleading.

**Comment by marten-seemann** [comment]
> I believe this aligns with our principles that a framing error which can be detected with no connection context is a FRAME_ENCODING_ERROR.

We only ever applied this principle to frames though, so I'm not sure we can use it as a precedent here. The name is indeed confusing, as it's FRAME_ENCODING_ERROR and not FRAMING_ERROR or ENCODING_ERROR.

**Comment by larseggert** [comment]
I always rationalized this as "the encoded content of the CRYPTO frame is erroneous".

**Comment by dtikhonov** [comment]
Well, if we've been through this before, I won't insist -- it's just something that jumped out at me.

**Comment by marten-seemann** [comment]
> I always rationalized this as "the encoded content of the CRYPTO frame is erroneous".

That's even more confusing. The CRYPTO frame itself is totally fine. I'd be in favor of changing it to a TRANSPORT_PARAMETER_ERROR.
