### ISSUE TITLE
Update contributors' lists in acknowledgements sections

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4108]
For -31, we should check that the contributors' lists in the various acknowledgements sections are up-to-date. (I guess someone has a script for that?)

**Comment by martinthomson** [comment]
These are manually created.  But I've been tracking things.  I hope that other editors have also.

This might change once we get into a phase that involves wider review.  We'll have to pay more attention at that point.

**Comment by larseggert** [comment]
I'll leave this open as a reminder to the other editors, with the intent that this will then just close when -31 arrives.

**Comment by MikeBishop** [comment]
I have a one-liner to dump text contributors, but people make contributions in other ways as well.

**Comment by janaiyengar** [comment]
@MikeBishop : can you dump the one liner here?

**Comment by martinthomson** [comment]
I found this one:

```sh
git ls-files | xargs -n1 git blame --line-porcelain | sed -n 's/^author //p' | sort -f | uniq -ic | sort -nr
```

**Comment by MikeBishop** [comment]
Pretty comparable:  Mine was:

    git blame -w draft-ietf-quic-http.md | perl -n -e '/^.*?\((.*?)\s+[\d]{4}/; print $1,"\n"' | sort -f | uniq -c | sort -n

**Comment by janaiyengar** [comment]
We've done the due diligence, and we're good now.
