### ISSUE TITLE
Why do we talk about ECN validation in the chapter "Cryptographic and Transport Handshake"?

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#4109]
The sentence
> An endpoint verifies support for Explicit Congestion Notification (ECN) by
observing whether the ACK frames acknowledging the first packets it sends carry
ECN counts, as described in {{ecn-validation}}.

seems to not belong into that section.

**Comment by ianswett** [comment]
Assuming one enables ECN on Initial and Handshake packets in order to perform ECN validation, then I think it's the right place?

**Comment by larseggert** [comment]
@marten-seemann are you OK with @ianswett explanation, i.e., can we close with no action?

**Comment by marten-seemann** [comment]
Not really happy with it, tbh. The sentence feels completely out of place as it stands now. I think we should either move it to the ECN section (I think that would make the most sense), or at least add an introductory sentence, along these lines:
> Endpoints can use packets sent during the handshake to test for ECN ({{ref:ecn}}) support.

**Comment by larseggert** [comment]
I like the introductory sentence.
