### ISSUE TITLE
Invariants intoduction

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4118]
Issue raised by @gorryfair via [email](https://mailarchive.ietf.org/arch/msg/quic/nUyowuoahrCG1JgVt_APRgaw8ug):

> (i) I suggest the introduction for this spec starts abruptly. Is it worth considering one sentence top explain what QUIC is, in case someone read this document first? - One possible solution could be to move the text in section 3 to section 1? (To me, the section 3 text does not need to come after the Section 2 definitions.)

**Comment by martinthomson** [comment]
I like it.  I'll see what that looks like.
