### ISSUE TITLE
Rewording suggestion

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4119]
Issue raised by @gorryfair via [email](https://mailarchive.ietf.org/arch/msg/quic/nUyowuoahrCG1JgVt_APRgaw8ug):

> (ii) Does this read better with /for/ moved within the sentence?
OLD:/At the endpoint, the connection ID is used to identify which QUIC connection the packet is intended for./
NEW:/At the  endpoint, the connection ID is used to identify the QUIC connection for which  the packet is intended./

**Comment by martinthomson** [comment]
Sounds good.  I'll do that too.
