### ISSUE TITLE
cross-draft references

### ISSUE THREAD

**Issue by reschke** [quicwg/base-drafts#412]
Here's a nit: the drafts currently cite their sibling drafts in a way that doesn't conform to the applicable rules. For instance, in <https://tools.ietf.org/html/draft-ietf-quic-http-02#section-10.1> we have:

       [QUIC-TRANSPORT]
                  Iyengar, J., Ed. and M. Thomson, Ed., "QUIC: A UDP-Based
                  Multiplexed and Secure Transport".

That lacks the draft name, the publication date, and the mandatory "work in progress" clause.

Essentially, a newbie reader would have to do a web search for the document title.

**Comment by martinthomson** [comment]
We had an accidental regression that removed the data.  I originally thought that the other parts would be too hard, but it turns out that a small change is enough, see 76b0e2d and separately https://github.com/martinthomson/i-d-template/commit/f29bbb3bd353b7291b46e787ebf2147379b7f94d

**Comment by LPardue** [comment]
This change creates links that do not work, for example the [editors copy of HTTP/QUIC](https://quicwg.github.io/base-drafts/draft-ietf-quic-http.html#rfc.references.1) links to http://tools.ietf.org/html/draft-ietf-quic-transport-latest.

**Comment by reschke** [comment]
Use rfc2629.xslt and the problem goes away. Grin.
