### ISSUE TITLE
Is NOT appropriate

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4120]
Issue raised by @gorryfair via [email](https://mailarchive.ietf.org/arch/msg/quic/nUyowuoahrCG1JgVt_APRgaw8ug):

> (iii) I see the desire to emphasise the “NOT”, but I query if this is correct usage of a RFC2119 keyword in Appendix A?:
/The following statements are NOT guaranteed to be true for every QUIC
   version:/

**Comment by martinthomson** [comment]
It's NOT a 2119 keyword, just emphasis.  To be pedantic, 2119 doesn't reserve the use of all uppercase phrases.

I believe the emphasis to be especially important given that many of these statements are in fact true for QUIC v1.

**Comment by gorryfair** [comment]
That said - I'll let RFC-Ed agree/disagree on best style - this text a really important note, and simply writing NOT in capital letters maybe isn't the best way to call out this?

**Comment by larseggert** [comment]
Maybe SHOUT it? "ANY OF THE FOLLOWING STATEMENTS CAN CHANGE FROM VERSION TO VERSION:"

**Comment by larseggert** [comment]
I added a PR that tries to address this by rephrasing and highlighting stylistically. Not sure if this is better. I would actually suggest to just close with no action.

**Comment by gorryfair** [comment]
This is just editorial. Please consider my comment, and then just decide what is best.
