### ISSUE TITLE
advice on how to disable ECN is problematic when multiplexing multiple connections

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#4122]
The spec says:
> If validation fails, then the endpoint MUST disable ECN. It stops setting the ECT codepoint in IP packets that it sends, assuming that either the network path or the peer does not support ECN.

This is fine advice when a single QUIC connection uses a socket. When multiplexing multiple connections on the same socket, it won't be possible to disable ECN on a per-packet basis, unless you want to call `setsockopt` before every datagram that is sent.

**Comment by larseggert** [comment]
Not true. You can use ancillary data with `sendmsg` to specify ECN codepoints for each packet to be transmitted.

**Comment by marten-seemann** [comment]
Interesting, I didn't know that. I guess we can close this issue with no action then?

**Comment by larseggert** [comment]
I would think so.
