### ISSUE TITLE
it might not be possible to set the DF bit on all systems

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#4130]
> The QUIC packet size includes the QUIC header and protected payload, but not the UDP or IP headers

For example, OSX doesn't have an API to set this bit (allegedly this will change with Big Sur).
Furthermore, not all implementations might have access to an API that allows them to set bits in the IP header. If I remember correctly, this is one of the reasons we made ECN optional.

**Comment by larseggert** [comment]
I think you wanted to quote this part
> UDP datagrams MUST NOT be fragmented at the IP layer.  In IPv4
({{!IPv4=RFC0791}}), the DF bit MUST be set to prevent fragmentation on the
path.

Would a proposal be to make the MUST a SHOULD and say "unless this is not supported by the underlying OS"?

**Comment by marten-seemann** [comment]
Yes, that was a weird copy-paste error.
If we say "unless this is not supported by the underlying OS or the programming language" we can probably even keep the MUST.

**Comment by janaiyengar** [comment]
This is an editorial issue, since the intent of the MUST cannot be to require something that isn't possible.
