### ISSUE TITLE
ECN verification 3RTT period

### ISSUE THREAD

**Issue by tatsuhiro-t** [quicwg/base-drafts#4132]
https://tools.ietf.org/html/draft-ietf-quic-transport-30#section-13.4.2.1 and https://tools.ietf.org/html/draft-ietf-quic-transport-30#appendix-B describe ECN validation and they say :

> To reduce the chances of misinterpreting congestive loss as packets
   dropped by a faulty network element, an endpoint could set the ECT(0)
   codepoint for only the first ten outgoing packets on a path, or for a
   period of three RTTs, whichever occurs first.

Initial PTO timeout is also 3RTT.  If client does not get ACK for its first flight Initial, after 3RTT later, it resends Initial without ECT set because client is now in "UNKNOWN" state.
If the first client Initial is really lost, ECN validation fails.

It seems to me that it would be better to lengthen timeout or ensure enough packets are sent not limited by the timeout?

**Comment by marten-seemann** [comment]
It seems like this particular problem was introduced by reducing the initial RTT from 500ms to 333ms (in #3823).
