### ISSUE TITLE
Various small  text NiTs in transport

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#4144]
* Error?
/   A stateless reset is not appropriate for signaling error conditions./
- I understand, but this sentence seems odd to me, is it possible to say
 /error conditions when there is connection state/ or something like that? Is it worth a cross ref to section 11 to be clear what a “normal” error is?
* Section 9 NiTs in wording:
/Acknowledgments cannot be used for path validation as they contain insufficient entropy/
Acknowledgments cannot be used for path validation because they contain insufficient entropy/
/as endpoints independently determine reachability on each direction of a path./the endpoints  independently determine reachability on each direction of a path./
* Is it slightly easier to read:
/   One or more frames are assembled into packets./
/ One or  more frames are assembled into a QUIC packet./
* In section 3.3. It says: /The receiver of a stream sends MAX_STREAM_DATA (Section 19.10) and STOP_SENDING frames (Section 19.5)./
- Is this a para where ACK frames should also be mentioned? It seemed odd to me that ACKs are not mentioned at some pointy around here.

**Comment by martinthomson** [comment]
> A stateless reset is not appropriate for signaling error conditions.

I think that the intent is to be more general than just "this is not for connection errors".  How about:

> A stateless reset is not appropriate for indicating errors in active connections. An endpoint that wishes to communicate a fatal connection error MUST use a CONNECTION_CLOSE frame if it is able.

I don't think that we want to talk about acknowledgements at the level of the stream section.  They don't affect stream states and this is specifically about what stream-related frames can be sent.
