### ISSUE TITLE
Where is padding explained?

### ISSUE THREAD

**Issue by gorryfair** [quicwg/base-drafts#4145]
* I have a long comment on a scattered observation that could be very simple to fix: In section 6, it wasn’t clear what were the ways that "padding" could be performed. There could be various ways - simply leave UDP payload unused, fill it with coalesced QUIC packets, add padding and other frames, etc and when the text says this I think it’s unclear to me what is expected - any or all of these, but it doesn't seem to be said.
e.g.:
/Clients that support multiple QUIC versions SHOULD pad the first UDP datagram they send to the largest of the minimum datagram sizes from all versions they support. /
- Is the assumption here, more like:
/Clients that support multiple QUIC versions SHOULD coalesce QUIC packets or add PADDING frames to pad the first UDP datagram they send to the largest of the minimum datagram sizes from all versions they
support. /
… rather than some other technique to pad-out the datagram payload?
See also:
/Clients MUST ensure that UDP datagrams containing Initial packets have UDP payloads of at least 1200 bytes, adding padding to packets in the datagram as necessary.  A client that sends padded datagrams allows the server to send more data prior to completing address validation./
and later:
/In particular, an endpoint can pad a packet carrying a PATH_CHALLENGE for Path Maximum Transfer Unit (PMTU) discovery /
- So, I think the topic of padding needs a tiny bit more clarification - it’s almost there, but maybe a sentence that explicitly explains the permitted options in section 14 would be good, which could be cited rather than this scattered mention of “pad-out”

**Comment by DavidSchinazi** [comment]
Perhaps these mentions of the word "padding" just need to reference section 19.1. "PADDING Frames" ?

**Comment by gorryfair** [comment]
If that is all that is intended, we should say so.

**Comment by ianswett** [comment]
Agreed, I think the right phrasing is PADDING Frames, though I don't think we need to reference 19.1 in every spot we talk about PADDING frames.

**Comment by gorryfair** [comment]
So could we grep for Padding and ensure we say /PADDING Frame/? - I guess the REF first time used would be good - if not already there?

**Comment by gorryfair** [comment]
How about something like: PR #4148 ?

**Comment by martinthomson** [comment]
Closing now that we have #4148.
