### ISSUE TITLE
recovery-31 erronous references to external docs

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4176]
So there are a couple of section references in the doc that points the wrong section in other documents. 

- Section 6.2.1: "A sender SHOULD restart its PTO timer every time an ack-eliciting packet is sent or acknowledged, when the handshake is confirmed (Section 4.1.2 of [QUIC-TLS]), or when Initial or Handshake keys are discarded (Section 9 of [QUIC-TLS])", should that last ref be to section 4.9 in QUIC-TLS?"

- Section 6.4:  "see Section 4.8 of [QUIC-TLS])" This is now Section 4.9.

- Section B.2:  max_datagram_size: The sender's current maximum payload size. Does not include UDP or IP overhead. The max datagram size is used for congestion window computations. An endpoint sets the value of this variable based on its PMTU (see Section 14.1 of [QUIC-TRANSPORT]), with a minimum value of 1200 bytes." Should that Section 14.1 reference be to 14.2.

**Comment by janaiyengar** [comment]
Thank you for catching these, @gloinul.
