### ISSUE TITLE
Recovery-31: Initial Smoothed_RTT values

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4192]
In Section 5.3:

"When there are no samples for a network path, and on the first RTT sample for the network path:

smoothed_rtt = rtt_sample
rttvar = rtt_sample / 2

Before any RTT samples are available, the initial RTT is used as rtt_sample. On the first RTT sample for the network path, that sample is used as rtt_sample. This ensures that the first measurement erases the history of any persisted or default values."

First of all this text uses "rtt_sample" while other places with the exception of the pseudo code uses latest_rtt variable. There are two issues with that. First that the value of rtt_sample is state dependent. If there exist an latest_rtt then that is used, if not the initial rtt. As the initial RTT is defined in Section 6.2.2 I think a forward reference is in place. 

Finally, should this calculation in cases where latest_rtt exists be using min_ack_delay?

**Comment by gloinul** [comment]
I like to add that there are some structural issues in Section 6.2.1 and 6.2.2 where the initial value depends on both section.

**Comment by larseggert** [comment]
Based on #4213, labeling this as "editorial"

**Comment by gloinul** [comment]
The PR resolves this issue.
