### ISSUE TITLE
Recovery-31: PTO time MUST NOT be set and interaction with time threshold

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4193]
Section 6.2.1:

"The probe timer MUST NOT be set if the time threshold (Section 6.1.2) loss detection timer is set. The time threshold loss detection timer is expected to both expire earlier than the PTO and be less likely to spuriously retransmit data."

What does "MUST NOT be set" means. The time threshold loss detection 6.1.2 only occurs if there is acknowledgement received by the sender sufficient late after the transmission. Thus, PTO timer needs to always be set. because even if Time Threshold timer fires it might not declare a loss.

**Comment by ianswett** [comment]
It means if the time threshold timer is armed, you are not supposed to arm the PTO timer.

If the Time Threshold timer fires and doesn't declare a loss, then I would consider that a bug.

**Comment by gloinul** [comment]
So the above text about loss timer is only when one are under the condition created by this Section 6.1.2 sentence? 

"If packets sent prior to the largest acknowledged packet cannot yet be declared lost, then a timer SHOULD be set for the remaining time."

Does the formulation in 6.1.2 need to be improved, possibly naming the timer?

**Comment by ianswett** [comment]
I can see the confusion.  This can either be a single timer or multiple, and sometimes we refer to it one way and sometimes as separately named timers, ie "The time threshold loss detection timer"

We can either be more consistent about naming the timers or stop naming the timers entirely.  Would you prefer the former?

**Comment by gloinul** [comment]
Frankly I don't know which direction that is best. Could I ask you to take an editorial stab on your most preferred. I would guess when you sit down to do either you realize if it will work or not when you harmonize it.

**Comment by ianswett** [comment]
@gloinul Does PR #4222 resolve this for you?

**Comment by larseggert** [comment]
@gloinul we'd need a response, please

**Comment by gloinul** [comment]
Yes, that simple tweak do make it clearer. So resolved.
