### ISSUE TITLE
Recovery-31: Congestion control based on ACKs only to speed up?

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4194]
Section 7. 
 
 "Unlike TCP, QUIC can detect the loss of these packets and MAY use that information to adjust the congestion controller or the rate of ACK-only packets being sent, but this document does not describe a mechanism for doing so." 
 
So is there need to say anything that if one does this it needs to be adjusted in both directions, i.e. it is not okay to only use it to speed up, and not slow down.

**Comment by ianswett** [comment]
As it stands, the statement uses the neutral word 'adjust' which does not imply up or down.  I think this is appropriate and given this is more of a research project, I'd prefer to keep the text approximately as is.

**Comment by janaiyengar** [comment]
I agree with @ianswett. The sentence actually says what you want it to say, in that it doesn't specify a direction of adjustment.

**Comment by larseggert** [comment]
@gloinul do these explanations address your issue? Or are text changes required?

**Comment by gloinul** [comment]
Yes, lets close this issue.
