### ISSUE TITLE
TLS-31: Sending with Updated keys

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4199]
Section 6.4:

An endpoint always sends packets that are protected with the newest keys. Keys used for packet protection can be discarded immediately after switching to newer keys.

I do get confused by the first sentence reference to "newest" key. So the previous section talks about the requirement that one retain the current and next key. If one have created the next key, then that key is newest. I don't think this is intention, but the text can be interpret that one need to switch to the next key as soon as one is allowed if one have created it. The only question is when it is created. 

If I would guess the above section 6.4 sentence is to ensure that one never uses the previous key, if a key change has occurred. However, one should not be forced to switch to the next key unless the other side has switched or the key has exhausted its protection life time. 

However, I think the current formulation can result in that an outside attacker that can inject a packet with a toggled key-phase bit can force an endpoint to switch its key, even if the peer hasn't initiated a key update. This simply by forcing it to generate it, and then have the packet integrity check to fail for the injected packet. Because now there is a newer "next key" in store.

**Comment by martinthomson** [comment]
Never using old keys is a nice way of putting this.  I'll make that change.

**Comment by martinthomson** [comment]
On the last point (which I glossed over initially, as it relates to a different concept), the attacker can *at best* force the installation of the next set of read keys and only if the receiver is willing to do so.  Flipping the key phase bit has the effect of causing a receiver to select the previous or next read keys.  If the receiver generates keys on demand (which is not a great idea, but some implementations do...), then it will generate those keys.  That key generation should be a one-off event (we recommend saving keys in [S6.3](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#section-6.3-3)).

A bit flip cannot result in any change to any other state (other than the global anti-forgery counter, which is a recent addition).  Updates only occur as a result of successfully removing packet protection and a bit flip will cause the integrity check to fail and the packet to be dropped with no other state changes.

**Comment by larseggert** [comment]
@gloinul do these explanations plus 52c5f4f41bb1a1128af8f52398224cd2c9f83e45 address your issue? Or are further text changes required?

**Comment by gloinul** [comment]
Mostly, I think one could use the previous sections discussion of "current" and "next" to clarify this. 

For example:
OLD: An endpoint never sends packets that are protected with old keys.

New:
An endpoint never sends packets that are protected with old keys (previous key) only the current key.

**Comment by martinthomson** [comment]
I did that in #4224, but somehow it slipped the net and I failed to create the pull request.  Sorry about that.  I'll make the recommended change (or something like it).
