### ISSUE TITLE
Inconsistency in recovery-31 w.r.t. resetting PTO backoff factor.

### ISSUE THREAD

**Issue by ptrd** [quicwg/base-drafts#4200]
There is an inconsistency in https://tools.ietf.org/html/draft-ietf-quic-recovery-31 w.r.t. resetting PTO backoff factor. Section 6.2.1:

> the PTO backoff is not reset at a client that is not yet certain that the server has finished validating the client's address. That is, a client does not reset the PTO backoff factor on receiving acknowledgements until the handshake is confirmed;...

This suggests that for a client to be certain that the server has finished validating the client's address, the handshake should have been confirmed.

However, the pseudo code uses PeerCompletedAddressValidation to determine whether to reset pto-count and PeerCompletedAddressValidation also checks for Handshake ACK received. That is not what the text in 6.2.1 says, as, according to https://tools.ietf.org/html/draft-ietf-quic-tls-31#section-4.1.2, the handshake is confirmed when HANDSHAKE_DONE is received or when a 1-RTT ack is received. That is a subtle difference.

As kazu noted in the discussion on Slack, Sec 8.1 of QUIC says: "Once the server has successfully processed a Handshake packet from the client, it can consider the client address to have been validated.", so, the client can consider that the server validated the client address when either ACK in Handshake or HANDSHAKE_DONE in 1-RTT is received. (See Figure 5 of TLS.)  Hence, the pseudocode seems to be correct and that means the text in 6.2.1 should be corrected.

**Comment by ianswett** [comment]
Thanks for filing this, I think the new text is simpler anyway.
