### ISSUE TITLE
HTTP-31: HTTP/3 Connection definition?

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4206]
Section 2.2.:

"connection:
    A transport-layer connection between two endpoints, using QUIC as the transport protocol.
connection error:
    An error that affects the entire HTTP/3 connection."

In a total of 11 places this document uses "HTTP/3 connection". The word connection exists 213 times in this document (HTML version). So are there a difference between connection and HTTP/3 Connection, and if it is can that be clearly expressed. Else maybe alignment would be better.

Secondly, I think the above "connection" definition is likely missing one important aspect isn't it? I have the impression that an "HTTP/3" connection is a QUIC connection established with the purpose of communicating HTTP/3 over it. That intention is likely explicitly expressed at QUIC connection establishment using ALPN?

**Comment by gloinul** [comment]
So that pull request resolves the definition of the HTTP connection. Does the usage of HTTP/3 connection vs Connection in the document need adjustment? In other words, can you please check all the usage of connection if there is difference and if anywhere it needs to be clarified that it is not an HTTP/3 connection?

**Comment by larseggert** [comment]
Based on #4212, labeling this as "editorial"

**Comment by MikeBishop** [comment]
Having looked through the occurrences of "connection" in the document, I mostly think it's clear from context which type of connection we're talking about.  (It also helps that an HTTP/3 connection *is* a QUIC connection, and so it's rarely necessary to distinguish the two.)  I did a slightly aggressive pass in 2530b98, but I think I'm going to pare that down a bit.

**Comment by MikeBishop** [comment]
Okay, I've pushed a less-aggressive change as dae7b75e.

**Comment by gloinul** [comment]
Thanks @MikeBishop that commit appear good to me. I think with these changes this issue is resolved.
