### ISSUE TITLE
HTTP-31: All section references into [SEMANTICS] needs updating

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4207]
Looking into latest semantics (-12) https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-12.html for the section references none of the first couple I look at provides the right content.

7.3.3. doesn't exist, and is now likely 5.5.4
2.2 is likely 3.7
5.4.1.1 is likely 5.7.2
6.4 is might be 4.3. 
and so on.

So please go through all references to [SEMANTICS]. I would also check [HTTP11], [CACHING].

**Comment by MikeBishop** [comment]
Please see #4182.

**Comment by gloinul** [comment]
So, good that the fix are ongoing. I understand there was a bit of unfortunate timing here. However, this patch is necessary before the IETF LC can start.

**Comment by larseggert** [comment]
Based on #4182, labeling this as "editorial"
