### ISSUE TITLE
StreamID versus Stream ID

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#422]
I'm in favor of the space, but we should at least be consistent.

**Comment by RyanAtGoogle** [comment]
On Wed, Mar 29, 2017 at 12:18 PM, Mike Bishop <notifications@github.com>
wrote:

> I'm in favor of the space, but we should at least be consistent.
>
​Agree on both counts.

**Comment by martinthomson** [comment]
or "stream identifier"

**Comment by ianswett** [comment]
+1 to Stream ID
