### ISSUE TITLE
Transport-31: IANA Policy and change controller

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4230]
Section 22.1.1:

It is quite common that one may want to separate who has the change control over an registration entry vs who is the contact. Change control can often be assigned to an organization rather than an individual while a contact information may be an individual or a specific contact address for the organization. Contact information has a tendency to get stale, and in many case the contact if a person may no longer represent the organization that made the registration. 

Thus, my suggestion would be to add a separation between contact and change controller. In fact just for the registration in the Transport doc it makes sense to make the change controller "IETF" and have the contact be "QUIC WG".

**Comment by gloinul** [comment]
This also applies to permanent registrations in Section 22.1.4

**Comment by larseggert** [comment]
@gloinul does the PR address your issue?

**Comment by gloinul** [comment]
Change looks good and implements what I proposed.

**Comment by larseggert** [comment]
Labeling as "editorial" based on #4231
