### ISSUE TITLE
QPACK-18: Normative reference for RFC2360

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4243]
Section 1.2:

Diagrams use the format described in Section 3.1 of [RFC2360], with the following additional conventions:

This clearly is an normative reference to RFC2360, please change its classification.

**Comment by larseggert** [comment]
Agreed. Marking as "editorial".

**Comment by MikeBishop** [comment]
Given that the diagrams themselves are illustrative and the text governs, is the format used in the diagrams actually essential to correctly implementing the protocol?
