### ISSUE TITLE
Make TLS Optional

### ISSUE THREAD

**Issue by guilt** [quicwg/base-drafts#4260]
I want to indicate the presence of TLS as optional, especially for public / relay broadcast devices which do not require privacy as much as they could use lower power. Plus, there must be a way to let QUIC use an alternative as opposed to TLS, where need be.

**Comment by larseggert** [comment]
The QUIC working group is [chartered](https://datatracker.ietf.org/wg/quic/about/) to specify an always-encrypted protocol, and TLS1.3 is our default way to do so. There has been research work on replacing the TLS handshake with something else, but no standards work is chartered on that at the moment.

**Comment by guilt** [comment]
Why are you people asking for suggestions to the WG filed as issues if you are not open to the simplest possible way to implement UDP based transport? 

This is being asked for the IETF formalization and QUIC has, IMO, a real issue. Stop closing tickets without addressing why we need this.

**Comment by larseggert** [comment]
The working group **cannot** do standards work outside its charter. You are welcome and start a discussion on the mailing list on a potential recharter effort; a GitHub issue is not the place for this.

**Comment by gloinul** [comment]
@guilt The first 6 documents forming the core of QUIC and HTTP/3 are in IETF last call. This is near at the end of the publication process. The WG has done its work and designed a protocol and written its specification and thinks it is ready for publication. So the IETF last call is to determine the IETF consensus to publish the written specification and identify any remaining issues and determine if they required to be addressed now or not. 

As @larseggert said what you are proposing are outside of the charter. Yes, future versions of QUIC can be defined. But such work in IETF will require new chartering and establishment of sufficient interest in doing that standardization work.

**Comment by guilt** [comment]
@gloinul @larseggert Thank you for that explanation, I didn't realize that this was off the charter. However, I found that this was the only thing that could require worthwhile investigation. 

I always thought TLS was backported IMO based on its mandation in HTTP/2, and before the finalization, felt Quic could fix that problem by making sure the transport isn't enforced. I knew some people who had configured TLS_NULL_WITH_NULL_NULL to get around some of these issues and I didn't want things like that to get repeated, hence wanted a clear inversion of control: either always encrypted (privacy) or free (replay and stream broadcast)

**Comment by hardie** [comment]
Hi Karthik,

The history is somewhat different, and you may find it useful to refer to
some of the original design rational:
https://docs.google.com/document/d/1RNHkx_VvKWyWg6Lr8SZ-saqsQx7rFV-ev2jRFUoVD34/edit
.  As it notes, one of the key desires was to encrypt as much as possible:

Experience with SPDY development has taught us that the only way to prevent
> middleboxes from maligning a new protocol built atop UDP or TCP (e.g.,
> misconstruing it for a “known” protocol, and making “less than helpful”
> changes), is to encrypt as much of the payload and control structure as
> feasible.
>

So the choice not to provide an unencrypted variant goes back quite a long
way and was justified by arguments for privacy, data integrity, *and a
desire to avoid network-hosted middleboxes attempting to adjust the
protocol state machine*.

regards,

Ted Hardie

**Comment by guilt** [comment]
Hi Ted,

Thank you for the explanation. I just felt that the points on having middle systems and proxies currently exists today, with edge devices, CDNs, layer 7bload balancer and reverse proxies, and only ends up adding a layer of encryption and decryption at each step. While this is perfect for secrecy, it fails to account for the I numerous websites powering our internet, which are not single monolithic systems by themselves.

Besides, TLS itself relying on trusting the certificates of many providers including the government and some ISPs still makes it easier for a rogue actor to snoop on one's privacy today.

The other factors to ideally consider would be the time needed to recieve multiple wireless packets over the wire and enable decryption them, preferably with quantum resistant curve algorithms (or some such) which only amplifies the amount of money thrown at the problem, not necessarily enabling more people to use this otherwise well engineered protocol.

Hence I made the suggestion was to make it optional, and that the people who will perform the complete deployment of a system may choose the right points to enable the usage of such privacy, as need rises.

 I know this wasn't the original design goal, hence I request the folks to consider,possibly for the future, having a way to define this mechanism in the wire.

**Comment by LPardue** [comment]
This thread is outside the scope of the QUIC WG. I'm now locking it.
