### ISSUE TITLE
Initial timeout in path validation failure

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4261]
[Section 8.2.4](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-failed-path-validation) says "initial timeout (that is, `2*kInitialRtt`)".  But I don't think that we have this initial timeout concept in recovery any more; we [just use the PTO](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#section-6.2.2-1).  Should this just be `3*PTO` now?  The result is that the `6*kInitialRtt` is meaningless as the PTO is `3*kInitialRtt + max_ack_delay` when initialized.

Or is this the PTO on the pre-existing path?

**Comment by kazuho** [comment]
> Or is this the PTO on the pre-existing path?

I think this is the case. Notice "current."

Therefore I belive that the formula should be `max(3*current_PTO, 3*initial_PTO)`.

**Comment by ianswett** [comment]
Changing 2*kInitialRtt to 3*kInitialRtt and 6*kInitialRtt to 9*kInitialRtt seems like the simplest fix since we don't define an initial_PTO variable anywhere in the documents.

**Comment by kazuho** [comment]
I assume that the choice between #4262 and #4263 is purely editorial. Either works for me.

**Comment by janaiyengar** [comment]
I prefer #4263 with some changes that I've noted on the PR.
