### ISSUE TITLE
Fundamentals into Section 1

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4265]
Section 1 provides an ultrafast introduction to the problem, and very little on
the fundamentals of how the protocol works. It would be useful if there a
process by which the reader is gradually immersed in the detail.

**Comment by MikeBishop** [comment]
That is, in fact, the intended structure of the document.  Section 1 provides an extremely high-level view of the protocol; section 1.1 lays out how these high-level concepts are discussed in greater depth in Sections 2-14, with wire-level details reserved for Sections 15-20.

Is the suggestion that there should be a new Section 2 which goes into more detail than Section 1, but less detail than Sections 2-14?  Or is the suggestion more detail in Section 1.1 about the concepts before the forward references?

**Comment by janaiyengar** [comment]
What @MikeBishop said above. The draft is already super long, so while we can make additions for clarity, I'd want to keep it as short as possible.

**Comment by StewartBryant** [comment]
Adding the text in a new section 2 would be a good idea.

Whilst the draft is long, it has to be readable by readers that are not yet experts on the protocol. 

My overall impression during my review was that it was a draft written by people that understood the protocol for people that understood the protocol, but the target audience for a major new IETF transport protocol is much wider than that.

It is also the same with the very abbreviated text on some important design decisions. This is fine whilst the original designers are around, but the work has a lifetime longer than the participation lifetime of the original designers, and a few words now save a lot of discussion and more importantly mistakes and complexity as the design is developed, possibly decades in the future.
