### ISSUE TITLE
Clarify frames and packets in Section 1

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4266]
Section 1 is the first place that you introduce the term "Frame". I got very
confused about frames and packets, and I thing the taxonomy needs to be clearly
explained. You have UDP/IP packets that carry one or more QUIC PDUs, but the
frame/packet notation made it unclear what was being discussed and whether the
terms were being used consistently. Some clarification would be useful, or if
it is in the text then making it more obvious would help.

**Comment by MikeBishop** [comment]
Perhaps "Frame" should be added as a defined term in Section 1.2.
