### ISSUE TITLE
Looking for a protocol definition

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4267]
>  Packet and frame diagrams in this document use a custom format.  The
  purpose of this format is to summarize, not define, protocol
  elements.

I found this confusing, because in a ST protocol specification I was
looking for a protocol definition

**Comment by MikeBishop** [comment]
The protocol definition is the text; the diagrams are helpful summaries of the text.

**Comment by martinthomson** [comment]
For the benefit of others, who might struggle with "ST", like I did.  "ST" == standards-track.

I don't know what sort of protocol definition is contemplated here.  There is RFC 4101, I guess.

If you look at that, the information RFC 4101 suggests be included is there already.  The introduction lays out the actors involved and what they hope to do and how they do it in general terms.  And the handshake section (7) shows some example handshake exchanges.

As for the use of diagrams, what Mike said applies.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
