### ISSUE TITLE
62 bits pulled out of a hat

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4268]
>  Streams are identified within a connection by a numeric value,
  referred to as the stream ID.  A stream ID is a 62-bit integer (0 to
  2^62-1) that is unique for all streams on a connection.

I found the 62 bits pulled out of a hat very confusing. Eventually the
reader realises that this is 64 bits with the two lowest bits  signifying the
parameters below.    Some explanatory text would help.

**Comment by MikeBishop** [comment]
That's an incorrect reading.  They are **62**-bit integers with the lowest two bits signifying the parameters which follow.  Variable-length integers (Section 16) have a maximum size of 62 bits.  The sentence immediately after the ones you quoted states that stream IDs are variable-length integers, with a reference to the variable-length definition.

**Comment by martinthomson** [comment]
What Mike says.  The inference that stream identifiers are encoded as variable-length integers is - I hope - obvious enough not to require explicit text.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
