### ISSUE TITLE
Text around table 1 confusing

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4270]
When I read the text around table 1, I found this to be confusing and was
not clear whether the object is a 64 bit object with a 62 bit instance ID or a
62 bit object with a 60 bit instance ID. If the former I am not sure what the
name of the whole is vs the name of the 62 bit instance ID is. This could
usefully be clarified.

**Comment by MikeBishop** [comment]
This appears to be a duplicate of #4268.  The whole is a 62-bit ID, and there is not a defined term for the 60-bit portion.

**Comment by martinthomson** [comment]
Mike is right.  Closing this in favour of #4268.
