### ISSUE TITLE
Again unclear

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4272]
>  Any maximum datagram size larger than 1200 bytes can be discovered
  using Path Maximum Transmission Unit Discovery (PMTUD; see
  Section 14.2.1) or Datagram Packetization Layer PMTU Discovery
  (DPLPMTUD; see Section 14.3).
>
>  Enforcement of the max_udp_payload_size transport parameter
  (Section 18.2) might act as an additional limit on the maximum
  datagram size.  A sender can avoid exceeding this limit, once the
  value is known.  However, prior to learning the value of the
  transport parameter, endpoints risk datagrams being lost if they send
  datagrams larger than the smallest allowed maximum datagram size of
  1200 bytes.

Again unclear. Are you saying that the network must support a network layer
packet of at least 1200B which is used to carry Ip + UDP + UDP payload?

**Comment by martinthomson** [comment]
I think that the response to #4271 addresses this one and this should be closed with no action.

**Comment by LPardue** [comment]
Closing due to #4271 being addressed and closed
