### ISSUE TITLE
Re-writing for clarity

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4273]
>  UDP datagrams MUST NOT be fragmented at the IP layer.  In IPv4
  ([IPv4]), the DF bit MUST be set if possible, to prevent
  fragmentation on the path.
>
>  Datagrams are required to be of a minimum size under some conditions.
  However, the size of the datagram is not authenticated.  Therefore,
  an endpoint MUST NOT close a connection when it receives a datagram
  that does not meet size constraints, though the endpoint MAY discard
  such datagrams.

I really think this section needs re-writing for clarity.

**Comment by martinthomson** [comment]
I find this text perfectly clear, so I will need help in identifying in what ways the text lacks clarity.
