### ISSUE TITLE
Only packet you can trust to explore the path is a QUIC packet

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4274]
>14.2.1.  Handling of ICMP Messages by PMTUD

I am worried about the text in this section. ICMP and UDP paths may not be
congruent as a result of different RTG ECMP treatment. The only packet you can
trust to explore the path is a QUIC packet.

**Comment by MikeBishop** [comment]
Can you expand on the worry?  The section doesn't use ICMP to explore path sizes, only defines reactions to ICMP notifications of dropped packets.  Further, "don't trust ICMP" seems to be exactly what it says:

> An endpoint MUST NOT increase PMTU based on ICMP messages; see Section 3, clause 6 of [DPLPMTUD]. Any reduction in QUIC's maximum datagram size in response to ICMP messages MAY be provisional until QUIC's loss detection algorithm determines that the quoted packet has actually been lost.

**Comment by martinthomson** [comment]
@StewartBryant, can you help here?

**Comment by janaiyengar** [comment]
This might have been a mis-read of the text. The suggestion of using QUIC packets to explore the path is precisely what the text suggests. Propose closing with no action.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel.

Hearing no pushback, I'm closing this.
