### ISSUE TITLE
Ask IANA to run an algorithm 

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4276]
>  Additionally, each value of the format "31 * N + 27" for integer
  values of N (that is, 27, 58, 89, ...) are reserved and MUST NOT be
  assigned by IANA.

We do not normally ask IANA to run an algorithm to check a value. Are we
sure that this will work?

**Comment by MikeBishop** [comment]
I'm sure we'll find out in the IANA review.  Is the suggestion here that we should request a pre-review by IANA?

**Comment by martinthomson** [comment]
I don't think that this issue is actionable.  As Mike says, we'll find out.

**Comment by gloinul** [comment]
So IANA will do an last call review of the IANA consideration section so hopefully they will provide it in time to help settle this issue. I will ask IANA where they are on these reviews.

**Comment by gloinul** [comment]
IANA has promised they will provide a IETF last call review before the deadline expires.

**Comment by LPardue** [comment]
Covered under the IANA reviews. Closing this.
