### ISSUE TITLE
Error states missing

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4277]
In looking at  "Figure 2: States for Sending Parts of Streams" it occurred
to me that this was the major states but there were possibly a number of error
states missing. It would be useful to clarify.

**Comment by MikeBishop** [comment]
Errors result in closing the connection, at which point the streams no longer have a state.

**Comment by martinthomson** [comment]
I think we'd need something more concrete for this to be actionable.  As this state machine has been implemented a number of times now, I don't believe that we've missed any states.

And, as Mike says, many error states are not relevant as genuine errors result in the connection closing.  Of course, there are far fewer concrete errors than you might first think.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
