### ISSUE TITLE
Prevent the network from being overwhelmed

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4278]
>  It is necessary to limit the amount of data that a receiver could
  buffer, to prevent a fast sender from overwhelming a slow receiver,
  or to prevent a malicious sender from consuming a large amount of
  memory at a receiver.

Surely it is also necessary to do this to prevent the network from being
overwhelmed?

**Comment by marten-seemann** [comment]
The quote is from the Flow Control section. I see flow control and congestion control as orthogonal to each other.

**Comment by martinthomson** [comment]
Yes, there are multiple defenses that QUIC employs.  This is about preserving endpoint memory resources.  There is a whole document on what we do to preserve the network.

Not seeing an action here.

**Comment by igorlord** [comment]
Technically, endpoint is just another device on path to the application that should not be overwhelmed. Regular congestion control without connection-level flow control would had been sufficient. However, transport can signal much more effectively about endpoint's state, so connection flow control is a special case congestion control optimization.

This description is about the flow control.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
