### ISSUE TITLE
Pulling of 2^60 out of a hat 

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4279]
>  If a max_streams transport parameter or a MAX_STREAMS frame is
  received with a value greater than 2^60,

This pulling of 2^60 out of a hat is too cryptic. As I understand it this
is because you need 2 bits to express the size of the object that holds to
identifier and two bits to hold the control parameters that go in the LSBs. It
would be helpful to the new reader to call all this out earlier rather than
making them figure it all out.

**Comment by martinthomson** [comment]
I don't think that the length of the necessary explanation is worth the effort, but would be happy to see a suggestion for text.

**Comment by StewartBryant** [comment]
Please remember that you are addressing the comment from the perspective of an expert that wrote it, but the spec will be read by many people that need to understand it from scratch.

**Comment by larseggert** [comment]
The full sentence referred to is
> If a max_streams transport parameter or a MAX_STREAMS frame is
   received with a value greater than 2^60, this would allow a maximum
   stream ID that cannot be expressed as a variable-length integer; see
   Section 16. 

The second part of that sentence is already explaining the limit. I think we can close this with no action.

**Comment by martinthomson** [comment]
Good point. In context, this seems adequate.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel.

Hearing no pushback, I'm closing this.
