### ISSUE TITLE
0x?a?a?a?a is somewhat pulled out of a hat

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4281]
> For a server to use a new version in the future, clients need to
  correctly handle unsupported versions.  Some version numbers
  (0x?a?a?a?a as defined in Section 15) are reserved for inclusion in
  fields that contain version numbers.

The value 0x?a?a?a?a is somewhat pulled out of a hat, it would be useful to
explain the rational. SB> and then in Section 15 I wondered why this pattern
which leaves all sorts of holes in the version space?

**Comment by MikeBishop** [comment]
The point of GREASE is that the values be easy to generate, but not clustered in the space (and thus more easily coded for).  We used this pattern because it had already been successfully used in TLS for four-byte spaces.  See RFC 8701.

**Comment by martinthomson** [comment]
I don't plan to do anything with this feedback.  Like other questions we've received, this doesn't really warrant an explanation.

**Comment by StewartBryant** [comment]
That is a perspective of one of the experts that wrote the spec, rather than a new reader of the spec.

One way of addressing this is to include a reverence.

**Comment by ekr** [comment]
I agree with MT here. We don't need to document every design choice.

**Comment by DavidSchinazi** [comment]
+1 to @ekr and @martinthomson. If we start documenting every single decision we're going to end up with a document that's so long it's completely unreadable

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
