### ISSUE TITLE
Congestion consequences of CRYPTO buffering

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4282]
>  Implementations need to maintain a buffer of CRYPTO data received out
  of order.  Because there is no flow control of CRYPTO frames, an
  endpoint could potentially force its peer to buffer an unbounded
  amount of data.

What are the congestion consequences of this?

**Comment by martinthomson** [comment]
As @marten-seemann says, this buffer only matters to the extent that it consumes storage.  In order to send this data, the congestion controller will have to allow sending, but this is entirely orthogonal.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
