### ISSUE TITLE
What units of time you are using

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4283]
>     validation_timeout = max(3*PTO, 6*kInitialRtt)

A quick look in the reference did not show what units of time you are using
in the protocol - maybe I missed it?

**Comment by marten-seemann** [comment]
`kInitialRtt` is set to 333ms. Not sure why a max between two values needs to define the unit in the first place though.

**Comment by larseggert** [comment]
`kInitialRtt` is not defined in -transport, and Stewart was (probably) only reviewing the document in isolation.

**Comment by MikeBishop** [comment]
@marten-seemann, a max needs to ensure both values use the same units.  But provided that they do, I agree.

**Comment by kazuho** [comment]
Maybe it's easier to say that these are all physical quantities, or numbers with units. In the specification, we use seconds, milliseconds, microseconds. That's fine, because we know how to align the units when we make calculations (e.g., max).

**Comment by martinthomson** [comment]
PR #4263 proposes removing the text in question.  Of course, it doesn't matter what time units are in use in this case.  I'm fairly confident that where units matter (i.e., we base the value on a constant), the units are explicit.  Here, the units are part of the definition of the variables.

**Comment by LPardue** [comment]
As Martin points out, the offending text was removed. Not seeing anything to be done here , so I'm closing the issue.
