### ISSUE TITLE
Pointer to a packet definition

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4284]
>  Stateless Reset {
    Fixed Bits (2) = 1,
    Unpredictable Bits (38..),
    Stateless Reset Token (128),
  }
>
>                    Figure 10: Stateless Reset Packet

When I first met this my reaction was that  I was sure it sends a lot more
bits on the wire than this, but so far I have not see a packet definition nor a
pointer to a packet definition.  Please could you clarify what is happening?

**Comment by martinthomson** [comment]
This seems like a nit.  I guess the only thing being that this is the first time the notation introduced in Section 1.3 is used.  And now it is Section 10.3.  I'll add a cross reference.
