### ISSUE TITLE
We do not know what a packet looks like

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4285]
>10.3.1.  Detecting a Stateless Reset
>
>  An endpoint detects a potential stateless reset using the trailing 16
  bytes of the UDP datagram.

I find this rather opaque given that so far we do not know what a packet
looks like, and I cannot see what the encoding of this is.

To add to the confusion over packets and frames we now have datagrams.

**Comment by martinthomson** [comment]
The encoding of a packet is specifically not relevant at this point.  I think that the question is whether it is reasonable to expect that readers have internalized [this paragraph](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-1-7):

> Frames are used in QUIC to communicate between endpoints. One or more frames are assembled into a QUIC packet. QUIC authenticates all packets and encrypts as much as is practical. QUIC packets are carried in UDP datagrams ([UDP]) to better facilitate deployment in existing systems and networks.

There is a reasonable criticism here in that the level of detail in the stateless reset description is too much too early.  It would be nicer if some of the more detailed stuff here were deferred until later.  Unfortunately, it is hard to extricate this from the other more generic stuff in Section 10.

So I'm not seeing any real way to improve this without making things worse in other ways.
