### ISSUE TITLE
Non-reusable number space

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4287]
>12.3.  Packet Numbers
>
>  The packet number is an integer in the range 0 to 2^62-1.

It would save a bit of wondering until later if this was described as a
non-reusable number space

**Comment by martinthomson** [comment]
I think that [this text](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-12.3-10) is sufficient:

> A QUIC endpoint MUST NOT reuse a packet number within the same packet number space in one connection.

It's not at the top of that section, but it isn't the most important thing to know either.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel.

Hearing no pushback, I'm closing this.
