### ISSUE TITLE
Say we have a maximum data size

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4288]
>  A QUIC endpoint MUST NOT reuse a packet number within the same packet
  number space in one connection.  If the packet number for sending
  reaches 2^62 - 1, the sender MUST close the connection without
  sending a CONNECTION_CLOSE frame or any further packets; an endpoint
  MAY send a Stateless Reset (Section 10.3) in response to further
  packets that it receives.

 I know that this is a lot of space, although you subdivide it so its
smaller, but I would be useful is the fact that there was a maximum data size
was stated up from and it was specified. There are some applications that
expect to send continuously without disruption and would need to take action
prior to termination of the transfer.

**Comment by MikeBishop** [comment]
How are the packet number spaces subdivided?  But yes, there are some absolute limits that it might be useful to mention earlier.

**Comment by martinthomson** [comment]
I think that the packet number spaces caused a little confusion here: they multiply the number of packets (in theory, in practice they just add a small fixed number).

It's good systems design to be prepared to lose fragile resources like connections, so I'm very happy that packet numbers eventually run out.  I would almost have been happier with a lower limit, but this is where we ended up.

BTW, the connection flow control limit is more likely to be the limit that applications hit (at least if you don't consider DATAGRAM).

**Comment by martinthomson** [comment]
Proposing no action here.

**Comment by janaiyengar** [comment]
I don't think we can come up with a maximum data limit, since:
- packet numbers apply to packets, not to bytes (unlike in TCP)
- each packet is sized based on MTU,
- even theoretically, there are various control frames that need to be sent for protocol operation, which take away from any byte limit that we come up with.

I expect that we can do an approximate maximum (2^62 * MTU = 4.6 * 10^18 * MTU), which will have no practical value to an application.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
