### ISSUE TITLE
Choice of padding values

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4295]
> 19.1.  PADDING Frames

The choice of padding values is itself an interesting problem, but as far
as I can see the text is silent on the subject.

**Comment by MikeBishop** [comment]
I don't understand this comment.  The text is silent because there is no choice of padding values -- PADDING frames have a defined frame type and no content.

**Comment by martinthomson** [comment]
I believe that this is raising the known-difficult problem of knowing when and how much to pad.  That is something that other documents have addressed by saying "we provide the tools, but don't show you how to use them".  That is absent here, so this is a fair criticism.

**Comment by janaiyengar** [comment]
I don't read the comment as being about the amount of padding, and so I have the same question as @MikeBishop, but the clarification in #4312 is a welcome addition. I think the PR addresses the addressable part of this issue.
