### ISSUE TITLE
Example Structure

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4298]
"Example Structure"

The use of white space coupled name components was strange to me and  it
too a while and a look late in the text to realise that Structure was part the
name and not part of the syntax (i.e. that a structure was not Structure {})

**Comment by MikeBishop** [comment]
Perhaps simply "Example" there?

**Comment by martinthomson** [comment]
As we use whitespace in other places, not including whitespace in the example could cause problems later.  I think that this is a consequence of trying to read these diagrams too closely, that's all.  I would be opposed to any change here.

**Comment by StewartBryant** [comment]
A more conventional approach would be s/Example Structure/Example_Structure/ (use underbar of hyphen or use capitals as in ExampleStructure so there is no ambiguity. This of course applies to all instances of names like this. 

This is about making it easy for the reader, who should be able to read these examples using conventional notation. They can and will study them in detail in the future.

**Comment by janaiyengar** [comment]
I would push back against changes here. This is a matter of what one is used to, but given a moment, any careful reader will figure this out (as Stewart did).

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel. 

Hearing no pushback, I'm closing this.
