### ISSUE TITLE
Conversion pseudo code would be helpful

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4300]
>                  Table 4: Summary of Integer Encodings
>
>  For example, the eight byte sequence c2 19 7c 5e ff 14 e8 8c (in
  hexadecimal) decodes to the decimal value 151288809941952652; the
  four byte sequence 9d 7f 3e 7d decodes to 494878333; the two byte
  sequence 7b bd decodes to 15293; and the single byte 25 decodes to 37
  (as does the two byte sequence 40 25).

The
Some hex & decimal indication would help.
A picture is worth a thousand words and save the reader drawing this out
themselves to understand it and getting confused. The conversion pseudo
code would be helpful, possibly in an appendix.

**Comment by martinthomson** [comment]
I don't think that any change is needed here.  It says "in hexadecimal" and "decimal value" right there.

**Comment by MikeBishop** [comment]
We could put comma separators in the decimal values (i.e. 494878333 => 494,878,333) so they're more readily parsed as decimals rather than digit sequences.  And an appendix with a varint decoder might not be the worst idea.
