### ISSUE TITLE
Advice for middlebox authors

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4305]
Reviewer: Yoav Nir
Review result: Ready

The contents of the "security and privacy considerations" section seems to be
advice for middlebox authors. I think that it may have been better to name the
section something else.  However, there is no information that is missing, so I
don't really have any recommendations for changing things.

**Comment by larseggert** [comment]
Opening this in case we want to make editorial changes.

**Comment by martinthomson** [comment]
I understand the concern, but of the options I can think of, doing nothing seems best.

I considered:
1. Moving this text to Section 2 (and removing the redundant point to the appendix)
2. Moving this text to a new section entitled "Middlebox Considerations" or some such
3. Doing nothing

I think we can justify this on the basis that these can be thought of as attacks.  Maybe not on the protocol, or specific deployments of it, but on the ability of the protocol to evolve.  Critically, these are attacks that this draft does not protect against.

**Comment by janaiyengar** [comment]
Agreed. It's worth noting that this isn't a protocol document, this is documenting the unchanging aspects of the protocol. Section 1 says "The primary goal of this document is to ensure that it is possible to deploy new versions of QUIC."

Given that, it's reasonable to argue that the security considerations apply to the evolvability of QUIC.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel.

Hearing no pushback, I'm closing this.
