### ISSUE TITLE
Specify what concurrent stream limit protects

### ISSUE THREAD

**Issue by siyengar** [quicwg/base-drafts#432]
Following up on the mailing list discussion, filing an issue so that this doesn't get lost. It's not clear from the draft what the concurrent stream limit actually protects. I don't think the current mechanism protects what I think we want it to protect, i.e. the stream state table and the retransmission buffer, however once we specify what we want to protect we can maybe come up with a solution for this.

**Comment by martinthomson** [comment]
I think that it does protect something, but we should discuss that.  In the mean time, you should take a look at #263 and in particular https://github.com/quicwg/base-drafts/issues/263#issuecomment-278041662 to get an idea of how this might work.

On your examples, retransmission buffers aren't a resource that we need to protect (if you don't want to create those buffers, don't send anything).  However, stream states aren't protected in the same way: you are right to observe that much of the protocol state exists outside of the direct control of QUIC in a way that QUIC can't help.

**Comment by martinthomson** [comment]
Closing based on https://github.com/quicwg/base-drafts/issues/419#issuecomment-295558369
