### ISSUE TITLE
transport: error connection of what

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#4347]
I'm checking "MUST treat" in the transport draft. Sec 17.2.4 says:

> Handshake packets MAY contain CONNECTION_CLOSE frames of type 0x1c. Endpoints MUST treat receipt of Handshake packets with other frames as a connection error.

This is only the place where the type of a connection error is NOT specified. This part should be modified as "a connection error of XXX".

**Comment by martinthomson** [comment]
This was deliberate, but you can now send CONNECTION_CLOSE in this case, so it makes sense to use a code here.
