### ISSUE TITLE
transport: a frame of unknown type

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#4348]
Sec 12.4 says:

> An endpoint MUST treat the receipt of a frame of unknown type as a connection error of type FRAME_ENCODING_ERROR.

I don't understand why a frame of unknown type MUST be treated as a connection error. Other unknown stuffs are just ignored. In the spirit of greasing, I think that a frame of unknown type is also just ignored.

**Comment by LPardue** [comment]
In order to decode QUIC packets you need to know the length of all the frames inside them. An unknown frame is likely to have an unknown length. Requiring all frames to have a length field is an overhead that we didn't want to pay.

**Comment by kazu-yamamoto** [comment]
Good point. Thanks.

But my point is why MUST? What about "MAY"?

**Comment by LPardue** [comment]
The rationale is explained a bit more in section 19.21. But really this is simply one of those cases where the peer is behaving in a way that violates a core contract of the protocol, I don't see any benefits that a MAY would allow. Better to fail fast and fail hard.

**Comment by kazuho** [comment]
Aside from what @LPardue pointed out, one of the practical issues are that the receiver cannot decode frames that might exist after the unknown one.

If the receiver acks the packet that carried an unknown frame, the sender might not retransmit the frames that followed the unknown frame. If the receiver does not ack the packet that carried the unknown frame, then the sender might continue retransmitting that frame.

Either ways, the connection gets stuck.

**Comment by martinthomson** [comment]
This is a fine question, but I don't see any need for changes. 

To add to the reasons, btw, if frames preceding the unknown one are processed, and frames after aren't, you both have to acknowledge and can't acknowledge the packet. At the same time.

**Comment by kazu-yamamoto** [comment]
@kazuho Thanks! I understand.

@martinthomson It would be nice if the reasons were added.

**Comment by LPardue** [comment]
@martinthomson do you see any work to do here or should this issue be closed with no action?

**Comment by martinthomson** [comment]
It would have been nice to see a proposal for the explanation, but the draft is fine without it (we don't need to explain everything).
