### ISSUE TITLE
HTTP concepts of error codes

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4352]
In the HTTP genart review, @theri writes:

> The concepts around error codes is not entirely clear to me, e.g.,
H3_REQUEST_INCOMPLETE or H3_NO_ERROR - Are these a separate concept from HTTP
response status codes such as "200 OK" and "404 Not Found", etc.? Are these
error codes related to QUIC errors? Is the "application error code" mentioned
in Section 5.3 the same concept or is it a different concept? Is the
"application error code" an HTTP/3 concept of a QUIC concept? Is "connection
error" used in Section 7 the same concept or is it a difference concept? Does a
"connection error" as used in Section 7 always mean that the entire connection
fails, as opposed to a single stream? Section 8 aims to explain some of these
concepts, and I think the document should reference to this section for more
information when it starts mentioning all these different error types. (Or, if
they are all the same, perhaps the terminology should be unified.)

**Comment by MikeBishop** [comment]
As you note, Section 8 describes the types of error, but mostly defers to QUIC-TRANSPORT for that.  It's probably worth pulling some more context into this document.
