### ISSUE TITLE
What does "retrying requests is not possible" mean?

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4355]
In the HTTP genart review, @theri writes:

> Section 4.1.2
> 
> "Automatically retrying such requests is
>    not possible, unless this is otherwise permitted (e.g., idempotent
>    actions like GET, PUT, or DELETE)."
> Retrying is "not possible" means it's prohibited? Is there a reference to the
> exceptions to that rule, e.g., a list of actions that are considered
> idempotent? If so, please provide a reference.

**Comment by MikeBishop** [comment]
Presumably a reference into SEMANTICS; I'll look for the right section to point to.
