### ISSUE TITLE
Is HTTP CONNECT always TCP?

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4356]
In the HTTP genart review, @theri writes:

> Section 4.2
> 
> "A proxy that supports CONNECT establishes a TCP connection […]"
> Is this necessarily always TCP, not QUIC? Can this change in the future?

**Comment by DavidSchinazi** [comment]
Yes, CONNECT only supports TCP, and there's no short-term plan to change that. There is separate relevant work such as [CONNECT-UDP](https://tools.ietf.org/html/draft-ietf-masque-connect-udp) but I don't think we need to change anything in the draft here - it pretty clearly mentions TCP so I don't see any ambiguity.

**Comment by MikeBishop** [comment]
This question should be addressed by the definition of CONNECT the spec is referring to.  It's worth double-checking the references in that section, though; it points to HTTP11, when I think there should be a definition in SEMANTICS.
