### ISSUE TITLE
Unclear wording about idle timeouts and HTTP/3 implementations

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4357]
In the HTTP genart review, @theri writes:

> Section 5.1
> 
> "HTTP/3 implementations will need to open a new HTTP/3
>    connection for new requests if the existing connection has been idle
>    for longer than the server's advertised idle timeout"
> Only the server's timeout? Does "implementations" here mean only clients?

**Comment by MikeBishop** [comment]
That language has changed in transport, so we should update to match here.  The timeout is negotiated between server and client.

**Comment by MikeBishop** [comment]
This also was addressed in #4383, specifically https://github.com/quicwg/base-drafts/pull/4383/commits/77ea56e18b33abd19356f57cc0a536ab428bbd20.

**Comment by LPardue** [comment]
This editorial issue was fixed in a PR but our automation didn't pick up on it. Manually closing.
