### ISSUE TITLE
HTTP/3 stream types and extensibility

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4358]
In the HTTP genart review, @theri writes:

> Section 6.2
> 
> "However, stream types that could modify the state or
>    semantics of existing protocol components, including QPACK or other
>    extensions, MUST NOT be sent until the peer is known to support them."
> Is there a defined list of stream types that are not allowed to be used? If so,
> please provide a reference.
> 
> Is section 6 missing the request stream? It has subsections for Control Streams
> and Push Streams, but then Section 7 says that Request Stream is also a stream
> type.

**Comment by MikeBishop** [comment]
Request streams are all client-initiated bidirectional streams, so they're not defined as a unidirectional stream type.  It's probably worth defining the term somewhere, though.

**Comment by LPardue** [comment]
I agree with this review, "stream type" is used unqualified across section 6.2 and 7

**Comment by MikeBishop** [comment]
Ah, I was right that I'd already made these changes -- I forgot to link it, but https://github.com/quicwg/base-drafts/pull/4383 contained changes for this, specifically https://github.com/quicwg/base-drafts/pull/4383/commits/f336847cf85b5eae42adcf4b8d7cf8ff9d45a269.  Can you confirm that these changes address the issue?

**Comment by MikeBishop** [comment]
Paging @theri, since I don't think anyone has.  You've seen the changes already, but just need to confirm the issue is addressed.
