### ISSUE TITLE
Authentication model for QUIC-HTTP is not explicitly spelled out

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4362]
Hilarie Orman wrote:
>The only problem that
I have is that the authentication model for QUIC-HTTP is not
explicitly spelled out.  The only discussion is in section 3.4
Connection Reuse, and although that section may be technically
correct, I find it hard to understand.

**Comment by MikeBishop** [comment]
For server authentication, which I think is what you're getting at here, 3.2 also mentions the concept of establishing authority, but doesn't go into much detail.  I suspect the specifics of comparing a certificate should move to 3.2.  I'd appreciate suggestions for making it easier to understand.
