### ISSUE TITLE
Privacy wrt reused connections

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4363]
Hilarie Orman wrote:
> Similarly [to the point made in https://github.com/quicwg/base-drafts/issues/4362], there is brief
mention of privacy wrt reused connections in 10.11, but that is
weak beer, simply saying that HTTP 3 prefers not to reuse connections.

**Comment by MikeBishop** [comment]
It doesn't even say that it prefers not to reuse.  It notes an explicit preference *to* reuse connections, but that's a privacy choice that clients will need to manage the trade-off for.  Individual implementations can be as aggressive about reuse or as aggressive about privacy as they want.  All this section is attempting to do is point out the trade-off.

I'm inclined to do nothing, but would welcome text suggestions.

**Comment by janaiyengar** [comment]
Given this is not any different in terms of privacy considerations as compared to h2, and unless someone can propose text that is stronger, I'm inclined to say that we leave it as is. There's not much more we can _do_ about the privacy issue here besides noting it.

**Comment by LPardue** [comment]
The text is almost word-for-wrod what is present in HTTP/2 https://tools.ietf.org/html/rfc7540#section-10.8. I'm happyto leave this as is.

**Comment by LPardue** [comment]
The proposed resolution was to close to with action, which was signalled to the appropriate review channel.

Hearing no pushback, I'm closing this.
