### ISSUE TITLE
Integrity of the data isn't mentioned at all

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4364]
Hilarie Orman wrote:
> And integrity of the data isn't mentioned at all, perhaps because
all this is assumed to be provided by QUIC.  Section 10.2 says that
all QUIC packets are encrypted; I'm not sure if that's true, or if
QUIC has an option for "non-modifiable" without encryption.

**Comment by martinthomson** [comment]
Actually, we now know that this is not true, so this really needs to be fixed:

> Because all QUIC packets are encrypted, it is difficult for an attacker to control the plaintext bytes of an HTTP/3 connection, which could be used in a cross-protocol attack on a plaintext protocol.

-- from [Section 10.2](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-cross-protocol-attacks).

The real language here needs to cite [Section 21.5](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-request-forgery-attacks) of the transport draft.

**Comment by MikeBishop** [comment]
The version of QUIC required by this draft is always encrypted; that seems sufficient for the original issue.  @martinthomson's issue is distinct, and worth fixing.  I'll use this issue to track it.

**Comment by janaiyengar** [comment]
... and we could add some text stating the integrity point in Section 1.2.
@MikeBishop suggests: "comparable integrity and confidentiality to TLS over TCP"

**Comment by larseggert** [comment]
Could we make some progress on this one?

**Comment by martinthomson** [comment]
Progress made; the PR now needs review.
