### ISSUE TITLE
IANA review of -http; overall correctness

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4375]
Please see the [review email](https://mailarchive.ietf.org/arch/msg/quic/2A76lPm7A86Aeu-6Y2mZyxB0Qtw) for full context. 

Editors, has IANA correctly identified the required actions (modulo the four questions raised that we are tracking in other issues in https://github.com/quicwg/base-drafts/milestone/17

**Comment by MikeBishop** [comment]
Yes, the required actions have been correctly identified.
