### ISSUE TITLE
IANA review of -transport; overall correctness

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4380]
Please see the [review email](https://mailarchive.ietf.org/arch/msg/quic/xlL0IKet4F_QwoiesvANZ32YsKQ) for full context. 

Editors, has IANA correctly identified the required actions (modulo the four questions raised that we are tracking in other issues in https://github.com/quicwg/base-drafts/milestone/18

**Comment by martinthomson** [comment]
I've responded via email with a summary of the issue discussion.

**Comment by martinthomson** [comment]
Response:

**Comment by larseggert** [comment]
@martinthomson did IANA respond to your email? do they still have questions or is this resolved?

**Comment by martinthomson** [comment]
I didn't get a response.

I will ask.  At the same time I will point out that IANA need to revise their actions as we are adding a new error code.

**Comment by gloinul** [comment]
From my perspective, it might be simplest that you get -33 submitted and I will ping IANA that they should check the revisions as well as the new error code.

**Comment by larseggert** [comment]
OK. In that case, I will close this issue now and if anything else pops up, we will open a new issue during IESG review.
