### ISSUE TITLE
Must small VN packets be dropped?

### ISSUE THREAD

**Issue by RyanTheOptimist** [quicwg/base-drafts#4395]
Currently section 10.3 of the transport doc says:

> Endpoints MUST discard packets that are too small to be valid QUIC packets. With the set of AEAD functions defined in [QUIC-TLS], packets that are smaller than 21 bytes are never valid.

However, Version Negotiation packets are not guaranteed to be larger than 21 bytes. For example, a VN packet with an 0-byte destination connection ID, 8 byte source connection ID and single version would be 19 bytes. If a client receives such a packet, must it be dropped? This text suggests it must. But it's not clear to mean (or the slack channel) that this interpretation is expected.

Of course, a server could work around this issue by appending a sufficient number of GREASE'd versions to make the packet large enough. But I'm not sure if that is mandatory?

**Comment by kazuho** [comment]
The second sentence merely points out that QUIC packets *that use AEAD* can never be smaller than 21 bytes.

VN packets do not use AEAD, hence that 21 byte limit does not apply. Of course, endpoints can do their own maths to figure out the minimal size of VN packets that they might receive.

Just my two cents. We might want to clarify the italic part ("that use AEAD") in the specification.

**Comment by DavidSchinazi** [comment]
I agree with @kazuho that the spec isn't technically wrong, but I find it unclear. It wouldn't surprise me if someone were to read this and add `IF packet.length < 21 THEN DROP` to their packet ingestion code. I think all we need here is an editorial clarification such as `Note that version negotiation packets do not use AEAD and can therefore be smaller that 21 bytes.`

**Comment by kazuho** [comment]
I'm not sure if 21 is correct. Isn't it 19 for 1-RTT packets; i.e. 1 (header) + 0 (CID) + 1 (PN) + 1 (frame) + 16 (AEAD tag)?
