### ISSUE TITLE
DAG of documents

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#44]
The submission was complicated by the fact that the documents cross-reference each other, which makes for some difficulty during the build/submission process.  Martin worked around that initially by just changing the references to be by title instead of by I-D name.  For the future, however, should we make the documents acyclic?  That would require clarifying the interfaces between the components we intend to make separable, which I think is a strictly good thing.

My initial inclination is that the core spec should reference none of the others, and each of the others should reference only the core spec.  The HTTP mapping doesn’t care what loss detection or security handshake is used, only that they provide the features needed by QUIC.  Currently, we explicitly require that the TLS handshake be used, but I’m not convinced that’s necessary.  (Alternately, we could reference the actual TLS RFC and require that “a handshake using TLS” be employed, rather than the particular handshake we’re currently defining.)  The loss detection and security components shouldn’t care about each other either, so long as they can trust that the jobs are getting done.  The core spec should contain the interfaces for all these intersection points.

Given that we’ve already agreed that we intend these pieces to be modular, I think this is *probably* an editorial-class change, albeit a big one.

**Comment by martinthomson** [comment]
I considered doing this, but I think that the loss of utility is pretty acute.  The solution I have in place will work for future submissions reasonably well (modulo some tweaking).

**Comment by MikeBishop** [comment]
Do you mean the loss of ease for submission, or that the documents themselves would suffer?  Arguably, if we want these to be modular, we should be defining more than one of each pluggable "thing" to help ensure they are.  But since we aren't doing that, forcing ourselves to define the interfaces (or for now, setting out space for the interfaces) seems like the next best way of ensuring we achieve that goal.

Of course, it might force some delay between version submissions while we wait for the new XML to publish; I agree with you on the ease-of-submission issue.

**Comment by MikeBishop** [comment]
Tagging this as "needs discussion," not for the editorial aspect of it, but because this reflects the "Does Transport depend on TLS?" discussion.  If Transport depends on TLS, we can't have a DAG.

**Comment by martinthomson** [comment]
Clearing the label.  I *think* that the transport depends on TLS, but we're trying to keep a clear delineation between the two.

**Comment by martinthomson** [comment]
@MikeBishop, I'd really like to close this with no action.  Do you want to make a case for doing this?

**Comment by martinthomson** [comment]
In the absence of a response.  I'm going to make an executive decision here.
