### ISSUE TITLE
ShortHeaderPacket does not indicate the ConnectionId length

### ISSUE THREAD

**Issue by Vect0rZ** [quicwg/base-drafts#4422]
Hello,

reading draft-32 of [quic-transport] we can notice the structure of the ShortHeaderPacket

```
Short Header Packet {
     Header Form (1) = 0,
     Fixed Bit (1) = 1,
     Spin Bit (1),
     Reserved Bits (2),
     Key Phase (1),
     Packet Number Length (2),
     Destination Connection ID (0..160),
     Packet Number (8..32),
     Packet Payload (..),
}
```

The `Destination Connection ID (0..160)` does not have a preceding `Destination Connection ID Length (8)`. In this case, we wouldn't know how many bytes does the connection ID occupies.

**Comment by larseggert** [comment]
This is discussed in [Section 5.1](https://tools.ietf.org/html/draft-ietf-quic-transport-32#section-5.1):
> Packets with short headers (Section 17.3) only include the
   Destination Connection ID and omit the explicit length.  The length
   of the Destination Connection ID field is expected to be known to
   endpoints. 

Your endpoint will need to remember the length chosen for a connection.

**Comment by Vect0rZ** [comment]
Thank you @larseggert !
