### ISSUE TITLE
Acknowledgement or acknowledgment, not both

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#4440]
The English and US spelling forms are used arbitrarily in transport draft.

**Comment by larseggert** [comment]
I think we can leave this for the RFC Editor to fix, unless for some reason we need to do a -34 anyway. Leaving this open until we know.

**Comment by martinthomson** [comment]
My guess is that there will be a -34, based on past experience with the IESG.  So it is better to fix it now.
