### ISSUE TITLE
Martin Duke Recovery Comment 1

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4467]
@martinduke said:

> It’s odd that sec 4.7 doesn’t mention RACK at all, as that’s headed to TCP standard.

**Comment by ianswett** [comment]
Good point, also 4.7 currently has TLP in the title, but doesn't use it anywhere else in the section, so I'll add some text on TLP too.

https://tools.ietf.org/html/draft-ietf-quic-recovery-33#section-4.7

**Comment by pravb** [comment]
Please also update the RACK reference to version 14. draft-ietf-tcpm-rack-14

**Comment by ianswett** [comment]
The version update is part of the toolchain we use, so the newest version of RACK should be referenced automatically.
