### ISSUE TITLE
Reduced flow control limits

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#447]
We currently say that a sender MUST NOT reduce these limits, but don't really require or permit a receiver to enforce this.  Now, it's true that reordering might cause limits to be received out of order, and it's probably best that we not *require* a receiver to check that the limit never reduces.  However, we might want to allow a receiver to look at packet numbers, determine that the number has been reduced, and kill the connection with a flow control error.

**Comment by marten-seemann** [comment]
An old WINDOW_UPDATE (with a lower offset) might end up in a packet with a higher packet number if it is a retransmission, and the sender doesn't regenerate the frame.

**Comment by mikkelfj** [comment]
Is there are more general control frame flooding attack concern? For example starving stream 0.

**Comment by martinthomson** [comment]
@marten-seemann, you aren't supposed to retransmit WINDOW_UPDATE verbatim like that.  A consequence of making a change like this would be a stronger prohibition on dumb retransmission strategies.
