### ISSUE TITLE
Alissa Cooper's comment regarding spin bit disabling

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4472]
@coopdanger notes:
> Section 17.4: For someone coming to this new, it might not be obvious why
requiring the disabling of the spin bit on a fraction of connections is useful.
This may be worth a sentence of explanation.

My understanding is that this exists both to protect the ability of endpoints to opt out and to ensure that monitoring is robust when the opt-out is exercised.

**Comment by MikeBishop** [comment]
Also to ensure that if the functionality is removed/changed in a future version of QUIC, we're only changing the percentage of traffic that enables it versus creating something new.
