### ISSUE TITLE
Ben Kaduk's TLS Discuss 2

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4476]
@kaduk said:

> (2) Let's check whether the quic_transport_parameters TLS extension
> should be marked as Recommended or not.  The document currently says
> "Yes", and the live registry say 'N'.  That said, the earliest mention I
> can see of using 'N' in the archives is in
> https://mailarchive.ietf.org/arch/msg/tls-reg-review/z8MOW0bYNP2KIj4XcCXBe2IOKfI/
> which seems to just be stating what IANA did when they changed what
> codepoint (since there were issues with the initially selected value
> '46') and not a reasoned decision.
> 
> The perhaps haphazard nature of that change notwithstanding, in my
> opinion the 'N' actually is correct, since the extension is not
> appropriate for general use *of TLS* (indeed, we require that TLS
> implementations that support this document abort the connection if it is
> used for non-QUIC connections).
﻿

**Comment by martinthomson** [comment]
Response provided via email.

**Comment by martinthomson** [comment]
Resolved via email.
