### ISSUE TITLE
Handshake protocol selection

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#45]
It's currently unclear how two QUIC peers opening a connection know which handshake protocol to expect on Stream 1.

Since the client has to include the opening handshake in its first flight, it has to at least be able to guess *a* handshake protocol that's acceptable to the server and include enough information for the server to know which one it's attempting.  Currently all the mechanisms for telling the client to retry with different options are at the TLS layer, which is too late.

How is this negotiated?  Is it baked into the QUIC version?  Is it specified as part of the application mapping (e.g. the HTTP mapping currently requires the TLS 1.3 handshake to be used) and therefore either supplied as part of the Alt-Svc record or implied by the port?

**Comment by ianswett** [comment]
I would suggest it be baked into the QUIC version.

**Comment by MikeBishop** [comment]
That's not unreasonable, though it feels odd to define in the core draft that a particular "version" means that its pluggable components have certain values.  So when we define a registry of "versions," it needs to specify both the base protocol release and the handshake protocol release that are implied by that version string.

Wading into unfamiliar transport territory -- does this need to include loss detection as well?  Do the two sides need to agree on the loss detection algorithm, or can that be unilateral?

**Comment by ianswett** [comment]
Crypto is special, because it indicates how to QUIC protocol handshake will
be transmitted, and QUIC can't do anything useful without crypto.

Loss detection can be unilateral.  And if something more framing oriented,
like an alternate ack format is desired, it could easily be negotiated in
the QUIC handshake, as long as it didn't need to be used before obtaining
the 1RTT keys.

**Comment by martinthomson** [comment]
Hmm, do I have to be the mailing-list police here?  I know that it's exciting and all, but we should either leave these design issues parked here, or take them to the list.  I suggest parking them because we can't have millions of design issues being discussed at the same time or they will all starve.

**Comment by MikeBishop** [comment]
Double-check the CONTRIBUTING file.

> Issues will be labeled by the Chairs as either `editorial` or `design`.
> 
> * `design` issues require discussion and consensus in the Working Group. This discussion can happen both **in the issue** and on the [Working Group mailing list](https://www.ietf.org/mailman/listinfo/quic), as outlined below.
> 
> * `editorial` issues can be closed by the editor(s) without consensus or notification. Typically, any discussion will take place on the issue itself.
> 
> Consensus for the resolution of a design issue can be established in a few different ways:
> 
> * Through discussion on the mailing list. Once a resolution is found, it will be recorded in the issue.
> 
> * **Through discussion on the issues list.** Once a resolution is found, it will be confirmed on the mailing list before consensus is declared.

Discussion on GitHub has been deemed appropriate -- it's only final decisions that have to go to the list.  If that's not the policy the chairs intended, they need to update their policy, because that's certainly how it reads.

**Comment by mnot** [comment]
Discussed in Tokyo; support for doing so, but not clear consensus yet.

**Comment by martinthomson** [comment]
@mnot, support for doing what?

**Comment by martinthomson** [comment]
To be clear, I *think* that this means that we will fix the crypto to the QUIC version (each QUIC version defines exactly one cryptographic handshake protocol), but that discussion was such a mess that I'm not sure that this just personal bias or not.

**Comment by mnot** [comment]
https://github.com/quicwg/wg-materials/blob/master/interim-17-01/minutes-24.md#issue-45

**Comment by ianswett** [comment]
@janaiyengar  still had reservations about this, and I don't know if they were completely allayed since then.  Jana, thoughts?

**Comment by mnot** [comment]
Discussed in Chicago; proposal (no consensus yet):

Handshake protocol and version is defined by the QUIC version; application mapping defines what handshake protocol(s) are acceptable, and may further constrain it.

The current transport's handshake is "TLS 1.3 or greater". The HTTP mapping will require that.
