### ISSUE TITLE
Érik Vyncke's Transport Comment 22

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4545]
Érik Vyncke said:

> -- Section 23.1 --
> Why using the anchor [IPv4] rather than [RFC791] ? Just curious...﻿

**Comment by martinthomson** [comment]
Because [IPv4] is obvious to people who don't know the numbers by heart.  We've used symbolic references by preference throughout, unless a simple mnemonic is unavailable.

**Comment by LPardue** [comment]
As an individual, I agree with Martin. There's over a dozen instances of symbolic references in the family of QUIC specs, I don't think changing them all is the right thing to do at this stage.
