### ISSUE TITLE
Roman Danyliw's Recovery Comment 1

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4555]
Roman Danyliw said:

> ** Section 3.  Per “The encryption level indicates the packet number space, as
> described in [QUIC-TRANSPORT ]”, I think that reference here is Section 4.*
> from [QUIC-TLS] as I can’t find a mapping between PNS and encryption levels as
> discussed here in [QUIC-TRANSPORT].﻿

**Comment by ianswett** [comment]
I believe the mapping from encryption level to PNS is detailed in section 12.3 of transport:
https://www.ietf.org/archive/id/draft-ietf-quic-transport-33.html#packet-numbers

**Comment by MikeBishop** [comment]
I can't find the text being commented on.

**Comment by larseggert** [comment]
@MikeBishop text is in the first paragraph of https://tools.ietf.org/html/draft-ietf-quic-recovery-33#section-3

**Comment by larseggert** [comment]
It might be useful to point to the specific section in -transport that @ianswett mentioned in his comment. Anyone care to propose a PR?
