### ISSUE TITLE
Roman Danyliw's TLS Comment 1

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4556]
Roman Danyliw said:

> ** Section 4.  Recommend a bit more text up front describing the notion of
> “encryption levels”.  This section first introduces the concept by noting that
> “Those frames are packaged into QUIC packets and encrypted under the current
> TLS encryption level”.  Later in Section 4.1.3, it is noted that “Four
> encryption levels are used, producing keys for Initial, 0-RTT, Handshake, and
> 1-RTT packets” which makes these “levels” seem only like categories.  In
> describing specific processing there is text such as “When TLS provides keys
> for a higher encryption level …” which now describes a relatively ordering
> perhaps with something have having or less.  I might be helpful to include an
> early narrative on what “higher” and “lower” and encryption “levels” means and
> how level changes occur (i.e., explicitly linking them to changes in the QUIC
> state machine).﻿

**Comment by martinthomson** [comment]
I'm going to suggest that the text I propose in #4561 addresses this first part of this.

The higher/lower stuff seems like it could be better, but it's a lot of work to do carefully.  I'm going to suggest that we could live with this, but I might leave this issue open and try to find a fix once other more pressing issues are dealt with.
