### ISSUE TITLE
Stateless Reset from clients

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#466]
A client may operate on equal footing with a server, i.e. it is not always a HTTP browser client, but currently a client cannot send a PUBLIC_RESET:

> A Public Reset packet is only sent by servers and is used to abruptly terminate communications. Public Reset is provided as an option of last resort for a server that does not have access to the state of a connection.

The problem is also that the purpose of PUBLIC_RESET is vague. The problem here is primarily that an endpoint might loose state during a crash and cannot tell peer to terminate the connection. The related use case for informing middle boxes is a separate topic.

Use case: Datacenters might have private networking, but not across datacenters. QUIC could be used to form a peer-to-peer server network. There might be edge routers in each datacenter (e.g. into a Kubernetes network), or not, but either way end-points may have high volume bidirectional traffic that needs to stop. The situation can also happen within datacenters with private networks with co-location where QUIC protects against other customers on the network.

Edge routers may have to also tear down the connection across datacenters (border gateway routing) which is then the separate middlebox issue.

Lost-state teardown need not involve any public activity and could avoid an obvious attack vector by using a non-public reset mechanism, but middlebox signalling need this. For the endpoint tear down, it could be replacing PUBLIC_RESET with a hint on lost connection which triggers surviving endpoint to perform a low volume liveness check, e.g. PING/ack at most every x ms.

Further consideration is that post-crash a server might have to load state from persistent storage in order to perform a reset proof that is not predictable. If this can be avoided via hint/live-ness verification, persistent state reset might be avoidable.

also discussed here:
https://github.com/quicwg/base-drafts/issues/462#issuecomment-297383356

**Comment by britram** [comment]
See #215: decided in Paris to make this symmetric.

**Comment by mikkelfj** [comment]
It appears that a client or server might not always be able to send a reset on the original communication path because the OS might not give access to the ephemeral port required. Perhaps some guidance is needed. I can't wrap my head around whether this is a real concern or not.

If a packet can be sent by other means, each connection could be indexed by the reset token previously received.

There is also the potential case where client and server both use fixed (non-ephemeral) ports in a symmeric p2p configuration, but that is not currently possible due 5-tuple uniqueness requirement, but a symmetric reset would be more important and easier to handle.

**Comment by martinthomson** [comment]
I started writing this up then realized the fatal flaw with the decision we made: the stateless reset token requires confidentiality protection for this to work and the client transport parameters are not confidentiality protected.

Maybe we should reconsider this decision, and - based on our decision to concentrate on our primary application - park this issue.

**Comment by mikkelfj** [comment]
Added a more general issue to discuss relevance/importance of reset in #1177

**Comment by martinthomson** [comment]
Based on #1151 being merged, the idea here is to change the client/server text on stateless reset to be endpoint/peer and allow clients to send one.  Then add a small paragraph noting that the client cannot send the token in its transport parameters because they aren't encrypted, therefore only the second client connection ID, as provided with NEW_CONNECTION_ID, is the first that can be used with stateless reset.

That's not a perfect solution.  Client's can't guarantee that servers will move to a new connection ID, for instance.  But it's a step in that direction that we can iterate on.  We aren't sure that we'll get around to a more complete fix before quicv2 though.
