### ISSUE TITLE
Robert Wilton's Transport Discuss 1

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4666]
Rob Wilton said:

> 1) I find it hard to understand why a server is allowed to independently decide
> whether or not to support the spin bit on a connection?  Shouldn't the client
> (or administrator of the client system) that opened the connection be able to
> choose whether they want the RTT to be monitorable via the spin bit?  What is
> the reasoning for allowing the server (or server administrator) to be able to
> independently be able to decide what is best for the client?

**Comment by LPardue** [comment]
This was talked about on the IESG telechat 2020-01-07. The action item is to add clarity one what an endpoint that does not support the spin bit should do. Note that this is distinct from an endpoint that supports spin bit but chooses to disable it. The discussion leaned towards an editorial change to the text in Section 17.4, for instance in paragraph 3.

IIUC no other changes are needed to resolve this discuss, but we should confirm this via email.

**Comment by martinthomson** [comment]
I don't get this.  The following text seems abundantly clear:

> When the spin bit is disabled, endpoints MAY set the spin bit to any value, and MUST ignore any incoming value. It is RECOMMENDED that endpoints set the spin bit to a random value either chosen independently for each packet or chosen independently for each connection ID.

Or is it this?

> The spin bit is an OPTIONAL feature of this version of QUIC. A QUIC stack that chooses to support the spin bit MUST implement it as specified in this section.

Where we don't say that optional == disable it?  If that is all, I'm going to hold my tongue.
