### ISSUE TITLE
Retransmission of handshake frames

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#471]
The draft currently says:

> Endpoints MUST retransmit handshake frames if not acknowledged within a time limit. 

I've been trying to be very careful about what it means to retransmit.  We don't retransmit packets, we create new packets; similarly, we don't retransmit frames, we create new frames that contain the data we want.

In the case of the first client packet, we can probably be a little more prescriptive.  The client can send another packet with the same contents, just with the packet number incremented.

**Comment by janaiyengar** [comment]
We played fast and loose with using "retransmit" earlier in the life of the
draft. I think it's reasonable to say that the client SHOULD rebundle, as
it always does.
