### ISSUE TITLE
Coalescing for padding clarification

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4738]
This text in `#initial-size` seems to cause confusion for implementors:
> by adding PADDING frames to the Initial packet or by coalescing the Initial packet; see {{packet-coalesce}}

since it leaves it unclear *what* the Initial packet can be coalesced with to pad it. Specifically, some implementations use zeros or other (random) data, which seems to surprise some implementors.

(`#packet-coalesce`, which is referred to, also doesn't seem to clarify this.)

**Comment by tatsuhiro-t** [comment]
My understanding is that transport draft does not say anything about padding outside QUIC packet.  Because a receiver is required to ignore invalid long packets, zero padding outside QUIC packet just works.  So this is "OK because it is not explicitly disallowed" category.

**Comment by larseggert** [comment]
I agree, but it has tripped up implementers (again). I wonder if a wording can be found that doesn't do that.

**Comment by ianswett** [comment]
I'd be happy to see a bit more explicit text to clarify this, since as you said, it's come up a few times as non-obvious.

**Comment by larseggert** [comment]
Maybe something like: "An Initial that is padded by coalescing could be coalesced with valid or even invalid QUIC packets; the latter MUST be ignored as described in Section XYZ."
