### ISSUE TITLE
Cleanup packet padding language in TLS

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4745]
This text could be better:

> The TLS implementation does not need to ensure that the ClientHello is large enough to meet the requirements for QUIC packets. QUIC PADDING frames are added to increase the size of the packet as necessary; see Section 14.1 of [QUIC-TRANSPORT].

Maybe instead:

> The TLS implementation does not need to ensure that the ClientHello is large enough to meet the minimum datagram size for carrying QUIC Initial packets. QUIC implementations use PADDING frames or packet coalescing to ensure that datagrams are large enough; see Section 14.1 of [QUIC-TRANSPORT].

**Comment by larseggert** [comment]
Does anyone want to prepare a PR? Otherwise, this will get dropped I guess.

**Comment by martinthomson** [comment]
I didn't want to clutter our list of stuff with post-IESG PRs.  I'll copy the above text once HTTP is done (real soon now).

We're going to have to be careful that these little tweaks don't pile up.

**Comment by larseggert** [comment]
I think this should be good to go now?
