### ISSUE TITLE
Transfer codings and normative references

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#4746]
@royfielding points out that, in addition to a couple easily-resolved normative references to the HTTP/1.1 draft (this content has moved to Semantics), there's a normative reference to "chunked" transfer encoding being prohibited.  But technically, this is still a MUST NOT for an informative reference.

One resolution would be to make it a statement of fact rather than a conformance requirement -- to say that the transfer codings defined by the HTTP/1.1 are HTTP/1.1-specific and not applicable to HTTP/3.  But that's a broader assertion than just "chunked."  Is there a reason we need to keep e.g. "Transfer-Encoding: gzip"?

**Comment by kazuho** [comment]
My +1 goes to talking about transfer-encodings in general rather than just chunked, but as stated in the review comment, IIUC we already use different language for endpoints and intermediaries and therefore am afraid we have to keep doing so.
