### ISSUE TITLE
HTTP/3 authority diverged from SEMANTICS

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#4761]
@kaduk notes that while we imported text from SEMANTICS in #3407 about what makes a server authoritative, this text later changed dramatically in https://github.com/httpwg/http-core/pull/437 and we're no longer aligned.  We need to re-sync, but only after https://github.com/httpwg/http-core/issues/680 is fixed.

**Comment by larseggert** [comment]
Labeling as design, since #4808 is.

**Comment by MikeBishop** [comment]
Reopening for consensus call.

**Comment by LPardue** [comment]
Closing this now that the IESG have approved the document and it's with the RFC editor.
