### ISSUE TITLE
Roman Danyliw's  HTTP/3 Comment 1

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4763]
@rdanyliw said

> ** Section 3.1.  “The host must be listed either as the CN field …”, why not a
> normative MUST just as there is in the next sentence around the required use of
> iPAddress?

**Comment by MikeBishop** [comment]
I suspect this will be fixed by the resolution to #4761.

**Comment by kaduk** [comment]
FWIW I have some changes staged in my forthcoming editorial PR that harmonizes the requirements language here, even though that is perhaps a little speculative for "just" an editorial PR.

**Comment by larseggert** [comment]
Labeling this design, since #4808 is.

**Comment by MikeBishop** [comment]
Reopening for consensus call.

**Comment by LPardue** [comment]
Closing this now that the IESG have approved the document and it's with the RFC editor.
