### ISSUE TITLE
Roman Danyliw's HTTP/3 Comment 2

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4764]
@rdanyliw said

> ** Section 3.3  Per “Once a connection exists to a server endpoint, this
> connection MAY be reused for requests with multiple different URI authority
> components”, it might be worth repeating here that in cases of https, changes
> in the authority components still need to occur within the bounds of the
> certificate validation practices noted in Section 3.1 and in Section 4.3.4 of
> draft-ietf-httpbis-semantics.

**Comment by MikeBishop** [comment]
Agreed, this should point back if it doesn't already.  This probably also gets swept up in the resolution to #4761, but it's a separate point I'll need to make sure is addressed.

**Comment by larseggert** [comment]
Labeling as design, since #4808 is.

**Comment by MikeBishop** [comment]
Reopening for consensus call.

**Comment by LPardue** [comment]
Closing this now that the IESG have approved the document and it's with the RFC editor.
