### ISSUE TITLE
Explicitly define H3_REQUEST_FOO as stream error

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/base-drafts#4766]
Sec 4.1 and 4.1.2 do not explicitly define `H3_REQUEST_REJECTED`, `H3_REQUEST_CANCELLED`, `H3_REQUEST_INCOMPLETE` as stream errors. A.4.1 says that `H3_REQUEST_REJECTED` is a stream error. It would be nice if they are explicitly defined as stream errors in Sec 4.1 and 4.1.2.

Also, it would be nice if each error code is categorized to either a connection error or a stream error in Table 4.

**Comment by LPardue** [comment]
Commenting as an individual.

The error code space is shared between connection and streams. The action associated with a stream error or connection error cause QUIC transport frames to be emitted, which can use a code.

H3 inherits H2's design philosophy that endpoints can generate a connection error at will. So while there are specific cases that describe "treat X as stream error foo", endpoints are also allowed to "treat X as connection error foo".

Constraining the error codes to different uses has a certain appeal. But then what do we say the the receiver of an error code of the wrong type should do? Generate its own error? I think this has come up a couple of times during H3 drafts but I'm satisfied that the flexibility we have today is about the best we can do.

**Comment by LPardue** [comment]
I also think "stream error" and "abort a stream" are unique and consistent terms used through the document. But I'll let Mike spec to that point with his editor hat.

**Comment by kazu-yamamoto** [comment]
Even though categorization is not reasonable, Sec 4.1, for instance, should say like "the server SHOULD abort its response and treat as a stream error of type H3_REQUEST_INCOMPLETE".

**Comment by LPardue** [comment]
"Abort" is a defined term in section 2.2. I personally don't see much clarity in the proposal, it threatens to add inconsistency to other places where streams are aborted due to application decisions rather than a protocol error.

**Comment by kazu-yamamoto** [comment]
My example proposal is to replace "the server SHOULD abort its response with the error code H3_REQUEST_INCOMPLETE" with "the server SHOULD abort its response and treat as a stream error of type H3_REQUEST_INCOMPLETE" in Sec 4.1. I don't understand why this would introduce inconsistency.

**Comment by LPardue** [comment]
WRT inconsistency, the editor would need to sweep for all instances of abort and reason about whether they need additional text or not. And there's a risk that someone later on picks up on an inconsistency of usage because they didn't appreciate the nuance. Since adding more detail after an instance of `abort` seems duplicative, I would favour not adding any more.

**Comment by MikeBishop** [comment]
I'm okay with @kazuhu's addition of "stream" since abort is defined as a stream operation.  I don't think we need to separate out "abort" and "stream error" as separate statements, because abort already describes what needs to be done.

**Comment by kazu-yamamoto** [comment]
If I was worried too much, no change is necessary. One alternative approach is to add a sentence like "errors in this section are stream errors" in the beginning of Sec 4.
