### ISSUE TITLE
Mandating use of CN-ID is not modern practice (aka Ben's HTTP/3 Discuss 1)

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4769]
@kaduk's review of -http identified use of the subject:commonName field in validating server identity.

We should not elevate CN-ID to MUST.  In doing so, we invalidate what CABF has done: 7.1.4.2.2 clause a of the [Baseline Requirements](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.3.pdf) marks subject:commonName as deprecated and discouraged.

My understanding (which I can confirm) is that browsers do not use CN-ID (concretely, the CN field of the certificate subject) and so we might want to just mention the dNSName type of subjectAltName here.  We can *mention* that some clients might use subject:commonName, but that this is a deprecated practice.  This accounts for some of the older certificate validation code that still exists in some places.  Some of that does rely on the common name.

I realize that this likely breaks new ground for the RFC series, and it likely needs more discussion, but maybe we can keep up with the times with this document.

(I apologize for not having caught this earlier; I think that this is copied from elsewhere and that too needs a refresh.)

_Originally posted by @martinthomson in https://github.com/quicwg/base-drafts/pull/4767#discussion_r560635858_

**Comment by kaduk** [comment]
There is some probably relevant discussion for http-semantics at https://github.com/httpwg/http-core/issues/404 (though as was noted recently the change that closed that issue had some issues of its own)

**Comment by larseggert** [comment]
Marking as design, since #4808 is.

**Comment by MikeBishop** [comment]
Reopening for consensus call.

**Comment by LPardue** [comment]
Closing this now that the IESG have approved the document and it's with the RFC editor.
