### ISSUE TITLE
Defer to core HTTP for 421 status code

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4790]
Spotted in https://github.com/httpwg/http2-spec/issues/802/. While we don't need to make any dependency on h2bis, I don't think it ould hurt to update the reference to 421 to point at http-core.

**Comment by larseggert** [comment]
Labeling as design, since #4808 is.

**Comment by MikeBishop** [comment]
Reopening for consensus call.

**Comment by LPardue** [comment]
Closing this now that the IESG have approved the document and it's with the RFC editor.
