### ISSUE TITLE
Murray Kucherawy's QPACK Comment 2

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4798]
@mskucherawy said

> In Section 2.2.1:
>
> >   While blocked, encoded field section data SHOULD remain in the
> >   blocked stream's flow control window.
>
> Since SHOULD grants me a choice, why might I decide not to do what it says
> here?  Or should this be MUST?

**Comment by dtikhonov** [comment]
One could imagine an implementation using a small buffer to read the beginning of the stream.  If the whole field section happens to fit into it, so be it.  A _MUST_ would probably mean that a conforming implementation had to unread the field section.

**Comment by martinthomson** [comment]
We can probably just use "can" here.  From an interoperability standpoint, there is no value to recommending any particular value.

**Comment by afrind** [comment]
Does SHOULD -> can mean this is a design change?

**Comment by LPardue** [comment]
Yes, so if you're advocating doing that then I'll mark this as design.

**Comment by dtikhonov** [comment]
The _SHOULD_ is there to guard against memory exhaustion attacks.  Streams "parking" is a QPACK design feature.  The _SHOULD_ should stay.

**Comment by afrind** [comment]
The plan is to leave the SHOULD, but add more editorial text in 2.2.1 explaining why it's a good idea.
