### ISSUE TITLE
Rejecting duplicated push streams requirement is unenforceable

### ISSUE THREAD

**Issue by guoye-zhang** [quicwg/base-drafts#4828]
> Each Push ID MUST only be used once in a push stream header. If a push stream header includes a Push ID that was used in another push stream header, the client MUST treat this as a connection error of type H3_ID_ERROR

For clients that have sent CANCEL_PUSH, they don't know if server's push stream will still arrive or not. They have to remember Push IDs forever in order to differentiate between cancelled push and completed push.

**Comment by gloinul** [comment]
I would appreciate some quick discussion if this issue is important to address before I approve or not.

**Comment by MikeBishop** [comment]
We could make this a MAY.  The other formulation we've used is "MUST ... if the client detects", making the response mandatory if the condition is detected, but not specifying the required level of effort to detect it.

**Comment by MikeBishop** [comment]
I don't know that this issue is critical to address, but I agree that with certain (reasonable) implementation strategies this particular MUST becomes unenforceable / unachievable.

**Comment by ianswett** [comment]
+1 for "MUST if the client detects" if we're going to make a change.

**Comment by LPardue** [comment]
I think "MUST if detects" is suitable here - it points at the core problem. Simply s/MUST/MAY doesn't help people appreciate that might not be able to detect the condition. I'd also suggest that "MUST if detects" is an editorial change.

**Comment by LPardue** [comment]
@guoye-zhang can you confirm if #4829 addresses your issue?

**Comment by guoye-zhang** [comment]
Looks good!

**Comment by LPardue** [comment]
Thanks. In that case I believe we have addressed this issue with an editorial change. @gloinul please confirm if we can merge the related PR and incorporate the change in during the RFC editor process.

**Comment by gloinul** [comment]
Yes, the change looks good. I could actually include it as an RFC-edtior note in my approval message.
