### ISSUE TITLE
Recovery: Execute the previously unarmed PTO to avoid a deadlock

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#4830]
When the PTO is not armed due to the amplification limit and then a packet is received: https://tools.ietf.org/html/draft-ietf-quic-recovery-34#section-6.2.2, it's important to send data for the PN spaces the PTO is armed for(Initial or Handshake) prior to new application data.

Typically PTO suggests writing new data instead of retransmitting data which may or may not be lost, but that's not true during the handshake.

This is only an issue for the server, since it's caused by enforcing the amplification limits prior to address confirmation.

This is most evident when 0-RTT is accepted, but address validation fails, since otherwise a server would not usually have enough data to write to create a problem.

**Comment by nibanks** [comment]
I went and double checked the msquic code [here](https://github.com/microsoft/msquic/blob/v1.0.0-129524/src/core/path.c#L96), and we always re-enable the loss detection timer when we become "unblocked" by amplification protection logic. I thought this logic was already driven by some statement in the spec.

I just went back and found this:

> A.6.  On Receiving a Datagram
> 
>    When a server is blocked by anti-amplification limits, receiving a
>    datagram unblocks it, even if none of the packets in the datagram are
>    successfully processed.  In such a case, the PTO timer will need to
>    be re-armed.

Do we need any more than this?

**Comment by ianswett** [comment]
The potential issue is that if the PTO is armed, but should have already expired, it's important to execute it prior to sending any pending data.

I'm working on a PR to make this clearer, and we can whether the extra clarification is necessary?

**Comment by huitema** [comment]
I wonder whether there is something else going on. Amplification or not, 0-RTT packets can only be acknowledged by ACK frames in 1-RTT packets. Those can only be received after the client gets the 1-rtt keys. So implementation should just start a short timer after the handshake completes.

**Comment by LPardue** [comment]
This seems like an editorial change, please confirm. Either way, lets ensure @gloinul has an opportunity to comment before landing any changes.

**Comment by tatsuhiro-t** [comment]
ngtcp2 has dedicated code for this situation: https://github.com/ngtcp2/ngtcp2/blob/397c943599665f35733b8d703715049be7031618/lib/ngtcp2_conn.c#L8583-L8594

**Comment by gloinul** [comment]
In response to @LPardue: If the WG establish a consensus on the need for a change a particular fix then this PR can be applied in the AUTH48 with AD approval. 

I think we need to figure out if not merging the PR until AUTH48 is the best? It makes it simple to provide the changes to the RFC-editor, but maybe makes it harder for the rest of the community to keep track of the changes if there are no editors copy that contain all agreed things. However, considering the hopefully limited time that may make sense.

**Comment by larseggert** [comment]
We can tag the versions that entered the RFC Editor queue, and then generate a diff against those at AUTH48.

**Comment by martinthomson** [comment]
That tag already exists, so we are good.
