### ISSUE TITLE
clarify how to handle in increase in initial_max_{stream_}data_{uni, bidi}

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#4834]
If the client has opened a stream in 0-RTT with `initial_max_stream_data_uni = N`, and the server increases `initial_max_stream_data_uni` to `M`, does this apply to this stream as well, or only to streams opened after handshake completion?

Consensus in Slack seems to be that the limit should apply to all streams. The text should be explicit about that.

**Comment by kazuho** [comment]
Isn't that already clear enough? [Section 7.4.1 of the transport draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-values-of-transport-paramet) states:
> Remembered transport parameters apply to the new connection until the handshake completes and the client starts sending 1-RTT packets. Once the handshake completes, the client uses the transport parameters established in the handshake.

**Comment by marten-seemann** [comment]
@kazuho This is what the definition of the TP says:

> initial_max_stream_data_bidi_remote (0x06): This parameter is an integer value specifying the initial flow control limit for peer-initiated bidirectional streams. This limit applies to newly created bidirectional streams opened by the endpoint that receives the transport parameter. 

Arguably, the stream used in 0-RTT is not a "newly created" stream.

**Comment by martinthomson** [comment]
Yeah, let's just be really clear about this.  Though @kazuho quotes the section that is most important, this has proven to be a mistake common enough to spend text on.
