### ISSUE TITLE
IANA:  Leading zeros discrepancy

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#4838]
IANA made the following observation while creating the H3 registries:
> In the document, the Stream Types registry presents numeric values 
> as two-digit sequences with a leading zero, while the first two 
> registries use one digit. Because 
> https://www.iana.org/assignments/quic uses two digits throughout, 
> we've used two here.

While the IANA copy of the registry uses two digits throughout, the QUIC draft is similarly inconsistent about whether literal hex values have any leading zeros.  Is it worth updating our hex literals to use full bytes (`0x00`, `0x0103`, etc.) or synchonizing on some other format?  We probably shouldn't synchronize on trimming, since IANA has already skewed the other way.

**Comment by martinthomson** [comment]
@MikeBishop, did #4844 fix this or do we need to inform IANA also?

**Comment by MikeBishop** [comment]
We should probably shoot IANA an e-mail to update the registries with leading zeroes where they hadn't already assumed them.

**Comment by martinthomson** [comment]
I'll let you do that.  The only registries that are affected are in HTTP/3 and QPACK.

**Comment by martinthomson** [comment]
Fixed both in the registry and the documents.
