### ISSUE TITLE
Loss recovery pseudocode can erroneously set PTO in the past

### ISSUE THREAD

**Issue by Ralith** [quicwg/base-drafts#4846]
If the server's first flight is interrupted by anti-amplification, the client's second flight may consist only of ACKs in the Initial and Handshake spaces. At this point, Initial state is discarded on the client, and no ack-eliciting data has been sent in the Handshake space. `GetPtoTimeAndSpace` dictates that (assuming the ACKs were padded) the PTO be set to `time_of_last_ack_eliciting_packet[space] + duration`, but `time_of_last_ack_eliciting_packet` still has its initial value of 0. 

The desired behavior here is to schedule an anti-amplification deadlock prevention probe in the future, so the logic used when there are no in-flight packets should probably apply here as well. This could be accomplished by special-casing the behavior when `time_of_last_ack_eliciting_packet[space] == 0` to use `now()` instead, or perhaps by adjusting the global `if (no in-flight packets):` test to `if (no ack-eliciting packets in flight):`. I believe the latter approach is safe because the only condition in which `GetPtoTimeAndSpace` controls the loss detection timer when there are no ack-eliciting packets in flight is when `SetLossDetectionTimer` has already found that `PeerCompletedAddressValidation` is false.

**Comment by Ralith** [comment]
Similarly, `OnLossDetectionTimeout` also uses `bytes_in_flight > 0` to judge whether a PTO is a real loss probe or an anti-deadlock packet, but this is incorrect in the case illustrated above.

**Comment by ianswett** [comment]
If I'm understanding correctly, the key issue is that the pseudocode is not robust to cases when Handshake packets are padded, which allows bytes_in_flight to be > 0, but no ack-eliciting packets are in-flight AND the server may still be blocked by the amplification limit?

I'll have to think about this more, but if you want to propose a PR, that would be helpful.

**Comment by Ralith** [comment]
Yeah, exactly. PR drafted based on the fix we've applied in Quinn.
