### ISSUE TITLE
Transport: Receiver/sender wording for MAX_STREAMS

### ISSUE THREAD

**Issue by WesleyRosenblum** [quicwg/base-drafts#4849]
[ §4.6](https://tools.ietf.org/html/draft-ietf-quic-transport-34#section-4.6) has the following requirement:

> Once a receiver advertises a stream limit using the MAX_STREAMS
   frame, advertising a smaller limit has no effect.  A receiver MUST
   ignore any MAX_STREAMS frame that does not increase the stream limit.

I believe this should be:

> Once a receiver advertises a stream limit using the MAX_STREAMS
   frame, advertising a smaller limit has no effect.  A ~~receiver~~**sender** MUST
   ignore any MAX_STREAMS frame that does not increase the stream limit.

This would be in line with the similar requirements for MAX_STREAM_DATA and MAX_DATA in [ §4.1](https://tools.ietf.org/html/draft-ietf-quic-transport-34#section-4.1):

> Once a receiver advertises a limit for the connection or a stream, it
   is not an error to advertise a smaller limit, but the smaller limit
   has no effect. [...] A sender MUST ignore any MAX_STREAM_DATA or 
   MAX_DATA frames that do not increase flow control limits.

**Comment by ianswett** [comment]
I believe the sentence was intended to read:
"A receiver(of the frame) MUST ignore any MAX_STREAMS frame that does not increase the stream limit."

**Comment by WesleyRosenblum** [comment]
Using "receiver" in this context is confusing, maybe it could just be replaced by "endpoint":

> Once an endpoint advertises a stream limit using the MAX_STREAMS
frame, advertising a smaller limit has no effect. An endpoint MUST
ignore any MAX_STREAMS frame that does not increase the stream limit.

Or just take the language from [§19.11](https://tools.ietf.org/html/draft-ietf-quic-transport-34#section-19.11):
> MAX_STREAMS frames that do not increase the stream limit MUST be
   ignored.
