### ISSUE TITLE
adjusted_rtt

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4860]
This was [raised on the mailing list](https://mailarchive.ietf.org/arch/msg/quic/Yrw8UH4tJISYTkJHSwLZhuqHvu0) by Timo Völker:
> I noticed in a simulation with a constant RTT that the smoothed_rtt value includes the ack_delay. It looks like my implementation follows the recovery draft. By looking closer, I believe I found a tiny error in the draft.
> 
> Section 5.3 contains this sentence.
> 
>> "MUST NOT subtract the acknowledgment delay from the RTT sample if the resulting value is smaller than the min_rtt."
> 
> I interpret this as do not subtract ack_delay from latest_rtt if
> 
>  latest_rtt - ack_delay < min_rtt
> 
> Or to say the inverse, substract ack_delay from latest_rtt if
> 
>  latest_rtt - ack_delay >= min_rtt
>  <==> latest_rtt >= min_rtt + ack_delay
>  <==> min_rtt + ack_delay <= latest_rtt
> 
> The pseudo code in Section 5.3 and in the appendix use a smaller instead of an equal or smaller in the if statement.
> 
>  if (min_rtt + ack_delay < latest_rtt):
> 
> It should be <= or did I miss something?

**Comment by janaiyengar** [comment]
This should have been closed with #4861.
