### ISSUE TITLE
Connection ID Lengths

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4865]
Invariants Section 5.2:  This document uses "Connection ID Lengths",
but draft-ietf-quic-transport uses "Connection ID lengths".  Would
you like to make usage of this term in these two documents consistent?

Original (this document):
> The short header does not
include the Connection ID Lengths, Source Connection ID, or Version
fields.

Original (draft-ietf-quic-transport):
> The header form bit, Destination and Source Connection ID lengths,
Destination and Source Connection ID fields, and Version fields of a
long header packet are version-independent.

Suggested (this document):
> The short header does not
include the Destination Connection ID Length, Source Connection ID
Length, Source Connection ID, or Version fields.

Suggested (draft-ietf-quic-transport):
> The header form bit and the Destination Connection ID Length,
Source Connection ID Length, Destination Connection ID, Source
Connection ID, and Version fields of a long header packet are
version independent.

I think that this is good and we should take the suggestions.

**Comment by nibanks** [comment]
LGTM. I like the consistency.

**Comment by MikeBishop** [comment]
Yes.  I think we've been consistent that the noun "length(s)" is not capitalized when talking about the value, but the name of the field ("Destination Connection ID Length") is.  However, it's reasonable to make this sentence reference the fields which are being affected rather than the information they convey.

**Comment by janaiyengar** [comment]
Fixed in #4868
