### ISSUE TITLE
Notation synchronization

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4866]
Invariants Section 4:  We see that the meanings for the notation
definitions appear to be the same as those for the notation
definitions in [QUIC-TRANSPORT], but some of the wordings are
different.  Please let us know if you would like the wordings to
match in both documents (and if yes, which document's wordings
should we use?).

Let's work this out.  I don't think that it matters much which wins, but there might have been changes that only made it into one or other document, so we should probably take the one that was updated last.

**Comment by janaiyengar** [comment]
This has been fixed.
