### ISSUE TITLE
keywords

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4867]
The RFC editor wants keywords for each of the drafts.

I suggest the word "protocol".

**Comment by MikeBishop** [comment]
`HTTP`, `WWW`, `web` for HTTP.  `Transport` for the transport document. `HTTP` and `compression` for QPACK.

**Comment by ianswett** [comment]
Possibly `congestion control` for recovery?

Is there an easy way to see the keywords for existing RFCs, I'm not sure where they are in the doc?

**Comment by martinthomson** [comment]
I guess my attempt at sarcasm was lost.  I don't think that the keywords thing is at all useful and that we should not bother to provide anything.

**Comment by ianswett** [comment]
What next?  Are [Drop Bears](https://en.wikipedia.org/wiki/Drop_bear#/media/File:Dropbear.jpg) not real?

**Comment by janaiyengar** [comment]
"next generation", please.

**Comment by janaiyengar** [comment]
transport: tcp/2, tcpng, transport-ng
recovery: FEC, loss-tolerant congestion control
tls: plaintext QUIC, opportunistic encryption
