### ISSUE TITLE
Permanent transport parameters

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#4880]
The RFC editor asks:
> Should the "QUIC Transport Parameters" registry include a "permanent" range (similar to the "QUIC Versions" registry)?  Or are values outside of those marked "provisional" all considered permanent?

I believe that this is just an error in transcription.  This should match the others and permanent assignments can be made with a specification.

I realize that this is super-late, but I realize that we reserved up to 0x3f for error codes (where size matters very little), but not for transport parameters (where size can matter).  Do we want to update that at the same time?

-- https://www.iana.org/assignments/quic/quic.xhtml

**Comment by DavidSchinazi** [comment]
I had assumed that we had reserved 0x00-0x3f in transport parameters too. I suspect that was the intent, and we just forgot to add that sentence. I would really prefer we update the doc to reserve 0x00-0x3f for transport parameters just like we do for errors.
