### ISSUE TITLE
Propose SLOT Frame

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#489]
A SLOT frame is packet oriented frame which is a simpler version of partially reliable transmission
(https://github.com/quicwg/base-drafts/issues/433).

It could be used in place of Stream 0 for handshake, and for game state services etc.

Semantics: a frame that has data similar to a stream frame, but no offset and it is limited to a single packet always. The frame has a SLOT ID similar to a FRAME ID but the SLOT ID can be reused indefinitely and the frame is not retransmitted. Ordering among slot frames is given by the packet number and the offset withint the packet, but it is not possible to tell how many slot frames were transmitted.

It is possible to have a second SLOT type that has retransmission. Optionally there could also be a sequence counter for the retransmittable slot.

**Comment by martinthomson** [comment]
My opinion only.

If the intent of this is to deal with the minor infidelity that sending a HelloRetryRequest introduces, then it is overkill.  If the intent is to define partial reliability, then I think that that this is out of scope (and likely also unnecessary).

**Comment by janaiyengar** [comment]
mikkelfj, partial reliability is currently explicitly out-of-scope. The charter says: "Extensions that will support partial reliability, and negotiation and use of Forward Error Correction schemes, are out of scope in this version of the working group charter."

Marking this as parked.

**Comment by mikkelfj** [comment]
Fair points - just please consider it as an option if it gets too complicated to formulate a handshake in the current form - there are probably many exceptions to made if stateless streams are to be supported.

**Comment by chocis** [comment]
I would love to see QUIC supporting non-reliable streams. It could be useful for games, IoT sensors and even VPNs based on QUIC, which all would have smaller performance hit, because of 1-connection (1 asymetric hanshake) with included benefit with easier load balancing (because of the Connection ID).

**Comment by janaiyengar** [comment]
There is definite interest in discussing partial reliability eventually, but it's scoped out of charter for now to allow focus on HTTP.

**Comment by martinthomson** [comment]
I'm closing this in the spirit of keeping on task.
