### ISSUE TITLE
Transport parameter advertisements

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#49]
We currently have no way of advertising things like flow control windows, maximum number of streams, etc...

Candidate is a QUIC extension that we include in the handshake.   This can include the QUIC version.

**Comment by MikeBishop** [comment]
#122 covers this, but isn't yet merged.  Is this part controversial?

**Comment by mnot** [comment]
Discussed in Tokyo; agreement that the parts of #122 that deal with this are good; should be factored out into a separate PR.

**Comment by martinthomson** [comment]
Closed with #122.
