### ISSUE TITLE
Auth48: Requests and required header fields

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#4947]
In [4.1.1.1](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.1.1.1), the RFC Editor asks:
> Because HTTP/3 requests is plural, may we update this as follows?
> 
> Original:
>>  All HTTP/3 requests MUST include exactly one value for the ":method",  
>> ":scheme", and ":path" pseudo-header fields, unless it is a CONNECT  
>> request; see Section 4.2.
> 
> Perhaps A:
>>  All HTTP/3 requests MUST include exactly one value for the ":method",  
>> ":scheme", and ":path" pseudo-header fields, except for CONNECT  
>> requests; see Section 4.2.
> 
> Perhaps B:
>>  All HTTP/3 requests MUST include exactly one value for the ":method",  
>> ":scheme", and ":path" pseudo-header fields, unless the request is a 
>> CONNECT  request; see Section 4.2.

**Comment by martinthomson** [comment]
Either A or B is better, but I have no preference.

**Comment by MikeBishop** [comment]
Fixed in #4954, but GitHub won't automatically close until it hits `main`.
