### ISSUE TITLE
Auth48: Capitalization consistency

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#4950]
Multiple related points (split slightly differently from how the RFC Ed did it):

> Throughout the text, the following terminology appears to be used 
> inconsistently. Please review these occurrences and let us know if any 
> updates are necessary.
> 
> - frame payload vs. Frame Payload
> - stream ID vs Stream ID

In general, the intent is to use "stream ID" or "frame payload" (lowercase) to refer to the identifier or payload itself, but "Stream ID" or "Frame Payload" (capitalized) to refer to the name of a field in a frame which carries an identifier or payload.  (Field names are intended to be capitalized in all cases.)  I will review instances of these terms to double-check whether that convention is used correctly throughout.

> Note that the authors of RFC 9000 indicated "stream ID" is correct.  This document introduces "Push ID" - should "stream ID" and "push ID" have the same capitalizaton? 

"Push ID" is deliberately capital, but by parallel with similar terms, it should probably be lowercase except when referring to the actual field.

**Comment by LPardue** [comment]
Push ID -> push ID suggestion works for me

**Comment by martinthomson** [comment]
Yep, as Mike says:
Concept: push ID
Field: Push ID

**Comment by MikeBishop** [comment]
Fixed in #4961.
