### ISSUE TITLE
Not Auth48: Control data

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#4953]
Http-core introduces a new term, "control data," and HTTP/2 has been updated to use this term.  HTTP/3 has not.  While it was not raised in Auth48, it might be appropriate to align this terminology before we publish these documents together.

**Comment by LPardue** [comment]
This seems like a good change for consistency, even if it might cause the document editor some short term pain.

**Comment by MikeBishop** [comment]
Closed in #4959.
