### ISSUE TITLE
Solidarity bot:  Invalid

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#4965]
Now that the Solidarity Bot is fixed again, it's flagging the term "invalid" several places in the H3 spec.  If anyone thinks this word should be changed in Auth48, here's the place to argue for it.  Some possible alternatives:  "not valid", "incorrect", "improper", "unacceptable".

**Comment by LPardue** [comment]
Wearing no hats: this seems like the type of change that could risk breaking the intention or interpretstion of current text.

The context of usage varies through the document, It feels too risky to change that at this stage.

**Comment by martinthomson** [comment]
I suspect that this is taking an interpretation that this is ableist, but I don't know if this particular usage meets that standard. I pronounce the two words differently even if they share a spelling.

That might be a poor assessment, so I won't insist that it is right. We probably can do better in future, but your conservative position here seems like it is best. Changing carries risks and without a clear signal that this needs to be fixed, doing nothing here is sensible.

**Comment by LPardue** [comment]
Agree.

I'll also highlight that the previous version of the bot didn't flag this term in the period it was running and we were more actively developing the document. Apply discretion to tooling updates against the status of our work seems fair. Here things are very late  the draft is already running in wide deployments.

In other documents for this WG, we have a bit more flexibility to incorporate the bots suggestions.

**Comment by MikeBishop** [comment]
Closing with no action.
