### ISSUE TITLE
Is "to the encoder" intended? (comment 2)

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4968]
Is "to the encoder" intended?  Should this be "within the encoder" or might "contain" be made "limit" or something else?

Original:

       QPACK is designed to contain the more complex state tracking to the
       encoder, while the decoder is relatively simple.

**Comment by MikeBishop** [comment]
"Limit" is probably the closest if we want to keep the phrase as-is.  Writing something *de novo* might be better, but I'm having trouble coming up with anything pithy.

**Comment by LPardue** [comment]
Some alternatives (aka throwing mud at the wall)

1. "The design of QPACK requires a encoder to implement relatively more-complex state tracking than a decoder."
2. "QPACK's design requires state tracking in various degrees of complexity. In relative terms, encoders have complex requirements, while decoders are more simple.
3. "QPACK is designed to put the state tracking complexity onus on encoders, resulting in relatively simple decoders."

**Comment by MikeBishop** [comment]
Fixed in #4988 with a variant of the third option.
