### ISSUE TITLE
Auth48: Artwork types

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4969]
Note that we updated instances of 'artwork type="drawing"' to type="ascii-art".  However, we wonder if any of these should be tagged as sourcecode instead.  Please review. 

Original (in the XML):  
   <artwork type="drawing" name="" align="left" alt=""> 

See <https://authors.ietf.org/rfcxml-vocabulary#sourcecode> for more information about sourcecode.

**Comment by MikeBishop** [comment]
In H3, I went with ascii-art for all of them.  However, QPACK includes some fairly substantial pseudocode.  These should probably be `sourcecode` instead.

**Comment by MikeBishop** [comment]
Fixed in #4982.
