### ISSUE TITLE
Packets that shouldn't generate Version Negotiation

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#497]
There are a bunch of things that might arrive at a server that aren't QUIC.  Not all of these need to generate a Version Negotiation packet in response.

We should insist that short-form packets are ignored.

We might also insist that a packet that isn't obvious an initial handshake packet be dropped.  That means that it needs to be at least 1232/1252 octets long.

These both might happen if routing is bad, if connection migration happens (and the client isn't using connection ID properly) or the server receives internet-chaff.  Better to ignore chaff than to waste effort on it.

**Comment by martinthomson** [comment]
Based on trying to write this up, I've concluded that this isn't a design decision any more.  Anyone who *wants* a design decision on this point is of course welcome to open a new issue.

**Comment by janaiyengar** [comment]
All we need to say is that a Version Negotiation packet is sent in response to only a Long Form packet. The rest of it seems unnecessary, since it's really not easy to detect a handshake packet: a client could just be sending a full-sized packet with a long header mid-connection.
