### ISSUE TITLE
Auth48: Difficult to parse sentence / duplicated words

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4970]
The repeated "when" clauses in this sentence make it
     difficult to parse.  If our suggestion does not correctly capture
     your intent, could you please rephrase?

Original:
A stream becomes unblocked when the Insert Count becomes
unblocked when the Insert Count becomes greater than or equal to the
Required Insert Count for all encoded field sections the decoder has
started reading from the stream.

Perhaps:
A stream becomes unblocked when the Insert Count becomes
unblocked.  When the Insert Count becomes greater than or equal to the
Required Insert Count for all encoded field sections, the decoder has
started reading from the stream.

**Comment by MikeBishop** [comment]
It actually looks as though the words "becomes unblocked when the Insert Count" are duplicated, which would make the corrected text:

> A stream becomes unblocked when the Insert Count becomes greater than or equal to the Required Insert Count for all encoded field sections the decoder has started reading from the stream.

That might still be confusing, but the proposed text certainly isn't the right change.

The key point to capture is:

- The decoder has started reading at least one encoded field section from the stream and encountered a Required Insert Count value in some or all of them which exceeds its current Insert Count.
- When the Insert Count is greater than or equal to the RIC value from all of the encoded field sections the decoder has attempted to process, the stream becomes unblocked.

**Comment by MikeBishop** [comment]
Fixed in #4926.
