### ISSUE TITLE
Auth48: Huffman-coded versus Huffman encoded

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4971]
May we update "Huffman-coded" with "Huffman encoded" in this text to match other uses?

Original:
They begin with a single bit flag, denoted as 'H' in this document
(indicating whether the string is Huffman-coded), followed by the
Length encoded as a 7-bit prefix integer, and finally Length bytes of
data.

**Comment by MikeBishop** [comment]
Fixed in #4986.
