### ISSUE TITLE
Auth48: SETTING_ => SETTINGS_

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4975]
Throughout, the document uses "SETTINGS_" as the first part of thte HTTP/3 setting names.  We have updated this sentence for consistency.  Please let us know if any corrections are needed.  

Original:

       For fomatting reasons, the setting names here are abbreviated by removing the 'SETTING_' prefix.

Current: 
   For formatting reasons, the setting names here are abbreviated by removing the 'SETTINGS_' prefix.

**Comment by MikeBishop** [comment]
Fixed in #4979.
