### ISSUE TITLE
Auth48: Capitalization and terminology consistency

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4976]
We had the following questions related to the terminology
used in this document.

a) Throughout the text, the following terminology appears to be used 
inconsistently. Please review these occurrences and let us know if/how they
may be made consistent.  

base vs. Base
post-base vs. Post Base
length vs. Length
delta vs. Delta Base

b) We have updated the following terminology to use the form on the right consistently to match what we feel was the intended use.  Please review and let us know any objections.

Instruction / instruction (e.g., Insert Count Increment instructions)

c) We see the use of both "single pass" and "one pass" in this
document.  Please review if these should be made uniform.

**Comment by MikeBishop** [comment]
"Length" is capitalized in several difference situations in the prose:
- In 4.1.2, defining string literals, "Length" is used interchangeably to refer to the length of the string and the field which contains that value.
- In field names ("Value Length", "Name Length") when representing the length-part of string literals
- In field diagrams, indicating the length of a field whose length was indicated by the previous field ("Length bytes")

It seems to me that the first should be fixed while the second is fine.  The third might benefit from a different means of indicating the size of the field, but it's not as obvious.

**Comment by MikeBishop** [comment]
I don't see any instances of (capitalized) "Instruction" in the document which aren't title-cased or the first word of a sentence.  That's fine.

The one instance of "One Pass" could be normalized to "Single Pass" without issue.

**Comment by MikeBishop** [comment]
Fixed in #4989.
