### ISSUE TITLE
Wiki: Implementations overview "destroyed"

### ISSUE THREAD

**Issue by zirngibl** [quicwg/base-drafts#5002]
Hi, 

Is there any reason the [implementations overview](https://github.com/quicwg/base-drafts/wiki/Implementations) in the wiki got destroyed or can it be recreated? 

I thought it was a great overview of existing implementations and their support of documents.

**Comment by LPardue** [comment]
Thanks for the report @zirngibl . It seems we suffured some recent vandalism. I've restored the page back to how it was. 

To avoid repeat offences, I'm locking down the wiki write access to only identified collaborators.
