### ISSUE TITLE
Stream ID 24-bit encoding?

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#508]
Similar issue to #507: The STREAM frame still allows a 24-bit encoding of the stream ID, which I think counts as one of the odd lengths we were going to eliminate.

**Comment by martinthomson** [comment]
Note: It may cost nothing, but save a large number of bits.  At one STREAM frame per stream, we're still talking 16 million frames.  It's hard to get excited about one byte though...

**Comment by ianswett** [comment]
8/16/32/64 would make sense and be more consistent, except we decided there wasn't a use for >32 bit stream ids.

**Comment by mikkelfj** [comment]
If you have 100K IOPS each represented by a single frame, your connection will last 12 hours with 32 bit stream identifiers. Moving to 64 bit would mean you can design applications without thinking about this limitation even if it would rarely be hit in praxis.

**Comment by larseggert** [comment]
-04 still allows "8, 16, 24, and 32 bits". If this is what it's going to be, we can close this issue?

**Comment by martinthomson** [comment]
Well, if we want to remove 24, then we can still decide to remove 24.  I'm not a piece of seating, but I'm not seeing much movement toward resolution.

**Comment by janaiyengar** [comment]
I'd like to keep 24 around. My reasoning is that there is a non-zero benefit for having it, and > 32 is  not something we need to engineer for in this version. We can rev a version if we really need > 32. And since we're using 2 bits to represent stream ID size, makes sense to use 4 sizes.

**Comment by janaiyengar** [comment]
I'll close the issue; please feel free to open it if you want to change the stream id sizes.

**Comment by mikkelfj** [comment]
I would like a 64-bit stream id - because it completely removes the need for application logic to care about this limitation since other limits happen much earlier, and because it makes it viable to really throw away small streams on long living connections.

**Comment by martinthomson** [comment]
@mikkelfj, we have discussed expanding the stream ID space to 64 bits and we explicitly decided not to.  If you have **new** information, please find the issue and add your new information there.  "I would like" isn't really strong enough to cause us to re-litigate the issue.
