### ISSUE TITLE
QUIC version number scheme

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#51]
There have been proposals on the list. We need to finalize a version number scheme for QUIC versions.

**Comment by MikeBishop** [comment]
#113 addresses this.

**Comment by mnot** [comment]
Discussed in Tokyo; consensus in the room. EKR asked for notice about existing QUIC versions in the document.

**Comment by ekr** [comment]
@mnot: I don't see that the notice about existing QUIC versions made it into the draft.

**Comment by martinthomson** [comment]
I'd prefer to track the omission, so that the larger issue isn't reopened.  That we neglected to mention Google QUIC versions is just an error.

**Comment by janaiyengar** [comment]
Why do we need a notice about Google QUIC versions in the draft? They fit in the experimental version space (by design), and are now listed on the wiki. As Google goes through them, old versions won't need to be listed. They don't conflict with the space carved out for IETF work.

**Comment by ekr** [comment]
Because it makes life clearer for people trying to understand how the world works. What's your objection?

**Comment by janaiyengar** [comment]
We agreed to list experimental versions in the wiki. Are we listing them in the draft as well?

**Comment by ekr** [comment]
I think that experimental versions that have been widely deployed probably make sense to be in the draft. Again, what's your objection?

**Comment by janaiyengar** [comment]
That the versions are changing, and the "widely deployed ones" today won't be around within a month or so? We have this list on the wiki, which is where all other experimental versions will live. 

Again, why do we need a list in the draft when the process was to list experimental versions on the wiki?

**Comment by ekr** [comment]
They'll still be floating around in packet traces, source code repos, archives, and the like. As I said, I think this will make things easier and I can't see that it's harming anything. As far as "the process" goes, when we had this discussion in Tokyo, I explicitly requested that the gQUIC versions be in the draft and I don't remember there being significant objections, hence Mark's recorded resolution of Jan 23. 

Honestly, Jana, I'm really having a hard time seeing why you're fighting this. Aren't there bigger things to argue about?

**Comment by janaiyengar** [comment]
I don't think you understand what I'm saying. My first question was "Why do we need a notice about Google QUIC versions in the draft?" since they're listed on the wiki. I haven't changed my question since you haven't answered it. Perhaps you believe that folks will read the draft but not the wiki, but that's inconsistent with the plan for experimental versions.

That said, I really don't care about adding this, so I'll stop. I was really sincerely trying to understand.

FWIW, arguments always need at least two people to participate. I'm not arguing, I was actually honestly trying to understand what you gain from this (and I still don't get it.) Saying "Aren't there bigger things to argue about?" doesn't move any conversation forward and risks seeming disingenuous.

**Comment by ekr** [comment]
> I don't think you understand what I'm saying. My first question was "Why do we need a notice about Google QUIC versions in the draft?" since they're listed on the wiki. I haven't changed my question since you haven't answered it. Perhaps you believe that folks will read the draft but not the wiki, 

Yes, I should have thought that would be obvious.


> but that's inconsistent with the plan for experimental versions.

No, I don't think so. The point of reserving code space for experimental versions is so people don't step on each other. When you have an experimental version that's very widely deployed, it's useful for readers to be able to pick up on it without having to go to the wiki. This is similar to the reason why we describe how to determine the version number for each draft in S 4 rather than having it on the wiki. You may or may not find it valuable, but I think it would be so, and, as I said, it seems like at worst it's harmless.


> FWIW, arguments always need at least two people to participate. I'm not arguing, I was actually honestly trying to understand what you gain from this (and I still don't get it.) Saying "Aren't there bigger things to argue about?" doesn't move any conversation forward and risks seeming disingenuous.

i don't think any response I can give to this will be productive.

**Comment by martinthomson** [comment]
The close hammer strikes.  @ekr, if you want a change, I think that you will have to supply text (and another issue, though in this case a PR would be OK, since it's basically editorial).
