### ISSUE TITLE
Describe how and why a server might choose connection IDs

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#514]
In #493 there are multiple server-chosen connection IDs, and a set of examples describing the intent of the design ought to be useful for implementers and deployments. This may belong in the applicability statement.

**Comment by igorlord** [comment]
I was going to write something up about this in Applicability, once we settle treatment of the Connection ID in the protocol.

**Comment by mirjak** [comment]
Yes please send text; I'll put a place-holder in for now!

**Comment by janaiyengar** [comment]
Moved to https://github.com/quicwg/ops-drafts/issues/29.
