### ISSUE TITLE
A server can't send SETTINGS first

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#515]
Stream 1 is a client-initiated stream.  That means that the server can't send its SETTINGS frame to the client until it reads the end of the client handshake and stream 1 is opened.  That's annoying because the server could otherwise send frames to the client after it sends its ServerHello.

In addition to SETTINGS, the server might use this otherwise dead air to send things like ORIGIN frames or secondary certificates.

This would not be a problem if streams were unidirectional ;)

**Comment by janaiyengar** [comment]
Alternatively, Stream 2 is available.

**Comment by janaiyengar** [comment]
If there are specific things that you'd want the server to be able to send, we could reserve stream 2 for it. But I suppose SETTINGS would need to be received before the client processes things on stream 1, right? In which case, ordering between stream 1 and 2 will become an issue... hm.
