### ISSUE TITLE
State bikeshedding time

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#520]
"half-closed (local)" might be a little obtuse.  "write-closed" or "read-only" might be better names.

Release the hounds.

**Comment by LPardue** [comment]
Would these states become redundant if the "unidirectional streams" concept takes foot

**Comment by MikeBishop** [comment]
Somewhat.  If the unidirectional flavor is pairs of unidirectional streams, these could be defined shorthand for the state of a pair.  If it's completely independent streams in each direction, yes, they're obsolete.

**Comment by ianswett** [comment]
I think Martin's inflight #894 will solve this issue.

**Comment by MikeBishop** [comment]
Yes, but the corollary on frame names is still there....  RST_STREAM => WRITE_ABORT, STOP_SENDING => READ_ABORT make even more sense after #894.

**Comment by martinthomson** [comment]
Fixed!
