### ISSUE TITLE
Handshake packets and is_retransmittable

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#526]
The definition of `is_retransmittable` only talks about packets that are containing various frame types. But it should also talk about handshake packets requiring retransmission, because otherwise the pseudo code for `OnPacketSent` never calls `SetLossDetectionAlarm`. 

(Or a call to `SetLossDetectionAlarm` needs to be explicitly added for handshake packets.)

**Comment by larseggert** [comment]
Or is there an implicit assumption that handshake packets will always carry stream-0 data?

**Comment by ianswett** [comment]
Yes, handshake packets must always carry stream-0 data.  I can clarify that.

**Comment by janaiyengar** [comment]
Yes, since all handshake data is carried in STREAM frames, they will be retransmittable by definition. Would it help to clarify this somewhere?

**Comment by janaiyengar** [comment]
(sorry, didn't see Ian's response.)

**Comment by larseggert** [comment]
I tripped over this, because my implementation currently doesn't have stream-0 data in the handshake packets (since I am still looking for a TLS lib that has a suitable API). I've now addressed this by faking the stream-0 TLS handshake, but a few words on this might be useful.

**Comment by mikkelfj** [comment]
@larseggert is there a place for a non-TLS profile of QUIC? Chrome is currently using Curve25519+AES-GCM + possibly SHA256/HKDF key derivation logic. This crypto can be implemented in very compact self-reliant code that does not require a complex TLS library and as such may be highly useful for embedded IoT devices. So why not formalize such a profile rather than hack around missing TLS libraries. I'm not suggesting to abandon TLS, but to provide a formal alternative with a much simpler handshake.

**Comment by larseggert** [comment]
@mikkelfj that discussion should happen in a separate ticket. 

(I have no horse in the race with regards to TLS or something else. But I also don't want to implement any crypto code. Ideally, I want to link against a minimal but widely used and audited library that lets me remain in control memory allocation and packet I/O.)

**Comment by MikeBishop** [comment]
Correct; SChannel is a Windows component, not an open-source library.

@mikkelfj, there is definitely a place, in my opinion.  I wouldn't be surprised to see an IoT-focused working group define a stripped down profile with some other handshake, and several of the issues we've debated around versioning and handshake mechanics are aimed at making TLS replaceable in subsequent work.  However, the alternate profile needs to supply similar properties:  key agreement, parameter transport, etc.  The *definition* of such a profile is explicitly outside the charter of this WG, though.

**Comment by mikkelfj** [comment]
OK, I'll leave it at that - a new ticket would be out of charter I suppose. Perhaps a wiki page could be useful for coordination? On crypto librariaries I have seen none that matches all of minimal, widely used and audited - but the components I mentioned are readily available with test vectors and can be liftet.
