### ISSUE TITLE
type octet language and public reset value

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#527]
transport commonly refers to a type octet when referring to long header packet types.. (e.g. 0x88) but the type field is defined as 7 bits and the long header packet type table lists values without the high bit (e.g. 0x08). I think we're better off without the type octet concept.

Also, public reset is defined in the table as having value 9, but in 5.6 as having a type octet of 0x88 which is already used by keyphase 1 protected packets. I think 9/0x89 is the intention. I would open a separate issue, but the merge conflict is inevitable :)

**Comment by janaiyengar** [comment]
"type field", then? 
or we can go with "type septet" :-)

**Comment by janaiyengar** [comment]
I think this change sounds reasonable.

**Comment by janaiyengar** [comment]
Addressed in #528
