### ISSUE TITLE
OnPacketAcked defined twice

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#533]
There are two different blocks of pseudo code for `OnPacketAcked`, one in Section 3.2.6 and a different one in 4.6.

**Comment by ianswett** [comment]
One is for congestion control and one is for recovery.  Any suggestion on a good way to tweak the naming to make it clear they're invoked on the same event, but are different modules?

**Comment by larseggert** [comment]
Give them two names, and call them one after the other where they need to be called from?
