### ISSUE TITLE
SetLossDetectionAlarm issue with TLP

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#537]
The pseudo code in Section 3.2.7.4 has this conditional `return` in the beginning:
```
SetLossDetectionAlarm():
    if (retransmittable packets are not outstanding):
      loss_detection_alarm.cancel()
      return
```
Afterwards, in the TLP case, it says:
```
      // Tail Loss Probe
      if (retransmittable_packets_outstanding = 1):
        alarm_duration = 1.5 * smoothed_rtt + kDelayedAckTimeout
      else:
        alarm_duration = kMinTLPTimeout
```
Given that the code would already have returned (per above) if `retransmittable_packets_outstanding` is false, how can the `else` clause here ever be executed?

**Comment by ianswett** [comment]
The early return ensures we don't set an alarm if there's no retransmittable data in flight.

If we get to the TLP section, retransmittable_packets_outstanding is 1 or larger.  So the else is for the >1 case.  I did just add a comment to that effect and use retransmittable_packets_outstanding in the first condition for consistency.

Does that make sense?

**Comment by ianswett** [comment]
Oh, I see your confusion.  retransmittable_packets_outstanding is an int, not a bool.

**Comment by ianswett** [comment]
I just renamed it to num_retransmittable_packets_outstanding, which I think should fix your confusion.
