### ISSUE TITLE
sent_packets and duplicate ACKs

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#541]
I'm not sure if the pseudo code around the `sent_packets` association correctly handles the case of duplicate ACKs. It seems that ACKed packets are removed from the association on first ACK, and information about them is therefore not present anymore when a repeated or duplicated ACK arrives?

**Comment by ianswett** [comment]
Yes, currently the pseudocode does nothing to handle track spurious retransmits, because it makes the psuedocode somewhat simpler.  

Adding proper handling is certainly possible, do you think it's worth the extra complexity?

**Comment by larseggert** [comment]
I don't know. That duplicate ACKs aren't handled make the current pseudo code IMO not very useful. However, complicating it a lot is also not great. Would some comments in the pseudo code be a middle ground? Or at least the text should explain the issue and that the pseudo code is not handling it.

**Comment by ianswett** [comment]
Re-reading this, I'm less sure I understand your comments about duplicated acks.  A packet is only acknowledged once and then there's no need to track it, since acks are irrevocable.  

The code is using FACK style loss detection(or time), so there's no need to store a dupack count anywhere.

**Comment by larseggert** [comment]
I think this issue has become stale - closing
