### ISSUE TITLE
What to do if a skipped packet is acknowledged

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#546]
#415 was submitted, but I think that that was in error.

**Comment by martinthomson** [comment]
To be clear, I think that the transport document is where this sort of requirement belongs.

**Comment by ianswett** [comment]
I tend to agree, now that you mention it.  The reference to a connection close error makes it clearer to me that it should be in transport.

**Comment by ianswett** [comment]
Closed with PR #555
