### ISSUE TITLE
broken packet-numbers reference

### ISSUE THREAD

**Issue by bagder** [quicwg/base-drafts#549]
In the HTML version of the [draft-ietf-quic-transport-03 document](https://tools.ietf.org/html/draft-ietf-quic-transport-03) in section 5.1, there's a broken reference. It looks as:

```
   Packet Number:  Octets 9 to 12 contain the packet number.  {{packet-
      numbers} describes the use of packet numbers.
```

While it should've become a link to the "5.8 Packet Numbers" section, surely.

**Comment by martinthomson** [comment]
Thanks @bagder, fixed in 8688539.
