### ISSUE TITLE
Clarify bytes in flight in recovery

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#550]
#395 mentions bytes_in_flight, but does specify what this means:  IP, UDP and QUIC header? ACK's, or just the sum of retransmittable frames, or just stream payload?

**Comment by ianswett** [comment]
I'll send you a PR to state what GQUIC does today.  That's not to say it's the only way to count bytes, but it's quite analogous to how TCP does it, which I think is a good start.
