### ISSUE TITLE
RTO Limits

### ISSUE THREAD

**Issue by lucas-clemente** [quicwg/base-drafts#556]
In the current version of the loss recovery draft there's neither a maximum exponent, nor an absolute maximum for the RTO timeout. (In gQUIC these are 10 and 60ms.) Is this an intentional omission?

**Comment by ianswett** [comment]
Good point, in practice GQUIC almost always hits the idle timeout long before those limits are hit, particularly the max exponent.

I think we should say something about a max, and make it clear either there should not be one, or that there should be and what it is.  I can see the benefits of both.

Suggestions?

**Comment by lucas-clemente** [comment]
Seems reasonable for the exponent, but I'm not sure the max timeout value can be discarded so easily. 60ms is much shorter than the ICSL, so it should make a difference from time to time, right?

**Comment by lucas-clemente** [comment]
Oh wait, nvm. I though it was 60ms, but it's 60s. Then I agree with you fully.

**Comment by ianswett** [comment]
Yes, 60ms as a max would be insanely short.  I thought you just mis-typed before.

Should I document the 60s max then?

**Comment by lucas-clemente** [comment]
Sorry, just had a brainfart there… I don't think it really makes a difference then, just wanted to make sure it was intentional.

**Comment by mikkelfj** [comment]
I haven't read the details, but quic input here: different applications might want different timeouts. 60s sounds fine, but certain low latency applications might want to disconnect if it doesn't get a response much sooner than that and choose another peer. Point being, make room for this in spec.

**Comment by ianswett** [comment]
Reopening based on discussion in Paris.

**Comment by ianswett** [comment]
Can anyone remember what else needed to be done to resolve this that was discussed in Paris?
