### ISSUE TITLE
More than 1 Client Initial Packet

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#558]
You might need more than 1 client initial packet (perhaps an over enthusiasm for tls client hello extensions?)..

The text says 

> The payload of a Client Initial packet consists of a STREAM frame (or frames) for stream 0 containing a cryptographic handshake message, plus any PADDING frames necessary to ensure that the packet is at least the minimum size (see Section 9). This stream frame always starts at an offset of 0 (see Section 7.4).

which raises a few of questions..

1] the phrase "required to be at least the minimum size" sounds like a tautology.   Perhaps "minimum MTU size" would be better

2] should the extra packets (those not containing offset 0) be required to be padded too? At least for reasons of reflection attacks it doesn't seem so. The https://github.com/quicwg/base-drafts/wiki/First-Implementation-Draft speaks of the first client packet being 1280 which made me wonder about this.. but perhaps it really just meant initial client packet rather than the first initial client packet :)

3] the language of "this stream frame always starts at an offset of 0" is funny as it speaks of a singular "this" after acknowledging the packet may have multiple frames and then there is the case of multiple packets. Perhaps the clause can just be removed as all streams semantically start at offset 0 and the various out of order reassembly rules don't seem different for this packet.

**Comment by ianswett** [comment]
If you need more than 1 client initial packet, it's easy to force the servers to store state.

It's possible there are simple solutions to this, such as limiting the number of partial CHLO's the server will store, but not allowing it would be the simplest solution.

**Comment by mcmanus** [comment]
7.2 (a looooong way away from the definition of client initial packet) does indeed limit you to a single packet. which seems sane.

perhaps this can be closed with editorial bits for questions 1 and 3 and note regarding 7.2 all in 5.4.1?

**Comment by mcmanus** [comment]
that's a poorly named pr #559
