### ISSUE TITLE
ACK prohibitions

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#563]
As pointed out by mcmanus@, since there are packet types that echo the packet number, these must not generate acks. This should be explicitly noted. Similarly, it may be helpful to explicitly list the frame types that must not generate acks (all non-retransmittable frames).

**Comment by martinthomson** [comment]
Maybe it would be better to enumerate the reliability options more generally.  For instance:

The client automatically repairs its Client Initial packet by sending it on a timer.  A server repairs Version Negotiation and Stateless Reject packets by sending one for each packet that it receives, so usually this chains off the client's strategy.  After that, packets are repaired using ACK frames.  All other packets are acknowledged using ACK frames, except those that only contain ACK and PADDING frames.

**Comment by larseggert** [comment]
I think the entire text related to when to generate ACKs, what should be in generated ACK blocks, what information sender and receiver need to maintain for the packets and ACK blocks they send and receive may need some more explanation, and maybe examples. QUIC is sufficiently different from other IETF transport protocols here that at least for me, many details remain unclear.

**Comment by mcmanus** [comment]
I think this specific issue should be closed with simple statements about the 2 packets in question (and maybe Public Reset for good measure).

but to lars's point I think there is a lot of ack related language that could lead to interop issues. Below is one of my favorites, which leads the casual reader to wonder just how required ack is :)

> To limit receiver state or the size of ACK frames, a receiver MAY limit the number of ACK blocks it sends. A receiver can do this even without receiving acknowledgment of its ACK frames, with the knowledge this could cause the sender to unnecessarily retransmit some data. When this is necessary, the receiver SHOULD acknowledge newly received packets and stop acknowledging packets received in the past.
