### ISSUE TITLE
loosen MUST requirement around close-on-ack-of-unsent

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#564]
>  sender MUST close the connection if an unsent packet number is acknowledged

I suggest s/MUST/SHOULD .. doing this as MUST requires keeping the state of every unused packet number for the entire duration of the connection to separate the ack of concern from a duplicated ack.

**Comment by martinthomson** [comment]
This seems sensible.  Anything other than MUST NOT has the right effect, though I think that SHOULD is a nice spot.

Of course, there are designs that would have us avoid skipping packets entirely, which reduces the state commitment considerably.

**Comment by siyengar** [comment]
Thanks for bringing this up, I encountered this exact same issue last week when implementing it and was going to bring it up myself as well :)
