### ISSUE TITLE
packet number text limitation on 32 bits of packet number

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#566]
5.8 introduces the fact that only the least significant bits of a packet number are transmitted and it goes on to say at most 32.

But acks can use 48.

I suggest fixing by just leaving out the number.

**Comment by mirjak** [comment]
I was about to fill the same issue this afternoon (and then got distracted). We could remove the number completely or say that the internal packet number size must be at least 64 bits

**Comment by larseggert** [comment]
Yes, see #507 (and #508)

**Comment by larseggert** [comment]
-04 still allows 48 bits in the ACK frame?

**Comment by martinthomson** [comment]
Only because we didn't get around to making those changes.  We agreed to move fast on -04 and we didn't have a PR for removing 48.

**Comment by janaiyengar** [comment]
this is a dup of #507 so closing.

**Comment by ianswett** [comment]
I didn't realize we were cutting 04 today, but PR #629 has now fixed the 48 bit issue.
