### ISSUE TITLE
Advice on STOP_WAITING

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#57]
Martin Duke observes that until STOP_WAITING is acknowledged, you can't assume that it has had an effect.  This means that anything that depends on the number of "in flight" packets can't assume that packets before the Last Unacked packet aren't still considered as in transit by the receiver of the STOP_WAITING.  This is particularly relevant for determining how many bits to allocate to packet numbers.

We might just provide advice here, but I've marked this as design so that we can discuss it.

**Comment by ianswett** [comment]
The sender always knows how many packets it has in flight, so I don't believe this is a problem.  In the worst case, ack frames from the receiver inform the sender of the largest packet the peer has received, and new packet numbers are always decoded relative to the largest ever received, so the gap between the largest acked and the current packet number is the critical value. 

That being said, there was a previous conversation between Marten Seemann and myself on proto-quic on removing STOP_WAITING entirely, and I suspect that's the right way to go.

All this being said, the section on determining the correct packet number length to use could use substantial improvement, including rationale for the logic.

**Comment by martinthomson** [comment]
Ian, I am going to open an issues on both of those.  And you will be assigned them.  If this becomes redundant, then we can close it.

**Comment by ianswett** [comment]
Thanks, sounds great.

**Comment by mnot** [comment]
Superseded by #66
