### ISSUE TITLE
Limit what Version Negotiation can be sent for

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#570]
In #568, I noted that Version Negotiation doesn't really need to be sent in response to anything other than a client initial packet.  Those currently have two properties that we could hook into if we wanted to fix those properties across all QUIC versions: the packet type octet, and the size.  Either or both of those could be used as a way to filter non-QUIC noise from QUIC so that servers don't generate Version Negotiation unnecessarily.

I don't think that doing this represents a particularly big commitment, but we should be careful.  The minimum size seems like it might be a constant across versions.  The packet type might be a little rough, particularly in light of techniques like that suggested in #311.

**Comment by mikkelfj** [comment]
Initially it does seem advantageous to reject small packets serverside. However, forcing a minimum initial packet size across all versions could be problematic - especially for non-linear special purpose versions. For example, resource constrainted battery powered networks.

If a reasonable checksum is added to all clear text, this would serve the same purpose. Constrained devices with special versions may reject large packets and packets with invalid checksums. Ordinary servers that require large initial packets may reject on small packets and on invalid checksums.

**Comment by RyanAtGoogle** [comment]
On Sat, Jun 3, 2017 at 11:35 PM, MikkelFJ <notifications@github.com> wrote:

> Initially it does seem advantageous to reject small packets serverside.
> However, forcing a minimum initial packet size across all versions could be
> problematic - especially for non-linear special purpose versions. For
> example, resource constrainted battery powered networks.
>
> If a reasonable checksum is added to all clear text, this would serve the
> same purpose.
>
​Of course, that requires the checksum to be version independent, right?​

**Comment by mikkelfj** [comment]
> ​Of course, that requires the checksum to be version independent, right?​

I probably is convenient to have it version independent, but since the initial packet has a version listed, it only requires that the server knows enough of the version to accept the checksum, or alternatively for the server to test a few known algorithms as long as the cost of doing so is not prohibitive.
