### ISSUE TITLE
Connection migration symmetry

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#573]
With the introduction of the NEW_CONNECTION_ID logic, a client can perform a connection migration that can't be correlated by an external observer. This works fine in the classic server-client setting, but (as pointed out in the discussion of #491) for p2p connections, both peers might want to perform such a connection migration.

**Comment by martinthomson** [comment]
See also #490.

**Comment by ianswett** [comment]
It's believed #560 and Connection Migration(#1012) should be sufficient for the HTTP over QUIC goals of v1, tagging this as v2.

**Comment by MikeBishop** [comment]
(...with the additional note that if those land and we manage to progess a PR sufficiently, nothing prohibits us from pulling this back.)
