### ISSUE TITLE
Need to distinguish Client Initial Packet with client Connection ID from one with server Connection ID

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#577]
Current text says that "The client populates the connection ID field with randomly selected values, unless it has received a packet from the server."

We need to be able to tell a different between Client Initial Packet with client-generated connection ID and Client Initial Packet with server-generated connection ID. I would suggest adding a packet type.

**Comment by martinthomson** [comment]
The current design has Client Initial (or just Initial) packets including a client-chosen connection ID always.  Is this still a problem @igorlord?

**Comment by igorlord** [comment]
No. This is no longer an issue. The current design has exactly two packet types that carry client-chosen connection id: "Client Initial" and (client's) "0-RTT" packets.
