### ISSUE TITLE
What is "legacy clients" in transport draft? 

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#578]
Section 1, has the following sentence:

Using UDP as the substrate, QUIC seeks to
   be compatible with legacy clients and middleboxes.

What does it mean to be compatible with legacy clients? 

Being compatible with a legacy client appears to imply that one can have a meaningful interaction, I don't see how that is possible. Is it the aspect that one can deploy on existing operating systems without operating system modifcations that one is after? In that case, please reformulate.

**Comment by MikeBishop** [comment]
Yes, I think that's the goal.  You can deploy QUIC as an application-included library on any operating system that provides UDP support, regardless of whether it provides QUIC support.
