### ISSUE TITLE
Recovery: Handshake Packet is not using constant names, and uses wrong default

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#587]
Recovery -03: Section 3.2.7.1:

If no previous RTT is available, the
   initial RTT defaults to 200ms.

This should reference the default konstant defined, and the value is currently set to 100 ms.

**Comment by ianswett** [comment]
This is being removed in PR #921

**Comment by gloinul** [comment]
So -10 resolves the mismatch about default. And I am fine with not using pseudo code constants in description.
