### ISSUE TITLE
5-tuple is stable during handshake

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#594]
We need to state this as an assumption.  This is particularly relevant in the case where we have version negotiation and a rebalancing of the connection-id-based routing on the server cluster.  We're opting for a hope-based solution here and assuming that the server will be the same (or at least run the same versions) and that the 5-tuple is enough to keep the routing the same.

**Comment by mikkelfj** [comment]
What is the motivation for not simply chaining Connection ID changes? That is if client sends CCID and server changes to a new SCCID, the old CCID could be chained in that packet, and so forth on path changes. It would simplify many things. Except for the initial handshake these chains are not observable from outside the connection.

**Comment by mikkelfj** [comment]
Of course, regardless of chaining, it must be a requirement that packets are routable to the recepient, but that is different from requiring a stable 5-tuple.

**Comment by igorlord** [comment]
This came up as a requirement for settling #588 in Paris.

**Comment by mikkelfj** [comment]
But if a stable 5-tuple is required, it should probably also be unique. The uniqueness requirement can be avoided with chaining Connection ID's.

**Comment by martinthomson** [comment]
Let's defer this until #1012 is landed.  Then we can add text about that to the connection migration section.
