### ISSUE TITLE
Transmitting ACK frames

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#601]
Raised on draft-ietf-quic-recovery-03

I find nothing discussing the transmission of ACK Frame in the recovery draft. It includes process for how to process the received, including delayed ACK transmission using default 25 ms, but their is no specification regarding how and when the delayed ACK transmission should be used, and how often in relation to received packets a peer should transmit ACK frames. 

I also do not find these details in the transport-03 draft. But, I think they actually belong here, as ACK thinning for high rates as well as timed delayed ACK is primarily functions for loss recovery and congestion control behavior beyond the initial handshake.

**Comment by mnot** [comment]
Dup of #230.
