### ISSUE TITLE
Transport: Client IP change reason

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#606]
draft-ietf-transport-quic-03, section 7.6: 

   QUIC's consistent connection ID allows connections to survive changes
   to the client's IP and/or port, such as those caused by client or
   server migrating to a new network.

I don't understand how a sever network migration changes the client's IP address. Or is it intended to discuss forced changes to the IP/UDP 5-tuple to reach the server in general?

**Comment by martinthomson** [comment]
We already have an open issue that is aimed at documenting the situations in which the connection ID helps, the limitations on that, and so forth (see #115).

As I understand it, the limitation of the proposal is that an endpoint can change its source address (IP or port) and then send and still have the packet arrive at the right destination.  However, after moving, an endpoint won't be able to receive anything until it sends something.  This is what makes simultaneous migration hard/impossible (see #490).

@gloinul, do you think that those two issues cover your concerns?

**Comment by gloinul** [comment]
Yes, I think the clarification of those two issues, will results in the text being addressed. So, yes we can close this one.
