### ISSUE TITLE
Report exactly what caused a frame decode error

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#607]
In Paris, when discussing what error codes to include in the connection close, the idea of optionally specifying a packet number and a byte offset into the packet where the error occurred seems potentially useful for debugging.

This wouldn't allow automated error analysis(unless one saved every packet ever sent), but for a given reproducible error, it could help dramatically.

**Comment by mikkelfj** [comment]
While rather useful, I would suggest printing such information to a string without standardizing.

Also, I assume this is fully encrypted, otherwise there could be potential crypto attack concerns. On a releated note: error text is variable length and also open to crypto analysis.

**Comment by ianswett** [comment]
There's a string in the close frames for details, and no one expressed a strong need for this.  Closing.
