### ISSUE TITLE
Handshake errors

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#608]
If the handshake fails, how do we signal that?  We could send CONNECTION_CLOSE in the clear...

If version negotiation fails, how do we signal that?  I don't think that we can, though we currently require that.

**Comment by mikkelfj** [comment]
Sending in clear would allow adversaries to close the connection if they can guess the tuple.

**Comment by martinthomson** [comment]
This is a valid concern.  Note that an adversary is able to interrupt a connection in many ways prior to the establishment of a shared key.  For example, a spurious Version Negotiation packet, a modified TLS handshake message, many things...  Some of those are quite hard to detect.

**Comment by mikkelfj** [comment]
There are many topics overlapping this by now - including https://github.com/quicwg/base-drafts/issues/554

I believe all of these can be sufficiently mitigated by having a server and client nonce in all packets. An attacker needs to guess the nonce which is hard for 64-bit - combined with FNV-1a checksum it is probably very hard to attack off-path.

**Comment by nibanks** [comment]
Has a decision been made as to whether CONNECTION_CLOSE can be sent in cleartext? The latest spec doesn't whitelist it, so I am assuming not; but I haven't seen clear indication either way.

**Comment by janaiyengar** [comment]
Revisiting this question, I think we have a small bit of a pickle. From #645, we agreed in Prague that "Off-path attacks would be protected against by using return routeability/proof of receipt." Server Cleartext carries a brand new packet number and carries a server-chosen connection ID, which means there's no proof of receipt in this packet. We should address this.

We could simply require that a Server Cleartext packet that closes a connection MUST echo the client's connection ID. This ought to be ok, since this connection is getting torn down, so there won't be a need to use a new connection ID anyways.

**Comment by ekr** [comment]
The plan was that Server Cleartext is going to be integrity protected with
a key derived from the client connection ID. I'll try to get to the PR this
week.

**Comment by RyanAtGoogle** [comment]
Presumably this means the client's connection ID, not the server's right?

**Comment by janaiyengar** [comment]
Good point -- it should be the client's connection ID, otherwise there's no proof of receipt. The Server Cleartext however carries a server-chosen Connection ID, which makes this all just a bit confusing unfortunately.

**Comment by siyengar** [comment]
When implementing this, I'm sending CONNECTION_CLOSE in a plaintext packet if the TLS handshake has not finished yet. I ran into a case where the cert validation failed, however I wasn't really able to indicate this with a reasonable error code. Should we have an error code for TLS_ERROR or HANDSHAKE_ERROR

**Comment by martinthomson** [comment]
Like TLS_HANDSHAKE_FAILED (0x201)?

**Comment by janaiyengar** [comment]
HANDSHAKE_ERROR sounds like the right error code to me.

**Comment by janaiyengar** [comment]
Ah, didn't see Martin's message (stale tab) -- yes, TLS_HANDSHAKE_FAILED (defined in draft-ietf-quic-tls) sounds right.

**Comment by siyengar** [comment]
ah completely missed that, thanks :)
