### ISSUE TITLE
Transport: Inclusion of multiple Stream Frames for the same Stream ID

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#610]
draft-ietf-quic-transport-03, Section 8.1 says:

>   Stream multiplexing is achieved by interleaving STREAM frames from
   multiple streams into one or more QUIC packets.  A single QUIC packet
   MAY bundle STREAM frames from multiple streams.

The inclusion of multiple stream frames for the same frame is not clear in the above. Is it allowed or not?

**Comment by martinthomson** [comment]
I'm not sure that I understand.  Doesn't the final sentence answer your question?

**Comment by gloinul** [comment]
No, there is a difference between one stream frame per stream ID aggregated in the same packet, and multiple stream frames for the same stream ID. The later is not clear that it is allowed with above formulation. But, I guess that based on what is in the Stream Frame you can have multiple stream frames for the same ID, so this is likely an editorial issue on the above text to make it explicit.

**Comment by martinthomson** [comment]
Oh, now I understand.  Well, that's suboptimal, but permissible.  (You said "multiple stream frames for the same frame", where you meant same stream.)  Do you think that removing "from multiple streams" would clarify this point?

**Comment by gloinul** [comment]
I would rather be explicit and say; "A single QUIC packet MAY bundle multiple STREAM frames from one or more stream IDs."
