### ISSUE TITLE
Standalone version-independent document

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#615]
Several existing sub-issues around what is version-independent.  I'm proposing that the cross-version envelope of QUIC should be a separate final RFC, and therefore a separate document now.  If we landed that split, it would resolve several other questions about what, specifically, is supposed to be cross-version.

I would argue that version negotiation and everything that's visible outside the encryption envelope belongs in this separate draft.  It's the piece that will ossify, and that we're willing to have ossified.  Everything that's version-dependent belongs in the specific version, which is the Transport draft.

However, I'll note that the current split means that packet protection and framing live inside the version.  That means there's a lot that will need to be re-stated in a new version -- are we okay with that?

See PR #600.

**Comment by martinthomson** [comment]
I'd prefer not to do this.

**Comment by mcmanus** [comment]
no more documents please - the crossrefs are hard enough to deal with already

Perhaps a short section in transport recapping the invariants used elsewhere in the doc would be helpful as an alternative?

**Comment by janaiyengar** [comment]
From editors meeting: park this issue for now. There is value in separating these invariants, and perhaps something along the lines of mcmanus@'s proposal makes sense. The plan is to do something like that by the Singapore IETF timeline.

**Comment by ianswett** [comment]
So, I think we've done this?  And I'm cool with that.
