### ISSUE TITLE
quic-tls is the wrong doc to talk about integrity check for unprotected packets

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#617]
I totally missed that the FNV-1a stuff was added to quic-tls. I had not followed that doc recently, because my code doesn't do any TLS yet. Only when I couldn't find anything about FNV-1a in quic-transport did I start to grep through the text, and found section 6 of quic-tls.

IMO that is the wrong document to talk about this, since this has nothing to do with TLS. I would move that section into quic-transport.

Alternatively, quic-transport needs a pointer to that section of quic-tls, because nothing in quic-transport alerts a reader to the existence of the hash.

**Comment by larseggert** [comment]
Sorry, I didn't know that was the plan. It's a good plan. Do it :-)

**Comment by mcmanus** [comment]
purely as a stopgap, transport does say "The payload of cleartext packets
also includes an integrity check, which is described in [QUIC-TLS]
<https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#QUIC-TLS>."
which alerts you to the hash.

**Comment by larseggert** [comment]
I think this issue has become stale - closing
