### ISSUE TITLE
Finding frame lengths

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#62]
Martin Duke requests that all fields necessary for frame length computation be moved to the start of the frame.

**Comment by mnot** [comment]
As discussed in Tokyo, editors to propose a resolution for ACKs and STREAM frames.

**Comment by RyanAtGoogle** [comment]
I confess to not quite having yet become zen with the process here. Is this ready for a consensus email to the list?

**Comment by martinthomson** [comment]
I believe that the decision was that the editors would be given discretion, based on the above.  If @janaiyengar is ok with my proposal, we're basically done.  If you disagree with anything, please let us know.

**Comment by RyanAtGoogle** [comment]
I'm sure I'm just confused about how the process is expected to work. This is not terribly surprising :)

Do I understand you correctly that since this issue was discussed in Tokyo, no consensus from the list is needed? I'm sorry for being dense.
