### ISSUE TITLE
Proxy context

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#622]
Would it make sense to have a X-Forwarded-For parameter at the transport level?

A HTTP/1.1 server could forward to HTTP/QUIC using HTTP headers. X-Forwarded-For is generally useful and sometimes necessary in load balancer contexts.

QUIC could be terminated at an edge server that has access to certificates not available to backend servers. In this case a new QUIC connection may be created from edge server to backend. if the application protocol is not HTTP and the backend wants to filter against blacklists or whitelists, or log traffic, it must pass this information to the edge server. The connection could also be generic port forwarding like `ssh -L 8080:localhost:9090 user@example.com`.

Could this forwarding information meaningfully belong to the transport layer, for example in extended transport parameters? And for non-terminating middle boxes, could these amend the initial client packet with forwarding headers?

I realise that this is a can of worms, but at least it is better to shoot it down knowlingly rather than to regret not adding it later on.

**Comment by martinthomson** [comment]
This feature is adequately addressed at the HTTP layer for HTTP, and the needs of other applications are best dealt with by adding messages to those protocols.

Note that in many cases, use of this sort of marking is in direct opposition to the goal of having an intermediary, namely privacy.  This is another reason that doing this in an application protocol makes good sense; a generic transport can't reasonably make good decisions about things like privacy.

Consider this one shot down.
