### ISSUE TITLE
Ack frame has two framings that specify a single range

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#635]
A single ack range can be specified with or without the "num blocks" byte present.  It would be nice to only have one way to specify a single range.

The obvious options are:
1) Remove the bit that indicates whether num_blocks is present and make it always present.
2) Make the number of blocks read = num_blocks + 1.  
3) Do nothing because we don't care.

**Comment by ekr** [comment]
I suggest that we open a bigger issue called "Reconsider ACK Frame Encoding" because this is only one of a bunch of complaints I have about it.

**Comment by mnot** [comment]
#644 is the Grand ACK Frame issue.
