### ISSUE TITLE
Suggest linking CCID to SCID

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#637]
Suggest that all unprocted server packets reflect both SCID and CCID until client sends at least one packet with SCID, or until 1RTT handshake.
```

0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+
|1|   Type (7)  |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
+                       Connection ID (64)                      +
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
+                                CCID (64)                      +
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
...
```

This will

- make clear text handshake robust against address spoofing.
- allow client side load balancers to route packets to client side backend.
- simplify implementations by always having an ID to associate with the connection.
- allow handshake error packets that are robust against adversarial off-path reset attempts.
- allow implementations to not rely on unique 5-tuples when both endpoints agree (e.g. high speed netmap implementations), and to easier reject suspicious on-path packets.
- reduce reliance on robustness of NAT middle boxes.

Note: a client could embed the CCID in handshake data on stream 0, but the handshake can span multiple packets and will not support client side load balancers. The CCID field can be ommitted for certain packet types such as client initial and stateless retry, but it might not be worth the complexity - and then CCID can reflect the Connection ID.

The extra CCID should be removed for all 1RTT protected communication. Path migration should also provide a similar linkage from old to new, but it must be in encrypted form.

Some concerns are already being addressed by reflecting the packet number and / or the CCID in some flows, but it is does not cover all cases in a unified form.

**Comment by mikkelfj** [comment]
An alternative option might be to keep using CCID as the Connection ID in both directions until 1RTT handshake where a new SCID is provided in the handshake encrypted. This would avoid the extra CCID field but still deal with all of the above points, I believe.

However, it is not clear to if there are reasons to have SCID online before handshake.

**Comment by ekr** [comment]
As I indicated earlier, I would prefer to fold the CCID into a MAC rather than reflect it. That's more consistent with our general idiom for preventing packet injection, which is the authentication tag.

**Comment by mikkelfj** [comment]
Adding CCID to the MAC would solve some of the issues listed without taking up additional space.

However, it is fairly simple to support a high number of client requests from a single port using the above proposal. This could avoid issues with ephemeral port exhaustion and would allow for a simple OS interface in high volume configurations.

"Limits Implied by the Ephemeral Port Range"
http://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html

**Comment by martinthomson** [comment]
After discussing with editors, we're getting too many issues that suggest a particular design.  Rather than phrase issues as suggestions for designs, we need to have the underlying problem identified.  That way we avoid opening multiple issues for the same actual problem and we can discuss alternative designs in the one place.
