### ISSUE TITLE
When can the connection ID be omitted

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#658]
The current draft doesn't really talk much about when the connection ID can be omitted. Is this a unilateral unidirectional decision by a sender? Is it negotiated somehow? How are connections being identified in the absence of a connection ID? Are there cases when connection IDs need to be sent again after having been omitted? Etc., etc.

**Comment by LPardue** [comment]
Is the omission of a description a meta question about when to omit connection ID?

**Comment by larseggert** [comment]
So this is weird, because I actually did write a description, and I also labelled and assigned the issue. 
Love those eventual-consistency database backends.

**Comment by mikkelfj** [comment]
The text is here #659

**Comment by larseggert** [comment]
Totally weird. Closing this one.
