### ISSUE TITLE
Remove STOP_WAITING

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#66]
@ianswett suggests that maybe this can be removed.  He didn't say why.

**Comment by martinthomson** [comment]
This is getting to be a dependency of a lot of issues, let's try to close this off at the interim.

**Comment by mnot** [comment]
As discussed in Tokyo, @ianswett will come up with a PR to reflect the removal of STOP_WAITING. We'll close related issues at that point.
