### ISSUE TITLE
Non-zero streams in cleartext

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#660]
Stateless Retry, Client Cleartext, and ServerClearText permit streams other than 0. Only ClientInitial forbids streams other than stream 0.

This adds an API complexity because it must be ensured that an application does not accidentally consume data from an unprotected stream. It also works against certain optimizations for handling handshake on a separate code path. And it makes it harder to defend against abuse such as packet interception and rewrite with more streams with no formal crypto protection to attack vulnerable implemenations.

**Comment by mikkelfj** [comment]
Also, what is the point of ACK frames in a stateless retry considering that it has no state to collect ACK data in, and considering that it is in itself effectively an ACK for client initial - of course an ack_delay timestamp could be carried to measure rtt, but is it worth the complexity for that? Might it not better to have it similar to Client Initial with stream offset 0 at stream 0?

**Comment by martinthomson** [comment]
https://quicwg.github.io/base-drafts/draft-ietf-quic-tls.html#rfc.section.9.1

**Comment by mikkelfj** [comment]
@martinthomson The packet description of clear text does not reflect the TLS text
https://quicwg.github.io/base-drafts/draft-ietf-quic-transport.html#rfc.section.5.4.4

>The payload of this packet contains STREAM frames and could contain PADDING and ACK frames.

The initial packet explicitly mentions that only stream 0 is permitted.
