### ISSUE TITLE
PING can't detect liveness

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#661]
PING is replied to via ACK, but ACK frames can be arbitrarily delayed or omitted. If PING was required to be ACK'ed timely, or replied to via a PONG frame, this would not be an issue. A PONG frame would interfere less with general ACK logic, but add yet another frame type.

**Comment by RyanAtGoogle** [comment]
What language allows ACK frames to be "arbitrarily delayed or omitted"? If
a peer does not ACK packets, the sender will be forced to retransmit,
possibly incur an RTO which collapses the CWN, and eventually close the
connection. I believe ACKs can be delayed for very small periods of time
(which do not matter in the context of liveness detection) or omitted for a
similar period of time, less than 1 RTT.

**Comment by mikkelfj** [comment]
>To limit receiver state or the size of ACK frames, a receiver MAY limit the number of ACK blocks it sends.

> Constants used in loss recovery are based on a combination of RFCs, papers, and common practice. Some may need to be changed or negotiated in order to better suit a variety of environments.

> // Tail Loss Probe
      if (retransmittable_packets_outstanding = 1):
        alarm_duration = 1.5 * smoothed_rtt + kDelayedAckTimeout

**Comment by RyanAtGoogle** [comment]
Right, but that's a very small time relative to the liveness check that a
PING demands.

**Comment by mikkelfj** [comment]
OK, I'll close the issue on the assumption that ACKs will not be allowed to delay for long, and also because when the ACK eventually arrives, the ACK delay parameter will provide more information.
