### ISSUE TITLE
stray 0x21 in HKDF-Expand info construction

### ISSUE THREAD

**Issue by tatsuhiro-t** [quicwg/base-drafts#665]
https://quicwg.github.io/base-drafts/draft-ietf-quic-tls.html#rfc.section.5.2.2 describes info parameter for HKDF-Expand.  The struct HKDFLabel does not contain 0x21 ("!"), but its example contains it:

```
 info = (HashLen / 256) || (HashLen % 256) || 0x21 ||
          "tls13 QUIC client 1-RTT secret" || 0x00
```

I couldn't find it in TLSv1.3 draft or RFC 5869.
Is it a practice to insert 0x21 after Length, or just a remnant of earlier draft?

**Comment by martinthomson** [comment]
This value is incorrect, but it's necessary.  The value changed in a recent PR and I missed the update.  It should be 0x1f - the length of the label string.

**Comment by tatsuhiro-t** [comment]
Thank you. That's make sense.
