### ISSUE TITLE
Stateless retry relation to version negotiation

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#669]
If a server decides to send a version negotiation packet and also a stateless retry, which one should it choose, and should the client retain a negotiated version if it receives a stateless retry? If it does not, the cryptographic context in the retry might not make sense but text says to start new connection state.

Also, retry might be related to which server version is supported, so there could potentially be a lot of ping pong going on. On the other hand, a retry might not know the versions supported by other servers.

**Comment by mikkelfj** [comment]
Wasn't mentioned in version negotation nor in Stateless Retry section, but stateless retry packet does section mention it:
"the client MUST remember the results of any version negotiation that occurred "

I keep the issue open for review in case the text can be clarified a bit.

**Comment by martinthomson** [comment]
This isn't really a valid question.  The draft is pretty clear that version negotiation happens before stateless retry.
