### ISSUE TITLE
What is the actual format of the ACK Delay parameter?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#677]
In the transport spec The ACK specification defines a 16 bit Ack Delay as:

> ACK Delay:
>
> : The time from when the largest acknowledged packet, as indicated in the Largest Acknowledged field, 
> was received by this peer to when this ACK was sent.

Other 16 bit ACK delays are encoded using an ad hoc floating point format. For this field, are we using the floating point format of a 16 bit number of microseconds?

**Comment by mikkelfj** [comment]
I wrote up the precise format of the 16 format used called ufloat16.

https://github.com/quicwg/base-drafts/issues/109

It is a 64-bit unsigned integer word with multiple values mapping to the same value in the ufloat16 format. It has a much higher dynamic range than 16-bit integer, but not the full range of a 64-bit integer - too large values are clamped to a maximum value.

The format is always used in its 64-bit decode form, except that it is possible to do relative comparisons directly on ufloat16 if you need to.

As to the specific use of the format in a given frame field, I suppose all values are 64-bit microseconds relative to either connection start or relative to some other reference point in a frame. It is actually quite good for timestamps where you need limited precision by have an unpredictable range.

**Comment by martinthomson** [comment]
Yeah, closing in favour of #109.
