### ISSUE TITLE
Minimum packet size

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#69]
Issue #64 brought up PTUMD, which brought up the issue of minimum packet size.

Stateless rejects require the CHLO to fit into one packet, so the minimum should be specified with that in mind.

#64 also brought up the issue of downgrade attacks, and given the vast majority of paths permit 1200 bytes, we should be able to agree on a reasonable(ie: >1k) minimum size.

**Comment by martinduke** [comment]
I fully support a relatively large minimum packet size for QUIC. It massively mitigates the downside of some MTU-based attacks.

**Comment by martinduke** [comment]
The other question here is, "what do we do if the reported path MTU is less than the minimum?" I think the answer is to simply ignore the lower MTU and keep sending big packets, even if that causes fragmentation. The alternative is to have an ICMP packet that can force TCP failover.

**Comment by mnot** [comment]
As discussed in Tokyo, resolved as part of #64 / PR #106
