### ISSUE TITLE
Do we need endofearlydata?

### ISSUE THREAD

**Issue by siyengar** [quicwg/base-drafts#690]
In TLS 1.3 end of early data is needed because it prevents truncation of 0-RTT data because of resetting sequence number. However quic does not reset sequence number and the 0-rtt data is sent on different streams from stream 0, so can we get rid of endofearly data?

this does have the disadvantage that the TLS stack will have to omit slightly different records in QUIC than in TLS, but I believe there need to be special cases anyway in the 0rtt stream for quic, for example content type of app data is not allowed on stream id 0.

**Comment by ekr** [comment]
On Wed, Jul 19, 2017 at 5:10 AM, Subodh Iyengar <notifications@github.com>
wrote:

> In TLS 1.3 end of early data is needed because it prevents truncation of
> 0-RTT data because of resetting sequence number. However quic does not
> reset sequence number and the 0-rtt data is sent on different streams from
> stream 0, so can we get rid of endofearly data?
>

That seems like it's going to make it kind of a pain to use a generic TLS
stack.

-Ekr

**Comment by MikeBishop** [comment]
From the TLS standpoint, QUIC is the app driving it.  If a normal TLS app requests a 0-RTT handshake, but then sends no data during 0-RTT, what happens?  Is there still an EOED?

That's what should happen here.  As far as QUIC is concerned, the app requested a 0-RTT handshake, but never sends any data, either during 0-RTT or 1-RTT.  TLS shouldn't be changing behaviors based on where it's used, but based on what the app does..

**Comment by ekr** [comment]
On Mon, Jul 24, 2017 at 10:42 AM, Mike Bishop <notifications@github.com>
wrote:

> From the TLS standpoint, QUIC is the app driving it. If a normal TLS app
> requests a 0-RTT handshake, but then sends no data during 0-RTT, what
> happens? Is there still an EOED?
>
Yes.


> That's what should happen here. As far as QUIC is concerned, the app
> requested a 0-RTT handshake, but never sends any data, either during 0-RTT
> or 1-RTT. TLS shouldn't be changing behaviors based on where it's used, but
> based on what the app does..
>
Agreed.

-Ekr

**Comment by siyengar** [comment]
ya I think I generally agree, being able to work with an unmodified TLS stack is kind of useful. The reason I asked this question was that when I saw the endofearly data I started scratching my head asking what security property this provides with QUIC, and the answer was really none and it seemed weird being there at that point.

**Comment by MikeBishop** [comment]
Sounds like we're in agreement that this can close with no text change, then.  Please re-open if you disagree.
