### ISSUE TITLE
Move ACK/STOP_WAITING into the packet header

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#70]
Mirja Kühlewind points out that multiple ACK frames per packet don't really make sense, and they aren't retransmittable.  Instead, Mirja suggests replacing the ACK frame with an optional region in the packet header and a bit indicating its presence.  STOP_WAITING, already a candidate for removal (#66), could be consolidated here as well.

**Comment by ianswett** [comment]
Could you clarify what you mean by packet header?  There is currently no encrypted packet header, so we'd have to create one in order to place the ack frame there.  I'll point out two connection close frames in a packet make even less sense.  Or PING frames.

**Comment by MikeBishop** [comment]
And I think that's the distinction.  If we had an encrypted header region, it could logically hold a lot of the connection-level information.  Of course, if we allow that set of stuff to be extensible, it could wind up looking a lot like frames.  ;-)  Updating the title to better reflect the suggestion.

**Comment by mnot** [comment]
As discussed in Tokyo, dropped (for now)
