### ISSUE TITLE
Is Version Negotiation integrity protected in first interop draft?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#706]
I am belatedly finishing the first interop draft implementation, and I have a doubt regarding the version negotiation packet. The text in section 5.4 Cleartext Packets says:

> The payload of cleartext packets also includes an integrity check, which is described in [QUIC-TLS].

The text in section 5.3. Version Negotiation Packet does not say anything about integrity protection. I understand that this will be clarified for future drafts as we resolve issue #693. But I would like to know how other implementations deal with version negotiation packets for the 1st interop. FNV1A or not?

**Comment by mcmanus** [comment]
no fnv1a on any version-negotiation afaict.. otoh it would probably just look like some versions the client didn't implement ;)

 (the slack is a great place for this kind of interop question)

**Comment by ianswett** [comment]
I think this is obsolete, since we're well past the first implementation draft.  I also think EKR clarified the text when he introduced AES-GCM handshake crypto.
