### ISSUE TITLE
Retain use of SETTINGS_ENABLE_PUSH

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#718]
When pushing, the server currently only pushes after it's heard a MAX_PUSH_ID from the client. It might be useful to retain HTTP/2's SETTINGS_ENABLE_PUSH boolean that indicates push is disabled by the client. Without this boolean, the server has to wait forever to push but can't because it didn't hear anything from the client "yet", and the only way it knows that the client has disabled push is basically silence... which seems not great. (Tertiary point: it might be useful for various debugging/logging purposes to have an explicit disabling.)

**Comment by martinthomson** [comment]
It's true, this changes the default stance of a server.  In the event that a MAX_PUSH_ID (#711) isn't received, the server simply can't use server push.  If the client really does support push, this error is going to be rare (the packet containing the MAX_PUSH_ID is lost or delayed and the request is still in a position to be understood and responded to).  The only consequence is lost opportunity, the protocol still functions.

We have a similar problem with SETTINGS.  SETTINGS establishes the header table size, so there is a lost (compression) opportunity if it is lost or reordered.

Either way, I think that we'll find out just how much of a problem this is when we get some experience with this.  It might be premature to decide right now.

**Comment by janaiyengar** [comment]
Marking as parked, since we aren't looking for resolution now.

**Comment by martinthomson** [comment]
MAX_PUSH_ID does this, right?

**Comment by LPardue** [comment]
I think the original issue and discussion are still valid up to draft 11 at least. MAX_PUSH_ID controls push enablement. Lost or delayed packets with this or SETTINGS are subject to the same consideration.

**Comment by MikeBishop** [comment]
I see the issue -- on the server, you don't know whether you're temporarily blocked or permanently disabled.  A server could heuristically guess that if it hasn't seen a MAX_PUSH_ID frame after a RTT or so then one isn't coming, but there's some value in an affirmative declaration of "don't bother deciding what to push."

We actually don't have this with SETTINGS, as each peer is currently required to have seen the other side's SETTINGS frame before sending request/response data.

**Comment by martinthomson** [comment]
Maybe just allow MAX_PUSH_ID to appear before SETTINGS and contain the problem that way.

**Comment by MikeBishop** [comment]
"Allow" doesn't actually solve the issue; just because it wasn't before SETTINGS doesn't mean it won't be after.

**Comment by martinthomson** [comment]
Allow means that we might also (strongly) recommend sending it then.  A server that doesn't see it could assume that it's permanent.

**Comment by MikeBishop** [comment]
Following the logic in #1359, if we treat push as being an extension which defines a few frames and a stream type, then clients should have an opt-in setting declaring that all the push-specific things are supported.  If that PR gets merged, the only "privileged" thing about push in the core protocol is that PRIORITY can prioritize/depend on a push stream.

I'm almost tempted, as part of this and removing Flags, to say that requests can't depend on pushes and split out a PUSH_PRIORITY frame so that it's totally disjoint.

**Comment by martinthomson** [comment]
PUSH_PRIORITY is tricky, because pushes and responses can be interdependent.  You would simplify PRIORITY, but PUSH_PRIORITY still gets 3/4 of the cases.

**Comment by MikeBishop** [comment]
I'm assuming with this that you never want to make a request dependent on a push.  So PUSH_PRIORITY always prioritizes a push, and only has to differentiate whether the target is a push or a request.  But that's a departure from what H2 technically supports, so it might be out of scope.

**Comment by MikeBishop** [comment]
Discussed in Tokyo; no setting.
