### ISSUE TITLE
Largest Acknowledged can't be 1 or 2 bytes

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#734]
In #731, we found that the encoding for ACK is a little perverse in another way (see #644 for a more comprehensive list of complaints).  The Largest Acknowledged can be 1 or 2 bytes.  However, this field isn't truncated like packet numbers (for the reasons described in #731, this would be hazardous).  And packet numbers start somewhere between 1 and 2^31-1, meaning that it would be very unlikely to have a packet number that was actually small enough to fix in 1 or 2 bytes.  We should not waste a whole bit to describe these two sizes if we can't use them.

**Comment by ianswett** [comment]
Closed by #877

**Comment by martinthomson** [comment]
This is still technically a problem, and will only be resolved by something like the proposal to obscure packet numbers.
