### ISSUE TITLE
Clarify Acks of Acks

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#736]
currently section 9 says
> To avoid creating an indefinite feedback loop, an endpoint MUST NOT generate an ACK frame in response to a packet containing only ACK or PADDING frames.

There is some implementation confusion around it.

Consensus seems to be that this means the packet containing only ACK/PADDING does end up referenced in an ACK frame eventually, but the generation of the ACK frame should not be triggered by the receipt of the ACK/PADDING-only packet.

however an alternative explanation, don't include the packet number of the ACK/PADDING-only packet in any ACK frame, is possible. It would be good to be clear.

I've noticed that the phrases like "don't ack acks" contribute to the confusion. Is it true that every packet except VN and Stateless-Retry needs to eventually be acknowledged? If so - that might be a useful clarifier.

**Comment by ianswett** [comment]
The consensus is correct.  The packet should be acknowledged in the next ack frame sent, but it should not cause a packet containing an ack frame to be sent.

**Comment by martinthomson** [comment]
Closed by #739, though Ian's comment wasn't in the precise form that GitHub wanted.
