### ISSUE TITLE
Application-defined error codes

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#74]
If applications want to terminate a stream or connection for a reason that isn't specific to the QUIC transport layer, they currently need to define their own error communication mechanism and wait for the frame to be acknowledged before they tell QUIC to terminate the stream/connection.  That's not necessarily practical.

Could we carve out a segment of the error space and define them to be application-defined, so each application mapping can add whatever error codes are relevant to it?  E.g. QUIC currently defines  QUIC_DECOMPRESSION_FAILURE, but QUIC defines no compression.  That's really there for HPACK, I presume.

We could do likewise for handshake errors, since that's also pluggable -- QUIC will have its own AEAD error codes, but things that could go wrong in the handshake will vary by which handshake protocol we're using.

**Comment by MikeBishop** [comment]
Proposed resolution in #131.

**Comment by mnot** [comment]
Discussed in Tokyo. Consensus confirmed in the room.
