### ISSUE TITLE
Introduce draining period for connection termination

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#748]
Feedback on what was an editorial change in #721 turned it into a substantial change.  Apparently we are now specifying what different peers do during shutdown in new and interesting ways.

**Comment by huitema** [comment]
I like the new text. It does result in reliable close. Just one nit: if the sender of the connection close receives an ACK for the packet carrying the connection close frame, it is probably OK to exit the draining state sooner.

Of course, when we study multipath, we will have to differentiate between closing a path and closing the connection...

**Comment by martinthomson** [comment]
Apparently the "closes/fixes" trick only works for those issues that were mentioned at first.  You can't add more later by editing the comment (that's weak-sauce GitHub).
