### ISSUE TITLE
Cancellation of requests with (partial) responses

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#756]
We should be a lot clearer about what it means to receive HTTP_REQUEST_CANCELLED for a stream where part of the response was received.  What if you receive (in the same packet even) a STREAM frame containing the headers block and a 200 status code, followed by a cancellation of that stream?

This also applies to GOAWAY, which implicitly sends HTTP_REQUEST_CANCELLED for all requests with stream ID > N.

**Comment by MikeBishop** [comment]
#770 appears to cover this as well, though the part about CANCELLED should perhaps move elsewhere in the doc.
