### ISSUE TITLE
STOP_SENDING is an application protocol concept

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#758]
Objectively, it makes very little sense for the frame to be defined at the transport layer.  There are minor advantages to the current arrangement in terms of generality (if we can agree that the concept is properly generic), and in performance (it can be sent at the transport layer without being subject to HOLB, though this might be removed by having it sent on a new stream).  However, neither of those benefits are significant enough to justify the cost of it being out of place.

Raised as a consequence of discussion on #722. This being just my opinion.

**Comment by MikeBishop** [comment]
We agreed in Seattle that it is not.  (Or not exclusively.)
