### ISSUE TITLE
CONTINUATION/END_HEADERS

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#76]
In HTTP/2, the CONTINUATION frame was [much loathed](https://github.com/http2/http2-spec/pull/548), but ultimately deemed a necessary evil since there are some truly, ridiculously large headers out there (*\*cough\** Kerberos *\*cough\**).  The current HTTP/QUIC draft allows a frame to be 64KB long before decoding the HPACK.  Is this large enough?  That was the boundary we'd said it would take in HTTP/2 to require a single frame.

If not, the current draft uses the END_HEADERS bit to indicate that another HEADERS frame will follow, which is effectively the same as CONTINUATION.  The same is not currently defined for PUSH_PROMISE (which really ought to be much smaller).

If so, could we drop the END_HEADERS thing entirely and say that HPACK-bearing frames are fully self-contained?  It would simplify a lot of client mechanics.

**Comment by mcmanus** [comment]
seems like something the browsers could collect data on for their current
h2 impls.. I don't currently have it, but if people are willing to put a
pin in this for a while I can add it.. maybe chrome too?

**Comment by MikeBishop** [comment]
Can't hurt.  The problem is we're really looking for outliers here -- not just the norm, but the largest header set anyone's ever had to deal with, and that's probably coming from something pretty specialized.

For our case, our mega-single-header scenario is carrying Kerberos tokens, which we've seen as large as 48KB, which then get Base64-encoded to 64KB.  (Huffman hopefully helps recover some of this, though.)  Looking a little, I see our [maximum configurable limits](https://support.microsoft.com/en-us/kb/820129) are 64KB per header field and **16MB** for the total of all headers.

That may be our answer, unfortunately -- if we want to continue being able to support 16MB of headers (ick), we'll need larger than a 64KB HEADERS frame *in extremis*.  However, Kerberos isn't yet supported over a multiplexed HTTP mapping, so this may be hypothetical for the time being.

**Comment by MikeBishop** [comment]
Related question:  Repeated HEADERS with an END_HEADER_BLOCK flag, or keep CONTINUATION?  IIRC, the reason we used CONTINUATION was because the subsequent blocks weren't allowed to contain the PRIORITY section which no longer exists.  The counter being present only on the first block might argue for bringing back CONTINUATION, but I'm hopeful we can get rid of that before we ship the spec.

**Comment by martinthomson** [comment]
Well, the question is academic if the headers frame can be arbitrarily/sufficiently large.  I would rather not conclude until we decide that question and the QPACK issue as well.  That suggests that we might want to track that as a separate issue.

**Comment by mcmanus** [comment]
fwiw - I've had firefox telemetry looking at the h2 data on this for the last few weeks. It has ~4billion server generated HEADERS samples and 0 CONTINUATIONS

**Comment by RyanAtGoogle** [comment]
YAGNI time?

**Comment by martinthomson** [comment]
That's an very interesting data point.  We never got the measurements while developing h2, so we were left with speculation and a few corner cases.  I think that @MikeBishop had one of those perverse cases (was it Kerberos?).  The other was really big URIs.

Since this operates at a different layer and we don't need to constrain frame sizes for head of line blocking reasons, it's tempting to say 16bits of length is OK.  That's four times what we allow in h2.

+1 to YAGNI.

**Comment by mnot** [comment]
A couple of observations:

- The places where this is most likely (behind firewalls in enterprises, in non-browser uses of H2) are least likely to show up in telemetry.

- Limiting the size of headers is a semantic change in HTTP; this is not a trivial thing.

- As we discussed in H2, the interop failures here are *really* nasty, especially for intermediaries.

- To me, much more interesting data would be some sense of how well greased CONTINUATION is in H2.

**Comment by mcmanus** [comment]
I just looked at this data again and now there is some data from release channel firefox (the earlier data point was limited to pre-release users). There is a tiny bit of CONTINUATION.. on the order of 1 in 100k HEADERS.. of those, > 99% are less than 64KB. But there is an existence proof of something that doesn't fit. (whether or not that's an error later in the stack, I don't know. I wouldn't be surprised.)

**Comment by mnot** [comment]
At Previous Employer™️, we had to up header block sizes to 128K IIRC, as we regularly came across things that big in internal HTTP calls. Don't assume that the browser sees everything...

**Comment by martinthomson** [comment]
I didn't change the frame length in #888, but it is an easy fix.  Can anyone suggest a reason not to?  It makes everything simpler and we no longer have to worry about keeping these frames small for multiplexing reasons.

**Comment by mcmanus** [comment]
@martinthomson sgtm

**Comment by ianswett** [comment]
SGTM as well.
