### ISSUE TITLE
Testing QUIC over high latency IP links

### ISSUE THREAD

**Issue by slenpree** [quicwg/base-drafts#773]
What is currently the best way to explore the feasibility and performance of QUIC on IP links with 580ms+ RTT such as from geostationary satellites as an alternative to TCP which struggles with these conditions without acceleration.

**Comment by janaiyengar** [comment]
I don't think this question belongs here -- this is an implementation-specific question. Also, this is really a question about the congestion controller that is in use, and that will also depend on the implementation.

This isn't a protocol issue, so closing.
