### ISSUE TITLE
Writing after closed frame enqueued

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#777]
I'm not sure if this belongs in the QUIC spec, but I had to handle it specially in Minq so I thought I would mention it.

The current text shows the transition from OPEN to HALF_CLOSED (LOCAL) happening when you send a FIN. However, if you think of this from an API perspective, that's not quite what you want. Consider the case where you have a stream flow control window of 1000. You write 999 and then 1000-1999, and then call stream.Close(). At this point, you have in queue:

``` 
  [0-999] (sent, maybe un-acked)
  [1000-1999] (not-sent)
  [2000: FIN] (not sent)
```

You're still in OPEN because you haven't sent the FIN, but the implementation should stop you from doing another Write() at this point. This isn't really captured by the state machine.

**Comment by martinthomson** [comment]
This relates to #1189.  If we address that at the same time, I think we're good.

**Comment by martinthomson** [comment]
Editors discussed this and while there might be some value in having states that reflect this internally in an API, but we probably don't need to do anything for this in the spec.
