### ISSUE TITLE
Streams start as "idle"

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#778]
There are two ways of thinking about streams:

1. All 2^32 streams exist but are in the IDLE state and transition to other states when messages are received/sent on them.
2. Streams are created when the aforementioned messages are received/sent.

The document is kind of agnostic on this, talking about them as being in IDLE (the state machine) but also talking about streams being created:

```
   A QUIC endpoint cannot reuse a Stream ID.  Streams MUST be created in
   sequential order.  Open streams can be used in any order.  Streams
```

I tend to think that it would be better to talk about streams being created and remove the IDLE state, but in any case it would be good if the draft were consistent.

**Comment by ianswett** [comment]
Streams being created better matches the way they're managed in data structures, so I would tend to favor that as well.

**Comment by martinthomson** [comment]
The new stream states don't exist until they transition to an active state.
