### ISSUE TITLE
CANCELLED streams outside of GOAWAY

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#782]
In #757, the CANCELLED state is discussed in the context of GOAWAY, because HTTP/2 used cancellation only for closure and for exceeding the stream limit (which is moot in HTTP/QUIC).  But there's no text that actually *prohibits* sending it at other times.  Should there be?

If not, the logic in #770 for not blowing up when the server cancels (declaring it hasn't processed any of the request) after starting to respond (proving that it has started processing the request) is somewhat broken.  As @janaiyengar points out, if the client doesn't hard-require it, it's not a MUST [NOT].

**Comment by martinthomson** [comment]
1XX  might influence the outcome.  I think that it is valid for a server to cancel a stream after sending 100 Continue, for example.

**Comment by MikeBishop** [comment]
Duplicate of #756.
