### ISSUE TITLE
Can Server Require Connection ID to be Included in Packets Sent by Clients?

### ISSUE THREAD

**Issue by nibanks** [quicwg/base-drafts#789]
This is slightly related to #659.

Is it reasonable/acceptable for a server implementation to require that a client always include the connection ID? If so, what exactly should it do if it receives a new connection where the client specified `omit_connection_id` in its transport parameters? Should it drop the connection? Send an error back (if so, what error)?

It seems to me that if we want to allow servers to restrict the usage of `omit_connection_id` by the client, we should probably have some mechanism to indicate the client the connection must include the connection ID. One possibility is a new transport parameters that is server specific that indicates connection id is required.

**Comment by RyanAtGoogle** [comment]
" The Connection ID field can only be omitted if the omit_connection_id
transport parameter is specified by the intended recipient of the packet."

So if a server does not send this parameter, the client must send
connection IDs. I think that gives you what you want?

**Comment by nibanks** [comment]
So the `omit_connection_id` indicates to the remote whether or not they should include connection ID. I thought it was indicating the sender was going to omit them. That makes a bit more sense. Thanks.
