### ISSUE TITLE
Explain reason for having connection limits

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#796]
The lifetime of a connection and the amount of data that can be transferred thereon are limited because the packet numbers, connection byte offsets, and stream byte offsets all have maximum values.  The draft should address the reason(s) why there are maximum values at all.

I raised this issue on the mailing list twice, but received no answers:

https://www.ietf.org/mail-archive/web/quic/current/msg02144.html
https://www.ietf.org/mail-archive/web/quic/current/msg02251.html

**Comment by martinthomson** [comment]
To be fair, you received answers, but you didn't like those answers.  I'm not defending those answers, they are somewhat arbitrary, but I think that the onus is on you not to question that they have limits, but to motivate a change.  Do you have a specific change in mind?

**Comment by dtikhonov** [comment]
That is incorrect: the question _Why is connection lifetime limited?_ has not been answered.

I do have a specific change in mind: take the answer to the question above and put it into the draft.

**Comment by martinthomson** [comment]
The answer was: because those various numbers have maximums.  That is in the draft.

**Comment by mikkelfj** [comment]
It would also be possible to wrap 128-bit bumbers, which are practically unbounded, similar to how packet numbers are truncated on wire. So it must be an implementation complexity tradeoff or a technical difficulty in resolving representational conflicts, or a yagni.

________________________________

**Comment by dtikhonov** [comment]
> The answer was: because those various numbers have maximums. That is in the draft.

@martinthomson, the fact that a number representation has a maximum not cause TCP to abort a connection after 2^32 bytes have been sent.  I think the reason must be something else.

**Comment by dtikhonov** [comment]
@mikkelfj, I agree with your analysis.  (For my money, a 64-bit number is practically unbounded as well.)  What I am proposing is that this verbiage or something to that effect -- _practical considerations... blah-blah-blah_ -- be put into the draft.

**Comment by RyanAtGoogle** [comment]
How 'bout sending out a PR.

**Comment by mnot** [comment]
Flipping to editorial.

Just a note -- the drafts need not justify every decision made, except where it's necessary to clearly communicate.  That's not to say that we can't (or shouldn't) discuss why things are the way they are; just saying that if we were to document the reason for every decision, they would quickly become unreadable.

**Comment by dtikhonov** [comment]
If the editors think that this is not important, I won't insist.  This is less of an issue for version 1, which focuses on supporting HTTP instead of being "[the next transport protocol for the Internet](https://quicwg.github.io/)."

**Comment by dtikhonov** [comment]
Closing -- seems it is not important.
