### ISSUE TITLE
ECN echo in ACK frame or as separate frame

### ISSUE THREAD

**Issue by IngJohEricsson** [quicwg/base-drafts#804]
There has been discussion wether the ECN indication (or echo) should be included in the ACK frame or in a separate dedicated frame. 
Proponents of a dedicated ECN frame argue that adding extra ECN info in the ACK frame can increase the complexity of the ACK frame encoding and parsing. Ian Swett however as a very strong point in his remark that ECN in a separate frame can give additional issues in the congestion control functionality, in other words, what we save (in complexity) in one part of the chain can cause extra cost and in the worst case incomprehensible code in another part of the chain. 
My personal opinion is that it is best to have ECN in the ACK frame

**Comment by britram** [comment]
+1 to ECN in ACK for Ian's reasons.

**Comment by janaiyengar** [comment]
Work is ongoing here, so parking until design team makes progress.

**Comment by martinthomson** [comment]
Closed by #1372.
