### ISSUE TITLE
Version Negotiation when Version = 0

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#816]
`The version 0x00000000 is reserved to represent an invalid version`, but what is the expected behavior when a server receives it?  Should it initiate version negotiation, or should it reject the incoming message entirely?

**Comment by martinthomson** [comment]
We don't need special handling for this.

**Comment by janaiyengar** [comment]
I agree -- I think this is fine as is. A server will send a VN packet in response to it, or if it's seen in a VN packet, it will simply be ignored. I'll close this, but @MikeBishop please reopen if you think we should discuss this further.

**Comment by MikeBishop** [comment]
> A server will send a VN packet in response to it...

The origin of this issue is that not all current implementations *do* send VN in response to version 0, so there is some difference of interpretation in the spec.  Maybe we decide that the spec is perfectly clear and any implementation behaving that way simply has a bug -- that's a reasonable position.  But I think it's also a reasonable reading of the current spec to ignore or CONNECTION_CLOSE a packet purporting to be in "an invalid version."

**Comment by janaiyengar** [comment]
I see. You're suggesting that we should articulate one precise behavior in this case. I probably don't really care which one, but I'm fine with that.

**Comment by martinthomson** [comment]
OBE.  See #827 for a more a request to address the remaining issue (that clients ignore unknown, unexpected, or unsupported versions).

**Comment by nibanks** [comment]
I'd like to reopen this issue, because if two servers support enough versions to produce really large VN packets, then an attacker could get them to continually send VN back and forth. So I think a server should silently drop a version 0 packet that it receives.

**Comment by martinthomson** [comment]
Nick, I think that a new issue is appropriate. Ignoring Version Negotiation if you aren't making a connection seems good, obvious even. I would take a PR to clarify that if you have the time.
