### ISSUE TITLE
Stateless Reset Format is hard to implement

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#820]
The issue is that part of the token is in what you would otherwise interpret as the sequence number field, which means that you need special serializers and deserializers. It would be better to just have a random sequence number (which is what this effectively is anyway) and then the token in the body.  In fact, that's so obviously better that when I implemented this, I totally missed it.

**Comment by ekr** [comment]
It would also make things easier if it were the last N bytes of the packet, because then you wouldn't need to parse an invalid packet header in order to find the data.

**Comment by martinthomson** [comment]
Conveniently, the last N bytes is the authentication tag and N = 16.  So I like this idea.

**Comment by ekr** [comment]
Correct. You need to check for SR if either replay or AEAD fail
