### ISSUE TITLE
multiple cleartext types

### ISSUE THREAD

**Issue by jpinner-lyft** [quicwg/base-drafts#822]
There is no value and additional validation cost in prescribing cleartext packet types for each direction of communication.

**Comment by ianswett** [comment]
One benefit is that if the network routes packets incorrectly, it's easy for the server to drop the client's packets and client to drop the server's.

**Comment by jpinner-lyft** [comment]
If there is a concern about directionality I think it would be preferable to mirror the directionality inferred in the encrypted packets by using hashes based on the packet direction similar to what's done for the encryption keys today.

**Comment by ianswett** [comment]
I'm happy with that as well.
