### ISSUE TITLE
clients always must regenerate client hello

### ISSUE THREAD

**Issue by jpinner-lyft** [quicwg/base-drafts#826]
The text in Sec 7.1 that details client handling of a version negotiation packet is not accurate:

"Though the contents of a packet might not change in response to version negotiation, a client MUST increase the packet number it uses on every packet it sends."

In particular because the transport parameters must be updated to reflect the version negotiation, the contents of the client initial packet must change. Also the first packet number will never be acknowledged so increasing the packet number by one to signify a retransmission does not make sense.

In particular the packet number should be reinitialized as specified in Sec 5.4.1 since as stated above, new contents must be created.

**Comment by siyengar** [comment]
+1

**Comment by martinthomson** [comment]
This is no longer necessary.  We changed the version negotiation, so clients only need to generate ClientHello in response to a change in QUIC version that is incompatible with their ClientHello.
