### ISSUE TITLE
Can a server use a Handshake packet for ACK of the last client Handshake packet

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#829]
Interesting question. Picoquic and Quickly have an interop issue because Quickly acks the client finished message (client clear text) in a server clear text packet carrying an ACK. Picoquic ignores the server clear text packet because it has already sent the client finished and has moved to encrypted operation. Who is right?

**Comment by janaiyengar** [comment]
Why did the server (Quicly) not move to 1-RTT and send the server ack in a 1-RTT packet? That's what I would have expected.

**Comment by ekr** [comment]
What's the text that leads you to believe that it should do that.

**Comment by kazuho** [comment]
@janaiyengar 
> Why did the server (Quicly) not move to 1-RTT and send the server ack in a 1-RTT packet? That's what I would have expected.

ACK for the cleartext packet that carried ClientFinished was sent in a cleartext packet that carried ServerFinished.

**Comment by ekr** [comment]
FWIW, this is what I do as well.

**Comment by huitema** [comment]
I am concerned that this creates a big special case. If I have to accept a clear text ACK for the Finished message, I need to keep track of the packet numbers that can be ACKed with that message -- ACKing 1RTT data would be wrong. That's a very big wart in the code.

**Comment by kazuho** [comment]
@huitema 
> I am concerned that this creates a big special case. If I have to accept a clear text ACK for the Finished message, I need to keep track of the packet numbers that can be ACKed with that message -- ACKing 1RTT data would be wrong. That's a very big wart in the code.

We cannot use the timing at which we finish TLS handshake as a moment to switch from ACK over cleartext to ACK over protected packets, considering the fact that 0-RTT packets need to be ACKed using protected packets, and that 0-RTT packets and cleartext packets can be sent in mixed order.

**Comment by huitema** [comment]
@kazuho You wrote:

> ACK for the cleartext packet that carried ClientFinished was sent in a cleartext packet that carried 
> ServerFinished.

That's not what I see in the logs. I see:

  -> Client initial (carries client hello)
  <- Server Clear Text (several message carry server flight, including server finished. Message embed 
       ACK of Client Initial
  -> Client clear text: carries client finished, and ACK of server clear text messages
  <- Server Clear Text: only carries an ACK Frame for the client clear text.

When the server sends the last server clear text message, it has already received the client clear text, since it acknowledges it. According to Ian's presentation of "ACK rules", ACKing a message means that the message was not just received but also processed -- which logically means processing the TLS state machine. I don't see what advantage there is to sending that last acknowledgement in clear text.

**Comment by MikeBishop** [comment]
Per editors' meeting:  Not only can a server do this, it MUST.  Packets encrypted with the handshake key MUST be acknowledged only in packets encrypted with the handshake key.  Packets encrypted with 0-RTT or 1-RTT keys MUST be acknowledged only in a packet encrypted with the 1-RTT key.  (There might be alternative solutions, and those would be welcome.)

The reason for this is a man-on-the-side attack in which an attacker injects a cleartext packet with the same packet number as a forthcoming 1-RTT packet, causing disagreement between the peers about whether subsequent packets were actually received.  This causes data loss after the handshake is complete by leaving a hole in the received data stream.

**Comment by nibanks** [comment]
That is not what the spec currently says:
```
8.15.3.  ACK Frames and Packet Protection

   ACK frames that acknowledge protected packets MUST be carried in a
   packet that has an equivalent or greater level of packet protection.
```
Personally, I believe ACK'ing the client finished in either handshake or 1-RTT encrypted packet should be allowed; though if I were to have to pick one, I'd prefer to go with the 1-RTT encrypted.

**Comment by huitema** [comment]
If we want a defense against the clear text injection attack, then we need a better behavior. Because if the source has sent an 1RTT packet, and receives a clear text ACK of the same packet number, that's a protocol error and the connection will be closed. So much for DOS resistance.
