### ISSUE TITLE
Soliciting acks of acks

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#836]
```   A receiver that is only sending ACK frames will not receive
   acknowledgments for its packets.  Sending an occasional MAX_DATA or
   MAX_STREAM_DATA frame as data is received will ensure that
   acknowledgements are generated by a peer.  Otherwise, an endpoint MAY
   send a PING frame once per RTT to solicit an acknowledgment.
```

If we think this is useful, we should add a flag to ack that says "ack this".

**Comment by huitema** [comment]
I would take a very deep breath, or run a couple miles, before proposing adding new flags to the ACK syntax. We already have a ready-made flag -- just add a one-byte PING after the ACK. @ekr , the text that you quoted just points out that in normal operation, even a "pure receiver" will need to send a steady stream of flow control updates, which is sufficient in practice to cause regular ACK of ACK.

**Comment by janaiyengar** [comment]
I don't think we need this. I agree with @huitema, this functionality is already available. From a transport perspective, I don't think there's value in this.

**Comment by ianswett** [comment]
Agreed, we should not do this.

**Comment by ekr** [comment]
Well, either it's "this happens anyway" or it's "you need to ask for it explicitly". If it's the latter, then it's goofy to have to add some other frame to get it, especially because the code that generates frames has no knowledge of how they will be marshalled into packets.

**Comment by huitema** [comment]
Well, my implementation generates ACK "on the fly" as part of sending packets, so I know exactly in which packet the ACK is sent and can easily add a PING if that's really needed. But even if the PING was sent in the next packet, you will still get a cumulative ACK that will "ACK the ACKs".

**Comment by janaiyengar** [comment]
Discussed at the editors meeting. If someone really wants this, please reopen, but we believe this is resolved with existing mechanisms (PING).
