### ISSUE TITLE
Version negotiation responses and FNV-1a protection

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#840]
Reading the specs, it wasn't clear to me that version negotiation responses are not protected by FNV-1a. This should IMO be explicitly called out.

draft-tls says

> QUIC adds an integrity check to all cleartext packets.

and draft-transport says

> Cleartext packets are sent during the handshake prior to key negotiation.

Neither if which made it obvious to me that a version negotiation response was excluded.

(And out of curiosity - why isn't there an FNV-1a? Seems like an odd special case?)

**Comment by jpinner-lyft** [comment]
Not saying that this couldn't be more clear in the spec; however, Sec. 5.3 defines the version negotiation packet and Sec 5.4 defines the "cleartext" packets and list the requirement for including an integrity check. Subsections 5.4.1 through 5.4.4 then define the four "cleartext" packets.

Again I agree that the fact that the spec defines "cleartext packets" as not all packets that are not encrypted is confusing.

Does this become moot point if FNV-1a is replaced with an AEAD cipher?
