### ISSUE TITLE
Long header variants for 1-RTT protected packets

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#848]
These should be removed for (at least) two reasons:

Firstly, there should only be one way to do anything, if possible.  This makes it possible to encode the same information two ways.

Perhaps more substantially, because it would make WebRTC easier.  In discussions about using QUIC for WebRTC, we found that there were several options for multiplexing designs that are feasible with QUIC.  One of the most difficult parts of that was ensuring that once the handshake was complete, QUIC packets could be distinguished easily from other packets.  

I think that during the handshake people are prepared to rely on checksums, and other such things, but in the steady state demultiplexing on the first octet would be ideal.  See [RFC 7983](https://tools.ietf.org/html/rfc7983) for more about this.

Right now, the two 1-RTT protected long header encodings collide with RTP and need more sophisticated handling to correctly identify.  Some tweaking of the type field might avoid that, but it could preclude greasing and effectively constrain what we can do with QUIC.  It would be easier to rely on the packets using the short header.  The short header only potentially collides with DTLS (which would not be used in this case) and STUN (which are infrequent enough that they can use the STUN hash or magic number to identify correctly - something Google already do).

@pthatcherg or @aboba can expand on the reasons, or explain some of their alternative designs.

**Comment by mikkelfj** [comment]
I has always bothered me that the choice of short/long headers was arbitrary.

**Comment by csperkins** [comment]
This is also issue #426

**Comment by ianswett** [comment]
Sounds good, I can't come up with a reason to keep them.

**Comment by martinthomson** [comment]
This might help with #426, but maybe not completely.  Short headers still potentially conflict with ZRTP, for example.  I'd keep #426 open even if we resolve this.

**Comment by ianswett** [comment]
If we really care about conflicting with WebRTC during the handshake, we have enough long header codepoints to avoid those codepoints in QUIC.  I'd prefer not to avoid codepoints post-handshake, however, since that eliminates the possibility of post-handshake type byte greasing.

**Comment by janaiyengar** [comment]
There is a good reason for this to exist: out-of-band key negotiation. I'll remind folks that transport negotiation is distinct from the TLS handshake -- we've taken pains to try and keep TLS separate from QUIC -- and you might have 1-RTT keys available when you are starting your transport connection.

On demuxing WebRTC and QUIC packets, that is a separate conversation. I outlined a couple of ideas in #426 and we could have that conversation separately, although we did agree in Paris that we'd add a framing layer if necessary later and closed the issue.

**Comment by martinthomson** [comment]
Why can't the client use the Initial packet for its first packet in that case?  That would ensure that the server can generate a Version Negotiation packet if it needs to.

It's very hard to know what your design is - you seem to assume a particular design, but since we aren't discussing it in any detail, I don't know whether you actually *need* these long-form packets.

**Comment by martinthomson** [comment]
Oh, I forgot to add: If you really need these, then your out-of-band key negotiation variant of QUIC is welcome to define them.  (Again, assuming that you have a different version number so that this is possible.)

**Comment by janaiyengar** [comment]
Having thought about this some more, it's actually ok to do this. It's not "my variant" of QUIC, it's a general use case that uses out-of-band key exchange. I've tried to explain this in the past. But since  0-RTT and 1-RTT keys can be the same, any such use of QUIC can treat 0-RTT and 1-RTT packets differently except use the same keys for both kinds. Which makes it ok to remove 1-RTT long headers.

Separately, please, please, don't rush to close out design issues in a rush. This was under discussion, and really should have been discussed more before closing.

**Comment by janaiyengar** [comment]
We also have a merge-imminent label for exactly things like this. I wasn't expecting the merge to happen without the discussion finishing so I'm quite surprised to see this happen.
