### ISSUE TITLE
Remove initial packet number randomization

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#850]
With the resolution of #693 we no longer need initial packet numbers to be randomized.

**Comment by mcmanus** [comment]
my PR for this conflicted with #824 so I made the PR be for that branch and it can close both issues (this and #823) if accepted.

**Comment by marten-seemann** [comment]
After some discussion at the Singapore Hackathon: The reason why #693 solves this, is because the client-chosen connection ID is used for the AEAD. This also applies in the case where the server directly replies with a Cleartext and uses a server-chosen connection ID.

**Comment by janaiyengar** [comment]
On whether initial packet number should be 0 or 1, with the new packet number encoding, we end up needing only 62 bis for the packet number, which means you can use a signed int for representing it and < 0 as a sentinel value. I'll be ok with either 0 or 1 as the initial value.

**Comment by ianswett** [comment]
Q on this.  Should we allow using other initial packet numbers to make sure middleboxes don't assume all handshake packets are <20 or some magic number?

Admittedly, the type byte is a lot more useful than packet number to identify handshake packets, but it's worth considering.

Besides that, I'm greatly in favor of this and would like it to land ASAP.
