### ISSUE TITLE
Use immediate close for application close

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#854]
At the Seattle interim we concluded that it was important to signal a close to intermediaries (those that have the keys, that is).  This allows application endpoints to reach an agreed close state and then terminate the transport without leaving the middlebox on a timer.

In short, once the application protocol has reached a terminal state, it will signal using APPLICATION_CLOSE (some code, maybe NO_ERROR).

**Comment by RyanAtGoogle** [comment]
Does this preclude silent close?

**Comment by martinthomson** [comment]
I think that the sort of close you have in mind relies on the timeout.  That is, neither side explicitly closes the connection, but they just don't get back to it.

What this covers is more the case where you have agreed to finish a certain set of requests - for example - and you are probably actively exchanging data up to the point where you are done.  This says that if you want to drop the idle timer, you need to send a message (see the issue for more discussion on why that might be needed).

**Comment by RyanAtGoogle** [comment]
Gotcha. Thanks!
