### ISSUE TITLE
Design team for ECN and/or timestamp design team

### ISSUE THREAD

**Issue by IngJohEricsson** [quicwg/base-drafts#856]
Unless something around this is already planned for.. (and not sure if this post fits in this issue-tracker )
I will attend IETF-100 and would be very much interested to get in contact with others who are interested to discuss the format of the ECN fields and timestamps in the ACK frames. 
Drop a note if you are interested, alternatively point to the proper contact personsif it a discussion group is already effective.

**Comment by martinthomson** [comment]
Feel free to use the quic@ietf list or the [wiki](https://github.com/quicwg/base-drafts/wiki) to coordinate this sort of activity.
