### ISSUE TITLE
Normative downrefs in recovery

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#858]
idnits reports:
```
  ** Downref: Normative reference to an Experimental RFC: RFC 4653
  ** Downref: Normative reference to an Experimental RFC: RFC 5827
```

These are not in the [downref registry](https://datatracker.ietf.org/doc/downref/), so we should be careful to get consensus that a downref is appropriate.

(Not sure if this is editorial or design.  Marking as design because it probably needs consensus.)

**Comment by janaiyengar** [comment]
We will make the refs informative.
