### ISSUE TITLE
Clients don't drain after stateless reset

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#867]
I think that this was just an error.  A stateless reset isn't necessary singular: the server might send multiple as it receives multiple packets.  So it makes sense for the client to stick around and absorb packets for a while.

**Comment by ekr** [comment]
I think this needs to be re-opened. See my comments in #868

**Comment by ianswett** [comment]
I tend to agree.  There is nothing useful the client can do after receiving a stateless reset and there's nothing to send.

The most complex case I can imagine is a client using the same port for multiple QUIC connections, so the port is still listening.  In such a case, it would have to continue discarding incoming stateless reset packets, but that's true of any 'junk' packet not associated with an open connection.

**Comment by ianswett** [comment]
Ok, closing this because EKR already opened #871
