### ISSUE TITLE
Fill in changelog for -07 drafts

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#875]
I spent all my time trying to work out why circle wouldn't build and neglected to fill in the change logs.  These can be back-filled.

**Comment by janaiyengar** [comment]
@martinduke notes that we should note timestamp deletion.

**Comment by ianswett** [comment]
Timestamp removal noted.  Is there anything else?

**Comment by mcmanus** [comment]
duplicate transport parameters are now an error
