### ISSUE TITLE
max_data and max_stream_data are inconsistent with transport params

### ISSUE THREAD

**Issue by siyengar** [quicwg/base-drafts#895]
max_data and max_stream_data seem to be inconsistent between the stream flow control and transport parameters 

In transport params they are encoded as 32 bit values and in  the MAX_STREAM_DATA it is a 64 bit value. Similarly now MAX_DATA is a 64 bit value in octets, however initial_max_data is a 32 bit value expressed in KB. It's not a big deal to implement, but just a bit weird.

**Comment by martinthomson** [comment]
I think that the intent was to specify both in the same units, and one got missed by both patch author and editors.  I'll fix that.

**Comment by martinthomson** [comment]
Oh, I missed the 32/64 thing.  I agree that it's odd.  Then there's the possibility of using a varint.  I await feedback from implementers on this one.

**Comment by siyengar** [comment]
I implemented 32/64, and it wasn't too bad, since these parsers are necessarily different, and 32 bits should technically be enough even for connection flow control since this is just an initial offset, however it just seems that having these 2 be different is error prone.

**Comment by MikeBishop** [comment]
We don't have varint in transport params, and this seems fine.  The initial doesn't need to be as big as the max for the connection.
