### ISSUE TITLE
Remove references to QUIC Crypto

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#9]
...and as in #8, anything else that isn't relevant.

**Comment by martinthomson** [comment]
We probably don't need a reference to draft-hamilton-quic-transport-protocol either.  The document can instead say "The original authors of this specification were: Ryan Hamilton, ...".

**Comment by janaiyengar** [comment]
SGTM. I want to wait until after -00 for QUIC Crypto references, but I can remove draft-hamilton... from the text now.

**Comment by janaiyengar** [comment]
Looks like you've added a contributors section separately. Did you mean to leave the old Contributors and Acknowledgments sections in?

**Comment by martinthomson** [comment]
I've fixed the contributors stuff in #41.  I agree that we can wait for -01 for this issue.

**Comment by martinthomson** [comment]
Fixed by #122.
