### ISSUE TITLE
Stream open as a signal

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#901]
We currently don't allow for an empty STREAM frame unless it closes the stream.  But that prevents mapping of TCP-based protocols that rely on the connection open as a signal to a server to start transmission.  In protocols where a server speaks first, the client initiates the connection (i.e., stream), and the opening of that connection/stream signals to the server to start sending.

Should we permit the sending of an empty STREAM frame at the beginning of a stream as well as the end?

**Comment by ekr** [comment]
Actually you could send MAX_STREAM_DATA.

**Comment by martinthomson** [comment]
That seems like a bit of an abuse.  We permit MAX_STREAM_DATA to open a stream only because it might be reordered ahead of STREAM/STREAM_BLOCKED.  On the other hand, we could put STREAM_BLOCKED in that same bucket if an empty STREAM frame was permissible - in other words, you might tolerate receiving STREAM_BLOCKED ahead of STREAM, but it's not the way you open a stream.

**Comment by ekr** [comment]
I don't disagree that it's a bit of an abuse. I'm just pointing out that the protocol permits it.

**Comment by ianswett** [comment]
This seems like a reasonable idea to me.  And yes, using MAX_STREAM_DATA or another frame is definitely an abuse, even if it is permitted.

**Comment by mcmanus** [comment]
I think martin's suggestion is the right thing to do - allow offset 0 to be empty

**Comment by nibanks** [comment]
I also think it seems reasonable to allow an offset 0 frame to be empty.

**Comment by ekr** [comment]
I'm fine with this, but then I'd still like to understand the status when
you *do* get MAX_STREAM_DATA and/or have an implicitly opened stream
because stream n+4 was opened.
