### ISSUE TITLE
in_flight inconsistency

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#903]
`OnPacketSentCC` is  not called for `is_ack_only` packets, which means that they don't increase `bytes_in_flight`.

However, when `bytes_in_flight` is reduced in `OnPacketAckedCC` and `OnPacketsLost`, no so such check is performed. This causes `bytes_in_flight` to eventually go negative.

**Comment by ianswett** [comment]
The packets_lost issue was fixed by PR #1223 and I just sent out PR #1248 to fix the rest.

**Comment by larseggert** [comment]
Good to close then
