### ISSUE TITLE
QUIC ack frames now store more than 255 ack ranges

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#906]
The existing text in the transport and recovery draft indicates QUIC ack frames can ack up to 255 ranges.  Now that we're using variable length integers, we can ack more than that.  

I'm not sure if that's a good thing or a bad thing, but at the least, we should update the text to be self-consistent.

**Comment by RyanAtGoogle** [comment]
More than 255 ACK ranges in a packet seems excessive to me. (Honestly 16 is probably fine). I'd be inclined to revert this field back to single byte and limit the number of ranges to 255.

**Comment by martinthomson** [comment]
There is value in uniformity.  No one has to *use* that many ranges (noting that 255 would be enough to overflow a packet anyway if abuse was the goal).

**Comment by ianswett** [comment]
Just because we use varints, doesn't mean we always have to, particularly for things which are only a byte.  Reading a byte is really not that difficult, so I think the uniformity value is minimal.

**Comment by ianswett** [comment]
Well, let's stick with this for now, but fix the text before 08 to make it consistent?
