### ISSUE TITLE
Applications and Stream IDs

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#910]
@nibanks previously proposed a QUIC API that didn't expose specific Stream IDs to applications.  That doesn't actually work for HTTP/QUIC as currently defined, but there are only two places where the HTTP/QUIC implementation needs to reference a Stream ID.

- PRIORITY frames reference requests by Stream ID.  The solution to this would be to expand #701 to use a Request ID for client-initiated requests as well as Push ID.  (At first glance, these don't need to be throttled since QUIC MAX_STREAM_ID effectively controls this.)
- The long-lived control stream is a specific stream ID.  This could be eliminated by putting a stream header (again, &agrave; la #701) on unidirectional streams that identifies them as control streams.  We still need the control stream to be unique to support order-dependent frames like PRIORITY.

If HTTP goes this direction, there's an associated question for the abstraction design team as to whether we want to explicitly recommend that the Stream ID is always an internal property of the transport.  (This would make it easier to make changes to Stream IDs and how they work in future versions, incidentally.)

**Comment by nibanks** [comment]
I'd like to qualify my proposal to say that the `stream = connection.OpenNewStream(type)` API would just internally create a new stream with the next available ID for the given type (unidirectional or bidirectional) and wouldn't indicate the Stream ID to the application by default. But instead there would just be a helper function on the Stream to query the ID, `stream.GetID()` for instance.

Would this be enough? Essentially that API would only support creating stream in order, as far as the ID space goes.

**Comment by MikeBishop** [comment]
I think that would be enough to implement HTTP/QUIC now, provided that the HTTP layer ensures the first created unidirectional streams are for the control streams.  So the question becomes whether there's a desire for more isolation than that in HTTP.

**Comment by martinthomson** [comment]
@MikeBishop, I think that making a change here would be helpful in resolving #1121.  Do you think that it is time to start talking about this again?
