### ISSUE TITLE
Dealing with unknown QUIC frames in a packet

### ISSUE THREAD

**Issue by siyengar** [quicwg/base-drafts#933]
QUIC frames are peculiar because peers who do not understand a QUIC frame, probably due to a custom frame being used, have to terminate the connection because they will not be able to process any frames in a packet after a frame they do not understand. So a new version needs to be added for each new custom frame. We have a huge version number space but this is a bit annoying to manage and creates a bunch of conditionals in the code to deal with different clients. 

There are many ways to probably solve this, including a special generic frame type that someone proposed (can't find the issue). Another way to potentially solve this is to have a common length field for all frames.  With draft-08 varints, the maximum size of a length field ever needed is 2 bytes (for a 1280 byte MTU). The most common quic frame types (acks and stream frames) have length fields of their own, and so it is only the uncommon ones like RSTs and window updates that this would add some overhead to.

This might make it easier to parse frames and also make it so that implementations can skip frames they do not understand. This is clearly only for non critical frame types, new frame types which are critical for communication should probably have some other negotiation mechanism which is frame specific.

**Comment by martinthomson** [comment]
See #58.
