### ISSUE TITLE
Coalescing in HTTP/QUIC

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#940]
As @LPardue notes, the draft currently omits any language about connection reuse.  We'll need text for that.  As a first pass, note that there is no way to directly address an HTTP/QUIC endpoint by URI/URL.  So an HTTP/QUIC endpoint is somewhat analogous to an HTTP/2 endpoint for an origin which doesn’t appear in the DNS record.

With that as our starting point, here are some thoughts:

- The only reason you’re speaking HTTP/QUIC for example.com in the first place is because you have an Alt-Svc record for example.com.  If you have Alt-Svc records for other origins that happen to share the same certificate pointing to the same host:port, this should be coalesced.
    - It seems a pity that you would need to speak individually to each origin for this.  Coincidentally, Ben Schwartz and I were having a conversation about reviving Alt-Svc records in DNS….
- In the absence of Alt-Svc records, draft-ietf-httpbis-origin-frame permits coalescing in HTTP/2 based on the combination of the server’s possession of the correct certificate and assertion that it wants the traffic.  Like #371, there would need to be a very short draft that defines the ORIGIN frame for HTTP/QUIC as Exceptionally Similar™ to the one in draft-ietf-httpbis-origin-frame.

**Comment by LPardue** [comment]
Is #794 (SNI requirement for HTTP/QUIC) related?
