### ISSUE TITLE
Do you need to supply max_early_data in NST to enable 0-RTT

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#942]
In TLS 1.3, servers have to opt-in to early data by sending "max_early_data". We need to clarify whether this is required in QUIC. I believe @martinthomson 's view is "no" but we need to decide one way or the other.

**Comment by martinthomson** [comment]
We should be clear about this, but the intent is to use the connection-level flow control window advertised in the transport parameters that are attached to the session ticket.

**Comment by martinthomson** [comment]
Oh, we also agreed that max_early_data was needed to signal that the server is willing to accept 0-RTT.  We probably need to say that too.

**Comment by ekr** [comment]
So you would say max_early_data = what?

**Comment by martinthomson** [comment]
Anything non-zero would work.  Maybe 1.

**Comment by ekr** [comment]
I would suggest 2^{32}-1, because that signals  "TLS is OK with anything"

**Comment by martinthomson** [comment]
WFM

**Comment by huitema** [comment]
Yes, 2^{32}-1 is actually what picoquic is sending.

**Comment by martinthomson** [comment]
We fixed this in b7aec9afdfcc24e664b1ba8c0f8403387cae98b8.
