### ISSUE TITLE
CONNECT

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#95]
Need discussion of how CONNECT works.  Initial thought:

 - Client does not close data stream after sending request
 - If server responds (on the message control stream) with success, the data stream is being relayed into a TCP connection by the server.

Is there a QUIC-CONNECT?  (Probably not, and almost certainly not in this document.)

**Comment by mnot** [comment]
Discussed in Tokyo; some doubt about the usefulness, but Chrome + Google Data Saver expresses interest in using it. If semantics are different than normal HTTP CONNECT, it's not CONNECT...

Leaving open for later discussion.

**Comment by MikeBishop** [comment]
@mnot - given the new semantics, does this still need to be open?  We have a proposal in the draft that preserves the semantics of HTTP CONNECT, and we have a use case.

**Comment by mnot** [comment]
If you think it's ready to determine consensus, close it.
