### ISSUE TITLE
Specify QUIC protocol fallback to TCP.

### ISSUE THREAD

**Issue by emile22** [quicwg/base-drafts#954]
Fallback is used by the endpoints when a QUIC connection fails.
The protocol specification should define when QUIC fallback occur (establishment, during the live time of a connection...) and detail how it works (delay before attempting to reconnect in QUIC ...).

**Comment by marten-seemann** [comment]
I don't think fallback to TCP should be part of the protocol specification. **Some** applications might use such a fallback for **a limited amount of time**. Other applications might choose to deploy QUIC-only right from the beginning.

**Comment by LPardue** [comment]
I think there are significant drawbacks to mandating or specifying TCP.

1) Application mapping such as DNS/QUIC don't naturally fullback to TCP.
2) TCP fullback maybe reflects a simple view where a host just advertises itself as a HTTP/QUIC alternative. More complex deployment may Alt-Svc to other hosts that listen on UDP only. The network path to such hosts may be configured for UDP only.
3) For HTTP/QUIC, fallback is really a function of Alt-Svc fullback. I.e. fallback to the origin that advertised the HTTP/QUIC endpoint. Strategies for this in Alt-Svc are loosely defined and I would say are implementation specific.
4) TCP fullback is a security consideration. Attack vectors such as version downgrade may become more attractive if standardised. In a scenario where QUIC is a prime transport protocol and receives continued security evolution, fallback to TCP (and TLS packet protection) requires effort to maintain equivalent security.

**Comment by martinthomson** [comment]
Fallback to TCP isn't a property of QUIC.  As others have said, the protocol that uses QUIC might vary in its requirement.

HTTP/QUIC uses alternative services to upgrade, so naturally it means that TCP is used as part of the bootstrapping process and TCP connections will be used if the QUIC-based alternative goes away.
