### ISSUE TITLE
Is fallback to TCP part of QUIC invariant ?

### ISSUE THREAD

**Issue by emile22** [quicwg/base-drafts#955]
Currently QUIC headers don't provide the information for on-path troubleshooting of the network performance. When the QoS decreases badly endpoints fallback from QUIC to TCP. This behavior enable network troubleshooting  with legacy TCP monitoring tools. 
Will the endpoints support the fallback to TCP for all the versions of the QUIC protocol  ?

**Comment by ianswett** [comment]
This is not an invariant.  There already are cases when QUIC does not need to fall back to TCP on private networks.
