### ISSUE TITLE
Handshake packets should be retransmitted based on the last sent handshake packet

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#962]
Instead of using time_of_last_sent_packet, handshake packets should use time_of_last_sent_handshake_packet(to be defined), because if the handshake hasn't completed, protected packets will not be acknowledged, because they cannot be decrypted and processed.  The only other valid frames to send pre-handshake are acks and connection close.  Acks do not cause an acknowledgement and connection closes are terminal.

**Comment by siyengar** [comment]
+1, this is a follow up to my comment in your PR?
