### ISSUE TITLE
congestion control in bytes, but pacing advice in packets

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#967]
"QUIC congestion control is specified in bytes due to finer control and the ease of appropriate byte counting" 

.. and then later ..

"In order to fairly compete with flows that are not pacing, it is recommended to not pace the first 10 sent packets when exiting quiescence."

Can we reasonably reword that advice into bytes? 10 MTU worth?

**Comment by janaiyengar** [comment]
I think that entire para needs rewriting, I'll give it a go.
