### ISSUE TITLE
Version Negotiation + TLS

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#97]
The QUIC-TLS spec currently says that the server should select a protocol without regard to the current QUIC version, and MAY (not MUST?) do Version Negotiation if the selected protocol can't be carried by the current QUIC version.  However, if the server does Version Negotiation, the client's ClientHello gets thrown away, and the client has to resend the ClientHello anyway.

I'd be more inclined to say that servers select application protocols compatible with the current version if it can.  There are then two possibilities:

  - Client learns that server supports a newer version in the response.  Then the client can try again (in parallel or in the future) over the newer version.  Same RTTs to reach the new version/protocol, but able to exchange some data on the initial connection 1 RTT sooner.
  - Server supports no protocol compatible with the client's supported version, and triggers Version Negotiation anyway.  Same RTTs to reach the new version/protocol.

**Comment by MikeBishop** [comment]
#99 & #122 address this in the same way -- app protocols MAY restrict which version are acceptable, but tokens aren't version-specific.

**Comment by mnot** [comment]
Discussed in Tokyo; seems reasonable.

**Comment by martinthomson** [comment]
Closed as part of #122.
