### ISSUE TITLE
Make initial_max_stream_id_x optional

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#970]
Out of discussion in #958, making initial_max_stream_id_x optional would allow for setting a value of zero.  The current definition requires a valid stream ID, which prevents the minimum being set so that no streams are permitted.  Having no streams as a default might seem crazy, but it is most efficient.

**Comment by martinthomson** [comment]
Also, it's not especially crazy to omit the values, because MAX_STREAM_ID can be sent after the handshake is complete.  It is crazy to omit the values for 0-RTT though.

**Comment by janaiyengar** [comment]
I prefer to have explicit intent with max_stream_id of 0 in transport params, but this works too.
