### ISSUE TITLE
Specify new error type, "closed by peer"?

### ISSUE THREAD

**Issue by huitema** [quicwg/base-drafts#973]
The updated text in Section 7.9.3, "Immediate Close" states that: "_After receiving a closing frame, endpoints enter a draining period. An endpoint that receives a closing frame MAY send a single packet containing a CONNECTION_CLOSE frame before entering a draining period, but MUST NOT send further packets, which could result in a constant exchange of closing frames until the closing period on either peer ended_."

That's fine, but what error type should the peer use? No error? Should we specify a "closed by peer" error type?

**Comment by MikeBishop** [comment]
I think we'd discussed using NO_ERROR for this.  0x0 is analogous to STOPPING, used on a stream in response to a STOP_SENDING.
