### ISSUE TITLE
STREAM_ID_BLOCKED and distinguishing unidir/bidir

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#979]
Now that we have unidirectional streams, how is the receiver of a STREAM_ID_BLOCKED frame supposed to tell which stream type to send a MAX_STREAM_ID for? Or is there an assumption here that raising MAX_STREAM_ID applies to both unidir and bidir streams?

**Comment by ianswett** [comment]
A given stream ID refers to exactly one stream, which is either uni or bidi, not both.

**Comment by larseggert** [comment]
Right, but since STREAM_ID_BLOCKED doesn't contain an ID, the receiver doesn't know which limit to raise. When you *receive* a MAX_STREAM_ID, you know for which type it is, but when you receive a STREAM_ID_BLOCKED,  you don't.

**Comment by MikeBishop** [comment]
#927 / #928 already addresses this, albeit as an accidental by-product.

**Comment by larseggert** [comment]
Perfect, thanks
