### ISSUE TITLE
Consistent use of the term protected packets

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#994]
QUIC TLS 08 sec. 5.3 claims that clear text packets are protected by AEAD with a key derived from the connection ID. This is correct, but later the TLS document uses the terminology protected and unprotected to distinguish between cleartext packets and 1-RTT protected packets.

The transport document refers to all packet types as being protected by some key, except for version neg, and stateless reset. This is correct, but the terminology does not match the TLS unprotected terminology. Also, the term cleartext is a bit vague at this point.

I realize this is likely a left-over from before cleartext packets became protected and rephrasing the entire QUIC TLS doc probably isn't top priority in the editing process.

**Comment by seanturner** [comment]
We'll definitely do a sanity check before we're done.  This is noted.
